### ISSUE TITLE
Calling out to linux from DOS drivers ?

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#1003]
Is it possible to implement something in DOS that calls out to code in Linux ?

Is DOSEMU or FDPP the best place to do it ?

I was trying to work out if it's possible to implement a display driver in GEM that would output to actual windows in Linux, a bit like the seamless display drivers in virtualbox for Windows ?

**Comment by stsp** [comment]
I am not sure what are you trying to do,
but the direct calls are of course not possible.
You need to implement a plugin for dosemu2
that hooks for example some int0xe6 calls,
and does the work implementing things on
top of the host calls.
HTH.

**Comment by stuaxo** [comment]
Thanks for the info.

**Comment by jschwartzenberg** [comment]
Possibly something like virtio-vsock could be a generic way to implement this kind of communication: https://wiki.qemu.org/Features/VirtioVsock

**Comment by stsp** [comment]
dosemu has nothing to do with virtio.
Do you really expect someone to
implement pci virtio transport and
posix sockets on top, under dos?
Or virtio-pci support under dosemu,
plus vhost backend? You gotta be
kidding.

**Comment by jschwartzenberg** [comment]
I don't know how much code would need to be written (or copied/linked against), but with such a solution a display driver like that for GEM could work for QEMU as well without modification.

**Comment by stuaxo** [comment]
I wouldn't worry too much as it's a spare time thing, so not sure how much progress there will be. 

The next thing I'm going to look at is how GEM display drivers work - I had a bit of a look at some docs the other day and there don't seem to be that many calls.

Unfortunately most of the sites with info on GEM are blocked at work.

**Comment by stsp** [comment]
> a display driver like that for GEM could work for QEMU as well without modification.

Pfft, who told you that?
Don't make me angry. :)
If you would at least say "virtio-gpu" rather
than "virtio-vsock", that could at least make
some sense.

**Comment by jschwartzenberg** [comment]
That depends on how GEM works. If the individual windows could be handled and passed along a channel and then with some conversion be displayed by an X11 server, we're not talking about a typical display device.

**Comment by stsp** [comment]
virtio-gpu is exactly about that.
It is not bound to any physical gpu.
It only allows you to create surfaces
on host and then display them wherever
you want.
And virtio-vsock has absolutely nothing
to do with this all. Its just a host sockets
to linux guest.

**Comment by jschwartzenberg** [comment]
Wow, I was not aware of that! Thanks! Finally I understand the difference between virtio-gpu and QXL!

I'll be looking forward to a win31 virtio-gpu driver now ;) I think winos/2 had this feature as well?

**Comment by stsp** [comment]
Maybe you can create a virtio-gpu driver
for win31, but before that, you'll need to
create a PCI support there (and virtio
support in dosemu2).

**Comment by jschwartzenberg** [comment]
Or first use the driver with QEMU ;)
It is quite likely that will only work well with emulation though.

At least win9x is still notable to be unstable with QEMU+KVM and given their priorities it's not unlikely win31 would be as well.

**Comment by stsp** [comment]
Even qemu doesn't give you the PCI
support in win31. Maybe you can find
some hacky PCI driver though, I know
you can find a lot of things.

virtio-vsock doesn't have the memory
sharing, which is essential for gfx.

**Comment by jschwartzenberg** [comment]
> Even qemu doesn't give you the PCI
> support in win31. Maybe you can find
> some hacky PCI driver though, I know
> you can find a lot of things.

I don't get why PCI is standing out here. Isn't that part of any display driver for win31? There are many different display drivers for win31 for cards on all kinds of buses ISA, PCI and even some less common ones.

**Comment by stuaxo** [comment]
Thanks for answering the memory sharing question, I was thinking that sending all this info via a socket would be slightly painful (have to build some sort of simple protocol).

Memory sharing makes things a lot more straightforward.

**Comment by stsp** [comment]
> I don't get why PCI is standing out here. Isn't that part of any display driver for win31?

In win31 - possibly, but that likely assumes
there is only one such a driver in a system.
PCI has a very archaic design, and controlling
it from multiple ring3 drivers (in win31 the
.drv drivers are ring3) may be racy.

**Comment by jschwartzenberg** [comment]
That's interesting. Are you suggesting that win31 would be less stable with both graphics and ethernet drivers being for PCI hardware which is not uncommon? And that switching either (or both) to ISA hardware would make things more stable? What about win9x?

**Comment by stsp** [comment]
> drivers being for PCI hardware which is not uncommon?

In what century?
Plus they may have the ring0 PCI driver
(which we do not support).

> What about win9x?

I hope it has the ring0 PCI driver but I
don't know for sure.

**Comment by jschwartzenberg** [comment]
Whenever someone virtualizes/emulates or runs win31 on something from the late win31 era. They will likely have something along the lines of an S3 Virge DX and an RTL8029.
