### ISSUE TITLE
Printing problem

### ISSUE THREAD

**Issue by widhaya3** [stsp/dosemu2#1008]
**Describe the bug**
A description of what the problem is.
Cannot print to network printer.

**To Reproduce**
Steps to reproduce the behaviour:
in `/etc/dosemu/dosemu.conf`
> ...
> $_lpt1 = "lpr -l -P epson_schai"
> ...

run with command:
> dosemu -O 2>x.txt

in file `x.txt`
> ...
> CONF(LPT0) f: -l -P epson_schai   c: (null)  t: 20  port: 0
> ...

run in dosemu:
>C:\echo 'abc' > lpt1:

error in file 'x.txt'
> ERROR: LPT1: error opening -l -P epson_schai: No such file or directory
> ERROR: Error opening printer 0
> ... (same error as above for 8 lines)...

**Attach the binaries or provide an URL**
If the problem needs specific DOS files to reproduce, please attach
or provide the download URL.

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.
> Package info:
> dosemu2: installed
> dosemu2 2.0~pre8-2
> fdpp: installed
> fdpp    0.1~beta9-1

**Comment by stsp** [comment]
Thanks, should now be fixed.

**Comment by widhaya3** [comment]
Sorry, the problem is back in latest devel.

**Comment by widhaya3** [comment]
`$ ERROR: LPT1: lpr: No such file or directory`

**Comment by stsp** [comment]
Different error msg.
Check if lpr still works from command
line.

**Comment by widhaya3** [comment]
Sorry again. It's my fault, miss config printer in `dosemu.conf`.
Thank you so much.
