### ISSUE TITLE
dosemu + fdpp: ms-dos command.com does not "find" fdppauto.bat

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/dosemu2#1013]
**Describe the bug**
command.com from MS-DOS 7.1 (Win98 SE) claims that it cannot find fdppauto.bat

**To Reproduce**
just start dosemu with command.com of MS-DOS 7.1

The problem is most likely due to the standard FDPPAUTO.BAT using LFs instead of the CR/LF combination as EOL markers. If I rewrite the file with a DOS editor, the LFs will be substituted by CR/LF and command.com has no problems running fdppauto.bat anymore.

**Comment by stsp** [comment]
This is intentional.
We provide config.sys and autoexec.bat
for other doses. I assume the problem
you faced, was caused by manually
copying fdppconf.sys to C and
renaming it to config.sys, which of
course should not be done.

**Comment by Baron-von-Riedesel** [comment]
> This is intentional.
That's a very strange intention IMO.

> was caused by manually copying fdppconf.sys to C

No. I did not even mention fdppconf.sys or config.sys in my post.
I talked about FDPPAUTO.BAT, which is a parameter to COMMAND.COM (the /k option).

**Comment by stsp** [comment]
Its a parameter that is set in fdppconf.sys
and nowhere else.
