### ISSUE TITLE
SLDT (and probably STR) cause a GPF

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/dosemu2#1017]
**Describe the bug**
When launching the simple tool DPMI.EXE included in HX (it has to be renamed to be launched because there exist another DPMI program in DOSEMU which apparently has super-high priority), it is terminated with a GPF when instruction SLDT is about to be executed.

**To Reproduce**
rename DPMI.EXE to DPMI_.exe and run it.

**Attach the binaries or provide an URL**
https://github.com/Baron-von-Riedesel/HX/blob/master/bin/HXRT219pre.zip
DPMI.EXE is in sub-directory TEST.

**Attach the log**
hardly needed, is it?

**Comment by Baron-von-Riedesel** [comment]
btw, it's quite intransparent to prevent a program from running because it has the "wrong" name. This really is to be improved.
Another case: when I try to run Windows 3.1 in dosemu, I type:
C:\\>cd Win31
C:\\>system\krnl386

and get a quite confusing "help" screen showing me the usage of "SYSTEM"!?

**Comment by stsp** [comment]
> hardly needed, is it?

Of course -D9+M log is needed: it will
show what exactly instruction GPFed.
Note that SLDT itself can GPF.

> and get a quite confusing "help" screen showing me the usage of "SYSTEM"!?

Not sure what do you mean by that.
For me it just starts windows.
But knowing your games with configs,
nothing is surprising.

**Comment by Baron-von-Riedesel** [comment]
> But knowing your games with configs, nothing is surprising.

Sorry,but this is wrong. The error that I described with MS-DOS command.com appears just by copying the file into the dosemu drive_c directory. There is no need to change or copy any config.sys or autoexec.bat files.

**Comment by Baron-von-Riedesel** [comment]
[boot.log.zip](https://github.com/stsp/dosemu2/files/4245557/boot.log.zip)

**Comment by stsp** [comment]
Doesn't command.com check the DOS
and prints incorrect DOS version if its not
MS-DOS? But I suppose fdpp reports
"DOS 7.10", which is why command.com
thinks its OK. I think we should report
some unrealistic version instead.
Could you check that patch to fdpp?
```
diff --git a/hdr/version.h b/hdr/version.h
index dc3bdc7..14225c4 100644
--- a/hdr/version.h
+++ b/hdr/version.h
@@ -28,7 +28,7 @@
 
 /* The version the kernel reports as compatible with */
 #ifdef WITHFAT32
-#define MAJOR_RELEASE   7
+#define MAJOR_RELEASE   10
 #define MINOR_RELEASE   10
 #else
 #define MAJOR_RELEASE   6
```

I hope it will trigger incorrect DOS version
on your command.com, avoiding the problem.

**Comment by stsp** [comment]
Yes, the log shows GPF comes from
`0f 00 c0                sldt   eax`.
We need to emulate sldt.

**Comment by Baron-von-Riedesel** [comment]
> But I suppose fdpp reports "DOS 7.10", which is why command.com thinks its OK. 

Perhaps, but MS-DOS command.com also works with the FreeDOS kernel.sys.

**Comment by stsp** [comment]
kernel.sys reports the same DOS version
as does fdpp. I don't suppose any other
command.com, eg from DOS-6.22, is
going to work.

**Comment by stsp** [comment]
I renamed dpmi.com to emudpmi.com to
avoid clash with your prog.

**Comment by stsp** [comment]
I added a very hackish impl into the sldt branch.
Please see if it work. It is completely untested
because on AMD CPU sldt never GPFs.

**Comment by Baron-von-Riedesel** [comment]
> because on AMD CPU sldt never GPFs.

I have a Ryzen cpu and can easily make SLDT cause a crash. All it needs is to set the so-called UMIP flag in CR4 (bit 11), switch to ring 3 protected-mode and then execute it. But UMIP is implemented on rather new cpus only.

**Comment by stsp** [comment]
Yep, maybe on ryzen, but I have FX.
So please test the patch. :)

**Comment by Baron-von-Riedesel** [comment]
I tried but found no difference.

I also looked at the hack. That's really ugly. Even if it works, there will be another GPF soon after when DPMI.EXE executes a "STR AX" instruction.

Can't you just tell KVM to let all these opcodes (SMSW, SGDT, SIDT, SLDT, STR ) pass without exception?

[boot.log.zip](https://github.com/stsp/dosemu2/files/4251286/boot.log.zip)

**Comment by stsp** [comment]
DPMI is not using KVM by default (yet).
And if you enable it, it will most likely
already pass them w/o exception.

**Comment by Baron-von-Riedesel** [comment]
I tried the patch now ( really, my previous attempt was incorrect because I didn't change to sldt branch. I behaves differently, instead of a GPF it does now loop/hang, and displaying:

```
DPMI: 0f opcode
DPMI: cs=0xa7, ss=0xaf, ds=0xaf, es=0xaf, fs=0, gs=0 ip=0xbb2
DPMI: switch to dpmi
DPMI: Return to client at 00a7:00000bb2, Stack 0xaf:0x000026c6, flags=0x93202
DPMI: switch to dosemu
DPMI: cs=0xa7, ss=0xaf, ds=0xaf, es=0xaf, fs=0, gs=0 ip=0xbb2
DPMI: 0f opcode
DPMI: cs=0xa7, ss=0xaf, ds=0xaf, es=0xaf, fs=0, gs=0 ip=0xbb2
DPMI: switch to dpmi
DPMI: Return to client at 00a7:00000bb2, Stack 0xaf:0x000026c6, flags=0x93202
DPMI: switch to dosemu
DPMI: cs=0xa7, ss=0xaf, ds=0xaf, es=0xaf, fs=0, gs=0 ip=0xbb2
DPMI: 0f opcode
DPMI: cs=0xa7, ss=0xaf, ds=0xaf, es=0xaf, fs=0, gs=0 ip=0xbb2
```

**Comment by bartoldeman** [comment]
yes setting `$_cpu_vm_dpmi = "kvm"` enables kvm for DPMI. The KVM code doesn't set the UMIP flag in CR4, so it should not trap (in fact the KVM code makes the VM pretend to be like a classic Pentium without even support for MMX -- that could be increased a little, particularly MMX is easy, but very few DOS apps know about SSE or even MMX. The CPU emulator does not emulate MMX at all).

DOSEMU2 is even mentioned in that context here:
https://lwn.net/Articles/735443/

**Comment by stsp** [comment]
The hang is that because I forgot
to increment eip by 3. You can do
that yourself as I am having internet
connection problems now.

**Comment by stsp** [comment]
Yeah, the guy at aforementioned
url was spamming the dosemu ML
with umip patches (like 50 mails
in a day), causing most people to
unsubscribe.

**Comment by Baron-von-Riedesel** [comment]
Ok, it runs now without GPF, althouth the values returned are pretty implausible.

**Comment by stsp** [comment]
Do they match the dpmi_ldt_alias
value (you can print it with printf()
or error()), or is there a bug with
returning?

**Comment by Baron-von-Riedesel** [comment]
> Do they match the dpmi_ldt_alias value...
Yes, it's 0xE7. Well, DPMI.EXE just reports those values, although, IIRC, neither LDTR nor TR can be loaded with a LDT/TSS descriptor in a LDT.

**Comment by stsp** [comment]
The only other option is probably to return 0.
And that's actually simpler, so I prefer that.

**Comment by stsp** [comment]
So will it be OK if I just return 0?

**Comment by Baron-von-Riedesel** [comment]
> So will it be OK if I just return 0?
I guess so - all that matters is that it won't GPF.

**Comment by stsp** [comment]
Should now be fixed.
But github seems down, so neither the
ticket is closed automatically, nor the
travis build run.

**Comment by andrewbird** [comment]
Might this be useful https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/cpu&id=b91e7089ae70d2f7c81a4456e5b78fef498663d9 ?

**Comment by stsp** [comment]
Quite sad they did that in the kernel,
and not in wine. :(
And I am a bit surprised that win32
apps do sldt...
