### ISSUE TITLE
Keyboard cmd f0 not returning ACK

### ISSUE THREAD

**Issue by jwt27** [stsp/dosemu2#1021]
**Describe the bug**
When using keyboard command `f0, 00` (query scan code set), only the first byte returns ACK.

**To Reproduce**
```c
#include <stdio.h>

typedef unsigned char byte;

void out(byte b)
{
    byte s;
    do { asm volatile ("in al, 0x64" : "=a" (s)); } while ((s & 0x02) != 0);
    asm ("out 0x60, al" :: "a" (b));
}

byte in()
{
    byte b;
    do { asm volatile ("in al, 0x64" : "=a" (b)); } while ((b & 0x01) == 0);
    asm ("in al, 0x60" : "=a" (b));
    return b;
};

int main()
{
    asm ("cli");
    out(0xf0);
    printf("%x ", in());
    out(0x00);
    printf("%x ", in());
    printf("%x ", in());
    asm ("sti");
}
```
Output is `fa 1` and then it hangs waiting for the next byte. Expected output is `fa fa 1`. (or `fa fa 41` but it seems dosemu2 is emulating a PC/XT keyboard)

**Comment by stsp** [comment]
Could you please attach binary?

**Comment by stsp** [comment]
Had to fix your example by hands to compile.

**Comment by stsp** [comment]
Should now be fixed, thanks.

**Comment by jwt27** [comment]
Oh right, I forgot to mention the example is compiled with `-masm=intel`
