### ISSUE TITLE
mouse wrongly positioned in vc/dn/ndn when selected custom video mode

### ISSUE THREAD

**Issue by j2969719** [stsp/dosemu2#1029]
**Describe the bug**
mouse wrongly positioned in vc/dn/ndn when selected custom video mode
![vc](https://user-images.githubusercontent.com/30291994/75703842-53a92f80-5cc9-11ea-9e6c-0c3da57da202.png)

**To Reproduce**
Change video mode:
Volkov Commander: F9>Commands>EGA lines (Alt+F9)
Dos Navigators: F10>=>EGA/VGA Lines (Shift+F10) or Custom video mode 1-2
And then click somewhere on the bottom half of the file panel.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by j2969719** [comment]
confirmed, thanks!

not sure whether to start another issue, but also noticed a slightly similar problem with mouse integration when launch [opengem](http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/gui/opengem/6/opengem6.zip)

**Comment by stsp** [comment]
No, in opengem the host mouse is invisible,
and whatever is visible, clicks to the right
coords. If you are annoyed with clipping,
you need to press Ctrl-Alt-Home.

**Comment by j2969719** [comment]
yep, only a small area at the bottom was not accessible and clicks work fine, sorry
