### ISSUE TITLE
Speedy does not have sound

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#103]
Neither with DOSEMU2 devel branch nor with the 1.5.0 tarball, the sound in the game Speedy is working (no a regression).

It seems the game deals with the audio hardware in a special way:
DOSBox needs to be forced to emulate a Sound Blaster 2 to allow the sound in it to work. I don't remember any special audio issues when I ran the game on real hardware though.
With DOSEMU 1.5.0 this error is shown when running the game.
ERROR: PCM: attempt to flush inactive buffer (SB DMA)

A shareware version of the game is attached.
[SPEEDY.zip.base64.txt](https://github.com/stsp/dosemu2/files/32387/SPEEDY.zip.base64.txt)

**Comment by stsp** [comment]
I had to revert the fix.
Perhaps we need a config option after all,
the same way dosbox does.

**Comment by jschwartzenberg** [comment]
With dosbox, you need to select a rather old card though to get it to work. I can imagine the audio quality will be better if the game can work with something newer.

If it would be possible to binary patch for this game, I would say that would also be a nice fix. (It would fix the game on other systems as well.) You did not run into any problems due to this Tetris Classic hack yet?

**Comment by stsp** [comment]
I'll see about binary-patching the game.
There are also some other interesting tests to do.
For example with some DSP versions this speedy
works properly only when -D9+S logging is enabled.
So it seems as if it uses the DSP version number to
calculate some delay, which would be very interesting. :)

> You did not run into any problems due to this Tetris Classic hack yet?

I added hack-above-hack 0b61bed5 to reduce the
chances of making the breakage too visible...
After all, the proper DOS emulation is in a balance
of hacks, unless you emulate all the timings precisely
(something dosbox is trying to do).

**Comment by jschwartzenberg** [comment]
Ah yeah, that sounds quite interesting. It seems Speedy was made by Andreas Epple and Heiko Kohfink. There seem to be some profiles with those names around of people who are in IT. Maybe they still have some source code lying around ;)

**Comment by stsp** [comment]
Fixed with a binary patch.

**Comment by jschwartzenberg** [comment]
Interesting, how do the patch solve the issue? It changes the detection routine?

**Comment by stsp** [comment]
OK, now there is no need for a binary patch.
Btw, forcing the SB version still doesn't make it very
reliable: sometimes work, sometimes not.
My current fix looks reliable.

**Comment by jschwartzenberg** [comment]
You managed to solve it in a new way or you added a configuration option?
I'd like to test your binary patch with dosbox in any case. I can imagine it'll fix the game there too without having to go to a lower SB version.

**Comment by stsp** [comment]
I've explored the new fix.
The binary patch basically just forces the
SB version, but I've found that not fully reliable.
Maybe it will be reliable under dosbox - you can
try. But don't try it under dosemu as it will then
bypass my new and reliable fix.

**Comment by jschwartzenberg** [comment]
Your binary patch makes the game work much better with dosbox. It's not necessary to force the old SB version in the dosbox configuration anymore and the game sounds much better because of that.

In dosemu without any patch the game sounds good now, except for the sound heard when picking up a coin. Especially when this sound is repeated when picking up multiple coins, it becomes distorted. This distortion is gone when using your binary patch however!

So the patch still improves the game in dosemu here, it fixes the sound played when picking up coins.

**Comment by stsp** [comment]
> Your binary patch makes the game work much better with dosbox. It's not necessary to force the old
> SB version in the dosbox configuration anymore and the game sounds much better because of that.

It should be the same because my patch also
just forces the version.

> This distortion is gone when using your binary patch however!

With the binary patch it sometimes works and sometimes
no sound at all. Its just a luck.
Anyway, I'm glad you are satisfied with the existing partial solutions.
I don't think this buggy game is worth of more efforts.

**Comment by stsp** [comment]
> It should be the same because my patch also
> just forces the version.

Of course I mean a binary patch for the game.
The dosemu patch does the entirely different work-around.

**Comment by jschwartzenberg** [comment]
> With the binary patch it sometimes works and sometimes
no sound at all. Its just a luck.

Yes, but without the binary patch, the coin sound is consistently distorted in dosemu. So I would still recommend using the binary patch.

**Comment by stsp** [comment]
> Yes, but

Is this "Yes" also under dosbox?

**Comment by stsp** [comment]
On dosbox I have this:
Exit to error: DMA segbound wrapping (read)
and dosbox crashes.

**Comment by jschwartzenberg** [comment]
On dosbox you can't play the game at all without either your patch or putting 'sbtype=sb2' in dosbox.conf (which decreases the sound quality).

**Comment by stsp** [comment]
Why don't they fix the crash at least?
It wasn't crashing on dosemu, even without
any fixes. :)

**Comment by jschwartzenberg** [comment]
I tested with 0.74 which is quite old already. Maybe there are more fixes in a newer revision.

**Comment by stsp** [comment]
This should fix it now.

**Comment by stsp** [comment]
> 'sbtype=sb2' in dosbox.conf (which decreases the sound quality).

Please, my binary patch does exactly the same.
So if that decreases, the binary patch should too.

**Comment by jschwartzenberg** [comment]
I probably didn't listen attentively. Are you sure that your patch forces a 22050 Hz sample rate though? It seems that's what dosbox gives me with that setting.

**Comment by stsp** [comment]
My patch forces sb2.
The rate that Speedy uses, is 15625, at least during intro.
You can run dosemu with -D9+S and grep the log for "rate="
string, then compare the results with different setups.

Now have you tried the new fix?

**Comment by jschwartzenberg** [comment]
Then I probably didn't listen right. I just tried the new fix. I couldn't hear a single glitch anymore!!

**Comment by jschwartzenberg** [comment]
Sound in this game broke recently. Only the first few bits play. Reopen this one or create a new ticket?

**Comment by stsp** [comment]
Indeed...

**Comment by jschwartzenberg** [comment]
The sound in this game is broken again. There's scratching going through it. Maybe I can do a bisect tomorrow.

**Comment by stsp** [comment]
I can hear the intro music.

**Comment by jschwartzenberg** [comment]
Yes audio was playing, but I heard a repeating scratching noise through it.

**Comment by stsp** [comment]
Doesn't happen here.

**Comment by jschwartzenberg** [comment]
Weird, with  38d6c2f I also get the scratching noise now. I'll have to try it on another system.

**Comment by jschwartzenberg** [comment]
This problem does not occur on my other system which is running OpenSUSE 42.3. It only happens on my notebook with Ubuntu 16.04. I have Fedora on that notebook as well, so I'll try it with that.
