### ISSUE TITLE
Prehistorik 2 is unplayable

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#104]
Neither in DOSEMU2 devel branch nor with the 1.5.0 tarball Prehistorik 2 can be played. The game hangs when the character is about to appear with both. There is a performance difference between the two versions in one screen before the level overview screen with the 1.5.0 tarball being much faster. This screen and the level overview graphics are not rendered properly in either version.

More info about the game:
http://www.abandonia.com/en/games/4/Prehistorik+2.html

**Comment by stsp** [comment]
Could you please see what commit makes it slower?
Try with "master", maybe the same problem that was
in #99 ?

**Comment by stsp** [comment]
Please specify (for all bug reports) what OS you are using: 32 or 64bit.
If possible, please test on both: esp $_cpu_emu="off" on 32bit is interesting.

**Comment by jschwartzenberg** [comment]
I think that it's indeed faster again now.
I was running on Ubuntu 14.04 AMD64. I'll look into getting a 32-bit system set up.

**Comment by stsp** [comment]
Very very suspicious.
I don't think the tetris hack could fix
also this. Please try reverting 2ea10723 to make sure.

**Comment by jschwartzenberg** [comment]
With current GIT it works much better, but it's still not playable. When jumping/smacking/hitting an enemy, DOSEMU (with kvm) crashes (2x below):

```
julius@wijsvinger:~$ dosemu
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: Bestand of map bestaat niet
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=4065d10b while in vm86 (DOS)
Program=do_vm86.c, Line=158
EIP: 0000:0000007e ESP: 0f85:000001f8  VFLAGS(b): 00011 00000100 10000110
EAX: 0000ffa0 EBX: 00008ea0 ECX: 0000ff70 EDX: 00000076 VFLAGS(h): 00030486
ESI: 00000225 EDI: 00001000 EBP: 00000320 DS: 5b57 ES: 5b57 FS: 0000 GS: 0000
FLAGS: PF SF IF DF RF VM  IOPL: 0
STACK: 6d 7b 57 5b f3 91 ea 55 57 5b -> 57 5b 57 5b 57 5b 85 0f 03 05 
OPS  : 20 c0 00 f0 22 05 00 00 32 c3 -> ff ff 94 10 5e 01 b4 16 65 08 
        ff                  0000:007e db FF

julius@wijsvinger:~$ dosemu
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: Bestand of map bestaat niet
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=41877d01 while in vm86 (DOS)
Program=do_vm86.c, Line=158
EIP: 0000:0000007e ESP: 0f85:000001d1  VFLAGS(b): 01011 00000010 00000010
EAX: 0000fe08 EBX: 00000000 ECX: 0000001c EDX: 00002008 VFLAGS(h): 000b0202
ESI: 0000000a EDI: 0000270c EBP: 00000050 DS: 6d7b ES: 6d7b FS: 0000 GS: 0000
FLAGS: IF RF VM VIF  IOPL: 0
STACK: 3d 2e 02 00 00 1c 21 00 7b 6d -> 7b 6d 7b 6d 7b 6d 7b 85 0f a5 
OPS  : 20 c0 00 f0 22 05 00 00 32 c3 -> ff ff 94 10 5e 01 b4 16 65 08 
        ff                  0000:007e db FF
```

**Comment by stsp** [comment]
Wow, who fixed it? I didn't. Maybe Bart?
Would be nice if you bisect and find out the
commit that makes it working. Maybe this will
give us some clue about a further fixing...

**Comment by jschwartzenberg** [comment]
I'll look into that. For testing I tried it on 32-bit as well (no KVM) and got the same crash at exactly the same moment:
```
julius@mond:~$ dosemu
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: Bestand of map bestaat niet
ERROR: unexpected CPU exception 0x06 err=0x00000007 cr2=00013f36 while in vm86 (DOS)
Program=do_vm86.c, Line=158
EIP: 0000:0000007e ESP: 0f78:000001d5  VFLAGS(b): 01011 00110010 00000010
EAX: 0000fe1c EBX: 00000008 ECX: 0000ff04 EDX: 00002000 VFLAGS(h): 000b3202
ESI: 00004f1a EDI: 00002709 EBP: 00000050 DS: aa55 ES: aa55 FS: 0000 GS: 0000
FLAGS: IF RF VM VIF  IOPL: 3
STACK: 03 02 04 2e 02 09 7b 60 55 aa -> 7b 60 7b 78 0f 98 0f 20 03 57 
OPS  : 20 c0 00 f0 22 05 00 00 32 c3 -> ff ff 94 10 58 01 b4 16 58 08 
	ff                  0000:007e db FF

```

**Comment by jschwartzenberg** [comment]
I'm ending up somewhere in simx86 commits when bisecting. Does that make sense?

**Comment by stsp** [comment]
On a 32bit system? Very unlikely.
Anyway, there was a large pull request that I
haven't reviewed properly:
https://github.com/stsp/dosemu2/pull/122
If I did, I would find that it breaks bisect, because
it introduces the fatal regressions and fixes them in
other commits. This is quite unfortunate. :(
You can try to revert it entirely by reverting a62a58042.

**Comment by jschwartzenberg** [comment]
Yep, reverting that one brings it back to the old state.

**Comment by stsp** [comment]
On a 32bit system with vm86? Are you sure of that?
I guess you have not enabled 0-based mmaps in your
system.

**Comment by jschwartzenberg** [comment]
Ah crap, it seems I forgot to set that correctly. That explains it. (Maybe there could be an option to show the used mode in the title bar? It seems to have quite a bit of influence.)

When I run it on a 32-bit system with 0-based mmaps, the game hangs much earlier and the CPU usage is very high.

**Comment by stsp** [comment]
1. Are you sure this fall-back is silent?
As I look at the code, it seems it should warn you
pretty loudly when vm86 is unavailable.

2. So you claim vm86 mode now works worse than
$_cpu_emu="vm86"? How about $_cpu_vm="kvm"?

**Comment by jschwartzenberg** [comment]
I don't have a 32-bit box with KVM, so that's a 64-bit box. With KVM it seems to work better.

**Comment by bartoldeman** [comment]
I have only tried the shareware version. In there you need to first select "2" (passcode), then "1" (level 1) otherwise the game corrupts itself (weird copy protection), and it crashes dosemu as soon as you jump, hit, etc.

see also
http://www.vogons.org/viewtopic.php?t=4182

I'll check how dosbox finally fixed this issue.

**Comment by jschwartzenberg** [comment]
The version I am using has its copy protection removed. In dosbox it works without the described workaround.

**Comment by stsp** [comment]
Am I the only one for whom all the intro
screens are broken, as well as the passcode
menu?

**Comment by bartoldeman** [comment]
I see the first intros upto the 1/2 menu working properly but between that and the actual game it looks weird.

For the game to work properly without the workaround (password, then level 1), dosemu needs to write-protect the bios all the way from 0xf0000. Presently the game writes at 0xf0465 and if it succeeds the game crashes when you try to jump the character. A quick hack confirmed this but i suppose it could be an option in dosemurc (at the moment the bios starts at 0xf4000 and is not write protected).

**Comment by stsp** [comment]
> I see the first intros upto the 1/2 menu working properly

Do you have a copyright-protection intro that
says "Hybrid", during the initial intros?
It is entirely broken too, but you need to compare
it with dosbox to see exactly how.

I think having the bios protected would be good,
as it will catch the "illegal" writes by dosemu
(that are bypassing the needed macros and are
done w/o the aliased space).
An option perhaps can only reserve the extra
range (f0000-f4000), but the protection itself can
perhaps be applied unconditionaly.
We already have the options $_umb_a0, $_umb_b0,
so how about just adding $_umb_f0 to that list?

Btw, I really think you should register your e-mail
with github, so that you are listed on a contributors
page.

**Comment by stsp** [comment]
Hmm, we perhaps can add the $_umb_f0,
and if it is not enabled, protect just that, leaving
the bios as it is now.
Looks like a very simple temporary solution.

**Comment by jschwartzenberg** [comment]
When I use that menu trick that Bart wrote about, I can actually play the game correctly now!

**Comment by stsp** [comment]
Modulo some shaking when entering the
password. Really great results.

**Comment by stsp** [comment]
OK, so we are almost there now!
The only problem I can see is that the screen
scrolling is very slow in cpuemu+jit mode, but
is fine in sim mode.
It is visible when you run and the landscape scrolls.
If scrolling happens during prehistorik jump, it
is even slower.
I suspect we have the regression somewhere.

**Comment by bolle732** [comment]
I stumbled over the following link, where Prehistorik 2 is tested with a lot of graphic set-ups:

https://gona.mactar.hu/DOS_TESTS/

Maybe this info could be useful.

**Comment by stsp** [comment]
Interesting documentation indeed!
```
VBE15bpp converts any VESA VBE 16bpp modes into 15bpp modes. If you have a game that insists
on using 15bpp modes (like X-Men: Children of the Atom) and your video card does not support 15bpp
then you can't run that game. VBE15bpp overcomes this problem by converting any 16bpp modes to
15bpp modes.
```

This reminds me the patch 783780c7 done by
your suggestion. Are you sure you fixed a typo
and not some trick like this one? Was the patch
tested?

**Comment by bolle732** [comment]
Yes, I believe the patch is correct:
- All other entries with P16 has 16 bit set
- PC/GEOS had corrupted graphics with "P16, 15", where it works with "P16, 16"

**Comment by bolle732** [comment]
After thinking again, that magic of converting 16bpp to 15bpp should not apply to DOSEmu2, as it has explicit support for both bpp modes.

**Comment by stsp** [comment]
So Bart made prehistorik fully playable.
I think this can be closed.
