### ISSUE TITLE
Highway Hunter works too fast

### ISSUE THREAD

**Issue by grapeli** [stsp/dosemu2#1051]
https://archive.org/download/HighwayHunter/highway.zip
I used these [tips](http://www.reimagery.com/fsfd/system.htm#pascalfix).
```
unp hw1.exe
crtfix hw1.exe
```
I used to R200FIX - TSR runtime fix.
All these methods seem to be ineffective. Maybe I'm doing something wrong.
This game is still running a lot too fast. How to slow it down?

**Comment by stsp** [comment]
These methods can only cure "Runtime error 200"
msg on fast CPUs, but not slow things down.
First thing to try is to create `~/.dosemu/.dosemurc`
and write there:
```
$_cpuemu = "vm86sim"
$_cpu_vm = "emulated"
```

**Comment by grapeli** [comment]
I have probably tried it before. I repeated the test. I got the impression that it was working 4x faster.
```
CONF: Disabling use of pentium timer
CONF: dosbanner on
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: CPU VM set to 2
CONF: CPU VM set to -1 for DPMI
Linux kernel 5.5.9; CPU speed is 1403313000 Hz
CPU-EMU speed is 1403 MHz
CONF: JIT CPUEMU set to 3 for 586
CONF: not running on console
```

**Comment by stsp** [comment]
Compared with dosbox and don't see any
speed differences.

**Comment by stsp** [comment]
Running them simultaneously in 2
separate windows (dosbox and dosemu2)
reveals on the long run that on dosemu
this game is slightly faster indeed.
But nothing like 4x faster.

**Comment by stsp** [comment]
So I can't reproduce that.
Please make a video comparing
dosbox and dosemu2 on the same
screen.
