### ISSUE TITLE
Duke Nukem 2 digital sound effects not working properly (ADPCM unsupported)

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#1060]
**Describe the bug**
Sound Blaster sound effects are not working properly in DN2. Adlib is fine (used for both music and parts of the effects).

**To Reproduce**
Run the game in DOSEMU2. Compare with https://www.youtube.com/watch?v=5uWPojVzxP0

**Attach program/game binaries or provide an URL**
See #942

**Comment by stsp** [comment]
It uses ADPCM samples.
I wonder how important is to have that.

**Comment by stsp** [comment]
But its quite trivial to implement
(aka steal from dosbox)

**Comment by jschwartzenberg** [comment]
The Last Eichhof is mentioned here as using them: https://www.vogons.org/viewtopic.php?p=589618#p589618

**Comment by stsp** [comment]
https://wiki.multimedia.cx/index.php/Creative_8_bits_ADPCM

**Comment by stsp** [comment]
Should now work, enjoy.

**Comment by jschwartzenberg** [comment]
Yep, sounds great now!! Thanks a lot!
