### ISSUE TITLE
utilities.c:768: popen2: Assertion `p >= 0' failed.

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#107]
On Debian Jessie i386 I get the following output after about 1-2 minutes with just a black window when I run DOSEMU.

  dosemu.bin: utilities.c:768: popen2: Assertion `p >= 0' failed.
  ERROR: fork failed, Resource temporarily unavailable
[boot.log.txt](https://github.com/stsp/dosemu2/files/34956/boot.log.txt)

**Comment by stsp** [comment]
cat /etc/security/limits.conf
ulimit -a

I don't think this is dosemu-related.

**Comment by jschwartzenberg** [comment]
I have this problem with both the devel & master branch. The 1.5.0 fork point starts correctly.

/etc/security/limits.conf contains only commented stuff and:
````
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1847
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1847
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
````

**Comment by stsp** [comment]
OK, so what can this be?
A resource leak?
See output of
ps -AL |grep dosemu
to find out if dosemu process or threads do not grow.
See
ls /proc/`pidof dosemu.bin`/fd | wc -l
to find if file descriptors count increases.

**Comment by stsp** [comment]
pidof dosemu.bin is in backward quotes

**Comment by andrewbird** [comment]
Mmm it strikes me that there is a resource leak in the error path, but for this to become a problem the second pipe call would have to fail many times.
```C
diff --git a/src/base/misc/utilities.c b/src/base/misc/utilities.c
index d9e043d..2437e67 100644
--- a/src/base/misc/utilities.c
+++ b/src/base/misc/utilities.c
@@ -755,7 +755,11 @@ int popen2(const char *cmdline, struct popen2 *childinfo)
     struct timespec to = { 0, 0 };
 
     if(pipe(pipe_stdin)) return -1;
-    if(pipe(pipe_stdout)) return -1;
+    if(pipe(pipe_stdout)) {
+        close(pipe_stdin[0]);
+        close(pipe_stdin[1]);
+        return -1;
+    }
 
 //    printf("pipe_stdin[0] = %d, pipe_stdin[1] = %d\n", pipe_stdin[0], pipe_stdin[1]);
 //    printf("pipe_stdout[0] = %d, pipe_stdout[1] = %d\n", pipe_stdout[0], pipe_stdout[1]);
```

**Comment by jschwartzenberg** [comment]
I did a git bisect:
```
1820c4feb1ceb058c02c475be1533cbfc79cf4f7 is the first bad commit
commit 1820c4feb1ceb058c02c475be1533cbfc79cf4f7
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Thu Sep 10 16:45:16 2015 +0400

    use vm86plus for now as otherwise dosdebug doesn't work

:040000 040000 c490d26c330c0b36ad5aaf99d7c67d58d6e54781 f50a085584fda52bbc98ebb2c09cc039fbce591c M      src
```

**Comment by jschwartzenberg** [comment]
It seems this is also related to the version of MS-DOS being used. WIth a Chicago DOS it breaks like this. WIth a MS-DOS 6.22 it seems to work better. (Still not managing to get to a visible C:\> prompt though.)

**Comment by stsp** [comment]
I think you are missing this patch:
http://git.kernel.org/cgit/linux/kernel/git/tip/tip.git/commit/?id=2459ee8651dc5ab72790c2ffa99af288c7641b64
Without that, vm86plus is very unstable.
Could you check?

**Comment by jschwartzenberg** [comment]
I'll check it probably as well, it indeed seems unlikely that my kernel would have this patch as it appears to be very recent. Are you aware of any distros that are shipping a kernel with this patch already?

**Comment by stsp** [comment]
See issue #77 - seems like ubuntu has it.

**Comment by andrewbird** [comment]
Yes, but I think it's only in wily's -proposed repository at the moment, so you won't get it in a std install plus update.

**Comment by jschwartzenberg** [comment]
Does that mean that DOSEMU2 shouldn't be expected to work properly on current 32-bit distros? That seems like quite a big limitation. Or should I try with vm86emu?

**Comment by andrewbird** [comment]
32bit is working fine with cpuemu=off on any kernel <= 3.19, on a patched 4.2 or any >= 4.3 with the vm86 config legacy variable( I forget its exact name) turned on. The patched 4.2 kernel for ubuntu is in -proposed at the moment but I'm hoping it will progress to the main repository soon. It may work on 4.0 or 4.1, but I'm not sure about those.

**Comment by stsp** [comment]
Yes, you should try $_cpu_emu="vm86" please.

**Comment by jschwartzenberg** [comment]
Turns out that this problem occurs with kernel version 3.16. Switching $_cpu_vm to emulated or $_cpu_emu to vm86 makes it work properly.

On multiple 32-bit systems I see that the DOSEMU window goes black shortly after starting up. Do you recognize this?

**Comment by stsp** [comment]
And on other kernels?

**Comment by stsp** [comment]
Is this fixed by newer kernel and/or $_cpu_vm="kvm"?

**Comment by stsp** [comment]
Enough.

**Comment by stsp** [comment]
Reportedly still valid?
