### ISSUE TITLE
dosemu plugin registry?

### ISSUE THREAD

**Issue by leecher1337** [stsp/dosemu2#1070]
Hi,

I recently developed a plugin for various DOS emulators including dosemu to provide BTRIEVE support via the native BTRIEVE system libraries:
https://github.com/leecher1337/btrieve-vdd

Is there any kind of registry where dosemu plugins can get registered so that users searching for a certain dosemu extension can find it? Or is it worth merging it into the dosemu tree?

**Comment by stsp** [comment]
That depends on a few things.
Does libbtrvif.so have a free license and
a development headers, so that the one
can link to it, rather than dlopen()? Btw,
do you really need RTLD_DEEPBIND?
Who uses that stuff? I don't remember a
single query about btrieve support under
dosemu.
Do you really need a .sys file, like if the
DOS progs check for "BTRDRV00", or
can you just hook int7b directly in int.c?
(of course we can make it hookable to
plugins, if need be)

The problem is that your code needs
modifications to dosemu sources besides
the plugin, and your instruction does not
apply to the current devel branch in git,
so of course it is better to keep it in dosemu2
source tree, but the license should be fine.

**Comment by leecher1337** [comment]
Hi,

No, libbtrvif.so is not free, this is proprietary and gets shipped with Pervasive SQL installation, so it needs to be bound. I'm not really sure about the header license, I found them on github.

RTLD_DEEPBIND is definitely necessary, library crashes without this parameter, finding this problem cost me several hours of debugging.

Some companies are using BTRIEVE based applications (mostly on Windows), but with the move of Windows Server operating systems towards 64bit, they are lacking NTVDM support on the terminal server side, so dosemu is a good possibility to get applications running in V86 mode on Linux (emulation is a no-go, of course, far too slow, but V86 mode performs very well) and i.e. accessing them via a terminal client. 

The .sys file is i.e. needed for installation check, offset of the interrupt handler has to be 0x33, otherwise installation check will fail. If you know how to do this via direct int.c hook, I can try it, of course. 

If the 2 functions that I need can me made public in dosemu2, no modification would be needed by the plugin.

**Comment by stsp** [comment]
Making some API public for out-of-tree
non-free code is usually a very bad idea.
And there are also practical reasons why
it is no, besides the "religion".
But we can think of the intE6h extension.
So if you are fine with calling these functions
from your .sys driver, then please sketch
the API you need, or even implement it and
make a PR.

**Comment by leecher1337** [comment]
Compared to dosemu1, build_posix_path already is
non-static in dosemu2, so it's just the truename API.

All I need is to get a full DOS-path for the supplied
filename in a request buffer.
Doing it in the .sys driver is not an option, as there would
be duplicate parsing of the request, the .sys driver would
need to analyze the request and then craft a new request
based on the template.
Directly calling the LFN API by setting up registers in the
plugin and then issuing a manual call to mfs_lfn() also is
useless overhead. The routine is very performance critical,
as it can get hundreds of calls per second, so every unnecessary
code that can be avoided should be avoided, as it would
have an impact on overall performance.

I could copy lfn.c to the plugin directory and use my own
copy of the module, but that's also awful in terms of
code maintainability.

**Comment by leecher1337** [comment]
So basically you suggest that I do:

```
static int my_truename(char *dest, const char *src)
{
  Bit16u ds=_DS, di=_DI, es=_ES, si=_SI, ax=_AX, cx=_CX;
  int ret;

  _DS = FP_SEG32(src);
  _SI = FP_OFF32(src);
  _ES = FP_SEG32(dest);
  _DI = FP_OFF32(dest);
  _AX = 0x60;
  _CX = 0;
  ret = mfs_lfn();
  _DS = ds;
  _DI = di;
  _ES = es;
  _SI = si;
  _AX = ax;
  _CX = cx;
  return ret;
}
```

?

**Comment by stsp** [comment]
> So basically you suggest that I do:

Roughly so, except that you should do
something like `do_int_call_back(0x21);`
for truename. Also search for "saved_regs"
in sources to see how to save/restore quickly.
Calling mfs_lfn() or alike directly is discouraged.
Of course I won't rush to add "static" back to
build_posix_path, but you should instead add
an intE6 extension for it and call it with
`do_int_call_back(0xe6);`, because it is
not the part of the public API, whereas
`do_int_call_back()` may be viewed as such.

**Comment by leecher1337** [comment]
I'm somehow unable to compile the plugin with dosemu2.
The lexer and parser grammar just isn't picked up, it seems.
I do a `./configure --enable-plugins=+btrieve-vdd`
and `make`
Still, `src/base/init/parser.y` doesn't get updated.
Is this a bug? Using dosemu2-2.0pre8.

**Comment by stsp** [comment]
dosemu2 is not dosemu1.
Nothing of what is written in your
readme, will work here.
And as for settings...
There are 2 ways I can think of.
- Pass settings to the .sys command
line. You can still parse them in the
host code, see ems.sys as an example
of doing so.
- pass settings via unix env variables.

**Comment by stsp** [comment]
Also pre8 is just a last pre-alpha.
Nothing that works with it, can work
in git, or an upcoming beta.

**Comment by stsp** [comment]
It would be better to support dosemu2
completely separately. You probably
won't find a common denominator, as
all the public api for proprietary code
that dosemu1 had, is simply not here.

**Comment by leecher1337** [comment]
Maybe you should update your readme then:
https://github.com/stsp/dosemu2/tree/devel/src/plugin clearly states, that lexer and parser support is still here, so this is a documentation error then?

**Comment by stsp** [comment]
Yes, good point, will do. :)
I simply didnt get to update any docs
yet, but at least removing whats not
there, should be done.

**Comment by leecher1337** [comment]
Passing paths via environment would be really bad design, there can be dozens of "btrv_mappath()" configuration lines, that could exceed environment block size and commanline length when put together in one line. 
So the only reasonable option I can think of would be to implement a seperate config file parser that parses the .dosemurc (or a seperate config file for the plugin) on its own. Why was the plugin configuration functionality removed, it was very useful?

**Comment by stsp** [comment]
I understand that was very useful
for your project, but the in-tree plugins
do not need it, and out of tree is only
yours.
Would it be an option to use a file in
DOS fs for map pathes? After all, the
config file is not for the large data
arrays, anyway.

**Comment by leecher1337** [comment]
So you mean that the plugin has to:
1) Implement lexer and perser for the config file on its own
2) .SYS driver should take DOS path to the config file as an argument, pass it on the the plugin and the plugin then translates the path to the UNIX path and applies the lexer and parser on the config file to load the configuration.

So that would be one additional step to add to just parsing the config file on the host side (passing pointer to config file form DOS side) , but would fit better into the concept that everything can be configured from DOS side, I guess?

**Comment by stsp** [comment]
I dont think you really need parser
and lexer. Isnt it all about key=value
thing? There are many libs to handle
that.

The rest is mostly right, except that
plugin does not need to translate the
path. See com_dosread() and friends
for a direct access.

**Comment by stsp** [comment]
I mean I do not propose to have
entire config in a dos file, just a path
map. The rest can be handled by .sys
cmd line, no?

**Comment by leecher1337** [comment]
Using 2 different config file parsers doesn't sound too appealing in terms of code maintainability. Say, I'll add 20 more options to it, I'd need to update plugin__parser, plugin_lexer (for dosemu1) and then do the same thing all over again for a custom dosemu2 config parser. 
That's why I thought about a custom parser, if the main parser is not available.

Of course it would be easier to write a file with mappings and just strtok('=') the lines and create the map, but It may be confusing for plugin users to have 2 completely different configuration syntaxes depending on the dosemu version.

Anyway, can you point me to the code location where the EMS driver parses the commandline options?

**Comment by stsp** [comment]
But its not config.
Large arrays of strings should
really be separated from casual
"options", and may of course have
different syntax. Have you seen
any configs, say, in /etc/*, that contain
some large textual databases?
Well, I won't claim there is none
(from 1000+ software packages),
but I am sure you'll have troubles
finding such thing.
So what I really suggest is to think
up the good design, and the syntax
that suits your project the best, rather
than the one inferred from dosemu1
parser.

> 2 completely different configuration syntaxes depending on the dosemu version.

But its really another emulator.
What's left is just some vary basic
support for old dosemu1 setups
for an easier migration. And that
usually, and most often, becomes
the downside, as people then expect
the full compatibility and never explore
the new functionality that would be
given by setting up things from scratches.
By converting from dosemu1, you get
a reduced and problematic setup, so
one day I may better rename to something
else and drop the compatibility completely. :)
If you don't want 2 syntaxes, you may as
well not support dosemu1 at all, as it is
barely usable on modern distros (vm86
disabled, 16bit LDT disabled etc).

> Anyway, can you point me to the code location where the
> EMS driver parses the commandline options?

Sure enough:
https://github.com/stsp/dosemu2/blob/devel/src/dosext/misc/xms.c#L324
Though the comment explicitly says its not for ems.sys. :)

**Comment by leecher1337** [comment]
I'm sorry to bother you in this thread with it, but I'm struggling for hours now to get dosemu2 to run on my machine in order to test my module with it. The documentation is a bit sparse.
I created a seperate user with his own home directory (to not interfere with dosemu1 installation). In order to run dosemu2 as a local installation, I used `src/bindist/mkbindist`.
It spit out some copy errors. I had to copy the files from bindist to src directory so reduce error count. It still had some errors remaining. Then I had to copy freedos over to tmp/freedos directory. Now I was able to start it, but I just receive errors about UMBs not available and it wants to load himem.sys (which isn't even included in freedos):
```
>>>device=c:\dos\himem.sys
         ^
CONFIG.SYS error in line 9
>>>device=e:\dosemu\umb.sys
         ^
UMB's unavailable!
CONFIG.SYS error in line 10
>>>devicehigh=e:\dosemu\ems.sys
             ^
UMB's unavailable!
CONFIG.SYS error in line 11
>>>devicehigh=e:\dosemu\emufs.sys
             ^
UMB's unavailable!
CONFIG.SYS error in line 12
>>>devicehigh=e:\dosemu\cdrom.sys
             ^
Bad or missing Command Interpreter: c:\command.com /e:1024 /p /k autoemu.bat
```

Is there any documentation on how to make a local bindist release that ignores all global directories and just works? I'm running out of ideas... :-(

**Comment by leecher1337** [comment]
Seems like the autoexec.bat and config.sys shipped with bindist aren't usable out of the box, I now wrote my own startup files based on dosemu1 config

**Comment by stsp** [comment]
OK, thanks for finding random crap, I removed it.
README.plugin is removed earlier.
Please find what else to remove, you are
good at that. :)
I mean, no kidding, locating and removing
outdated crap helps.

**Comment by stsp** [comment]
> Seems like the autoexec.bat and config.sys shipped with
> bindist aren't usable out of the box, I now wrote my own startup files based on dosemu1 config

I would curse if not for the fact
that you are helping me to remove crap. :)

**Comment by stsp** [comment]
Now seriously.
Please just get the packages from our
ubuntu PPA: https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa
and get in touch with dosemu2 that way.
After that you'll be able to build/install
from sources.

**Comment by leecher1337** [comment]
It seems that I got it working with a working config.sys /autoexec.bat pair.
Now that you removed mkbindist, can you document how to make a copy of dosemu2 that runs without installing any files outside of home? So if mkbindist is outdated, what's the proper way for that? ./configure with --datadir etc. set to ~/.dosemu  ...?

**Comment by stsp** [comment]
The proper way is, as I said, just install
from ubuntu PPA. That's the simplest way.
At least it brings in all dependencies for you,
because you do not seem to be looking at
what configure is loudly telling you about
the missing packages.

I am working on making fdpp a hard dep
on a configure level, because I've got enough.
@andrewbird do I remember correctly
that your complain to that was that it can't
find headers in non-default path? Since we
use pkgconfig for that, I wonder if override
is even possible.

**Comment by andrewbird** [comment]
I think there may be some oddity when FDPP / comcom packages are installed and you want to run dosemu2 from the build directory using a locally built FDPP too. But I gave up trying to understand the logic and uninstalled dosemu2 and FDPP packages. Dosemu2 builds just fine with a locally built FDPP from the source directory using a local pkgconfig directory and env var. See travis_build for an example.

**Comment by stsp** [comment]
Yes, I see, you hack on prefix.
I'll try to code up something sensible for that.

**Comment by jschwartzenberg** [comment]
> I am working on making fdpp a hard dep on a configure level, because I've got enough.

Can you make sure it would be clear which version of FDPP is compatible with a given DOSEMU2? From time to time when I try old revisions, I have to disable FDPP to get them to compile. The alternative would be to seek the correct FDPP version, but there doesn't seem to be an obvious mechanism for that other than looking at the timestamps of commits in both repositories.

**Comment by stsp** [comment]
No, its perfectly versioned.
I think the problem during bisect
is that fdpp becomes "too new".
I'll change `>=` version check to `==`.
I will also have to add an option
to explicitly disable fdpp perhaps.

**Comment by stsp** [comment]
In fact, changing to `=` sucks, as it will
require updating the check every time
the new fdpp is out. So I think the compile
errors during bisect are unavoidable,
and the only option is to disable it while
bisecting. :(

**Comment by andrewbird** [comment]
What about tagging FDPP before each incompatible change/version bump, then during bisect of doesmu2 at each point, see what version is required and checkout that tagged version and build it first?

**Comment by stsp** [comment]
This all already exist.
Except that not all API changes are
being tagged.
But no one will rebuild fdpp during
bisect I am afraid.

**Comment by andrewbird** [comment]
I don't see any API changes being tagged, least not by number.
~~~
$ git tag -l 
alpha-1
alpha-2
alpha-3
alpha-4
banner-works
beta-1
beta-2
beta-3
beta-4
beta-5
beta-6
beta-7
beta-8
beta-9
fdpp-start
ke2042
rc-1
~~~

I was thinking of tag by API number. So dosemu tester could do
~~~
git grep "FDPP_API_VER .="
src/plugin/fdpp/fdpp.c:#if FDPP_API_VER != 26

(cd ../fdpp.git && git checkout API26 && make clean all)

# Note pkgconfig points to directory above
make distclean && env PKG_CONFIG_PATH=`pwd`/pkgconfig ./default-configure -d && make
~~~

**Comment by stsp** [comment]
OK, I can add tags, just need to install
`git recursive-blame`. I am really sceptical
someone will do that, but lets try.

**Comment by andrewbird** [comment]
I will if it's easy to determine the version, but I always run with a local FDPP installation anyway, so it's no great issue.

**Comment by stsp** [comment]
How about coding up the script
that will, being run from dosemu2 tree,
automatically grep fdpp.c, check out
the needed tag at fdpp repo, build it,
do `make local_install_hdrs` and point
dosemu's configure script to that?
Yesterday I already added `--with-fdpp-dir`
that allows to pick up from local build
(but needs `make local_install_hdrs`
on fdpp side).

**Comment by andrewbird** [comment]
Yes, but using the new features `make local_install_hdrs` and `--with-fdpp-dir` will only work from now on, I suppose bisect might need to go further back.

**Comment by stsp** [comment]
We can recommend the use of new
methods later. For now bisect should
go as before: by disabling fdpp. But
at least we need to code this all up
for the future.
Good that such problems are brought
to our attention now, while we are still
in an alpha stage. Acceptable screw-ups
for an alpha quality. :)

**Comment by stsp** [comment]
Tags added.
Someone should write the script. :)

**Comment by andrewbird** [comment]
cool, thanks, trying to write something now

**Comment by stsp** [comment]
Andrew, seems like all the infrastructure is
in place now. You can do
```
./default-configure fdpp-build-path=/home/stas/src/fdpp/fdpp/build
```
and it should even override the globally installed
fdpp, if any. Does this work for you?
