### ISSUE TITLE
Sound Blaster 16 installation broken

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#1072]
**Describe the bug**
![afbeelding](https://user-images.githubusercontent.com/877112/77797911-3110f900-7072-11ea-891e-70c87d8d230a.png)

**To Reproduce**
Extract the files, run the installer.

**Attach program/game binaries or provide an URL**
https://github.com/jschwartzenberg/dos-download-scripts/tree/master/sb16w31

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/4395807/boot.log)

**Additional info**
I suspect it's due to that `mfs.c` issue you fixed recently.

**Comment by jschwartzenberg** [comment]
Confirming that with 63226d70e65f1dc6e194bd5220a2652683ff3a2a it works fine, so the last commit broke this.

**Comment by stsp** [comment]
How interesting!
If you change "unsigned" that was added
by my patch, to "signed", will it still break?
(the prev error should re-appear of course)

**Comment by jschwartzenberg** [comment]
Yes indeed, then I get the error, but it works.

**Comment by stsp** [comment]
So if you revert my patch completely, but
in mfs.c:4183 write something like:
```
off_t offset = ((unsigned)WORD(state->ecx) << 16) | (unsigned)WORD(state->edx);
```
will it work then?

**Comment by jschwartzenberg** [comment]
No, that gives the same as in the screenshot.

**Comment by bartoldeman** [comment]
I think the issue here is that off_t is signed 64-bit, so with unsigned it will contain 0xffffffff (positive) but with signed it contains -1.

using
```
off_t offset = (int)(((unsigned)WORD(state->ecx) << 16) | (unsigned)WORD(state->edx));
```
would fix that (or after applying the patch,
```
off_t offset = (int32_t)((WORD(state->ecx) << 16) | WORD(state->edx));
```
)

**Comment by stsp** [comment]
Ahh, negative offsets!!! :(
@jschwartzenberg could you please test
Bart's suggestion?
I think such a cast is implementation-specific,
but I hope its not an UB this time.

**Comment by stsp** [comment]
OK, I applied Bart's suggestion in a hope that it works.

**Comment by jschwartzenberg** [comment]
Yes, that fixed it!
