### ISSUE TITLE
MS Office complains about share.exe

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#1073]
I'm getting this:
![afbeelding](https://user-images.githubusercontent.com/877112/77803452-70911280-707d-11ea-8ca3-7b36c627f130.png)

But in the past it worked:
https://schwart6.home.xs4all.nl/dosemu-msoffice.webm

I cannot reproduce that anymore. Any idea what could be wrong?

**Comment by stsp** [comment]
What if you load freedos's share.exe?

**Comment by jschwartzenberg** [comment]
I only found `share.com` here: http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/dos/share/2006/
But loading that doesn't work. The message is the same.

**Comment by andrewbird** [comment]
Don't you need the share command that matches the dos kernel you are running. I.e. share.com with freedos or FDPP (I checked it does work), or share.exe with ms-dos / windows? It should be on the ms-dos installation disk, but may need expanding.

**Comment by jschwartzenberg** [comment]
`fakeshar.com` doesn't work either: https://www.vogons.org/viewtopic.php?t=9405

But I found the issue after @andrewbird's hint. It seems `msexpand` changed and it cuts the underscore off the extracted filename instead of moving it to the path specified in its second argument. This is why my script was not installing `share.exe` anymore.

**Comment by stsp** [comment]
But it still doesnt work?

Btw, what about embedding
share into fdpp?

**Comment by andrewbird** [comment]
I'm looking at locking again at the moment, so I've also considered having FDPP provide share itself. The only downside I can see is the extra memory usage for the locks would always be allocated, unless it was configured by a config.sys keyword.

**Comment by jschwartzenberg** [comment]
> But it still doesnt work?

No it works now! This issue could be closed. I did not test with FDPP though only with MS-DOS 6.22.

**Comment by stsp** [comment]
Ok, lets close.

Yes, it will take some mem, but that
can be umb I hope. We can make that
a config option, but under dosemu2
the default config rarely changes, so
I wonder if that is needed.
