### ISSUE TITLE
Micro Machines does not work properly with KVM enabled

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#116]
Latest GIT devel on Ubuntu 14.04 AMD64.
When running Micro Machines with KVM enabled, the background music in the menu is very slow. Trying to go into a race results in a hang with DOSEMU printing in the terminal:
```
KVM: KVM_RUN: Invalid address
```

With $_cpu_vm = "emulated" the music and the game plays normally.

More info about the game:
http://www.abandonia.com/en/games/77/Micro+Machines.html

**Comment by stsp** [comment]
Bart, this is easy to reproduce (I checked),
could you please take a look?

**Comment by jschwartzenberg** [comment]
With current GIT, I get this message + the hang already at the first title screen (before the copy protection screen).

**Comment by bolle732** [comment]
I can reproduce the same on Ubuntu 15.10 amd64 with other programs. Sometimes it works for a few seconds, sometime it freezes after one second.

Would it make sense to test it on the KVM branch ?

**Comment by stsp** [comment]
No, just disable kvm for now,

**Comment by jschwartzenberg** [comment]
Now I can actually get in a race and race about half a lap before I get the error. There are also timing issues.

**Comment by jschwartzenberg** [comment]
Alley Cat has the same symptoms. In the middle of the game, while playing, it'll suddenly hang with
```
KVM: KVM_RUN: Invalid address
```
being printed.

**Comment by jschwartzenberg** [comment]
Two more games with the same issue, Prince of Persia and Zeliard.

**Comment by stsp** [comment]
So should we undefault this perhaps?
Bart, what's your take on this?

**Comment by jschwartzenberg** [comment]
Don't know if it makes sense to add more here. I had the same the issue with the Tristan pinball game and with a specific version of Sim City in a rather specific condition.

**Comment by stsp** [comment]
OK, I'll try to not forget to undefault KVM.

**Comment by stsp** [comment]
I also have the machine reboot with KVM on
the following cpu: AMD Athlon(tm) II X2 245
So far I wasn't able to reproduce this on other
CPUs.
If someone wants to try, get this file:
https://github.com/stsp/dosemu2/blob/bug/c_drive/c.tar.gz
Unpack it into ~/.dosemu/drives.
Then run dosemu, and when Dos Navigator loaded,
hit
Alt-x Enter
to exit.
At that point my machine reboots if dosemu uses kvm.
Please everyone, try and post your CPU model here.

**Comment by bolle732** [comment]
I've tested the DN on my Ubunut 14.04 AMD64 machine. DOSEMU ist from the GIT repo. It worked  ok, no reboot.

CPU info: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

Settings in "dosemu.conf"
```
$_cpu_vm = "kvm"
$_hdimage = "/home/<MY_USER>/<MY_PATH>/drive_c"
```

**Comment by stsp** [comment]
Thanks!
It may be good to test 2-3 times, since it is not
always happening from first time. But I am pretty
sure you won't reproduce that on Intel CPU, because
I can't reproduce even on more modern AMD CPUs...

**Comment by bolle732** [comment]
I've started it several times without a problem.

**Comment by stsp** [comment]
I am including your CPU into my kvm bug report
and will post it to their list, lets see.

**Comment by bolle732** [comment]
Ok, that's fine for me.

**Comment by bartoldeman** [comment]
I haven't been able to reproduce this issue with the current devel -- Micro Machines does not give the KVM_RUN error for me and I also had no issues with Prince of Persia. Is there a specific commit for which it is easy to reproduce.

**Comment by stsp** [comment]
Interesting question, works for me too. :)
Was this a kernel problem?
@jschwartzenberg

**Comment by jschwartzenberg** [comment]
I have upgraded that system from Ubuntu 14.04 to 16.04 now. It still doesn't work here, I get the KVM_RUN error immediately when I start up Micro Machines.

**Comment by stsp** [comment]
OK, the bug looks unstable.
The one needs to run micro.com (and only micro.com)
and maybe it will crash. For me it crashes about 1/3 times.
And at the different moments of an intro.

**Comment by bartoldeman** [comment]
I could reproduce it now. There is a nasty race in the vgaemu thread code. This code changes the protection of the page at 0xa2000 from R/W to R/O while KVM is running, which means calling mprotect() and adjusting the page tables in the monitor. These two things cannot be done at the same time (atomically) which confuses KVM.

I am not quite sure how to fix this yet. One way is to use a completely different approach: the page tables in the monitor have "accessed" and "dirty" bits themselves. We could use those bits instead of needing to use mprotect() -- unless special planar modes with instremu are used, the vgaemu pages would be permanently r/w, and the update code just scans the page tables for dirty bits and resets them.

**Comment by bartoldeman** [comment]
Hmm, a quick fix would be to adjust the monitor page table before calling mprotect() instead of after... Let me test that.

**Comment by jschwartzenberg** [comment]
The problem with Micro Machines is indeed fixed! I've been testing the other games I mentioned here as well. In most of those, I couldn't reproduce it anymore either. The only one which still hits the issue regularly is the Tristan pinball game. Should I open a new issue for that?

**Comment by stsp** [comment]
Why not?
And please don't forget to test the new DPMI code that
was recently pushed in. :)

**Comment by jschwartzenberg** [comment]
Alright, will do! Looking forward already to trying this Tetris Classic ;)
