### ISSUE TITLE
X86_EFLAGS_FIXED missing on older kernel

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#124]
I've compiled the DOSEMU2 devel branch (2.0pre4, 1893) on an Ubuntu
12.04 LTS (x86 / 32-bit / PAE). This fails due to the usage of
"X86_EFLAGS_FIXED" in the file "src/emu-i386/kvm.c".

I believe that the define of "X86_EFLAGS_FIXED" is missing in the kernel
3.2.x of my Ubuntu version. There has been a rename of "X86_EFLAGS_BIT1"
to "X86_EFLAGS_FIXED" some time ago:

https://www.kernel.org/pub/linux/kernel/v3.0/ChangeLog-3.10.60

But I even can't find the define of "X86_EFLAGS_BIT1" in the kernel sources.

In the meantime, I added the following line to "kvm.c" and could compile
successfully DOSEMU2:

#define X86_EFLAGS_FIXED                0x00000002

But I believe, this is NOT the right thing to correct the problem...

DOSEMU2 runs so far with "vm86", which is my goal. I don't intend to use the KVM on 32-bit.

What would be the correct way to fix this ? Or is DOSEMU2 not supposed to run on older kernels ? Or do I have a local problem due to missing something ?

**Comment by andrewbird** [comment]
Hi Andreas,
    That definition is in the 'uapi' section of the kernel sources, which means it's the user api. Those files are a reference for the distros to follow when shipping kernel headers for applications to be built against. On my Ubuntu (14.04) 32bit the corresponding distro file is in /usr/include/i386-linux-gnu/asm/processor-flags.h. Your older release should have something in there called 'X86_EFLAGS_BIT1', as you mentioned. I suspect a build fix for dosemu would need to be added and go something like
~~~
#ifndef X86_EFLAGS_FIXED
#define X86_EFLAGS_FIXED X86_EFLAGS_BIT1
#endif 
~~~
But I'm not sure if that should go in kvm.c or a header

**Comment by bolle732** [comment]
Hello Andrew

I've checked the header file "/usr/include/i386-linux-gnu/asm/processor-flags.h" on my Ubuntu 12.04 with kernel "3.2.0-97-generic-pae". There is neither a define for "X86_EFLAGS_BIT1" nor for "X86_EFLAGS_FIXED". So using the "X86_EFLAGS_BIT1" wouldn't work here too.

**Comment by andrewbird** [comment]
Yep I agree, I've now checked the linux-libc-dev package for 12.04 and that BIT1 is missing and there are no EFLAGS defines with the same value. Not sure what is best now, I guess that's one for Stas or Bart.

**Comment by bolle732** [comment]
I've seen that Stas has removed the usage in the define. But there are still 2 other places in "kvm.c" where the constant "X86_EFLAGS_FIXED" is used.

**Comment by stsp** [comment]
Oh, I forgot to reference the ticket in the commit, sorry.
I've applied the different fix now, could you check?

**Comment by bolle732** [comment]
Yes! The devel branch now compiles again out of the box. Thank you. Will now do some testing.
