### ISSUE TITLE
Parallel Port / Dongle

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#129]
Hello,

how can I use the parallel port with dongles? I tried deleting the $_lpt1 = "xxxx" entries and adding $_ports = "device /dev/parport0 fast range 0x378 0x37f". I also tried $_ports = "device /dev/lp0 fast range 0x378 0x37a". Both with dosemu -s but no luck (and no errors either).

**Comment by stsp** [comment]
This is a duplicate of #3 it seems.
