### ISSUE TITLE
Application crash on x32

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#130]
Running my legacy dos application crashes dosemu on 32bit systems if I do

> sudo sysctl -w vm.mmap_min_addr=0

before running dosemu to fix the error message which appears instead. 

```
ERROR: Using CPU emulation because vm.mmap_min_addr > 0.
You can most likely avoid this problem by running
sysctl -w vm.mmap_min_addr=0
as root, or by changing the vm.mmap_min_addr setting in
/etc/sysctl.conf or a file in /etc/sysctl.d/ to 0.
If this doesn't help, disable selinux in /etc/selinux/config
```

If I don't do that the application works (as well as on x64). I think we discussed a similiar issue somewhere on the old dosemu scoureforge?
Default configuration of dosemu.conf, no changes. Which log do you need?
[program.zip](https://github.com/stsp/dosemu2/files/76634/program.zip)

**Comment by stsp** [comment]
Could you please try branch "master"?
Its not easy to reproduce that for me.
Need to install 32bit system...

**Comment by haenschen** [comment]
With the master branch make fails with 

```
gcc -c -MMD -DCFLAGS_STR="-Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -fno-stack-protector -fplan9-extensions -Wno-maybe-uninitialized -O2   " -I../../../src/include -I../../../src/plugin/include  -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -fno-stack-protector -fplan9-extensions -Wno-maybe-uninitialized -O2    -o video.o video.c
make[2]: *** No rule for target »../../../src/include/instremu.h«, 
  needed to create »instremu.o«.  End.
make[2]: Verzeichnis »/home/pa/dosemu/src/base/video« wird verlassen
make[1]: *** [base/video] Fehler 2
make[1]: Verzeichnis »/home/pa/dosemu/src« wird verlassen
make: *** [default] Fehler 2
```

**Comment by stsp** [comment]
make realclean

**Comment by haenschen** [comment]
Okay. The crash occurs on master too.

**Comment by stsp** [comment]
And on dosemu1?

**Comment by haenschen** [comment]
dosemu1 works

**Comment by stsp** [comment]
Uh, sorry to say that, but you'll likely need to
do "git bisect" then.
I would suggest to first try dosemu2 tags:
$ git tag -l
dosemu-1.4-dev
dosemu-1.5.0
dosemu2-2.0pre1
dosemu2-2.0pre2
dosemu2-2.0pre3
dosemu2-2.0pre4

Please walk down the pre's and see which one
fails. Then you can do a bisect between the 2
nearby releases. Can you do that?
Note: you'll need "make realclean" in many cases,
and if that doesn't help, then autogen.sh.

**Comment by haenschen** [comment]
````
1820c4feb1ceb058c02c475be1533cbfc79cf4f7 is the first bad commit
commit 1820c4feb1ceb058c02c475be1533cbfc79cf4f7
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Thu Sep 10 16:45:16 2015 +0400

    use vm86plus for now as otherwise dosdebug doesn't work

:040000 040000 c490d26c330c0b36ad5aaf99d7c67d58d6e54781 f50a085584fda52bbc98ebb2c09cc039fbce591c M	src

**Comment by stsp** [comment]
So quick?? :)
Are you sure this is the problematic commit?
Can you try reverting it from devel and see?

**Comment by haenschen** [comment]
You taught me well but I don't know how to revert from devel and I don't want to mess up.
When doing git checkout 1820c4feb1ceb058c02c475be1533cbfc79cf4f7 after make realclean and compiling that version it doesn't work so I think yes.

**Comment by stsp** [comment]
Very simple:
git checkout devel
git revert 1820c4fe

**Comment by haenschen** [comment]
Yes, devel with the reverted commit works!

**Comment by stsp** [comment]
Very strange... Please fill in a separate report about that.
Now, how's your dongle feel?

**Comment by stsp** [comment]
Oh, this is already a separate report. :)

**Comment by stsp** [comment]
What kernel is this?
I think this is a problem of older kernels.
You can also try $_cpu_vm="kvm"

**Comment by stsp** [comment]
Is this still a problem?

**Comment by haenschen** [comment]
May I test this in VMware? Else I need to reinstall 32bit OS on the machines which is not possible for me within the next two weeks.

**Comment by haenschen** [comment]
What do I need to configure to recreate this? I set up a new Ubuntu 16.04 LTS 32bit
Linux PAPC 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 i686 i686 GNU/Linux

I can't do $_cpu_vm = "vm86"  as it says

```
ERROR: vm86 service not available in your kernel, the requested function is not implemented
ERROR: using CPU emulation for vm86()
```

If I use the standard "auto" it works fine but I guess that's not the thing to be tested.

**Comment by stsp** [comment]
Imho you only need to update your kernel:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1499089

**Comment by haenschen** [comment]
Ok I updated to 4.4.0-24 did sudo sysctl -w vm.mmap_min_addr=0 and I was again able to start vm86 dosemu but my application still crashes dosemu.

Reverting 1820c4f still fixes the issue.

**Comment by stsp** [comment]
Very bad.
If on line 298 you put "if 1"
instead of "if 0" but comment out 2
loadregister() lines a bit below, does
it still work?
Any chances to set up an ssh for me?

**Comment by andrewbird** [comment]
@stsp are you thinking that fs and gs are not preserved across the vm86* calls? I had a quick look at the kernel source and vm86old / vm86 syscalls are provided by the same function in the kernel. There seemed to be no difference in handling fs/gs between old and plus variants?

BTW don't you find it confusing that the kernel uses vm86old / vm86 syscall names whereas dosemu uses vm86 / vm86_plus, respectively?

@haenschen have you the boot.log and terminal output of the crash (with gdb installed) it would be good to see where the crash happens?

**Comment by stsp** [comment]
@andrewbird this was the case on 2.4 kernels.
This shouldn't be on 2.6, but I simply don't know
what to think up next. :)

The confusing names come from the fact that for
dosemu2 I initially wanted to use solely vm86old,
so in the sources I called it vm86: wouldn't it be silly
to suffix with "old" something you are going to use
permanently? But my hopes did not materialize
because of the small bug in vm86old: it raises SIGTRAP
on realmode interrupts 1 and 3, instead of returning
the proper code from vm86(). This can easily be fixed,
but I don't suppose kernel people are awaiting patches
for vm86old. :)

@haenschen already set up an ssh for me, hence the
stream of the installer and video fixes yesterday: I am
surprised how he got the things working at all, because
I was only seeing crashes and unworkable installations.

Now when things seem to settle, I'll try to debug the damn
thing BUT it is exceptionally difficult: dosemu works so
slowly under "ssh -X" one can hardly imagine. And to
reproduce the problem, I need to run the GUI prog! It
takes several minutes before it just _starts_ to draw something,
I was never been able to wait till it draws an entire screen...
Fortunately the problem seems to manifest when it just
starts drawing, so with some patience I'll probably get
something...

**Comment by stsp** [comment]
I actually have seen many people on the internet
saying that dosemu segfaults on start etc. Obviously
they were frustrated enough to immediately install
dosbox and not to bugreport here. Fortunately, on
@haenschen machine this all seems to happen at once.

**Comment by andrewbird** [comment]
X makes many calls over the network, and latency kills speed. You should try to use vncserver, performance will be much better as the round trip is local.

**Comment by stsp** [comment]
> X makes many calls over the network, and latency kills speed. You should try to use vncserver,

OKey, I try:
https://bugs.launchpad.net/ubuntu/+source/tightvnc/+bug/1597115

@haenschen machine is cool for bug-reporting, but is
horrible for debugging, as any possible bug seems to
trigger. I'll debug the vm86 problem one day, but we are
not quite there yet. :)

**Comment by haenschen** [comment]
Ok, what can I do? Is it still needed?

**Comment by stsp** [comment]
You can try to set up some other vnc server
that at least work. If not, I'll try myself tomorrow,
and will likely hit some bug again...

**Comment by haenschen** [comment]
Okay, you may keep on trying of course! If needed I may access the PC via Teamviewer. However the internet connection is not pretty fast but it should not take minutes to load DOSEMU..

I'll have physical access to the computer this weekend at latest BUT I don't need to use it.

**Comment by andrewbird** [comment]
If you have problems with tightvnc try installing vnc4server, it has always worked for me.

**Comment by stsp** [comment]
The vnc port there is unaccessible.
As well as pings do not float.
@haenschen could you please make
the vnc port accessible? I think it is blocked
by some external firewall.

**Comment by andrewbird** [comment]
If you still have ssh access, you could port forward over the ssh tunnel.



On Wed, 29 Jun 2016 14:23:58 -0700
Stas Sergeev <notifications@github.com> wrote:

> The vnc port there is unaccessible.
> As well as pings do not float.
> @haenschen could you please make
> the vnc port accessible? I think it is blocked
> by some external firewall.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/stsp/dosemu2/issues/130#issuecomment-229493379


-- 
Andrew Bird <ajb@spheresystems.co.uk>

**Comment by stsp** [comment]
I should tag another pre rather soon it seems.

**Comment by haenschen** [comment]
Port 5900 (vnc) should now be open/redirected

**Comment by andrewbird** [comment]
@stsp I think you need to alter the code inside the #if 0 to use the union too. After I change #if 0 to 1 for a test I see:
~~~
do_vm86.c: In function ‘do_vm86’:
do_vm86.c:432:22: warning: passing argument 1 of ‘true_vm86’ from incompatible pointer type [-Wincompatible-pointer-types]
     return true_vm86(x);
                      ^
do_vm86.c:400:12: note: expected ‘struct vm86_struct *’ but argument is of type ‘union vm86_union *’
 static int true_vm86(struct vm86_struct *x)
            ^
~~~

**Comment by stsp** [comment]
@haenschen but the bug is already closed. :)

@andrewbird done, but "who cares" was also among the
valid answers. :)

**Comment by haenschen** [comment]
Okay anything else to be tested or can I setup 64bit again?

**Comment by stsp** [comment]
I think you mentioned more regressions somewhere,
but they were probably in 64bit.
Thanks!

**Comment by stsp** [comment]
Btw, were you successful at testing this with vmware?
You mentioned vmware here a month ago.

**Comment by haenschen** [comment]
Okay.
I didn't try it in VMware as I hadnt enoguh spare time...

**Comment by andrewbird** [comment]
Thanks, that's a nice tidy up. :-)
