### ISSUE TITLE
Current master does not compile (‘in_indirect_dpmi_transfer’ undeclared)

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#138]
During "make" I get the error
```dpmi.c:479:3: error: ‘in_indirect_dpmi_transfer’ undeclared (first use in this function)```

I think, the initialization of ‘in_indirect_dpmi_transfer’ in "dpmi.c"
```
#if !DIRECT_DPMI_CONTEXT_SWITCH
static int in_indirect_dpmi_transfer;
#endif
```
should be
```
#if defined(__i386__) || !DIRECT_DPMI_CONTEXT_SWITCH
static int in_indirect_dpmi_transfer;
#endif
```
With this change, the compilation finished.

**Comment by stsp** [comment]
How typical...
Thanks for testing!
There are those old development branches from
which I keep merging the old bugs...
