### ISSUE TITLE
Textmode ---   ERROR: SMALLOC: Out Of Memory on alloc, requested=282624 

### ISSUE THREAD

**Issue by ccarcel** [stsp/dosemu2#143]
Hi,

I have been using DOSEMU 1.4.0.8 for some time, I had errors with memory ERROR: SMALLOC: Out Of Memory on alloc, requested=282624

I have download and install dosemu 2.0 I still am getting the same issue, there is much more memory than any dos machine where this old dbase complied app still works.

Any help would be much appreciated.

**Comment by ccarcel** [comment]
major = 136 minor = 0
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing built-in global.conf file.
CONF: config variable version_3_style_used unset
CONF: config variable version_3_style_used set
CONF: opened include file /etc/dosemu/dosemu.conf
CONF: closed include file /etc/dosemu/dosemu.conf
CONF: mapping driver = 'auto'
debug flags: -Da+cw
CONF: Disabling use of pentium timer
CONF: dosbanner on
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe400
CONF: DPMI-Server on (0x5000)
CONF: DPMI base addr = 0xffffffff
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: no, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout keyb-user
device: /etc/dosemu/floppy_dir type 4 h: 0  s: 0   t: 0 floppy A:
CONF: fastfloppy = 1
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -l -P lpt2  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver disabled.
device: /etc/dosemu/drives/c type 4 h: -1  s: -1   t: -1 drive C:
CONF: cdrom MSCD0001 on /dev/cdrom
CONF: config variable c_system unset
debug flags: -p
Linux kernel 3.10.0; CPU speed is 2266747000 Hz
CPU-EMU speed is 2267 MHz
CONF: running exclusively as ROOT: uid=0 (cached 0) gid=0 (cached 0)
DBG_FD already set
DOSEMU-2.0pre4 is coming up on Linux version 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64
Compiled with GCC version 4.9.2 -m64
CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -fno-stack-protector -fplan9-extensions -Wno-maybe-uninitialized -O2
WARN: vm86plus service not available in your kernel
WARN: using CPU emulation for vm86()
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 48Kb at 0xF4000 for 'r' (Dosemu reserved area)
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0217
initial segment bases: fs: 0x7f08caae4740  gs: (nil)
WARN: using non-zero memory base address 0x40fb3000.
WARN: You can use the better-tested zero based setup using
WARN: sysctl -w vm.mmap_min_addr=0
WARN: as root, or by changing the vm.mmap_min_addr setting in
WARN: /etc/sysctl.conf or a file in /etc/sysctl.d/ to 0.
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
Registering HWRAM, type=e base=0xff671000 size=0x400000
CONF: reserving 4096Kb at 0xFF671000 for 'e' (VGAEMU LFB)
CONF: reserving 4Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
SERIAL $Id$
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xF0000 for 'E' (EMS page frame)
CONF: reserving 140Kb at 0xC1000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

ERROR: SMALLOC: Out Of Memory on alloc, requested=81920
System info:
	linux-vdso.so.1 =>  (0x00007ffe322f5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efe06d81000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007efe06b7d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007efe0687a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007efe06672000)
	libc.so.6 => /lib64/libc.so.6 (0x00007efe062b1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efe06fa5000)
glibc 2.17
NPTL 2.17
00400000-0059a000 r-xp 00000000 fd:00 18229773                           /usr/bin/dosemu.bin
00799000-0079a000 r--p 00199000 fd:00 18229773                           /usr/bin/dosemu.bin
0079a000-007cb000 rw-p 0019a000 fd:00 18229773                           /usr/bin/dosemu.bin
007cb000-02336000 rw-p 00000000 00:00 0 
02e12000-02f97000 rw-p 00000000 00:00 0                                  [heap]
40624000-40a24000 rwxs 00110000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
40a30000-40a3f000 rw-p 00000000 00:00 0 
40b8d000-40b9c000 rw-p 00000000 00:00 0 
40fb3000-40fb5000 rwxs 00000000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
40fb5000-40fb6000 r-xs 00002000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
40fb6000-40fba000 rwxs 00003000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
40fba000-40fbb000 r-xs 00007000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
40fbb000-41053000 rwxs 00008000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41053000-41054000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41054000-41055000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41055000-41056000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41056000-41057000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41057000-41058000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41058000-41059000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41059000-4105a000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4105a000-4105b000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4105b000-4105c000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4105c000-4105d000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4105d000-4105e000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4105e000-4105f000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4105f000-41060000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41060000-41061000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41061000-41062000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41062000-41063000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41063000-41064000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41064000-41065000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41065000-41066000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41066000-41067000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41067000-41068000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41068000-41069000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41069000-4106a000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4106a000-4106b000 rwxs 00510000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
4106b000-41073000 rwxs 00110000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41073000-410af000 rwxs 000c0000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410af000-410b0000 r-xs 000fc000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410b0000-410b2000 rwxs 000fd000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410b2000-410b3000 r-xs 000ff000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410b3000-410b4000 rwxs 00100000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410b4000-410bc000 r-xs 00101000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410bc000-410bf000 rwxs 00109000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410bf000-410c0000 r-xs 0010c000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
410c0000-410c3000 rwxs 0010d000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41519000-41529000 r--s 00511000 00:11 51796                              /dev/shm/dosemu_20453 (deleted)
41529000-42194000 rwxp 00000000 00:00 0 
42194000-42195000 ---p 00000000 00:00 0 
42195000-4287e000 rwxp 00000000 00:00 0 
4287e000-4288e000 ---p 00000000 00:00 0 
4288e000-428d7000 rwxp 00000000 00:00 0 
428d7000-428de000 ---p 00000000 00:00 0 
428de000-428f8000 rwxp 00000000 00:00 0 
428f8000-428fe000 ---p 00000000 00:00 0 
428fe000-4292d000 rwxp 00000000 00:00 0 
4292d000-4292e000 ---p 00000000 00:00 0 
100000000-100001000 rw-p 00000000 00:00 0 
7f08bdbd8000-7f08bfe35000 rw-p 00000000 00:00 0 
7f08bfe35000-7f08bfe37000 r-xp 00000000 fd:00 35913973                   /usr/lib64/libXau.so.6.0.0
7f08bfe37000-7f08c0037000 ---p 00002000 fd:00 35913973                   /usr/lib64/libXau.so.6.0.0
7f08c0037000-7f08c0038000 r--p 00002000 fd:00 35913973                   /usr/lib64/libXau.so.6.0.0
7f08c0038000-7f08c0039000 rw-p 00003000 fd:00 35913973                   /usr/lib64/libXau.so.6.0.0
7f08c0039000-7f08c005a000 r-xp 00000000 fd:00 35914029                   /usr/lib64/libxcb.so.1.1.0
7f08c005a000-7f08c0259000 ---p 00021000 fd:00 35914029                   /usr/lib64/libxcb.so.1.1.0
7f08c0259000-7f08c025a000 r--p 00020000 fd:00 35914029                   /usr/lib64/libxcb.so.1.1.0
7f08c025a000-7f08c025b000 rw-p 00021000 fd:00 35914029                   /usr/lib64/libxcb.so.1.1.0
7f08c025b000-7f08c026c000 r-xp 00000000 fd:00 35914138                   /usr/lib64/libXext.so.6.4.0
7f08c026c000-7f08c046b000 ---p 00011000 fd:00 35914138                   /usr/lib64/libXext.so.6.4.0
7f08c046b000-7f08c046c000 r--p 00010000 fd:00 35914138                   /usr/lib64/libXext.so.6.4.0
7f08c046c000-7f08c046d000 rw-p 00011000 fd:00 35914138                   /usr/lib64/libXext.so.6.4.0
7f08c046d000-7f08c05a5000 r-xp 00000000 fd:00 35914135                   /usr/lib64/libX11.so.6.3.0
7f08c05a5000-7f08c07a5000 ---p 00138000 fd:00 35914135                   /usr/lib64/libX11.so.6.3.0
7f08c07a5000-7f08c07a6000 r--p 00138000 fd:00 35914135                   /usr/lib64/libX11.so.6.3.0
7f08c07a6000-7f08c07ab000 rw-p 00139000 fd:00 35914135                   /usr/lib64/libX11.so.6.3.0
7f08c07ab000-7f08c07bb000 r-xp 00000000 fd:00 559448                     /usr/lib64/dosemu/libplugin_X.so
7f08c07bb000-7f08c09ba000 ---p 00010000 fd:00 559448                     /usr/lib64/dosemu/libplugin_X.so
7f08c09ba000-7f08c09bb000 r--p 0000f000 fd:00 559448                     /usr/lib64/dosemu/libplugin_X.so
7f08c09bb000-7f08c09c0000 rw-p 00010000 fd:00 559448                     /usr/lib64/dosemu/libplugin_X.so
7f08c09c0000-7f08c09c2000 rw-p 00000000 00:00 0 
7f08c09c2000-7f08c09e7000 r-xp 00000000 fd:00 33628194                   /usr/lib64/libtinfo.so.5.9
7f08c09e7000-7f08c0be7000 ---p 00025000 fd:00 33628194                   /usr/lib64/libtinfo.so.5.9
7f08c0be7000-7f08c0beb000 r--p 00025000 fd:00 33628194                   /usr/lib64/libtinfo.so.5.9
7f08c0beb000-7f08c0bec000 rw-p 00029000 fd:00 33628194                   /usr/lib64/libtinfo.so.5.9
7f08c0bec000-7f08c0c12000 r-xp 00000000 fd:00 34042520                   /usr/lib64/libncurses.so.5.9
7f08c0c12000-7f08c0e11000 ---p 00026000 fd:00 34042520                   /usr/lib64/libncurses.so.5.9
7f08c0e11000-7f08c0e12000 r--p 00025000 fd:00 34042520                   /usr/lib64/libncurses.so.5.9
7f08c0e12000-7f08c0e13000 rw-p 00026000 fd:00 34042520                   /usr/lib64/libncurses.so.5.9
7f08c0e13000-7f08c0e18000 r-xp 00000000 fd:00 35670873                   /usr/lib64/libgpm.so.2.1.0
7f08c0e18000-7f08c1018000 ---p 00005000 fd:00 35670873                   /usr/lib64/libgpm.so.2.1.0
7f08c1018000-7f08c1019000 r--p 00005000 fd:00 35670873                   /usr/lib64/libgpm.so.2.1.0
7f08c1019000-7f08c101a000 rw-p 00006000 fd:00 35670873                   /usr/lib64/libgpm.so.2.1.0
7f08c101a000-7f08c101c000 r-xp 00000000 fd:00 559452                     /usr/lib64/dosemu/libplugin_gpm.so
7f08c101c000-7f08c121b000 ---p 00002000 fd:00 559452                     /usr/lib64/dosemu/libplugin_gpm.so
7f08c121b000-7f08c121c000 r--p 00001000 fd:00 559452                     /usr/lib64/dosemu/libplugin_gpm.so
7f08c121c000-7f08c121d000 rw-p 00002000 fd:00 559452                     /usr/lib64/dosemu/libplugin_gpm.so
7f08c121d000-7f08c1a1d000 rw-p 00000000 00:00 0 
7f08c1a1d000-7f08c2b2d000 rw-s 00000000 00:11 51796                      /dev/shm/dosemu_20453 (deleted)
7f08c2b2d000-7f08c2f2d000 rw-p 00000000 00:00 0                          [stack:20453]
7f08c2f2d000-7f08c3024000 r-xp 00000000 fd:00 33628497                   /usr/lib64/libslang.so.2.2.4
7f08c3024000-7f08c3224000 ---p 000f7000 fd:00 33628497                   /usr/lib64/libslang.so.2.2.4
7f08c3224000-7f08c3228000 r--p 000f7000 fd:00 33628497                   /usr/lib64/libslang.so.2.2.4
7f08c3228000-7f08c3241000 rw-p 000fb000 fd:00 33628497                   /usr/lib64/libslang.so.2.2.4
7f08c3241000-7f08c32a5000 rw-p 00000000 00:00 0 
7f08c32a5000-7f08c32ae000 r-xp 00000000 fd:00 559456                     /usr/lib64/dosemu/libplugin_term.so
7f08c32ae000-7f08c34ad000 ---p 00009000 fd:00 559456                     /usr/lib64/dosemu/libplugin_term.so
7f08c34ad000-7f08c34ae000 r--p 00008000 fd:00 559456                     /usr/lib64/dosemu/libplugin_term.so
7f08c34ae000-7f08c34b0000 rw-p 00009000 fd:00 559456                     /usr/lib64/dosemu/libplugin_term.so
7f08c34b0000-7f08c34b1000 rw-p 00000000 00:00 0 
7f08c34b1000-7f08c34bb000 r-xp 00000000 fd:00 559450                     /usr/lib64/dosemu/libplugin_console.so
7f08c34bb000-7f08c36bb000 ---p 0000a000 fd:00 559450                     /usr/lib64/dosemu/libplugin_console.so
7f08c36bb000-7f08c36bc000 r--p 0000a000 fd:00 559450                     /usr/lib64/dosemu/libplugin_console.so
7f08c36bc000-7f08c36bd000 rw-p 0000b000 fd:00 559450                     /usr/lib64/dosemu/libplugin_console.so
7f08c36bd000-7f08c9be4000 r--p 00000000 fd:00 34042477                   /usr/lib/locale/locale-archive
7f08c9be4000-7f08c9d9a000 r-xp 00000000 fd:00 33618323                   /usr/lib64/libc-2.17.so
7f08c9d9a000-7f08c9f9a000 ---p 001b6000 fd:00 33618323                   /usr/lib64/libc-2.17.so
7f08c9f9a000-7f08c9f9e000 r--p 001b6000 fd:00 33618323                   /usr/lib64/libc-2.17.so
7f08c9f9e000-7f08c9fa0000 rw-p 001ba000 fd:00 33618323                   /usr/lib64/libc-2.17.so
7f08c9fa0000-7f08c9fa5000 rw-p 00000000 00:00 0 
7f08c9fa5000-7f08c9fac000 r-xp 00000000 fd:00 33618329                   /usr/lib64/librt-2.17.so
7f08c9fac000-7f08ca1ab000 ---p 00007000 fd:00 33618329                   /usr/lib64/librt-2.17.so
7f08ca1ab000-7f08ca1ac000 r--p 00006000 fd:00 33618329                   /usr/lib64/librt-2.17.so
7f08ca1ac000-7f08ca1ad000 rw-p 00007000 fd:00 33618329                   /usr/lib64/librt-2.17.so
7f08ca1ad000-7f08ca2ae000 r-xp 00000000 fd:00 34764641                   /usr/lib64/libm-2.17.so
7f08ca2ae000-7f08ca4ad000 ---p 00101000 fd:00 34764641                   /usr/lib64/libm-2.17.so
7f08ca4ad000-7f08ca4ae000 r--p 00100000 fd:00 34764641                   /usr/lib64/libm-2.17.so
7f08ca4ae000-7f08ca4af000 rw-p 00101000 fd:00 34764641                   /usr/lib64/libm-2.17.so
7f08ca4af000-7f08ca4b2000 r-xp 00000000 fd:00 35104141                   /usr/lib64/libdl-2.17.so
7f08ca4b2000-7f08ca6b1000 ---p 00003000 fd:00 35104141                   /usr/lib64/libdl-2.17.so
7f08ca6b1000-7f08ca6b2000 r--p 00002000 fd:00 35104141                   /usr/lib64/libdl-2.17.so
7f08ca6b2000-7f08ca6b3000 rw-p 00003000 fd:00 35104141                   /usr/lib64/libdl-2.17.so
7f08ca6b3000-7f08ca6c9000 r-xp 00000000 fd:00 35104159                   /usr/lib64/libpthread-2.17.so
7f08ca6c9000-7f08ca8c9000 ---p 00016000 fd:00 35104159                   /usr/lib64/libpthread-2.17.so
7f08ca8c9000-7f08ca8ca000 r--p 00016000 fd:00 35104159                   /usr/lib64/libpthread-2.17.so
7f08ca8ca000-7f08ca8cb000 rw-p 00017000 fd:00 35104159                   /usr/lib64/libpthread-2.17.so
7f08ca8cb000-7f08ca8cf000 rw-p 00000000 00:00 0 
7f08ca8cf000-7f08ca8f0000 r-xp 00000000 fd:00 35104134                   /usr/lib64/ld-2.17.so
7f08ca90d000-7f08ca92d000 rwxp 00000000 00:00 0 
7f08ca92d000-7f08ca92e000 rw-p 00000000 00:00 0 
7f08ca92e000-7f08ca92f000 ---p 00000000 00:00 0 
7f08ca92f000-7f08ca93f000 rwxp 00000000 00:00 0 
7f08ca950000-7f08ca970000 rwxp 00000000 00:00 0 
7f08ca970000-7f08caae8000 rw-p 00000000 00:00 0 
7f08caae8000-7f08caaef000 r--s 00000000 fd:00 50432063                   /usr/lib64/gconv/gconv-modules.cache
7f08caaef000-7f08caaf0000 rw-p 00000000 00:00 0 
7f08caaf0000-7f08caaf1000 r--p 00021000 fd:00 35104134                   /usr/lib64/ld-2.17.so
7f08caaf1000-7f08caaf2000 rw-p 00022000 fd:00 35104134                   /usr/lib64/ld-2.17.so
7f08caaf2000-7f08caaf3000 rw-p 00000000 00:00 0 
7ffd5e560000-7ffd5e581000 rw-p 00000000 00:00 0 
7ffd5e5d4000-7ffd5e5d6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Debug info:
gdb /usr/bin/dosemu.bin
attach 20453
info registers
thread apply all backtrace full
detach
quit
sh: gdb: command not found

done backtrace
leavedos(handle_dosemu_keys:45|0) called - shutting down
1 threads still active
leavedos thread started
leavedos thread ended
coopthreads stopped
======================= LEAVE CPU-EMU ===============

**Comment by stsp** [comment]
Please update to git branch "devel".

**Comment by stsp** [comment]
If you can't update from git, then please install gdb
and re-do the log.
