### ISSUE TITLE
Support for swapping disk images

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#148]
There is currently no way to swap to another disk image once dosemu is started. Implementing this would allow running many installers on systems which do not have a physical floppy drive.

A nice feature would be a shortcut that could be used to cycle through disks if an obvious pattern can be deduced. A directory with files named disk1.img, disk2.img and disk3.img, disk1.img is attached as a: and the shortcut would remove disk1.img and let disk2.img be accessible through a:. Another way could be to specify multiple files for a drive and let the user cycle through them.

**Comment by stsp** [comment]
The first step would be for dosemu to
close/reopen the image files, so that the user
can swap them by hands (or by a script, or/and
with symlink).
Does manual replacing work right now, or dosemu
does not re-open an image files?

**Comment by runderwo** [comment]
Good idea.  this was my silly workaround:
http://home.icequake.net/~nemesis/blog/index.php/archives/583

**Comment by jschwartzenberg** [comment]
No, when I tested it, I couldn't get it to work (at least with installers).

**Comment by stsp** [comment]
@runderwo 404 URL

**Comment by stsp** [comment]
Ok, this is what we can fix (if someone have
enough time).

**Comment by jschwartzenberg** [comment]
It seems runderwo's hosting is having some issues. I managed to open the page once. His trick is to modify the image file itself which is attached to dosemu. He uses mtools to perform the operations on the same file that dosemu is using as a disk.

**Comment by stsp** [comment]
Hmm, in this case you can perhaps
"cp" one image over another.
Anyway, dosemu should re-open them eventually.

**Comment by runderwo** [comment]
Hmm, sorry about that server problem, it looks like anti-DoS protection went crazy.

**Comment by stsp** [comment]
> No, when I tested it, I couldn't get it to work (at least with installers).

When was that?
Looking at the code, it seems it would always re-open the
image. Please provide the -D9+d log.

**Comment by jschwartzenberg** [comment]
My apologies! My memory is flawed. You actually fixed it and I reported that I had it working this way:
https://sourceforge.net/p/dosemu/bugs/488/
I would need to retest though.

So the only thing that's missing is some kind of user interface. My original post describes something which now also seems complicated to me. The easiest solution, allow specifying multiple multiple images on the command line for a single drive and come up with a keyboard shortcut to cycle through them. If it's really hard to come up with a good shortcut, maybe it would be an idea to use those multimedia keys that many keyboards nowadays have and that dos programs will never use. My notebook has XF86AudioPrev and XF86AudioNext for instance which could make sense.

**Comment by stsp** [comment]
Not sure.
How about the user interface on linux side?
You can write a simple script that swaps an images,
and run it in another terminal.

**Comment by stsp** [comment]
So unless there is a compelling use-case, or a patch,
I am going to close this. This is a task for GUI, which
we don't have. And even if there is a GUI, there would
still be an open question whether that gui should just
manipulate the symlinks, or the functionality should be
implemented on dosemu side. That question is not simple.
So if someone provides an implementation then fine,
but I don't think I am going to work on that.
