### ISSUE TITLE
modemu support

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#164]
I created a "modemu" branch and imported the
modemu sources. I wonder if maybe Ryan Underwood
have some test-case for this and an interest to do some
work. :) I remember Ryan was trying some BBS games.

**Comment by runderwo** [comment]
BBS games hand the console over to the comport (or fossil driver).  Where a modem emulator could be useful is for a DOS BBS software itself to pretend to answer the phone, for example.

**Comment by runderwo** [comment]
Also could simulate modem head-to-head play in doom, duke3d, etc.

**Comment by stsp** [comment]
For doom and duke we have an IPX support.
In fact, I used doom and GTA as an IPX test-cases. :)

modemu makes a telnet connection out of serial port.
dosbox seem to have that functionality too.
In principle, I might be able to test it by just installing
a telnet server locally, but I don't understand the real
use-case so far.
Also see here:
https://sourceforge.net/p/dosemu/feature-requests/76/

**Comment by stsp** [comment]
@runderwo Would be nice if you can test the new stuff.
