### ISSUE TITLE
Tristan pinball does not work properly with KVM enabled

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#168]
After the fixes for the KVM support (#166), the Tristan pinball game still gives the invalid address error. It happens at rather random moments but it's pretty much impossible to really start playing because it will occur soon enough. It seems this only happens with the 256 color version of the game not with the 16 color version.

More information about the game: http://www.abandonia.com/en/games/1044/Tristan+Pinball.html

**Comment by bolle732** [comment]
I can reproduce the same effect with PC/GEOS. Using its VESA driver in 800x600 and 16 colors works stable as far I could test it. Using 256 colors or more, DOSEmu terminates in seconds with the "KVM: KVM_RUN: Invalid address".

If I can do more tests, please instruct me how to do it.

**Comment by bartoldeman** [comment]
Could you try PR #172?

**Comment by jschwartzenberg** [comment]
Yep, that solves the problem. Tested the other games as well, no regressions!

**Comment by bolle732** [comment]
I will test the PR on Monday when I have access to my 64-bit machine. Here at home, I'm still on 32-bit.

**Comment by bolle732** [comment]
Tonight, I upgraded my 32-bit Ubuntu from 12.04 to 16.04. It seems that vm86plus isn't compiled into the new kernel anymore. But I was lucky, that DOSEmu2 with KVM now works on that 32-bit machine and with the patch from PR #172, I can now use high colors. Tested with 64k. Will still do tests on the 64-bit machine.

**Comment by bolle732** [comment]
Now, I've tested the patch on my 64-bit Ubuntu 15.10 installation. It works there too. I didn't encounter any other problem with different resolution and colour deeps. For me it would be great if this 2-liner gets into master. Cheers.

**Comment by stsp** [comment]
This was reported to have regressed on 10a7aa7.
