### ISSUE TITLE
Wacky Wheels performance/timing regression

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#169]
There is a regression in Wacky Wheels for a while already, somehow I noticed it only recently. The game appears to be mostly running fine, but the speed of the race, once you actually get in the race, is very slow. It happens with both $_cpu_emu kvm and emulated. I did a bisect and got this result:
```
c1388d3b897f90f0737afb4fb8303c1ba3b7ee45 is the first bad commit
commit c1388d3b897f90f0737afb4fb8303c1ba3b7ee45
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Jan 23 23:32:52 2016 +0300

    dpmi: move fault handling to dosemu context [#128]
    
    This change was suggested by Bart and is presumably helping
    to reduce his kvm-dpmi patch.
    This was one of the most difficult things to implement, for
    almost no reason. :)

:040000 040000 7449c64b0d07592fc79158f25a403bc32e1016b7 a6ef08a0feaee0f11e779c176716525a3ee61dfa Msrc
```

More information about the game: http://www.abandonia.com/en/games/11/Wacky+Wheels.html

**Comment by stsp** [comment]
It is actually much better to specify only
the commit hash, rather than the full msg as
the code. When you specify the hash like this:
c1388d3b8, github makes it a link to a commit
itself.

**Comment by jschwartzenberg** [comment]
Thanks, I indeed didn't know that!

**Comment by stsp** [comment]
Yes, reproducible.

**Comment by stsp** [comment]
Fixed in wacky_fix branch.

**Comment by stsp** [comment]
OK, I've finally solved this mystery.
It turned out to be a conglomerate of multiple problems:
coopth, dpmi, instremu, signals etc.
The good testing is needed.

**Comment by stsp** [comment]
Now all the involved subsystems got the
needed fix, and I made sure every separate
fix fixes the problem alone. Hope together
they will not culminate into another extremely
elusive problem somewhere.

Btw, I've found that Wacky locks up completely
if you set $_cli_timeout=(off). If not for that
finding, I would probably never able to debug this.
(of course this is now also fixed)
