### ISSUE TITLE
dosemu window not properly refreshed in SDL mode (2.0pre1-288.gb611afe)

### ISSUE THREAD

**Issue by fhanzlik** [stsp/dosemu2#17]
devel 288.gb611afe (same seems be in 271.g21f8c1e) in SDL mode, dosemu window is not refreshed when I pull other window over dosemu window (see first attached screenshot), or when switch to another windows and then back to dosemu (second screenshot, after switching to xterm and back with ALT/TAB). This occurs with default dosemu.conf with '$_X_font = "vga"' or some other font selected.

When '$_X_font' isn't specified, this behaves slightly differently: when pull some window over dosemu window, then again traces remain on dosemu window, but then when I activate dosemu window, that dosemu window after some (short, but very perceivable time - almost 0.5 seconds) refresh and is displayed rightly.
When I switch to another window (xterm in this case) and back to dosemu window, then I again some short time (0.5 sec) see text from terminal and graphic from switching menu remained on dosemu window, and then is dosemu window rightly refreshed and is displayed fine.

This problem does not appear in X11 mode (dosemu -X), no matter when I specify $_X_font or not - in both cases is all fine.

Tested on Fedora 19 i686, SDL2-2.0.3
![other_window_gragged_over_the_dosemu_window](https://cloud.githubusercontent.com/assets/9540755/5889668/6810a3da-a433-11e4-8a3e-760d7245231a.png)
![switching_to_xterm_and_back_to_dosemu_with_alt-tab](https://cloud.githubusercontent.com/assets/9540755/5889670/7524cea2-a433-11e4-81be-5b786f7fea04.png)

**Comment by fhanzlik** [comment]
Just I tried 295.gd2bb330, and it seems problem is solved - for both built-in and specified X_font.
Thanks!

**Comment by stsp** [comment]
Could you please try also 2f6655713?
If it still works, please close this. :)

**Comment by fhanzlik** [comment]
Just tried it, 296.g2f66557 work well, tested in SDL and X modes, both with built-in and user-specified fonts. Thanks!
