### ISSUE TITLE
dumb mode is broken when DOS cmd is specified

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#173]
This bug is very strange.
dosemu -dumb
works fine, but:
dosemu -dumb ttt
doesn't print anything on terminal, while:
dosemu -dumb -K ttt
works fine again...

**Comment by andrewbird** [comment]
Does -td work for you? It seems odd that we generally accept args like -S and --libdir like gnu progs but also take -dumb, which we users expect to be parsed as -d -u -m -b. IMHO it would be better to change that to --dumb if we really need it? Is there a difference with -td?

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 08/05/2016  03:33  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Subject [stsp/dosemu2] dumb mode is broken when DOS cmd is specified (#173) 
 
This bug is very strange.
dosemu -dumb
works fine, but:
dosemu -dumb ttt
doesn't print anything on terminal, while:
dosemu -dumb -K ttt
works fine again...

**Comment by andrewbird** [comment]
It seems to me that it stails in dumb mode when the dos command cannot be found on disk. I find that if i use

command|result
-------|-----
-td ver            | command stails
-td -E ver    | command succeeds
-t ver           | get 'No such file ver'
-t -E ver       | command succeeds
-td test-imagedir/drives/c/version.bat | with a linux path to batch file containing 'ver' succeeds


So I have a couple of thoughts:

1/  According to the manpage (I know this is not much of a reference) the only difference between running with -E and not is supposed to be just whether dosemu exits after running the command. I see a difference that it causes DOS internal commands to be runnable, not just batch files or executables. So in your example, is 'ttt' a path to a batch file or executable?
2/ Perhaps if your 'ttt' batch file or executable cannot be found, the error message displayed is causing the dumb terminal mode to expect input, but the display is not echoing keys typed. I found I could type 'exitemu' to get out when stalled, but typing 'ugetcwd' produced no output.

**Comment by stsp** [comment]
> also take -dumb, which we users expect to be parsed as -d -u -m -b.

Or, if -d takes an argument, then it can be parsed as
"-d umb" and disable UMB. :8ball: 

> IMHO it would be better to change that to --dumb if we really need it? Is there a difference with -td?

-dumb is only in dosemu wrapper script. It passes -td to
the binary. This is a compatibility thing, can't be removed.
Even if you also send the patch to openwatcom to use
-td instead of -dumb, this won't work on dosemu1 as it
doesn't have -td.

> 1/ According to the manpage (I know this is not much of a reference) the only difference
> between running with -E and not is supposed to be just whether dosemu exits after running
> the command.

manpage needs fixing. I updated it.

**Comment by stsp** [comment]
It turned out this behaviour was by design, not
a bug... But I "fixed" it anyway.

**Comment by andrewbird** [comment]
command|observation|result
-----------------------------|-----|----
-td ver          |  get 'No such file ver', but no stall, user left in DOS | ???
-td -E ver     | command ok, user left in DOS | Good
-td -T -E ver | command ok, user returned to Unix | Good
-td -q -E ver | command ok, some output suppressed, user left in DOS | Good
-td -q -T -E ver | command ok, some output suppressed, user returned to Unix | Good
-t ver           | get 'No such file ver', but no stall, user left in DOS | Good
-t -E ver       | command ok, user left in DOS | Good
-t -T -E ver   | command ok, user returned to Unix | Good
-td drives/c/version.bat | batch file ok, user left in DOS| ???

Looks good to me. My only slight concern is that bare '-td command' leaves user in DOS. I believe that was the previous behaviour for failure, but for success the command returned to Unix. I also note that the return code from dosemu.bin is 74, on both success and failure. I'm not sure if that ever propagated properly, but it seems odd that on success it should return anything other than zero.

**Comment by stsp** [comment]
Yes, but I explicitly mentioned in man page that
specifying the command without either -E or -K is
discouraged. And I added -T to explicitly specify
the desired behaviour, so the default for (discouraged)
no-switch passing was broken again. Fortunately
openwatcom is not affected because they put "exitemu"
at the end of their batch files.
Well in principle, since this way of passing an arg
was left for compatibility, lets not break the compatibility.
I'll amend the patch now.

**Comment by stsp** [comment]
Am I the only one thinking that unix.com shold
execute unix commands and not DOS commands?
Oh well. :(

**Comment by stsp** [comment]
I implemented the return code.
