### ISSUE TITLE
re-introduce system.com

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#174]
unix.com currently executes both unix and DOS
commands. There was in the past system.com, that,
strangely enough, also executed unix commands,
and for that it was removed.
It would be good to re-introduce system.com, but
for the DOS commands, leaving that functionality
in unix.com for compatibility.

**Comment by andrewbird** [comment]
If we do this, I think we should replace 'unix -e' function with a msg to convert to 'system -e' else there's not much point in just duplicating functionality. Or is there something I'm missing?

**Comment by stsp** [comment]
Yes.
I added the "unix_rework" branch where I did that
and a bit more.

**Comment by stsp** [comment]
So as the old functionality is preserved
(with the warning), I don't expect anyone
to hate this patch too much.
But, as it is mostly a clean-up stuff, anyone
can vote against it.

**Comment by stsp** [comment]
OK, so I merged the change.
As you can see, there is no functionality
duplication on the source level: unix.com
simply calls system_main() to delegate the
compatibility functionality.
And the duplicated functionality on the binary
level gives the warning.

**Comment by andrewbird** [comment]
Yes, looks fine,  although I didn't actually test it yet! 

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 14/05/2016  15:53  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Comment <comment@noreply.github.com> 
Subject Re: [stsp/dosemu2] re-introduce system.com (#174) 
 
OK, so I merged the change.
As you can see, there is no functionality
duplication on the source level: unix.com
simply calls system_main() to delegate the
compatibility functionality.
And the duplicated functionality on the binary
level gives the warning.

**Comment by haenschen** [comment]
Is there any new freedos package (dosemu-freedos-bin.tgz) available? I am still using the dosemu1 one but by default the autoexec now produces these warnings.

**Comment by stsp** [comment]
> Is there any new freedos package (dosemu-freedos-bin.tgz) available?

Firstly, where do you get it...
If you get it from here:
https://sourceforge.net/projects/dosemu/files/dosemu-freedos/1.0/
then the name would be dosemu-freedos-1.0-bin.tgz, not dosemu-freedos-bin.tgz.

Secondly, the default config/autoexec from that archive are
now ignored. dosemu2 now installs their own, updated ones.
If you simply use the previous install, you can either ignore
the warnings (don't worry, I won't break the compatibility, the
warnings are just a hint that something newer is available), or
you can re-install freedos, and dosemu will update things.
