### ISSUE TITLE
Supporting multiple DosEmu instances or versions

### ISSUE THREAD

**Issue by kalpha2** [stsp/dosemu2#175]
as per snippets from 
<<    FreeDOS is not delivered #93   >>
and
<<   problems with --Flibdir #80    >>

It wasn't so much wanting dosemu1 and 2 to be separate, but to be able to run differing versions or builds of dosemu. At the moment that would essentially mean between 1 and 2, where for me dosemu 1 (largely) represents a stable build. So if dosemu2 could be configurable to run in isolation from dosemu1 would be a bonus for me. But going forward I would hope one day to get a stable version of 2 and then be able to run another instance which I could tinker with the build, test patches, or newer versions, etc. again without destabilising a stable working environment. 
For me if this was only achieved by a compile time option or code tweak(s) would be fine.... just need a bit of doco / pointers as to what needs tweaking where.

If dosemu2 is introducing new, better, but potential incompatibilities maybe it should be renamed?
But on the other hand if it is largely intended to be a drop in replacement it should not be?
Maybe detecting if dosemu (1) is present and ask what you want to do?
i.e. overwrite existing version or deploy as dosemu2 (or insert name prompt. and type how you want known .. dosemu2-PatchedXYZ).
If detecting dosemu1 and overwriting could that get messy with differing distro package installs of dosemu(1) ?

<<
Won't this mean users of both versions that have a common drive will need to set or order the path according to which version of dosemu has been started?
>>
I currently tweak my setups so for instance DosBox and DosEmu have their own C: drive, but share the same (common) D: drive.
I keep C: drive as OS specific and D: drive for DOS apps and data.

**Comment by stsp** [comment]
OK, I implemented some new functionality to allow
the tools being movable, but unfortunately this didn't
help with compatibility to dosemu1. It is still good because
I wanted to move dosemu tools outside of freedos dir
long ago, but it doesn't solve this particular problem
unfortunately, because then dosemu1 needs a separate
config.sys. Plus dosemu1 lacks new tools (sound.com,
system.com, lredir2.com), so also autoexec should be
different (or use compatibility modes that were preserved
for all tools).

> If dosemu2 is introducing new, better, but potential incompatibilities maybe it should be renamed?

Very probably.
In most cases it was a drop-in replacement, but now
it is becoming obvious it will not always be... Because
that prevents changes to config.sys and forces to
use the compatibility modes in autoexec.bat when using
dosemu tools.

**Comment by stsp** [comment]
> it is becoming obvious it will not always be... Because
> that prevents changes to config.sys and forces to
> use the compatibility modes in autoexec.bat when using
> dosemu tools.

I was confused and was telling about using dosemu1 with
dosemu2-created setup, which is not what you ask. Please
ignore the prev comment.
I've just commited one more compat change, and now
dosemu2 should again load the dosemu1's setup fine
(but the opposite is impossible).
Actually, I am not sure I know what problems you had
when running dosemu2 on dosemu1 setup. It should work,
but I haven't tested that. There could be warnings about
the compatibility modes etc, but it should work.

**Comment by stsp** [comment]
Of course it should work only after you do "make install",
so that it will replace the old commands by the new ones
(and the per-user install has a symlinks to it, so it should
see the new ones immediately).
Maybe you wanted to have dosemu1 and 2 in parallel,
without doing "make install" before running each other -
this is not possible. You need to run "make install" to
whatever instance you want to run, and the setup should
be from dosemu1. Then I think both can work, but please
check.

**Comment by kalpha2** [comment]
I'll be honest, I can't totally remember.....
I will have been running dosemu1 from the LMDE2 package install.
Before whatever I did with dosemu2....I made copies of 
	/usr/bin/dosemu
	/usr/bin/dosemu.bin
	/usr/lib/dosemu/
	/etc/dosemu/
	/home/user/.dosemu/

When I (thought I had installed) dosemu2, it complained about not finding freedos and then about lredir being deprecated and use lredir2.... I did get it into some sort of running state, but some DOS application development issue I had at the time was still present in dosemu2.... so then I wanted to revert... but I must have failed to copy back something and was running out of time... so I just re-installed the LMDE2 doesmu1 package.

But yes, for me I would really like to be able to parallel more than one copy of dosemu.
For now that would be dosemu1 and dosemu2-dev?, but in the future I would hope and like if it could be dosemu2-stable and dosemu2-dev, and maybe even another dosemu2-dev+patchXYZ or dosemu2-dev+myHack.......

**Comment by stsp** [comment]
> When I (thought I had installed) dosemu2, it complained about not finding freedos
> and then about lredir being deprecated and use lredir2....

So if it wasn't finding freedos where dosemu1 did, this is
a compatibility issue that should be resolved. The deprecation
warnings do not harm. I am going to support dosemu1 setups
until it becomes to difficult and while someone tests them.

> development issue I had at the time was still present in dosemu2....
> so then I wanted to revert... but I must have failed to copy back something

Likely /usr/share/dosemu was forgotten. ~/.dosemu/drives/*
has symlinks to there, so it must be replaced.
I have already started curing this.

> For now that would be dosemu1 and dosemu2-dev?, but in the future I would hope and like if it
> could be dosemu2-stable and dosemu2-dev, and maybe even another dosemu2-dev+patchXYZ
> or dosemu2-

This will be possible for the future dosemu versions, but
never for dosemu1. To restore dosemu1, you need to re-install
it or recover its /usr/share/dosemu (other parts of dosemu1
are relocatable and can use any prefix, or be started right out
of a compilation tree).

**Comment by kalpha2** [comment]
jfi
<<  /usr/share/dosemu  >>
this doesn't exist (for dosemu1) in LMDE or Debian Wheezy units (from their respective packaged installs of dosemu1)

**Comment by stsp** [comment]
Where do they store dosemu tools?

**Comment by kalpha2** [comment]
if you mean things like lredir (generic.com) they are in 
   /usr/lib/dosemu/drive_z/dosemu
and there is also a symlink to this location from
   /usr/lib/dosemu/~commands

**Comment by stsp** [comment]
Which means you preserved those...
Well, if you can find out what exactly went wrong
and the way to reproduce, please reopen.
For now I close.

**Comment by kalpha2** [comment]
it looks like my  /usr/lib/dosemu/drive_z/dosemu  ended up with mixture of dosemu1 and 2, as I can see lredir2 in there .... haven't got time at moment to do clean install but will look to and keep notes.
With the changes you have made, will dosemu2 now make install into a separate location to allow parallel run with dosemu1 ? Are they in the main branch or another?

**Comment by stsp** [comment]
> it looks like my /usr/lib/dosemu/drive_z/dosemu ended up with mixture of dosemu1 and 2,
> as I can see lredir2 in there

dosemu2 is trying to purge dosemu1 on install, but
dosemu1 doesn't do so, so lredir2 is expected.
If after dosemu2 install you see some dosemu1 remnants
together with dosemu2 files, then let me know and I'll
add the removal.

> With the changes you have made, will dosemu2 now make install into a separate
> location to allow parallel run with dosemu1 ? Are they in the main branch or another?

In "devel".
It always allowed the separate location for installing,
but the problems started to happen when the symlink
to freedos/tools is created from ~/.dosemu/drives/d. If
another dosemu installs its tools to a separate location,
that symlink would still point to the old location, so the
new tools are unreachable from dos.
This should now be fixed.
