### ISSUE TITLE
use html docs by default

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#183]
Currently the docs are converted to plaintext,
and many things (like URLs) are lost in the process.
I'd like to switch to html docs.
So unless people know this shouldn't be done
(eg some distro policies that prevent this), I'll switch
to html.

**Comment by kalpha2** [comment]
Depends on which docs you are referring to. I have some sites where there is no X and units are off the web, if I was at one of those and wanted to refer to something in the docs, then html would be a pain in that scenario. Maybe could have two folders \txt and \html ?

**Comment by stsp** [comment]
The ones in a "doc" dir of dosemu sources.
It would be possible to have both, but looking
into /usr/share/doc I don't see it as an existing
practice. Some projects put htmls, some - only
plain text, some put both. But those both are with
the different content. I don't see any that put both
text and html with the _same_ content. So I am
inclined to just move to html. You don't need X
for html, all you need is lynx.

Would be nice if someone who maintains and/or
packages some other projects can comment on that.
