### ISSUE TITLE
Installing with DESTDIR set creates bad symlinks

### ISSUE THREAD

**Issue by fstirlitz** [stsp/dosemu2#184]
Running `make install` with `DESTDIR` set makes `$(DESTDIR)/usr/lib/dosemu/drive_z/dosemu` an absolute-path symlink to `$(DESTDIR)/usr/lib/dosemu/dosemu2-cmds-0.1/dosemu`. This is bad for packaging, which would assume all symbolic links are relative (or at least not point under the mock installation root).

**Comment by stsp** [comment]
Thanks, I've fixed 2 such instances now,
Let me know if there are more.
