### ISSUE TITLE
Micro Machines unplayable with current git

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#185]
There is a problem with the graphics in Micro Machines. The initial logo doesn't appear properly and after that the in-game graphics are not rendered. Both with KVM and emulated CPU.

a51e8edc34baa508c10e61fe2ea23b0628e33f8f is the first bad commit
commit a51e8edc34baa508c10e61fe2ea23b0628e33f8f
Author: Bart Oldeman <bartoldeman@users.sourceforge.net>
Date:   Mon May 16 13:24:23 2016 -0400

    KVM: alias_mapping() calls mmap_kvm(), mapping directly to source.
    
    This completely avoids double page protections and related races.

**Comment by bartoldeman** [comment]
ok, it seems this commit causes a few issues. I will be completely offline for the coming week (Mon-Fri) so feel free to revert this patch for now (and only this -- we can keep the other patch in the PR).

**Comment by stsp** [comment]
> so feel free to revert this patch for now (and only this -- we can keep the other patch in the PR).

OK, done.
However, I feel like I can revert the rest too, and add the
kvm_base instead. But I'll wait for your return.

**Comment by bartoldeman** [comment]
kvm_base won't fix it. The problem is the parallel update of the page tables that KVM doesn't see directly (because of the TLBs).

In the end the best solution is to use KVM's dirty page tracking (the KVM_GET_DIRTY_LOG ioctl). I'll get back on that later.

**Comment by stsp** [comment]
You mean the vgaemu thread updates again, not
propagating down to the guest? Hmm, in this case
I wonder if the previous "retry" solution isn't best -
at least it is most reliable and simple; and gives us
the EFAULT as soon as the guest TLB is out of sync.
So out of sudden, I wonder if we should just get back
to that hack.

**Comment by stsp** [comment]
By the way, I seem to have forgot the reason of
the previous change. It just briefly says
"This now fixes the race by mapping directly into non-aliased memory."
But what exactly was the fix?
It seems all this change does, is to bypass the
host side of the protection, similar to the unprotected
kvm_base or whatever. But how was it expected to fix
the race? If you fixed the race, then you don't even
_need_ to bypass the host protection - you will comply
to it. It is actually even probably _good_ to have the
host protection in the way: it will guard you against any
possible race (in a somewhat nasty ways like EFAULT,
but it will).
So, unless I am missing something obvious, the
logic behind this patch was inverted.

**Comment by stsp** [comment]
What is the state of this?
As I understand, we should still have some regressions
because the EFAULT work-around being currently removed.
But no one seems to complain.
Should I revert 10a7aa7d or everything is working fine?

**Comment by jschwartzenberg** [comment]
I indeed have the original issue again with Tristan Pinball because the workaround was removed. I assumed that Bart or you would get back to it, so I didn't report it myself again.

**Comment by stsp** [comment]
It would still better to always keep the tickets actual.
If you re-open or submit more tickets than needed, there
is no problem to close the unneeded ones. But when
nothing is opened, the problem will just be forgotten.

Bart, OK to revert?

**Comment by bartoldeman** [comment]
I have been experimenting with different strategies.

One drawback of the current approach is that we use different techniques for alias mapping than for page protection; alias mapping goes via dosemu but protection via guest page tables.

The most performant way would be to do everything via guest page tables -- trapping via the guest IDT gives all the info we need (error code, trapno etc). This works fine for VM86 and DPMI. It won't work for VCPI, or raw protected or real mode, but getting those into dosemu is a lot more work.

Doing everything via mmap/mprotect won't work -- the guest exits with EFAULT and we have no good way to determine error code and cr2 without disassembly.

The other alternative is to use KVM interfaces for everything, which is what QEMU does, in that case the guest does not even need to enable paging (if you can live with the fact that DPMI clients can then overwrite the guest monitor GDT, LDT and TSS), or one could use simple identity paging with ring-0 access-only to the guest monitor. The disadvantage is then still that if a page fault occurs it is seen as an MMIO exit by KVM, and the register state needs to be recovered using multiple ioctl syscalls, which is more expensive than trapping via guest IDT and HLT.

Reverting 10a7aa7 would be a short-term fix for sure. I assumed that was reverted already but I mixed it up with patch 9762f2d537b which should NOT be reverted (at least for now).

I will write more later today.

**Comment by stsp** [comment]
> Reverting 10a7aa7 would be a short-term fix for sure.

OK, done.

> Doing everything via mmap/mprotect won't work -- the guest exits with EFAULT and we
> have no good way to determine error code and cr2 without disassembly.

You mean, only without a retry, for sure?

**Comment by bolle732** [comment]
Thank you for reverting. I've been staying on 9762f2d537ba16d5bb56eb79c1fe68d938e80c4b due to performance reason. Now, PC/GEOS is running again nicely on head.

**Comment by stsp** [comment]
> Thank you for reverting. I've been staying on 9762f2d due to performance reason.

Feel free to re-open all bugs next time.
When people are silent, I am not aware about the severity.

> The other alternative is to use KVM interfaces for everything, which is what QEMU does,
> in that case the guest does not even need to enable paging

This resembles to me the first vm86 attempts, where it
happened that KVM API is simply insufficient to emulate
the v86 accurately.
So what is the problem with the mixed approach, when
the guest page tables are used for faults, but host page
tables are used for aliases and for guarding against TLB
races? You called it a "drawback", but what is the reason?

**Comment by bolle732** [comment]
> Feel free to re-open all bugs next time.
> When people are silent, I am not aware about the severity.

I don't like to hurt the good devs too much ;-)

**Comment by stsp** [comment]
> races? You called it a "drawback", but what is the reason?

I mean, surely retrying on EFAULT is not the
cleanest way, but if it is just a kernel bug or a
missing API (like missing guest TLB flush call),
then why to care? I think if we had the call to
flush guests tlb, then the current implementation
will be exactly the right one, and the retry thing
can then be removed without any further work.
