### ISSUE TITLE
ERROR: SMALLOC: Out Of Memory on alloc

### ISSUE THREAD

**Issue by ccarcel** [stsp/dosemu2#186]
Release pre5:

boot.log attached.

**Comment by andrewbird** [comment]
Hi, did you forget to attach the boot.log?

**Comment by ccarcel** [comment]
it says it supports zip but will not upload, please rename back to zip


![boot](https://cloud.githubusercontent.com/assets/6603424/15776880/0a085eb4-2983-11e6-8d58-bce35707d119.png)

**Comment by andrewbird** [comment]
Mmm, github serves it with mime-type set to image, so it's not easy to view from the browser. Shame github doesn't support .txt.gz.

~~~
DOSEMU-2.0pre4 is coming up on Linux version 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64
~~~

The log indicates it's an old git checkout, and not pre5 like you suggested. Also have you some context for the failure; what DOS version, what program were you running?

**Comment by stsp** [comment]
If this is -pre4, then this bug is already fixed. #143

**Comment by ccarcel** [comment]
I will manual delete and re-install to check pre4 and pre 5 issue. using ms dos 6.22. I have to remove pre 4 before installing pre 5. i did noice it said this on loading.
