### ISSUE TITLE
ERROR: Unable to initialize video subsystem

### ISSUE THREAD

**Issue by ccarcel** [stsp/dosemu2#187]
dosemu -t

text mode does not load in pre5
*****************************************
[root@localhost mnt]# dosemu -t
ERROR: Unable to initialize video subsystem
*****************************************
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing built-in global.conf file.
CONF: config variable version_3_style_used unset
CONF: config variable version_3_style_used set
CONF: opened include file /etc/dosemu/dosemu.conf
CONF: closed include file /etc/dosemu/dosemu.conf
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Disabling use of pentium timer
CONF: dosbanner on
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: CPU VM set to -1
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x5000)
CONF: DPMI base addr = 0xffffffff
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout keyb-user
device: /dev/fd0 type 2 h: 0  s: 0   t: 0 floppy A:
CONF: fastfloppy = 1
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P cups-pdf  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
device: /etc/dosemu/drives/c type 4 h: -1  s: -1   t: -1 drive C:
CONF: cdrom MSCD0001 on /dev/cdrom
CONF: config variable c_system unset
Linux kernel 3.10.0; CPU speed is 2266747000 Hz
CPU-EMU speed is 2267 MHz
work around FreeDOS UMB bug
CONF: running exclusively as ROOT: uid=0 (cached 0) gid=0 (cached 0)
DBG_FD already set
DOSEMU-2.0pre4 is coming up on Linux version 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64
Compiled with GCC version 4.8.5 -m64
CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -fno-stack-protector -fplan9-extensions -Wno-maybe-uninitialized -O2
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 48Kb at 0xF4000 for 'r' (Dosemu reserved area)
KVM: error opening /dev/kvm: No such file or directory
KVM not available: No such file or directory
using CPU emulation for vm86()
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0217
initial segment bases: fs: 0x7fcd24f36740  gs: (nil)
ERROR: Unable to initialize video subsystem
leavedos(video_init:250|32) called - shutting down
CONF: reserving 64Kb at 0xB0000 for 'v' (Video memory)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
SERIAL $Id$
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
CONF: reserving 64Kb at 0xA0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 128Kb at 0xC0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
Leaving DOS before booting
leavedos(main:359|0) called - shutting down
DPMI: mem init, mpool is 23031808 bytes at 0x40fee000
TIME: using 9154 usec for updating ALRM timer
leavedos(main:390|99) called - shutting down
======================= ENTER CPU-EMU ===============

leavedos thread started
leavedos thread ended
coopthreads stopped
======================= LEAVE CPU-EMU ===============

**Comment by stsp** [comment]
This is -pre4, and supposedly no plugins were able to load.

**Comment by ccarcel** [comment]
it is the pre 5 I installed, what plugins do I need for text mode please. I have to uninstall pre 4 to let me install pre 5
