### ISSUE TITLE
Compilation error in vgaemu

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#189]
Hey,

when compiling after default-configure on Ubuntu x64 3.19 make fails with

```
...
gin_translate_charsets.a -Wl,--no-whole-archive -lpthread -ldl -lm -lrt 
lib/libbase_dev_vga.a(vgaemu.o): In Funktion `vga_emu_fault':
vgaemu.c:(.text+0x1d65): Nicht definierter Verweis auf `static_assert'
vgaemu.c:(.text+0x1d85): Nicht definierter Verweis auf `static_assert'
vgaemu.c:(.text+0x1f5d): Nicht definierter Verweis auf `static_assert'
vgaemu.c:(.text+0x1f75): Nicht definierter Verweis auf `static_assert'
lib/libbase_async.a(int.o): In Funktion `ret_from_int':
int.c:(.text+0x91): Nicht definierter Verweis auf `static_assert'
lib/libbase_async.a(int.o):int.c:(.text+0x14c): Weitere nicht definierte Verweise auf `static_assert' folgen
collect2: error: ld returned 1 exit status
make[2]: *** [../2.0-pre5/bin/dosemu.bin] Fehler 1
make[2]: Verzeichnis »/home/pa/dosemu/src« wird verlassen
make[1]: *** [dosemu] Fehler 2
make[1]: Verzeichnis »/home/pa/dosemu/src« wird verlassen
make: *** [default] Fehler 2
```

One may translate the error to "Undefined reference to `static_assert'"

**Comment by stsp** [comment]
Could you please add:
`#include <assert.h>`
into cpu.h file and see if that helps?

**Comment by haenschen** [comment]
I added it below
`#include "bios.h"`

but it did not help, same error

**Comment by stsp** [comment]
Could you try replacing the occurrences of static_assert
with
_Static_assert
in cpu.h and memory.h? There are just a couple of them.

**Comment by haenschen** [comment]
Yes, that worked out!

**Comment by stsp** [comment]
What is your gcc and glibc version?

**Comment by haenschen** [comment]
```
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

pa@PA:~/dosemu$ ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.9) 2.19

```

**Comment by stsp** [comment]
Could you please in configure.ac line 103 add
-std=gnu11
to the list of options? Then you need to run
autoconf
then ./default-configure and make.

**Comment by haenschen** [comment]
Do I need to remove the manual changes to cpu.h and memory.h first?

**Comment by stsp** [comment]
Yes, all manual changes can be discarded by:
git reset --h

**Comment by haenschen** [comment]
That works too

**Comment by stsp** [comment]
It seems dosemu2 uses frighteningly many
language extensions these days.

**Comment by haenschen** [comment]
thanks for your help!
