### ISSUE TITLE
INT33 mouse support for higher resolutions (800x600, 1024x768) in Windows 3.x (possibly other applications as well)

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#193]
Currently it's not possible to use an INT33 mouse driver (in Windows 3.x) with higher resolutions. It basically only works correctly for 640x480.

Note: Higher resolutions in Windows 3.x are supported through the SVGA or Trident drivers.

**Comment by stsp** [comment]
"fixed" in mouse_fix branch for mouse_grab mode
only for now. This is just a testing branch, which you
cen test. :) I'll try to work on it as time permits.

**Comment by stsp** [comment]
Should now be fixed also for non-grab mode.

Hmm, looks like we already have 3 those "fix" branches...

**Comment by jschwartzenberg** [comment]
With the mouse_fixes branch, it works well (with autodetection) at 800x600 and 1024x768!! Here's my drive_c again: https://yadi.sk/d/hfN993ZFsMoN3

**Comment by stsp** [comment]
I started to write the mouse driver with hiew.exe.
It doesn't work well yes, just a demo. As you can see,
it can already do something. :)

[stspmous.drv.zip](https://github.com/stsp/dosemu2/files/335531/stspmous.drv.zip)
