### ISSUE TITLE
System Beeps should use sound stack

### ISSUE THREAD

**Issue by kalpha2** [stsp/dosemu2#195]
If dosemu(1or2) is installed on a unit without an internal speaker but has external speakers, should the FreeDOS cmd Beep still emit a sound?
The FreeDOS cmd Beep works on units I have with internal speaker/buzzer but not on those without.
from a terminal I tried  echo -e "\007"
this does nothing, but as per a google suggestion if you do (and if you have permission)
echo -e "\007" > /dev/tty5
does beep ... not sure why ... and apparently it does rely on knowing a tty is available and unused?
Is it possible to do via a config setting change to allow the above or redirect to the external speakers somehow... maybe making use of the (debian) beep package?

as a test I tried the following (on a unit with the debian package "beep" installed)
 = = = = =  
--- speaker_orig.c  2016-06-07 20:52:28.000000000 +0100
+++ speaker.c   2016-06-10 13:56:41.924515798 +0100
@@ -93,7 +93,8 @@

 static void dumb_speaker_on(void \* gp, unsigned ms, unsigned short period)
 {
-   putchar('\007');
-   //putchar('\007');
-   system("beep ");
  }
  static void dumb_speaker_off(void *gp)
  {
  = = = = =  
  few things of note ... 
- This worked .... but get a variable number of beeps (usually about 3). 
   From console "beep" issues a single beep, but from FreeDos/Dosemu2-pre5 I get variable 
    number of beeps.
   I also substituted the "beep " with an "aplay /usr/share/sounds/sound.wav " this also worked 
    but again the wav file gets played multiple times.
   Is this because it is linked in with timer somehow, and the putchar('\007') normally executes so
    quickly it will do it the once, but instantiating beep or aplay causes the multiple?
   When called from within a DOS program, it is noticeable that the DOS program is "paused" while
    these multiple beeps (or wavs) are played before it will continue.
- Is "system" a bad idea (for more than one reason)?
   There seems to be some suggestions that it is bad, and a spawned pid should be created.
   The code (and dependencies) seemed far more involved for that, hence my quick test was
   with only using system.

**Comment by stsp** [comment]
> played multiple times. Is this because it is linked in with timer somehow, and the putchar('\007') 
> normally executes so quickly it will do it the once, but instantiating beep or aplay causes the multiple?

Exactly.
The proper speaker support is when the speaker
emulation talks to the audio stack, not to linux terminal.
Unfortunately, this is not implemented, and the pre-requisite
seems to be the proper PIT code. When we have the proper
PIT code, I'll add the speaker support to the todo list.

The system() is of course bad. See the usage of popen2()
in dosemu as an example: this does not pause the calling
process.

**Comment by stsp** [comment]
Next time I'll look into stealing the PIT code from
reactos's ntvdm (and I wish them to steal our SB emulator).
Someone else interested may take a look on their PIT code too.

**Comment by stsp** [comment]
dosbox, as an example, has the speaker emulation that
talks to the audio stack. You can test it to see what we
should achieve ideally.

**Comment by kalpha2** [comment]
yes dosbox appears to emit system beeps (on units without internal speakers) via external speakers (though I had to run a DOS exe to confirm this, as it doesn't have a builtin beep cmd, like FreeDos on dosemu). For the units I want to have beeps emit from, dosbox is a not appropriate.
I found popen2 referenced in lpt and utilities, but haven't looked at how used yet.

**Comment by andrewbird** [comment]
@kalpha2 are you running dosemu2 on the linux vt console or in X/SDL window?

**Comment by kalpha2** [comment]
the units I want system beeps on are just console, there is no X running.
But I have been testing on other units some with X

**Comment by stsp** [comment]
> I found popen2 referenced in lpt and utilities, but haven't looked at how used yet.

You can use fork/exec too, or even popen().
But the care should be taken to shut down signals
before doing exec(), and this is what popen2() does
for you.
I think if you only want to get the freedos beep to work,
then some simple change is possible to get just one
beep instead of many.
Another alternative is to use $_speaker="native" and
dosemu -s

**Comment by kalpha2** [comment]
I think freedos beep and $_speaker="native" are only going to work IF there is an internal (system) speaker? I need something to intercept the system bell call and emit a sound through external speakers (which my initial hack attempts were with the (debian "beep" package or "aplay ... "

**Comment by stsp** [comment]
> I think freedos beep and $_speaker="native" are only going to work IF there is an internal (system)
> speaker?

Yes.

> I need something to intercept the system bell call and emit a sound through external speakers

For freedos beep or something more complex?
I suspect that the simple case can be solved if the
only problem is multiple beeps.

**Comment by kalpha2** [comment]
the actual beeps needing to be heard are generated from a dos exe, and probably doing same as what freedos beep does. Actually the multiple beeps could be acceptable, it was more the delay / pause to the program until the beeps had finished that would be annoying an issue.

**Comment by kalpha2** [comment]
I added a call using popen2 and then pclose2 (in place of the system call)
I couldn't quite follow the parameter structure in lpt.c but followed the style in vde.c and got it to compile and run.
I tried setting the cmd to either the debian beep or to aplay.
under freedos they do as expected.
If I compile a powerbasic exe with one line that calls it's beep function.
That exe sounds two beeps or if I do aplay front_center.wav you hear ...
Front..Front....Center..Center
On the plus side, yes control seems to return after the start of the noise, so it will probably do what I want ... I just need to test with the real setup.

**Comment by stsp** [comment]
You can create a shell wrapper script that
will create a semaphore file before invoking the
player.
http://unix.stackexchange.com/questions/70/what-unix-commands-can-be-used-as-a-semaphore-lock

**Comment by kalpha2** [comment]
I tried changing the popen2 to call a script like below
 - - - - - - - 
#!/bin/bash
# Makes sure we exit if flock fails.
set -e
(
  # Wait for lock on /var/lock/.myscript.exclusivelock (fd 200) for 10 seconds
  flock -x -w 10 200
  aplay /usr/share/sounds/alsa/Front_Center.wav 
) 200>/var/lock/.myscript.exclusivelock
 - - - - - - - 
But that actually generated 3 non overlapping occurrences of the wav file being played.
I also tried incorporating the beep code into speaker.c but got error trying to access /dev/tty0 
I'm going to close the issue as the first attempt at popen2 will be usable.
As a Wishlist item, it would be nice to have a dosemu.conf option to set where system bell/beeps should be directed, i.e. to cover the instance where no internal speaker exists.

**Comment by andrewbird** [comment]
So just to be clear, one console beep in DOS generated three calls of your script, which because of your locking working correctly made them emerge sequentially? As a test I just backgrounded 5 copies of the script in my shell and they came sequentially, so the script looks good. The question I have is why the DOS beep gets multiplied? Or, perhaps there really are 3 DOS beeps, and on real hardware they come out simultaneously.

**Comment by stsp** [comment]
Looking at the code, the bug seems to be that
do_sound() only checks the new value of port61,
and, if it is, say, 3 - calls speaker_on().
It should also check the previous value of 0x61,
and call speaker_on() only if it wasn't 3.
Feel free to fix this. :)

**Comment by stsp** [comment]
Should now be fixed.

**Comment by kalpha2** [comment]
just tried your patch .... it works for the freedos "beep" cmd. 
But the powerbasic exe still emitted three times.
Can I debug / trace this somehow to see where / why it calls, or what the port 61 value is?
Where did you get the & 3 from ?

**Comment by stsp** [comment]
You can debug with gdb, or just add
error("value=%x old=%x\n", value, port61);

3 is because the speaker is controlled only by 2 bits.
See the picture here:
https://courses.engr.illinois.edu/ece390/books/labmanual/io-devices-speaker.html
Unfortunately, this picture gets the bits in a wrong order.
GATE2 is bit0, and "SPEAKER DATA" is bit1.
Other than that, the picture is correct.

**Comment by kalpha2** [comment]
sorry not skilled with gdb ... yet.
So I just added some printf to the timer.c in the   do_sound  and  spkr_io_write functions
[timer_c.txt](https://github.com/stsp/dosemu2/files/319193/timer_c.txt)
![powerbasicbeep](https://cloud.githubusercontent.com/assets/12398407/16130820/c36ae9e2-3402-11e6-9a76-b8ad00a908e4.png)
![freedosbeep](https://cloud.githubusercontent.com/assets/12398407/16130821/c36fe1d6-3402-11e6-824a-a47620cc00d3.png)

**Comment by stsp** [comment]
I dont see the values written to port.

**Comment by kalpha2** [comment]
if I add printf to the spkr_io_write as below
 - - - -
void spkr_io_write(ioport_t port, Bit8u value) {
   if (port==0x61) {
printf ("Z port61 value = %x old = %x\n", value, port61);
 - - - - 
then for a freedos beep I get
Z port61 value = bf old = f
Z port61 value = 3f old = f
B spkr_io_write
A speaker_on(sound_duration = 7530, period = 52d)
Z port61 value = f old = f
Z port61 value = c old = f
 - - - - - - 
and for a powerbasic beep I get 
Z port61 value = 3f old = c
B spkr_io_write
C spkr_io_write
A speaker_on(sound_duration = 7530, period = 24)
A speaker_on(sound_duration = 7530, period = 5d4)
A speaker_on(sound_duration = 7530, period = 24)
Z port61 value = 2c old = f

**Comment by stsp** [comment]
Should now be fixed.

**Comment by kalpha2** [comment]
thankyou ... yes single beep (or wav) from the powerbasic exe or from freedos beep.
is there any merit in using the popen2 (as I have) and creating any optional dosemu.conf setting to hold what should be invoked if wanting system bell to invoke external script/program?
Obviously default to existing internal speaker action unless overridden?

**Comment by stsp** [comment]
I don't think so.
There is already a pulseaudio solution for this:
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#index30h3
module-x11-bell
Intercepts X11 bell events and plays a sample from the sample cache on each occurence.

There are also other (seemingly outdated) solutions:
https://gitlab.com/gi1242/xbelld
http://beep-module.sourceforge.net/

Alternatively, if your powerbasic program needs
to play a sample, it could use unix.com for this.
If you can't modify your program but it uses the
"bell char" (as it really should), then nansi.sys would
need a simple addition to execute the user-specified
command on bell. dosemu could have some option
for handling a "bell char", but it may be simpler and
cleaner to solve in nansi.sys. But if your program
uses port writes instead of the "bell char", then I don't
think dosemu or nansi or whoever should mess with
this - the program should be fixed.

**Comment by kalpha2** [comment]
I need a non X solution ... 
a Shell to UNIX statement crashes dosemu ... seemingly on large programs

**Comment by stsp** [comment]
http://beep-module.sourceforge.net/ is non-X solution.
Bell char is non-X solution.
Crash may probably be fixed, etc.

**Comment by kalpha2** [comment]
personally I like the solution we came to with dosemu2 and just thought making it a configurable override would be a nice finalisation.
I certainly prefer it over patching a kernel with "http://beep-module.sourceforge.net/"
Being able to play a sample was just something I liked idea of  ... and I think it helped identify/clarify some of the issues.
But the bottom line is wanting any system running dosemu with no internal speaker, to allow a standard(?) call to system bell (from bespoke or closed source DOS pgms) to still be audible.

**Comment by stsp** [comment]
The only "standard" call is a "bell char".
And nansi.sys already has a few options of
dealing with it. You just need to add another
one, which is the user-specified cmd.

**Comment by kalpha2** [comment]
I only see the nansi /B parameter ?
I don't understand what it means by redirect to BIOS 
using /B didn't seem to make any difference for me.

**Comment by stsp** [comment]
Unfortunately there is currently no option to
execute the cmd on beep, but it might be easy
to add one. Or maybe no new options are needed
at all: instead nansi.sys could just check some
env var, and if it is set - execute the command
from that env var.

**Comment by stsp** [comment]
Hmm. I have recalled something.
There was already such a task in a previous life.
And my solution to it was to implement
bell_cmd in "screen" package.
So you need to run dosemu under screen
session and screen will intercept the bell
char and execute the cmd.
I still have the modified screen sources here,
so let me know if you need that.

**Comment by stsp** [comment]
Of course it looks cleaner to have that in nansi.sys,
but the screen-based solution already works, while
nansi would need a small bit of work.

**Comment by kalpha2** [comment]
if you want to put the modified screen sources somewhere I can take a look, though time is bit tight at moment. As I said I'm actually (very) happy with the solution we already came to with patching the port values and me using popen2 .... Making it configurable as to what cmd/script the popen2 should call would be a nice touch.... this would all obviously be optional for those who want or have need.

**Comment by stsp** [comment]
OK, in this case I would just suggest you
to use the environment var for what cmd
you want to execute. That would be easiest
to implement for you (1-2 minutes of work)
and gives you all the configurability you need.

**Comment by stsp** [comment]
I asked the nansi.sys maintainer and he
thinks this would be too difficult to impossible
on a nansi.sys side.
So indeed perhaps the only reliable solution
we can have, is to off-load this to things like
screen...
