### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [stsp/dosemu2#20]
*** No rule to make target 'config.status', needed by 'default'.  Stop.

(Debian Linux)

**Comment by stsp** [comment]
Could you please show the full output?
The sequence is this:

./autogen.sh
./default-configure -d
make -j 4

**Comment by ThebestwaytodesignJoinGitHub** [comment]
./autogen.sh ... right.
Sorry.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I have a new make error:
make[2]: *** No rule to make target '../../../src/include/pcl.h', needed by 'coopth.o'.  Stop.
make[2]: Leaving directory '/usr/src/dosemu2/src/base/misc'
../src/arch/linux/Makefile.main:111: recipe for target 'base/misc' failed
make[1]: *** [base/misc] Error 2

**Comment by stsp** [comment]
make distclean

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Doesn't change anything.
Btw I got this error on 2 different debian computers.

**Comment by stsp** [comment]
Fixed.
