### ISSUE TITLE
Regression: booting from hdimage file fails

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#203]
Whilst hoping to continue the efforts in fixing #49, I tried to boot from an hdimage file, but I find it's broken in current git. After bisecting it seems that commit a7c44e302576cff0c8585310bbd3032f4fb3cd3c is the cultprit, however during the bisect the errors shown were changing, so it's possible that there is more than one commit that contribute to the regression.

With a minimal conf file referencing an valid OS hdimage
~~~
cat test-imagedir/dosemu.conf 
$_lpt1 = ""
$_hdimage = "fat12-10mb.img.pc-dos33"
~~~

git checkout a7c44e302576cff0c8585310bbd3032f4fb3cd3c~1
~~~
make distclean;./default-configure -d;make
bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir/
# boots just fine
~~~

a7c44e302576cff0c8585310bbd3032f4fb3cd3c is the first bad commit
commit a7c44e302576cff0c8585310bbd3032f4fb3cd3c
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sun May 15 23:09:03 2016 +0300

    support link drives
    
    This is where you create a <drive>.lnk file in a hdimage dir,
    for example e.lnk.
    The content of the file is the path to drive directory.
    The difference with real symlinks is the possibility to specify
    the env variables inside the name.

git checkout a7c44e302576cff0c8585310bbd3032f4fb3cd3c
~~~
make distclean;./default-configure -d;make
bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir/
sh: 1: eval: Syntax error: "|" unexpected
ERROR: Sector not found in read_sector, error = Illegal seek!
ERROR: can't boot from (null), using harddisk
ERROR: Sector not found in read_sector, error = Illegal seek!
ERROR: can't boot from hard disk
~~~

Note: since the commit above seems to care about the directory contents, here is the listing:
~~~
$ ls -l test-imagedir/
total 124
-rw-r--r-- 1 ajb sphere       50 Jul  7 11:00 dosemu.conf
-rw-r--r-- 1 ajb sphere 10653696 Jul  7 11:00 fat12-10mb.img.pc-dos33
~~~

Note: reverting a7c44e302576cff0c8585310bbd3032f4fb3cd3c allows current HEAD to boot again from an hdimage file

**Comment by stsp** [comment]
> bisect the errors shown were changing, so it's possible that there is more than one commit that 
> contribute to the regression.

You can revert that commit instead of resetting before it,
and see what happens then.

Basically it seems it finds the .lnk file where it doesn't
exist, or maybe it looks elsewhere. Could you please
use the "warn" directive in global.conf to pring the $yyy
and $lnk variables?

Also "ERROR: can't boot from (null)" indicates an error
somewhere, likely in stop_disk() in parser.y.in.

**Comment by andrewbird** [comment]
Yes, I edited the report to show that reverting the commit allowed the boot to succeed. I'll revert the revert and try printing the vars :-)

**Comment by stsp** [comment]
Revert the revert is:
git reset --h origin/devel

**Comment by stsp** [comment]
"warn" prints to boot.log

**Comment by andrewbird** [comment]
Building now. Incidentally the "ERROR: can't boot from (null)" weren't always present during the bad bisect runs, so maybe they have already been fixed.

**Comment by stsp** [comment]
Ahh, makes sense.
Yes, they were indeed hopefully fixed.
I missed the fact that you got them on older build.

**Comment by stsp** [comment]
ac565d81b

**Comment by andrewbird** [comment]
CONF: **** Warning: lnk is -1                                                   
CONF: **** Warning: yyy is /clients/common/dosemu2.git/test-imagedir/fat12-10mb.img.pc-dos33

**Comment by andrewbird** [comment]
-1 seems like an odd return value for strstr.

parser.y.in has this definition
~~~
                | STRSTR '(' string_expr ',' string_expr ')' {                  
                        char *s = strstr($3,$5);                                
                        if (s) $$ = s - $3;                                     
                        else $$ = -1;                                           
                        free($3); free($5);                                     
                }                                                               
  ~~~

**Comment by stsp** [comment]
Yes, yes, I am preparing the fix already, thanks!
The problem is also in an installer, I am glad I haven't
tagged the -pre with the stuff like this.

**Comment by andrewbird** [comment]
Thanks, works for me!

**Comment by stsp** [comment]
Yes, except that it requires re-installing ~/.dosemu again.
I guess people got already tired from continuous re-installing. :(
But luckily this didn't yet slipped into master, thanks for spotting!
