### ISSUE TITLE
My sound is working only with -s switch

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [stsp/dosemu2#21]
, saying "Running privileged (via sudo) in full feature mode".
How to enable it for normal user?
I've already studied the docs and searched the internet.

**Comment by stsp** [comment]
Docs are irrelevant, sorry about that. Don't read them.
I am really unsure why you have sound only with -s.
Have you tried -S (capital S instead of lowercase s)?
Then it would be more plausible because -S enables
SDL.

What version you are using? Try

git checkout devel
git pull

that will give you all the latest.
Then in dosemu.conf set
$_sound = (2)
(dont forget to remove leading # )

**Comment by ThebestwaytodesignJoinGitHub** [comment]
>Already on 'devel'. Your branch is up-to-date with 'origin/devel'. git pull. Already up-to-date.<
Actually it's not correct that it works only with the -s swith, it works with pkexec and gksu too (what gives it root rights), but I think it's the same in the end.
-S alone doesn't help, no sound and music at all.
$_sound = (2) alone doesn't help, no sound and music at all.

But both $_sound = (2) and -S together and sound and music are playing!
Thank you for your help! Now I can finally play settlers2 without stuttering (dosbox is stuttering extremely with settlers2)

**Comment by stsp** [comment]
OK, I think we have 2 problems here.

1. You already had uncommented $_sound=(on) in your
config before reporting this. Unfortunately $_sound=(on)
currently mean "use sound code of dosemu-1", while
$_sound=(2) means "use sound code of dosemu-2".
Eventually I'll fix that up so that there is no more
"dosemu-1 sound code" on earth. dosemu-1 sound code
uses OSS. Perhaps you have to add yourself to the
group "audio" to be able to use it without -s switch.
Please check the permissions on /dev/dsp and /dev/mixer.

2. $_sound = (2) alone doesn't help, no sound and music at all.
I don't have an immediate guess to this, and this may actually
be a bug somewhere. It may seem as if libao doesn't work
for you. In compiletime-settings.devel you can set "libao off"
then do
./default-configure -d
and recompile - without libao support. Then hopefully
$_sound=(2) alone will be enough, as well as just commenting
out $_sound.
Do you have pulseaudio installed?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I removed libao before posting the issue because without it at least midi was working...
(I will check your other suggestions next week when I have access to my computer.)

**Comment by stsp** [comment]
> I removed libao before posting the issue because without it at least midi was working...

This I absolutely don't understand.
If you have pulseaudio installed, please open pavucontrol
and see what client is playing midi... If you removed libao
then it should be SDL, but then I don't understand why you
would still need -S. Or it could be alsa midi, but that one is
independent from libao, so I am confused.

**Comment by stsp** [comment]
I think I've got that fixed.
Please re-open if not.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Installed libao-dev again, feels better when compiling with satisfyed dependencies.
Sound working with -S (big S).
Sound not working without  -S (big S).
Pavucontrol shows SDL is playing midi and sound.

**Comment by stsp** [comment]
So, it doesn't matter whether or not libao is
compiled in, but you still get sound only with -S?
I guess pavucontrol in that case also show nothing?
Are there any errors in terminal, like this?
ERROR: libao support not compiled in or not found

**Comment by stsp** [comment]
Another interesting check.
In snd_o_ao_file.c please find
#define ENABLED 0
and change it to 1, then recompile.
It will then create the file /tmp/ao.wav and dump
all the played sound there. Could you check if
that works?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
"but you still get sound only with -S?"
And I can get it with -s.

**Comment by stsp** [comment]
Wow! Both with $_sound=(2)?
Absolutely unexpected.
What would pavucontrol show in case of -s?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Both $_sound=(2).
Now I don't undestand what you mean.

**Comment by stsp** [comment]
I mean please run "dosemu -s" and when sound plays,
please see pavucontrol. Last time you tried with -S, it was
"Pavucontrol shows SDL is playing midi and sound"
which is correct.
I wonder what it shows with -s instead.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Under Output devices tab. Built-in analog stereo. Line out (plugged in). Show All output devices.
It does not display any level meter.

**Comment by stsp** [comment]
So you mean you hear the sound but in pavucontrol
you don't see anything? Very strange.
Could you please do the following while the sound is playing with -s:

lsof | grep /dev | grep dosemu

and post the output here.

**Comment by stsp** [comment]
> Under Output devices tab.

No, under Playback tab please.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Under playback tab: Nothing but system sounds. ('All streams' selected.)

**Comment by stsp** [comment]
Could you please do the following while the sound is playing with -s:

lsof | grep /dev | grep dosemu

and post the output here.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
lsof | grep /dev | grep dosemu                                                                                                                                                 
dosemu.bi 2217            user  DEL       REG               0,17               15786 /dev/shm/dosemu_2217                                                                              
dosemu.bi 2217            user    0u      CHR              136,0      0t0          3 /dev/pts/0                                                                          
dosemu.bi 2217            user    1u      CHR              136,0      0t0          3 /dev/pts/0                                                                           
dosemu.bi 2217            user    2u      CHR              136,0      0t0          3 /dev/pts/0                                                                               
dosemu.bi 2217            user    5u      CHR             10,200      0t0       1802 /dev/net/tun
dosemu.bi 2217            user    8u      REG               0,17 17891328      15786 /dev/shm/dosemu_2217 (deleted)
dosemu.bi 2217            user    9u      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2217            user   10w      CHR               14,3      0t0       3293 /dev/dsp
dosemu.bi 2217            user   11u      CHR                5,2      0t0        285 /dev/ptmx
dosemu.bi 2217            user   19r      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2217 2249       user  DEL       REG               0,17               15786 /dev/shm/dosemu_2217
dosemu.bi 2217 2249       user    0u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2249       user    1u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2249       user    2u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2249       user    5u      CHR             10,200      0t0       1802 /dev/net/tun
dosemu.bi 2217 2249       user    8u      REG               0,17 17891328      15786 /dev/shm/dosemu_2217 (deleted)
dosemu.bi 2217 2249       user    9u      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2217 2249       user   10w      CHR               14,3      0t0       3293 /dev/dsp
dosemu.bi 2217 2249       user   11u      CHR                5,2      0t0        285 /dev/ptmx
dosemu.bi 2217 2249       user   19r      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2217 2259       user  DEL       REG               0,17               15786 /dev/shm/dosemu_2217
dosemu.bi 2217 2259       user    0u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2259       user    1u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2259       user    2u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2259       user    5u      CHR             10,200      0t0       1802 /dev/net/tun
dosemu.bi 2217 2259       user    8u      REG               0,17 17891328      15786 /dev/shm/dosemu_2217 (deleted)
dosemu.bi 2217 2259       user    9u      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2217 2259       user   10w      CHR               14,3      0t0       3293 /dev/dsp
dosemu.bi 2217 2259       user   11u      CHR                5,2      0t0        285 /dev/ptmx
dosemu.bi 2217 2259       user   19r      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2217 2260       user  DEL       REG               0,17               15786 /dev/shm/dosemu_2217
dosemu.bi 2217 2260       user    0u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2260       user    1u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2260       user    2u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2217 2260       user    5u      CHR             10,200      0t0       1802 /dev/net/tun
dosemu.bi 2217 2260       user    8u      REG               0,17 17891328      15786 /dev/shm/dosemu_2217 (deleted)
dosemu.bi 2217 2260       user    9u      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2217 2260       user   10w      CHR               14,3      0t0       3293 /dev/dsp
dosemu.bi 2217 2260       user   11u      CHR                5,2      0t0        285 /dev/ptmx
dosemu.bi 2217 2260       user   19r      CHR                1,3      0t0       1033 /dev/null
dosemu.bi 2234            user    0u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2234            user    1u      CHR              136,0      0t0          3 /dev/pts/0
dosemu.bi 2234            user    2u      CHR              136,0      0t0          3 /dev/pts/0

**Comment by stsp** [comment]
Wow, lots of /dev/dsp handles! Why??
Please do
ls -l /dev/dsp
I guess you don't have enough permissions, that's
why you need -s. You will probably need to add yourself
to group "audio" to fix this.

Another thing to try is to remove /usr/local/lib/dosemu/libplugin_libao.so
and try sound again.

**Comment by stsp** [comment]
Also please do
cat /etc/libao.conf
and post the results.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
cat /etc/libao.conf
default_driver=alsa
quiet                   
I am alredy in the audio group.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
After deleting /usr/local/lib/dosemu/libplugin_libao.so
dosemu
ERROR: libao support not compiled in or not found:
ERROR: /usr/local/lib/dosemu/libplugin_libao.so: cannot open shared object file: No such file or directory  
But: Sound and midi working...!

**Comment by stsp** [comment]
Please do

ls -l /dev/dsp
echo aaa > /dev/dsp

and post the results.

**Comment by stsp** [comment]
also

cat /proc/asound/cards
ls /dev/snd

**Comment by ThebestwaytodesignJoinGitHub** [comment]
cat /proc/asound/cards                                      
 0 [SB             ]: HDA-Intel - HDA ATI SB                                    
                      HDA ATI SB at 0xfe024000 irq 16                           
 1 [NVidia         ]: HDA-Intel - HDA NVidia                                    
                      HDA NVidia at 0xfcffc000 irq 18     

ls /dev/snd                                                 
by-path    hwC0D0  hwC1D2    pcmC0D0p  pcmC0D2c  pcmC1D8p  timer                
controlC0  hwC1D0  hwC1D3    pcmC0D1c  pcmC1D3p  pcmC1D9p                       
controlC1  hwC1D1  pcmC0D0c  pcmC0D1p  pcmC1D7p  seq      

echo aaa > /dev/dsp gives no output. But there is a short click from the speakers.

**Comment by stsp** [comment]
ls -l /dev/dsp ?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
ls -l /dev/dsp                                              
crw-rw----+ 1 root audio 14, 3 Mar 17 12:20 /dev/dsp

**Comment by stsp** [comment]
OK so you are in group audio and can easily write
to /dev/dsp, and yet you need -s... That besides the
fact that /dev/dsp should not be used at all!
I think your libao is somehow broken, and it is trying
to use OSS by mistake (ti should be using pulseaudio).

In any case, please do the following:
strace -f -o log1.txt dosemu.bin
and try to play sound.
Then became root with su, and do as root
strace -f -o log2.txt dosemu.bin
and try to play sound (I guess it should play now
because of root).
Then gzip these 2 logs and e-mail them to me.
github is so cool that there is no possibility to attach
files...

**Comment by ThebestwaytodesignJoinGitHub** [comment]
You remember I deleted /usr/local/lib/dosemu/libplugin_libao.so.
Shall I strace with it installed or without it?

**Comment by stsp** [comment]
Yeah, please re-install it before strace.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I call dosbox without any extra command after deleting (renaming) /usr/local/lib/dosemu/libplugin_libao.so.
This way I have all sound an midi, and when invoking emumouse x 8 y 8 I have a smooth mouse pointer too.
So everything is ready now for playing settlers2, thanks for your help!

**Comment by stsp** [comment]
Good that you made it working (you could
as well use -S), but I still wonder why libao
does not work for you.
So if you can provide an strace output or
ssh access for me, that would be good.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Now libao is working!
I use emumouse x 4 y 4 (not 8) after calling dosemu with -S switch.
This way mouse is nice and slow and all sound is working.

**Comment by stsp** [comment]
You confuse things.
With -S SDL is working.
Without -S - libao is working (but doesn't for you)

**Comment by ThebestwaytodesignJoinGitHub** [comment]
'Without -S - libao is working (but doesn't for you)'
Right. But when the plugin file is deleted sound works without -S too.

**Comment by stsp** [comment]
> But when the libao plugin file is deleted, sound works without -S too.

That's normal: it then still loads SDL as a fall-back
(only for audio, video is then still bypasses SDL).
You can see that in pavucontrol.
But it would be nice to get libao working too.

**Comment by stsp** [comment]
> cat /etc/libao.conf
> default_driver=alsa
> quiet

I think you are affected by this bug:
https://bugs.launchpad.net/ubuntu/+source/libao/+bug/1075479
Simply removing /etc/libao.conf might help.
Alternatively the following /etc/asound.conf might help:
$ cat /etc/asound.conf
#
# Place your global alsa-lib configuration here...
#
pcm.!default {
    type pulse
}
ctl.!default {
    type pulse
}
