### ISSUE TITLE
Weird interactions switching between fullscreen and windowed mode

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#213]
Hi,

on Ubuntu 16.04.1 x64 I experience weird interactions when switching from fullscreen to windowed mode and back, both in X and SDL. Sometimes the whole window takes the size of the former fullscreen, sometimes it doesn't work at all and sometimes the content of the window isn't resized (see attached picture).
Correct:
![correct](https://cloud.githubusercontent.com/assets/9266844/17083612/b46dd7f8-51a6-11e6-8679-0dc916611fcb.png)

Wrong:
![wrong](https://cloud.githubusercontent.com/assets/9266844/17083613/b4749020-51a6-11e6-9aee-19e1def6eac4.png)

Also wrong:
![wrong2](https://cloud.githubusercontent.com/assets/9266844/17083614/b47a51a4-51a6-11e6-8354-99985ea2ee3d.png)

I tried a former branch which I believe worked but it did not help so maybe it's a problem with the OS but I couldn't investigate further yet. Maybe you have an idea.
I will try the old OS soon and report here.

**Comment by stsp** [comment]
Not really.
Try playing with $_X_fixed_aspect and related settings.

**Comment by stsp** [comment]
In fact, yes, I can reproduce some weirdness
on ubuntu after a few switches.

**Comment by haenschen** [comment]
Indeed, thanks!
