### ISSUE TITLE
Mouse range restricted again (was #132)

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#214]
Tested on Ubuntu 16.04 32-bit and KVM running PC/GEOS @1024x768x64k. With the commit 4b3ee4c85247b955e5c301bda7fbb4e5ee64a21f, the mouse can't be moved over the whole window again. Its restricted to the upper left part, about 1/3rd of the top and 2/3rd of the left. Last commit 262c1ea123ab3197eb3db403284f73a3304d8f8f has the same problem.

Bisected to:
```
4b3ee4c85247b955e5c301bda7fbb4e5ee64a21f is the first bad commit
commit 4b3ee4c85247b955e5c301bda7fbb4e5ee64a21f
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Jul 23 19:44:01 2016 +0300

    mouse: use mode 6 when video mode is unknown

:040000 040000 900f961449d7a520394afee1624cb8e93bc7557e 23f9f32d5497d1ff1af053474442e028c1cd25d6 M	src
```

**Comment by stsp** [comment]
Please provide the -D+m log from working and
non-working version.
It seems your ssh password have changed.

**Comment by jschwartzenberg** [comment]
I'm also seeing some issues which seem new in Holiday Lemmings '94. The game does seem to use INT33 as it repositions the cursor when you enter the window from another edge.

More info about the game: http://www.abandonia.com/en/games/234/Holiday+Lemmings+Pack.html

**Comment by bolle732** [comment]
Hello Stas, could you please try the ssh access again ? It should still work with the password I've provided to you. If not, let me know privately.

**Comment by stsp** [comment]
But the bug is already fixed.

**Comment by stsp** [comment]
Yes, I am sorry, ssh still works.
I simply forgot the right login when trying. :)
