### ISSUE TITLE
wrong $_hdimage runs installer

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#215]
If $_hdimage is set incorrectly, dosemu runs
installer. It should instead err out. The only
condition for running the installer should be
the missing installation in ~/.dosemu/drives,
disregarding of what $_hdimage says.

**Comment by stsp** [comment]
@andrewbird would you like to take a look into
this as well? :)
I seem to have fallen into an infinite recursion of
rewriting the mouse driver, and it is unclear when
I reach the bottom of it.

**Comment by stsp** [comment]
It seems, with the commit 694a97db I removed
the hack that did exactly that. And there seem to
be no other way for dosemu to even see the config
values if global.conf doesn't present them. And if
one wants to solve that problem in global.conf, it is
unclear how to see if the value was uncommented
or not.
So what logic can we use here? Should the installer
respect $_hdimage and install there?
I think this should be solved in a following way: the
default value for $_hdimage should became "".
global.conf will expand that to DOSEMUHDIMAGE_DEFAULT"/drives/*"
and also pass a new parameter, like "install_path".
If the value of $_hdimage is not "", then the things
work as now, but, because the "install_path" is not
passed, the installer does not activate.
Yes, looks complicated, but the whole global.conf
stuff is a one big over-complication.

**Comment by bolle732** [comment]
I don't have a definitive preference. Personally, I didn't liked the installer invoked auto-magically. But I see its strengths, similar the usage of a skeleton for the home directory of a user.

For me to understand it better, I tried to write down the cases I see, which is more or less equal to what Stas already wrote:

1. '$_hdimage' is specified and boot files exists
-> Use them

2. '$_hdimage' is specified and NO boot files exists
-> Tell the user to run DOSEmu2 with the (hypothetical) install option. If no system wide (Free-)DOS exist, tell the user to install it (by package manager of distribution?)

3. NO '$_hdimage' is specified and boot files exists under '.dosemu'
-> Use them

4. NO '$_hdimage' is specified and NO boot files exists under '.dosemu'
-> Automatically install from system wide (Free-)DOS installation to '.dosemu' OR tell the user to run DOSEmu2 with the (hypothetical) install option. If no system wide (Free-)DOS exist, tell the user to install it (by package manager of distribution?)

So, as Stas wrote, an explicit option to kick off the installation for an "empty" '$_hdimage' path would be nice. I wouldn't call it 'install_path', only an simple switch like '--Finstall' or something like this. Maybe that could be extended to force the overwrite / replacing an existing installation.

Now, checked the MAN pages:
I never used the option '-i[bootdir]' , but this seems like that what is talked about.

**Comment by stsp** [comment]
I meant an option internal to global.conf, not
exported to the user. I wouldn't pollute the config
with things like this, and we already have it from
cmd line as you noted.

**Comment by stsp** [comment]
That were mainly a notes to myself and maybe
to @andrewbird if he is looking into a global.conf
clean-ups these days.

**Comment by andrewbird** [comment]
Hi,
I've injured my back and can't sit down for long periods of time at the moment, so it could be quite some time before I can return to the imagedir cleanups etc. If there's anything useful in my dirs-01 branch feel free to cherry-pick if it helps. Otherwise at some point, presumably after next pre, I'll start on a new branch and PR.

Thanks

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 27/07/2016  22:25  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Mention <mention@noreply.github.com> 
Subject Re: [stsp/dosemu2] wrong $_hdimage runs installer (#215) 
 
That were mainly a notes to myself and maybe
to @andrewbird if he is looking into a global.conf
clean-ups these days.

**Comment by stsp** [comment]
OK, please get well soon. :)
I also have some problems with back sometimes,
so I know this sucks.

**Comment by stsp** [comment]
This is now fixed, and here is an option to disable
the install completely. But it shouldn't be used that
way if you want to boot fdpp. I think all knobs are
now available to not disable install/fdpp and make
them completely "invisible" to the user.
