### ISSUE TITLE
SimCity mouse issue with title screen at 640x350x4

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#216]
SimCity has several options for its graphics mode. At 640x350x4, the title screen has an issue and the right part of the buttons cannot be clicked on. I think I remember the game limited mouse movement to within the button area on real hardware. In game the problems seem to disappear
At 320x240x8 the mouse always works correctly.

More info about the game: http://www.xtcabandonware.com/game/831/simcity

**Comment by stsp** [comment]
Is this a regression?

**Comment by jschwartzenberg** [comment]
Yes this is a regression, in 1.4 the mouse is perfect for this game.
My memory of limited movement on the title screen is incorrect, that's probably with another game.

**Comment by stsp** [comment]
Yes, this is reproducible.
However, I tested with the real mouse driver
(mouse.com) and indeed the horizontal speed
of the cursor is very slow, while the vertical
speed is normal.
This game slows the horizontal movement twice,
and dosemu2 now emulates the speed properly
instead of emulating the coordinates properly.
Obviously if you slow down the cursor speed, then
it will be out of sync with the real one. Note that
if the game uses the native cursor rather than
drawing its own, then the speed is ignored, and
the native speed is used. Unfortunately simcity
draws its own cursor.
So while this is a regression, I think this is an
unfixable one, at least in non-grab mode.

**Comment by stsp** [comment]
Or maybe the compatibility is more important
than new functionality, and I can add the
emumouse.com knob to enable the speed
handling, and ignore it by default as older
dosemus did.

**Comment by jschwartzenberg** [comment]
It's an interesting observation that the game slows down its horizontal movement exactly twice. The horizontal and vertical movements were likely intended to be the same. This means that the screen was likely intended to be stretched exactly twice and the slow down was introduced to compensate for the stretching. The speed would appear be the same in both directions then.

Having speed handling indeed does not seem useful when running in non-grab mode and is actually something that would seem better to avoid.

The ratio difference in horizontal and vertical speed however is probably an accurate indication of what the intended aspect ratio for the screen was. With fast SDL support for stretching in a specific direction, maybe there could be a feature to get this right by default for the cases where applications were meant to run with non-square pixels.

**Comment by stsp** [comment]
> horizontal and vertical movements were likely intended to be the same.

Not what I see with the native mouse driver (mouse.com)
under dosemu. Of course the same driver can give
completely different results on a bare metal, which will
mean we have more bugs - you can test that.

**Comment by jschwartzenberg** [comment]
But did you have the screen stretched when you tested that? If you stretch to be twice bigger, that would compensate for the slowness.

**Comment by stsp** [comment]
> But did you have the screen stretched when you tested that?

No because I have fixed_aspect enabled.
Yes if I disable that and stretch, then indeed with
the native mouse.com they are equal.
There is of course no possibility to keep it with the
native cursor even this way, because the native
cursor is faster horizontally because the resolution
is not square.

I'll try some compatibility hack.

**Comment by stsp** [comment]
Just to be sure: do we have more mouse
regressions, or this can be considered "good enough"
for the next pre release?

**Comment by stsp** [comment]
It turned out the 3-buttons mode was never enabled.
I have enabled it now.
Needs to be testerd for regressions again. :)

**Comment by jschwartzenberg** [comment]
SimCity is fixed at least. 3D Lemmings is still regressed (#220).
The middle button still doesn't seem to work for me in Wfw 3.11.

Why are speed ups good btw? I don't think they're bad, but having the cursor at the host speed, when the location is always in sync with the host mouse seems the best.

**Comment by stsp** [comment]
> Why are speed ups good btw?

Are allowed only when the native cursor is hidden.

**Comment by jschwartzenberg** [comment]
Sure, but still, having the program cursor follow the host one would seem much more natural. It'd be like any other VM then.

**Comment by stsp** [comment]
How do you suppose it to follow, if it
hides the host cursor, draws its own
and scales the coordinates at will?

**Comment by stsp** [comment]
The best we can do is to honor its settings
and hope that then it will match the host's
cursor. But this may not happen if it scales
wrongly.

**Comment by jschwartzenberg** [comment]
That last one "scales the coordinates at will" is the problem then yes. I guess that not having the speed-ups either would fix some applications to be very nice, but cause others to be very problematic and there's no way to detect what kind is running.

**Comment by stsp** [comment]
If you disallow the speed-ups then you:
1. break the program that scale well
2. allow unreachanble areas
Both is very bad things.
If you allow the speed-ups and the program
does the wrong thing, then you'll get out-of-sync
things yet no unreachable areas, which is still fine.

**Comment by stsp** [comment]
> The middle button still doesn't seem to work for me in Wfw 3.11.

Should now be fixed.
