### ISSUE TITLE
The Even More Incredible Machine demo crashes DOSEMU

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#219]
When I run The Even More Incredible Machine with either kvm or emulated $_cpu_emu, dosemu crashes with the following output:

```
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=000166d7 while in vm86 (DOS)
Program=do_vm86.c, Line=153
EIP: 0000:000000ce ESP: 5294:00005e18  VFLAGS(b): 00011 00110000 00000010
EAX: 00000208 EBX: 00000002 ECX: 00005602 EDX: 0000385a VFLAGS(h): 00033002
ESI: 00000000 EDI: 0000006a EBP: 00005259 DS: 5294 ES: 0005 FS: 0000 GS: 0000
FLAGS: IF RF VM  IOPL: 3
STACK: 00 00 00 00 00 00 00 00 00 00 -> 00 00 00 00 00 00 00 00 00 00 
OPS  : 01 00 00 00 da 10 5e 01 46 c0 -> ff ef da 10 5e 01 da 10 5e 01 
        ffef                0000:00ce jmp  far di
```

More info about the game: http://www.dosgamesarchive.com/download/the-even-more-incredible-machine/

**Comment by jschwartzenberg** [comment]
Not a regression, 1.4 crashes as well:
```
======================= ENTER CPU-EMU ===============

*       Fault out of DOSEMU code, cs:eip=33:44a400, cr2=7d8e, fault_cnt=1
*       Fault out of DOSEMU code, cs:eip=33:44a400, cr2=7d9e, fault_cnt=1
leavedos(Interp86|3056) called - shutting down
======================= LEAVE CPU-EMU ===============
```

**Comment by stsp** [comment]
All incredible machines should be re-tested
because of the SB bug (which didn't crash
for me but produced the sound sticks).

**Comment by stsp** [comment]
Also please see if the crash is related to
some mouse events.

**Comment by jschwartzenberg** [comment]
The crash is still there, but now it seems that I also get hangs.

It indeed does *NOT* happen when I switch to PC speaker and it runs fine then.
When I switch to Sound Blaster Pro for the music and no sound effects, the game hangs with a black screen.

The Adlib/Sound Blaster (non-Pro) setting allows the game to work with music.

This combined with the Sound Blaster for sound effects (instead of no sound effects) hangs the game again with a black screen.

Other than that, the mouse is pretty buggy in the game. Clicks do not always register and the cursor can't reach the whole screen area. The score counters at the bottom also do not display properly. Initially they were not visible at all. After a while the bottom half appeared.

**Comment by stsp** [comment]
OK, so this is a known problem with sound drivers:
https://sourceforge.net/p/dosbox/bugs/156/
http://www.sierrahelp.com/Utilities/SoundUtilities/GOSiERRA.html

**Comment by jschwartzenberg** [comment]
The game doesn't run with the patched sound driver either here. Maybe it's the IRQ stuff messing it up though. Did you get it to work?

**Comment by jschwartzenberg** [comment]
Note, that while it appears to hang, it does crash after a while with this in boot.log:
```
ERROR: fork failed, Hulpbron is tijdelijk onbeschikbaar
ERROR: Please install gdb!
Obtained 10 stack frames.
debug.c:95      print_trace()
signal.c:531    abort_signal()
??:0    __restore_rt()
raise.c:54      __GI_raise()
abort.c:91      __GI_abort()
assert.c:92     __assert_fail_base()
??:0    __assert_fail()
utilities.c:788 popen2()
lpt.c:167       pipe_printer_open()
lpt.c:189       printer_open()
Backtrace finished
```

The output is:
```
dosemu.bin: utilities.c:788: popen2: Controletest 'p >= 0' faalt.
```
So this shows that infamous forking/can't start gdb issue again.

**Comment by jschwartzenberg** [comment]
I tried to reproduce this on my other systems, but on one it just crashes and on another it hangs (with very high CPU usage). In each caes, the problems are solved by using PC speaker mode.

Maybe emulating a Pro Audio Spectrum 16 or another widely supported card would help supporting these games some day.

**Comment by stsp** [comment]
For what?
dosbox aims to support every broken game.
And it is very good on this, so why do we care?
The fact that dosbox does this so well, allows
us to concentrate on other games, like the ones
that require more speed etc.

**Comment by jschwartzenberg** [comment]
Yes, also the WIndows version can be played in dosemu, so there's no big need. I will send an EMUFAILURE PR.

**Comment by stsp** [comment]
Amazing to know windows version works
better than the DOS one!

**Comment by jschwartzenberg** [comment]
At least it should :) I'll test again soon ;)
