### ISSUE TITLE
Mouse too sensitive

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [stsp/dosemu2#22]
Playing settlers2  in a terminal window under Debian linux

**Comment by stsp** [comment]
Please be specific. You will probably not like
my answers also being 1 line without much sense.
There is emumouse.com to adjust sensitivity.
Also I don't understand how it is possible to
play settlers in text terminal window. If you run
"dosemu -t" for terminal mode, settlers won't run.
But if you use a separate dosemu window, then
you can try Ctrl-Alt-Home to grab mouse pointer,
or you can use Ctrl-Alt-f for full-screen.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I start it from a terminal window on desktop.
This opens a window.
I know I can grab mouse and keybord, and I know I can switch to fullscreen.
In both cases the mouse is much too sensitive.
Where can I find this emumouse.com?

**Comment by stsp** [comment]
OK, but if you don't do grab and full-screen, then
mouse in the game should match your Xorg mouse
pointer. Is this also too sensitive?

emumouse.com comes with dosemu and is usually
available on d:\dosemu. If not, you can symlink
/usr/local/share/dosemu/drive_z to ~/.dosemu/drives/d

**Comment by ThebestwaytodesignJoinGitHub** [comment]
"but if you don't do grab and full-screen"
Yes, it's too sensitive.

**Comment by stsp** [comment]
But it should match your native mouse pointer!
Or does it?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I have no ~/.dosemu/drives/ folder, is this a problem?

**Comment by stsp** [comment]
dosemu usually creates it on first startup.
Maybe you have some legacy location, like
/var/lib/dosemu
which you forgot to erase?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
No, no legacy folders.
Also I have no idea how to use emumouse.com

**Comment by stsp** [comment]
In emumouse you are interested in x and y parameters.
For example
emomouse x 8 y 8

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I'm a dummy, don't know what you mean, sorry.

**Comment by stsp** [comment]
In DOS you should type
emomouse x 8 y 8
if emumouse.com is available.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I copied emumouse.com and generic.com to my other DOS files.
Then, after starting DOS I entered 'emumouse x 8 y 8'.
Now the mouse sensivity is perfect, thank you!

**Comment by stsp** [comment]
Is it perfect only in grab/fullscreen mode, or in
an ungrabbed mode also?

**Comment by stsp** [comment]
How have you found this project?
I have never announced it.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
You're right, I only tested with ungrabbed in fullscreen mode.
Grabbed it is still too fast.
Ungrabbed and windowed is not really possible to play.

**Comment by stsp** [comment]
> You're right, I only tested with ungrabbed in fullscreen mode.

But in full-screen it is grabbed by default.
Please try without -S. You won't get sound, but
testing mouse is possible.

> Ungrabbed and windowed is not really possible to play.

Indeed, but the sensitivity is... ?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Indeed, starting dosemu without -S and calling 'emumouse x 8 y 8' lets the pointer work correct, also in a window.

**Comment by stsp** [comment]
I can't reproduce any sensitivity problems with
settlers2 and -S. What version of SDL2 package
do you have?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
"How have you found this project? I have never announced it."
I found you by searching for dosemu on github and then choosing the project with most recent activity.
And you SHOULD announce dosemu2! It works so much better than dosbox, at least with settlers2.

**Comment by stsp** [comment]
I find it very strange.
I've tested settlers2 last week and found it
working very bad: too laggy, heavy CPU load
etc. So, while I haven't found any problems
with mouse, I've done _a lot_ of work to make
settlers2 really playable.
So please update from git (branch devel) and
enjoy!

About mouse: maybe without "emumouse x 8 y 8"
it is a bit too sensitive vertically, but you really
should not compare it with dosbox. dosbox is
tuned for better user experience, while dosemu
is emulating closer to real machine. It would be
interesting to try settlers2 in real DOS without any
emulators and I suspect the horizontal sensitivity
will match the one of dosemu.

**Comment by stsp** [comment]
In fact I wonder what CPU you have there.
For me even the initial settlers2 menu screen
(static, without animation) was overloading entire
system, making all other processes unresponsive.
Now it takes only 60% of my CPU.
Anyway, what exactly was the problem with it on dosbox?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Playing it with cpu set to powersave on an old amd 2-core.
Using 'emumouse x 4 y 4' (not 8) makes the mouse move nice even with dosemu -S switch.
This way I do no longer have to delete or rename libao.so.
With dosBOX, when you are in a game with large map and many interrupted enemy paths (often the case in end-game state) settlers2 is stuttering, makes a pause for 2 seconds every 3 seconds or so.
Under dosemu it runs better and better.

**Comment by stsp** [comment]
I won't care what exactly values (4 or 8) you
prefer, but if they differ between normal and "-S"
invocation - then it is a bug. They should not
depend on -S. So if you see the difference in mouse
sensitivity with and without -S, please re-open the
ticket.
There is a setting that may influence the sensitivity -
$_X_fixed_aspect
Uncomment it and try setting to (off) - see if that gives
any difference.

> This way I do no longer have to delete or rename libao.so.

IIRC deleting libao.so was needed to run _without_
-S, and now you are talking about running _with_ -S.
So I think you have some erratic logic here.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
'So I think you have some erratic logic here.'
This is all really confusing me: huge S, small s, without s, libao, deleted libao, renamed libao, uncompiled libao, the different settings in config file and so on. I think I lost the thread.

**Comment by stsp** [comment]
Small s is a mistery.
The only way I can find out why its needed,
is by the strace log.

As for mouse, the most important thing is
to make it behave similar for -S and without -S.
If it differs - we have a bug.
