### ISSUE TITLE
In 3D Lemmings the mouse cursor always goes to the upper left corner when it enters the window

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#220]
Each time the mouse enters the window, the cursor is moved to the upper left corner. In 1.4 the cursor appears on the edge where the mouse entered the window. (Horizontally is not so accurate like Holiday Lemmings '94, but vertically is always correct.)

More info about the game: http://www.old-games.com/download/3491/3d-lemmings

**Comment by stsp** [comment]
Is this a regression?

**Comment by jschwartzenberg** [comment]
I'd say yes, the behavior in 1.4 seems more correct to me.

**Comment by stsp** [comment]
We don't seem to have any more mouse
regressions, do we?

**Comment by jschwartzenberg** [comment]
Finally got around to checking this again. It works really nicely with the latest GIT!!
