### ISSUE TITLE
windows-3.0 doesn't work

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#225]
Doesn't start.
I think this is a regression.
Some checking/bisecting is welcome. :)

**Comment by stsp** [comment]
Hmm.
It doesn't start if either himem.sys (from DOS)
or emm.sys (from dosemu) are loaded.
Very strange...

**Comment by stsp** [comment]
Something with mapping perhaps.
I am getting the parts of "lowmem" region
(not lowmem_base!) unmapped...
"lowmem" region should never be unmapped
or mprotected.

**Comment by stsp** [comment]
Works fine with
$_ems_conv_pages = (0)
but doesn't work if himem.sys is loaded without ems.sys.
Perhaps we have bugs in both int15 and emm...

**Comment by stsp** [comment]
This seems to have been fixed by 0d724724!
How???

**Comment by stsp** [comment]
Should now be broken again.

**Comment by stsp** [comment]
This doesn't like the ascending order of get_mpa
or the number of pages owned by the OS handle.
Or something else... at least these parameters
affect the crash in different ways.

**Comment by jschwartzenberg** [comment]
Eww, another hack? So is win31_mode set to 1 for Windows 3.0?

**Comment by stsp** [comment]
win31_mode is 1 for real, 2 for standard and
3 for enhanced mode of windows.
win /r /s /3

**Comment by jschwartzenberg** [comment]
Maybe better call it win3x_mode at least? This enumeration makes sense. Maybe it would be nice to have constants for that.

**Comment by stsp** [comment]
You can send such pr.
