### ISSUE TITLE
dosemu -dumb to receive output of command not working

### ISSUE THREAD

**Issue by briceburg** [stsp/dosemu2#227]
It appears that the `-dumb` flags longer works, such as:

```
dosemu -dumb dir > listing
# from http://www.dosemu.org/docs/README/1.4/x724.html
```

I am getting `No such file: dir`

The command returns the following output

```
root@567c4a78f17d:/# dosemu -dumb dir
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4371:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4371:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4371:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4850:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM default
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
DOSEMU2 2.0pre6-dev-20160820-6-ge78a7ab
Configured: 2016-08-21 05:50:27 +0000
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org

FreeDOS kernel build 2036 cvs [version Aug 18 2006 compiled Aug 18 2006]
Kernel compatibility 7.10 - WATCOMC - 80386 CPU required - FAT32 support

(C) Copyright 1995-2006 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
UMB's unavailable!                                                             
dosemu XMS 3.0 driver installed.
dosemu EMS driver rev 0.7 installed.
[dosemu cdrom driver installed (V0.2)]


Access to cdrom denied.
Installation aborted.

Kernel: allocated 41 Diskbuffers = 21812 Bytes in HMA

FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre6-dev-20160820-6-ge78a7ab
No such file: dir
```

My **dosemu.conf**

```
$_hdimage = "/etc/dosemu/drives/c /etc/dosemu/drives/d"
```

/etc/dosemu/drives/d is the freedos drive, and the c drive config.sys and autoexec.bat follow:

```
root@567c4a78f17d:/# cat /etc/dosemu/drives/c/autoexec.bat
@echo off
rem autoexec.bat for DOSEMU + FreeDOS
path d:\dosemu;d:\bin;d:\gnu
set HELPPATH=d:\help
set TEMP=c:\tmp
sound /e
prompt $P$G
system -s CDROM_PATH
if "%CDROM_PATH%" == "" goto nocdrom
lredir2 -nC linux\fs%CDROM_PATH%
:nocdrom
system -s DOSDRIVE_EXTRA
if "%DOSDRIVE_EXTRA%" == "" goto nodrived
lredir2 -n linux\fs%DOSDRIVE_EXTRA%
:nodrived
rem uncomment to load another bitmap font
rem lh display con=(vga,437,2)
rem mode con codepage prepare=((850) d:\cpi\ega.cpx)
rem mode con codepage select 850
rem chcp 850
echo Welcome to dosemu2!
system -s DOSEMU_VERSION
echo     Build %DOSEMU_VERSION%
system -e
```

```
root@567c4a78f17d:/# cat /etc/dosemu/drives/c/config.sys   
rem generic config.sys for DOSEMU + any DOS
SWITCHES=/F
DOS=UMB,HIGH
lastdrive=Z
files=40
stacks=0,0
buffers=10
devicehigh=d:\dosemu\ems.sys
devicehigh=d:\dosemu\cdrom.sys
rem uncomment to load another bitmap font (see also autoemu.bat)
rem devicehigh=c:\dos\display.sys con=(ega,,1)
shell=d:\command.com /e:1024 /p
```

Is this supposed to be supported still? Thanks!

**Comment by briceburg** [comment]
as a followup, I searched and found a great discussion on this: https://github.com/stsp/dosemu2/issues/173

I believe the command (to simply pipe the output) is now;

```
dosemu -td -q -E <command>
```

My output is as follows
```
root@567c4a78f17d:/# dosemu -td -q -E dir
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4371:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4371:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4371:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4850:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM default
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
 Volume in drive C is mu/drives/c
 Directory of C:\

AUTOEXEC BAT           636  08-21-16  6:08a
CONFIG   SYS           328  08-21-16  6:07a
TMP                  <DIR>  08-21-16  6:01a
         2 file(s)            964 bytes
         1 dir(s)     48,599 Mega bytes free
```

is there a way to suppress the runtime alsa/error messages?

**Comment by stsp** [comment]
Hi, firstly, you can still use -dumb.
But you need to also give -E.
Sorry for that incompatibility.
The problem was that dosemu1 was not able to
reliably distinguish the DOS command and the
linux command. It did a lot of heuristic (even up
to searching the .com,.exe,.bat extenstions), but
that still didn't work in the most obvious cases.
So I just removed the crap. You now need to specify
explicitly what type of the command do you give.
Perhaps we need to start writing a migration guide.
The compatibility for the default setup is there and
is kept fully, so the migration wizard is not neede.
But all those small non-default features have changed
in many subtle ways...
We can also start using the separate directories, like
~/.dosemu2, so that people to stop even expecting the
compatibility with dosemu1 and run them in parallel, as
you can run dosbox. There is a vote for this, you can give
your voice.

Unfortunately we don't control the ALSA messages, but
the polite people would write them to stderr. So you can try
dosemu -dumb -E dir 2>/dev/null
and see if that helps. If alsa is not polite and writes to
stdout, perhaps we need to find some API to force it into
a quiet mode, or bugreport that to alsa bugtracker.

**Comment by briceburg** [comment]
This does make sense, and thanks for the pointers. I was able to learn more through the man page as well which I found very informative compared to cmd line help. 

redirected stderr to /dev/null does indeed suppress the alsa output, and dosemu doesn't appear to be writing its output to stderr on failed commands, so I think we're good! 

```
root@a4bca7e5e447:/# dosemu -dumb -q -E "dir aaa" 2>/dev/null
 Volume in drive C is mu/drives/c
File not found
```

+1 for a migration guide, do you think a markdown file in the repository root is a good place for this?

**Comment by andrewbird** [comment]
I see this suggestion on [Stackoverflow](http://stackoverflow.com/questions/24778998/how-to-disable-or-re-route-alsa-lib-logging) for redirecting stderr around the Alsa startup (via PortAudio in this case)
```C
freopen("/dev/null","w",stderr);
PaError err= Pa_Initialize();
freopen("/dev/tty","w",stderr);
```
I don't know if something similar is possible with Dosemu's use of Alsa, though preferably the messages would go to the logfile rather than the bitbucket?

Alternatively, and I haven't tried it, it may be possible to define a new error handler as this Alsa doc [page](http://www.alsa-project.org/alsa-doc/alsa-lib/group___error.html#ga6ba1f0aa6c6bc5d335ab297d6019cb03) suggests
~~~
int snd_lib_error_set_handler 	( 	snd_lib_error_handler_t  	handler	) 	

Sets the error handler.

Parameters:
    handler	The pointer to the new error handler function.

This function sets a new error handler, or (if handler is NULL) the default one which
prints the error messages to stderr.
~~~

**Comment by stsp** [comment]
> +1 for a migration guide, do you think a markdown file in the repository root is a good place for this?

You mean, a plain readme.md?
We have a documentation in a "doc" and "src/doc"
dirs, or we can start using the wiki.
readme.md doesn't look like the best place to me,
but if you should the results, then maybe I am convinced
otherwise? :)

**Comment by stsp** [comment]
> Alsa: redirect library logging from stderr to logfile #228

Thanks Andrew, but do we really need this?
Perhaps the user _wants_ to know why there is no
sound output, and your patch seems like hiding that
info.
We can alternatively use error() in the message handler,
which can then be suppressed on -q option (not sure
if this is the case right now, but can be done)

**Comment by andrewbird** [comment]
Well, IMHO spitting it out to stderr is messy, it isn't currently a fatal error and the boot.log file is the place to look when things aren't quite right. I'm not sure why the Alsa lib needs to be different and print to stderr itself. If we really care that sound is working we should be checking return values and handling them in the application.

For example on every startup of dosemu on my system I see the following, which I've learnt just to ignore.
~~~
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
~~~
The patch doesn't ignore the whinge, it just sends it to boot.log, and if I cared about sound that's where I'd go to find out what's wrong, just as I would about any other feature that wasn't working.

**Comment by stsp** [comment]
> Well, IMHO spitting it out to stderr is messy, it isn't currently a fatal error

This is really quite fatal for those who want sound,
which is really a majority. But I agree with you that
we should check the return values, as we currently
do:
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
The interesting case however is that the alsa errors
could better diagnose the problem to the user. I.e.
we can only print "No such file or directory" as does
strerror(), but this may be meaningless without what
alsa also writes.
So how about actually use error() for the "if (err)" case
in your patch, making sure -q suppresses that?

**Comment by andrewbird** [comment]
I meant not fatal in the sense that dosemu doesn't exit if sound issues are present, and I'd hope that it wouldn't ever be the case that a working sound system was required. I looked at error() but didn't see any advantage over the stderr printing we have now, except if it were extended to respect the -q switch. I do think that putting the alsa derived messages in the log should be enough to diagnose any sound issues, the only change is that it doesn't appear on stderr, so the diagnosis procedure is the same as with most other dosemu issues; look in the boot.log file. That said, if the cost of this patch is that you make a misconfigured sound system a fatal error ( dosemu exits) then please ignore this PR, the status quo is better!
Thanks, Andrew

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 21/08/2016  19:48  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Comment <comment@noreply.github.com> 
Subject Re: [stsp/dosemu2] dosemu -dumb to receive output of command not
  working (#227) 
 
Well, IMHO spitting it out to stderr is messy, it isn't currently a fatal error

This is really quite fatal for those who want sound,
which is really a majority. But I agree with you that
we should check the return values, as we currently
do:
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
The interesting case however is that the alsa errors
could better diagnose the problem to the user. I.e.
we can only print "No such file or directory" as does
strerror(), but this may be meaningless without what
alsa also writes.
So how about actually use error() for the "if (err)" case
in your patch, making sure -q suppresses that?

**Comment by stsp** [comment]
> I looked at error() but didn't see any advantage over the stderr printing we have now,
> except if it were extended to respect the -q switch. 

Yes, -q is the thing here. Otherwise they are same.
But your approach have a disadvantage because the
+S log is not always enabled. So the risk is to actually
lose some info that is currently available.

> make a misconfigured sound system a fatal error

Not of course. But hiding it too much is not very good
too. That said, your patch may be good by itself, we
can change it to error() and -q later if you think this is
too difficult to code.

**Comment by briceburg** [comment]
If I could vote, it would be to move these to the boot.log. I imagine most people would check there if their sound wasn't working -- but would expect it to output in the -h flag as well. 

Re: migration guide, maybe a general FAQ.md would do. I personally am accustomed to projects w/ useful README.md in repo root as it makes them accessible to casual viewers on github. Their markdown supports relative linking, so could link to a docs/MIGRATION_GUIDE or docs/FAQ from there as well?

I did manage to release w/ `-dumb -q -E <cmd>`, and have `deltree` working nicely -- as if it were a regular linux command!

```
[nesta@hartford dex]$ export DEX_BIN_DIR=~/bin
[nesta@hartford dex]$ ./dex.sh install --global deltree
building dex/v1-install/deltree:latest ...
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM briceburg/dosemu2:dex
 ---> 907704eac116
Step 2 : ENV DOSEMU_CMD "deltree" DOSEMU_FLAGS "-dumb -q -E"
 ---> Using cache
 ---> 5f542257a59b
Step 3 : LABEL "org.dockerland.dex.build-api" "v1" "org.dockerland.dex.build-imgstr" "deltree" "org.dockerland.dex.build-tag" "latest" "org.dockerland.dex.image" "deltree" "org.dockerland.dex.namespace" "dex/v1-install" "org.dockerland.dex.source" "extra"
 ---> Running in f8754e236ded
 ---> 8e338a650f5a
Removing intermediate container f8754e236ded
Successfully built 8e338a650f5a
built */deltree
installed /home/nesta/bin/ddeltree
installed /home/nesta/bin/deltree
[nesta@hartford dex]$ mkdir -p a/b/c
[nesta@hartford dex]$ deltree a
Delete directory "r:\home\nesta\git\dex\a" and all its subdirectories? [ynq] y
Deleting r:\home\nesta\git\dex\a...
[nesta@hartford dex]$ echo "yay"
yay
```

If you're interested, the dex project can be found here:
  https://github.com/dockerland/dex

My dosemu2 images:
  https://github.com/briceburg/docker-dosemu2

and of deltree is simply 
  https://github.com/dockerland/dex-dockerfiles-extra/blob/master/images/deltree/Dockerfile

Dex is still a WIP, but dosemu was important and I'd like to work on fun things like getting it running in alpine (compiling on musl, which I had some issues with and still trying to resolve) and playing w/ SDL2.

**Comment by stsp** [comment]
Yes, log, of course, sorry for forgetting to mention this:
@andrewbird the -q is one difference, and the log is another.
error() goes to log. Hope that addresses your concerns.

> Re: migration guide, maybe a general FAQ.md would do.

Very probably, with the links to docs.
In either case, anything is better than nothing, so if you have
some doc updates, please open a pull request without hesitations.

> If you're interested, the dex project can be found here:

Interesting. :) But I am really not on the subject.
Can this, for instance, be used for delivering DOS games
packaged together with dosemu, so that you can install and
run them as if it is native? Or perhaps this question makes no sense. :)

**Comment by stsp** [comment]
> Dex is still a WIP, but dosemu was important

Have you also tried dosbox?
