### ISSUE TITLE
Crash on 32bit

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#229]
I've bisected the problem to commit

ajb@polly:/clients/common/dosemu2.git$ git bisect bad
f27a90fe4ab15beafb5f66560637a8b3d45615f4 is the first bad commit
~~~
commit f27a90fe4ab15beafb5f66560637a8b3d45615f4
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sun Aug 14 17:39:48 2016 +0300

    disks: add read_mbr() helper
    
    This untangles the boot sequence a bit.

:040000 040000 1d74f91452192c538849c8cfe9dce794c97e8d6a fbaeda6f19b01d2e1277909ef6db4cf3e11eb9cf M	src
~~~

after which the following crash occurs
~~~
ajb@polly:/clients/common/dosemu2.git$ bin/dosemu.bin -D+cS -n -f test-imagedir/dosemu.conf --Flibdir test-libdir --Fimagedir test-imagedir
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=00000000 while in vm86 (DOS)
Program=do_vm86.c, Line=153
EIP: 0000:00007c78 ESP: 0000:0000fffc  VFLAGS(b): 01011 00000010 10000010
EAX: 0000ff80 EBX: 00000000 ECX: 00000000 EDX: 00000000 VFLAGS(h): 000b0282
ESI: 00000002 EDI: 00000002 EBP: 00000000 DS: 0040 ES: 0000 FS: 0000 GS: 0000
FLAGS: SF IF RF VM VIF  IOPL: 0
STACK: 46 00 00 00 03 00 84 e0 40 00 -> 00 00 00 00 00 00 00 00 00 00 
OPS  : 00 f0 1f c0 00 f0 20 c0 00 f0 -> c7 6f 00 f8 68 05 00 c0 23 c0 
	c76f00f868          0000:7c78 mov  word [bx],68F8
~~~

Do you need any other logs?

**Comment by stsp** [comment]
Could you please be specific?
What crashes? Should I remove the release?

**Comment by stsp** [comment]
Ah! This one is not in a release! Phew. :)
I was smart enough to keep this one out. :)
You've scared me to the hell...

**Comment by andrewbird** [comment]
Yes I should have said pre6 was good, but f27a90f broke it afterwards. Dosemu crashes on startup. I need to investigate further, but that's probably going to be tomorrow now.

**Comment by stsp** [comment]
Any progress?
No one else seem to have reported this
(may indicate different things though)

**Comment by stsp** [comment]
I did a small change, but it will unlikely change now
anything.

**Comment by andrewbird** [comment]
Mmm, I think I should close this for now. It seems that when testing the --Flibdir changes I'd left a stray empty directory ~/.dosemu/drives/c. Even when using --Fimagedir pointing at a valid installation this causes the existing code to show 'Sorry, there is no operating system here:' and exit. Note that's a DOS issued message. I think the crash happened with an older version of MS-DOS, whereas with 6.22 the message is displayed and the exit occurs okay. There probably is some issue lurking with older DOS, but unless I can repeat it at some point there's no hope of finding.

Closed as invalid
