### ISSUE TITLE
Settlers2: Crash when trying to select a free game map

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [stsp/dosemu2#23]
I was wrong: Dosemu crashes when trying to select another free game map, not when starting the default free game

**Comment by stsp** [comment]
Doesn't crash for me.
Please specify how exactly to reproduce.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I downloaded freedos and reinstalled siedler2 and now it works.
Until now I used the dos from a win98 bootdisk.

**Comment by stsp** [comment]
Please find if it is strictly related to win98dos.
If there is an easy way to reproduce, maybe
I'll take a look to improve the compatibility with
win98dos.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Freedos and my OLD settlers2 installation: working.
Win98dos with my NEW installation of settlers2: working.
Must have been something wrong with the old installation.

**Comment by stsp** [comment]
You can compare the directories of you installations
to find out which files differ and why.

**Comment by stsp** [comment]
Hmm, have you seen this:
https://launchpad.net/s25rttr
Looks like the native port of Settlers2 to linux!
Though I prefer SerfCity (aka settlers-1)

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Alas I do not own the gold edition which is required to play rttr

**Comment by stsp** [comment]
I think Gold edition just includes the CD music
instead of midi music. But I may be wrong.

You can as well try this:
https://github.com/freeserf/freeserf
