### ISSUE TITLE
ERROR: Drive C not defined can't boot! with clean installation

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#232]
When running DOSEMU2 without any ~/.dosemu directory, this error is shown:
> ERROR: Drive C not defined can't boot!

The installation code in install.c is not triggered like in the past.

**Comment by stsp** [comment]
Does anyone else reproduce this with current devel?

**Comment by aperezbios** [comment]
> On Sep 6, 2016, at 10:30 AM, Stas Sergeev <notifications@github.com> wrote:
> 
> Does anyone else reproduce this with current devel?
> 
> 
I experienced the same problem a week or two ago, but it is since fixed. I suspect he needs to update.

**Comment by jschwartzenberg** [comment]
I am testing with lastest git devel here.

**Comment by stsp** [comment]
I'll need vnc.

**Comment by jschwartzenberg** [comment]
Should be np. I have it on both systems I'm testing dosemu on.
