### ISSUE TITLE
It would be great to have.deb packages for Ubuntu/Debian!

### ISSUE THREAD

**Issue by ulrith** [stsp/dosemu2#233]
A repository with regular updates would be even better!...

**Comment by andrewbird** [comment]
I believe Ubuntu's Launchpad now allows Recipes to build for multiple targets(i386, x86_64) from git repositories. So perhaps someone could create one using the info [here](https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted). I'm not sure if that can be triggered with every repository change like the Bazaar based builds, but even if it's manual it could be done by a human when something significant happens like a tag being added. Of course the Recipe is not the whole thing, the Debian build process needs to be successful locally before thinking about getting the automation done. Perhaps the build files for dosemu1 could be obtained from [here](http://packages.ubuntu.com/xenial/dosemu) and modified to match dosemu2's requirements?

**Comment by stsp** [comment]
I pushed the basic version to master and
spent 2 days on integrating it properly in devel.
Should now be good.
Please get it some testing.

**Comment by stsp** [comment]
@andrewbird Yes, I used dosemu1 files as an
example, thanks for the link.
