### ISSUE TITLE
How to use vbootfloppy now?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#235]
I used to be able to boot from a virtual floppy with a minimal dosemu.conf as follows:
~~~
$_lpt1 = ""                                                                     
$_vbootfloppy = "drives/c"
~~~

Now I see the this message:
~~~
ERROR: can't boot from /clients/common/dosemu2.git/test-imagedir/drives/c, using harddisk
~~~
And booting is successful as if using $_hdimage = "drives/c", but this is not what I intended.

My use case is for making boot.blk for testing is as follows:
- Create bare hdimage file with known CHS geometry
- Populate "drives/c" with minimum files for boot + format.com + fdisk.com
- Create dosemu.conf with  $_vbootfloppy = "drives/c" & $_hdimage = "test.img"
- Boot into virtual floppy hosted DOS A:
- Using the correct DOS's fdisk command, create partition on C:
- Using the correct DOS's format command do 'format C: /s' to create filesystem and boot.blk
- Shutdown the DOS
- Extract the boot.blk from the hdimage

How can I achieve this goal?

**Comment by andrewbird** [comment]
For now I rolled back to using -pre6, which boots to A: as I expect.

**Comment by stsp** [comment]
I wonder why do we need this vbootfloppy stuff.
If you have time, perhaps it would be a good idea
to nuke it, together with bootoff tool.

**Comment by stsp** [comment]
Maybe it used to be good to select between
bootable and unbootable A this way, but now
we have $_bootdrive option just for this.

**Comment by stsp** [comment]
Done boot from normal floppies.
Now I think vbootfloppy can be finally nuked.

**Comment by andrewbird** [comment]
Thanks, that's working again for me.
