### ISSUE TITLE
nuke vbootfloppy

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#236]
With recent additions (like
https://github.com/stsp/dosemu2/commit/e78a7ab2a9384c5b17223c09cf807af501d79e09
and
https://github.com/stsp/dosemu2/commit/8c1c2aaf00c931f7eb6a0700880d4ea187f5c853
)
vbootfloppy is barely needed.
Someone should stand up to remove it,
together with "bootdisk" parser stuff, bootoff tool
and all the other mess.

**Comment by andrewbird** [comment]
So in the scenario of wanting to boot off A:, then fdisk/format an hdimage file as C: using the DOS native tools. Would I have to create a floppy image to boot from, or would there still be some method of booting from a directory as if it were a floppy?

**Comment by stsp** [comment]
You can use directory in $_floppy_a

**Comment by andrewbird** [comment]
Almost. I tried this dosemu.conf
~~~
$_lpt1 = ""                                                                     
#$_vbootfloppy = "drives/c"                                                     
$_floppy_a = "drives/c"                                                         
$_bootdrive = "A"                                                               
$_hdimage = "test.img"                                                          
~~~
With _vbootfloppy enabled, and _floppy_a/_bootdrive commented, boot works fine. With the conf as above boot hangs with just a black X-window and has to be killed with -9. If I change the 'A' to 'a', boot fails with the complaint 'ERROR: Drive A: not defined, can't boot!'

**Comment by andrewbird** [comment]
Maybe the non default paths are screwing things up, I use relative ones from the build directory
~~~
bin/dosemu.bin -q -n -f test-imagedir/dosemu.conf --Flibdir test-libdir --Fimagedir test-imagedir
~~~

**Comment by stsp** [comment]
Could you please see if the default ones
are better? I don't have this problem.

**Comment by andrewbird** [comment]
Yes I think it's a problem with a relative path in $_floppy_a not being prefixed with value of -Fimagedir. If I fully path as
~~~
 $_floppy_a = "/path/to/test-imagedir/drives/c"
~~~
the boot is successful. I presume this should be happening in global.conf, but I just can't see where?

**Comment by andrewbird** [comment]
Found it - PR coming soon!

**Comment by andrewbird** [comment]
BTW should I be able to boot from floppy_b also?
I specified
~~~
$_floppy_b = "drives/c"                                                         
$_bootdrive = "b"
~~~
but get the message
~~~
    ERROR: Drive B: not defined, can't boot!
~~~

**Comment by stsp** [comment]
Could you try defining both A and B and then try booting from B?

**Comment by andrewbird** [comment]
After I defined $_floppy_a = "drives/bob" and created the directory I got further. Now I get usual black window and
~~~
Starting MS-DOS ...
~~~
But never gets to DOS prompt and host has high CPU usage.This might be a MS-DOS 6.22 issue rather than a dosemu2 one. I'm not too worried, it was just a curiosity.

**Comment by stsp** [comment]
I wonder if under DOS you can have B without A?
I think it will became A. So you need to define A as
well, but we can improve that, I suspect.
For me, booting freedos from B works fine, but there
is also a new option $_swap_bootdrive to cure the
things like you describe. Of course it doesn't work for
floppies... I'll fix it.

**Comment by stsp** [comment]
Should now be better.

**Comment by andrewbird** [comment]
Yes $_swap_bootdrive works for me now with MS-DOS 6.22. It DOS booted from my B drive location and saw it as A:, also I could dir B: and see my A drive location.

**Comment by stsp** [comment]
You can as well now not define A and boot from B.
In which case it will became A though, disregarding
$_swap_bootdrive. Not sure if it worth the trouble to
improve this case any further.

**Comment by andrewbird** [comment]
Yes, that's almost perfect. If I do define 'A:' as follows, I still get the hang,
~~~
$_lpt1 = ""                                                                     
#$_vbootfloppy = "drives/c"                                                     
$_floppy_a = "drives/bob"                                                       
$_floppy_b = "drives/c"                                                         
$_bootdrive = "b"                                                               
$_hdimage = "test.img"                                                          
~~~
But I guess making the swap happen automatically if bootdrive is 'B:' would hurt the working FreeDOS boot to 'B:' drive you have?

**Comment by stsp** [comment]
> But I guess making the swap happen automatically if bootdrive is 'B:'

... and A is not defined. Not the case above.
As to why ms-dos doesn't boot from B, I don't know.
Someone have to try on real PC or on qemu.

**Comment by andrewbird** [comment]
Quick question about old vbootfloppy code. I see that if using an image file with $_vbootfloppy, the filesize is matched in global.conf against known sizes to select a particular geometry. If removing vbootfloppy option, is it necessary to add something similar to the $_floppy_X code?

**Comment by stsp** [comment]
It supports threeinch/fiveinch keywords, see
comments in the config. I dont think guessing
on the file size is a good thing to do.

**Comment by andrewbird** [comment]
I can't think of a situation where a DOS program should care about about what type of floppy disk it has except for some sort of funky copy protection, I suppose. At the DOS level, support for 5 1/4" 1.2Mb disks has been around for a long time, DOS 3.0 according to [Standard Floppy Disk Formats Supported by MS-DOS](https://support.microsoft.com/en-us/kb/75131), which is probably older than Dosemu2 will currently boot. So unless a user actually has an image or physical disk in an older format, I don't see a need to relay that info via $_floppy_X.

**Comment by stsp** [comment]
I was suspecting that the size of the actual
image can be determined from its boot sector,
and as such, even if you have the smaller image
than $_floppy_X expects, it will still work fine.
In which case the guessture on file size if not needed.
Am I wrong?

**Comment by stsp** [comment]
> I don't see a need to relay that info via $_floppy_X.

In fact, before my recent changes, the floppy type
was the primary info the one can specify via $_floppy_X.
You could also specify the device (/dev/fdX), but it was
optional. I made it so that the type is optional. Type can even
be removed if we don't need it. You can send a PR for that.
(one have to check that both 1.2 and 1.44 images still work)
What I think is only that the guessing on file sizes is not
needed either. I want to remove as much silly code as possible.

**Comment by andrewbird** [comment]
Yes I agree that the floppy image should have the chs in the boot sector which could be read to determine the geometry, but what about an unformatted floppy image, how would the geometry be determined such that DOS could format it? Note, I'm not saying there's anything wrong here just trying to view all the implications. :-)

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 25/09/2016  22:17  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Comment <comment@noreply.github.com> 
Subject Re: [stsp/dosemu2] nuke vbootfloppy (#236) 
 
I don't see a need to relay that info via $_floppy_X.

In fact, before my recent changes, the floppy type
was the primary info the one can specify via $_floppy_X.
You could also specify the device (/dev/fdX), but it was
optional. I made it so that the type is optional. Type can even
be removed if we don't need it. You can send a PR for that.
(one have to check that both 1.2 and 1.44 images still work)
What I think is only that the guessing on file sizes is not
needed either. I want to remove as much silly code as possible.

**Comment by stsp** [comment]
Unformatted floppy can get the good use
of threeinch/fiveinch stuff to be formatted
accordingly. I don't see why you need the
initial file size: the size will be changed during
formatting. You can create an initially empty
(zero-length) file and format it, and it will grow
to an image size. Forcing the user to dd the
actual size from /dev/zero is an exceptionally
annoying restriction.

**Comment by andrewbird** [comment]
Should I be able to boot from a floppy disk image (a 1.44MB DOS setup disk) using dosemu.conf?
~~~
$_floppy_a = "floppy.img"
$_bootdrive = "a"
~~~
I never tried a booting a floppy image before. The dosemu window error about missing OS seems to be coming from DOS as I couldn't find the string with 'git grep'. I tried adding the 'threeinch' prefix but it made no difference.

As a test, I mounted the image, extracted the boot files into a directory, then by setting
~~~
$_floppy_a = "dirname"
~~~
booting works well.

**Comment by stsp** [comment]
> As a test, I mounted the image, extracted the boot files into a directory, then by setting

This off-loads it to fatfs.c that builds a boot sector.
Booting from floppies the way you specified, should
work and was likely tested in this very thread.
Perhaps your image is not bootable?

**Comment by andrewbird** [comment]
I did try with another image, with the same result. Tomorrow I'll try to get some more info. I suppose this should be a new issue too? Thanks.

**Comment by stsp** [comment]
Who knows... In fact, looking at that thread again I can
see we only tested the directory boot. So the image boot
was likely never tested and needs more work before
vbootfloppy can be nuked.
Would be great if you can take a look.

**Comment by stsp** [comment]
Thanks!
