### ISSUE TITLE
Stable platform install instructions

### ISSUE THREAD

**Issue by ccarcel** [stsp/dosemu2#242]
Hi,

I am have installed the pre6 on a clean build - Ubuntu 12.04 and CentOS 7

they are minor issues that chnage from Linux flovours.

I have had it working in devel mode using github but would like to be able to run from installer. 

I get this on both my new builds - 
ERROR: libao support not compiled in or not found:
ERROR: libao.so.4: cannot open shared object file: No such file or directory
ERROR: sdl support not compiled in or not found:
ERROR: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
ERROR: fluidsynth support not compiled in or not found:
ERROR: libfluidsynth.so.1: cannot open shared object file: No such file or directory

I do not seem to be able to get these packages install as the DOSEMU2 expects.

I would like to create a small OVF template that I could share.

**Comment by stsp** [comment]
The packages on the release page were built for
ubuntu-16.04 and fedora-24.
If you installed them on a very old distros, perhaps
you should just run 'dosemu -t' and see if maybe the
text-mode works (and ignore all printed errors).

Alternatively you can try to build the packages for your
system yourself. You should get the devel code and do
either "make rpm" or "make deb". Of course I haven't
tested this on such old distros, so something may go
wrong also with that approach.

**Comment by stsp** [comment]
@andrewbird I know you had many distros
installed somewhere. Maybe if you have time,
you can build the packages for them which I'll
upload...

**Comment by andrewbird** [comment]
@stsp I almost have the Ubuntu Launchpad build farm building the currently supported platform packages automatically, see https://code.launchpad.net/~dosemu2/+recipe/dosemu2-daily . If you have a launchpad account I can add you as admin for Dosemu2 team. Unfortunately the packaging process requires the build occurs in a bzr repository if I want automatic source import from the github repo. There is a 'changelog' target in the Makefile that relies upon 'git log' being present and working. Currently the build is failing because it can't find the 'git' binary on the build machines. Perhaps you can make the changelog population from git optional?

**Comment by stsp** [comment]
I wouldn't care much about the changelog being
packaged. So how about this:
if [ -d .git -o -f .git ]; then
git log >$@
else
echo "See git log for changelog" >$@
fi

**Comment by andrewbird** [comment]
Thanks, that looks good, although I haven't the ability to test at the moment.

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 07/10/2016  17:47  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Mention <mention@noreply.github.com> 
Subject Re: [stsp/dosemu2] Stable platform install instructions (#242) 
 
I wouldn't care much about the changelog being
packaged. So how about this:
if [ -d .git -o -f .git ]; then
git log >$@
else
echo "See git log for changelog" >$@
fi

**Comment by stsp** [comment]
Done.
HTH.

**Comment by ulrith** [comment]
Hi!

I've got similar errors when try to start dosemu in Docker with Ubuntu Xenial:

```
ERROR: libao support not compiled in or not found:
ERROR: libao.so.4: cannot open shared object file: No such file or directory
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
ERROR: fluidsynth support not compiled in or not found:
ERROR: libfluidsynth.so.1: cannot open shared object file: No such file or directory
ERROR: alsa_midi (ALSA lib): seq_hw.c:457:(snd_seq_hw_open) : No such file or directory open /dev/snd/seq failed
```
Do you have any advices please? :)

**Comment by ccarcel** [comment]
Try Ubuntu 14.xx or cent Os 7. I have struggled to get all the correct devalopers tools for the new version to run smoothly on older Linux systems.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: ulrith <notifications@github.com> Date: 15/01/2017  17:00  (GMT+00:00) To: stsp/dosemu2 <dosemu2@noreply.github.com> Cc: ccarcel <claude@carcel.co.uk>, Author <author@noreply.github.com> Subject: Re: [stsp/dosemu2] Stable platform install instructions (#242) 
Hi!
I've got similar errors when try to start dosemu in Docker with Ubuntu Xenial:
ERROR: libao support not compiled in or not found:
ERROR: libao.so.4: cannot open shared object file: No such file or directory
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
ERROR: fluidsynth support not compiled in or not found:
ERROR: libfluidsynth.so.1: cannot open shared object file: No such file or directory
ERROR: alsa_midi (ALSA lib): seq_hw.c:457:(snd_seq_hw_open) : No such file or directory open /dev/snd/seq failed

Do you have any advices please? :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stsp/dosemu2","title":"stsp/dosemu2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stsp/dosemu2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ulrith in #242: Hi!\r\n\r\nI've got similar errors when try to start dosemu in Docker with Ubuntu Xenial:\r\n\r\n```\r\nERROR: libao support not compiled in or not found:\r\nERROR: libao.so.4: cannot open shared object file: No such file or directory\r\nALSA lib confmisc.c:768:(parse_card) cannot find card '0'\r\nALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory\r\nALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings\r\nALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory\r\nALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name\r\nALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default\r\nERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory\r\nERROR: fluidsynth support not compiled in or not found:\r\nERROR: libfluidsynth.so.1: cannot open shared object file: No such file or directory\r\nERROR: alsa_midi (ALSA lib): seq_hw.c:457:(snd_seq_hw_open) : No such file or directory open /dev/snd/seq failed\r\n```\r\nDo you have any advices please? :)"}],"action":{"name":"View Issue","url":"https://github.com/stsp/dosemu2/issues/242#issuecomment-272708110"}}}

**Comment by stsp** [comment]
@ulrith its not exactly the same.
For example you've got successfully loaded
SDL, but it says sound card is not available.
I think you can safely ignore the errors, or you
can try `$_sound = (off)` in dosemu.conf.
I don't know why you have the libao error
(see if libao4 package is installed), but it
should disappear once you disable sound.

**Comment by andrewbird** [comment]
I wonder if the software was built from source, or installed via a package?  If it's a package then perhaps the packaging is missing a dependency definition.

**Comment by stsp** [comment]
@andrewbird we have libao4 in "Recommends", I
wonder if this is enough...
It was likely installed from package because if it
is built from sources and the dev packages were
missing, it will not compile the appropriate plugins,
and as such, can't have such dependency.
But what package was installed and from where -
is the question. It could have been some older
package that didn't have the deps right.

**Comment by andrewbird** [comment]
I suppose as libao-dev is in build depends it should really have libao in runtime depends, else if libao is not installed we would get the error we see here. You probably need to promote libao from Recommends to Depends, do you agree?

**Comment by stsp** [comment]
Its the opposite to what I've done: they were
initially in Depends when I first implemented
the debuild support, and they are in Depends
in the package that is linked from the releases
page. But having them in Depends forever,
diminishes the use of the dynamic plugins.
They are here exactly for this reason: to allow
dosemu to run even in absence of an optional libs.
I would find it very annoying if I only wanted to
run dosemu in dumb terminal mode and it would
take the entire X stack + SDL just for depends.
So isn't it better to just shut up an errors?

Note that by default Recommends is not any different
from Depends, so even the current situation may
result into someone's downloading many unneeded
depends, but at least he can willingly avoid that.
I think the OP did something unusual to get the
missing deps.
