### ISSUE TITLE
PC DOS 2000 setup /A is very slow with KVM

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#247]
When I run "setup /A" in a directory with all the PC DOS 2000 installation files, DOSEMU become extremely slow, its CPU usage is at 99-100%.

Steps to reproduce:
1. Download and extract all PC DOS 2000 diskimages (1).
2. Start dosemu2
3. lredir2 f: linux\fs\dir\with\pcdos2k
4. f:
5. setup /A
6.Try to move the selection. It's very slow. In dosbox it's much faster.

(1) Page with the disk images of PC DOS 2000: https://archive.org/download/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip/

**Comment by stsp** [comment]
Is this a regression?

**Comment by jschwartzenberg** [comment]
I forgot to test this, but I just found that this do not happen when $_cpu_vm is set to emulated. It only happend with $_cpu_vm set to kvm. I'll update the title.

**Comment by stsp** [comment]
Is this still a problem?

**Comment by jschwartzenberg** [comment]
I cannot reproduce this anymore. With recent Git and following my own instructions from back then it's fast now with KVM.

**Comment by stsp** [comment]
Thanks for an update.
