### ISSUE TITLE
Radeon on Ubuntu 14.04 (+16.04 HWE stack) doesn't work in SDL mode

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#248]
As in title. Going back to 03dff3f fixes it. llvmpipe doesn't help, neither does tweaking the filters.

**Comment by stsp** [comment]
Try $_SDL_nogl=(on)

**Comment by jschwartzenberg** [comment]
I can confirm with latest git & nogl it works again now!

**Comment by stsp** [comment]
Thanks!
Btw, if someone else report this, I'll have
to make the old code default again. :(

**Comment by stsp** [comment]
Could you please try sdl_nogl branch?
I am hoping for a simpler fix there.

**Comment by jschwartzenberg** [comment]
It seems to work. I don't need to explicitly specify nogl in the config anymore either.

**Comment by stsp** [comment]
> It seems to work. I don't need to explicitly specify nogl in the config anymore either.

Looks like you edited your message.
Does it work sometimes even without nogl?
I was also hitting the very strange effect when
the dosemu window is entirely transparent: no
drawing at all and underlaying windows are all
visible. But this happens for me only sometimes
on ubuntu and never on fedora.
Is this what you see?

**Comment by jschwartzenberg** [comment]
Yeah, sorry. I just had failed to save the config properly after commenting nogl and realised that shortly after posting here.

I never saw a transparent window.

**Comment by stsp** [comment]
What do you see when the problem happens?
Black window?

**Comment by jschwartzenberg** [comment]
Yes, exactly.

**Comment by stsp** [comment]
OK, I suppose I have to write the proper
rendering code instead of papering around
the regressions with the soft renderer.
Lets reopen this.

**Comment by stsp** [comment]
Could you please test the new "rend" branch?
It is full of hacks so far, but I wonder if it affects
your problem anyhow.

**Comment by jschwartzenberg** [comment]
Instead of a black window, nothing is rendered at all with the "rend" branch when I enable OpenGL (comment $_SDL_nogl = (on)).

**Comment by stsp** [comment]
What exactly? A transparent window?
Could you please try a few times? I've
seen transparent window myself at occasions,
but for me it happens very rarely.

**Comment by jschwartzenberg** [comment]
It appears transparent (when you move it's clear that just nothing is drawn inside the window). This happens every single time I run dosemu.

**Comment by stsp** [comment]
Could you please re-test after pull?

**Comment by jschwartzenberg** [comment]
Now the window stays black. I discovered that when I shade (roll up) the window and then back, I see the cursor flashing. Then pressing some keys reveals the rest is drawn as well, but it's all very slow compared to the nogl rendering.

**Comment by stsp** [comment]
> I discovered that when I shade (roll up) the window and then back

Is it the same with devel or new?

**Comment by stsp** [comment]
Could you please retry?

**Comment by jschwartzenberg** [comment]
With devel the shading actually solves the issue and rendering is fast then. I'll try these fixes as well now.

**Comment by jschwartzenberg** [comment]
With rend it's not fixed. I still need to do a shade+unshade. While the performance is better than before, it's still worse than devel after shade+unshade.

**Comment by stsp** [comment]
Its actually strange that its still not fixed.
Could you please confirm that on 1cdbb8ae
and bc47a0cf you see absolutely no difference?
What is shade/unshade?
Could you please record the video so that
I know exactly what you see and what you do?

**Comment by stsp** [comment]
> While the performance is better than before, it's still worse than devel

Performance will be improved later.
I need a working code first.
But it won't match devel, it will be a bit slower
even after every possible tuning. Fixing regressions
is more important than the speed.

**Comment by stsp** [comment]
I finished the code and pushed things to devel.
Could you please re-test?
Performance can now be measured too.

**Comment by stsp** [comment]
Could you please retry?

**Comment by jschwartzenberg** [comment]
There are still issues with the current code.
Just after starting:
![dosemu-sdlgl](https://cloud.githubusercontent.com/assets/877112/22182033/ae808056-e09a-11e6-9ea7-8b8d3c00b32a.png)

After shading/unsharing, triggering some display updates:
![dosemu-sdlgl2](https://cloud.githubusercontent.com/assets/877112/22182034/d7d865fe-e09a-11e6-867c-aaef9262a57f.png)

**Comment by stsp** [comment]
May this be because I messed up
your repo yesterday and you haven't
done 'git reset --h'?

**Comment by jschwartzenberg** [comment]
I reverted the file you changed (kept the diff) and then did 'git pull' and 'git clean -xf'.

**Comment by stsp** [comment]
Wholly sucks. :)
I am updating the code now and will push
it soon. if that won't help, I'll need your machine
again...

**Comment by stsp** [comment]
I pushed the latest update.
It likely doesn't change anything for you
but please try.

**Comment by stsp** [comment]
If devel still doesn't work, please try the sdl_fix branch.

It seems your sdl wants to bring us to
the stone age of the single-threaded rendering.
Every attempt of me to leave at least something
in a different thread, cases a failure.
It seems there is currently some work in progress
to teach sdl to use the Vulkan API. Vulkan API
was designed for threaded rendering, so perhaps
a few years later we'll finally be able to implement
the renderer without all the hacks I am currently
adding... Another option is to return to the drawing
surface and forget about these textures forever.

**Comment by jschwartzenberg** [comment]
Indeed didn't help. I guess you'll need access to my system again?

**Comment by stsp** [comment]
Even sdl_fix branch?

**Comment by andrewbird** [comment]
I have a pretty basic radeon card and I don't see any issues with SDL on Ubuntu 16.04
~~~
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV516 [Radeon X1300/X1550 Series]
~~~
Is there some special feature that is unavailable to me on older radeon chipset?

**Comment by jschwartzenberg** [comment]
Whoops, sorry I read over that. That branch indeed works!

**Comment by stsp** [comment]
Andrew, he is using 14.04 + 16.04 HWE stack.
This likely means 14.04 userspace + proprietary
drivers for 16.04. We can't replicate this setup
of course.

**Comment by stsp** [comment]
> Whoops, sorry I read over that. That branch indeed works!

Thanks, but it has the hack that moves texture
unlock to the main thread while leaving the texture
lock to the render thread... And overall the sdl plugin
became completely botched in a last couple of days.
Sigh.

**Comment by stsp** [comment]
Could you please test sdl_rend branch?

**Comment by stsp** [comment]
In $_SDL_swrend on and off modes.
I bet 'off' won't work for you even now...

**Comment by jschwartzenberg** [comment]
With $_SDL_swrend = (on) it works otherwise it doesn't.

**Comment by stsp** [comment]
OK, thanks for confirming.
In this case I will not switch to hw rendering
by default and will instead concentrate on
improving the sw rendering.
