### ISSUE TITLE
Strange compiler messages on 32 bit

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#253]
This compiler message appears when building on 32bit Ubuntu 16.04. I've not noticed any problems with Dosemu I can attribute to it, but I expect it will probably need fixing.

~~~
In file included from ../../../src/include/cpu.h:370:0,
                 from ../../../src/include/emu.h:17,
                 from lfn.c:23:
lfn.c: In function ‘getfindnext’:
lfn.c:709:38: warning: right shift count >= width of type [-Wshift-count-overflow]
  WRITE_DWORD(dest + 0x1c, st.st_size >> 32);
                                      ^
../../../src/include/memory.h:248:60: note: in definition of macro ‘UNIX_WRITE_DWORD’
 #define UNIX_WRITE_DWORD(addr, val) (*(Bit32u *) (addr) = (val) )
                                                            ^
lfn.c:709:2: note: in expansion of macro ‘WRITE_DWORD’
  WRITE_DWORD(dest + 0x1c, st.st_size >> 32);
  ^
~~~

From lfn.c the intention looks as if to write a 64 bit offset as 
```C
        WRITE_DWORD(dest + 0x20, st.st_size);                                   
        WRITE_DWORD(dest + 0x1c, st.st_size >> 32);                             
```
but on 32bit we have a struct stat with 32 bit st_size, so what is the correct fix, switching to stat64()?

**Comment by andrewbird** [comment]
Mmm, I'm coming round to the idea that >2 GB files are broken with lfn on 32 bit machines. There are other cases of st_size being cast to shut up the compiler warning in lfn.c e.g.

```C
                WRITE_DWORD(buffer + 0x20, (unsigned long long)st.st_size >> 32);
                WRITE_DWORD(buffer + 0x24, st.st_size);                         
```
Any objections to switching to stat64() and culling the casts?

**Comment by stsp** [comment]
Thanks for spotting this!

**Comment by andrewbird** [comment]
Wow, that was easier than modifying the stat calls to stat64 etc! So what about the cast to (unsigned long long) in lfn.c at  lines 1273 & 1277, is that purely for signedness now? I looked at DOS's [DIsk Transfer Area](http://stanislavs.org/helppc/dta.htm) but couldn't decide if the DWORD should be signed or not, but I suspect it's impossible to a negative filesize.

**Comment by stsp** [comment]
Yeah, I guess its just for signedness...
And I'd say encoding st_size with a signed type
(instead of size_t or alike) is silly. I don't think this
cast is really needed though, maybe the right shift
is fine for signed types (left shift is UB, IIRC), but
I'd leave it. When something silly is going on, we have
a right to react in a silly ways. :) If someone uses
signed types for file size, we just cast the sign away.
