### ISSUE TITLE
Booting from floppy image fails

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#254]
1/ As a test I created dosemu.conf as follows (threeinch was needed as format defaulted to 360kB):
~~~
$_lpt1 = ""                                                                     
$_hdimage = "drives/c:hdtype9"                                                 
$_floppy_a = "threeinch:floppy.img"                                             
$_bootdrive = "c"                                                               
~~~~

2/ touch floppy.img

3/ I was able to boot from the C drive, format the floppy image as 1.44MB with 'format /s'.

4/ Changed dosemu.conf to following:
~~~
$_lpt1 = ""
$_hdimage = ""                                                                                                  
$_floppy_a = "threeinch:floppy.img"                                             
$_bootdrive = "a"
~~~

5/ Try to boot to floppy drive, but fails with "Boot failure" message.

6/ After pressing enter in DOS window twice, dosemu crashes (but that's a secondary issue)

I've attached the +dRW log, and to me it looks like the floppy has no geometry

[floppy_boot_fail.txt](https://github.com/stsp/dosemu2/files/581596/floppy_boot_fail.txt)

Perhaps this line is significant
~~~
device: /clients/common/dosemu2.git/test-imagedir/floppy.img type 2 h: 0  s: 0   t: 0 floppy A:
~~~
 
Note: I also tried creating the file first with "dd if=/dev/zero of=floppy.img bs=512 count=2880" as the image file created by dosemu (and DOS format) was undersize for 1.44MB floppy, but the boot failure was the same.

**Comment by andrewbird** [comment]
Just a quick note to let you know that I'm working on fixing this and removing vbootfloppy [#236] in a follow up patch

**Comment by stsp** [comment]
Thanks!
