### ISSUE TITLE
Underscore keypress is ignored in terminal mode

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#256]
When booting into terminal mode (-t or -td) the underscore key is no longer printed, or executed. For example I have a batch file called 'test_mfs.bat' but if I start typing its name I just see 'testmfs' appear on the terminal. I've bisected it to the following commit

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[a41687d8d29cdba83123115db621015c317fc0d2] kbd: disable pic EOI keyboard hack

**Comment by andrewbird** [comment]
As a test I tried setting KBD_PIC_HACK to 1, which fixed it for me.

**Comment by stsp** [comment]
Pre-existing bug.
Thanks for spotting!
