### ISSUE TITLE
Creative SB16 driver installer (for Windows 3.1) hangs at SB16 detection

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#259]
I'm trying the SB16 installer to install the Windows 3.1 drivers. It can be downloaded here:
http://files2.europe.creative.com/manualdn/Drivers/Others/272/s16dw3up.exe

When ran, dosemu/the installer hangs at the moment it should detect the SB16. In dosbox the detection works.

This is not a regression, 1.4 also has this problem.

**Comment by jschwartzenberg** [comment]
Trying these Sound Blaster Pro drivers in Windows for Workgroups 3.11 gives a 'division by zero' error:
http://www-ftp.lip6.fr/ftp/pub/pc/garbo/windows/drivers/sbpw31.zip

It seems the drivers included with Windows itself are the only working ones. (Creative Labs Sound Blaster 1.5)

**Comment by stsp** [comment]
Please attach the -D9+Sq log

**Comment by jschwartzenberg** [comment]
Indeed a lot of output regarding SB, the last two line continue repeating infinitely:
[boot.log-sb16-installer-hangs-at-detection.txt](https://github.com/stsp/dosemu2/files/601457/boot.log-sb16-installer-hangs-at-detection.txt)

**Comment by stsp** [comment]
I added some dosbox code.
Please provide the new log.

**Comment by jschwartzenberg** [comment]
Now it detects an SB16 correctly but the installer still doesn't complete successfully, because it doesn't consider C to be a "fixed drive".
Here's the new log till that point:
[boot.log.txt](https://github.com/stsp/dosemu2/files/604751/boot.log.txt)

**Comment by andrewbird** [comment]
Presumably it's an lredired drive. I wonder what should be done to cope with that?

**Comment by stsp** [comment]
What's the error message?
Can you try hdimage as D and install it there?

**Comment by jschwartzenberg** [comment]
Here are the question & error. I should note this is after copying the files. For that C:\SB16 is accepted.
![dosemu-sb16-1](https://cloud.githubusercontent.com/assets/877112/20640051/600b1b76-b3d5-11e6-9912-2aa780a597e7.png)
![dosemu-sb16-2](https://cloud.githubusercontent.com/assets/877112/20640050/600aaf6a-b3d5-11e6-9959-7c8fb3b35c96.png)

**Comment by jschwartzenberg** [comment]
With a hdimage it's indeed possible to finish the installation.

**Comment by jschwartzenberg** [comment]
Note that this does not seem like a complete installation set (just an update), so it seems there's another driver I should look for for using with Windows 3.1. I'll open another issue when I run into issues installing a complete driver set.

**Comment by stsp** [comment]
Is this still a problem?

**Comment by jschwartzenberg** [comment]
The hang was solved from the subject, but most driver sets still cannot be installed without using hdimage.

**Comment by stsp** [comment]
You mean, you re-tried that recently enough?

**Comment by jschwartzenberg** [comment]
I did not try them all, but the set I do use stops at the same issue at some point during the installation.

The set from https://github.com/jschwartzenberg/dos-download-scripts/tree/master/sb16w31:
1. copies all the files in place
2. checks whether it's pointed to a fixed drive (to update the boot files), without an hdimage it will only let you abort the installer at this point

End result: all files are in `c:\sb16`, running `winsetup.exe` from Windows installs the Windows drivers.

Most the other sets that you find online:
1. check whether they are pointed to a fixed drive, in dosemu without hdimage, **it will only let you abort the installer at this point**
2. _copies the files in place => this is not reached without an hdimage_

End result: nothing was extracted/installed, nothing to install inside Windows

So while in both cases one cannot fully finish installing, the first set above allows finishing the installation manually.

**Comment by stsp** [comment]
I think these days we are well equipped
to debug the redirector problems.
Andrew, would you like to take a look?

**Comment by andrewbird** [comment]
Will check later, but it's probably a valid thing to test if the boot drive is a real HD. I saw similar thing when trying to install msclient 3.0 networking on an MFS (networked drive), again reverting to an hdimage allowed proper installation.

**Comment by stsp** [comment]
It just says its not a fixed disk.
Which looks very similar to this:
https://github.com/stsp/fdpp/commit/5f06d9e32248dacf02ab0c5e6ff8dde9d5f747d7
My guess is that this can be an intentional
behaviour only if it uses some int2f API
directly, or maybe checks if the driver is
remote with ioctls - quite an unlikely situation.
It is much more likely that it confuses
this drive with a floppy.

**Comment by andrewbird** [comment]
Ahh, okay I hope so. I had a vision of it searching LoL for CDS head and indexing!

**Comment by andrewbird** [comment]
The installer asks for the DPB from the target drive, see [rbil](http://www.ctyme.com/intr/rb-2724.htm), DOS returns AL == 0xff, which means invalid or network drive.
```asm
0d30:2fdd CD21             int  21                                              
int 0x21, ax=0x3246                                                             
RET INT0xe6 eax=0x00003246 ebx=0x00004acf ss=0x5204 esp=0x000034c8              
           ecx=0x00000000 edx=0x00050003 ds=0x10e5  cs=0xf000 ip=0xf6ce         
           esi=0x0001375e edi=0x00000838 es=0x0001 flg=0x00030046               
RET INT0x16 eax=0x00041100 ebx=0x0000035a ss=0x00da esp=0x000008e0              
           ecx=0x00000d30 edx=0x00050000 ds=0x00da  cs=0x0070 ip=0x018c         
           esi=0x0001063a edi=0x00005204 es=0x4acf flg=0x000b0246               
iret INT0x21 eax=0x000432ff ebx=0x00004acf ss=0x5204 esp=0x000034d6             
           ecx=0x00000000 edx=0x00050003 ds=0x10e5  cs=0x0d30 ip=0x2fdf         
           esi=0x0001375e edi=0x00000838 es=0x0001 flg=0x000b0346               
MHP:>                                                                           
AX=32ff  BX=4acf  CX=0000  DX=0003  SI=375e  DI=0838  SP=34d6  BP=34de          
DS=10e5  ES=0001  FS=0005  GS=0000  FL=000b0346                                 
CS:IP=0d30:2fdf       SS:SP=5204:34d6                                           
                                                                                
0d30:2fdf 5D               pop  bp                                              
```

Not sure if there's anything that can be done about that?

**Comment by stsp** [comment]
Well, the obvious "fix" would be to use
DPB from underlying drive... And can only
be done with fdpp...
Perhaps nope.

Thanks for analysing that!

**Comment by jschwartzenberg** [comment]
Yes, as suspected. At least the issue can be worked around with the right driver set. It took me quite a lot of trying of different driver sets to find one that does the trick :)

**Comment by stsp** [comment]
Are they any better than the built-in ones?

**Comment by jschwartzenberg** [comment]
Yes of course, way better. You get 44.1 kHz stereo sound with them! The built-in ones don't offer that.
