### ISSUE TITLE
Impossible to install Video for Windows or WinG inside WfW 3.11

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#260]
Downloads can be found here:
http://www.win31.de/esoft.htm

These (and several other installers) give the message: "Insufficient memory or disk space."

**Comment by jschwartzenberg** [comment]
As the a671649 commit message mentions working Video for Windows support, it would be nice to be able to bisect from this version. It's rather old though and relies on vm86 support, so it won't run on a 64-bit system. I'm setting this up on a 32-bit system now. Attached a patch that allows compilation on Ubuntu 14.04.
[patch1.txt](https://github.com/stsp/dosemu2/files/590548/patch1.txt)

**Comment by andrewbird** [comment]
I just thought it worth mentioning since you say it relies on the vm86() system call, that you would be wise to make sure it does actually work with commit a671649 before you start bisecting. I believe that the vm86() changes in the kernel since 2004 might affect that. I could save you a lot of time bisecting back to that commit to find that it doesn't work any more with a modern kernel. Hope it helps :-)

**Comment by jschwartzenberg** [comment]
Thanks for the note. I'll be sure to test that first! Also I should make sure it doesn't work with the newer version on a 32-bit system like this I guess.

Another note. To compile on Ubuntu 14.04 i386 I had to add CFLAGS=-U_FORTIFY_SOURCE CPPFLAGS=-U_FORTIFY_SOURCE in front of ./default-configure.

**Comment by jschwartzenberg** [comment]
Now I've got both the old and the new version working in a VM, but the old dosemu version can't find any command.com. I tried it with both FreeDOS and MS-DOS 6.22.

With the new dosemu version I can confirm that the installers not working either.

**Comment by stsp** [comment]
> Attached a patch that allows compilation on Ubuntu 14.04.

The patch is for the old version of course, right?
You can set up the branch for that with the patch applied,
so other people can help you testing.
But I wonder if that would be me because I don't have
the 32bit system around. If you can get that to work on
qemu, then it would be interesting.

> Now I've got both the old and the new version working in a VM, but the old
> dosemu version can't find any command.com.

Older dosemus were case-sensitive.
Maybe your command.com is upper-cased on FS?
Just shoot into a dark...

**Comment by jschwartzenberg** [comment]
Yes, the patch is for that revision specifically. All files are lower-case. Even when using the dosemu-freedos tarball with 'make install' and letting dosemu use that, it doesn't work.

I have a 3.3 GB vmdk file now btw. Maybe I can try a slightly newer revision and see if that works.

**Comment by andrewbird** [comment]
Mmm, I just wondering if you are running into an old issue. At some point dosemu used strcpy with overlapping source/target range. This is undefined behaviour if I remember correctly, and worked for years without issue. At some point newer versions of glibc started optimising strcpy calls using simd instructions which specifically disallows this, and so dosemu promptly fell over until it was patched. I looked for the patch but can't seem to find the issue over at sourceforce, but it's in current git of course. I think it's 506c7965 but you might only need the single line from 'build_ufs_path_()'

Hope it helps

**Comment by jschwartzenberg** [comment]
I'm doing a bisect now to see which revision solved the command.com not loading issue. I should be there soon :)

**Comment by jschwartzenberg** [comment]
The bisect indeed went to the commit you pointed out! I applied this patch against the old version and it boots up now. But the installers still do not work. So it indeed seems this problem is related to something else.

I wonder what to try next now.

**Comment by andrewbird** [comment]
I only remembered that strcpy issue because I used to keep an old version of 1.2.2 running for a friend of mine on his latest Ubuntu / hardware. I don't have any idea about the installers I'm afraid :-(

**Comment by stsp** [comment]
@jschwartzenberg likely meant the installer of the
windows media player.
You can set up the separate branch, apply your compilation
patch there, and then also cherry-pick 506c796 to get
things working.

**Comment by stsp** [comment]
> The bisect indeed went to the commit you pointed out!

Good extrasensory abilities indeed. :)

**Comment by jschwartzenberg** [comment]
> You can set up the separate branch, apply your compilation
patch there, and then also cherry-pick 506c796 to get
things working.

That's exactly what I did! (Apart from creating a branch in git.) But even then the Video for Windows installer and the WinG installer do not work.

So it seems that there's another factor that causes it not to work, not a regression in dosemu. Maybe what @andrewbird suggests, due to the kernel or maybe there's something wrong with my configuration. I just have no idea how to proceed. Maybe I could test it with an older kernel/distro. It would be nice if anybody else could try to reproduce this.

**Comment by stsp** [comment]
It is entirely possible it never worked.
The problem was brought up by someone in an
ML (was that you? I don't remember), and he
confirmed the video now works. Whether installer
worked, is unclear. Unless it was you, we can't tell.

**Comment by jschwartzenberg** [comment]
I don't remember this. I don't think it was me on the mailing list. Do you think you could try to reproduce this problem?

**Comment by stsp** [comment]
In either case please provide an URL.

**Comment by stsp** [comment]
I tried under windows-3.1 and everything works perfectly
except that it is in German so I don't know what choices
have I done during install.

**Comment by jschwartzenberg** [comment]
I can confirm it's all working with Windows 3.1 here as well!

So it's really just broken with Windows for Workgroups 3.11 it seems. Maybe it's related to "32-bit file access". https://en.wikipedia.org/wiki/Windows_3.1x#Windows_for_Workgroups

**Comment by jschwartzenberg** [comment]
My Windows 3.1 installation developed the same issue now...

**Comment by stsp** [comment]
Huh?
Please find the reason of that change.

**Comment by jschwartzenberg** [comment]
Yep, I will try to rebuild my Windows installation and see if I can trigger it and when that happens. I probably won't have time for that before the weekend though. Btw. it would be very nice if there would be a feature similar to Wine's WINEPREFIX feature. It would make switching between different set-ups for testing much easier.

**Comment by andrewbird** [comment]
Can you use --Fimagedir /path/to/directory/above drives?

**Comment by stsp** [comment]
> Can you use --Fimagedir /path/to/directory/above drives?

Does this work?
According to #80 it doesn't.

**Comment by andrewbird** [comment]
Always works for me , except that you have to be careful not to have a matching path in ~/.dosemu.

For example:
~~~
bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir -o out.log -D+dRW
~~~
runs the images in ./test-imagedir/drives/ assuming you have $_hdimage = "drives/*" in test-imagedir/dosemu.conf

The only wrinkle is, as I suggested earlier, even though you specify imagedir, by default it still looks in ~/dosemu first.
I have a patch here that I worked on a while back that pushed the directory search logic into C, but was called from the parser, and was common for floppy and hdimage processing. This had the advantage of killing off quite a bit of global.conf. It seemed quite elegant, but the problem I had then was how to handle the default 'drives/*' as that needs to be globbed in each of the directories and of course it increases the number of strings returned the more matches it finds. It'll need some more work before a PR, I think.

**Comment by stsp** [comment]
So I think this is a NOTABUG report.

**Comment by jschwartzenberg** [comment]
I'll retest this in any case at some point when I enhance my installer scripts to deal with WfW 3.11 as well.

**Comment by stsp** [comment]
> I can confirm it's all working with Windows 3.1 here as well!

That's what you said in some comment, and
as such I think this is not a bug.

**Comment by jschwartzenberg** [comment]
Ok, I don't know how different Win 3.1 and WfW 3.11 are. I suppose it mainly depends on whether enhanced mode is used as well.

**Comment by stsp** [comment]
You also said
`My Windows 3.1 installation developed the same issue now...`
so this really is not a bug likely.
Or maybe it is fixed, because I've fixed a
few difficult to reproduce crashes is windows
recently.
