### ISSUE TITLE
RFC: The flag position with floppy and harddrive directives in dosemu.conf is inconsistent

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#263]
I noticed that the flags used for floppy and harddrives are different:
- floppies use a prefix
$_floppy_a = "readonly:/dev/fd0"

- harddrives use a suffix
$_hdimage = "drives/test.img:readonly"

Is does anyone else find this strange? Is that enough reason to standardise it? Which should be the preferred format, if so?

**Comment by stsp** [comment]
The $_hdimage's one, of course.
Please go ahead and change $_floppy stuff.
I don't think it was ever uncommented by someone,
because images were supported via $_vbootfloppy.
