### ISSUE TITLE
SDL: copy/paste from dosemu window with mouse

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#271]
... does not work.

**Comment by andrewbird** [comment]
Not sure if [this](http://piumarta.com/squeak/icccm.html) describes part of the problem, or even related, but does outline an interesting argument.

**Comment by stsp** [comment]
Do you think SDL have changed to this?
Very probably but I have no idea how to veryfy that.

**Comment by andrewbird** [comment]
My desktop died, so I can't test myself at the moment. I'm wondering if this is a window manager 'feature',  AFAICR X windows should paste  Primary selection not Clipboard contents when middle mouse button is pressed. Some window manager that wants us to be more Windows like might paste Clipboard contents. Of course the same window manager would promote Primary selection to Clipboard by key press Ctrl Shift C or menu item copy. What's the behaviour you are seeing?

**Comment by stsp** [comment]
> My desktop died

Wasn't it an AMD-based desktop btw?
I've lost the count of my died AMD-based
desktops here...

> Of course the same window manager would promote Primary selection to
> Clipboard by key press Ctrl Shift C or menu item copy.

Under dosemu I am not getting anything by
pressing Ctrl Shift C, it just goes to the DOS program.

> What's the behaviour you are seeing?

Pasting with middle button something that was
previously selected in dosemu window, does not
work. Works with X plugin perfectly.
The problem is that our SDL plugin uses an X
calls to handle selection, which is of course wrong.
When writing an SDL plugin for dosemu2, I copied
that part from dosemu1 unfortunately. Of course
when something is copied without an understanding,
it doesn't work. Someone needs to rtfm on SDL-based
copy/pasting and implement that properly.

**Comment by andrewbird** [comment]
Yes it was an amd x2 5600, actually an identical Dell machine died the same way a month ago. 10 years after manufacture, it makes you wonder about inbuilt obsolescence?

It certainly sounds like selection is the problem, just to confirm I wonder if you run xcutsel does your selection make it to it?
Yes I think SDL plugin is probably not right to use X functions.

**Comment by stsp** [comment]
> 10 years after manufacture, it makes you wonder about inbuilt obsolescence?

Maybe that's a different problem.
I am having lots of AM3 mobos died with
VRM failure sympthoms, but am3 is not
10 years old like yours.

> Yes I think SDL plugin is probably not right to use X functions.

I am currently rewriting this part.
Looks not too difficult, lets see if I get something
ready within an hour...

**Comment by stsp** [comment]
> I am having lots of AM3 mobos died with
> VRM failure sympthoms

... not to mention that I am also having the
GPU overheat problems because of these:
https://bugzilla.kernel.org/show_bug.cgi?id=119211
https://bugzilla.redhat.com/show_bug.cgi?id=1340662
https://bugzilla.redhat.com/show_bug.cgi?id=1340949

And I  am having the chipset overheats because
some idiots put its radiator near the CPU in a hope
the CPU fan will cool it, but when you have the liquid
cooling for CPU, the chipset's radiator doesn't get any
air flow from the (non-existent in this case) CPU fan.
I am going to try to make some cooling system for the
chipset from the notebook fans, but that's quite challenging.

I have 2 different MSI motherboards and one gigabyte
mobo already failed. Now its time for ASUS, which, in
the combination with the very expensive Zalman PSU
so far doesn't show the VRM failures, but I am sure it
will not last for too long either, as I suspect that the flaws
were somewhere in the AMD references that they give
to the manufacturers.
So my own experience shows this days it is nearly
impossible to build the reliable desktop system based
on AMD hw. And all you can find for am3, is dated year
2011, nothing new for 5 years! (well, MSI Krait mobo is
dated 2015, but there is nothing really new and it failed
the same way here)
A complete failure on AMD side, IMHO.
Sorry for the rant, but I've got so much fed up with AMD,
that can't resist. :) It hurted the dosemu2 development a
lot too, by draining my time and money resources in vain.

**Comment by stsp** [comment]
I also made a very interesting and expensive
experiment. Bought the quite power-hungry video
card Radeon R9 380 and brought it to our lab at
work to test it on different mobos. ALL the AMD
mobos that I tried, immediately showed the signs
of the VRM failure, but Intel boards, even with the
cheapest PSUs, were rock stable (and yes, I tried
to swap PSUs between them to get the more
consistent results, but the failures are only with
the AMD boards, nothing helps).

**Comment by andrewbird** [comment]
Okay, Desktop back in business now using quad core Intel Q6600 I had laying about.

The SDL selection and pasting works for me just fine. Great stuff!

**Comment by stsp** [comment]
> The SDL selection and pasting works for me just fine. Great stuff!

Perhaps you have noticed that this now
requires pressing Shift. I guess people will
again grumble about the compatibility with
dosemu1... :)

**Comment by andrewbird** [comment]
Mmm, no I didn't need to use shift. I just did left mouse click/drag in sdl window, switch to lxterm, middle mouse button to paste.

**Comment by stsp** [comment]
I seriously doubt you use an SDL output then!

**Comment by andrewbird** [comment]
How bizarre. Now I need to use shift. But I started dosemu in exactly the same way as before. Oh well, call it PEBKAC!
