### ISSUE TITLE
MS-DOS 7.00 / 7.10 unable to format floppy disk

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#276]
We seem to be missing some more modern disk functions. From memory, the procedure is as follows:

1/ create empty 'b.img' 1.44 disk image using 'dd'
2/ boot into MS-DOS 7.00 via boot floppy image on 'a.img'
3/ escape from installer
4/ try to 'format /s b:'
5/ see that DOS reports floppy format fail

repeat procedure with -d +dRW, see messages in boot.log from what appear to be unimplemented functions. Can provide boot.log later, if necessary.

**Comment by stsp** [comment]
Please provide the function numbers.
And maybe also the fix. :)

**Comment by stsp** [comment]
Why would you need 2 images?
Just boot from C?

**Comment by andrewbird** [comment]
Yes it would be equivalent to boot off the C drive as formatting the floppy is the only issue here. I tried to describe the issue as I remember it, and at that time I was installing from boot floppy on A:. I hope to fix it, but I'm working on #274 at the moment, then #275, hence the woolly bug report and lack of boot.log. :-)

**Comment by andrewbird** [comment]
Mmm, I'm not sure how this can happen, but Win95 (MS-DOS 7.0) is getting the drive number wrong when trying to write the directory to the floppy.
  - boot off c: format image at a:, no b: present 
~~~
INT13: ax=0301 cx=0001 dx=0001                                                  
DISK: null dp                                                                   
DISK write [h:0,s:0,t:0](1)->0x16768                                            
ERROR: Sector not found 3!                                                      
~~~

- boot off a: format image at b:
~~~
INT13: ax=0301 cx=0006 dx=0006                                                  
DISK: null dp                                                                   
DISK write [h:0,s:5,t:0](1)->0xf170                                             
ERROR: Sector not found 3!                                                      
~~~

What's really strange is that in both cases the drive had been previously accessed correctly with int13 functions before that were done for laying down format.
A couple of things that look odd to me is that dx is following the value of cx, and that the sector being written changes even though the operation should be the same in both cases.

**Comment by andrewbird** [comment]
To rule out the MS-DOS 7.0 format program I tried qemu and there it worked successfully. So it seems that it's okay.
I tried to run Turbo Debugger (TD) today but I get out of memory when trying to load format.com and neither TD286 or TD386 will work for me under dosemu, is that expected?

**Comment by stsp** [comment]
Likely not, see with dosemu1.

**Comment by andrewbird** [comment]
With Dosemu built at tag 1.5.0 TD can load format.com okay. I'm trying to bisect now, but builds in the middle are failing with messages like
~~~
./default-configure: 102: exec: ./configure: not found
autoreconf -v
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
/usr/bin/m4:aclocal.m4:350: cannot open `m4/ax_restore_flags.m4': No such file or directory
/usr/bin/m4:aclocal.m4:351: cannot open `m4/ax_save_flags.m4': No such file or directory
/usr/bin/m4:aclocal.m4:352: cannot open `m4/perl-check.m4': No such file or directory
/usr/bin/m4:aclocal.m4:353: cannot open `m4/std-gnu11.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
/usr/bin/m4:aclocal.m4:350: cannot open `m4/ax_restore_flags.m4': No such file or directory
/usr/bin/m4:aclocal.m4:351: cannot open `m4/ax_save_flags.m4': No such file or directory
/usr/bin/m4:aclocal.m4:352: cannot open `m4/perl-check.m4': No such file or directory
/usr/bin/m4:aclocal.m4:353: cannot open `m4/std-gnu11.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
autoreconf: /usr/bin/autoconf failed with exit status: 1
make: *** No rule to make target 'config.status', needed by 'default'. Stop.
~~~
Any suggestions?

**Comment by stsp** [comment]
Remove aclocal.m4

**Comment by andrewbird** [comment]
Thanks, happily bisecting now :-)

**Comment by andrewbird** [comment]
Well the bisect turned out to be a waste of time. I bisected all the way back to HEAD without a fail. So I really don't know what I was doing before to get out of memory with TD. It could be Operator error!

**Comment by andrewbird** [comment]
Even though I got TD working(v2.01), dosdebug turned out to be a better tool for this purpose. Incidentally TASM 5.0 has TD v5 included and seems to use DPMI and the TD286/TD386 versions have been dropped.
Anyway here's the last section of trace from format.com just before the write to an invalid drive(DL == 06)
```ASM
04a1:431e 5E               pop  si
dosdebug> 
dosdebug> 
system state: stopped
AX=5c00  BX=0002  CX=0846  DX=365c  SI=3654  DI=005e  SP=01dc  BP=01d2
DS=00c9  ES=00c9  FS=0000  GS=0000  FL=00123346
CS:IP=04a1:431f       SS:SP=170f:01dc

04a1:431f 5F               pop  di
dosdebug> 
dosdebug> 
system state: stopped
AX=5c00  BX=0002  CX=0846  DX=365c  SI=3654  DI=3675  SP=01de  BP=01d2
DS=00c9  ES=00c9  FS=0000  GS=0000  FL=00123346
CS:IP=04a1:4320       SS:SP=170f:01de

04a1:4320 5D               pop  bp
dosdebug> 
dosdebug> 
system state: stopped
AX=5c00  BX=0002  CX=0846  DX=365c  SI=3654  DI=3675  SP=01e0  BP=174f
DS=00c9  ES=00c9  FS=0000  GS=0000  FL=00123346
CS:IP=04a1:4321       SS:SP=170f:01e0

04a1:4321 1F               pop  ds
dosdebug> 
dosdebug> 
system state: stopped
AX=5c00  BX=0002  CX=0846  DX=365c  SI=3654  DI=3675  SP=01e2  BP=174f
DS=1352  ES=00c9  FS=0000  GS=0000  FL=00123346
CS:IP=04a1:4322       SS:SP=170f:01e2

04a1:4322 07               pop  es
dosdebug> 
dosdebug> 
system state: stopped
AX=5c00  BX=0002  CX=0846  DX=365c  SI=3654  DI=3675  SP=01e4  BP=174f
DS=1352  ES=1352  FS=0000  GS=0000  FL=00123346
CS:IP=04a1:4323       SS:SP=170f:01e4

04a1:4323 CF               iret
dosdebug> 
dosdebug> 
INT 0x13, system state: stopped
AX=0301  BX=0000  CX=0006  DX=0006  SI=0064  DI=0064  SP=08d4  BP=0005
DS=0070  ES=1bab  FS=0000  GS=0000  FL=000b3246
CS:IP=059d:1661       SS:SP=00c9:08d4

059d:1661 CD13             int  13
```
What I don't understand is what the IRET is doing there, and how register values change on return as my old TASM quick reference guide suggests only flags and stack should be altered. Any ideas?

**Comment by stsp** [comment]
> Incidentally TASM 5.0 has TD v5 included and seems to use DPMI

Does this work?

> What I don't understand is what the IRET is doing there, and how register values change

Iret can disable the trace flag and we probably
do not have special code in dosdebug to restore it.
Then your bpint triggers again, in a completely
unrelated place.

**Comment by stsp** [comment]
Note that in the past we had 'tf' for that.
Since we no longer have it, we need to write
the special code for things like iret. But its not
difficult.

**Comment by andrewbird** [comment]
Yes TD v5 seems to offer hardware breakpoints, and I believe that means protected mode. Certainly the TDMEM program that comes with it has no complaints.
~~~
C:\tasm\bin>tdmem
TDMEM  Version 1.5  Copyright (c) 1990, 1992 Borland International
 
 PSP  blks bytes owner    command line        hooked vectors
----- ---- ----- -------- ------------------- ------------------------------
0008   2   60032 config
10C0   3   10064 command                      22 2E
133A   2  576608 free
 
free  Int-15:      0k
 
DPMI version 0.9 services detected  CPU:586  32-bit programs allowed   
~~~

Regarding the trace. The 'bpint' I used got me to the previous INT 13 with no problems, correct DL value etc, after execution its return buffer was filled with boot block data (nice!). Then I used only 'ti' instructions until the IRET / and the viewed the incorrect DL value for the next INT 13.

So regarding your tf flag comment, would that mean that after IRET executed, other instructions could be done before the 'ti' stopped at the next instruction, or was that thought specific to 'bpint'?

**Comment by andrewbird** [comment]
I think you are correct about not stopping in the right place. I just ran under TD and added a breakpoint at 04a1:4321 and single stepped back from the iret to a different place...

**Comment by stsp** [comment]
Something like this should help:
```
diff --git a/src/tools/debugger/mhpdbgc.c b/src/tools/debugger/mhpdbgc.c
index 526da78..95d5ad6 100644
--- a/src/tools/debugger/mhpdbgc.c
+++ b/src/tools/debugger/mhpdbgc.c
@@ -583,13 +583,23 @@ static void mhp_trace(int argc, char * argv[])
 
       if (!in_dpmi_pm()) {
        unsigned char *csp = SEG_ADR((unsigned char *), cs, ip);
-       if (csp[0] == 0xcd) {
+       switch (csp[0]) {
+       case 0xcd:
            LWORD(eip) += 2;
            do_int(csp[1]);
            set_TF();
            mhpdbgc.stopped = 1;
            mhpdbgc.int_handled = 1;
            mhp_cmd("r0");
+           break;
+       case 0xcf:
+           LWORD(eip) += 1;
+           fake_iret();
+           set_TF();
+           mhpdbgc.stopped = 1;
+           mhpdbgc.int_handled = 1;
+           mhp_cmd("r0");
+           break;
        }
       }
    }
```

**Comment by stsp** [comment]
`mhpdbgc.int_handled = 1;` line should not be there.

**Comment by andrewbird** [comment]
Okay, thanks. Will try again.

**Comment by andrewbird** [comment]
I hacked mhp_printf to write the trace out to a log file. Here's the relevant portion of if. It seems the drive number is stored at es:[di+04] where es == 0229 and di == 0064. At line 4656 in the log it's good (1) and at line 5041 it's bad (6). I can't see the problem at the moment, but more eyes may help :-)
[format_b.txt](https://github.com/stsp/dosemu2/files/818786/format_b.txt)

**Comment by stsp** [comment]
Should I commit the iret patch?

**Comment by stsp** [comment]
If you need to find who modifies some
value, you use gdb's watchpoint and cpu_emu,

**Comment by andrewbird** [comment]
Yes the iret now seems to do the right thing so it's good to commit, thanks. Regarding the gdb how would I translate the dos memory address into a value for a watchpoint? Also I notice in dosdebug it loads the dosemu executable's memory map, what purpose does that serve?

**Comment by stsp** [comment]
> I translate the dos memory address into a value for a watchpoint?

Add `mem_base` or `lowmem_base`.

> dosemu executable's memory map, what purpose does that serve?

Who knows... In general, dosdebug uses mapfile
to decorate disasm with symbol names. And as for
dosemu.map - perhaps then it can decorate also
the dosemu bios? In either case, I don't think this
works.
