### ISSUE TITLE
Mortal Kombat 1 & 2 keyboard issue

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#277]
At least with recent git, there keyboard issues with Mortal Kombat 1 and 2. On the initial screen it is possible to press F10 to open a settings menu. This works correctly. After that it should be possible to move the cursor down in this menu. This does not work.

A demo version of Mortal Kombat 2 which has this issue can be found here:
https://www.classicdosgames.com/game/Mortal_Kombat_II.html

**Comment by stsp** [comment]
Thanks for spotting, this is a blocker.

**Comment by stsp** [comment]
Hope you can now continue testing these games. :)
