### ISSUE TITLE
windows: krnl286 doesn't work

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#287]
```
cd windows
system\krnl286
```
doesn't work.
But commit ed62bcda says it worked.
It might be a regression, but not since 1.4.0.8 at least.
Going so deep into a bisect process is exceptionally
difficult these days.
@jschwartzenberg I know you had a 32bit vm setup
for such testing. Maybe you can take a look into that
problem?

**Comment by jschwartzenberg** [comment]
I hadn't caught this question before. Is there still anything I should test? I think i still have this VM indeed.

**Comment by stsp** [comment]
No, this works now.
