### ISSUE TITLE
Prince of Persia 2 timing becomes too slow after some time (kvm)

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#290]
When I play Prince of Persia 2 with latest git and kvm, after a while the game starts to have timing issues and things go much slower than they should go. Sound effects still play at the correct speed, but are also delayed due to all events being triggered slowly.

I once had it triggered at the end of the first level and once at the end of the third level.
To reproduce I would suggest playing the first three levels. I don't know if there's a quicker reproduction path.

More information about the game: http://www.abandonia.com/en/games/51/Prince+of+Persia+2+-+The+Shadow+%2526+The+Flame.html

**Comment by stsp** [comment]
Have you tried "speed 0"?
Is this a regression?
If so - bisect would be nice.

**Comment by jschwartzenberg** [comment]
I don't know if it's a regression. What's "speed 0"?

**Comment by stsp** [comment]
> What's "speed 0"?

Command in DOS prompt.

Please see on 1.4.x if it is a regression.

**Comment by jschwartzenberg** [comment]
I just had it happen again with "speed 0". Going to the right in level 2 (into the water) seemed to trigger it. I'll try it with 1.4 now or should I also try it without kvm?

**Comment by jschwartzenberg** [comment]
Whoops, it seems I screwed up. I had fullsim enabled. I switched to vm86 now and I played the first 3 levels without issues now. I'll play further and see how it goes.

**Comment by jschwartzenberg** [comment]
Nope, the problem is still there, I had to play till the bridge in level 5 to get it to appear though.

**Comment by jschwartzenberg** [comment]
Another note, restarting the game makes it disappear.

**Comment by jschwartzenberg** [comment]
I just played and got into level 6 with 1.4. No problems at all, so it indeed seems like a regression. It's hard to reproduce though, because it's a matter of playing the game long enough to trigger it is seems.

**Comment by stsp** [comment]
I understand your concerns, but I wasn't
able to ever pass move than the first level
in prince.
Here's the small hint that may help you
with bisecting this. Create a separate
git worktree (git worktree --help) and do
the trials in that work-tree in your spare time.
This will not prevent you from working with
other work-trees on other things and can
take as much time as needed.

**Comment by jschwartzenberg** [comment]
I had an attempt at reproducing this using cheat codes. This makes it easier (even within the first level), but so far I haven't found a stable reproduction path. Just bashing some of the cheat codes for a few minutes usually triggers the bug at one point.

It would be nice if we had some way to have automatic tests which include input. Maybe the tooling that is used for these tool assisted playthroughs could work with dosemu as well.

**Comment by jschwartzenberg** [comment]
On my older notebook (Intel Core2 Duo instead of i3) this problem is very easily reproducable with kvm. With emulated I didn't manage to reproduce it (playing quite a few levels).

**Comment by stsp** [comment]
Would be nice if you can get this bisected.

**Comment by jschwartzenberg** [comment]
Yep, I'm still finding ways to reproduce this reliably. Maybe I could try going back to the first working kvm version on my older notebook and see if that one already has the problem. If not, I could bisect easily with that.

**Comment by jschwartzenberg** [comment]
Seems it was already there then, I just checked out commit 205d60f and could reproduce the problem with it.

**Comment by stsp** [comment]
OK, that's unfortunate.
Could you please record the video of how that happens?

**Comment by jschwartzenberg** [comment]
Here's a video:
http://schwart6.home.xs4all.nl/prince2-dosemu-bug.ogv

The bug is triggered here exactly at the moment the prince reaches for the ship at the end of the level. I've had it triggered much earlier before as well, sometimes even on the second screen already.

**Comment by stsp** [comment]
Ah, prince2!
Let me diagnose my mind to find out why
I was thinking of prince1... done. Here it is:
```
To reproduce I would suggest playing the first three levels.
I just played and got into level 6
```
You referred to the level by numbers, but
prince2 only vaguely has levels, and certainly
not numbered (will you count the desert after
the ship as a separate level?)

I can't reproduce this hitting the ship, but see
if it is related to sound. If you disable sound in
setup, does this still happen?

**Comment by jschwartzenberg** [comment]
Yeah the second level is very short, but internally it's just counted as a level. There's also a way to display the level number you're in.

This hitting the ship was just coincidentally the moment it's triggered when I made the video. It usually happens much earlier in the game already on my older notebook. On my newer notebook, it often happens later.

I'll try to see if I can reproduce it with the sound disabled.

**Comment by jschwartzenberg** [comment]
Switching the sound from Sound Blaster to PC Speaker indeed works. I managed to play up to level 7 with KVM on my older notebook.

**Comment by stsp** [comment]
Then please provide the -D9+S log.

**Comment by jschwartzenberg** [comment]
It happened at the same moment again this time as in the video:
[boot.log-prince2.txt](https://github.com/stsp/dosemu2/files/769619/boot.log-prince2.txt)

**Comment by stsp** [comment]
No, this is probably not about sound.
Nothing interesting in the log.
Btw any reason you use adlib for music
instead of GM?

What is the CPU load during bug?
I wonder if I should send you my copy
of prince2 as I never experienced this.

**Comment by jschwartzenberg** [comment]
Maybe there are different versions of the game. I guess it could also depend on other factors.
I usually prefer the Adlib music over the GM track. While the GM instruments are often nicer, it sounds to me like the whole compositions are often made to be played on Adlib. I also have this with Wacky Wheels for example.

**Comment by stsp** [comment]
I've just fixes the very similar symptoms in
TIM2 game. Not that it is likely to fix prince2
too, but I wonder why that bug never popped
up before...

**Comment by jschwartzenberg** [comment]
I didn't test prince2 before in my case. I just tried it with lastest git btw, the issue is still there.

**Comment by stsp** [comment]
So its only kvm, right?
And only with sound?

**Comment by jschwartzenberg** [comment]
Yes, at least only with that combination I could reproduce it.

**Comment by jschwartzenberg** [comment]
It seems the problem is the most easily reproducable in level 6. Start the game with `prince makinit level6` go to into the palace, run+jump one screen to the left and drop down. If it hasn't shown up then, crawl through the hole. It seems this level has something which triggers this issue.

I also managed to reproduce it with both the "Sound Blaster Pro" and "Sound Blaster" settings.

If that argument doesn't work, this page lists other variants for different versions:
http://popuw.com/parameters.html

Note that the game only plays sounds when it's configured to use high memory. Maybe this goes the other way around as well (it only uses high memory when sound effects are enabled).

**Comment by stsp** [comment]
But if you found that out, maybe you can
now bisect? :)

**Comment by jschwartzenberg** [comment]
Yes, I guess but obviously 1.4 didn't have kvm. Reading back I'm not 100% sure I could reproduce this without kvm, so I'll try that first.

**Comment by jschwartzenberg** [comment]
With cpu emulated it works fine. So I don't know if there's an initial kvm revision I could test it with that would less likely have this issue?

**Comment by stsp** [comment]
Probably somethng like this:
205d60f6a

**Comment by jschwartzenberg** [comment]
Just tested it with that version and it already has the problem.

**Comment by jschwartzenberg** [comment]
The new `$_cpu_vm_dpmi = "kvm"` option makes this even more easy to reproduce.

**Comment by stsp** [comment]
Could you please re-test this?

**Comment by jschwartzenberg** [comment]
Do you have a reason to believe this is fixed? I did manage to get to get once past the second level for the first time without it occurring, but then trying it again I reproduced it. It happened this time as the game transitioned to the second level. This is with  6a791138b41acec817878bd2a4ca2da34f50f66a.

**Comment by stsp** [comment]
I think prince has a bug to use iret
with a call stack frame, so it can put
junk in eflags, which sometimes
gets to TF, resulting in a slow execution.

**Comment by jschwartzenberg** [comment]
Do you think that bug would be in the sound driver?

**Comment by stsp** [comment]
Dunno.
But you can see the state with dosdebug.

**Comment by jschwartzenberg** [comment]
Ah indeed, reading back my comments, it seems I forgot a lot about this bug. It might also be the high memory part. I was thinking another sound driver might be an option if the bug would be there.

I'll have to play around with dosdebug to figure out how it works.

**Comment by stsp** [comment]
It prints registers even when you just
connect it.

**Comment by jschwartzenberg** [comment]
I get this:
```
julius@pols:~$ dosdebug 
dosdebug> 

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
system state: running
AX=1f57  BX=9ca9  CX=4651  DX=9cca  SI=0d21  DI=1024  SP=8b46  BP=8b50
DS=65bb  ES=772b  FS=0d98  GS=0cd7  FL=000a0303
CS:IP=1ea9:784b       SS:SP=3e9b:8b46

1ea9:784b 43               inc  bx
dosdebug> 
system state: stopped
AX=1f57  BX=9ca9  CX=4651  DX=9cca  SI=0d21  DI=1024  SP=8b46  BP=8b50
DS=65bb  ES=772b  FS=0d98  GS=0cd7  FL=000a0303
CS:IP=1ea9:784b       SS:SP=3e9b:8b46

1ea9:784b 43               inc  bx
```

**Comment by stsp** [comment]
When it is slow?
Yes, TF is set.

**Comment by jschwartzenberg** [comment]
Seems that I was just impatient, now it's really slow:
```
julius@pols:~/dos/games/prince2$ dosdebug
dosdebug> 

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
system state: running
AX=0016  BX=0070  CX=0002  DX=0000  SI=0007  DI=2832  SP=9144  BP=9144
DS=3e9b  ES=3e9b  FS=0d98  GS=0cd7  FL=000a0346
CS:IP=1074:00ed       SS:SP=3e9b:9144

1074:00ed 5D               pop  bp
dosdebug> 
system state: stopped
AX=0016  BX=0070  CX=0002  DX=0000  SI=0007  DI=2832  SP=9144  BP=9144
DS=3e9b  ES=3e9b  FS=0d98  GS=0cd7  FL=000a0346
CS:IP=1074:00ed       SS:SP=3e9b:9144

1074:00ed 5D               pop  bp
dosdebug> 
```

**Comment by stsp** [comment]
Try something like this:
```
diff --git a/src/base/emu-i386/do_vm86.c b/src/base/emu-i386/do_vm86.c
index f808542d9..c90ae3250 100644
--- a/src/base/emu-i386/do_vm86.c
+++ b/src/base/emu-i386/do_vm86.c
@@ -587,7 +587,9 @@ static void run_vm86(void)
        mhp_debug(DBG_PRE_VM86, 0, 0);
 #endif
 
+    clear_TF();
     _do_vm86();
+    clear_TF();
 }
 
 /* same as run_vm86(), but avoids any looping in handling GPFs */
```

**Comment by jschwartzenberg** [comment]
I just found that the game is fast again after entering `g` in dosdebug.

**Comment by stsp** [comment]
> Edit: even switching to dosdebug seems to fix it.

Yes, indeed, because it would clear TF.
I can't reproduce it though.
Try to create the `-D9+i#g` log.

**Comment by jschwartzenberg** [comment]
With or without the patch?

**Comment by stsp** [comment]
With patch see if it helps, and make the log
without one.

**Comment by jschwartzenberg** [comment]
Here's the log I pushed ctrl+alt+pagedown when it was slow:
[boot.log.gz](https://github.com/stsp/dosemu2/files/4013449/boot.log.gz)

**Comment by jschwartzenberg** [comment]
The patch seems to work, but the game now crashed dosemu after dieing in level 5 and pressing enter to continue again:
[boot.log](https://github.com/stsp/dosemu2/files/4013492/boot.log)

I played quite a while before that though. Кстати, с новым годом!!

**Comment by stsp** [comment]
Your log starts too late.
Try this patch:
```
diff --git a/src/base/emu-i386/do_vm86.c b/src/base/emu-i386/do_vm86.c
index f808542d9..e2759ed3a 100644
--- a/src/base/emu-i386/do_vm86.c
+++ b/src/base/emu-i386/do_vm86.c
@@ -494,6 +494,7 @@ static void _do_vm86(void)
        dret = mhp_debug(DBG_INTx + (VM86_ARG(retval) << 8), 1, 0);
        if (!dret)
 #endif
+if (VM86_ARG(retval) == 1) error("TF\n");
            do_int(VM86_ARG(retval));
        break;
     case VM86_TRAP:
```

Does it print something, and if so - is it
the right time when things arebecoming
slower?

**Comment by stsp** [comment]
Happy new year. :)

**Comment by jschwartzenberg** [comment]
> Does it print something, and if so - is it
> the right time when things are becoming
> slower?

No, it doesn't print anything, also when the slowness occurs. Note that the sound effects continue to play at the right speed. I'm watching the story now between level 1 and 2 very slowly. The music already finished before the first screen appeared. The sound effects are all triggered at the right moment when appropriate in the slow story.

**Comment by stsp** [comment]
Could you please try this binary patch to prince2:
```
016549  CF      CB
```

**Comment by jschwartzenberg** [comment]
That binary patch seems to solve the issue! I could play from level 1 to level 7 without encountering any problems!!

**Comment by stsp** [comment]
Thanks!

**Comment by jschwartzenberg** [comment]
Do you know why it only happens with KVM?

**Comment by jschwartzenberg** [comment]
I just found there are multiple versions of the game: https://popuw.com/download2.html

Maybe not all have this bug or some need the fix in a different spot.

**Comment by stsp** [comment]
Use this patch to test if the fix is needed:
```
diff --git a/src/base/emu-i386/do_vm86.c b/src/base/emu-i386/do_vm86.c
index f808542d9..e86c6d69c 100644
--- a/src/base/emu-i386/do_vm86.c
+++ b/src/base/emu-i386/do_vm86.c
@@ -497,6 +497,7 @@ static void _do_vm86(void)
            do_int(VM86_ARG(retval));
        break;
     case VM86_TRAP:
+if (VM86_ARG(retval) == 1) { error("TF\n"); leavedos(5); }
 #ifdef USE_MHPDBG
        if(!mhp_debug(DBG_TRAP + (VM86_ARG(retval) << 8), 0, 0))
 #endif
```

It will terminate dosemu as soon as TF is seen.
Which happens very quickly, definitely within the
first level. It never leads for me to the slowdown
you mentioned (or maybe I should play through
the entire game for this to happen), but my theory
that this is related, is now proven.

It happens everywhere, but with cpu-emu the
slowdown is not that big - just all instructions
are intermixed with unneeded int/irets from int1.
In kvm however this means exit to dosemu for
every guest instruction, which will definitely be
unplayable. So my fix should slightly speed it up
everywhere, even on real CPU.

**Comment by jschwartzenberg** [comment]
It seems this bug is not present in version 1.1 of the game either. I'm still playing it now, all smooth so far till level 5.

**Comment by stsp** [comment]
Try with the patch.
It detects the problem much earlier than
when the slowdown happens.

**Comment by stsp** [comment]
(i mean dosemu2 test patch above)

**Comment by stsp** [comment]
How to tell the version?

**Comment by jschwartzenberg** [comment]
Don't know, just grab the different versions of the page above :)

**Comment by stsp** [comment]
Yes, v11 is indeed unaffected.

**Comment by jschwartzenberg** [comment]
I just finished level 3 with the IR version with the above patch. It did trigger the line with version 1.0. I guess the IR version is also not affected.

**Comment by stsp** [comment]
The check line or real slowdown?

**Comment by jschwartzenberg** [comment]
At least the check line.

**Comment by stsp** [comment]
OK, added the update suggestion.

**Comment by jschwartzenberg** [comment]
It seems I had been testing with the leaked IR version. Possibly the needed binary patch is different for v1.0. alt+v shows the version of the game.
