### ISSUE TITLE
Regression: terminal mode

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#291]
My test suite uses the python pexpect module to drive the terminal based tests. The following commit 9974a908cb7f9899bc510ab95a286f39a00d9fa4 seems to have stopped them working according to a git bisect. That said I don't understand why, as the commit seems to be focussed on sdl, and I'm using Dosemu in terminal mode.

~~~
ajb@polly:/clients/common/dosemu2.git$ git bisect good
9974a908cb7f9899bc510ab95a286f39a00d9fa4 is the first bad commit
commit 9974a908cb7f9899bc510ab95a286f39a00d9fa4
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Mon Jan 23 02:24:18 2017 +0300

    sdl: add probe kbd method to avoid confusion with tty keyb
    
    Without the probe method for sdl, our kbd code was also loading
    the tty driver, so both kbd drivers worked together stealing the
    input from tty (from gdb for instance).

:040000 040000 b68982d92c157e0c9856f151fc67e6619b7b988e 6d61a3328359bbbe83bf12cabac9daa8c7c8d39e M	src
~~~

I've attached a cut down version of the test suite with just a single test that shows the problem

Method
1/ build dosemu - no need to install
2/ make sure you don't have ~/.dosemu/drives etc, as it currently overrides --Fimagedir
3/ untar testcase.tar in build directory
4/ make sure you have python pexpect module and nose installed
5/ run 'nosetests -v test/test_bootos.py:FRDOS110TestCase.test_floppy_vfs'

Test will show 'Timeout' after the offending commit, but 'ok' before it.
[testcase.tar.zip](https://github.com/stsp/dosemu2/files/737495/testcase.tar.zip)

**Comment by stsp** [comment]
In your runDosemu() I don't see you using
'-td' for a terminal mode. What am I missing?

**Comment by andrewbird** [comment]
Doing it via option -I video{none}, but effect is the same if I replace that with -td.

**Comment by stsp** [comment]
In video.c:112 could you please try:
- if (config.X) return 0;
+ if (config.X || config.term) return 0;

**Comment by andrewbird** [comment]
Mmm, I made a mistake regarding the retest with '-td', sorry! it does work even without your video.c tweak. So the only regression is that '-I  video{none}' is no longer equivalent to '-td'. I'm not sure if it's best to fix or remove it?

**Comment by stsp** [comment]
> I'm not sure if it's best to fix or remove it?

Yes, I'll be all for removing the -I support completely
(and then also entire global.conf).

**Comment by stsp** [comment]
Btw, I remember you wanted to get rid
of global.conf too, but the conclusion was
that its too difficult. In fact it is not.
You can take any option you like, remove
it from global.conf and implement it in a new
parser that you can think of. Most options
are simple and can be taken one by one.
Some "hard" options (that do a lot of shell
interaction, or with loops) can be considered
later or left in global.conf forever.
I think with such technique we can get a
very quick start on that task.

**Comment by stsp** [comment]
I mean even if you implement a parser for
just one option, that would still be valuable
as it will allow in the future to add the new
options there instead of in global.conf. Of
course it should be compelling, i.e. adding
a new option there should be trivial.

**Comment by andrewbird** [comment]
Thanks, it's fixed now with -I video{none}. I have now switched the test suite to use -td anyway.

I doubt I have any time in the near future for global.conf elimination. From my POV scrapping -I option might be a good way to mark it deprecated though.
