### ISSUE TITLE
RFE: Show $_cpu_emu and $_cpu_vm settings by default in the title bar

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#299]
It would be nice if the $_cpu_emu and $_cpu_vm settings would be displayed in the title bar by default (or at least have a feature for that which can be quickly turned on), because:
1. They affect compatibility significantly
1. They affect performance significantly
1. They are cool features that DOSEMU2 should prominently advertise
1. They are very relevant for bug reports

**Comment by stsp** [comment]
> They affect compatibility significantly

Why?

> They are cool features that DOSEMU2 should prominently advertise

Why?

> They are very relevant for bug reports

They can be found in the log.

I wonder why is this needed.

**Comment by jschwartzenberg** [comment]
>> They affect compatibility significantly

> Why?

Especially the sim variants are not working so well yet. Also sometimes you request to test on 32-bit with vm86. Isn't it nice to see whether vm86/kvm/sim is used when trying things?

>> They are cool features that DOSEMU2 should prominently advertise

> Why?

To show off the advantages over DOSBox ;)

**Comment by stsp** [comment]
> Especially the sim variants are not working so well yet.

Please open the tickets then.
I can boot windows with sim, and overall I've
got an impression it works better than jit.

> To show off the advantages over DOSBox ;)

No one should change the default value normally.
This is just a debugging stuff, so it shouldn't be
that visible.

**Comment by stsp** [comment]
(but not fullsim of course)

**Comment by jschwartzenberg** [comment]
The default doesn't say much. That can be either vm86 on 32-bit and kvm on systems supporting that, so not everybody will have the same default.

**Comment by stsp** [comment]
But vm86 and kvm are roughly similar in
performance. I think the defaults should just
be the best we have and no one should be
changing them. User certainly doesn't need
to know if he is using kvm or vm86 as he
doesn't even know what does this mean.
