### ISSUE TITLE
Direct Parallel Access

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#3]
Hi,

I have a Datamax printer which I use on LPT1 or under Linux lp0. The printer doesn't need a driver, you just send the raw data, the files include the printer control signs.
However I can't get it to work under CUPS / Ubuntu 14.04.1 x64 unlike other printers. I tried it with raw mode in cups, ECP/EPP/SPP in Bios, never printed. I then tried a LPT to USB cable in ECP mode and it showed up the correct printername in CUPS. I may print one label from dosemu but no more. No error message shown and cups says that all tasks have been completed but it is also saying "Sending data to printer".

I have to reboot in order to print another label.

Now I want to give dosemu direct access to the parallel port and print via original lpt port, maybe that helps. In dosemu.conf I changed $_lpt1 = "" and added
$_ports = $_ports, " device /dev/lp0 range 0x378 0x37a"
and started sudo dosemu -s
## When copying the file to LPT1 it states "Error reading from device LPT1: write fault".

In terminal I tried to copy the file to lp0, after setting chmod 666 /dev/lp0 I did cat file.txt > /dev/lp0 but nothing happens.

**Comment by haenschen** [comment]
Okay I rmmoded lp, parport_pc, parport. ppdev modules. I am not t
https://github.com/stsprying to print smth but I am trying to use a dongle. I set $_lpt1="direct". I set $_ports = "device /dev/null range 0x378 0x37a". I ran dosemu -s. Dongle doesnt work but no errors in terminal either. 

[boot.log.zip](https://github.com/stsp/dosemu2/files/76276/boot.log.zip)

**Comment by stsp** [comment]
Please edit your comment, it refers to non-existing links.

**Comment by stsp** [comment]
-D9+cT log would be needed.

**Comment by haenschen** [comment]
Ok try this [boot.log.zip](https://github.com/stsp/dosemu2/files/76284/boot.log.zip)

**Comment by stsp** [comment]
-D9+ciT please

**Comment by haenschen** [comment]
[boot.log.zip](https://github.com/stsp/dosemu2/files/76312/boot.log.zip)

**Comment by stsp** [comment]
Interesting, we have

PORT: trying to give fast access to ports [0x0378-0x037a]
nPORT: set_ioperm [378:3:1] returns 0

... and yet all the I/O is traced.
Please try $_cpu_vm="vm86"
and add the -D9+cipT log.

**Comment by haenschen** [comment]
> Please try $_cpu_vm="vm86"

Do I need to install a 32bit Ubuntu?

**Comment by stsp** [comment]
Well, that would be ideal. So far I don't know
if ioperm works with KVM. Bart, can you help?
Of try
$_cpu_vm="emulated"
$_cpu_emu="vm86"
That would be an interesting test too.

**Comment by haenschen** [comment]
This is with 
> $_cpu_vm="emulated"
> $_cpu_emu="vm86"
[boot.log.zip](https://github.com/stsp/dosemu2/files/76326/boot.log.zip)

**Comment by stsp** [comment]
Please re-try the log with latest devel.

**Comment by haenschen** [comment]
now dosemu crashed when accessing the dongle check.
[boot.log.zip](https://github.com/stsp/dosemu2/files/76343/boot.log.zip)
```
ERROR: unexpected CPU exception 0x0d err=0x00000000 cr2=410ad031 while in vm86 (DOS)
Program=do_vm86.c, Line=158
EIP: 00d1:0000108a ESP: 35e8:00002074  VFLAGS(b): 00011 00110000 01000110
EAX: 02001600 EBX: 00000000 ECX: 0000000d EDX: 00000001 VFLAGS(h): 00033046
ESI: 000000a5 EDI: 00000084 EBP: 0000209e DS: 35e8 ES: 35e8 FS: 1297 GS: 0296
FLAGS: PF ZF IF RF VM  IOPL: 3
STACK: 27 47 e8 35 e8 35 9e 20 14 00 -> 13 0a 6e 20 e8 35 06 07 e8 35 
OPS  : 00 01 5b 07 cb cf e8 7f 00 cb -> e8 7b 00 ea 78 14 ff ff e8 73 
	e87b00              00d1:108a call 1108 ($+7b)

**Comment by stsp** [comment]
Seems like you'll need to test on 32bit system,
is that possible?

**Comment by haenschen** [comment]
Ok, on the 32bit system make fails with

``` 
cpu.c:227:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   REG(eflags) = 0;
   ^
cpu.c: In function ‘cpu_setup’:
cpu.c:338:17: error: ‘SYS_vm86old’ undeclared (first use in this function)
     if (syscall(SYS_vm86old, (void *)VM86_PLUS_INSTALL_CHECK) != -1 ||
                 ^
cpu.c:338:17: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [cpu.o] Fehler 1
make[2]: Verzeichnis »/home/pa/dosemu/src/emu-i386« wird verlassen
make[1]: *** [emu-i386] Fehler 2
make[1]: Verzeichnis »/home/pa/dosemu/src« wird verlassen
make: *** [default] Fehler 2
```

Did I forget something?

**Comment by stsp** [comment]
No, its me... :(
in file include/emu.h could you please try
adding
#include <syscall.h>
and see if that helps?

**Comment by stsp** [comment]
Arrr

**Comment by stsp** [comment]
include syscall h

**Comment by stsp** [comment]
Damned github. :)
Is it clear what I wrote above?

**Comment by haenschen** [comment]
Well with that change it compiles but I can't get to the test as my program now crashes upon startup, just a blue screen without text no matter what options for $_cpu_vm are set or if I use dosemu -S. Maybe I made some mistake, I'll recheck tomorrow.

**Comment by haenschen** [comment]
[boot.log.zip](https://github.com/stsp/dosemu2/files/76769/boot.log.zip)

I hope I didn't forget something in config. This is from 32 bit but dongle still doesn't work.. :(

**Comment by stsp** [comment]
Are you sure your dongle works exactly on that
machine? The parallel port type in bios setup should
be set to SPP.

**Comment by haenschen** [comment]
I'll doublecheck tomorrow.

**Comment by stsp** [comment]
Oh, and please also fill in the separate report
about the 64bit regression you have after I added
the patch 717508f1

**Comment by haenschen** [comment]
Hi,

sorry for the long delay but I had trouble installing DOS on a PC with SSD and no floppy drive lol...
However I got it to work and I can confirm that the parallel port works and the software too under pure DOS - with dongle I may use it, without it won't let me.

What can I do now?

**Comment by stsp** [comment]
I am afraid you'd need a parallel port logger to
troubleshoot this. If you can get one, you'll need
to log your DOS session and see if dosemu session
produces any data at all, and how similar is it to the
one of the DOS session. You can also get some basic
idea of that with an oscilloscope.
Of course there are other ways, as usual. :)
But if you want me to reproduce this, there are the
additional complications about transferring the
dongle etc.

**Comment by stsp** [comment]
Does dosbox work?

**Comment by haenschen** [comment]
On Ubuntu or Windows or doesnt matter?

**Comment by stsp** [comment]
Try everything. :)

**Comment by stsp** [comment]
> now dosemu crashed when accessing the dongle check.

This is probably fixed now by ac3f59b0f.

**Comment by mcericdos** [comment]
Probably? Can the original reporter test it?

**Comment by haenschen** [comment]
At the earliest in one week and I need to set everything up again. What logs do you need? 32bit Ubuntu or is 64bit okay?
I dropped following this as Stas pointed out a parallel logger would've been needed.

**Comment by stsp** [comment]
But you have reported a new crash https://github.com/stsp/dosemu2/issues/3#issuecomment-168414248
and a couple of other regressions.
They definitely do not require any logger.
