### ISSUE TITLE
Order of file- and directorynames

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#30]
When using /dir to display contents there is no alphabetical order of files and directories. FreeDos usually shows directories first and then files, both in alphabetical order.

![dir](https://cloud.githubusercontent.com/assets/9266844/7542949/149f569e-f5c1-11e4-924a-b53e2a28c1bc.png)

One can force the "correct" order by using *dir /o*. A workaround is to include this in autoexec.bat via 
**SET DIRCMD=/o**

This doesnt work for applications which list contents / directories though.
Tested on Ubuntu x64.

**Comment by stsp** [comment]
> This doesnt work for applications which list contents / directories though.

I don't understand the sentence.
What applications do not work?
Here's the description of freedos dir:
http://help.fdos.org/en/hhstndrd/command/dir.htm
It says that
dir /O:a
should do the alphabetical order.

**Comment by haenschen** [comment]
I want directories first so I use dir /O:g while :g is standard for dir /o. :g sorts alphabetically too. However it seems like my dir version doesnt support "dir /O:a" anyway as it says "Ill-formed option: 'a'"

Despite having SET DIRCMD=/o in my autoexec.bat which results in a correct listing when using "dir" in my accounting software I get the old order.

**Comment by stsp** [comment]
I guess your accounting software doesn't
use "dir". It is uncommon for dos software
to use external utilities. So no wonder DIRCMD
didn't help.

**Comment by haenschen** [comment]
Yes, that was what I expected. However in freedos and ms-dos the order is correct

**Comment by stsp** [comment]
What do you mean?
This whole ticket is about freedos.
So is it correct under freedos, or not?

**Comment by haenschen** [comment]
Yes it is correct under freedos (for example in vmware) but not in dosemu. I also tried MS-DOS in dosemu, still wrong order.

**Comment by stsp** [comment]
You can't compare with vmware.
To simulate the situation a bit closer to
vmware's, you can do
lredir del c:

After that, dosemu will _probably_ sort the
files for you on drive c: the way vmware does,
but no promises.

**Comment by haenschen** [comment]
Okay here are the results from my vmware ubuntu machine with dosemu. Test from real pc following.
![dir1](https://cloud.githubusercontent.com/assets/9266844/8533248/17bf236c-2434-11e5-9a54-64972e16cb08.PNG)
![dir2](https://cloud.githubusercontent.com/assets/9266844/8533249/17c1d85a-2434-11e5-8a54-4838213ae2cf.PNG)

**Comment by stsp** [comment]
I don't see you doing
lredir del c:
as I said above.

**Comment by haenschen** [comment]
In the second picture I did lredir del C: ... lredir del c: results in the same order as C:...

**Comment by stsp** [comment]
Ah, indeed, I see.
Why are you saying it's the same order as without del?

**Comment by haenschen** [comment]
I thought you ment there is a difference between lredir del c: and lredir del C: (capital C:)

**Comment by stsp** [comment]
No, I simply missed the fact that you did it
on the second pic... where the ordering is
better, right?

**Comment by haenschen** [comment]
Yes, it is indeed, straight alphabetically except the system files (?).

**Comment by stsp** [comment]
http://blogs.msdn.com/b/oldnewthing/archive/2014/03/04/10504812.aspx

**Comment by haenschen** [comment]
Ah I see.
Actually this fixes the order in the program too.
So what did I change by deleting that redirection? I figured out that it doesn't sync my file changes to ~/.dosemu/drive_c anymore but if I start dosemu and delete the redirection afterwards I still have all files up until that moment. But I guess you already knew that, so what's next?

**Comment by stsp** [comment]
What did you change is to get a slow and
read-only FS, although by chance - partially
alpha-ordered (modulo system files).

The next is likely to close this ticket.
Any other ideas?

**Comment by haenschen** [comment]
How to get a writeable alphabetical ordered fs? :)

**Comment by stsp** [comment]
You need to ask in freedos list - maybe there
is some dos program that will change the file
ordering transparently.
If not - it can be written. ;)
