### ISSUE TITLE
Can't quit win3x anymore

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#306]
This appears to be a recent regression. I can't quit Windows anymore. It doesn't seem to matter whether Windows runs in standard or enhanced mode. Also happens with both emulated and kvm.

**Comment by stsp** [comment]
Can't reproduce.
Could you please bisect?

**Comment by jschwartzenberg** [comment]
Strange, I can't reproduce this anymore either.

**Comment by stsp** [comment]
Should be fixed by 5424865.
DPMI was very unstable.
Hmm, how do the problems like this go
unnoticed for very long. :(
Likely 609335fd made it more visible.

**Comment by jschwartzenberg** [comment]
Nice catch! I should probably redo all my testing with win31 soon.

**Comment by stsp** [comment]
Only if you had a random hard lock-ups
of entire dosemu.
