### ISSUE TITLE
Foxpro hangs quickly

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#309]
I shift mark some text in dosemu and middle click paste into medit. When pasting text from a plain DOS prompt the paste works every time. When pasting from a Foxpro screen I must middle click several times for the paste to work.

This is on version dosemu2-git-2.0pre6.1.dev.127.g2db8aaea.

I tried moving to versions dosemu2-git-2.0pre6.1.dev.272.gd1a13d77 and dosemu2-git-2.0pre6.1.dev.287.ga616cf6f but these lock up within seconds in Foxpro.

Typical launch session
````
% ps -ef | ...
/bin/sh /usr/bin/dosemu -X
/usr/bin/dosemu.bin -X
vde_switch -s /tmp/filew35WLy
sh -c slirpvde -s /tmp/filew35WLy --dhcp 2>&1
slirpvde -s /tmp/filew35WLy --dhcp
````

**Comment by stsp** [comment]
Copy/paste is implemented for SDL in 00349ad65.
You use -X but it is a fall-back option and is not
maintained currently.

**Comment by severach** [comment]
I started using -X because automatic X detection disappeared a while ago. dosemu would crash out on startup without -X. X detection works again so I can stop using it if you say it's broken.

**Comment by stsp** [comment]
What kind of "automatic X detection" disappeared a while ago?
Since when would dosemu crash on startup?

**Comment by severach** [comment]
I don't know what it's called. All I know is that for years, when you launch dosemu from an xTerm, dosemu knows to launch the X-Window variant of itself, complete with the extra X Alt and FN keyboard support I need. For several months dosemu2 would crash on start without -X. Using -X restored expected functionality.

It's all fixed now. dosemu2 launches the X-Window as it should without -X. I used -X for so long that it has become a habit.

**Comment by severach** [comment]
Launching an X-Window without -X works fine.

With or without -X, Foxpro locks up in seconds when used with the two later versions above: 272 and 287. Foxpro is running fine in 127.

**Comment by severach** [comment]
This appears to work. Pasting text from Foxpro works every time and Foxpro hasn't locked up yet.
