### ISSUE TITLE
Build release Pre2 on Wheezy

### ISSUE THREAD

**Issue by kalpha2** [stsp/dosemu2#31]
apologies if this is too similar to #29 but looking at that hasn't helped me and wasn't sure how common the denominators are.
If I download the release Pre2 and try to make I get
make: *** No rile to make target 'config-status' ....

If I run ./default-configure 
I get a repeated number of 
./mkpluginhooks: line 53: ./configure: No such file or directory
for the following
libao, alsa, term, X, sdl, fluidsynth

Unless it is a min version required thing, bit surprised about X, have got most if not all X dev packages installed, and I also got libsdl2-dev from backports.

Any suggestions on how to confirm what packages (specific name) required in order to build on Wheezy, or known issues?

**Comment by runderwo** [comment]
Have you run autogen.sh?

**Comment by kalpha2** [comment]
ah, no, but now if I do, I get


./autogen.sh: 5: ./autogen.sh: autoreconf: not found
Failure!

   -  -  -

**Comment by haenschen** [comment]
Instell autoconf,
sudo apt-get install autoconf

**Comment by kalpha2** [comment]
aha, thankyou.

autogen runs,
a number of warnings about things being obsolete, and run auto update
AC_LANG_C, AC_TRY_COMPILE, AC_LANG_RESTORE, AC_LANG_SAVE

then says to run ./default-configure
which looks much better now.

Though (as #29 found) SDL2 is only v2.0.0 in Wheezy backports, and the 
configure wants v2.0.2.

I can live without SDL for now.

make succeeds

Next naive question.

Can I use the new build, without doing a make install ?
(like different prefixes in wine)

I try to invoke from the bin folder, and shows that it is DOSEMU2 
2.0pre2 but falls over with
EMS driver version mismatch, disabling
Please update your ems.sys from the latest dosemu package
Press any key!

(but is frozen)

   -  -  -

**Comment by runderwo** [comment]
Yes, use --Flibdir /path/to/dos

**Comment by kalpha2** [comment]
so if I create a new folder "mydos"
copy dosemu-freedos-bin.tgz into that folder
and then  tar -zxf dosemu-freedos-bin.tgz

is that all I need to do, or do I need to copy or symlink files from my 
dosemu2 tree?

is my cmdline
./dosemu --Flibdir ~/mydos

giving up for now, hopefully with fresh start and coffee will be clearer 
in the morning:)

many thanks
   -    -

**Comment by kalpha2** [comment]
Ok, thankyou for all the help, the issue raised about building on Wheezy 
was resolved for my needs, caveat on the SDL2 version problem in Wheezy 
backports making unavailable.

I mainly wanted to see if printing to lpt1 (direct or via CUPS/LPR) had 
improved... my results were actually worse so going to have to go serial 
printing only route for now.

I never got the --Flibdir though, which might have affected my testing 
above as I resorted to letting dosemu2 pre2 pick up the .dosemu settings 
I use for debian package.

whenever I tried --Flibdir, I always got
"EMS driver version mismatch, disabling
Please update your ems.sys from the latest dosemu package"
and in the console
"ERROR: EMS driver version mismatch: got 3, expected 5, disabling"
I tried copying the ems.sys (that I checked says is version 5) into 
every (recursive) folder within my test folder I was pointing --Flibdir 
at and still got this error.

and then I hit
"Error 35 (network name not found)
while redirecting drive Z:  to LINUX\FS\Bad or missing Command 
Interpreter: z:\command.com /e:1024 /p
Enter the full shell command line:"
Which is why I reverted to no --Flibdir for my testing
   -  -  -  -
