### ISSUE TITLE
GEOS broke

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#313]
... with this commit:
8b79fed63
if himem.sys is not loaded.
But I am guessing this is some pre-existing
bug, not a regression...

**Comment by bolle732** [comment]
I've used always 'ems.sys' for XMS. It still runs on f0f985a32d42c2fcd47c3cbfb804fb58e1525442.

But it seems, that UMBs aren't working at the moment. Starting only FreeDOS prints unavailable and checking with 'mem /p /c' shows no UMB.

In the 'boot.log' I can see:
```
CONF: reserving 32Kb at 0xB0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 196Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
```
So, something has changed not only for XMS...

**Comment by stsp** [comment]
Thanks for the tip!
Indeed I can see the difference with plain `mem`.
That would simplify the task of fixing this a lot.

**Comment by bolle732** [comment]
Should we close this issue and reopen another one regarding UMBs ?

**Comment by stsp** [comment]
So far geos does not work for me, and I
do not have enough evidence it will after the
UMB bug is fixed. This is just a hypothesis.
You can of course open an UMB ticket at any
time, too.

**Comment by bolle732** [comment]
Regarding UMB, this should be fixed independently. I'll open an issue for it.

Don't know what broke your version of PC/GEOS. But here, it still runs happy with the current devel...

What happens exactly ? Could you post the "geos.ini" and "geos.log" so I can revise them ?

**Comment by stsp** [comment]
This has indeed fixed itself by the umb fix.
You were absolutely right.
