### ISSUE TITLE
Better Resize, More fonts, and 132x60 with mouse

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#316]
Can we get:

* Better resize. Resize should only allow sizes that are integer multiples of the font. The interpolation for adding a random number of pixels to the standard window size makes the font unreadable and I must close the window to get the original size back.

* Larger fonts, more fonts, hopefully scalable fonts.

* Some sort of clicky menu where fonts can be selected. I can pick a font from a bat file if that's the only way. Any font picker should not only pick the font, but the Width and Height integer multiples.

* 132x60 for Foxpro with proper mouse support and a better font. 132x60 support has improved a lot from when I last tried. The font needs to be taller. The mouse driver does not track correctly. I suspect it's tracking based on an 80 column screen.

**Comment by stsp** [comment]
> Resize should only allow sizes that are integer multiples of the font.

Try $_X_fixed_aspect

> Larger fonts, more fonts, hopefully scalable fonts.

Yeah, someone have to look into SDL_ttf.

> Some sort of clicky menu where fonts can be selected.

No, we don't have GUI. From bat file is more
feasible, and is actually already there in xmode.com.

> The mouse driver does not track correctly.

Then you can open a bug report for that.

**Comment by andrewbird** [comment]
I stumbled across this beautiful scalable DOS like font
https://int10h.org/blog/2018/05/flexi-ibm-vga-scalable-truetype-font/
Is it possible to use this in SDL mode? Would it have any benefit for resized windows?

**Comment by stsp** [comment]
We currently don't use SDL_ttf.
It would be exceptionally cool to have that
implemented, its just not there.
See #18
