### ISSUE TITLE
All DOS commands stopped working

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#318]
From pre6.1.dev.327.g48f370f1 to pre6.1.dev.330.g4c2304a4 all DOS commands have stopped working. I can't tell what all has stopped working because exitemu and lredir2 are no longer functional.

On startup.
````
MKDIR failed for 'c:\tmp'.
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Batchfile 'C:\AUTOEXEC.BAT' not found.
C:\>
````

Commands in CONFIG.SYS do work. Internal COMMAND.COM commands work like CD and DIR. I can change drives. Even when I can see the file in the current folder, it won't run.

**Comment by andrewbird** [comment]
I think some more info is required:
Which flavour and version of DOS are you using?
How do the commands fail - crash, error message, hang etc?
Is it just Dosemu provided DOS commands(exitemu/lredir2) or all DOS external commands?
What's in your dosemu.conf?
What does the boot.log show?

**Comment by severach** [comment]
Freedos 1.1 as part of an [Arch Linux](https://aur.archlinux.org/packages/dosemu2-git/) package.
The commands do nothing at all. No message or error is displayed. Just another `C>\` prompt. I have lredir2 in `CONFIG.SYS` and it runs there. Once `COMMAND.COM` starts, nothing.

Without lredir2 I can't test much. I use it in AUTOEXEC.BAT to mount the main drive. Still I can go around to what is available and all commands other than internal produce nothing.
````
C:\>command.com
C:\>set
PATH=z:\bin;z:\gnu;z:\dosemu;D:\NC4;C:\UTIL;D:\UTIL
COMSPEC=Z:\COMMAND.COM
HELPPATH=z:\help
TEMP=c:\tmp
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
PROMPT=$P$G
C:\>lredir2
C:\>exitemu
C:\>Z:
Z:\>cd dosemu
Z:\dosemu>dir exitemu.*
 Volume in drive Z is emu/drive_z
 
 Directory of Z:\DOSEMU
 
EXITEMU  COM           313  03-03-17  2:28p
         1 file(s)            313 bytes
         0 dir(s)     27,678 Mega bytes free
Z:\dosemu>exitemu
Z:\dosemu>
````
`dosemu.conf` is unchanged from the original.
The bootlog shows no significant differences between the 327 and 330 startup. The version changes and some memory sizes change slightly.

**Comment by andrewbird** [comment]
Since the commands you mention not working are Dosemu supplied commands rather than FreeDOS external ones, I wonder if they were updated in your Z: drive when you rebuilt with latest HEAD, as they have to match the running dosemu version?
If you run a command from the z:\gnu directory does that work?

**Comment by stsp** [comment]
> have to match the running dosemu version?

Commands have not recently changed.
I can't reproduce this.
Could you please identify the particular
commit? What freecom version?

**Comment by severach** [comment]
Dosemu will let me have anything I want as C: but won't let me move the system drive D: to Z: using symlinks. I move the system drive to Z: so I can put my D: in place. Z: is always current as of the package.
````
FDCONFIG.SYS
install=d:\dosemu\lredir2.com z: linux\fs\${DOSEMU_LIB_DIR}\drive_z ro
shellhigh=z:\command.com /e:1024 /p
````
````
AUTOEXEC.BAT
path z:\bin;z:\gnu;z:\dosemu
lredir del d: > nul
lredir2 d: linux\fs\home\chris\d
````

All commands failed at once. There's nothing wrong with the commands. To eliminate any problems from my drive layout, I renamed my ~/.dosemu and let the system create a new one. This has increased the number of commands that I can run from the command line from 0 to 1/2.

48f370f1 works.
````
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre6.1-dev-20170301-327-g48f370f1
C:\>lredir2
Current Drive Redirections:
C: = LINUX\FS\home\chris\.dosemu\drives\c\ attrib = READ/WRITE
D: = LINUX\FS\home\chris\.dosemu\drives\d\ attrib = READ/WRITE
E: = LINUX\FS\usr\share\dosemu\dosemu2-cmds-0.1\ attrib = READ/WRITE
C:\>lredir2
Current Drive Redirections:
C: = LINUX\FS\home\chris\.dosemu\drives\c\ attrib = READ/WRITE
D: = LINUX\FS\home\chris\.dosemu\drives\d\ attrib = READ/WRITE
E: = LINUX\FS\usr\share\dosemu\dosemu2-cmds-0.1\ attrib = READ/WRITE
C:\>
````
The very next commit 56261bf5 only works for the very first hand typed command. Since clearly drives are mapped and lredir2 won't report them even the little that does work, doesn't!
````
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre6.1-dev-20170303-328-g56261bf5
C:\>lredir2
No drives are currently redirected to Linux.
C:\>lredir2
C:\>D:
D:\>cd gnu
D:\gnu>dir
 Volume in drive D is mu/drives/d
 Directory of D:\GNU
 
.                    <DIR>  03-03-17  5:35p
..                   <DIR>  03-03-17  5:35p
HEAD     EXE        16,572  09-19-90 12:43p
CAT      EXE        17,868  09-19-90 12:32p
GREP     EXE        27,138  09-24-90 12:42a
RM       EXE        19,820  09-22-90  9:50p
TAIL     EXE        20,188  09-19-90 12:51p
MV       EXE        23,100  09-19-90 12:46p
LS       EXE        27,756  09-19-90 12:44p
CUT      EXE        17,948  09-19-90 12:38p
TAC      EXE        37,644  09-19-90 12:50p
CP       EXE        26,780  09-19-90 12:38p
CMP      EXE        20,028  09-19-90 12:35p
        11 file(s)        254,842 bytes
         2 dir(s)     27,678 Mega bytes free
D:\gnu>head
D:\gnu>cat
D:\gnu>grep
D:\gnu>
````

**Comment by stsp** [comment]
Should now be fixed.

**Comment by severach** [comment]
The commands are working again.
