### ISSUE TITLE
MT-32 on IRQ2 breaks packet driver RX callback

### ISSUE THREAD

**Issue by jharrison022** [stsp/dosemu2#325]
This seems to be an issue with the handling of the 8259s.  Set --

$_midi_synth = "mt32"
$_mpu_irq = "2"

...And then enable anything that uses the packet driver.  The RX callback function registered with the packet driver is never reached.

If you set the mpu_irq to something other than 2, the packet driver works, but this will obviously break games.

**Comment by stsp** [comment]
No, can't reproduce this.
Packet driver works perfectly.
But the fact that without setting `$_mpu_irq = (2)`
you "obviously" break games, is a
bug that should now be fixed.
Please comment out $_mpu_irq.
Btw setting it to `"2"` is wrong, the
correct syntax would be eg `(2)`

**Comment by stsp** [comment]
Actually, there was no any bug at all it seems.
The wrong syntax is the only problem I can think of.

**Comment by stsp** [comment]
If the problem persists, please attach the
-D9+SPr log.

**Comment by stsp** [comment]
> The configuration file doesn't accept $_midi_synth = (mt32), but it accepts $_midi_synth = "mt32".

I didn't say you should use `$_midi_synth = (mt32)`.
I said you should use `$_mpu_irq = (2)` for the correct
syntax, but you shouldn't do even that. You should
just keep it commented out, and if this produce any
problems, then attach the log file.
