### ISSUE TITLE
make: git-rev.sh Bad substitution

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#326]
I've not noticed this before, but appears with current devel

~~~
ajb@polly:/clients/common/dosemu2.git$ make
make[1]: Entering directory '/clients/common/dosemu2.git/src'
../git-rev.sh: 5: ../git-rev.sh: Bad substitution
echo "Updating version.h"; \
echo "#ifndef	VERSION_H" > include/version.h; \
echo "#define	VERSION_H" >> include/version.h; \
echo "#define	VERSTR	\"2.0pre6.1-dev-20170307-355-g6fb056f8\"" >> include/version.h; \
echo "#define	VERSION_NUM	2" >> include/version.h; \
echo "#define	SUBLEVEL	0" >> include/version.h; \
echo "#define	PATCHLEVEL1	\"pre6\"" >> include/version.h; \
echo "#define	REVISION	3073" >> include/version.h; \
echo "#define	VERDATE \"2017-03-07\"" >> include/version.h; \
echo "#endif /* VERSION_H */" >> include/version.h; \

Updating version.h
echo '#define  ALTERNATE_ETC      "/etc/dosemu"' > include/confpath.h
echo '#define  DOSEMUPLUGINDIR "/usr/local/lib/dosemu"' >> include/confpath.h
echo '#define  DOSEMULIB_DEFAULT  "/usr/local/share/dosemu"' >> include/confpath.h
echo '#define  DOSEMUHDIMAGE_DEFAULT "/var/lib/dosemu"' >> include/confpath.h
echo '#define  SYSTEM_XFONTS_PATH "/usr/local/share/dosemu/Xfonts"' >> include/confpath.h
~~~

**Comment by severach** [comment]
Related to #324 ?
I'm not getting this. I build with a package and the package always builds with a clean copy.

**Comment by stsp** [comment]
Yes, its related, but it is because of the dash.
I am seriously considering to add bash into
build-requires. Someone needs to give dash
a good fight-back, and if it should be me - oh
well. :)

**Comment by severach** [comment]
This can be made dash compatible with `case esac`. I agree though. I only use bash for scripts now. bash is required for many Arch Linux internals.

**Comment by stsp** [comment]
> This can be made dash compatible with case esac.

Indeed, but using `case esac` for this is clumsy.
I don't want to accept the bad coding just because
dash decided to dictate me so.

So if no one objects, I'll be adding bash
into build-requires. To me, dash is just a
madness that removes features that people
got used to, stating them as "unportable".
The end result is a lot of compatibility problems
and nothing good. I think people should start
ignoring dash and I am fine with being the first
one with that.

**Comment by andrewbird** [comment]
Requiring bash is fine by me, thanks.

**Comment by stsp** [comment]
Added to build-reqs.
In fact, dash is good at requiring me to
use a proper shebang, which is `#!/bin/bash`.
Not a big problem at all, if we don't have an
ill-fated attitude of removing bashisms.

**Comment by stsp** [comment]
> bash is required for many Arch Linux internals.

I guess Arch have never had this problem at all.
The problems started when ubuntu made dash
as `/bin/sh`. Arch doesn't do this, is it?
Ubuntu probably only wanted people to explicitly
state `#!/bin/bash` in their scripts when using
bash-specific constructs (perfectly valid requirement),
but people got too scared with that change and started
to remove bash constructs... I can even see a lot of
"remove bash constructs" commits in dosemu1. But
they seem to be very small, nothing really valuable
was lost it seems, yet I wouldn't do this.

**Comment by severach** [comment]
````
% ls -l /usr/bin/sh
lrwxrwxrwx 1 root root 4 Feb 14 08:16 /usr/bin/sh -> bash*
````
/bin/sh puts bash in compatibility mode which disables most but not all bash constructs. dash is available but it's not installed by default. It doesn't make sense to remove bashisms. Bash is available everywhere and is not going away.

So far as I know the original reason to switch to dash was to speed up startup which systemd made irrelevant.

**Comment by stsp** [comment]
It appears not as simple as that.
People from freebsd camp are telling
me to not do this, because they have
bash in `/usr/local/bin/bash` at best.
So the `#!/bin/bash` in a script makes
them to fsck.
Any solution to this? :(
I tried `#! bash` (without a full path),
but that seem to produce some strange
effect.

**Comment by andrewbird** [comment]
Can you do
~~~
#! /usr/bin/env bash
~~~

which I think people used to do to find perl or python in the path?

**Comment by stsp** [comment]
Yes, thank.
Done exactly that, lets see.

**Comment by severach** [comment]
Git version is broken again.
````
make[1]: *** No rule to make target '../../.git/refs/heads/devel', needed by 'include/version.h'.  Stop.
````
Fixed with `ln -s '../.git' 'src/.git'` as found in #317. Related to #356 #324

**Comment by stsp** [comment]
> Git version is broken again.

Please, such statements make no sense.
The only thing I can say is "no its not".

**Comment by andrewbird** [comment]
There seems to be a build failure in the Launchpad ppa, see [buildlog](https://launchpadlibrarian.net/321337427/buildlog_ubuntu-xenial-i386.dosemu2_2.0~pre7-4460+46c197d~ubuntu16.04.1_BUILDING.txt.gz)
The salient section appears to be
~~~
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
   dh_auto_build -a -O--parallel -O--builddirectory=build
	make -j4
make[1]: Entering directory '/<<PKGBUILDDIR>>/build'
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
make[2]: Entering directory '/<<PKGBUILDDIR>>/build/src'
fatal: Not a git repository (or any of the parent directories): .git
Non-git builds deprecated
echo "Updating version.h"; \
~~~
Note the ppa is bzr repo not git so has no .git directory. If it's a problem, I'll disable the Recipe and later see if I can build using a git repo.

**Comment by severach** [comment]
Ok, it's not you. It's git, either a bug or a new feature. They fixed something that broke #324.
````
%  git --version
git version 2.12.2
%  cd src
%  bash -x ../git-rev.sh 
++ git rev-parse --symbolic-full-name HEAD
+ SYM=refs/heads/makepkg
++ git rev-parse --git-path refs/heads/makepkg
+ REV=.git/refs/heads/makepkg
+ '[' . '!=' / ']'
++ git rev-parse --show-cdup
+ CDUP=../
+ '[' -n ../ ']'
+ REV=../.git/refs/heads/makepkg
+ echo ../.git/refs/heads/makepkg
../.git/refs/heads/makepkg
````

````
%  git --version
git version 2.13.0
%  cd src
%  bash -x ../git-rev.sh 
++ git rev-parse --symbolic-full-name HEAD
+ SYM=refs/heads/makepkg
++ git rev-parse --git-path refs/heads/makepkg
+ REV=../.git/refs/heads/makepkg
+ '[' . '!=' / ']'
++ git rev-parse --show-cdup
+ CDUP=../
+ '[' -n ../ ']'
+ REV=../../.git/refs/heads/makepkg
+ echo ../../.git/refs/heads/makepkg
../../.git/refs/heads/makepkg
````

**Comment by stsp** [comment]
@severach Ah! So they finally fixed that
horrible bug which caused the entire headache!
But of course they broke all my work-arounds
on top of it... This should now be fixed.

@andrewbird the lines:
```
fatal: Not a git repository (or any of the parent directories): .git
```
are not actually fatal at all, its just some kind of frightening.
The problem was with `echo -E` in mkpluginhooks,
should now be fixed.

**Comment by stsp** [comment]
Lets make a note here that in the future we
should require git version >= 2.13.0.
The particular fix is:
https://github.com/git/git/blob/master/Documentation/RelNotes/2.13.0.txt
```
 * The "--git-path", "--git-common-dir", and "--shared-index-path"
   options of "git rev-parse" did not produce usable output.  They are
   now updated to show the path to the correct file, relative to where
   the caller is.
```

So at present we have broken tar, broken sdl and
broken git in all distros, with the upstream patches
being already in.

**Comment by andrewbird** [comment]
Perhaps I jumped to the wrong conclusion with assuming the problem was the fatal line. Maybe something else broke all the ppa builds?

**Comment by stsp** [comment]
Whatever it is, it is fixed.
