### ISSUE TITLE
MT-32 on IRQ2 breaks packet driver RX callback

### ISSUE THREAD

**Issue by jharrison022** [stsp/dosemu2#329]
The configuration file doesn't accept $_midi_synth = (mt32), but it accepts $_midi_synth = "mt32".

**Comment by jharrison022** [comment]
EDIT -- This was a response to another issue, it shouldn't have shone up here.

**Comment by stsp** [comment]
FYI I replied in another thread.

**Comment by jharrison022** [comment]
Here are the relevant log and configuration files.

The only difference between the two setups --, one has the MT-32 on IRQ2, the other on IRQ11.  Both use the packet driver.  No other difference.

When the MT-32 is on IRQ2, the receiver callback function registered with the packet driver is never reached.  

http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq11
http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq11.log.bz2
http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq2
http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq2.log.bz2

**Comment by jharrison022** [comment]
Here are the relevant log and configuration files.

The only difference between the two setups --, one has the MT-32 on IRQ2, the other on IRQ11.  Both use the packet driver.  No other difference.

When the MT-32 is on IRQ2, the receiver callback function registered with the packet driver is never reached.  

http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq11
http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq11.log.bz2
http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq2
http://home.ix.netcom.com/~jjingber/dosemurc-munt-mt32-irq2.log.bz2

**Comment by jharrison022** [comment]
Incidentally, it won't work on IRQ9 either.  Only 2 and 9 have this problem.

**Comment by stsp** [comment]
Please use `-D9+SPr` log, not +a

**Comment by stsp** [comment]
Oh, you need to test this on a git branch `devel`,
not a 6.1 release or master.

**Comment by jharrison022** [comment]
Will do.
