### ISSUE TITLE
prince2 hangs when configured with GM music

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#33]

**Comment by PaulRaul** [comment]
I don't know if this should be a new ticket or part of the MPU-401 ticket, but I tried out Prince2, and there are some other games configured for MIDI that appear to fail in the same way.  Ultima 6 is one of them, and I've provided my log file for comparison.

http://home.ix.netcom.com/~jjingber/boot.log

**Comment by PaulRaul** [comment]
I don't know if this should be a separate ticket, or should be part of the MPU-401 ticket, but there are other games configured for MIDI which appear to fail in a similar way.  Ultima 6 is one of them, and I've attached my log file for comparision:

http://home.ix.netcom.com/~jjingber/boot.log

**Comment by stsp** [comment]
Yes, new ticket please.
With all needed url to reproduce the game.

**Comment by stsp** [comment]
Not sure if I still can reproduce this...
