### ISSUE TITLE
windows-3.1 int33 mouse driver crashes

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#330]
Got a "divizion by zero or overflow" error in
windows with our win31 mouse driver.
This may be a driver's bug, but more likely
dosemu's. It probably returned the coords
above maximum.

**Comment by jschwartzenberg** [comment]
I was already thinking of trying to get Windows 3.1 to work in debug mode. I understand it will output stuff over the serial port then, it should be possible to hook up DOSEMU2's serial port to some tool to easily read this out with a pipe.

**Comment by stsp** [comment]
All we need is a -D9+Mm log.
Unfortunately this problem looks very rare.
IIRC you mentioned it once too.

**Comment by stsp** [comment]
Since this crash is very rare, lets move it:
https://github.com/stsp/win31-mouse-driver/issues/1

**Comment by stsp** [comment]
I think this could depend on what was going
on before the windows start. As there were
problems with stalled pointer from ps2 mode,
which our windows driver doesn't use, but the
original one does.
So I think we've seen this error either right
after win31 install (setup uses original driver),
or after swapping the drivers in and out.
Should now be fixed.

**Comment by stsp** [comment]
Should have been fixed with 0d1295e1f and c7688784e.
