### ISSUE TITLE
SDL mouse cursor not hidden

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#331]
After the commit 227d59631961b2e566a88e511401778f5ff12e42, the SDL mouse cursor will not be hidden in graphics mode. Observed when running PC/GEOS.

The SDL mouse cursor is shown along the mouse cursor of the DOS program. Switching once to grab mode hides the SDL mouse cursor and it stays hidden as expected even after leaving grab mode and leaving/entering the window.

**Comment by stsp** [comment]
> it stays hidden as expected even after

Does it stay disable after exit and restart of
the geos itself?

I can't reproduce this. Maybe some SDL versions
lose the cursor visibility upon some operations
that happen during mode switch?
SDL2-2.0.5

**Comment by stsp** [comment]
Should now be fixed.
So the code in question was just a work-around
for another bug.

**Comment by bolle732** [comment]
Once doing the grab / ungrab, the SDL cursor keeps hidden. Even after an exit from GEOS to DOS and starting it again. Further, it doesn't makes a difference, if the grab/ungrab is done in the text mode or graphics mode.

I'm on Ubuntu 16.04 with the following SDL packages:

libsdl1.2debian:amd64 (1.2.15+dfsg1-3)
libsdl2-2.0-0:amd64 (2.0.4+dfsg1-2ubuntu2)
libsdl2-dev (2.0.4+dfsg1-2ubuntu2)

**Comment by bolle732** [comment]
Yes, it's fixed right now ;-) Thanks a lot !

**Comment by stsp** [comment]
> Even after an exit from GEOS to DOS and

Yes, it turned out that the initial state was not
propagated. So just one switch of it made it
in sync.
