### ISSUE TITLE
dosemu.conf going to wrong location

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#333]
The .conf file is going to `/etc/dosemu/dosemu/dosemu.conf`. Is that intentional?

**Comment by stsp** [comment]
No.
That usually happens when you checked
out to older commits and back, without
`make realclean`.
Please close if so.

**Comment by stsp** [comment]
Restart autogen.sh

**Comment by severach** [comment]
Manually running `make clean` and `autogen.sh` do not apply to me. The PKGBUILD always erases the build folder. Every build is clean. With 4 cores 8 threads a complete build only takes 50 seconds so partial rebuilds offer no benefit to me.

**Comment by stsp** [comment]
Then you have manually specified `sysconfdir`
and/or `confdir`. You shouldn't have been doing so.

**Comment by severach** [comment]
Changing `sysconfdir` from `/etc/dosemu` to `/etc` fixed it. You must have had the files outside of a folder a long time ago.

**Comment by stsp** [comment]
Please use `default-configure` to avoid the
problems like this.
