### ISSUE TITLE
Add uninstall target

### ISSUE THREAD

**Issue by bmanga** [stsp/dosemu2#334]
Hi, the makefile doesn't seem to provide an uninstall target to undo the "make install" process.
Is there an easy way to uninstall it?

**Comment by stsp** [comment]
I think the simplest way of uninstalling is
to `rm -rf /usr/local/share/dosemu`.
I wonder if it would be good to use this for
coding `make uninstall` in general, or is too
rough...

**Comment by bmanga** [comment]
I think it generates more than just that folder (for example the binaries in /usr/local/bin).
The rm calls should be fine, provided that they undo all the generated stuff from make install

**Comment by stsp** [comment]
Yes, there are quite a few more dirs
(bin, man, doc, etc), but its still quite simple
to remove things from there. I wonder if uninstall
should erase /etc/dosemu though, perhaps
this one should stay.
But its not a high-priority feature.
Would be nice if you can try this on your own.

**Comment by bpranoto** [comment]
I am using ubuntu. Instead of make install,  I run checkinstall. With checkinstall besides installing it also makes a .deb package,  to uninstall you then just simply run dpkg -r dosemu2 or apt-get remove dosemu2

There is also make deb which makes debian package, however it always starts from the scratch (clean all, configure, make). It installs in /usr directory where as make install installs in /usr/local

**Comment by severach** [comment]
I use Arch Linux. The package provides uninstall functionality. The [standard](https://wiki.archlinux.org/index.php/Pacman/Pacnew_and_Pacsave#.pacsave) for files in /etc is to delete them if they are the same as original and rename them if they contain user customized information.

**Comment by stsp** [comment]
> The standard for files in /etc is to delete

This is a standard for the particular package manager.
I don't want to turn "make uninstall" into a package
manager, I want something simple. So I guess I'd just
leave the config untouched. Removing everything else
looks pretty much straight-forward. "make uninstall" is
a very handy feature when you build from sources a lot,
but it should be avoided when you use the package
manager. If the prefix matched, you can uninstall the
wrong thing.

**Comment by stsp** [comment]
Trivial make uninstall was coded up.
