### ISSUE TITLE
Borland MAKE.EXE 4.0 crashes under DOSemu

### ISSUE THREAD

**Issue by jharrison022** [stsp/dosemu2#335]
http://home.ix.netcom.com/~jjingber/dosemurc
http://home.ix.netcom.com/~jjingber/make.exe
http://home.ix.netcom.com/~jjingber/makefile
http://home.ix.netcom.com/~jjingber/boot.log.bz2

Current DOSemu running 'make' with this dosemurc and makefile crashes DOSemu.  I know this worked maybe three or four months ago but now it doesn't -- I don't know exactly when this broke.

SIGILL while in vm86(): 0004:0063
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=addc2000 while in vm86 (DOS)

Program=do_vm86.c, Line=156
EIP: 0004:00000063 ESP: 0047:0000110e  VFLAGS(b): 00011 00000000 00000010
EAX: 00011808 EBX: 00006a68 ECX: 00000001 EDX: 000007a5 VFLAGS(h): 00030002
ESI: 0001ffff EDI: 00010183 EBP: 00020444 DS: 013f ES: 013f FS: 0000 GS: 0000
FLAGS: IF RF VM  IOPL: 0
STACK: ff 12 00 00 40 89 03 d4 ac d9 -> 66 00 64 d9 ac d4 12 ff ff 00 
OPS  : 10 3f 01 bc 10 3f 01 bb 02 55 -> da f6 02 02 c3 1e 01 55 da da 
	daf6                0004:0063 fidiv st(6)

closing debugger pipes
GEN: fd=21 removed from select SIGIO
coopthreads stopped
VID: video_close() called
VID: video_close()->Video->close() called
SPEAKER: sound off
calling keyboard_close
SER: Running serial_close
SER0: Running ser_close
GEN: fd=27 removed from select SIGIO
JOY: joy_uninit() CALLED!
GEN: fd=19 removed from select SIGIO
GEN: fd=19 removed from select SIGIO
KBD: keyb_server_close()
00| cec3:0fac->0cfbdc   01| 0070:06f4->000df4   02| f000:c004->0fc004
03| 0070:06f4->000df4   04| 00c0:0400->001000   05| 7006:f4f0->07f550
06| f000:c008->0fc008   07| 06f4:f000->015f40   08| 06f4:0070->006fb0
09| f000:e987->0fe987   0a| f400:7006->0fb006   0b| 0700:7006->00e006
0c| f000:c00e->0fc00e   0d| 0070:06f4->000df4   0e| f000:c007->0fc007
0f| 0070:06f4->000df4   10| 00c0:0700->001300   11| 00c0:08f0->0014f0
12| f000:c014->0fc014   13| c008:f000->0cf080   14| c009:f000->0cf090
15| 0070:084a->000f4a   16| 09f0:00c0->009fc0   17| b9f0:00c0->0b9fc0
18| f000:c01a->0fc01a   19| f000:c009->0fc009   1a| c903:0cb9->0c9ce9
1b| 077a:107d->00881d   1c| 030c:b9f0->00eab0   1d| 00e9:87c9->009659
1e| 0000:0522->000522   1f| e987:c903->0f6173   20| f100:f000->100000
21| d967:00cb->0d973b   22| 00f0:00e9->000fe9   23| 0df0:00f1->00dff1
24| 077a:128e->008a2e   25| f000:f100->0ff100   26| f000:c00d->0fc00d
27| 013f:10bc->0024ac   28| 00c0:0df0->0019f0   29| 00c0:0ef0->001af0
2a| da55:011e->0da66e   2b| c00e:f000->0cf0e0   2c| c00f:f000->0cf0f0
2d| 013f:10da->0024ca   2e| 0ff0:00c0->00ffc0   2f| 10f0:00c0->010fc0
30| 3f10:d0ea->04c1ea   31| f000:c00f->0fc00f   32| f000:c010->0fc010
33| efff:c045->0fc035   34| 00c0:10f0->001cf0   35| 7006:f4f0->07f550
calling disk_close_all

**Comment by stsp** [comment]
This is not on branch `devel`.
Please post an update if it doesn't work on `devel`.
