### ISSUE TITLE
Request: ctl-z functionality?

### ISSUE THREAD

**Issue by Dobesov** [stsp/dosemu2#337]
Hello, let me first say I am very happy to see this project. I grew up in the golden age of shareware and DOS will always have a special place in my heart. I'm not a giant Linux guy and I'm an old pascal hack. I came across this project because I was actually thinking of starting a dumb personal project to make myself a DOS dedicated Linux system. Just a small Linux core to take care of modern drivers and facilitate what I would call a "Modern multitasking DOS environment" you know the original dream of FreeDOS... a what if DOS was still a developed viable OS.

I was going to write some text mode interfaces and programs to spiff things up a bit and give old DOS some flare the likes of ANSI art style FX I used in the past... one of the things I wanted to make was a session controller, a sort of menu system that would let you launch new DOS sessions and cycle through them.

Then I found out that I could not actually run a ctl-z in dosemu, I started looking for alternate methods, like running unix ps, getting the PID and running a unix kill -TSTP <PID>, and that worked, but dosemu could not be brought back to the foreground.

I was just wondering if in this new super cool version there could be some facility to pause the session to the background so that you could effectively run and switch between DOS tasks. Yes, I know you can alt-arrow through virtual consoles, but you have to log in again and I just it would be neat to have a way to "minimize" your instance.

I'm sure there might be some technical hurdles, so I get if its not possible or even on the radar. Just a thought.

P.S. when you run unix ps it returns the result of ps -e, not ps. weird.

I'd like to support your endeavor in any way I can, Thank you for your effort and work!

-Sean

**Comment by stsp** [comment]
Hi, if you are so keen about the DOS emulation,
then the first question is have you already tried dosbox?
It is very nice that you are so amused about our
project, but it shouldn't be just because you haven't
looked into other similar ones.

I am not sure what display mode you are using.
Virtual consoles? Are they KMS or plain text?
Are you doing a VGA pass-through or text-mode
or gfx with SDL over directfb?

We have a way to pause dosemu session, just hit
Ctrl-Atl-p. As for putting it into background - this is
very vague without specifying your environment,
for example under X session you can just minimize
the dosemu window with a mouse click.

**Comment by Dobesov** [comment]
I'm very aware of DOSbox, its fine for playing games when you have a tremendous amount of CPU to spare. My interest in DOSEMU comes from more of an operating system integration perspective. DOSbox is a full emulator, where as DOSEMU is a more integrated way of allowing DOS access to system resources while scheduling and emulating things that need to be, like the NTVDM, which is why I find it far more interesting as technology.

I have been using it in pure console VGA mode, no x no GUI.

On the console if you are running a Linux program, you can press ctl-z and it will pause the process and spit you back to prompt. From there you can tell it to continue running in the background and start a new process. or bring it back to the foreground. The only way to really multi-task on a single ssh or console session.

By virtual console I mean the 6 console session Linux makes available and that can be accessed by using alt and arrow keys or fkeys. When you have dropped to or start up with no GUI, you are offered multiple console sessions to work with, when you switch to a new one you log in to it just as though you made a new ssh session, in this way you can be logged into the system multiple times when physically sitting at it and run tasks in parallel. This of course works fine.

**Comment by stsp** [comment]
Today pure vga console is most certainly KMS.
If you didn't append `nomodeset` then it is.
In which case you likely run dosemu with -t switch
to use the terminal mode? Or do you have sdl2 built
with dfb support?
Anyway, what you do is a mystery, so I just added
the `-ks` switch that will allow use to use ^Z in terminal
modes.

**Comment by stsp** [comment]
^Z is now fully supported with `-ks` but
of course it only works properly with `-dumb` / `-td`.
In general, `-k` now selects the console
keyboard backends, eg `-kt` selects a tty backend.
Note that the tty/stdio backends were just very
recently implemented, but up until now there was
no way to select them explicitly. So I guess this
feature is just in time.
