### ISSUE TITLE
VESA OEM mode number not starting at 0x140

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#338]
I've found an odd behaviour. In 'vgaemu_modelist.h' we have the following define:
`#define	VBE_FIRST_OEM_MODE 0x140`

While printing the mode number in 'vgaemu.c' -> `vga_emu_setup_mode_table()`, the mode number started with `0x142` instead of  `0x140`.

Checking the following code
```
  for(vmi_end = vmi + vbe_modes; vmi < vmi_end; vmi++) {
    if(vmi->VESA_mode == -2) vmi->VESA_mode = vbe_num++;
    if(vmi->VESA_mode > last_mode) last_mode = vmi->VESA_mode;
```
shows that the mode number is increased if `VESA_mode` has the value `-2`.

I found 2 modes, which are defined in `vga_mode_table[]` with the value of `-1`, but get overwritten to `-2`:

```  {0x13,    -1, GRAPH,   P8,  8,  320,  200,  40, 25,  8,  8},```
```  {0x6b,    -1, GRAPH,  P24, 24,  320,  200,  40, 25,  8,  8},```

This overwrite occures  in 'vgaemu.c' -> `vga_emu_setup_mode()`:
```
int vga_emu_setup_mode(vga_mode_info *vmi, int mode_index, unsigned width, unsigned height, unsigned color_bits)
{
  int i;

  for(i = 0; i < mode_index; i++) {
    if(vmi[i].width == width && vmi[i].height == height && vmi[i].color_bits == color_bits) {
      if(vmi[i].VESA_mode == -1) vmi[i].VESA_mode = -2;
      return 0;
    }
  }
```
In my eyes, we shouldn't overwrite the `VESA_mode` here, only `return 0`. Removing the line
`if(vmi[i].VESA_mode == -1) vmi[i].VESA_mode = -2;`
lets start the OEM VESA modes at `0x140`.

Is this correct or do I miss some point ?

**Comment by stsp** [comment]
Not sure. I have the following questions:

- One of the modes you've found, 0x13, is the
VGA mode, so who calls vga_emu_setup_mode()
for it and why?

- The second mode is P24, which doesn't look like
a VGA-only mode to me. Why doesn't it have the
VESA mode number assigned in the table? If there
is no such VESA mode officially, then I think redefining
it to -2 and then renumbering to >=0x140 space
makes sense.

- What breakage have you observe with this, what
makes you think there is a bug?

**Comment by stsp** [comment]
> VGA mode, so who calls vga_emu_setup_mode()
> for it and why?

... likely just to assign a vesa mode to it in 0x140 space.
I see no bug here.

**Comment by stsp** [comment]
The question is still whether that code
assigns a vesa number to any mode
marked with -1, or it just choose these 2?
If so, why they were chosen?

**Comment by bolle732** [comment]
As I first understand, the code will add the VESA mode number starting at `VBE_FIRST_OEM_MODE` to all modes defined in `vgaemu_simple_mode_list[]` and `$_X_vgaemu_memsize`.

But as I can see now, it updates the VESA modes also in the `vga_mode_table[]`, if it exist in `vgaemu_simple_mode_list[]` or `$_X_vgaemu_memsize`.

It seems I had an incomplete set-up with my debug printf statements and the first OEM number is really `0x140`. So, sorry for the noise!
