### ISSUE TITLE
FD tarball path specification

### ISSUE THREAD

**Issue by fhanzlik** [stsp/dosemu2#341]
maybe there is unnecessary `$(REALTOPDIR)/` part in fdtarball spec:
```
--- ../../../../dosemu-2.0pre6.1/src/arch/linux/Makefile.main.PUV	2017-03-18 22:14:49.000000000 +0100
+++ ../../../../dosemu-2.0pre6.1/src/arch/linux/Makefile.main	2017-03-18 22:37:05.681185225 +0100
@@ -157,9 +157,9 @@
 	-rm -rf $(cmddir)
 	-rm -rf $(sysdir)
 	$(INSTALL) -d $(DESTDIR)$(etcdir)
-	if [ -f $(REALTOPDIR)/$(fdtarball) ]; then \
+	if [ -f $(fdtarball) ]; then \
 	  rm -rf $(DESTDIR)$(dosemudir)/freedos; \
-	  tar -C $(DESTDIR)$(dosemudir)/.. --no-same-owner -xpzvf $(REALTOPDIR)/$(fdtarball); \
+	  tar -C $(DESTDIR)$(dosemudir)/.. --no-same-owner -xpzvf $(fdtarball); \
 	  rm -f $(DESTDIR)$(dosemudir)/FDchange.log; \
 	  rm -f $(DESTDIR)$(dosemudir)/README.bindist; \
 	  rm -rf $(DESTDIR)$(dosemudir)/freedos/tmp; \
```

**Comment by stsp** [comment]
Could you please be more specific?
I don't see why this is wrong.

**Comment by fhanzlik** [comment]
When I run configure as here (fdtarball spec as abs. path -  as redhat rpmbuild macro does):
```
configure (here i have compiletime-settings /sysconffdir and fdtarball/) --build=i686-redhat-linux-gnu' '--host=i686-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-fdtarball=/home/hanzlik/src/rpm/SOURCES/dosemu-freedos-1.1-pre1-bin.tgz'
```
then root Makefile.conf contain right spec:
`fdtarball:=/home/hanzlik/src/rpm/SOURCES/dosemu-freedos-1.1-pre1-bin.tgz`
but in 'src/rpm/BUILD/dosemu-2.0pre6.1_0/src/arch/linux/Makefile.main' it is interpreted as
relative path:
```
if [ -f ..//home/hanzlik/src/rpm/SOURCES/dosemu-freedos-1.2-bin.tgz ]; then \
dosemubld-20170313-020626.lst-  rm -rf /home/hanzlik/src/rpm/BUILDROOT/dosemu-2.0pre6.1-dev.20170311.370.gd80b555.2.dbgemu.fc19.i386/usr/share/dosemu/freedos; \
```

**Comment by stsp** [comment]
We do not support any other specs than we
provide. Please use `make rpm`.

**Comment by stsp** [comment]
Let me know if our spec doesn't work for you.

**Comment by fhanzlik** [comment]
IMO this is unrelated (directly) with my own spec file, but with fdtarball absolute pathspec  - the same result I get if I want to build dosemu manually and I enter absolute fdtarball path.

**Comment by stsp** [comment]
`make rpm` expects the fdtarball in a dosemu's
top dir. Is this too restrictive? I don't see any problem
with that.

**Comment by fhanzlik** [comment]
But it is not just for "make rpm", but also for each assembly by using the configure / make / install, right? Even in these cases can not be fdtarball specified using an absolute path, I think.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by fhanzlik** [comment]
Yes now it works, thanks.
This problem would be, I think, approved in the moment when creates a source RPM and use rpmbuild to create a binary rpm package. Dosemu source tarball, fdtarball and any other files and patches are in the directory, which is also outside unpacked source tree - so it is necessary to refer outside source tree. A rpmbuild macros implicitly refer source and other files by absolute path.

**Comment by stsp** [comment]
fdtarball is a legacy thing.
It will be removed in the future releases.
Our spec doesn't refer to it. Only I myself
was making the fd-enabled packages,
others couldn't. :)
If for the moment they can - so be it, but
I'll remove it when the alternative implementation
is done.
