### ISSUE TITLE
Serial port initialization appears to be slow with high CPU usage

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#348]
I see this issue in both Windows 3.1 Terminal and Kermit.

To reproduce:
1. Install tty0tty: https://github.com/freemed/tty0tty
2. Put a getty on /dev/tnt0 (follow the distro docs on doing it for ttyS0)
3. Test with 'cu -l /dev/tnt1' (tnt0 is linked with tnt1)
4. In dosemu.conf/.dosemurc: $_com1 = "/dev/tnt1"
5. Install Kermit: http://www.columbia.edu/kermit/mskermit.html
6. Start kermit and type connect

Instead of 6 also the Terminal in Windows 3.1 can be used.

Each time there is some kind of initialization going on, the dosemu process is using a lot of CPU and the application appears to hang for a moment.

**Comment by stsp** [comment]
Hmm, seems tty0tty is a kernel module?
I don't think I am going to support this.
Is there a test-case without a kernel module?

**Comment by stsp** [comment]
You can start from the following:
`socat PTY,link=/tmp/a PTY,link=/tmp/b`
which will create a tty pair just like tty0tty
does, but without any kernel modules.
Then please rearrange the test-case to
use agetty or mingetty.

**Comment by jschwartzenberg** [comment]
It seems that this already works:
```
socat PTY,link=/tmp/a exec:bash,pty,stderr,setsid
```

Then you get immediately get bash from within dosemu. This also shows the high CPU usage issue.

**Comment by stsp** [comment]
Should I still need mskermit, windows etc etc?
What is the full path of reproducing this?

**Comment by jschwartzenberg** [comment]
1. socat PTY,link=/tmp/a exec:bash,pty,stderr,setsid
2. Test with 'cu -l /tmp/a' (tnt0 is linked with tnt1)
3. In dosemu.conf/.dosemurc: $_com1 = "/tmp/a"
4. Install Kermit: http://www.columbia.edu/kermit/mskermit.html
5. Start kermit and type connect

Instead of 4 & 5 above you can also do:

4. Install Windows 3.1
5. Start Terminal from the Accessories group and connect with COM1.

**Comment by stsp** [comment]
Thanks.
The correct line is:
`socat PTY,echo=0,link=/tmp/vmodem exec:bash,pty,stderr,setsid`

`echo=0` was missing, which produced an infinite
data stream and CPU load.

**Comment by jschwartzenberg** [comment]
With latest GIT, I can confirm that Terminal in Windows 3.1 doesn't have any hangs anymore whatsoever! There is still high CPU usage though. Kermit is still very slow as well and the CPU usage is very high when Kermit is slow.

I've tested everything with both tty0tty and the corrected socat command.

So your fix helps a lot, but there are still things that appear to be odd.

**Comment by stsp** [comment]
Please open a new ticket then.
The remaining is likely about some optimization,
the obvious bug is fixed.

**Comment by stsp** [comment]
Btw, `cu -l /tmp/a` just gives me "Line busy".

**Comment by jschwartzenberg** [comment]
That usually means that the device is not properly accessible. This works fine here:
In one terminal:
socat PTY,echo=0,link=/tmp/vmodem exec:bash,pty,stderr,setsid
In another:
cu -l /tmp/vmodem

Then I get bash in cu.

I'll open another ticket but the reproduction path is pretty much the same. Is there any additional info you'd like?

**Comment by stsp** [comment]
No, I am not getting shell with cu in fedora-25.

**Comment by jschwartzenberg** [comment]
I can confirm that this is broken with Fedora 25. I don't get the bash shell inside dosemu with Kermit either through socat. With Ubuntu this works. On Fedora I do see the high CPU usage with Kermit then though.

I'll see if I can get tty0tty to work on Fedora.

**Comment by stsp** [comment]
Thanks for continuous testing.

**Comment by jschwartzenberg** [comment]
tty0tty works on Fedora 25, but if your system is updated (kernel 4.11) you need to use this PR:
https://github.com/freemed/tty0tty/pull/10

After loading the module, I had to:
1. add my user to the tty group
2. sudo chgrp tty /dev/tnt*
3. sudo chmod g+r,g+w /dev/tnt*
4. sudo systemctl start getty@tnt0.service
5. Relogin or su <username> so that `groups` shows tty

Then `cu -l /dev/tnt1` works. Opening `/dev/tnt1` as _root_ doesn't work maybe due to SELinux.

I don't know if there's a way to get socat working on Fedora like it works on Ubuntu now. I guess it would make sense to test this with SELinux disabled.

**Comment by jschwartzenberg** [comment]
Kermit works with the above on Fedora 25, but the initialization phase is still very slow & CPU hungry. Let me know if I can open a bug with this module as a reproduction path or whether it should stay in user space (or with real serial hardware). I would expect the same behaviour with real serial hardware.

**Comment by stsp** [comment]
Yes, please keep using socat.
I have already showed your mistake with
it a few messages above, so that it works
fine.

**Comment by jschwartzenberg** [comment]
I couldn't get it to work on Fedora 25 at all though, even with your fixed command. I just got a bit further with that. This works for me now:
```
socat PTY,echo=0,link=/tmp/vmodem exec:bash,pty,stderr,setsid
```
and in another terminal
```
cu -l `readlink /tmp/vmodem`
```
This while making sure that /dev/pts/* is owned by the tty group and has g+r,g+w set.
