### ISSUE TITLE
QEMM 97 optimize crashes Dosemu

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#35]
With current GIT:
After enabling QEMM 97 (probably a bad idea in general) and doing the 'cold reboot' it requests, Dosemu crashes with this output:
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=000955b5 while in vm86 (DOS)
Program=sigsegv.c, Line=185
EIP: 000a:00000a58 ESP: 9fc9:00000106  VFLAGS(b): 00000 00000011 10000011
EAX: 00003fc4 EBX: 0000f000 ECX: 00000000 EDX: 000003c9 VFLAGS(h): 00000383
ESI: 00000119 EDI: 00000070 EBP: 00000200 DS: 0070 ES: 207d FS: 0000 GS: 0000
FLAGS: CF SF TF IF RF VM VIF  IOPL: 0
STACK: 00 9c 46 32 0d 0a 0a 00 26 83 -> 01 ff 00 c3 e8 3f f0 33 f6 e8 
OPS  : 00 00 00 00 00 00 00 00 00 00 -> ff ff ff ff ff 4e 4f 20 4e 41 
        ff                  000a:0a58 db FF

I remember it would fail gracefully before.

**Comment by stsp** [comment]
> I remember it would fail gracefully before.

How and when?

**Comment by jschwartzenberg** [comment]
Seems I was wrong. It fails gracefully only after removing this crashing driver from config.sys, I did that before as well. If you want I can provide a debug log for this one, but it's probably not a regression.

**Comment by stsp** [comment]
No, I don't want an exotic bugs.
Too few development resources.
Better if you send a patch. :)

**Comment by jschwartzenberg** [comment]
Yep makes sense. I think it would be neat to have Deskview/X working with its X11 inside Dosemu, but that'd be quite tough. Here's the debug output in case anybody is interested:

CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xF0000 for 'E' (EMS page frame)
CONF: reserving 132Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

!!! Illegal op f0 09 00
==============================================================
CPU exception 0x06 err=0x00000000 cr2=000955b5 eip=00000ae3
==============================================================
SIGILL while in vm86(): 000a:0a43
ERROR: LOCK prefix not permitted!
!!! Illegal op ff ff ff
==============================================================
CPU exception 0x06 err=0x00000000 cr2=000955b5 eip=00000af8
==============================================================
SIGILL while in vm86(): 000a:0a58
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=000955b5 while in vm86 (DOS)

**Comment by stsp** [comment]
This is mostly impossible: I don't have
desqview, and there is probably no legal
way I can get it.
Please see if it works on 32bit system, maybe
it is 64bit-specific problem? Also see if it
works on dosbox.

**Comment by stsp** [comment]
By the way, I think desqview can't work
under dosemu at all. Does it work under
anything other than qemm? For example,
will it work under Win9x if qemm was not
loaded before windows?
dosemu only runs user-level software, but
not system-level software.

**Comment by jschwartzenberg** [comment]
This page is online for a few years, but legality is unclear: http://www.chsoft.com/dv.html

I understand that Desqview requires QEMM, that would be the only purpose to have QEMM in Dosemu. Desqview actually managed to run a copy of Windows 3.1 itself, so it probably qualifies as system-level software.

The main thing would be how Dosemu should deal with such software. Completely crash with an error which suggest to report a bug or recognize this specific condition and report that this kind of software cannot be supported.

**Comment by stsp** [comment]
> I understand that Desqview requires QEMM, that would be the only
> purpose to have QEMM in Dosemu.

Impossible.
Why not to use some other multitasker than desqview?

> Desqview actually managed to run a copy of Windows 3.1 itself

Was it able to switch between tasks after that?
Like run multiple copies of win31?
dosemu runs win31 either.

> which suggest to report a bug or recognize this specific condition and report that this kind of 
> software cannot be supported.

I wonder if the crash is x86-64-specific.
Well, to make a more graceful handling, we
need to add a stubs for VCPI calls, that will
just return an error. A good task for a new
dosemu coder - will you make a patch? :)

**Comment by jschwartzenberg** [comment]
The only reason for Desqview/X specifically would be to be able to forward the window containing Windows over X11 to the host desktop. Another idea that seemed interesting was having Dosemu hosting an X11 server. It seems there are also other alternatives for this however (X11 servers that run inside Windows 3.1 :).

You're right I should look into writing a patch for that myself. It seems more useful than just playing DOS games all the time ;) I'll see if I can get somewhere with that!!

I'll see if I can test this also on a 32-bit system btw.

**Comment by stsp** [comment]
I don't understand anything.
Can't you forward the window containing
Windows to host desktop just with dosemu?

**Comment by stsp** [comment]
Also I think you are confusing X server and
X client. If you want Windows window to be
passed to host desktop and rendered there,
then the "Windows window" is an X client, and
the "host desktop" hosts an X server.
Desqview/X had both, but you only need the
client, which is... well, dosemu.

**Comment by stsp** [comment]
> The main thing would be how Dosemu should deal with such software. Completely crash with an
> error which suggest to report a bug

No, this indeed should never happen.
If it asks to report a bug, then that should be fixed.
Please, where in your quoted output it asks to report
a bug?

**Comment by jschwartzenberg** [comment]
Yep, but imagine you could run a copy of Dosemu and have its window inside another Dosemu instance ;)

The output here is just the contents of the boot.log. The message asking to report the bug is printed on the terminal only.

**Comment by stsp** [comment]
> The output here is just the contents of the boot.log. The message asking to report
> the bug is printed on the terminal only.

It should be in the log either, no?
Please provide a full log with debug info then.

**Comment by stsp** [comment]
> Yep, but imagine you could run a copy of Dosemu and have its window inside
> another Dosemu instance ;)

While I think it is pretty useless, please check this one:
ftp://ftp.ta3.sk/pub/DOS/X.PC/

**Comment by stsp** [comment]
See here for a full list of an available
X servers for DOS:
ftp://ftp.ta3.sk/pub/DOS/X.PC/XServers-NonUNIX.txt
Wow! I didn't know there's so many.

**Comment by stsp** [comment]
http://www.coe.ufrj.br/~acmq/xview-pc.html
This one may even run under dosemu.
OK, I think enough info for you to play with. :)
