### ISSUE TITLE
Crash in Fedora 25

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#358]
I installed Fedora 25 cleanly and tried to install and run dosemu2. It immediately crashes on start-up however.

Attached my boot.log.
[boot.log.txt](https://github.com/stsp/dosemu2/files/908479/boot.log.txt)

**Comment by stsp** [comment]
I can't reproduce this, but likely now fixed.

**Comment by jschwartzenberg** [comment]
Indeed fixed!

**Comment by stsp** [comment]
10x, good to know.
Fewer crashers for next pre.
