### ISSUE TITLE
Wrong dosemu fonts

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#364]
with 

`$_X_font = "vga11x19"`

dosemu gives this:

```
You do not have the DOSEMU vga11x19 font installed and are running
remote X. You need to install the vga11x19 font on your _local_ Xserver.
Look at the readme for details. For now we start with the bitmapped
built-in font instead, which may be slower.

```
Here is the output of  /usr/share/dosemu/Xfonts

```
gilang@gilang-desktop:~/master/dosemu2$ ls /usr/share/dosemu/Xfonts -l
total 76
-rw-r--r-- 1 root root  784 Apr 17 20:23 fonts.alias
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga10x20-cp850.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga10x20-cp866.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga10x24.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga11x19.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga12x30.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga8x14-cp850.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga8x19.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga-cp866.pcf.gz
-rw-r--r-- 1 root root 5537 Apr 17 20:23 vga.pcf.gz

```

The file sizes are different with dosemu1's, here is dosemu1's:

```
bambang@bambang-notebook:~$ ls -l /usr/local/share/dosemu/Xfonts
total 364
-rw-r--r-- 1 root root 307200 Apr 17 15:05 -z
-rw-r--r-- 1 root root    637 Oct 26  2012 fonts.alias
-rw-r--r-- 1 root root    518 Oct 26  2012 fonts.dir
-rw-r--r-- 1 root root   5011 Oct 26  2012 vga-cp866.pcf.gz
-rw-r--r-- 1 root root   4844 Oct 26  2012 vga.pcf.gz
-rw-r--r-- 1 root root   5451 Oct 26  2012 vga10x20-cp866.pcf.gz
-rw-r--r-- 1 root root   5702 Oct 26  2012 vga10x24.pcf.gz
-rw-r--r-- 1 root root   5838 Oct 26  2012 vga11x19.pcf.gz
-rw-r--r-- 1 root root   6271 Oct 26  2012 vga12x30.pcf.gz
-rw-r--r-- 1 root root   5323 Oct 26  2012 vga8x19.pcf.gz


```

By copying dosemu1's fonts directory, the problem is solved.

This was unnoticed before because I have a copy of  vga11x19.pcf.gz from previous version in other font path.

**Comment by stsp** [comment]
Thanks!
Should now be fixed.

**Comment by bpranoto** [comment]
I purge my dosemu installation and reinstall again.

Now, /usr/share/dosemu/Xfonts contains right fonts and dosemu recognized vga11x19 fonts.

However, after relogin dosemu  gives `You do not have the DOSEMU vga11x19 font installed` error again, it turns that the file fonts.dir did not exist. Running mkfontdir in /usr/share/dosemu/Xfonts solves the problem.

**Comment by stsp** [comment]
mkfontdir is run by `make install`.
This doesn't work or are you installing
by other means?

**Comment by bpranoto** [comment]
Yes, I ran `make deb` and then installed via `sudo dpkg -i *.deb`

**Comment by stsp** [comment]
Could you please add the postinst script
that does `mkfontdir` and submit a PR here?
Thanks!

**Comment by bpranoto** [comment]
I'd love to do it. But I am just only an application programmer and don't have capability/knowledge to do that... Sorry..

**Comment by stsp** [comment]
Maybe @fhanzlik can help?

**Comment by andrewbird** [comment]
Perhaps this can help. There seems to be a debhelper that can be added to the debian rule file to do the xfont installation
http://manpages.ubuntu.com/manpages/xenial/en/man1/dh_installxfonts.1.html

**Comment by fhanzlik** [comment]
I know nothing about .deb packages, I'm using RPM-based distros.
There I have this in install phase:
```
mkdir -p ${RPM_BUILD_ROOT}/etc/X11/fontpath.d
ln -s /usr/share/dosemu/Xfonts ${RPM_BUILD_ROOT}/etc/X11/fontpath.d/dosemu-Xfonts
```
and in postinstall script:
```
FONTDIR=/usr/share/dosemu/Xfonts
if [ -x /usr/bin/xorg-x11-fonts-update-dirs ]; then
# this script from xorg-x11-font-utils call all of mkfontscale/mkfontdir/fc-cache etc:
  /usr/bin/xorg-x11-fonts-update-dirs $FONTDIR
else
{
# create an index of scalable font files for X:
  umask 133; mkfontscale $FONTDIR

# create an index of X font files in a dosemu Xfonts directory:
  umask 133; mkfontdir $FONTDIR

# build font information cache files for applications using fontconfig:
  if [ -x /usr/bin/fc-cache ]; then 
    /usr/bin/fc-cache $FONTDIR
  fi
} || :
fi
```
and in postuninstall script:
```
FONTDIR=/usr/share/dosemu/Xfonts
if [ "$1" = "0" ]; then         # if we are uninstalling dosemu:
  if [ -x /usr/bin/xorg-x11-fonts-update-dirs ]; then
    /usr/bin/xorg-x11-fonts-update-dirs $FONTDIR
  else
    {
      if [ -d $FONTDIR ]; then
        mkfontdir $FONTDIR
      fi

      if [ -x /usr/bin/fc-cache ] ; then 
        /usr/bin/fc-cache $FONTDIR
      fi
    } || :
  fi
fi
```
and this seems be working. Maybe someone with .deb packaging skills could do some appropriate adaptations for .deb packages?

**Comment by stsp** [comment]
Someone needs to gather this stuff
and integrate into `make rpm` and `make deb`. :)

**Comment by andrewbird** [comment]
Just looking at this now. I notice an odd thing though, which I don't think is right for a packaged install, dosemu is playing with the font path at runtime.
~~~
VID: initializing video X                                                       
X: X_init                                                                       
X: visual class is TrueColor                                                    
X: using true color visual                                                      
X: pixel size is 32 bits/pixel                                                  
X: MIT-SHM major opcode: 130                                                    
X: using MIT-SHM                                                                
X: X_keymap_init: X server vendor is "The X.Org Foundation"                     
X: X_keymap_init: using DOSEMU's internal keycode translation                   
X: X_init: parent window: 0x274                                                 
X: X_init: screen = 0, root = 0x274, mainwindow = 0x2200001                     
X: running xset +fp /usr/share/fonts/X11/misc/dosemu 2>/dev/null                
X: X_change_config: font "vga11x19" not found, using builtin                    
X: NOT loading a font. Using EGA/VGA builtin/RAM fonts.                         
X: EGA/VGA font size is 9 x 16                                                  
Resizing our window to 720x400 image                                            
X: resize_ximage 720 x 400 --> 720 x 400                                        
X: X_init: mouse grabbing enabled, use Ctrl+Mod1+Home to activate               
~~~

Every time dosemu is run the dosemu font path is prepended to the current font path, causing multiple duplicates, see the section below.

xset q
~~~
Font Path:
  /usr/share/fonts/X11/misc/dosemu,/usr/share/fonts/X11/misc/dosemu,/usr/share/fonts/X11/misc/dosemu,/usr/share/fonts/X11/misc/dosemu,/usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
~~~

Note i've changed the font path to that which is used for the official dosemu1 debian package. This has the benefit of causing the debian helper font install tool to be run.
~~~
make[1]: Leaving directory '/clients/common/dosemu2.git'
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_installman
   dh_perl
   dh_link
   dh_installxfonts <<<<<<< ====== :-)
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   dh_gencontrol
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'dosemu2' in '../dosemu2_2.0~pre7-1_i386.deb'.
 dpkg-genchanges -b >../dosemu2_2.0~pre7-1_i386.changes
~~~

**Comment by andrewbird** [comment]
I notice now that the font path is only changed at runtime if the font is not found, so IMHO it's okay as is. I've updated via a PR the xfont install directory to be the standard Debian location and so the Debian packaging helpers notice that the font cache needs updating and do so automatically.

**Comment by andrewbird** [comment]
The debian build seems to have broken for all versions and archs
~~~
echo "-> Installing the X PC fonts..."
-> Installing the X PC fonts...
for i in ../etc/*.pcf.gz; do \
    install -m 0644 $i /<<PKGBUILDDIR>>/debian/dosemu2/usr/share/dosemu/Xfonts; \
done
install -m 0644 ../etc/fonts.dir /<<PKGBUILDDIR>>/debian/dosemu2/usr/share/dosemu/Xfonts
install: cannot stat '../etc/fonts.dir': No such file or directory
../src/arch/linux/Makefile.main:153: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/src'
Makefile:26: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_install: make -j4 install DESTDIR=/<<PKGBUILDDIR>>/debian/dosemu2 AM_UPDATE_INFO_DIR=no returned exit code 2
debian/rules:3: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary-arch gave error exit status 2
~~~

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
Nope, sorry all versions and arch still failing
~~~
echo "-> Installing the X PC fonts..."
-> Installing the X PC fonts...
for i in ../etc/*.pcf.gz; do \
    install -m 0644 $i /<<PKGBUILDDIR>>/debian/dosemu2/usr/share/dosemu/Xfonts; \
done
/usr/bin/install -c -m 0644 ../etc/dosemu.alias /<<PKGBUILDDIR>>/debian/dosemu2/usr/share/dosemu/Xfonts/fonts.alias; \
cd /<<PKGBUILDDIR>>/debian/dosemu2/usr/share/dosemu/Xfonts
mkfontdir
ln -sf /<<PKGBUILDDIR>>/debian/dosemu2/usr/share/dosemu/Xfonts /etc/X11/fontpath.d/dosemu2:unscaled:pri=20
ln: failed to create symbolic link '/etc/X11/fontpath.d/dosemu2:unscaled:pri=20': No such file or directory
../src/arch/linux/Makefile.main:153: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/src'
Makefile:26: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_install: make -j4 install DESTDIR=/<<PKGBUILDDIR>>/debian/dosemu2 AM_UPDATE_INFO_DIR=no returned exit code 2
debian/rules:3: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary-arch gave error exit status 2
~~~

BTW what's the rational for putting dosemu fonts in their own directory? On my Lubuntu 16.04 system, no other package has done so.
~~~
ajb@polly:~$ find /usr/share/fonts/X11 -type d
/usr/share/fonts/X11
/usr/share/fonts/X11/Type1
/usr/share/fonts/X11/util
/usr/share/fonts/X11/encodings
/usr/share/fonts/X11/encodings/large
/usr/share/fonts/X11/misc
~~~

~~~
ajb@polly:~$ xset q | egrep '(Font|fonts)' 
Font Path:
  /usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
~~~

and I don't even have an /etc/X11/fontpath.d

**Comment by stsp** [comment]
Should now be fixed.

> BTW what's the rational for putting dosemu fonts in their own directory?

Much simpler installation of `fonts.dir` and,
more importantly, `fonts.alias`. That way we
don't even need to generate them in a `postinst`.
Note that in fedora, this is normal. I have, for
example, `/etc/X11/fontpath.d/nethack` etc.
By altering the install path to `/usr/share/fonts/X11/misc`
as you PR does, you gain nothing, because
there you already have fonts.alias that will
collide (unless the dpkg can merge those
upon installation). If ubuntu doesn't support
`fontpath.d` and there is no simple way around,
lets just say that it sucks and forget about this
problem. dosemu will alter the font path at
runtime, so it will still work correctly. I don't want
any extra complications if some distro sucks. :)

**Comment by andrewbird** [comment]
It seems to me that you are just reinventing the packaging decisions that Debian made. Just because that's how it works in Fedora and if it doesn't work that way it's broken is not really a proper argument. From what I see the Debian installation procedure shouldn't do anything with fonts.dir and fonts.alias. By using the standard path the Debian package helper regenerates those on package install and removal if said package alters the contents. See how easy it's supposed to be https://wiki.debian.org/Fonts/PackagingPolicy.
BTW I didn't test your latest patch, but isn't it trying to make a link into a **system** area at package build time, shouldn't it be doing that at package install time?

**Comment by stsp** [comment]
> using the standard path the Debian package helper regenerates those on package install

AFAIK you can't regenerate `fonts.alias`.
You really need to take the supplied one and the
existing one, and merge them together, unless I
am missing something.

> time, shouldn't it be doing that at package install time?

I checked what other packages do, and I see:
```
$ LC_ALL=C rpm -qf /etc/X11/fontpath.d/*
cjkuni-uming-fonts-0.2.20080216.1-57.fc24.noarch
ghostscript-fonts-5.50-35.fc24.noarch
file /etc/X11/fontpath.d/dosemu2:unscaled:pri=20 is not owned by any package
urw-fonts-2.4-22.fc24.noarch
efont-unicode-bdf-0.4.2-18.fc24.noarch
fonts-KOI8-R-100dpi-1.0-23.fc24.noarch
fonts-KOI8-R-75dpi-1.0-23.fc24.noarch
fonts-KOI8-R-1.0-23.fc24.noarch
liberation-fonts-common-1.07.4-7.fc24.noarch
file /etc/X11/fontpath.d/nethack is not owned by any package
terminus-fonts-4.40-5.fc25.noarch
xorg-x11-fonts-ISO8859-1-100dpi-7.5-16.fc24.noarch
xorg-x11-fonts-100dpi-7.5-16.fc24.noarch
xorg-x11-fonts-ISO8859-15-100dpi-7.5-16.fc24.noarch
xorg-x11-fonts-ISO8859-1-75dpi-7.5-16.fc24.noarch
xorg-x11-fonts-75dpi-7.5-16.fc24.noarch
xorg-x11-fonts-cyrillic-7.5-16.fc24.noarch
xorg-x11-fonts-misc-7.5-16.fc24.noarch
xorg-x11-fonts-Type1-7.5-16.fc24.noarch
```

So as you can see, most symlinks there are
owned by the packages, which means they
are not generated on install time. Still the
`nethack` package doesn't seem to own the
symlink, so we can do it that way too.

**Comment by stsp** [comment]
And yes, I find the `fontpath.d` a cool thing
that distros should support. You have the right
to disagree of course, and of course I will not
reject the PRs that support those that suck. :)
If you PR does things rightly about `fonts.alias`
and works fine with the latest changes, then
fine.

**Comment by stsp** [comment]
Seems like ubuntu has `/etc/X11/fonts/*`.
I added the change to get it used, but it is untested.

**Comment by andrewbird** [comment]
>So as you can see, most symlinks there are
owned by the packages, which means they
are not generated on install time. 

But from the error earlier the link is attempted to be made at package build time into below the real`/etc` directory, this is on the build farm logs.
~~~
>ln -sf /<<PKGBUILDDIR>>/debian/dosemu2/usr/share/dosemu/Xfonts /etc/X11/fontpath.d/dosemu2:unscaled:pri=20
ln: failed to create symbolic link '/etc/X11/fontpath.d/dosemu2:unscaled:pri=20': No such file or directory
../src/arch/linux/Makefile.main:153: recipe for target 'install' failed
make[2]: *** [install] Error 1
~~~
I know that you now test for `/etc/X11/fontpath.d` existence, but surely that can't be right?

The thing is with the right installation path for fonts in the package, the Debian package helper sorts out the font installation and removal for you. e.g. it generates the post.install script magically. Here's the one from the deb package generated with just my one line change
```sh
#!/bin/sh
set -e
# Automatically added by dh_installxfonts
if which update-fonts-dir >/dev/null 2>&1; then
	update-fonts-dir --x11r7-layout misc
fi
# End automatically added section
```

**Comment by stsp** [comment]
> at package build time into below the real/etc 

The build usually happens under `fakechroot`.
Plus the dir is not hardcoded, it follows `--sysconfdir`.
I am not sure what problem are you mentioning.

> I know that you now test for /etc/X11/fontpath.d existence, but surely that can't be right?

Please don't assume that `make install` is just a
helper for `debuild`. It is not. Its primary use is to
create the working installation. And the working
installation should contain symlink in `/etc/X11/fontpath.d`.

> it generates the post.install script magically.

I already added the untested installing of `fonts.alias`
to ubuntu's place, so maybe this will now work.

**Comment by stsp** [comment]
> I know that you now test for /etc/X11/fontpath.d existence, but surely that can't be right?

Maybe you want to consolidate all such tests
in configure, but in this particular case it is just
not worth the troubles. We have a runtime
fall-back for those distros that fsck, so no
complex logic is needed to offload to configure.

**Comment by stsp** [comment]
I think you meant to say that I forgot DESTDIR.
Which is now there. Looks better? :)

**Comment by stsp** [comment]
Should now be fixed.
