### ISSUE TITLE
fontpath

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#365]
After running dosemu several times, here is the output of `xset -q` fontpath:

```
Font Path:
  /usr/share/dosemu/Xfonts,/usr/share/dosemu/Xfonts,/usr/share/dosemu/Xfonts,/usr/share/dosemu/Xfonts,/usr/share/dosemu/Xfonts,/usr/share/dosemu/Xfonts,/usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins

```
Is it possible to check whether dosemu Xfonts already in fontpath before adding one?

**Comment by stsp** [comment]
Does not happen for me.
I think this is a left-over from the situation
when you had bad fonts installed.

**Comment by bpranoto** [comment]
You're right. After relogin the problem disappears..
