### ISSUE TITLE
big performance difference on relatively same HW /OS

### ISSUE THREAD

**Issue by fhanzlik** [stsp/dosemu2#367]
I did some performance testing and found big differences betveen run on my PC a my kids NTB, which I can not explain. I run 3 sort of tests - one display ASCII text intensive, second math operation intensive and third I/O intensive. Responses on NTB are cca several times worse than on PC - biggest difference is in I/O (~15x), which is partialy understandable, but difference in math ops is also ~ 1:8 and in display speed ~ 1:7. My configuration:

PC: Core2 Duo E8200@2.66GHz (CPUMark 1883/1113), Linux Fedora 19/i686
NTB: i5-560M@2.67GHz (2601/1198), Linux Fedora 25/i686
(CPU Mark is from http://www.cpubenchmark.net/, firs number is overall, second single thread)
On both machines is set vm.mmap_min_addr=0 (did it matter also in dosemu2?).
dosemu.conf on both machines contain only '$_sound = (off)', nothing else.
differences between boot.log's  are these (both dosemu's run in terminal mode):
```
42,43c46,47
< Linux kernel 4.10.8; CPU speed is 2133000000 Hz
< CPU-EMU speed is 2133 MHz
---
> Linux kernel 3.14.27; CPU speed is 1998000000 Hz
> CPU-EMU speed is 1998 MHz
47,49c51,53
< DOSEMU-2.0pre6.1 is coming up on Linux version 4.10.8-200.fc25.i686 #1 SMP Fri Mar 31 14:02:07 UTC 2017 i686
< Compiled with gcc version 6.3.1 32bit
< CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.h -Wno-unused-result -fplan9-extensions -Wno-maybe-uninitialized -ggdb3 -O0 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables
---
> DOSEMU-2.0pre6.1 is coming up on Linux version 3.14.27-100.fc19.i686.PAE #1 SMP Wed Dec 17 19:56:19 UTC 2014 i686
> Compiled with gcc version 4.8.3 32bit
> CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.h -Wno-unused-result -fplan9-extensions -Wno-maybe-uninitialized -ggdb3 -O0 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables
52d55
< using CPU emulation for vm86()
55c58
< Conventional memory mapped from 0xb68d1000 to 0xae5cb000
---
> Conventional memory mapped from 0xb714d000 to (nil)
58,59c61,62
< Registering HWRAM, type=e base=0xad477000 size=0x400000
< CONF: reserving 4096Kb at 0xAD477000 for 'e' (VGAEMU LFB)
---
> Registering HWRAM, type=e base=0xb5ef0000 size=0x400000
> CONF: reserving 4096Kb at 0xB5EF0000 for 'e' (VGAEMU LFB)
69c72
< DPMI: mem init, mpool is 136273920 bytes at 0xae6db000
---
> DPMI: mem init, mpool is 136273920 bytes at 0xaa57000
74,75d76
< ======================= ENTER CPU-EMU ===============
< 
78c78
< leavedos(dos_helper:566|0) called - shutting down
---
> leavedos(dos_helper:565|0) called - shutting down
82,83d81
< ======================= LEAVE CPU-EMU ===============
```
from which it seems as CPU on NTB is somehow emulated (part of NTB boot.log about CPU:
```CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: CPU VM set to -1
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI base addr = 0xffffffff
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout keyb-user
CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P cups-pdf  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: disk type 'Directory' drive C:
CONF: disk type 'Directory' drive D:
CONF: disk type 'Directory' drive E:
CONF: cdrom MSCD0001 on /dev/cdrom
CONF: config variable c_system unset
Linux kernel 4.10.8; CPU speed is 2133000000 Hz
CPU-EMU speed is 2133 MHz
work around FreeDOS UMB bug
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
DBG_FD already set
DOSEMU-2.0pre6.1 is coming up on Linux version 4.10.8-200.fc25.i686 #1 SMP Fri Mar 31 14:02:07 UTC 2017 i686
Compiled with gcc version 6.3.1 32bit
...
using CPU emulation for vm86()
initial register values: fs: 0x0000  gs: 0x0033 eflags: 0x0246
...
======================= ENTER CPU-EMU ===============
...
======================= LEAVE CPU-EMU ===============
```
/proc/cpuinfo flags on NTB (slow, M 560@2.67GHz): fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm ida arat

/proc/cpuinfo flags on PC (fast, E8200@2.66GHz): fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm dtherm tpr_shadow vnmi flexpriority

Please, are these differences explainable/normal, or ...?

**Comment by stsp** [comment]
Try `$_cpu_vm="kvm"`.

> On both machines is set vm.mmap_min_addr=0 (did it matter also in dosemu2?).

Yes but sometimes you need to also disable selinux
for this to work. With "kvm" it is not needed.

**Comment by fhanzlik** [comment]
$_cpu_vm="kvm": KVM: error opening /dev/kvm: No such file or directory
                                 ERROR: KVM not available: No such file or directory
(I had disabled virtualization in BIOS)

 $_cpu_vm="vm86": ERROR: vm86 service not available in your kernel, Function not implemented
(Fedora 25 has kernel opts:
# CONFIG_X86_LEGACY_VM86 is not set
# CONFIG_VM86 is not set
, in contrast to Fedora 19, where is VM86 enabled )

What is famous, it seems as even on 32-bit machine is KVM emulation faster than VM86 - in my tests is displaying speed about 20% better with vm86 (it would need to do more tests), but with kvm it is about three times faster in mathematical calculation. I/O is roughly same with kvm and vm86.


Thank you for all this tremendous work!

PS: on machines where I run dosemu I have selinux usually in permission mode, as there. But is useful to know about this.

**Comment by fhanzlik** [comment]
Yeah, Markdown styling is striking. Then it should be rather:

# Thank you for all this tremendous work!

**Comment by stsp** [comment]
@bartoldeman have contributed the KVM
support, so this is his thanks. :)
