### ISSUE TITLE
dosemu not respect --Fimagedir option

### ISSUE THREAD

**Issue by fhanzlik** [stsp/dosemu2#368]
when running
dosemu --Fimagedir SOMEPATH -E command
dosemu still create ~/.dosemu/ structure and also command is searched there - instead to using analogical SOMEPATH structure (.dosemu/ hierarchcal tree).

**Comment by stsp** [comment]
Please see the very old bug #80 .
It may be a duplicate of this one.
But its too long to make any sense of,
and seems like ending inconclusively.
But @andrewbird had some patches.
Someone with enough of free time
needs to study that ticket and try to
revive it. :)

**Comment by fhanzlik** [comment]
Why I report about it: I have DOS program, which I run under dosemu from remotely accessing PCs. They start dosemu with command roughly as:
```
dosemu --Fimagedir /var/lib/dosemu/$USER/$REMOTEPCNAME/$DOSPRGNAMEVARIANT -f /var/lib/dosemu/$USER/$REMOTEPCNAME/$DOSPRGNAMEVARIANT -E 'C:\\program.bat'
```
This was because I need set some properties depending on the remote station that is accessing (their IP address, remote station name, etc.).
I had this was working with dosemu-2.0pre1-20150215.g1fa5fef which I build 15-Feb-2015 from git (on Centos 6 - which is another problem :( ). Also it was working on dosemu-1.4 and older. Now it is failing, and I have no idea how solve this needs.

**Comment by stsp** [comment]
You can try `-K` for now.

**Comment by andrewbird** [comment]
Whilst I agree that after specifying --Fimagedir=xxx dosemu shouldn't look in ~/.dosemu for drives/* there are other things that are still expected to be there, for instance: 
- ~/.dosemu/disclaimer
- ~/.dosemu/boot.log
- ~/.dosemu/run/dosemu-midi
- ~/.dosemu/run/dosemu.dbg*

You may need to use -o to specify independent boot.log and -n may help to give you local config control. I notice that your -f points to the same path as the --Fimagedir, I would expect that to be a config file. If these don't help, then I think we need more detail on what exactly is in conflict between the dosemu instances.

Regarding previous patches, it's been a while and they probably don't apply now, but I seem to remember that two things stopped me; what to do about the auto freedos installation if boot files are missing; use of wildcards and environment variables in paths.

Going forward I think that as a general rule if the user specifies --Fimagedir , auto installation of Freedos if no boot files are found should be avoided. I think that indicates his intent not to run a standard installation, is that a reasonable assertion?

**Comment by stsp** [comment]
> I think that indicates his intent not to run a standard installation, is that a reasonable assertion?

I think this doesn't matter in most cases.
Even if you specified the alternate path, it
should still be bootable, in which case the
install is avoided anyway.
I'll remove the freedos installation completely
soon.
So I don't think this is a show-stopper of any kind.

**Comment by jschwartzenberg** [comment]
You can tell dosemu to use a different location for its drives by specifying a dosemu__hdimage environment variable.

**Comment by fhanzlik** [comment]
My fault, Andrew, Stas, Julius - excuse for it. In this case dosemu started from several slightly complex scripts and this was not quite obvious - but basicaly it start as:
```
HOME="/var/lib/dosemu/$USER/$REMOTEPCNAME"  dosemu --Fimagedir /var/lib/dosemu/$USER/$REMOTEPCNAME/$DOSPRGNAMEVARIANT -f /var/lib/dosemu/$USER/$REMOTEPCNAME/$DOSPRGNAMEVARIANT -E 'C:\\program.bat'
```
(environment variable "HOME" point to same directoty as --Fimagedir, thus all dosemu files are there.  It is the same as in the previous dosemu 1.x). Thanks.
