### ISSUE TITLE
DOSEMU2's ems.sys breaks Video for Windows

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#379]
When I have this line in config.sys (and e:\dosemu\ems.sys exists):
```
devicehigh=e:\dosemu\ems.sys
```

I get this message when trying to play an AVI file inside Windows 3.1:
"There is no driver installed on your system."

Putting 'rem' in front of that line allows videos to be played inside Windows 3.1.

**Comment by stsp** [comment]
Please attach `-D9+ME` for good and bad.
msdos.c uses ems a lot, so maybe there was
some "unsafe" usage.

**Comment by jschwartzenberg** [comment]
Here you are!
[boot.log-bad.gz](https://github.com/stsp/dosemu2/files/1002277/boot.log-bad.gz)
[boot.log-good.gz](https://github.com/stsp/dosemu2/files/1002276/boot.log-good.gz)

**Comment by stsp** [comment]
IIRC windows uses different modes depending
on the presence of ems. Can you try explicitly
`/s` and `/3`?

**Comment by stsp** [comment]
You can also try winos2.com

**Comment by jschwartzenberg** [comment]
It seems you're completely right! In 286 mode it never works, in 386 mode it does. Stupid I had missed this in the title bar.

I guess that Video for Windows not working in 286/standard mode is the problem then. I have no idea at all whether this is the case on real hardware as well, although I suspect it was supposed to work.

**Comment by stsp** [comment]
Whether VfW is supposed to work, needs
to be tested, but I don't suppose this matters
much. Not a ems bug (unimplemented feature),
and not sure if it worth an efforts to code things
for 286 mode...

**Comment by jschwartzenberg** [comment]
Yeah, I'll test this in PCEM tonight and see. At least now I know that 386 mode is more compatible than 286 mode, so I'll continue to test primarily with enhanced mode. I was always doubting which mode would make the most sense to use (and test).

I still need to document the SB16 driver installation for win31. I think it would also make sense to have a set of recommendations regarding running win31 somewhere which would mention that 386-enhanced mode is recommended. And maybe something about bug reporting and testing both modes explicitly in that case. I'd like to avoid others to make my mistakes again :)

**Comment by stsp** [comment]
It is difficult to say which mode is recommended.
For example we do not support DOS prompt in
enhanced mode as it will require a rather good
implementation of Shell vxd, while in standard
mode it is implemented with dswap.exe instead.
I think DOS shell is the only exception as it has
the separate driver file for standard mode, dswap.exe.
But if there are other things that has different
impl between standard and enhanced mode, then
we are in troubles.
Another problem is that, as you already see, windows
defaults to 286 with our emm implementation because
it can't find the needed API there to switch to real mode
(we don't support this, but maybe some stubs are possible
to just make windows think that we do).

**Comment by jschwartzenberg** [comment]
I don't know if there are many features that the DOS prompt in Windows 3.1 would offer that wouldn't be offered by a second DOSEMU instance? I also found in a readme that the vxd (v*d.386) drivers included with the SB16 drivers are actually only used to provide sound support in DOS applications. I don't know why this extra driver is needed, but maybe it means that sound support currently doesn't work in DOS applications running in Windows 3.1 either. I never tried this.

At least a recommendation could be to run enhanced mode for more compatibility with Windows applications or the specific compatibility issues we're seeing could be documented.

**Comment by stsp** [comment]
> I don't know if there are many features that the DOS prompt in Windows 3.1 would offer

But some people like yourself may decide to
open the bug ticket nevertheless. :)

> why this extra driver is needed

Likely to handle concurrent accesses.
For example if windows or another DOS prompt
already uses SB, the next DOS prompt should
behave as there is no SB. If you allow windows
and multiple DOS prompts to access SB at the
same time, everything will crash.
Alternatively, this driver can present itself as an
_emulated_ SB, in which case multiple DOS sessions
and windows itself will be able to use SB at the same
time, but I don't think in win31 era such advanced tricks
were common so I would guess subsequent DOS prompts
to get no SB, but you need a .386 driver even for this.

> At least a recommendation could be to run enhanced mode for more compatibility with Windows

I'd say this is good to add to tweaks.sgml where we
collect the temporary solutions. Maybe in the future
out emm driver will trick windows to use 386 mode
by default and the DOS prompt is implemented, so
the recommendation to explicitly specify `/3` may
not be needed forever.
Feel free to submit the dos update. :)

**Comment by jschwartzenberg** [comment]
I just tested with PCEM. Same behavior there, 386 enhanced mode works, standard mode, same error as DOSEMU. Sorry for the noise!

I'll update the documentation, although I'm not sure whether I should mention this as it seems to be VfW or possibly Intel Indeo buggyness which is not DOSEMU2 specific.

**Comment by stsp** [comment]
You can update `tweaks.sgml` to suggest `/3`
unless the one wants a working DOS prompt.

**Comment by jschwartzenberg** [comment]
As I was reading through that old thread on SourceForge, I came across this message from Japheth:
https://sourceforge.net/p/dosemu/feature-requests/_discuss/thread/0a75f20e/?limit=25&page=2#a8a0

This was actually my exact testcase for this report. I can confirm the Civilization 2 videos play fine in enhanced mode.

**Comment by stsp** [comment]
Then we already do better than hdpmi. :)
