### ISSUE TITLE
cannot compile on ubuntu:  Unmet build dependencies: docbook-style-dsssl

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#383]
Git pulled last version dosemu2, but make deb failed:

dpkg-checkbuilddeps: error: Unmet build dependencies: docbook-style-dsssl

I am using ubuntu, looking at https://repology.org/metapackage/docbook-style-dsssl/versions show this package is not available in ubuntu (yet?)

**Comment by stsp** [comment]
Thanks, removed.
linuxdoc-tools package should get all the needed
deps like this itself.

**Comment by stsp** [comment]
I've merged a large build update.
Please check if things are still fine.
Thanks!

**Comment by bpranoto** [comment]
Last update builds fine.
Thanks for the good work.

**Comment by AMDmi3** [comment]
Just a note, docbook-style-dsssl may have [other names](https://repology.org/metapackages/all/?search=docbook%25dsssl), it's [docbook-dsssl](https://repology.org/metapackage/docbook-dsssl/packages) on Debian/Ubuntu.
