### ISSUE TITLE
Clipper protected mode application hangs - ERROR: coopth: unsafe context switch

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#384]
Protected Mode application written in Clipper hangs with ERROR: coopth: unsafe context switch.

Attached is the boot.log:

[bootlog.txt](https://github.com/stsp/dosemu2/files/1019543/bootlog.txt)

**Comment by stsp** [comment]
Please check you log.
```
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
```

Fix this, compile with debug info and attach
a new log please.

**Comment by bpranoto** [comment]
Attached:
[bootlog.txt](https://github.com/stsp/dosemu2/files/1020987/bootlog.txt)

**Comment by bpranoto** [comment]
BTW, the error happens when the application is idel for sometimes...

**Comment by stsp** [comment]
You are still not building with debug info.
Witness:
```
Reading symbols from /usr/bin/dosemu.bin...(no debugging symbols found)...done.
```

Please fix this with
```
make clean
./default-configure -d
make -j 9
sudo make install
```

**Comment by stsp** [comment]
If you are only installing from package, then
you need to install the dbg package to get
debug info. We do not generate it by default
though. This can be changed.

**Comment by bpranoto** [comment]
Hoping get a good log this time.
[bootlog.txt](https://github.com/stsp/dosemu2/files/1021948/bootlog.txt)

**Comment by stsp** [comment]
Looks better.
Are you using IPX?

**Comment by bpranoto** [comment]
yes.

**Comment by stsp** [comment]
Should now be fixed.
Another coopth-unsafe code, after 5 years
of coopth integration. This quite sucks.

**Comment by bpranoto** [comment]
Confirmed. No more coopth unsafe context switch error.
