### ISSUE TITLE
Kermit is slow with serial port initialization

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#390]
Full reproduction path which I tested on Fedora 25:
1. Make sure your user is in the tty group (`groups`)
2. `socat PTY,echo=0,link=/tmp/vmodem exec:bash,pty,stderr,setsid`
3. `readlink /tmp/vmodem` -> this should return something like `/dev/pts/1`
4. Make sure that the device permissions are correct, `chmod g+r,g+w /dev/pts/1`
5. Optional, test with `cu -l /dev/pts/1`
6. In dosemu.conf/.dosemurc: `$_com1 = "/dev/pts/1"`
7. I had to do this `chmod 777 /var/run/lock` before running dosemu (apparently related to an old-style locking mechanism)
8. Install Kermit: http://www.columbia.edu/kermit/mskermit.html
9. Start `kermit` and type `connect`

Starting Kermit will already take a long time with high CPU usage. This will continue again after typing `connect`. At some point the bash shell will become available inside Kermit.

**Comment by mcericdos** [comment]
Educated guess: Might be related to some forms of serial port bit banging being slow with some tools. Minicom does not have this issue, so whatever the workaround is, minicom has it ;-)

**Comment by stsp** [comment]
minicom is a linux app and mskermit is for win31.

**Comment by jschwartzenberg** [comment]
I haven't actually found or tested with a win31 version of kermit. I only ran the dos version directly inside dosemu (without Windows).
I can't find a dos version of Minicom, it was apparently inspired by Telix which was for dos.

**Comment by mcericdos** [comment]
Uhm misunderstanding! I mean the way in which LINUX software does bit banging on the physical serial port is prone to slowness and hangs in SOME variants of the software, while the LINUX version of minicom never has such hangs. So if you debug dosemu and see that there are issues in how it communicates with the Linux host operating system (for example ioctl or polling not wanting to cooperate) then you may want to have a look at minicum (for Linux) to see if that contains any work arounds which might be useful for dosemu to mimick in the code where dosemu communicates with Linux...

**Comment by stsp** [comment]
The dosemu usually does not spend a
lot of time on serial ports (unless someone
configured ~30 COM ports where polling
really becomes expensive). This ticket is
more likely about the DOS prog doing
polls.
Eric, you can just follow the instructions
above and reproduce it yourself. You are
very welcome to do so! :)

**Comment by stsp** [comment]
> readlink /tmp/vmodem

You don't have to, using /tmp/vmodem everywhere
is perfectly fine.

I think this kermit is simply buggy.
After `connect`, when I first type the
command, I can see it, and I can see
its result after pressing Enter. But after
that, nothing that I type and nothing that
is received via com port, is displayed on
screen. The cursor only moves down
when I press Enter, but it does not
print anything.

**Comment by stsp** [comment]
With this binary patch there is no slowdown:
```
0000EB20:     75 90
0000EB21:     F0 90
```

It uses delays by reading from port 0x61.
Maybe we should add some threshold and
not do the expensive stuff if we exit from
vm86 too often.
The simplest heuristic may look like this:
if we exit at the same address for more
than the threshold times in row, and that
address represents the port read, then
get back to vm86 immediately.

**Comment by stsp** [comment]
Still this doesn't fix the fact that there is
no data after the first command.

**Comment by stsp** [comment]
No, heuristic won't help.
It does the delay calibration via
PIT channel 2. To fix this properly
we need a reliable PIT timing, and
we are very far from this.
So for now please use the binary
patch.

**Comment by jschwartzenberg** [comment]
Yep, that works! Thanks!

**Comment by stsp** [comment]
OK, if you want you can document this.
