### ISSUE TITLE
key combos broken under X

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#391]
With `dosemu -X` the `alt-x` is not properly recognized
by software, for example by ndn.

**Comment by stsp** [comment]
Hmm, can't reproduce on fedora - only on ubuntu...

**Comment by jschwartzenberg** [comment]
Maybe related to X.org VS Wayland.

**Comment by stsp** [comment]
Can you reproduce?

**Comment by jschwartzenberg** [comment]
Do you have a nice testcase? Something like xev that runs inside dosemu maybe :)
