### ISSUE TITLE
ERROR: vde_switch failed: sh: 1: vde_switch: not found

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#396]
After newest build: g3bea242, I always get this error when starting:

`ERROR: vde_switch failed: sh: 1: vde_switch: not found`

despite of this, dosemu runs well though....

**Comment by andrewbird** [comment]
I've been seeing that message for a long time. I believe it's because the vde plugin is built, but I don't have the 'vde2' package installed.

**Comment by stsp** [comment]
Yes, indeed.
I added vde2 to Suggests.
But I have a question: if I depend on
some xlibs, should I also add xorg to
the dep list or what?

**Comment by jschwartzenberg** [comment]
xorg will provide an x11 server on the local system, but dosemu could run on another system than the x11 server, so I wouldn't suggest xorg as a recommends for xclient packages.

**Comment by stsp** [comment]
Yes, wrong example on my side.
Its just a bit annoying that I need to add
vde2 to deps only because I used
libvdeplug2-dev that itself depends on
libvdeplug2 but not on vde2. Hence the
example with xorg on which its libs do
not depend too.
