### ISSUE TITLE
int2f - misplaced brace?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#398]
As a precursor to reading int2f handler I indented it consistently, and now it appears that a brace may be misplaced if the IPX code is enabled. See below where the case for INT2F_DETECT_IPX appears within the braces for the previous case INT2F_IDLE_MAGIC. If it is indeed wrong, should I make two commits, one with the indentation change and one to correct?

```C
-static int int2f(void)
-{
+static int int2f(void) {
   reset_idle(0);
 #if 1
-  ds_printf("INT2F at %04x:%04x: AX=%04x, BX=%04x, CX=%04x, DX=%04x, DS=%04x, ES=%04x\n",
-       LWORD(cs), LWORD(eip),
-       LWORD(eax), LWORD(ebx), LWORD(ecx), LWORD(edx), LWORD(ds), LWORD(es));
+  ds_printf("INT2F at %04x:%04x: AX=%04x, BX=%04x, CX=%04x, DX=%04x, DS=%04x, "
+            "ES=%04x\n",
+            LWORD(cs), LWORD(eip), LWORD(eax), LWORD(ebx), LWORD(ecx),
+            LWORD(edx), LWORD(ds), LWORD(es));
 #endif
   switch (LWORD(eax)) {
-    case INT2F_IDLE_MAGIC: {  /* magic "give up time slice" value */
+    case INT2F_IDLE_MAGIC: { /* magic "give up time slice" value */
       idle(0, 100, 0, "int2f_idle_magic");
       LWORD(eax) = 0;
       return 1;
 
 #ifdef IPX
-    case INT2F_DETECT_IPX:  /* TRB - detect IPX in int2f() */
-      if (config.ipxsup && IPXInt2FHandler())
-        return 1;
-      break;
+      case INT2F_DETECT_IPX: /* TRB - detect IPX in int2f() */
+        if (config.ipxsup && IPXInt2FHandler())
+          return 1;
+        break;
 #endif
-  }
+    }
 
```

**Comment by stsp** [comment]
> +static int int2f(void) {

I think we use `indent -kr` style, not this.

Yes, please send 2 patches, just remove
both braces please. But I wonder
why is this not a syntax error. :)

**Comment by stsp** [comment]
> unless IPX is defined the code won't ever come into play.

IPX should always be defined.
It is still used.
So I think it is defined in this case.
