### ISSUE TITLE
Error finding .git/refs/heads/devel after 'git gc'

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#411]
I don't seem to be able to build any more, I think it's to do with the git repo packing the refs.

~~~
$ make distclean
$ ./default-configure -d
$ make
make[1]: Entering directory '/clients/common/dosemu2.git/src'
make[1]: *** No rule to make target '../.git/refs/heads/devel', needed by '../src/include/version.h'. Stop.
make[1]: Leaving directory '/clients/common/dosemu2.git/src'
Makefile:27: recipe for target 'default' failed
make: *** [default] Error 2

$ ls .git/refs/heads/
$ grep devel .git/packed-refs 
59de9240860e845a8d1aa0999a40b93ac712004f refs/heads/devel
9b6d3d1e9dbe86a5fcfc07297d96e321405f0235 refs/heads/devel-test
166511a033e36054916ce7b27c9283d2482185ed refs/remotes/origin/devel
~~~

**Comment by stsp** [comment]
`git rev-parse --symbolic-full-name HEAD`
What does it say?

**Comment by andrewbird** [comment]
~~~
$ git rev-parse --symbolic-full-name HEAD
refs/heads/devel
$ ls -l .git/refs/heads/
~~~
I think the assumption that refs/heads/$branch will always exist is wrong. I think that the 'git gc' caused packing, see [git-pack-refs](https://git-scm.com/docs/git-pack-refs).

As a workaround I did this
```
diff --git a/src/Makefile.common b/src/Makefile.common
index 00fb2461..ea0c6e0d 100644
--- a/src/Makefile.common
+++ b/src/Makefile.common
@@ -28,7 +28,7 @@ $(top_builddir)/src/lib $(top_builddir)/commands:
        ln -sf $(THISVERSION)/commands $(top_builddir)/commands
 
 GIT_REV := $(shell $(REALTOPDIR)/git-rev.sh)
-$(top_builddir)/src/include/version.h: $(top_builddir)/Makefile.conf $(REALTOPDIR)/VERSION $(GIT_REV)
+$(top_builddir)/src/include/version.h: $(top_builddir)/Makefile.conf $(REALTOPDIR)/VERSION
        echo "Updating version.h"; \
        echo "#ifndef   VERSION_H" > $@; \
        echo "#define   VERSION_H" >> $@; \
```

I'm using the git version 2.13, perhaps packing became more aggressive, as the error never occurred previously after 'git gc'

**Comment by stsp** [comment]
`git rev-parse --git-path` changed in 2.13 a lot.
Maybe before it simply used to produce the
valid path?
What does `git rev-parse --git-path devel` says?

**Comment by andrewbird** [comment]
~~~
$ git rev-parse --git-path devel
.git/devel
~~~

The trouble is that even if you fix the build to work with 2.13 now, when bisecting etc the problem still might occur. I suppose something like 'https://github.com/tj/git-extras/pull/197' might work, but I didn't dare to test on my repo!

**Comment by stsp** [comment]
Hmm, tested on 2.9 - the same thing. :(

**Comment by stsp** [comment]
I asked a question in git ML.
This seems to be a never-ending story
unless someone gives us a clue.

**Comment by stsp** [comment]
I am sure it is a wrong thing to do,
but should now be fixed.

**Comment by andrewbird** [comment]
Yes, allows the build to continue. Thanks.

**Comment by stsp** [comment]
Git people are actively suggesting to
stop doing that file lookup.
So lets keep this open.

**Comment by stsp** [comment]
Now probably for real.

**Comment by stsp** [comment]
Of course `.LOW_RESOLUTION_TIME` is still
a hack, but this time the hack is 1-line rather
than a big script, so this is definitely a progress. :)
