### ISSUE TITLE
Not sure if this is interesting, seems to be reimplementing DOS on win64

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#412]
http://takeda-toshiya.my.coocan.jp/msdos/index.html

**Comment by stsp** [comment]
Looks like ntvdm on top of the mame cpu emulator.
Doesn't seem to have jit.
Also I think it does not support gfx and sound,
whereas ntvdm did. Seems to have some dma
emulation, but I wonder what dma is good for
without sb emulation.
