### ISSUE TITLE
VESA test utility vbetest.exe doesn't work since new int_revect logic

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#419]
I'd decided to start on the remappers, but unfortunately the utility 'vbetest.exe' stopped to work. Trying to start any interactive test, it reports `ERROR: Video mode did not set correctly!` and seems to hang.

I've bisected it to the following commit:

$ git bisect bad
5dca7336d846891af70ca2865ebdd7e04bdc5df5 is the first bad commit
commit 5dca7336d846891af70ca2865ebdd7e04bdc5df5
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Wed Jul 19 07:02:12 2017 +0300

    int: update post_boot to employ new int_revect logic [#347]

:040000 040000 366c9c9b37b07c680ab98b9a4a4975b28f088ea4 aef4d45cc73ed76141586f994a3b823632cee3d9 M	src

**Comment by stsp** [comment]
Please don't put bisect results under
any markup. github would treat the commit
hashes as URLs if you don't mark it as code
block.

**Comment by stsp** [comment]
Where is this vbetest.exe?

**Comment by emendelson** [comment]
http://dll-rehab.com/file/vbetest.exe/12041.html

It's originally by Sci-Tech.

**Comment by bolle732** [comment]
@emendelson : thank you for providing the link!

@stsp : I use this utility as a reference for testing VBE modes (remappers).

**Comment by bolle732** [comment]
I've removed the mark-up for the bisect result.

**Comment by stsp** [comment]
Hmm, for me it doesn't work very differently.
I press `0` for interactive test. Then I press
anything, say `1`. Then it says:
```
Which video mode to test:
 
    [Q] - Quit
```
i.e. no choices but quit.
And this happens no matter what
colour depth have I selected.

**Comment by stsp** [comment]
This also breaks quake2...
Unlucky release. :)

**Comment by stsp** [comment]
This took me the whole night of debugging...
It appears the aforementioned patch was
innocent: 2 completely unrelated bugs suddenly
popped up in other places.
But I only tested with quake2.
Does vbetest work too?

**Comment by bolle732** [comment]
Yes, it works again like before with 97664050a1616467a38aaedb92ec7acf6575efa3. Thanks a lot for it!

Some tests still don't work, but that happened before too. If you mind, try for example:
[0] - Interactive Tests
[1] - 8 bits per pixel modes
[1] - 640x480x8, 8 page, Banked+Linear
[1] - Linear framebuffer mode
The test after "Wide DAC test" starts drawing, but never terminate. I have to abort DOSEmu2, as I can't exit normally the "vbetest".

In my eyes, this issue can be closed if no one cares about the failing tests from "vbetest".

**Comment by stsp** [comment]
Good to know, thanks!
This means there was no actual regression
with the new code, and the effect of the bug
is minimal: it just affects some 32bit dos-extended
programs.
This ticket is already closed, but you can open
a new one. :)
