### ISSUE TITLE
Application crash under PC-DOS 3.00 ( -td only)

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#421]
I have a strange application crash that occurs under PC-DOS 3.00 when using the -td option. The same program runs successfully in an SDL window.
![pc-dos-application-crash-td](https://user-images.githubusercontent.com/220835/29005130-6501a7e4-7acc-11e7-935e-ea4ddb72af5a.png)
![pc-dos-application-crash-sdl](https://user-images.githubusercontent.com/220835/29005134-708870f2-7acc-11e7-88c1-c965b75b73eb.png)

I've attached the log, but I'm not sure what debug options to specify, for now it's +dRW
[test_log.zip](https://github.com/stsp/dosemu2/files/1203234/test_log.zip)

**Comment by stsp** [comment]
Try disabling `$_umb_a0` or removing
`DOS=HIGH,UMB`?

**Comment by andrewbird** [comment]
I have no ~DOS=HIGH,UMB~ so I tried setting ~$_umb_a0=(off)~ but I still get the crash. Any ideas on how to debug this?

**Comment by stsp** [comment]
Try adding `M` to the log.
Since `lfntest.exe` does not use our `msdos.c`,
things should not be too convoluted on DPMI front.

**Comment by andrewbird** [comment]
Here's the new log [test_log.zip](https://github.com/stsp/dosemu2/files/1204155/test_log.zip)

**Comment by stsp** [comment]
How about also attaching a good log?
Also if you attach dosdebug, it will stop
on an exception and you can see what
instruction have crashed.

**Comment by stsp** [comment]
Does it work fine with `-t`?

**Comment by stsp** [comment]
It seems PSP:2Ch contains 0 in "bad"
case and "0xffff" in good case. Could you
check if this is true?
I don't know how it matters though.
But you can try to rewrite the value and
see if something changes.

**Comment by andrewbird** [comment]
Yes, it works fine with `-t`

How should I change the value in PSP:2Ch?

**Comment by andrewbird** [comment]
I wonder if it's related to use of dos_get_psp() as it relies upon sda_cur_psp() and in turn sda_cur_psp_off which is different in PC-DOS 3.00?

**Comment by stsp** [comment]
Exactly!

**Comment by stsp** [comment]
So do we just get the wrong PSP address?

**Comment by andrewbird** [comment]
Maybe so and it could be just plain luck that -t and -S work. I'll dump and examine the sda from PC-DOS 3.00 again.

**Comment by stsp** [comment]
> Maybe so and it could be just plain luck that -t and -S work.

That's what I think too, because `0xffff` does
not look like a valid env sel by any means.
It just does not lead to NULL ptr deref, this is
all the difference.

**Comment by andrewbird** [comment]
Yep, that's the problem. The PSP segment is at a different offset in the SDA. I've found it now, but since the value came from the apparently 'fixed to work with v3.0 DOS' phantom redirector, i have to check some other values too!

**Comment by stsp** [comment]
Please attach the log btw.
I'll see how the values are now.

**Comment by andrewbird** [comment]
Here are the (old lucky -t and new) [logs.zip](https://github.com/stsp/dosemu2/files/1206090/logs.zip)

I think the salient part is:
~~~
dpmi_sel()=97 CS=a7 DS=af SS=af ES=b7
DPMI: convert seg 0x9b3 to desc
DPMI: SEG at base=0x9b30 not found, allocate a new one
~~~

whereas even with -t version
~~~
dpmi_sel()=97 CS=a7 DS=af SS=af ES=b7
DPMI: convert seg 0xffff to desc
DPMI: SEG at base=0xffff0 not found, allocate a new one                                 
~~~

**Comment by stsp** [comment]
Yes, this looks like a valid env because
DS is 0x9cd, which is just a bit higher than
env.
