### ISSUE TITLE
HMA unavailable after a reboot from within DOSemu

### ISSUE THREAD

**Issue by jharrison022** [stsp/dosemu2#427]
Rebooting DOSemu with Ctrl-Alt-Del from within DOSemu causes the HMA to be unavailable when DOS restarts.

http://home.ix.netcom.com/~jjingber/boot.log.bz2

**Comment by stsp** [comment]
It appears also XMS and UMBs were unavailable...
Everything is now fixed.
Lets say reboot was not supported by dosemu2
till that point. :)
