### ISSUE TITLE
Keyboard detection in X and SDL picking wrong keyboard

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#43]
I have a system using United Kingdom keyboard (GB keymap) with secondary US keymap installed, the dosemu.conf is default i.e. 'auto' but the detected keymap is US. Here is the salient portion of the boot log with -D+a

~~~
KBD: keyb_server_init()
KBD: setup_default_keytable: setting up table 35
setup_default_keytable: failed
10 keysyms per keycode not supported, set to 4
Attempting to match against "us"
matches=46, mismatches=11, seq=45, score=45
Attempting to match against "us"
matches=51, mismatches=6, seq=50, score=75
Attempting to match against "finnish"
matches=32, mismatches=25, seq=31, score=-38
Attempting to match against "finnish"
matches=35, mismatches=22, seq=34, score=-22
Attempting to match against "finnish-latin1"
matches=32, mismatches=25, seq=31, score=-38
Attempting to match against "finnish-latin1"
matches=34, mismatches=23, seq=33, score=-27
Attempting to match against "uk"
matches=39, mismatches=18, seq=39, score=4
Attempting to match against "uk"
matches=48, mismatches=9, seq=47, score=57
Attempting to match against "de"
matches=31, mismatches=26, seq=28, score=-45
Attempting to match against "de"
matches=33, mismatches=24, seq=30, score=-33
Attempting to match against "de-latin1"
matches=30, mismatches=27, seq=27, score=-50
Attempting to match against "de-latin1"
matches=33, mismatches=24, seq=30, score=-33
Attempting to match against "fr"
matches=28, mismatches=29, seq=25, score=-62
Attempting to match against "fr"
matches=33, mismatches=24, seq=28, score=-35
Attempting to match against "fr-latin1"
matches=28, mismatches=29, seq=25, score=-62
Attempting to match against "fr-latin1"
matches=32, mismatches=25, seq=27, score=-41
Attempting to match against "dk"
matches=32, mismatches=25, seq=31, score=-38
Attempting to match against "dk"
matches=35, mismatches=22, seq=34, score=-22
Attempting to match against "dk-latin1"
matches=32, mismatches=25, seq=31, score=-38
Attempting to match against "dk-latin1"
matches=34, mismatches=23, seq=33, score=-27
Attempting to match against "dvorak"
matches=40, mismatches=17, seq=24, score=11
Attempting to match against "dvorak"
matches=51, mismatches=6, seq=33, score=75
Attempting to match against "sg"
matches=33, mismatches=24, seq=30, score=-34
Attempting to match against "sg"
matches=33, mismatches=24, seq=29, score=-35
Attempting to match against "sg-latin1"
matches=31, mismatches=26, seq=28, score=-44
Attempting to match against "sg-latin1"
matches=32, mismatches=25, seq=28, score=-40
Attempting to match against "keyb-no"
matches=32, mismatches=25, seq=31, score=-38
Attempting to match against "keyb-no"
matches=34, mismatches=23, seq=33, score=-27
Attempting to match against "no-latin1"
matches=32, mismatches=25, seq=31, score=-38
Attempting to match against "no-latin1"
matches=34, mismatches=23, seq=33, score=-27
Attempting to match against "sf"
matches=33, mismatches=24, seq=30, score=-34
Attempting to match against "sf"
matches=33, mismatches=24, seq=29, score=-35
Attempting to match against "sf-latin1"
matches=31, mismatches=26, seq=28, score=-44
Attempting to match against "sf-latin1"
matches=31, mismatches=26, seq=28, score=-45
Attempting to match against "es"
matches=31, mismatches=26, seq=30, score=-44
Attempting to match against "es"
matches=36, mismatches=21, seq=35, score=-16
Attempting to match against "es-latin1"
matches=31, mismatches=26, seq=30, score=-44
Attempting to match against "es-latin1"
matches=33, mismatches=24, seq=32, score=-33
Attempting to match against "be"
matches=31, mismatches=26, seq=26, score=-45
Attempting to match against "be"
matches=33, mismatches=24, seq=27, score=-35
Attempting to match against "po"
matches=33, mismatches=24, seq=31, score=-33
Attempting to match against "po"
matches=36, mismatches=21, seq=34, score=-15
Attempting to match against "it"
matches=34, mismatches=23, seq=32, score=-26
Attempting to match against "it"
matches=35, mismatches=22, seq=33, score=-21
Attempting to match against "sw"
matches=32, mismatches=25, seq=31, score=-38
Attempting to match against "sw"
matches=34, mismatches=23, seq=33, score=-27
Attempting to match against "hu"
matches=13, mismatches=44, seq=12, score=-152
Attempting to match against "hu"
matches=31, mismatches=26, seq=28, score=-45
Attempting to match against "hu-cwi"
matches=17, mismatches=40, seq=16, score=-128
Attempting to match against "hu-cwi"
matches=31, mismatches=26, seq=28, score=-45
Attempting to match against "hu-latin2"
matches=13, mismatches=44, seq=12, score=-152
Attempting to match against "hu-latin2"
matches=31, mismatches=26, seq=28, score=-45
Attempting to match against "jp106"
matches=39, mismatches=18, seq=38, score=3
Attempting to match against "jp106"
matches=41, mismatches=16, seq=39, score=15
Attempting to match against "pl"
matches=37, mismatches=20, seq=36, score=-9
Attempting to match against "pl"
matches=51, mismatches=6, seq=50, score=75
Attempting to match against "hr-cp852"
matches=19, mismatches=38, seq=17, score=-116
Attempting to match against "hr-cp852"
matches=34, mismatches=23, seq=31, score=-27
Attempting to match against "hr-latin2"
matches=19, mismatches=38, seq=17, score=-116
Attempting to match against "hr-latin2"
matches=34, mismatches=23, seq=31, score=-27
Attempting to match against "cz-qwerty"
matches=13, mismatches=44, seq=12, score=-153
Attempting to match against "cz-qwerty"
matches=31, mismatches=26, seq=29, score=-46
Attempting to match against "cz-qwertz"
matches=13, mismatches=44, seq=11, score=-153
Attempting to match against "cz-qwertz"
matches=31, mismatches=26, seq=27, score=-46
Attempting to match against "ru"
matches=13, mismatches=44, seq=13, score=-153
Attempting to match against "ru"
matches=15, mismatches=42, seq=15, score=-141
Attempting to match against "tr"
matches=30, mismatches=27, seq=30, score=-51
Attempting to match against "tr"
matches=31, mismatches=26, seq=31, score=-45
Attempting to match against "keyb-user"
matches=46, mismatches=11, seq=45, score=45
Attempting to match against "keyb-user"
matches=51, mismatches=6, seq=50, score=75
Using closest match (us) for scan/virtual codes mapping.
CONF: detected layout is "us"
CONF: detected alternate layout: us
rules->trans_rules.rule_arr[j].rule_map:
~~~

I'm not sure how the detection works exactly, but because of the line
~~~
10 keysyms per keycode not supported, set to 4
~~~
I tried increasing the array lengths to 10 and altering the if accordingly and it almost worked. I got 'BE' primary with 'US' secondary, but obviously it's not correct.

Is there any way of reading the keyboard type from SDL or X instead and does the keymap have to be set at Dosemu startup i.e. could it be switchable from the desktop like most X applications?

**Comment by stsp** [comment]
> Is there any way of reading the keyboard type from SDL or X instead and does the keymap have to
> be set at Dosemu startup i.e. could it be switchable from the desktop like most X applications?

dosemu is not the most X applications.
While "most X applications" are happy with the
high-level keyboard abstractions that allow them
to work with unicode, dosemu should instead
reverse them all and get the initial scan code,
which is highly obscured.
Since this code was obviously stolen from wine,
I can't properly comment. My suggestion would
be for you to check the wine code and see if they
have updated it in any way. It is a bit strange that
you have 10 keysyms per keycode, as if you have
5 layouts defined, not 2.

**Comment by andrewbird** [comment]
Hi,
  So on your system 'XGetKeyboardMapping() returns 4 or less for ksyms_per_keycode? The wine code still has the same 4 ksym limit. The extra ksyms seem to be for superscript etc, using Alt-Gr.

This looks pretty ordinary to me.
~~~
ajb@polly:~$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     gb,us
variant:    ,
options:    grp:shift_caps_toggle
~~~

To me the problem looks like it's the order that the keysyms come out from the Xserver. For instance when the code is trying to match the '2' key in the UK keymap I see

~~~
for keycode  11,   32   22   40, got   32   22   32   40
~~~

We are looking for 2"@ but get 2"2@ it's as if there's another modifier keysym column


I can tweak the code to work for me by looking for the dosemu keysym in any position in the X server keysym e.g.
~~~
key:   3 score  4 for keycode  11,   32   22   40, got   32   22   32   40
~~~
But I'm not sure I have understood the problem properly.

**Comment by stsp** [comment]
> So on your system 'XGetKeyboardMapping() returns 4 or less for ksyms_per_keycode?

No, you are right: 10 also. I didn't know that.

Please see here about the possible reorderings:
https://tronche.com/gui/x/xlib/input/keyboard-encoding.html

What I think is that perhaps everything will work
properly if you have US primary and GB secondary.
Can you try?

**Comment by andrewbird** [comment]
I have to go out for a while, so I won't get the chance to try this until later. In the meantime I can say that adding another keyboard input method (FR) increased ksyms_per_keycode to 15. I'm experimenting with an alternative xkb method at the moment.

**Comment by stsp** [comment]
So our code seem to do the following:
it first compares 4 keysyms to find a primary
keymap, and then compares only 2 higher
keysyms of the same 4 to try find a sec keymap.
This properly complies to the above URL, but
in reality we seem to have 5 keysyms per group
instead of 2. I don't know how to map that
knowledge to the above xlib programming manual.
Unless you come up with the brightest ideas,
lets say this is not a 2.0 material.

**Comment by andrewbird** [comment]
Hi yes I doubt it's for 2.0. I have been playing around and have xkb getting the available layouts and also active layout now, but I'm trying to understand what Dosemu uses the alternate keymapping for i.e.
~~~
CONF: detected layout is "uk"                                                   
CONF: detected alternate layout: us                                             
~~~
When would a DOS application use the 'us' layout, is it selectable with a hotkey or suchlike?

**Comment by stsp** [comment]
I think you can simply adapt the existing code
if you manage to get the number of keysyms
per group.

> When would a DOS application use the 'us' layout, is it selectable with a hotkey or suchlike?

It is selectable an X way. Nothing special from
DOS side is needed. dosemu translates the
received keysym not only to the raw keyboard
scancode, but also to the set of modifiers and
the codepage char which goes to the bios buffer.

**Comment by andrewbird** [comment]
So that being said, remember I'm playing ;-) , if my available layouts were:
(gb, us, fr) and gb was active - I could make gb==primary and us==alternate. Since Dosemu evaluates the layout on startup, presumably the alternative layout couldn't be used without a Dosemu restart, even if I selected it in X?

**Comment by stsp** [comment]
dosemu supports exactly one alternate layout
at a moment AFAIK. So if you ask about fr layout
from the example above - yes, perhaps it will
not be usable. But DOS only supports 2-layout
codepages (256 chars) anyway, so it would
probably be useless to rewrite dosemu code to
support 3 layouts if they will not properly map
to the DOS codepage.

**Comment by stsp** [comment]
Or maybe you can map all 3 layouts to the
single codepage, if the the char sets are compatible.
And the gb, us, fr are likely compatible, so maybe
if you try very hard, you'll make it possible to use
more that 2 layouts... I am not really an i18n expert.

**Comment by andrewbird** [comment]
My example above attempted to make the case that if xkb could always determine the active keyboard layout at Dosemu startup, there would never be a case where the alternate layout was used.

Incidentally xkb seems to support notification events for changes, but I'm not sure how Dosemu could cope with changing layout on the fly.

So does this need the KEYB.COM loaded with the correct two letter keyboard code to work properly? I think I need to read up on how keyboards and codepages interact, as I had been treating them as two totally separate things.

**Comment by stsp** [comment]
Are you saying that with XKB you can't
determine all layouts at startup, but only the
active one? Is this true?

No, keyb.com is not needed because you
switch the layouts the X way, as I already
mentioned. All you need is to load the proper
codepage and font (display.sys/mode.com)

Keyboard and codepage interract in the way
that when you press a key, the appropriate
symbol should be displayed. For that dosemu
should convert the unicode symbol to the
codepage, AFAIK. I am not an i18n expert,
this is just my understanding of the subject.

**Comment by stsp** [comment]
Please also note the $_internal_char_set.
It is a piece of puzzle that you've likely missed.
When it is set to match your codepage, the
proper conversion can be done.

**Comment by andrewbird** [comment]
With xkb, you can see all layouts that are configured up to 4 (Xserver compile time value) and also which one of the layouts is currently active. The old X11_detect code assumes that the first pair of keysyms in each row is the active one, but I'm not sure that is true since when I changed the active one, the order didn't change on my system.

As an aside, in non X environments e.g. console and dumb terminal, how is the alternate layout selected?

That's good about keyb.com, it's one less complication.

**Comment by andrewbird** [comment]
This is an interesting read
http://www.freedos.org/technotes/technote/txt/141.txt

**Comment by stsp** [comment]
> With xkb, you can see all layouts that are configured up to 4 (Xserver compile time value)
> and also which one of the layouts is currently active. 

That's fine.
Is there also a way to get keysyms_per_keycode for every
layout? This looks like it would be enough.

> As an aside, in non X environments e.g. console and dumb terminal, how is the alternate
> layout selected?

From tty it can AFAIK read the scancode->keysym mapping,
and build a keymap from that. You don't need to even select
any of the dosemu builtin keymaps then. But X does not
reveal the scancode, AFAIK that's the problem.

> That's good about keyb.com, it's one less complication.

You _can_ use keyb.com, but then you loose an ability
of switching an X way.

> This is an interesting read

Too long. :) I am sure you'll explain to me all the new
findings from that doc. :)

**Comment by andrewbird** [comment]
Hi,
Here's a link about the differences with XKB and pure X11, but it has a nice table for what's returned in pure X11.
http://pascal.tsu.ru/en/xkb/internals.html#types
I think what we have for comparing just the first four values is OK as long as we don't try to evaluate anything other than layout1 unshifted/shifted and layout2 unshifted/shifted. 

My problem seems to be that the ALT keymap seems to be compared during detection with the alternative layout. I think there's some confusion there, for instance testing with the keycode 11
~~~
 key: 3 score -1 for keycode 11, 32 22 40, got 32 22 32 40
~~~
Dosemu has 
unshifted map = 32
shifted map = 22
alt map = 40

X returns
layout 1 unshifted map 32
layout 1 shifted map 22
layout 2 unshifted map 32
layout 2 shifted map 40

I suggest that Dosemu alt_map != layout2, but the detection logic compares lkey[2] to ckey[2] i.e. Dosemu alt modified layout1 key to X unshifted layout2 key

Now for a little test with 'xev -event keyboard'

With layout 1 selected in X and keycode 11
~~~
unshifted
state 0x0, keycode 11 (keysym 0x32, 2), same_screen YES

shifted
state 0x1, keycode 11 (keysym 0x22, quotedbl), same_screen YES

alt
state 0x8, keycode 11 (keysym 0x32, 2), same_screen YES,

ctrl
state 0x4, keycode 11 (keysym 0x32, 2), same_screen YES,

altgr
state 0x80, keycode 11 (keysym 0xb2, twosuperior), same_screen YES,
~~~

So I think the UK alt map is wrong, at least in X, but I don't think it should compared against the alternate layout anyway.

**Comment by stsp** [comment]
> I think what we have for comparing just the first four values is OK as long

Right, this is exactly what I was saying above.

> but I don't think it should compared against the alternate (layout2) anyway.

I tend to agree, but for the following:
- This code is stolen from wine, so that should be verified with wine.
- This works fine with the way the tty keytable is evaluated, AFAIK.
But the code in keymaps.c:2422 under "if (altgr_lock_present)"
should handle the tty case fine even if you don't compare the alt
layout in X detector.

So I'd say please make a pull requests so that we can have a
look into an actual patches.

**Comment by andrewbird** [comment]
Yes, you were right. I think I started out with the premise that alt_map data was in the four values as it just so happened that in dosemu's uk alt_map keycode 11 == '@' and that was the code in the shifted layout2 (US). That was wrong and I think the alt_map shouldn't be tested to detect the keyboard maping. I'll code something up that uses xkb (if available), since the X11 data from XGetKeyboardMapping() is not changing or reordering with desktop keyboard switching.

**Comment by stsp** [comment]
Could you please elaborate on the grouping?
If we have 5 keysyms per keycode instead of 2, and
then we compare to 4 keysyms, what 4 keysyms are
those? Are they 4 from first layout's 5? Or?

> since the X11 data from XGetKeyboardMapping() is not changing or
> reordering with desktop keyboard switching. 

Why should it? I dont understand. If it would, our detection
would break.

**Comment by andrewbird** [comment]
In Xkb terms group == layout.

In my tests, and also the http://pascal.tsu.ru/en/xkb/internals.html#types document suggests, that although we have 5 keysyms per keycode for each layout the XGetKeyboardMapping() still returns the following for compatibility with non xkb clients
~~~
layout 1 unshifted keysym, layout 1 shifted keysym, layout 2 unshifted keysym, layout 2 shifted keysym
~~~
My first patch with xkb will avoid using that data and instead use XkbKeycodeToKeysym(). Later I hope to figure out the logic with XGetKeyboardMapping() further value ordering if necessary

Well on my desktop (Lubuntu) I can select keyboard with LXPanel (xkb based) to 'fr' from a possible currently defined 3 (gb,us,fr) but if I run dosemu I get
~~~
CONF: detected layout is "us"                                                   
CONF: detected alternate layout: us                                             
~~~
The French layout is not present in XGetKeyboardMapping() first four fields of row, so there is no possibility of it being detected. I had hoped that for compatibility the Xserver would have reordered the active layout into the first two fields. Alternatively using xkb you can determine the active layout and then ask for the keysym from that layout with XkbKeycodeToKeysym(). 

It's crossed my mind that you must be aware of another non xkb method of switching X between primary and alternate layouts. Do you know of such a thing?

**Comment by stsp** [comment]
> XGetKeyboardMapping() still returns the following for compatibility with non xkb clients

But where are 3, 4, 5? In what order they are returned,
and started from what position?

> The French layout is not present in XGetKeyboardMapping() first four fields of row, so there is no
> possibility of it being detected. I had hoped that for compatibility the Xserver would have reordered
> the active layout into the first two fields.

But that looks wrong.
Please note that every window can have its own
active layout. When dosemu window is created,
it gets the default layout. If dosemu will have different
keymaps depending on that layout was active on the
xterm window you were starting dosemu from, then
it will be a total crap IMHO.

**Comment by andrewbird** [comment]
>But where are 3, 4, 5? In what order they are returned,
>and started from what position?

I don't know yet, I have to experiment

>Please note that every window can have its own
active layout. When dosemu window is created,
it gets the default layout.

I presume this is so for Dosemu as we only do keyboard detection at startup. For other X clients I'm not sure what mechanism is used. For instance I open an xterm with UK keyboard, I type 'mmmm' then switch to FR and type the same key, I now see ',,,,' appearing. This is different behaviour to an X Dosemu window where the characters being shown with each keypress do not change.

I did a similar test with plain terminal using xev -event keyboard which suggests that the active layout is global rather than per window.
~~~
KeyPress event, serial 25, synthetic NO, window 0x2800001,
    root 0x274, subw 0x2800002, time 16390796, (38,41), root:(39,531),
    state 0x0, keycode 58 (keysym 0x6d, m), same_screen YES,
    XLookupString gives 1 bytes: (6d) "m"
    XmbLookupString gives 1 bytes: (6d) "m"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2800001,
    root 0x274, subw 0x2800002, time 16390892, (38,41), root:(39,531),
    state 0x0, keycode 58 (keysym 0x6d, m), same_screen YES,
    XLookupString gives 1 bytes: (6d) "m"
    XFilterEvent returns: False

KeymapNotify event, serial 28, synthetic NO, window 0x0,
    keys:  116 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeymapNotify event, serial 28, synthetic NO, window 0x0,
    keys:  116 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeymapNotify event, serial 28, synthetic NO, window 0x0,
    keys:  116 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyPress event, serial 28, synthetic NO, window 0x2800001,
    root 0x274, subw 0x2800002, time 16397948, (56,34), root:(57,524),
    state 0x4000, keycode 58 (keysym 0x2c, comma), same_screen YES,
    XKeysymToKeycode returns keycode: 59
    XLookupString gives 1 bytes: (2c) ","
    XmbLookupString gives 1 bytes: (2c) ","
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2800001,
    root 0x274, subw 0x2800002, time 16398044, (56,34), root:(57,524),
    state 0x4000, keycode 58 (keysym 0x2c, comma), same_screen YES,
    XKeysymToKeycode returns keycode: 59
    XLookupString gives 1 bytes: (2c) ","
    XFilterEvent returns: False
~~~

I think for Dosemu to behave the same way it would have to listen to xkb events and redetect the keymap if the active one were changed. I'm not sure that's worthwhile because as you say the internal charset needs to match etc. I think I'd be happy if I had FR active and at Dosemu startup it was detected as FR. If subsequently the global setting were changed to GB and Dosemu continued to work in French that would be fine.

**Comment by stsp** [comment]
> I presume this is so for Dosemu as we only do keyboard detection at startup.
> For other X clients I'm not sure what mechanism is used.

They don't care about the layout.
All they need is a unicode keysyms.
They don't need the scancode & modifiers.

> I did a similar test with plain terminal using xev -event keyboard which suggests
> that the active layout is global 

This is configurable.
I always prefer per-window.

> I think for Dosemu to behave the same way it would have to listen to xkb events
> and redetect the keymap if the active one were changed.

I don't see the point re-detecting when active changed.
The active layout is indicated in the X keyboard event IIRC,
so you don't need to re-detect every time.
What you want is probably to just support more than 2 layouts.

**Comment by andrewbird** [comment]
I just read the whole array row at the keycode just listed
~~~
key: 58 - got   6d   4d   6d   4d   b5   ba   2c   3f  301  30b ffff ffff ffff ffff ffff
[0] unshifted layout1
[1] shifted layout1
[2] unshifted layout2
[3] shifted layout2
[4] unknown
[5] unknown
[6] unshifted layout3
[7] shifted layout3
[8] unknown
[9] unknown
[10..14] unknown
~~~

and without the charset_to_unicode() conversion
~~~
key: 58 - got   6d   4d   6d   4d   b5   ba   2c   3f fe51 fe59    0    0    0    0    0
0] unshifted layout1
[1] shifted layout1
[2] unshifted layout2
[3] shifted layout2
[4] unknown
[5] unknown
[6] unshifted layout3
[7] shifted layout3
[8] altgr unshifted layout3
[9] altgr shifted layout3
[10..14] unknown
~~~

**Comment by andrewbird** [comment]
>They don't care about the layout.
>All they need is a unicode keysyms.
>They don't need the scancode & modifiers.
Yep, understood

>This is configurable.
>I always prefer per-window.
Ok, this is unknown to me. Can you tell me how to configure layout per window please?

>I don't see the point re-detecting when active changed.
Yes, agreed

>The active layout is indicated in the X keyboard event IIRC,
Will look into that

>so you don't need to re-detect every time.
>What you want is probably to just support more than 2 layouts
Yes, indeed

**Comment by andrewbird** [comment]
I found this, which seems to implement what you suggested by switching the global layout every time the active window is changed. I suppose something similar could be implemented in the window manager, but for now it looks like the Xserver has only one active keyboard layout
http://sourceforge.net/p/perwindowlayout/code/ci/master/tree/perWindowLayoutD.cpp

**Comment by stsp** [comment]
Oh c'mon.
I use that functionality for maybe 20 years or so.
Go to keyboard preferences, go into Layouts tab
and select the option you need.

**Comment by andrewbird** [comment]
Hi I found it in LXPanel, it's using xkb to switch the global keyboard layout. I wrote a test program to query xkb active keyboard and ran it repeatably in a while loop in one window. Then switched between two other windows, one configured for FR one for GB. The active layout in the test window was changed as below:
~~~
active layout is 0
active layout is 0
active layout is 2
active layout is 2
active layout is 0
active layout is 0
active layout is 2
active layout is 2
active layout is 0
active layout is 0
~~~

So you see the layout is not per window, it's global and just switched as you focus each.

**Comment by stsp** [comment]
What does this change?
This is an implementation detail.
If you force dosemu to detect the layout
that is currently active (be it global or specific
to dosemu window), you get problems depending
on whether the per-window layout is enabled or
not, no matter how it is really implemented.
Essentially, I see no reason why the active layout
should affect the program's startup anyhow.

**Comment by andrewbird** [comment]
Yes, it's an implementation detail but it freaked me a little when you said layout could be per window and I thought how will I cope with that! Knowing that it doesn't some other mechanism will mean that it makes no difference to Dosemu whether layout is set per window or globally.

Well I think at Dosemu startup the active Xkb keymap needs to be used to initialise Dosemu's own keymapping, or else how can it ever use the correct keycodes? I sense I'm not *getting* the method Dosemu uses to switch between primary and alternative keymaps? My assumption is that the Dosemu primary keymap would be selected by sensing which X keymap is active at Dosemu startup. Is that not the case?

**Comment by stsp** [comment]
> I sense I'm not getting the method Dosemu uses to switch between primary
> and alternative keymaps?

The current group is coded in the XKeyEvent.state.
But you don't need to parse it manually; the functions
like XkbLookupKeySym() parse it.

> My assumption is that the Dosemu primary keymap would be selected by
> sensing which X keymap is active at Dosemu startup. Is that not the case? 

Of course not.
I don't understand why the active layout at startup
bothers you at all.

**Comment by andrewbird** [comment]
Ok, can I take a step back from the code and talk about how a user might use different keyboard mapping in dosemu?
Say I have a UK physical keyboard with active X layout of UK and secondary layout of US. Dosemu starts up and autodetects UK primary and US secondary keymaps. As a user how would I press a key and it send a keycode from the US set which dosemu maps into a keysym from the US keymap? I had been working on the assumption that the active X layout would have to be changed to US to do that.




Sent from Samsung tablet

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 13/07/2015  22:13  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk> 
Subject Re: [dosemu2] Keyboard detection in X and SDL picking wrong keyboard
  (#43) 
 
I sense I'm not getting the method Dosemu uses to switch between primary
and alternative keymaps?

The current group is coded in the XKeyEvent.state.
But you don't need to parse it manually; the functions
like XkbLookupKeySym() parse it.

My assumption is that the Dosemu primary keymap would be selected by
sensing which X keymap is active at Dosemu startup. Is that not the case?

Of course not.
I don't understand why the active layout at startup
bothers you at all.

**Comment by stsp** [comment]
How does this relate to the active layout _at startup_?
Surely you have to switch the proper layout before you can type...

**Comment by andrewbird** [comment]
Hi, sorry it took me a while to get back to this. Yes I think I understand what you mean. Anyway back to the problem of detection of the primary keyboard. My UK one is incorrectly detected as US normally, but if I prevent the detection routine from checking the alt map it is detected correctly.
```C
          //lkey[2] = keysym_to_unicode(kt->alt_map[key]);                      
          lkey[2] = U_VOID;                                                     
```

 I wrote a little test program to show what I think is going on.
~~~
keysyms_per_keycode = 7
keycode 12 X =   33(             3), map =   33(             3), map2 =   33(             3), Xkb =   33(             3)
keycode 12 X =   a3(      sterling), map =   a3(      sterling), map2 =   a3(      sterling), Xkb =   a3(      sterling)
keycode 12 X =    0(        (null)), map =   33(             3), map2 =   33(             3), Xkb =   b3( threesuperior)
keycode 12 X =    0(        (null)), map =   a3(      sterling), map2 =   a3(      sterling), Xkb =   a3(      sterling)
keycode 12 X =   a3(      sterling), map =   b3( threesuperior), map2 =   b3( threesuperior), Xkb =    0(        (null))
keycode 12 X =    0(        (null)), map =   a3(      sterling), map2 =   a3(      sterling), Xkb =    0(        (null))
keycode 12 X =    0(        (null)), map =   b3( threesuperior), map2 =   b3( threesuperior), Xkb =    0(        (null))
~~~

That's with just one layout defined (UK), note there are seven keycodes per keysym. And specifically offsets 2 and 3 from XGetKeyMapping in each row don't match either XkbKeycodeToKeySym() or the actual character that it produces in a terminal.
~~~
333£££³³³£££
~~~

See that the results from XkbKeycodeToKeySym() are respectively, Unshifted, Shifted, AltGr, AltGrShifted.

Here is the test program
```C
#include <stdio.h>                                                              
                                                                                
                                                                                
#include <X11/X.h>                                                              
#include <X11/Xlib.h>                                                           
#include <X11/keysym.h>                                                         
                                                                                
#include <X11/XKBlib.h>                                                         
                                                                                
                                                                                
KeySym XKeymapKeycodeToKeysym(KeySym *map, int width, int min, int keycode, int index) {
        int offset = ((keycode-min) * width) + index;                           
        return map[offset];                                                     
}                                                                               
                                                                                
                                                                                
KeySym XKeymapKeycodeToKeysym2(Display *display, int keycode, int index) {      
        int width = 0;                                                          
                                                                                
        KeySym *map = XGetKeyboardMapping(display, keycode, 1, &width);         
        KeySym ret = (index <= width) ? map[index] : 0;                         
        XFree(map);                                                             
                                                                                
        return ret;                                                             
}                                                                               
                                                                                
int main () {                                                                   
                                                                                
        int min_keycode, max_keycode;                                           
                                                                                
        int keysyms_per_keycode, i;                                             
                                                                                
        Display *display = XOpenDisplay(":0");                                  
        if (display == NULL) {                                                  
                printf("cant open display\n");                                  
                return 1;                                                       
        }                                                                       
                                                                                
        XDisplayKeycodes(display, &min_keycode, &max_keycode);                  
        printf("keycodes min = %d, max = %d\n", min_keycode, max_keycode);      
                                                                                
        KeySym *kmap = XGetKeyboardMapping(display,                             
                        min_keycode,                                            
                        max_keycode + 1 - min_keycode,                          
                        &keysyms_per_keycode);                                  
                                                                                
        printf("keysyms_per_keycode = %d\n", keysyms_per_keycode);              
                                                                                
        int kcode = 12;                                                         
                                                                                
        for (i=0; i < keysyms_per_keycode;i++) {                                
                KeySym k0, k1, k2, k3;                                          
                k0 = XKeycodeToKeysym(display, kcode, i);                       
                k1 = XKeymapKeycodeToKeysym(kmap, keysyms_per_keycode, min_keycode, kcode, i);
                k2 = XKeymapKeycodeToKeysym2(display, kcode, i);                
                k3 = XkbKeycodeToKeysym(display, kcode, 0, i);                  
                                                                                
                char *c0, *c1, *c2, *c3;                                        
                c0 = XKeysymToString(k0);                                       
                c1 = XKeysymToString(k1);                                       
                c2 = XKeysymToString(k2);                                       
                c3 = XKeysymToString(k3);                                       
                                                                                
                printf("keycode %d X = %4x(%14s), map = %4x(%14s), map2 = %4x(%14s), Xkb = %4x(%14s)\n",
                                kcode, (int)k0, c0, (int)k1, c1, (int)k2, c2, (int)k3, c3);
        }                                                                       
                                                                                
        return 0;                                                               
}                                                                               
```
Note that XKeycodeToKeySym() differs from XGetKeymap() result, which is why it was deprecated.

So it would seem that either not checking the Alt map or finding out which proper offset the value is at would seem to be the correct fix for plain X, or switching to XkbKeycodeToKeysym() if that's available. What do you think?

**Comment by stsp** [comment]
I think dealing with Alt map and finding its
location is a waste of time. Likely even the
shifted map can safely be bypassed - we
only need to compare the plain map. At least
I believe this will hold for the European layouts.
Comparing Alt map was likely done for the
layouts read from tty, but the relevant code
suggests it is already prepared to not compare
the Alt layout either.
So if you cook the patch that compares only
2 layouts per map instead of 4 per map, that
would be nice. Of you can explore the approach
of comparing just 1 layout per map, to get some
simpler code.

**Comment by stsp** [comment]
You should refer the tickets in the patch, then
they'll auto close.
