### ISSUE TITLE
Int 14h function 1Bh returns pointer to wrong ID string after reboot

### ISSUE THREAD

**Issue by jharrison022** [stsp/dosemu2#432]
Int14h function 1Bh returns the location of the FOSSIL driver ID string in a data structure.  When DOSemu is started, the string is:

"dosemu FOSSIL emulator".

When DOSemu is rebooted from within DOSemu (Ctl-Alt-Del), the string is

"$SUP"

**Comment by andrewbird** [comment]
@stsp Perhaps we need to add `com[num].fossil_active = FALSE;` to ser_reset_dev()?

I don't know how to test this, hence no PR :smile:

**Comment by jharrison022** [comment]
This is with FOSSIL.COM loaded (from DOSemu).

**Comment by andrewbird** [comment]
I see a slightly different effect, for me fossil.com reports that it's already installed. I think it's to do with the `fossil_tsr_installed` variable that the TSR checks via helper not being reset on reboot.

**Comment by stsp** [comment]
Thanks! :)

**Comment by andrewbird** [comment]
@jharrison022 Any chance you can test the branch [fossil](https://github.com/andrewbird/dosemu2/tree/fossil), please?

**Comment by stsp** [comment]
Andrew, I think for the very basic setup you
can use DOS navigator (it has terminal tool)
and pty link established with socat.
See #390 for the socat setup example.

**Comment by jharrison022** [comment]
Will check the FOSSIL branch ASAP.

**Comment by jharrison022** [comment]
@andrewbird the fossil branch properly returns the driver ID after reboot.

**Comment by andrewbird** [comment]
@jharrison022 Thanks, that's good to know. 
@stsp I tested the PR #434 code with the procedure in #390 as you suggested (but I used Kermit 3.16b7). it worked fine even after reboot, but I didn't see any FOSSIL messages in the log except those generated when fossil.com was loaded. As a further test I tried Kermit without loading fossil.com first, and it seemed to function just as well, so I can't be sure the FOSSIL driver was even being used.

**Comment by andrewbird** [comment]
Do you have a link for 'DOS navigator', as I couldn't find it, hence the attempt with Kermit?

**Comment by stsp** [comment]
Why not?
https://www.ritlabs.com/en/products/dn/
Also you can easily find its successor NDN

**Comment by stsp** [comment]
It may be that freeware version has no terminal.
Try downloading non-freeware version by the same
link (https://www.ritlabs.com/download/dn/dn1502_1.zip)

**Comment by andrewbird** [comment]
No, the DN link you posted has the terminal, it's just the NDN I found myself that had no terminal.

**Comment by stsp** [comment]
Ah. IIRC this is because the sources
on ritlans.com are incomplete, they lack
terminal, so all forks lack it too.
In either case, by default fossil is disabled.
Make sure you have the right setup without
fossil first. Then in serial port configuration
you choose fossil and have a test-case.

**Comment by andrewbird** [comment]
Yes, I'm happy that DN works with dosemu's FOSSIL driver now, the boot.log snippet above shows the requests it makes.

**Comment by stsp** [comment]
Yeah, with unknown/unimplemented function errors. :(
So do you get bash interaction?

**Comment by andrewbird** [comment]
Yes it works fine, the char writes in the log are me typing '\nls\n' and the large read is the start of the listing. Actually it seems DN is ignoring the max fossil command specified in the FOSSIL header. It says 0x1b, but the log shows it tried 0x1f.

**Comment by andrewbird** [comment]
@jharrison022 Can I ask you what application program you were using to issue the FOSSIL 0x1b Status request please?
