### ISSUE TITLE
DOSemu becomes slow after certain programs return from a DOS shell

### ISSUE THREAD

**Issue by jharrison022** [stsp/dosemu2#433]
This happens with numerous programs, but the most consistent way to reproduce this is with Borland C 3.1.

Invoke the IDE with BC, then shell to DOS and return.  DOSemu will seem to be running at a much slower speed.

Something wrong is probably happening during the interrupt vector setup when invoking the shell, but it's not just a BC issue.  Other programs exhibit this behavior, but the Borland compilers do it 100% of the time.

http://home.ix.netcom.com/~jjingber/bc31.zip

**Comment by jharrison022** [comment]
http://home.ix.netcom.com/~jjingber/boot.log.4.bz2

**Comment by jharrison022** [comment]
Immediately after the shell is invoked from the IDE, this is observed

**Comment by stsp** [comment]
OK, silly bug, just a wrong assert.
Fixed.
