### ISSUE TITLE
Windows crashes dosemu

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#435]
with this error:
`ERROR: Coopthreads recursion depth exceeded, ints thread revect off=0`

**Comment by stsp** [comment]
Bisect shows this patch: 1428ed348.
But that's crazy as this patch was for
windows, so obviously windows worked
back then!

**Comment by stsp** [comment]
Indeed reverting that half year old patch
from current devel makes windows to work
again...
Wtf?

**Comment by stsp** [comment]
Looks like coopth breaks from some
interaction of revectored int28 and DPMI's
hw interrupt handling happening at the same
time. But don't tell me windows was broken
for half an year, because I tested it every day. :(

**Comment by jschwartzenberg** [comment]
I could also run Windows without problems usually. Quite often I run into a crash that I can't reproduce when I try it a second time though. Sometimes I have a crash for multiple times in a row with the same action and then later it starts to work and it works fine multiple times in a row. It seems there are some things going on that affect reproducibility.

**Comment by stsp** [comment]
Did you have windows crash or dosemu crash?
In my case it is a dosemu crash.
Was there any `Coopthreads` message on console
when the crash occurred? coopth is very vocal even
if no logging is enabled.

**Comment by jschwartzenberg** [comment]
I don't remember this unfortunately. I will update this issue when I run into such a situation again.

**Comment by stsp** [comment]
It appears the crash only happened with cpusim,
that's why it got unnoticed for so long.

**Comment by stsp** [comment]
Good that coopth catches such obscure bugs. :)
