### ISSUE TITLE
dosemu crashes X server when launced from openbox menu

### ISSUE THREAD

**Issue by PaulRaul** [stsp/dosemu2#44]
Latest dosemu2 crashes X on Debian Jessie if launched as a menu item from openbox.  The old dosemu 1.4 behaves as expected, as do other items launched from the menu.  X server is running on Intel G41 integrated graphics on a stock Optiplex 280.

To reproduce:

Add a new menu item with 'execute' and 'xdosemu' as the target and the launch dosemu from the openbox menu.  If the menu command is setup such as 'rxvt -e xdosemu', the terminal opens, and launches dosemu properly.  When full debugging is enabled, I get a log file which ends in ~4MB of this:

VGAEmu: vga_emu_protect_page: 0xbf = RW (unchanged)
VGAEmu: vga_emu_protect: error = 0, region = 0, page = 0x7 --> map_addr = 0xbf, prot = RH

Nothing else I can see in the X logs seems to give any indication of any errors.  Willing to help debug this, but I'm not that familiar with dosemu internals yet.

Paul

**Comment by stsp** [comment]
xdosemu is deprecated, please use 'dosemu' to start.
I'll just remove it.
As to the problem: please make it easier to reproduce.
For example can you reproduce the problem if you just
type 'dosemu' under xterm?
Please also try 'dosemu -S'

**Comment by PaulRaul** [comment]
Maybe some progress --

Running dosemu from a regular xterm (or any other term) works perfectly - this problem only seems to occur if launched from the openbox menu.

Running dosemu -S from the openbox menu does indeed prevent the crash, however, I'm not able to use the packet driver interface via tap when I start dosemu in this mode.  My user is has access to the tap device.

**Comment by stsp** [comment]
Then please fill a but report to openbox or X, as
obviously I can't help with that problem.

As for tap - try 'dosemu -s -S'

**Comment by stsp** [comment]
In fact, xdosemu is already removed.
I am puzzled where have you got it from.
