### ISSUE TITLE
Shift Middle-click in SDL doesn't get data from other windows

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#440]
Using dosemu-2.0pre7.1-20170823-63-g2b3a1cbc on Debian 9.1, and starting (x)dosemu without switches or with -S (run with SDL), the shift + middle-click pasting only pastes data selected previously within the same window. Selecting text in some other window doesn't affect what is pasted in the dosemu SDL window. (Without shift, middle-click does nothing.)

Starting (x)dosemu with -X (run with X) does allow pasting text from other windows using shift + middle-click. (It pastes without shift, too.)

**Comment by stsp** [comment]
Unfortunately copy/paste is a moving target,
and SDL have moved to the different clipboard
API. As the result, under SDL you can paste
with middle mouse only if in another window
you explicitly selected "copy to clipboard".
I don't think this is something I can help with.
AFAIK freedesktop people want to deprecate
the good old middle-button copy-paste.
