### ISSUE TITLE
Int19 loads the MBR but returns to where it was called

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#441]
I tried out a (partition) boot sector within an image file I created using mkfatimage16. As it failed, it prompted for a key and upon receipt invoked interrupt 19h. This led to a crash, eg "ERROR: general protection at 0xac2a3bba: c4".

What seems to happen is that the interrupt 19h call makes dosemu reload the MBR to 0:7C00h, but then it returns to the address from which it was called, which is some arbitrary position (here: 0:7CCEh). It should instead jump to the MBR's entrypoint at 0:7C00h.

I'm using dosemu-2.0pre7.1-20170823-63-g2b3a1cbc on Debian 9.1

**Comment by stsp** [comment]
Yes, we need to also jump to reset address.

**Comment by ecm-pushbx** [comment]
Tested with dosemu-2.0pre7.1-20170903-73-ga02a35a2, works as expected now.
