### ISSUE TITLE
Dosemu doesn't honour the disk hdtype1 flag on older DOS

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#444]
On MS-DOS 3.30 after setting the disk hdtype in dosemu.conf explicitly to 1, the disk code ignores it and promotes it to 2.
On MS-DOS 6.22 it is okay.

~~~
$_hdimage = "drives/c:hdtype1
~~~

~~~
DISK: Forcing IBM disk type 1
DISK: changing hdtype from 1 to 2
DISK: Forcing IBM disk type 2
~~~

**Comment by stsp** [comment]
So what? :)
IIRC we force what is bootable.
Of course if you can relax the rules
and test that nothing breaks, that
would be great.

**Comment by andrewbird** [comment]
Yes, I'll change it. IMHO current behaviour isn't right else we'd be promoting the 6.22 to FAT16B too(don't do this!).
