### ISSUE TITLE
RxDOS boot support

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#445]
I expected that eg "bpint 13" would break for the next invocation of interrupt 13h, but it seems to only break for those invocations that it directly encounters during single-stepping. That is, if the code invokes interrupt 21h and that eventually deeper down calls into interrupt 13h, the latter int doesn't seem to break. is this expected (though not (well) documented) or is it a bug?

dosemu-2.0pre7.1-20170903-73-ga02a35a2 on Debian 9.1

If you need a simple test case I'll create one.

**Comment by stsp** [comment]
No, for me it triggers after `g`, which is
not a single-stepping.

**Comment by ecm-pushbx** [comment]
I was unclear. Running a program with g makes it stop only where it seems to directly encounter the int 13h instruction. It doesn't stop for int 13 within another interrupt invocation. This is what *would* be seen when single-stepping, but happens when running with g, too.

**Comment by stsp** [comment]
What do you mean?
There is almost no a direct int13
invocation after boot sector is completed.
It all happens from int21 then, and for
me it stops perfectly after g.

**Comment by ecm-pushbx** [comment]
Sorry, I can't currently reproduce with a simple test case. If it really comes to it I may upload the whole test image with which it happens.

**Comment by stsp** [comment]
Happens what?
Some app that calls int13 directly
instead of DOS doing it inside int21?
Sounds unrealistic.

**Comment by andrewbird** [comment]
@ecm-pushbx, just a little warning if you are tempted to start doing 'trace until keypress' command, it generates a lot of output and the transport between client and debugger is lossy, so does drop data. I have local branch here that doesn't, as it uses unix domain sockets, but that has another problem in that the data to be displayed is buffered to the extent that the keypress is so out of sync with it that it's pretty useless for interactive type stuff.

**Comment by stsp** [comment]
@andrewbird I think the right solution for
this can be to write the trace data to a file.

**Comment by ecm-pushbx** [comment]
The error I'm seeing with a fuller test case is that the int 13 calls in DOS do not stop execution, they don't break to the debugger. But as I mentioned, I can't yet reproduce this with a simpler test case.

**Comment by ecm-pushbx** [comment]
This is the simple test case. As mentioned, it properly breaks at each int 13, including the one in the int 21 handler.

```
evln@alyra:~/coding/proj/RxDOS/test$ cat test.asm
	org 7C00h
	cpu 8086

start:
	jmp strict near handler

	times 80h-3 db 0

handler:
	cli
	xor ax, ax
	mov ds, ax
	mov es, ax
	mov ss, ax
	mov sp, 7C00h
	sti

	mov word [21h*4], int21
	mov word [21h*4+2], ax

	xor ax, ax
	int 13h

	mov ax, 8000h
	int 21h

loop:
	int3
	xor ax, ax
	int 16h

	jmp loop

int21:
	cmp ax, 8000h
	jne .iret
	xor ax, ax
	int 13h
.iret:
	iret

	align 512, db 0
evln@alyra:~/coding/proj/RxDOS/test$ nasm -fbin -o test.dat test.asm -l test.lst; echo -ne "\$_hdimage = \"test.img\"\n\n\$_bootdrive = \"c\"\n" > test.cfg; mkfatimage16 -b test.dat -k 10240 -p -f test.img; dosemu.bin -X -f test.cfg --Fimagedir . -H1

```

dosdebug session:
```

evln@alyra:~$ dosdebug

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
Reading map file nm /usr/local/bin/dosemu.bin | grep -v '\(compiled\)\|\(\.o$\)\|\( a \)' | sort
7610 symbol(s) processed
highest address 019cef90(_end)
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
bpint 13
g
INT 0x13, system state: emulated,stopped
AX=4100  BX=55aa  CX=0000  DX=0080  SI=7e00  DI=7dbe  SP=7bde  BP=7c00
DS=1fe0  ES=0000  FS=0000  GS=0000  FL=000b3282
CS:IP=1fe0:7cb8       SS:SP=1fe0:7bde

1fe0:7cb8 CD13             int  13
g
INT 0x13, system state: emulated,stopped
AX=4200  BX=aa55  CX=0001  DX=0080  SI=7cc9  DI=7dbe  SP=7bde  BP=7c00
DS=1fe0  ES=0000  FS=0000  GS=0000  FL=000b3202
CS:IP=1fe0:7ceb       SS:SP=1fe0:7bde

1fe0:7ceb CD13             int  13
g
INT 0x13, system state: emulated,stopped
AX=0000  BX=aa55  CX=0001  DX=0080  SI=7cc9  DI=7dbe  SP=7c00  BP=7c00
DS=0000  ES=0000  FS=0000  GS=0000  FL=000b3246
CS:IP=0000:7c98       SS:SP=0000:7c00

0000:7c98 CD13             int  13
g
INT 0x13, system state: emulated,stopped
AX=0000  BX=aa55  CX=0001  DX=0080  SI=7cc9  DI=7dbe  SP=7bfa  BP=7c00
DS=0000  ES=0000  FS=0000  GS=0000  FL=00033246
CS:IP=0000:7cad       SS:SP=0000:7bfa

0000:7cad CD13             int  13

```

**Comment by ecm-pushbx** [comment]
I made an assumption that may be wrong. It's possible that my test case that fails simply doesn't actually call interrupt 13h at all. Will report more as I figure it out.

**Comment by ecm-pushbx** [comment]
Sorry for the bother. It does seem that my test case doesn't actually call interrupt 13h. I'll make a new issue for something to do with this.

**Comment by stsp** [comment]
> It does seem that my test case doesn't actually call interrupt 13h.

Yes, that's what my point is.
Anything that is not DOS itself, should almost
never call int13.

**Comment by stsp** [comment]
> This is the simple test case.

Some custom boot sector?

**Comment by ecm-pushbx** [comment]
The simple test case is indeed a custom boot sector. It seemed to be the simplest way of recreating the conditions.

And the other thing: In my test case, interrupt 13h wasn't called *at all* after boot-up. Not from outside DOS, nor by the DOS itself. This was due to https://github.com/stsp/dosemu2/issues/447 which meant that the RxDOS 7.1.5-based kernel (internally: 7.21) didn't install any units.

**Comment by andrewbird** [comment]
@ecm-pushbx does RxDOS exist somewhere other than [sourceforge](http://rxdos.sourceforge.net/readme) as It seems only to be at v6.2?

**Comment by ecm-pushbx** [comment]
http://ftp.uni-bayreuth.de/pc/freedos/unofficial/rxdos.old/ (and maybe some other FreeDOS mirrors) have the original GPL release, 7.1.5, though this seems to have been removed from the official FreeDOS mirror source.

At https://bitbucket.org/ecm/rxdos-7.2x/ I'm continuing a NASM port of that (initial commit is a bug-for-bug reproduction).

Eventually, I plan to either update the entire kernel, or else replace it bit by bit.

**Comment by ecm-pushbx** [comment]
To boot this, I use the following commands:

`evln@alyra:~/coding/proj/RxDOS/rxdos-7.2x$ echo -ne "\$_hdimage = \"boot.img\"\n\n\$_bootdrive = \"c\"\n" > bin/boot.cfg; mkfatimage16 -b bin/RxBOOT.SYS -k 10240 -p -f bin/boot.img bin/RxBIO.SYS bin/RxDOS.SYS ~/.dosemu/drives/c/{command.com,bin/debug.com}; dosemu.bin -X -f bin/boot.cfg --Fimagedir bin -H1
`

**Comment by stsp** [comment]
Probably it would be good if you can
contribute the rxdos boot support to dosemu2.
Otherwise @andrewbird will have to get
to the disassembler again. :)

**Comment by andrewbird** [comment]
Funnily enough I was thinking of adding fatfs boot support, could you tell? If it's bootable with standard FAT12/FAT16/FAT16B it should be straightforward.

**Comment by ecm-pushbx** [comment]
ch = media descriptor [not used]
dl = int13 boot unit
bx:ax = root directory sector (including hidden sectors, ie LBA on boot unit) [not used by 7.1.5 / 7.2x]
ds:si -> relocated DPT inside boot sector (same value as int 1Eh entry)
70h:0 = load address, should work with loading 3 sectors of 512 bytes each (600h bytes)
70h:0 = entry point to jump to
0:7C0Bh -> BPB inside boot sector [used to boot both kernel files]

50h:0 = first root directory sector, first entry must be RXDOSBIO.SYS (RXBIO.SYS), second RXDOS.SYS; particularly the starting cluster words must be present

FAT32 booting isn't supported yet.

I plan to eventually merge RxBIO into RXDOS.SYS (or RXDOS.COM), so while that may differ eventually, RXDOSBIO.SYS or RXBIO.SYS present should indicate the herein described (old-style) interface.

**Comment by andrewbird** [comment]
@ecm-pushbx Where does command.com come from, is it FreeDOS?

**Comment by ecm-pushbx** [comment]
In my test case I copied it from my default dosemu drive C:, which has the one from dosemu-freedos-1.0-bin.tgz  RxDOS originally comes with RxDOSCMD (RxCMD), but I'll probably not develop this any soon.

**Comment by andrewbird** [comment]
Currently our boot code doesn't copy the DPT out from the BIOS area, is that likely to be a problem for RxDOS?

**Comment by ecm-pushbx** [comment]
Not really, I don't think. Just load ds:si with the pointer from the IVT.

**Comment by andrewbird** [comment]
okay, thanks I have 7.1.5 booting
![rxdos7 1 5](https://user-images.githubusercontent.com/220835/30006966-6fb953bc-90fc-11e7-96dc-c9b60d8815b4.png)
But it's probably not that useful at the moment:
1/ disk is not writable as MFS redirector is not working
2/ FAT12 (hdtype1) and FAT16 (hdtype2) causes dosemu crash
~~~
DISK 80 init                                                                    
INT13: ax=0826 cx=0e00 dx=ff00                                                  
disk get parameters 0                                                           
ERROR: EMU86: error 96
~~~

**Comment by andrewbird** [comment]
So here's my first stab at booting RxDOS on fatfs [andrewbird/disks12](https://github.com/andrewbird/dosemu2/tree/disks12). Works with 7.1.5 and FAT16B. With FAT12 or FAT16 sized disks it doesn't like something and then crashes dosemu when accessing the floppy. Short of time today, so won't be able to tidy up into something worthy of a PR :smile:

**Comment by ecm-pushbx** [comment]
Here's copies of all the RxDOS files I've found. [RxDOS.OLD.zip](https://github.com/stsp/dosemu2/files/1274423/RxDOS.OLD.zip)

**Comment by andrewbird** [comment]
I notice in your bugs fixed list the SDA format was incorrect. Was that true of 7.1.5?
~~~
#0018:
UDESC:	Some programs crash.
FOUND:	-
BFILE:	RXDOS.SYS
PDESC:	Although the SDA/DOSDATA layout word was set to 1 (MS-DOS 4.x+), the
	SDA actually had the MS-DOS 3.x layout.
SOLTN:	SDA changed to MS-DOS 4.x+ layout.
SFILE:	RxDOS.ASM
LABEL:	SwappableDataArea
~~~

Is there a way to determine that the running DOS is RxDOS, not some other supplier's variant with same version number?

**Comment by ecm-pushbx** [comment]
21.3000 vendor is 5Eh for RxDOS, though that isn't very certain. The bug does apply to RxDOS 7.1.5, yes. However, note that this version doesn't use the redirector interface at all, so I don't know whether you need the SDA at all.

**Comment by andrewbird** [comment]
Ahh, okay, so since our fatfs vfs is readonly and 7.1.5 doesn't do redirector calls, there's probably not much point worrying about it too much. We do use SDA to find the PSP of the running program, so we can discover its program name, but for nothing serious, just window title.
So is 7.2 the first version to support a redirector? I didn't see it in the zipfile you uploaded, though it mentioned a 7.2 beta in versions.txt?
Thanks for the vendor ID hint, i have an old paper DOS quick reference book that I use which didn't have it listed, whereas RBIL has a list of OEM and vendor codes.

**Comment by ecm-pushbx** [comment]
As far as I'm aware, currently no RxDOS revision supports redirectors. One of many shortcomings.

**Comment by stsp** [comment]
> As far as I'm aware, currently no RxDOS revision supports redirectors.

Ouch.
This makes it almost irrelevant under dosemu.
