### ISSUE TITLE
Fatfs has duplicate config.sys file

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#449]
See the screenshot below. After removing MFS redirection it can be seen that the underlying fatfs has two copies of config.sys. I'm not sure when this started (I don't have time to bisect at the moment)
![fatfs-two-config-sys](https://user-images.githubusercontent.com/220835/30016767-57fb2dca-914e-11e7-9111-68a5d21d2780.png)

In the boot.log
~~~
fatfs: assign_clusters: obj 4, start 69, len 1 (CONFIG.SYS)                     
fatfs: assign_clusters: obj 5, start 70, len 1 (config.sys)                     
~~~

**Comment by stsp** [comment]
Thanks!
This is recent. :(

**Comment by andrewbird** [comment]
Thanks, that fixed it!
