### ISSUE TITLE
MPU-401 intelligent mode

### ISSUE THREAD

**Issue by PaulRaul** [stsp/dosemu2#45]
MPU-401 intelligent mode doesn't appear to work in dosemu2.  It does, however, work with the old dosemu 1.4 if the 'old' sound code (1) is used with dosemu-midi pointing to the proper sequencer device.  The dosemu2 sound code is much, much improved, except for this issue.  Basically, this is going to prevent music output on most of the Sierra games and bunch of others.

I have ALSA setup with MUNT and plumbed properly, which works on games that use the UART mode of the MPU-401 exclusively (essentially later games that use General MIDI as opposed to early Roland synths paired to an intelligent MPU).  Running the old dosemu binary, these games work fine.

Would love to see this working again!

Paul

**Comment by stsp** [comment]
No, I don't believe the intelligent mode worked on 1.4.
You probably mean UART mode - that one worked,
and should work on dosemu2 too.
dosemu2 doesn't need pipe for midi, but dosemu-midi
is still supported for compatibility.
To do a quick test, you can remove dosemu-midi fifo
and create a generic file with the same name. Then,
after playing the game, this file should contain the raw
midi data, which will indicate that dosemu works as expected.

**Comment by PaulRaul** [comment]
I've actually tested it with the file (and I understand this is the 'legacy' way of handling MIDI) - games that use UART (dumb) mode will produce output to the file, while games which assume 'standard' (ie. intelligent mode MPU) don't produce any output at all.  UART mode is basic I/O to the MPUs data and status ports, while software written for intelligent mode will install an interrupt handler to coordinate timing and other events with the MPU.  

This certainly works under 1.4 using $_sound = (1) and dosemu-midi pointed to the sequencer device.  

As a test, try running something like, ie. Space Quest III or Ultima 6 on dosemu2.  These games use interrupt-driven timing from the MPU, while something like Doom will run without a problem as it uses UART mode.

**Comment by stsp** [comment]
No, UART mode supports irq as well.
Its just that for dosemu2 the mpu401 irq is 2,
but you can set it back to 5 in dosemu.conf:
$_mpu_irq = (5)
(dont forget to uncomment the config line)

**Comment by PaulRaul** [comment]
Already tried switching the IRQ back to 5 to simulate the behaviour of 1.4 and this doesn't work.  I don't think this *should* work, as the majority of the software which uses the MPU in intelligent mode all assume IRQ 2 (this is due to the original Roland hardware all being hardwired for IRQ 2 in days of 8-bit ISA machines).

I'm not an expert on MIDI, but I have programmed in UART mode which is the 'dumb' mode of an MPU-401, and the mode the majority of sound-card MIDI interfaces operate in.  In this mode, you're doing in/outs to the data and status registers and never using any sort of interrupt handler.

It's somewhat confusing, because Roland refers to 'intelligent mode' as 'standard mode'.  If UART mode (dumb mode) can use interrupts, it's certainly not required, and i've never actually seen any program that behaves like this.

**Comment by stsp** [comment]
http://www.piclist.com/techref/io/serial/midi/mpu.html
Whenever the MPU receives an incoming MIDI byte, it will interrupt the computer. In your interrupt handler, you should keep reading bytes from DATA port while DSR is low.

**Comment by stsp** [comment]
If there is some bug, please make a -D9+S log
with the game that doesn't fill the dosemu-midi file.

**Comment by stsp** [comment]
Or give an URL to such a game so that I can try.

**Comment by PaulRaul** [comment]
Will do...  Thanks for helping with this.

Glancing over that link, the interrupt handler is not *strictly required* in UART mode, whereas in 'intelligent mode', it is a hard requirement.  So, the problem may not be an issue with intelligent mode, per se, but the possibility that programs which use the MPU with interrupts aren't receiving them.  I don't think the vast majority of software which use UART mode actually use the interrupt handler, however - the MIDI program which are working, will work regardless of where the MPU IRQ is set to in dosbox.

**Comment by stsp** [comment]
Yes, none of the games will, as the IRQ is
only for RX but not for TX. So something else
is a problem.

**Comment by PaulRaul** [comment]
OK...

http://home.ix.netcom.com/~jjingber/sound.log.bz2
http://home.ix.netcom.com/~jjingber/nosound.log.bz2

- First log was a run of Duke Nukem 3D, both digital audio and MIDI were enabled and worked.  Log size is ~150K.  
- Second log was a run of Space Quest 3 with non-functioning MIDI.  Log size is ~66 MB (compressed well to 35K as it's mostly repetitive messages dealing with MIDI events).

I know that SQ3 expects an 'intelligent' MPU, and Duke3D does not.  Generally games which have a GM option will work, while games which relied on a pairing of an MT-32-type device and MPU-401 will not, which makes sense.

**Comment by stsp** [comment]
My comment above is not accurate: there is only
RX IRQ indeed, but every command generates an
ACK byte from data port, that also generates RX IRQ,
so games can use irqs too.
Please see if the problem is now "fixed"

**Comment by PaulRaul** [comment]
Close it up.   You're a star.   Thanks a bunch for knocking this out so fast.

**Comment by stsp** [comment]
Its already closed, github closes the tickets
automatically when fixed.
But you shouldn't be using midi pipe.
I think you'd just get midi out of dosemu2 without
any extra setup.

**Comment by runderwo** [comment]
My fork https://github.com/runderwo/dosemu2 has working midi UART as well as intelligent mode.  But the intelligent mode timing has some problems still that I haven't resolved.

**Comment by stsp** [comment]
https://github.com/runderwo/dosemu2/commit/379ef8dfd6a91b3983e5d66b0cb9805f7a94c1bf
Merge sound work from dosemu 1.x 

So would you also claim that dosemu-1.x supported this?

**Comment by runderwo** [comment]
No, I had started the work on dosemu 1.x and gave up since there's no future in it. :-)

**Comment by stsp** [comment]
> But the intelligent mode timing has some problems still that I haven't resolved.

reset_idle_mt() was too slow.
Please rebase and try add_thread_callback().

**Comment by stsp** [comment]
Hmm...
Anyone seen this?
http://bjt42.github.io/softmpu/

**Comment by runderwo** [comment]
Yes, unfortunately it uses some nasty EMM386/QEMM specific hacks to
virtualize I/O:
https://github.com/bjt42/softmpu/blob/master/SRC/PORTHAND.ASM

Other than that it's a direct port of Dosbox intelligent mode just
like my code.

-- 
Ryan C. Underwood, <nemesis@icequake.net>

**Comment by stsp** [comment]
Hmm.
It might be cool to support emm386 more than
we do now, and it may be NOT cool adding the
intelligent mode to sb16 code as it is not part of
sb16, and normally you'd have to implement a
roland addon card instead. Its cool to implement
the roland addon card, but too much work for too
small benefit (most games are happy with uart).
While supporting the emm386-style hook is likely
a nearly trivial task.
Would you consider having a look into that?

**Comment by runderwo** [comment]
It's okay to factor it out into a separate MPU module once the timing works correctly, I agree with your comment that it doesn't belong in SB DSP core.  The only reason it is there is because that's where the existing SB-MIDI and MPU401 UART functionality lived.

I don't know about doing the emm386 hook, I'm not an expert at it.

The hard work is already done in dosbox, this is just a copy and adaptation of that code.  Here is the list of games using intelligent mode.
https://github.com/bjt42/softmpu/wiki/Compatible-Intelligent-Mode-Games

**Comment by stsp** [comment]
I wonder if most of these games still work
if you forcibly switch the uart mode, as I did
for this bug report.

**Comment by stsp** [comment]
> comment that it doesn't belong in SB DSP core.

sb16 AFAIK doesn't have intelligent mode _in hardware_,
do this code doesn't belong to anything but a new
card by roland.

**Comment by stsp** [comment]
I mean, even if you have a real PC
with real soundblaster where you run real DOS,
you would _still_ need to load this softmpu there.

**Comment by runderwo** [comment]
that's right, any hardware like SB which doesn't have a MPU401 sequencer mode would require SoftMPU.

Some of these games have patches to work in UART mode (SQ3 and other Sierra SCI games for example).  On the other hand, programs like Cakewalk 3.0 require the sequencer.

**Comment by PaulRaul** [comment]
> Here is the list of games using intelligent mode.

Now, are these games actually using intelligent mode, or just utilizing an interrupt handler for the MPU-401?  I was confused about this distinction when I submitted the ticket.

**Comment by PaulRaul** [comment]
> I wonder if most of these games still work
> if you forcibly switch the uart mode, as I did
> for this bug report.

The games I have tried on that list *all*  work by forcing UART mode.  

I have tried:

Conquests of Camelot
Quest for Glory I
Space Quest III
Silpheed
The Colonel's Bequest
Ultima VI (but crashes from unrelated issue)
Wing Commander
Wing Commander II

**Comment by stsp** [comment]
> Now, are these games actually using intelligent mode, or just utilizing
> an interrupt handler for the MPU-401?

I don't know how the intelligent mode work (maybe @runderwo does),
but I guess it uses the data port just the same way it is used in uart
mode. Given that via uart port you can also send sysex messages
to do a setup work, I would expect that the timing irqs is the only thing
it can get from intelligent mode. I can't guess what else is not possible
in uart mode.

**Comment by PaulRaul** [comment]
Here's something interesting I just tried, to further support this discussion.

The MediaVision Proaudio Spectrum 16 Rev. D has the ability to use an IRQ for the MPU-401, unlike the SoundBlaster cards.  Curious, I tried SQ III and Silpheed with the PAS16 configured for the MPU-401 IRQ and it will indeed also play these games and properly drive the synth.

This card definitely doesn't support any of the Roland advanced functions.  The games seem to just need IRQ capabilities on the MPU-401 portion of card.

Unsurprisingly, it seems Creative Labs' decision to save one cent on the price of a a single PCB trace is responsible for this whole boondoggle.

**Comment by stsp** [comment]
Please be more specific!
As already discussed, on sb16 the rx irqs work too, so
I don't know how to parse your "unlike the SoundBlaster cards"

**Comment by PaulRaul** [comment]
Specifically, the *dosemu* SB16 code works, as it supports the IRQ, but an *actual* SB16 card does not, as the hardware itself does not provide an MPU-401 IRQ.

**Comment by stsp** [comment]
I don't believe you.
dosemu's sb16 mpu emulation is modelled around
the document I've already pointed you too, that
clearly says rx irqs are supported, and additionally
every command ACK also generates an irq.

**Comment by PaulRaul** [comment]
That document is based on Roland's MPU-401 specification, not Creative Lab's implementation (interpretation) of the MPU-401.  Whoever did the initial work on the dosemu driver added the MPU-401 IRQ for compatibility.

**Comment by stsp** [comment]
http://bochs.sourceforge.net/cgi-bin/lxr/source/iodev/sound/sb16.h
It has
#define BX_SB16_IRQMPU  BX_SB16_IRQ // IRQ for the MPU401 part - same value
which is how it was on dosemu-1: same irq for SB and mpu.

**Comment by PaulRaul** [comment]
You Sir, are correct.  

Reading the SB16 tech ref, the peculiarity with the SB16's implementation is that an SB16 *will* generate the IRQ, but the the card doesn't provide any mechanism for the ISR to receive timing information from the hardware like a real (Roland) MPU-401.

From page 5-10:  MIDI Port I/O programming:

> Under the MPU-401 UART mode, there is no timing information available. It is up to
the application to handle the timing for the MIDI data.

http://pdos.csail.mit.edu/6.828/2008/readings/hardware/SoundBlaster.pdf

The PAS16D does, I assume include a more complete MPU-401 implementation which includes the timing information.

**Comment by PaulRaul** [comment]
The timing of course, is an intelligent mode function.

**Comment by stsp** [comment]
> The PAS16D does, I assume include a more complete MPU-401 implementation
> which includes the timing information.

This is absolutely not important.
Firstly, you can read PIT counter in an MPU interrupt
handler to get a timing, and secondly inband timing
information accomplishes only the incoming midi stream,
and most likely only in an intelligent mode.
So if you say PAS16 does something better, this may
be in intelligent mode only (or maybe it does tx irq -
the only possible improvement for uart).

**Comment by runderwo** [comment]
The MPU-401 is a stupid piece of hardware that just offloads sequencer work from XT-class machines that do not have the overhead available to accomplish it in software.  It became "standard" only because it was the only way to connect an expensive MIDI synthesizer to the PC before SB cards.

So emulating it is not interesting except for software that requires it (that uses an MPU401 ISR  in the music driver) and has not been patched to operate in UART mode (like Sierra games).

Gateway is a good example, it has a great MT-32 soundtrack which can't operate without intelligent mode.

This is the mpu401 datasheet, you can see that operation in UART and intelligent mode are completely different with respect to using the data port.
http://media.rolandus.com/manuals/MPU-401_OM.pdf

**Comment by PaulRaul** [comment]
I'm not trying to be difficult guys... :)  This whole thing is somewhat confusing, and I'm trying to get a better grasp on this.

According to that SB tech ref., the SB16 has two MIDI "devices".  The internal OPL3-based synth and the MPU-401 portion.  If a wavetable add-on card is installed, it is accessed as a device attached to the MPU-401.

Now, the OPL3 MIDI device uses an IRQ which is always shared with the DSP - ie. DSP is on IRQ5 so the OPL3 MIDI portion will *also* be on IRQ5.  In the Bochs and dosemu code, they have the *MPU-401* portion of the card sitting on IRQ5 which is the default location of the *OPL3* device.

Is this valid, yes it is, according to the tech. ref, however, this is not the *de-facto* IRQ for the MPU-401 portion or a real MPU-401.  This would be IRQ 2, and I would imagine the selection of games which are hard-coded to IRQ will fail.  I think IRQ2 is really where the default should be set, despite what dosemu 1.4 or Bochs are doing.  Dosemu used IRQ5 as there were interrupt steering issues with the second PIC when the MPU-401 interrupt code was originally submitted and it stuck there. 

Now, to make this even more confusing, the tech ref. lists a number of IRQs which are available for the MPU-401 portion of the card, 2, 5, and the usual suspects are included.  Pin B4 on the ISA bus is IRQ2.  In front of me, I have a Compaq OEM SB16 SCSI model CT770 (Compaq PN 197493-001).  The trace and finger for IRQ2 is *physically absent* from this board, despite being a valid IRQ, again according to the tech ref.  This a pre-PNP board and is completely configured by means of jumpers.  There are no jumpers to assign an IRQ to the MPU-401 portion of the card, only a jumper to change the I/O port address of the MPU-401, which is, again, in contrast to the information in that tech ref.

When I have time, I'm going to put this card into a machine and examine how the MPU-401 setup is occurring for the games we're discussing.  There's alot that's not making sense to me, but I'm going to have some data before I stick my foot in my mouth again.

**Comment by runderwo** [comment]
No, the OPL3 is not a midi device in hardware, only in software emulation.  There's no interrupt associated with it, it's a write-only device with host sequencing.  No program using FM synthesis would expect it to behave like a MIDI device in hardware.

IRQ2 is canonical, but I made it configurable because of the reality of some programs having trouble with this on AT-class machines (like dosemu) where IRQ2 is cascaded.

**Comment by PaulRaul** [comment]
[/QUOTE]No, the OPL3 is not a midi device in hardware, only in software emulation.[/QUOTE]

Roger, so "SB MIDI", as used in the tech. ref. refers to the non-MPU-401 compatible interface prior to the SB16, and the initial state of the MPU-401 portion *prior* to placing it into UART mode.

**Comment by runderwo** [comment]
SB-MIDI is the half-duplex midi interface of the SB/SBPro/SB16 DSP, which is not MPU-401 compatible, either UART mode or not.  It does act like a UART for output (send raw MIDI bytes to whatever is connected), it just has a totally different programming interface.

The SB16 MPU-401 interface has nothing other than a UART mode.  I am not sure what it does when not initialized into UART mode.  The SB16 programmer manual contradicts itself regarding entering and exiting UART mode.  One could test that with some real hardware.

**Comment by stsp** [comment]
> This is the mpu401 datasheet, you can see that operation in UART and intelligent mode are completely
> different with respect to using the data port.

Not seeing.
On page 8 at the very bottom is a diagram of transmitting
midi messages. They are sent to data port, with something
is sent to command port. Only on receiving, the midi messages
gets decorated by an MPU messages (timing perhaps, sb-midi
does the same thing btw).
So I don't see anything that contradicts my expectations.

**Comment by stsp** [comment]
> According to that SB tech ref., the SB16 has two MIDI "devices". The internal OPL3-based
> synth and the MPU-401 portion.

As already explained by Ryan, this statement is wrong.

> Now, the OPL3 MIDI device uses an IRQ

OPL3 chip has IRQ pins unconnected on sb16 board.

> Is this valid, yes it is

Absolutely not.

**Comment by stsp** [comment]
> Now, to make this even more confusing, the tech ref. lists a number of IRQs which are available
> for the MPU-401 portion of the card

They are the same as for the DSP.
And in fact, cannot be configured to be separate from DSP.
And the doc explicitly mentions the default (5), and the same
is default for DSP irq, obviously.

**Comment by stsp** [comment]
> IRQ2 is canonical, but I made it configurable

FYI, it is configurable in dosemu2 too.
Which is a bit of an extension from the real HW.
I put it by default to 5 to stay compatible with the
real world.

> because of the reality of some programs having trouble with this on AT-class
> machines (like dosemu) where IRQ2 is cascaded.

Your patch that made it cascaded, had a severe bug.
You should re-test the programs you mention, with
dosemu2 which have it fixed.

**Comment by stsp** [comment]
> Roger, so "SB MIDI", as used in the tech. ref. refers to the non-MPU-401 compatible
> interface prior to the SB16

Not sure who is Roger, but SB-MIDI is still available on
sb16 (yet no one uses it) and is completely unrelated
to mpu401 by all means other than that they share the
same game-port AFAIK, so you can't use both together.
sb-midi can provide interrupts and timestamps, but since
it has sb-specific programming interface (via DSP register
space IIRC), it is quite unhelpful.

**Comment by PaulRaul** [comment]
Thanks for setting me straight on the SB stuff.

I played around on the real hardware tonight based on the piclist document.  Unless I'm missing something, UART mode doesn't provide ACKs or any other status feedback, making the use of the IRQ in this mode somewhat useless if you're not using the card for recording.  

So if you setup a receive ISR, it'll catch exactly one ACK from the FF before you put the card in UART mode and then it sits there doing nothing.

**Comment by stsp** [comment]
> Unless I'm missing something, UART mode doesn't provide ACKs or any other status feedback

Unless you write to the command port.
Maybe the only reasonable thing to write
there in UART mode, would be a reset cmd,
so perhaps not a big deal indeed, but I suspect
any other writes to command port will also
generate an ACK.

> if you're not using the card for recording. 

Many midi sequencing programs do exactly that (recording)
and work under dosemu only if the IRQ is set up rightly.

**Comment by runderwo** [comment]
> FYI, it is configurable in dosemu2 too.
> Which is a bit of an extension from the real HW.
> I put it by default to 5 to stay compatible with the
> real world.

I was talking about mpu-401, you're talking about SB16.  So in terms of emulating a SB16 you're right, but I was talking about emulating MPU-401.  The first MPU-401 cards were strapped to IRQ2 but later ones (MPU-401AT like I have) can have the IRQ configured.

> Your patch that made it cascaded, had a severe bug.
> You should re-test the programs you mention, with
> dosemu2 which have it fixed.

Sorry, you didn't tell me there was a problem with it.

**Comment by stsp** [comment]
> I was talking about mpu-401, you're talking about SB16.

I was simply wondering what you mean by "but I made it configurable"
and how that differ from the way it is configurable in dosemu2.
You added a new config option instead of re-using the existing,
or something along the lines.

> Sorry, you didn't tell me there was a problem with it.

Because I've found it later.
Make sure you have this commit:
678aa43d3
or nothing works.

**Comment by runderwo** [comment]
> On page 8 at the very bottom is a diagram of transmitting
> midi messages. They are sent to data port, with something
> is sent to command port. 

Read section 3 starting on page 9 and it should be clearer.  You have to be careful when reading because the datasheet refers to "receiving data" when playing back and "sending data" when recording.  But it is clear that when playing back, there are leading bytes other than the raw midi data.

**Comment by runderwo** [comment]
(This is also observed by spying on the gateway music driver)

**Comment by runderwo** [comment]
> You added a new config option instead of re-using the existing,
> or something along the lines.

I added a config option for the MPU IRQ separate from the DSP IRQ.  This may be confusing the thread because I'm talking about a fork instead of your master tree.

**Comment by stsp** [comment]
> I added a config option for the MPU IRQ separate from the DSP IRQ.

Which is already in dosemu2... puzzled. :)

**Comment by runderwo** [comment]
I guess you added it after January which was the last time I had any time to work on this.

**Comment by stsp** [comment]
> But it is clear that when playing back, there are leading bytes other than the raw midi data.

I wonder.
Please see page 10.
It says: "When the HOST wants to transmit a MIDI message
to MIDI OUT using the MPU COMMAND of $D0 to $D7 (Want To Send Data),
the data must be sent in standard MIDI format but without a leading timing byte".
That actually is the only explanation why forcing the UART mode always works.
In fact, the logs in this ticket indicate exactly that 0xd0 was written to cmd port.

**Comment by runderwo** [comment]
> Make sure you have this commit:
> 678aa43
> or nothing works.

Thanks for the fix.  I guess all the programs I was testing were installing their own IRQ2 handlers. :/

**Comment by runderwo** [comment]
"That actually is the only explanation why forcing the UART mode always works."

Yes, it makes sense, because in UART mode the WSD command is ignored.  But it can't always work.  If the program's MIDI playback is interrupt driven and is formatted as full MPU message instead of raw MIDI data, the bytes would be sent at the wrong time and control bytes would be misinterpreted as MIDI data and transmitted to the bus.

**Comment by stsp** [comment]
> But it can't always work.

There seem to be some "stop mode", in which it
also works, and I suspect it is a default.
So unless you try really hard, everything by default
will work.

**Comment by runderwo** [comment]
> There seem to be some "stop mode", in which it
> also works, and I suspect it is a default.
> So unless you try really hard, everything by default
> will work.

No, that's not true.  Try it yourself and see.  It's obvious that the only difference between MPU message control bytes and the raw MIDI data is their position in the stream.  If that gets out of sync, control and data bytes are totally confused.  Anyway, Dosbox and SoftMPU would surely be happy to delete all this code, if it were the case that it was unnecessary to simulate a stateful MPU.

**Comment by stsp** [comment]
> No, that's not true.

What exactly, the presence of "stop mode", or
the way I describe it, or that it is a default mode?
Surely if you program MPU in some weird ways,
it won't work as UART. But by default it seems
like it does, and even when not, most progs still
use 0xd0 and/or sysexes, so it works again.
That makes me very confident in my recent
fix to just always pretend we are UART: you'll
have hard times finding something that still
doesn't work, although you _can_ find it if you
really try.

**Comment by runderwo** [comment]
People have found plenty of things that don't work, all the programs on the SoftMPU list that do not have UART mode fixes (like Sierra SCI games).  Before stateful MPU was implemented in Dosbox, UART was what was available.  People noticed MIDI-using programs didn't work, figured out why, and implemented that functionality.

Please don't misunderstand me; I agree with you that when emulating a SB16, always-UART is most likely the right thing to do (in fact it's the best the HW is capable of).

I am only arguing that this will not work (nor would real SB16 hardware!) for the majority of games on that list, nor for any other programs like Cakewalk 3.0 that expect to talk to a stateful MPU.  That's why the MPU emulation is necessary to run these programs if MIDI is to be used successfully.

**Comment by runderwo** [comment]
Btw, I don't disagree with you that this MPU emulation doesn't belong in SB16.  I was only hacking to see if it would work, that's the only reason it's there in my fork.

**Comment by stsp** [comment]
Please see the above comment about the list:

> The games I have tried on that list all work by forcing UART mode.
> I have tried:

This is what is important here.
The list will not help you to find such progs now,
when UART mode is forced. You may _still_ find
something, especially among the recording software,
but you'll have hard times finding the non-working
_game_ now.

**Comment by runderwo** [comment]
Ok, then we disagree.  5 out of 8 of those games he tested are Sierra SCI games which use the MPU so much like a UART (sysex's and raw MIDI data with host-controlled timing) that a simple patch makes them UART compatible.  I don't know about the other three.  Good luck with anything else on the list, such as Gateway, a particularly difficult one.

**Comment by stsp** [comment]
I think pretty much everything on the list that
is not marked with (1), will work.
"(1)" means that it uses MPU interrupts.
Gateway is marked with (1).

**Comment by runderwo** [comment]
Yes, I think you would be correct in that case.

**Comment by jharrison03** [comment]
If you want to close something else out -- it works perfectly now.

**Comment by stsp** [comment]
But all mt32 tickets seems closed.
