### ISSUE TITLE
Implement INT21/6c Extended Open for {MS,PC}-DOS < 4.0 && DR-DOS < 7.00

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#453]
Since LFN file open on MFS redirected drives is implemented by finding the SFN and asking DOS to open it via INT21/6c, some earlier DOS versions error out as they don't provide that function. With one of the affected DOS variants the situation is compounded by LFN findfirst/next working fine to return an LFN, but then the application trieds to open the LFN and it fails due to this problem. Of course this can be worked around by disabling LFN support in dosemu.conf.
As I understand, it may be possible to implement a replacement INT21/6c by means of INT21/3c and INT21/3d. 

Currently 16 variants of DOS in my test suite are showing this issue.

**Comment by stsp** [comment]
We can just disable LFNs selectively for these doses.
