### ISSUE TITLE
lagging after printing

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#455]
After printing to lpt1, dosemu2 become lagging. It still running but become unresponsive. For example after executing command : `dir > prn` , output of listing the directory contents with dir command is not as snappy as before the printing. 

It is more noticable in my database application which store the data in netware server.

I've tried the 32bit and 64bit versions, all experience the same thing. Old dosemu (in 32bit environment) does not have this problem. It happens with `dosemu -S` and `dosemu -X
`
$_lpt1 is set correctly in dosemu.conf with real printer

**Comment by stsp** [comment]
Can it be reproduced without a printer,
for example when printing to a file?

**Comment by bpranoto** [comment]
Yes, I set:

`$_lpt1 = "cat > /tmp/hapusaja"`

same effect.

**Comment by bpranoto** [comment]
I make a screencast recording to show the symptom

https://www.youtube.com/watch?v=4MJZXysfQZg

**Comment by stsp** [comment]
So it seems to be reproducible with only one program,
not with everything, right? Please try `speed 0`

**Comment by bpranoto** [comment]
Did you mean  `$_cpuspeed = (0)`, isn't it the default?

The program connects to Advantage Database Server  resides in netware server through IPX, could it somehow related to IPX?

**Comment by andrewbird** [comment]
I don't suppose as a test it's even possible to run your program on a non netware drive? I wonder about netware interaction with dosemu, as I seem to remember that netware drives are implemented not by redirector, but by installing a front end int21 handler that filters out the filesystem calls.

**Comment by jharrison022** [comment]
My dosemu setup also uses Netware extensively (my C drive is a "stub" to login to a netware server), and I've observed similar slowdowns.

If you're running with VLMs on the client-side, try disabling packet burst in NET.CFG/Netware DOS Requestor/PB BUFFERS = 0.

Is your Netware running under QEMU?  I think this is where the problem is.

**Comment by jharrison022** [comment]
Running Borland compilers from a Netware volume seems to trigger a slowdown that sounds similar to what you're experiencing.

**Comment by jharrison022** [comment]
Since we have a few Netware users here, are you using the packet driver interface for dosemu or IPX?

The dosemu IPX stuff seems to run at about 1/10 the speed of pdether on top of the packet driver interface.

I'm fine with pdether, this is just FYI.

**Comment by stsp** [comment]
> The dosemu IPX stuff seems to run at about 1/10 the speed of pdether
> on top of the packet driver interface.

Maybe you should bug-report that.
I tried various IPX games and I can't tell
the difference between internal IPX and
ipxodi.

**Comment by stsp** [comment]
> Did you mean $_cpuspeed = (0), isn't it the default?

`speed 0` is not `$_cpuspeed = (0)`.
Please try the former.

**Comment by bpranoto** [comment]
Did you mean speed.com in C:\DOSEMU? 

Trying `speed 0` does not fix.

**Comment by bpranoto** [comment]
> Since we have a few Netware users here, are you using the packet driver interface for dosemu or IPX?

No, I use the IPX built in support. Speed is fine, except  for this problem.

**Comment by stsp** [comment]
Please add `-D9+pn` log.

**Comment by bpranoto** [comment]
Here is the log.
Thanks very much.

[boot.log.zip](https://github.com/stsp/dosemu2/files/1293112/boot.log.zip)

**Comment by stsp** [comment]
Please add `-D9+pg`

**Comment by bpranoto** [comment]
[bootlogD9pg.zip](https://github.com/stsp/dosemu2/files/1293232/bootlogD9pg.zip)

**Comment by stsp** [comment]
Can you reproduce this if IPX is disabled in config?

**Comment by bpranoto** [comment]
I'll recompile my program so it will run on pure local drive with IPX disabled in config.
I will report then.

**Comment by bpranoto** [comment]
No problem when running on local drive.

**Comment by stsp** [comment]
So is this specific to ipx?
Can you reproduce it with ipxodi instead
of an internal ipx?

**Comment by stsp** [comment]
In `utilities.c:801` can you please comment
out `ioselect_done();` and `sigprocmask` at
line 803, and see if something changes?

**Comment by bpranoto** [comment]
In my files, the lines are in line 792 and  794

```
        /* close signals, then unblock */
        /* ioselect_done(); */
        signal_done();
        /*sigprocmask(SIG_SETMASK, &oset, NULL);*/

```
You are wonderful, I commented out those lines and now everything is okay.

Thank you very much! Dosemu2 rocks!

**Comment by stsp** [comment]
OK, thanks for testing.
