### ISSUE TITLE
Build engine and VESA modes

### ISSUE THREAD

**Issue by j2969719** [stsp/dosemu2#456]
Build engine games like duke3d or blood runs extremely slow with vesa modes.
~ after commits on Jul 5-6

**Comment by stsp** [comment]
True, but I can't bisect the bad commit,
as if its always different. Most time bisect
stops on some seemingly harmless merge
commits. :(

**Comment by stsp** [comment]
No longer happens for me...
Could you check?

**Comment by stsp** [comment]
Hmm, seems like I can reproduce it
only on fedora +debug kernel, but not
with normal kernel. And not after commit
096984b, so this looks most definitely
fixed.

**Comment by j2969719** [comment]
yeah, on arch with default 4.12 kernel it became a little better now, but FPS is still a bit lower and a lot of screen tearing is happening 
anyway thanks

**Comment by stsp** [comment]
Is there any way to show fps?

**Comment by j2969719** [comment]
> dnrate

http://www.ign.com/wikis/pc-cheats/Duke_Nukem_3D_Cheats

**Comment by stsp** [comment]
Indeed, FPS is ~4 times lower than of dosemu-1!
What a buggy crap is our pre7...

**Comment by jschwartzenberg** [comment]
Does it matter much whether SDL is used or not? What about VGA pass-through? I guess it shouldn't be too hard to bisect some of the performance issues. For the issue I saw with Wacky Wheels, I had to use `dosemu -X` to get bisecting to go properly. Commit 096984b also fixed the performance in Tetris Classic, but with that game it wasn't as obvious as with Wacky Wheels.

**Comment by stsp** [comment]
> Does it matter much whether SDL is used or not?

Not much.
But you need debug kernel to make this
regression very visible:
```
$ uname -r
4.12.13-300.fc26.x86_64+debug
```
Maybe -X will make it easier to bisect,
I'll try when I have more time.

**Comment by stsp** [comment]
Regression seem to be somewhere around 683088db.

**Comment by stsp** [comment]
But I am not sure how real it is.
Yes, FPS measured by duke3d drops.
But it is quite possible that real FPS
increased to match the "virtual" more
precisely.

**Comment by stsp** [comment]
Should now be fixed, please check.
Horrible day of bisecting: there are
tons of changes that were introducing
the regressions that were later fixed,
but bisect was pointing to them all and
not to the needed one.

**Comment by j2969719** [comment]
indeed, thanks for you hard work

**Comment by stsp** [comment]
Does anyone know any more outstanding
regressions since pre7? If not, I'll prepare
pre8 soon.

**Comment by jschwartzenberg** [comment]
Maybe the win31 reboot hang. At least pushing the 'reboot' button before didn't cause a hang before.

**Comment by stsp** [comment]
Right, reboot should better work too.

**Comment by j2969719** [comment]
if the keyrus is loaded and i run duke3d with vesa https://pastebin.com/qLs0BbF0

**Comment by stsp** [comment]
Yes, I've seen this keyrus-related problem too.
Why do you think it is dosemu2's bug?

**Comment by stsp** [comment]
But if you are sure, please open another bug.

**Comment by stsp** [comment]
Could you please try on dosbox?

**Comment by j2969719** [comment]
yep, it's definitely keyrus.com v8.0b16 bug. same happend on dosbox svn 
with v7.3 all seems works fine

sorry

**Comment by stsp** [comment]
Thanks for confirming.
I was bothering about this strange crash too.

**Comment by j2969719** [comment]
not sure, but now looks like when i press quit in duke3d i get memory.c:566: DPMI_free: assertion mem_allocd >= PAGE_SIZE failed
[boot.log.gz](https://github.com/dosemu2/dosemu2/files/5709983/boot.log.gz)


older builds like 66dea1aaf seems works fine

**Comment by stsp** [comment]
Should now be fixed.
