### ISSUE TITLE
RFE: Use Coverity static checker

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#460]
Perhaps you would consider submitting dosemu2 to be scanned by the Coverity free checker? At one time I had a commercial licence for it and I can say it does find some interesting and perhaps unexpected bugs. I no longer have that licence but I believe the free service for OSS projects would do something similar. The link is [here](https://scan.coverity.com/projects?utf8=%E2%9C%93&search=dosemu). I'd do it myself but it should be the project owner that sets it up.

**Comment by stsp** [comment]
> I'd do it myself but it should be the project owner that sets it up.

What kind of project owner? On github?
But aren't you an owner of your repo fork?

**Comment by andrewbird** [comment]
I've just read the T's & C's again, perhaps they've relaxed them, but it seems that as Dosemu2 is not registered I can register it against my fork. Of course that means I'll have to keep it in sync with yours and it will make it difficult if you want to do it yourself at some point.

**Comment by stsp** [comment]
Please go ahead.
I am sure we'll find some recovery
if I ever want to try that myself. :)

**Comment by andrewbird** [comment]
Well, the scanning tool failed to agree with my system header files and would only scan 20% of Dosemu2, Coverity support failed to answer my question in over a week, so I'm going to stop wasting my time with it.

**Comment by stsp** [comment]
What was the problem?

**Comment by andrewbird** [comment]
Lots of these
~~~
"/usr/include/stdlib.h", line 69: error #40: expected an identifier
      union wait *__uptr;
~~~

**Comment by stsp** [comment]
Fortunately valgrind gives us the good scan,
except for cpuemu jit.
Perhaps we can also use valgrind to see for
some thread locking bugs.
