### ISSUE TITLE
dosdebug: t on an interrupt instruction loses control

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#468]
Test: run dosemu -X -H1, then in another terminal:

```
$ dosdebug

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
Reading map file nm /usr/local/bin/dosemu.bin | grep -v '\(compiled\)\|\(\.o$\)\|\( a \)' | sort
7765 symbol(s) processed
highest address 019bafd0(_end)
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
bpint 2f
g
INT 0x2F, system state: emulated,stopped
AX=1123  BX=08b6  CX=08b6  DX=03be  SI=000e  DI=03be  SP=08ae  BP=08ce
DS=9e12  ES=00d8  FS=0000  GS=0000  FL=000b3246
CS:IP=8f8d:174b       SS:SP=00d8:08ae

8f8d:174b CD2F             int  2F
t
INT 0x2F, system state: emulated,stopped
AX=1123  BX=08b6  CX=08b6  DX=03be  SI=0002  DI=03be  SP=08ae  BP=08ce
DS=9e13  ES=00d8  FS=0000  GS=0000  FL=000b3246
CS:IP=8f8d:174b       SS:SP=00d8:08ae

8f8d:174b CD2F             int  2F
```

Expected: running the interrupt, then stopping either behind the int instruction or one instruction after that.

**Comment by ecm-pushbx** [comment]
It seems that the interrupt call in question may be returning with "retf 2" and thus lose the trap flag. FreeDOS debug specifically puts an int3 type breakpoint when skipping interrupt calls: https://bitbucket.org/ecm/ldebug/src/747435d98764a440d006de4e945578e4c7092a8e/source/run.asm?at=default&fileviewer=file-view-default#run.asm-1028

**Comment by stsp** [comment]
You can use "ti" to trace into an interrupt.
Then I suppose `retf 2` will not harm.
HTH.

**Comment by stsp** [comment]
How about manually setting bp then? :)
OK, lets reopen this, but I wouldn't consider
this to be important enough.

**Comment by stsp** [comment]
Next time you will ask to step through `call`
insn - the same thing, but debugger can
really be extended infinitely.

**Comment by ecm-pushbx** [comment]
I do think some interrupt calls use the stack, yeah. And FreeDOS debug does have "p" which steps over calls or repeated string instructions.

**Comment by stsp** [comment]
We also step over repeated string instructions.

Maybe we can alter the return address and
save the real return address not to DOS stack,
but this will mean more coding.

**Comment by andrewbird** [comment]
I was thinking about whether one could automate the setting of a oneshot breakpoint on 't' when it's to execute an interrupt, but I wonder if the interrupt handler can alter its return address i.e. not iret to int's CS:IP + 2. Is that possible, if so do int handlers do it often enough to make it a waste of time?

**Comment by stsp** [comment]
I don't think its possible because the caller
is supposed to get the control back. If it doesn't
transfer the control back (say int19 that does
reboot), then we do not care about tracing it
over reboot.

**Comment by stsp** [comment]
Note that you can also change the return
address to some pre-defined location
(registered with hlt.c API) where you can
restore TF and jump to the original location.
To me that looks a bit simpler than the
temporary break-points, but of course
the implementor decides.

**Comment by andrewbird** [comment]
I'm not familiar enough with the HLT stuff to do this, but from what you say it certainly seems simpler.

**Comment by stsp** [comment]
Please see fossil.c, its really very simple.
`hlt_register_handler()` returns you an
offset which you can pass to DOS as
`BIOS_HLT_BLK_SEG:offset`, and it will
call your handler function in dosemu when
someone in DOS calls this address.

**Comment by andrewbird** [comment]
So I'm just starting to think about this and I have some questions:

1. Is installing the handler a one time thing to do or is it done once per interrupt call?
2. How is the return address changed to the one that will trigger the handler?
3. You mentioned `someone in DOS calls this address`, is the handler only triggered for calls, or will a jump to it or just moving forward onto the address enough?

**Comment by stsp** [comment]
> Is installing the handler a one time thing to do or is it done once per interrupt call?

Just once.

> How is the return address changed to the one that will trigger the handler?

By pushing 2 iret frames instead of one:
```
fake_int_to(BIOS_HLT_BLK_SEG, offset);
fake_int_to(handler_cs, handler_ip);
```

> You mentioned someone in DOS calls this address, is the handler only triggered for calls,
> or will a jump to it or just moving forward onto the address enough?

Any execution of this address is enough.

**Comment by andrewbird** [comment]
Isn't this already implemented by means of `ret_from_int`  but its setup is ifdefed out at the top of `do_int()`?

**Comment by stsp** [comment]
It was added and commented out during the
very painful initial coopth integration. I don't
remember the details, but that approach didn't
work with revectored ints, so I did some other
tricks and stunts with them 5f263dd6b.

dosdebug should install its own handler, it does
not need to mess with the coopth-specific things
like `ret_from_int`.

**Comment by andrewbird** [comment]
Okay before I start on this I thought I'll just test the original case. Only thing is I don't get the same result, I see the debugger stopping after the interrupt, but one instruction too late.

~~~
stop
system state: stopped
AX=1100  BX=0392  CX=0001  DX=0000  SI=00ee  DI=03bc  SP=0a66  BP=0a6e
DS=0070  ES=011f  FS=0000  GS=0000  FL=00003246
CS:IP=fc00:0119       SS:SP=011f:0a66

fc00:0119 F4               hlt
bpint 2f
g
INT 0x2F, system state: stopped
AX=ae00  BX=9ca2  CX=ff00  DX=ffff  SI=9f20  DI=0000  SP=a800  BP=0081
DS=9578  ES=9578  FS=0000  GS=0000  FL=000b7202
CS:IP=9578:2e47       SS:SP=9578:a800

9578:2e47 CD2F             int  2F

u 9578:2e47
9578:2e47 CD2F             int  2F
9578:2e49 3C00             cmp  al,00
9578:2e4b C3               ret
9578:2e4c A1F39F           mov  ax,[9FF3]
9578:2e4f 8B36F59F         mov  si,[9FF5]
9578:2e53 C60621A000       mov  byte [A021],00
9578:2e58 C6061DA000       mov  byte [A01D],00
9578:2e5d 8B36F59F         mov  si,[9FF5]
9578:2e61 8B0EF39F         mov  cx,[9FF3]
9578:2e65 8BD6             mov  dx,si

t
system state: stopped
AX=ae00  BX=9ca2  CX=ff00  DX=ffff  SI=9f20  DI=0000  SP=a800  BP=0081
DS=9578  ES=9578  FS=0000  GS=0000  FL=000a7346
CS:IP=9578:2e4b       SS:SP=9578:a800

9578:2e4b C3               ret
~~~

**Comment by andrewbird** [comment]
Ahh I just read @ecm-pushbx 's comment
> It seems that the interrupt call in question may be returning with "retf 2" and thus lose the trap flag. FreeDOS debug specifically puts an int3 type breakpoint when skipping interrupt calls:

So I guess I need the proper test case case!! :-)

**Comment by andrewbird** [comment]
I now wrote a quick and dirty test case (note the NOPs added after each INT as in the normal IRET case the `t` command stops one instruction too late)

```ASM
.text                                                                           
.code16                                                                         
                                                                                
    .globl  _start16                                                            
_start16:                                                                       
                                                                                
        mov $0x2523, %ax                                                        
        mov $IntHandlerCode, %dx                                                
        int $0x21                                                               
                                                                                
        nop                                                                     
                                                                                
        mov $0x9, %ah                                                           
        mov $textmain1, %dx                                                     
        int $0x21                                                               
                                                                                
        nop                                                                     
                                                                                
        int $0x23                                                               
                                                                                
        nop                                                                     
                                                                                
        mov $0x9, %ah                                                           
        mov $textmain2, %dx                                                     
        int $0x21                                                               
                                                                                
exit:                                                                           
        movb    $0x4c, %ah                                                      
        int     $0x21                                                           
                                                                                
IntHandlerCode:                                                                 
        mov $0x9, %ah                                                           
        mov $textint, %dx                                                       
        int $0x21                                                               
/*      iret */                                                                 
        retf $2                                                                 
                                                                                
textint:                                                                        
        .ascii "new Interrupt Handler...\r\n$"                                  
                                                                                
textmain1:                                                                      
        .ascii "starting in main\r\n$"                                          
                                                                                
textmain2:                                                                      
        .ascii "back in main\r\n$"                                              
```

So I see with RETF 2 instead of IRET, dosdebug does run away instead of stopping afterwards.

**Comment by stsp** [comment]
> the t command stops one instruction too late)

Does this happen when you step over this
INT, or when you do `ti` and step through,
or in both cases?

**Comment by andrewbird** [comment]
It happened with just plain `t`.
I did try with `ti` using int10/03 to avoid the in21 revect code and it seemed to work okay.

**Comment by stsp** [comment]
OK, then I guess both these problems can
be fixed with a single fix. (extra iret frame)
But some ints access their arguments via
stack, so I suppose the extra iret frame can't
be put on the same stack - the stack should
be somewhere in dosdebug.

**Comment by andrewbird** [comment]
I'm not sure where to start on this, is it still by looking at the method in fossil.c?

**Comment by stsp** [comment]
Nothing changes from what it was before.
Just instead of
```
fake_int_to(BIOS_HLT_BLK_SEG, offset);
fake_int_to(int_handler_cs, int_handler_ip);
```
you can write:
```
push_to_my_stack(_CS, _IP);
_CS = BIOS_HLT_BLK_SEG;
_IP = offset;
fake_int_to(int_handler_cs, int_handler_ip);
```

And in handler you do:
```
pop_from_my_stack(&_CS, &_IP);
```
or similar.

**Comment by andrewbird** [comment]
This code seems only to be used for `ti`, is it still the right place to do `t` too?
```C
      case 0xcd:                                                                
        if (mhpdbgc.trapcmd != 1)                                               
          break;                                                                
```

**Comment by stsp** [comment]
Why do you think so?
`!= 1` means `t`.

**Comment by andrewbird** [comment]
I meant the code after the break, but no matter I think I'm on the right track now.

**Comment by stsp** [comment]
Well, I commented it _before_ `break`. :)

**Comment by andrewbird** [comment]
See the PR something not quite right yet! :smile:
