### ISSUE TITLE
Windows 3.1 setup reboot hangs

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#469]
It seems recently dosemu started to really perform a reboot when clicking the reboot button at the end of the installation (before it would just go back to the dos prompt).

This boot hangs however, here is a screenshot:
![dosemu-win31-reboot-hang](https://user-images.githubusercontent.com/877112/30718474-51b09e3e-9f20-11e7-8dd2-b647c7799c74.png)

When I then close dosemu manually (ctrl+alt+pagedown) and start it again, it boots without issues. So it appears certain configurations hang when a reboot is triggered, but not in a fresh instance.

In the screenshot it's also visible that after this reboot, the window title still reflects the name of the program that triggered the reboot.

**Comment by stsp** [comment]
Yes, a serious regression indeed.
Thanks.

Now does anyone know about more
regressions of pre7?

**Comment by jschwartzenberg** [comment]
The installation goes further again, but there's another crash. It seems Windows can't start up after this reboot took place. I reproduced it twice, I don't think there is a significant difference between the two logs.
[win31-crash.log](https://github.com/stsp/dosemu2/files/1357107/win31-crash.log)
[boot.log](https://github.com/stsp/dosemu2/files/1357109/boot.log)

**Comment by stsp** [comment]
Could you please re-check?

**Comment by jschwartzenberg** [comment]
It works great now!
