### ISSUE TITLE
Ultima VI crashes when using VGA mode with cpu_emu = "full"/"vm86"

### ISSUE THREAD

**Issue by PaulRaul** [stsp/dosemu2#47]
With Ultima 6 configured for VGA mode, and dosemu using "full" or "vm86"  CPU emulation, the game will freeze several seconds after the publisher's logo first appears when the game is run.  

The game will run successfully if dosemu CPU emulation is set to "off".  This game does work under 1.4 with full CPU emulation, even though this appears to be a problem with how the game accesses what it thinks is VGA memory.  The game is also well behaved under other emulators such as DOSBox.

VGAEmu: vga_emu_fault: write access to some region, address 0x27a8c, page 0x27, vga page 0x0
VGAEmu: vga_emu_fault: in_dpmi 0, err 0x7, scp->cs:eip 0073:a93589db, vm86s->cs:eip 1793:00b3
VGAEmu: vga_emu_fault: cs:eip = 1793:00b3, instr: 1f 5e 5f 5d cb 55 8b ec 57 56 1e 1e 07 fc 9c fa
VGAEmu: vga_emu_fault: unhandled page fault (not in 0xa0000 - 0xc3000 range)

http://home.ix.netcom.com/~jjingber/boot-ultima6.log.bz2

URL: http://www.myabandonware.com/game/ultima-vi-the-false-prophet-11s

**Comment by PaulRaul** [comment]
To add: The game works under "full" emulation if set for EGA mode.

**Comment by stsp** [comment]
Can't reproduce.
And how can I set it up to VGA mode instead?
Your log is not complete, either.

**Comment by PaulRaul** [comment]
> Can't reproduce.
> And how can I set it up to VGA mode instead?
> Your log is not complete, either.

Run "install" from within the game dir.  I have it setup for VGA/Mouse/MT-32.

Updated log with all options enabled.

http://home.ix.netcom.com/~jjingber/boot-ultima6.log.bz2
http://home.ix.netcom.com/~jjingber/dosemu.conf

**Comment by stsp** [comment]
Terminating on signal 1

... is how your log ends.
For some reason your dosemu gets SIGHUP.
You need to find out yourself who sends a SIGHUP
to it. See dmesg for anything suspicious.
For me it works perfectly.
You can also try git bisect, but dosemu2 is especially
hard on bisecting...

**Comment by PaulRaul** [comment]
> For some reason your dosemu gets SIGHUP. 

That's me killing it off, as at this point, the game is completely frozen and stuck at a black screen (right after the "Origin" logo).  I can't even close the dosemu window through the window manager.

**Comment by stsp** [comment]
Please try to kill it with SIGSEGV:
killall -SEGV dosemu.bin
Maybe it then will log the stack trace.
Does the problem happen with "vm86sim"?

**Comment by PaulRaul** [comment]
Updated log with killall -SEGV.

http://home.ix.netcom.com/~jjingber/boot-ultima6.log.bz2

'vm86sim' does allow the game to work properly, however, it causes more problems with other software that 'full' does not.

**Comment by stsp** [comment]
> sh: 1: gdb: not found

Please fix this.

**Comment by stsp** [comment]
> 'vm86sim' does allow the game to work properly

Then the suspect is commit 095a2944d.
Please try
git checkout 095a2944d^
and see if that works (note the ^ above)

**Comment by PaulRaul** [comment]
That works.  

Updated log from head incase you still want it:

http://home.ix.netcom.com/~jjingber/boot-ultima6.log.bz2

**Comment by PaulRaul** [comment]
FWIW, this also allows Prince2 to run, also.  https://github.com/stsp/dosemu2/issues/33

**Comment by stsp** [comment]
Reproduced on my home PC.
Previously I tried on a work PC.
Interestingly, prince2 lock-up is reproducible
for me only on work PC, not at home.
Magic.
