### ISSUE TITLE
Drive still visible when deleted with lredir2

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#470]
````
install=d:\dosemu\lredir2.com z: linux\fs\${DOSEMU_LIB_DIR}\drive_z ro
install=z:\dosemu\lredir2.com -d d:
shellhigh=z:\command.com /e:1024 /p
````

I put this into my `fdconfig.sys` so I can use D: for a data drive. Checking `dir D:` before mounting the data drive still shows contents.
````
C:\>lredir2
Current Drive Redirections:
C: = \\LINUX\FS\home\user\.dosemu\drives\c\ attrib = READ/WRITE
Z: = \\LINUX\FS\usr\share\dosemu\drive_z\ attrib = READ/WRITE
cwd: /home/user/.dosemu/drives/c/
C:\>dir D:
 Volume in drive D is DRIVES D
 Volume Serial Number is 4ADD-1B8B
 
 Directory of D:\
 
KERNEL   SYS        45,344  06-21-11 11:39p
COMMAND  COM        66,945  08-28-06 10:38p
CONFIG   SYS           350  11-12-06  6:05p
AUTOEXEC BAT           473  10-29-13  9:05p
APPINFO              <DIR>  09-22-17 12:46p
BIN                  <DIR>  09-22-17 12:46p
CPI                  <DIR>  09-22-17 12:46p
DOC                  <DIR>  09-22-17 12:46p
DOSEMU               <DIR>  09-22-17 12:46p
GNU                  <DIR>  09-22-17 12:46p
HELP                 <DIR>  09-22-17 12:46p
MTCP     CFG            16  07-07-11  5:35a
NLS                  <DIR>  09-22-17 12:46p
TMP                  <DIR>  09-22-17  1:27p
         5 file(s)        113,128 bytes
         9 dir(s)   1,885,470,720 bytes free
````

Alternatively, is there a better way to make the system drive Z: and leave D: open for a data drive? I had hoped that naming the soft link ".dosemu/drives/z" would make it mount as Z: but dosemu doesn't do that. dosemu mounts drives in order C:, D:, E: no matter what they are named.

**Comment by stsp** [comment]
This is not a problem.
Please fill free to mount anything else
to D and it will be there. Or use `lredir2 -f`
to remount drive w/o unmounting.

**Comment by andrewbird** [comment]
The fact that `DIR D:` is showing the serial number indicates that you are seeing the fatfs drive underneath and that the `lredir2 -d d:` succeeded.
Within your dosemu.conf you presumably have a `$_hdimage = "drives/*` that will order (using unix globbing) whatever directories within ~/.dosemu/drives you have, but as you pointed out they will be allocated sequentially. So if you want to change the order you could specify `$_hdimage = "drives/c drives/x drives/f" but they would be allocated as `C: D: E:` This really isn't a Dosemu limitation, it's more like installing physical disks into a real system. They just get enumerated according to number of controller and master/slave setting (assuming IDE). You can't have gaps in enumeration (no C:, D:, Z:), and there are limits depending on DOS version, on the number of disks that can be identified.
Finally as Stas said you can overlay any fatfs disk letter with lredir, in any order you like. It's just the fatfs, and hdimage file assignment you can't arbitrarily set.
