### ISSUE TITLE
how to use $_vbootfloppy, $_floppy_a, $_floppy_b, -I floppy {} ?

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#473]
Could you please list examples of how to use the first three (in dosemu.conf or ~/.dosemurc) and the last one (in the dosemu command line)? Here are my attempts for the latter:

```
$ dosemu -X -I"floppy { readonly threeinch file kahn.img }" --Fimagedir .
Error in commandline: (line 001) syntax error
Error in commandline: (line 001) unrecognized floppy disk flag 'kahn.img'

Error in commandline: (line 001) disk: no device/file-name given!
3 error(s) detected while parsing the configuration-file
$ dosemu -X -I"floppy { readonly threeinch file:kahn.img }" --Fimagedir .
Error in commandline: (line 001) unrecognized floppy disk flag 'file:kahn.img'

Error in commandline: (line 001) disk: no device/file-name given!
2 error(s) detected while parsing the configuration-file
$ dosemu -X -I"floppy { readonly threeinch:kahn.img }" --Fimagedir .
Error in commandline: (line 001) unrecognized floppy disk flag 'threeinch:kahn.img'

Error in commandline: (line 001) disk: no device/file-name given!
2 error(s) detected while parsing the configuration-file
$ dosemu -v
dosemu2-2.0pre7.1-20170921-134-gb3d59a1a
$ 
```

**Comment by ecm-pushbx** [comment]
Oh, just figured out the latter by looking at

```
$ grep -ER --colour -C4 "L_FLOPPY" *
[...]
src/base/init/lexer.l-cylinders		RETURN(CYLINDERS);
src/base/init/lexer.l-tracks			RETURN(TRACKS);
src/base/init/lexer.l-heads			RETURN(HEADS);
src/base/init/lexer.l-offset			RETURN(OFFSET);
src/base/init/lexer.l:floppy			RETURN(L_FLOPPY);
src/base/init/lexer.l-cdrom			RETURN(CDROM);
src/base/init/lexer.l-diskcyl4096		RETURN(DISKCYL4096);
src/base/init/lexer.l-hdtype1			RETURN(HDTYPE1);
src/base/init/lexer.l-hdtype2			RETURN(HDTYPE2);
[...]
$ 
```

This is how to use that:

```
$ dosemu -X -I"floppy { readonly fiveinch floppy kahn.img }" --Fimagedir .
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
```

**Comment by stsp** [comment]
Where have you got `$_vbootfloppy`?
Its not there.
The use of `$_floppy_X` should be straight-forward,
namely, `$_floppy_a = "floppy.img:threeinch" which
will look up in imagedir, or I believe you can also use
an absolute path there.

**Comment by jschwartzenberg** [comment]
You can also use environment variables to configure dosemu on the commandline. From the readme:
```
All these settings are also environment variables. You can override them
by prefixing with dosemu_, e.g.
    dosemu__X_title="DOS was in the BOX" dosemu
temporarily changes the X window title
```

**Comment by stuaxo** [comment]
A while back there was talk of revamping config for dosemu, the environment variables would be much more conventional if they could be in uppercase, without the double underscore e.g.

```DOSEMU_X_TITLE="DOS was in the BOX" dosemu```

That would mean no unusual syntax to memorise.

**Comment by stsp** [comment]
> DOSEMU_X_TITLE="DOS was in the BOX" dosemu

No, you only add a prefix here.
`dosemu__X_title` consists of
`dosemu_` prefix and an option
name. So at best you can aim for
`DOSEMU_X_title` which doesn't
look like a big  improvement.

**Comment by stuaxo** [comment]
Having it mixed case would indeed be worse.

**Comment by stsp** [comment]
Yes, and option names are currently
low-case or mixed.

**Comment by stuaxo** [comment]
Hadn't thought about this - if option names were all lower case and envvars were uppercase it would make it easier to remember for the occasional user of dosemu.

I guess it may be too much change for too little gain.
