### ISSUE TITLE
free fdisk 1.31 doesn't work

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#474]
With drive C: (hd unit 80h) redirected, Free FDISK 1.31 fails to function:

```
C:\>fdisk131
 
 
Error Reading Hard Disk:
  Addressed sector not found.
 
Program Terminated.
 
C:\>
```

The following log excerpt is written during this:

```
$ dosemu -X -D9+d -O 2>&1 | grep -Ev "^MFS:|^LFN:|^FLOPPY: flushing after 1 ticks$"
[...]
INT13: ax=410f cx=000f dx=1880
INT13: ax=410f cx=0001 dx=0081
INT13: ax=410f cx=0001 dx=0082
INT13: ax=410f cx=0001 dx=0083
INT13: ax=410f cx=0001 dx=0084
INT13: ax=410f cx=0001 dx=0085
INT13: ax=410f cx=0001 dx=0086
INT13: ax=410f cx=0001 dx=0087
INT13: ax=0800 cx=0000 dx=1880
disk get parameters 0x80
INT13: ax=4800 cx=00fe dx=0080
INT13: ax=423e cx=0000 dx=c080
DISK 80 ext read [LBA 4112639](1)->180f:4324
Sector not found, read_sectors!
Real-mode state dump:
EIP: fc00:00000116 ESP: 24b0:00000f38  VFLAGS(b): 00000 00110000 01000110
EAX: 0000423e EBX: 0000feff ECX: 00000000 EDX: 0000c080 VFLAGS(h): 00003046
ESI: 000047ac EDI: 00000007 EBP: 00000f48 DS: 180f ES: 180f FS: 0000 GS: 0000
FLAGS: PF ZF IF  IOPL: 3
STACK: fe 00 00 00 3f 00 00 00 fe 00 -> c8 20 50 10 46 32 80 00 ff c0 
[...]
```

In wde, the following is shown for the MBR of unit 80h:
 ```
 Partition 1:        Partition 2:        Partition 3:        Partition 4:
 Boot  80 (Active)   Boot  00            Boot  00            Boot  00
 S-CHS 0000/001/01   S-CHS 0000/000/00   S-CHS 0000/000/00   S-CHS 0000/000/00
 Type  06 (Fat16)    Type  00 (Unused)   Type  00 (Unused)   Type  00 (Unused)
 E-CHS 0254/254/63   E-CHS 0000/000/00   E-CHS 0000/000/00   E-CHS 0000/000/00
 S-LBA 0000000063    S-LBA 0000000000    S-LBA 0000000000    S-LBA 0000000000
 Sects 0004096512    Sects 0000000000    Sects 0000000000    Sects 0000000000
```

The last accessible sector according to wde:
```
 Offset: 000 Sector: 0004096574 [1] [Data]                     CHS: 0254/254/63
```

**Comment by ecm-pushbx** [comment]
Found a fix. This is a bug in free FDISK, it checks for "an extra cylinder" in PDISKIO.C:622 but on error the handler terminates the process instead of returning to Get_Hard_Drive_Parameters. Does anyone know where to report errors in free FDISK?

```
set FFD_CHECKEXTRA=OFF
fdisk
```

**Comment by ecm-pushbx** [comment]
And Display_All_Drives (USERINT2.C:567) does something weird / confusing to calculate space_used_on_drive_in_MB. Certainly not correct.

**Comment by PerditionC** [comment]
Errors for free fdisk should be reported to FreeDOS developers list or preferably in the FreeDOS bug tracking system.  It may not seem like it, but they are looked at there, just not enough developers or time to always respond or implement fix.

**Comment by stsp** [comment]
@PerditionC 
Are there the repositories on github for this?
I've found some:
https://github.com/FDOS
but they lack fdisk, and the fact that
https://github.com/orgs/FDOS/people
list no one, is a kinda upsetting.
I think we, those who are interested in
dosemu2, should start contributing to
freedos actively or we will never achieve
our goals. But for that it must be very
clear where we should start.
Would it be possible to, for example,
enrich the aforementioned repo collection
with fdisk and the rest? Add some people
there who can be contacted, etc.
Also I wonder if https://github.com/PerditionC/fdkernel
is actual. Seems like it was not updated for
quite long, except for a couple of PRs from
myself. :) Is it a primary fdkernel repo, or at
least is in sync with one?

**Comment by andrewbird** [comment]
@stsp This [page](http://www.fdos.org/kernel/) seems to explain the situation. However the biggest problem I see is that there's no history before
~~~
commit 1cef75adce3c58fa8c6229189e2c1709da034643
Author: PerditionC <PerditionC@gmail.com>
Date:   Sun Oct 14 16:56:41 2012 -0700

    Initial commit
~~~

**Comment by stsp** [comment]
> history before

So it spans 5 years.
What I find to be the biggest problem is
that it only lists 65 commits. Lets see if I
can find some free time to change that.
At least I have a very secret plan to do so. :)

**Comment by andrewbird** [comment]
I was thinking about perhaps using git-svn to grab the sf freedos svn tree, then perhaps git filter-branch and then re-add the 65 commits. **BUT** it's probably not my business to do this :smile:

**Comment by stsp** [comment]
Why not?
I think with `git replace` you can try to
replace the first commit with the one that
references the full history. After that, maybe
you can even do a pull request. But I have
not tried that myself.

**Comment by PerditionC** [comment]
I should probably type this on a computer and not phone, but anyway.

The fdkernel on GitHub is where I do my kernel development from, and is
most current.  I will take patches from it and reapply to svn kernel before
making official releases.  They don't share a history and not directly
syncable for historical reasons.  I also merge from svn kernel to GitHub
one.  Patches can be submitted to either.  The svn source has a mailing
list that publishes all patches to it that Tom & Bart seem to watch.

The FDOS site is where I work on all the other FreeDOS software.  I
originally had it as a single svn repository on sourceforge, I have slowly
been splitting it out into individual git repositories.  Eventually I want
every program included, either as primary or fork that is replicated to
primary repository.

As you noticed, my free time is very limited.  I am happy to add any
FreeDOS developers to the FDOS users, no one has asked.  There are only a
handful of people still updating anything.

I have received more patches since I moved the code to GitHub than before,
so I would like to continue that trend.

Most of the programs were not originally under source control, so what is
there is from me checking in new releases or occasional bug fix.

Jeremy

**Comment by andrewbird** [comment]
Ooh, another redirector implementation for me to look at https://github.com/PerditionC/vbxmount

**Comment by ecm-pushbx** [comment]
https://sourceforge.net/p/freedos/bugs/ for reference

**Comment by ecm-pushbx** [comment]
https://sourceforge.net/p/freedos/bugs/196/ "usage" issue, https://sourceforge.net/p/freedos/bugs/195/ FFD_CHECKEXTRA failure

**Comment by stsp** [comment]
> I was thinking about perhaps using git-svn to grab the sf freedos svn tree, then perhaps
> git filter-branch

I did the same for dosemu now, but w/o filter-branch.
Now everyone who wants to see full dosemu history,
can add
`fetch = refs/replace/*:refs/replace/*`
to the description of `[remote "origin"]` and full
history will be available after `git pull`.
