### ISSUE TITLE
dosdebug loses trace in DPMI

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#486]
While debugging #483 I've found
that "tc" in DPMI loses trace quite
quickly.

**Comment by andrewbird** [comment]
So I'm thinking about looking at this, but I think I need more detail on what went wrong?

**Comment by andrewbird** [comment]
Using one of my djgpp compiled test programs after doing `tc` I see some normal traces, then
~~~
f800:4800 F4               hlt

CPU Exception occured, invoking dosdebug

system state: stopped in DPMI-16bit

EAX: 00000001 EBX: 000000e6 ECX: 00000800 EDX: 000007bf eflags: 00003302
ESI: 00000772 EDI: 00000081 EBP: 00000000 DS: 00af ES: 00b7 FS: 0000 GS: 0000
 CS:EIP= 00a7:00000217 SS:ESP= 00af:0000075e
CS:IP points to invalid memory
Invalid ADDR
DPMI: do_default_cpu_exception 0x01 at 0xa7:0x217 ss:sp=af:75e
DPMI: fake_pm_int() called, dpmi_pm=0x01
DPMI: switching to realmode stack, in_dpmi_rm_stack=1
DPMI: Return to dosemu at 00a7:00000217, Stack 0xaf:0x0000075e, flags=0x83302
DPMI: realmode hlt: 0xfc802
DPMI: Return from DOS Interrupt without register translation
DPMI: return from realmode procedure, in_dpmi_rm_stack=0
system state: stopped in DPMI-16bit

EAX: 00000001 EBX: 000000e6 ECX: 00000800 EDX: 000007bf eflags: 00003302
ESI: 00000772 EDI: 00000081 EBP: 00000000 DS: 00af ES: 00b7 FS: 0000 GS: 0000
 CS:EIP= 00a7:00000217 SS:ESP= 00af:0000075e
CS:IP points to invalid memory
Invalid ADDR
~~~

Is that what you were seeing?

**Comment by stsp** [comment]
No but this is a bug too.
It raises the debug exception `do_default_cpu_exception 0x01`
up to the client. Very bad.

**Comment by andrewbird** [comment]
Okay I'll package up the test and raise another bug. I'm out of my depth in DPMI stuff, so I'll look for something else(easier!) to fix.

**Comment by stsp** [comment]
DPMI and dosdebug interaction has no
complications at all. See for example dpmi.c:3678.
Try removing the `dpmi_mhp_TF` - it should
then probably stop raising the exception to client,
and will forward it always to dosdebug.
If so - the question will be why `dpmi_mhp_TF`
is not set at the right moment. But it is controlled
by dosdebug directly, no complications, context
switches, signals and all the rest people are afraid
of when talking about DPMI impl in dosemu.

**Comment by andrewbird** [comment]
raised issue #642
