### ISSUE TITLE
Windows 3.1 doesn't start after starting+quiting Borland C and 'bc' crashes dosemu when quiting it from Windows

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#488]
I installed Borland from here: https://archive.org/download/2015.02.old-dos.ru/2015.02.Abandonware.tar/Abandonware%2FBorland%20C%203.11%20%283.5%29.7z

When I run `bc` and quit it, then Windows 3.1 hangs on start up.
When I run `bc` from within Windows 3.1 and then quit it, dosemu crashes with `ERROR: general protection at 0x7f02b6b62dd0: df`.

As the Borland C installer creates a Windows program group itself, I suppose these two don't usually cause problems for each other.

**Comment by jschwartzenberg** [comment]
In 1.4 this works correctly, so it's a regression. Also `win /3` does work correctly, just `win /2` hangs.

**Comment by jschwartzenberg** [comment]
cb3c9f08d92359693aa8a5e95e7b5274053cd31e is the first bad commit
commit cb3c9f08d92359693aa8a5e95e7b5274053cd31e
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Thu Oct 5 00:19:21 2017 +0300

    dpmi: dont reset int vectors upon reboot [#469]
    
    The previous hooker does not exist on reboot, so resetting
    vectors to old location caused crash.

:040000 040000 e6209b27a9bdfacd9bb4372aca5c47d8ea0fd11f 066016b490865df17cad86aea28cb93594b10a30 M      src

**Comment by jschwartzenberg** [comment]
The crash when quitting `bc` from within Windows is also not in the revision before the first bad one. After quitting then, there's the TSR + Ctrl+C to quit message from Windows (and pressing Ctrl+C indeed goes back to Windows).

**Comment by stsp** [comment]
Should now be fixed, thanks!

**Comment by jschwartzenberg** [comment]
Indeed works great now, thanks!
