### ISSUE TITLE
keen4 sometimes crashes in remap.c

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#491]
keen4 sets display_start to the value
that does not evenly divide to scan_len:
```
(gdb) p vga.display_start
$50 = 59903
(gdb) p vga.scan_len 
$53 = 64
(gdb) p vga.display_start/64.0
$51 = 935.984375
(gdb) p (vga.display_start+1)/64.0
$52 = 936
```

So display_start is 1 byte smaller than
the value that is scan_len-aligned.
When we handle wrap, we don't have
an API in remapper to offset only source.
We have API to offset source and dest,
so to compensate, we add negative
offset to source, see render.c:427 that
passes `-len` as `src_offset`. len is
`wrap - display_start` which has reminder
of 1 when divided by scan_len:
```
(gdb) p update_offset
$54 = 5633
(gdb) p update_offset%vga.scan_len
$55 = 1
```
Unfortunately remap_mem_1() aligns
an offset to scan_len even for RFF_REMAP_RECT,
but remapper that keen uses (gen_4to32_all)
is RFF_REMAP_LINES, so aligning is unavoidable
in that case. So far so good, but the problem is
that aligned offset does not fully compensate the
negative offset we passed for src image start, so
at the end we touch src[-1]. If `vga.mem.base`
happens to start at the page boundary, this
causes crash...
I guess as a first step I should add the guard
page before vga mem so that keen to crash
always rather than once in a year, and declare
the new regression.

**Comment by stsp** [comment]
OK, keen4 now crashes reliably.

**Comment by jschwartzenberg** [comment]
Is this also related to the crappy scrolling in vgaemu with keen456? (The CGA versions do not have this problem.)

**Comment by stsp** [comment]
Likely not, however I haven't looked at
how keen does scrolling.

**Comment by jschwartzenberg** [comment]
Where is it supposed to crash? (It doesn't crash here.)

**Comment by stsp** [comment]
Enter the first village and run towards
the jumping ball. When you run over
the small hill before jumping ball, it will
crash.

**Comment by stsp** [comment]
I added the work-around.
Now when you run to that hill, you'll
see the visual artefact: a horizontal
line in the middle of the screen, but
no crash. There is also a great improvement:
the similar horizontal line that was when
keen enters the house, is no longer there,
and the artefact that this patch adds, has a
clear explanation in the code comments, so
there would be no need to debug it.

**Comment by jschwartzenberg** [comment]
I wonder if this work-around will really be useful as long as the scrolling issues are not fixed. To see what scrolling is supposed to be like, play the game with either VGA pass-through or DOSBox.
Note that many VGA emulators have difficulty with Commander Keen 4's scrolling.

**Comment by stsp** [comment]
The work-around is needed to fix crash.
I've run now under dosbox, and the intro
is completely broken it seems. And in game
I can't see any differences.
Maybe you can record videos?

**Comment by jschwartzenberg** [comment]
Yep, I'll look into that. The scrolling should be smooth, there used to be a lot of stuttering and shaking, especially when the score box was enabled it was visible.

**Comment by jschwartzenberg** [comment]
I haven't found a way to record videos yet, but when I run it in DOSBox here, I do not see any issues. With latest Git from here, there is a lot of stuttering already at the very beginning.

Which version of Commander Keen 4 do you have? I'm using 1.4 now.

**Comment by jschwartzenberg** [comment]
This video seems to show pretty well what the scrolling should be like:
https://www.youtube.com/watch?v=iKHUOKVzo0Q

For instance the score box is completely still in the video, in dosemu it shakes when there is horizontal scrolling (with vertical scrolling on the Shadowlands map it seems to be ok).

**Comment by stsp** [comment]
Hmm, I think distros provide some bad
build of dosbox then. Thanks for the video.
Feel free to open a ticket.
