### ISSUE TITLE
dosdebug u with only an offset specified acts strangely

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#494]
I don't know what it disassembles there (the all-zeros run), but it certainly isn't 0:0 (even though these addresses are listed) nor cs:e05d (F000:E05D). Note that the repeated u after the odd one does actually disassemble 0:20.

```
$ dosdebug

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
Reading map file nm /usr/local/bin/dosemu.bin | grep -v '\(compiled\)\|\(\.o$\)\|\( a \)' | sort
7627 symbol(s) processed
highest address 019d0f50(_end)
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
u f000:e05d

f000:e05d B008             mov  al,08
f000:e05f CDE6             int  E6
f000:e061 3C00             cmp  al,00
f000:e063 740A             je   E06F ($+a)
f000:e065 1E               push ds
f000:e066 2EFF1E00D0       call far word cs:[D000]
f000:e06b 1F               pop  ds
f000:e06c FB               sti
f000:e06d EB04             jmp  short E073 ($+4)
f000:e06f B003             mov  al,03
f000:e071 CD10             int  10
f000:e073 B009             mov  al,09
f000:e075 CDE6             int  E6
f000:e077 B005             mov  al,05
f000:e079 CDE6             int  E6
f000:e07b 2E8A1609D0       mov  dl,cs:[D009]


f000:e080 B0FC             mov  al,FC
f000:e082 CDE6             int  E6
f000:e084 EA007C0000       jmp  0000:7C00
f000:e089 0000             add  [bx+si],al
f000:e08b 0000             add  [bx+si],al
f000:e08d 0000             add  [bx+si],al
f000:e08f 0000             add  [bx+si],al
f000:e091 0000             add  [bx+si],al
f000:e093 0000             add  [bx+si],al
f000:e095 0000             add  [bx+si],al
f000:e097 0000             add  [bx+si],al
f000:e099 0000             add  [bx+si],al
f000:e09b 0000             add  [bx+si],al
f000:e09d 0000             add  [bx+si],al
f000:e09f 0000             add  [bx+si],al
u e05d

0000:0000 0000             add  [bx+si],al
0000:0002 0000             add  [bx+si],al
0000:0004 0000             add  [bx+si],al
0000:0006 0000             add  [bx+si],al
0000:0008 0000             add  [bx+si],al
0000:000a 0000             add  [bx+si],al
0000:000c 0000             add  [bx+si],al
0000:000e 0000             add  [bx+si],al
0000:0010 0000             add  [bx+si],al
0000:0012 0000             add  [bx+si],al
0000:0014 0000             add  [bx+si],al
0000:0016 0000             add  [bx+si],al
0000:0018 0000             add  [bx+si],al
0000:001a 0000             add  [bx+si],al
0000:001c 0000             add  [bx+si],al
0000:001e 0000             add  [bx+si],al


0000:0020 A5               movsw
0000:0021 7E00             jle  0023 ($+0)
0000:0023 F8               clc
0000:0024 87E9             xchg cx,bp
0000:0026 00F0             add  al,dh
0000:0028 00F1             add  cl,dh
0000:002a 00F0             add  al,dh
0000:002c 0DC000           or   ax,00C0
0000:002f F00E             lock push cs
0000:0031 C000F0           rol  byte [bx+si],F0
0000:0034 0FC000           xadd [bx+si],ax
0000:0037 F010C0           lock adc al,al
0000:003a 00F0             add  al,dh
0000:003c 11C0             adc  ax,ax
0000:003e 00F0             add  al,dh
u 0:0

0000:0000 02C0             add  al,al
0000:0002 00F0             add  al,dh
0000:0004 03C0             add  ax,ax
0000:0006 00F0             add  al,dh
0000:0008 04C0             add  al,C0
0000:000a 00F0             add  al,dh
0000:000c 05C000           add  ax,00C0
0000:000f F006             lock push es
0000:0011 C000F0           rol  byte [bx+si],F0
0000:0014 07               pop  es
0000:0015 C000F0           rol  byte [bx+si],F0
0000:0018 08C0             or   al,al
0000:001a 00F0             add  al,dh
0000:001c 09C0             or   ax,ax
0000:001e 00F0             add  al,dh


0000:0020 A5               movsw
0000:0021 7E00             jle  0023 ($+0)
0000:0023 F8               clc
0000:0024 87E9             xchg cx,bp
0000:0026 00F0             add  al,dh
0000:0028 00F1             add  cl,dh
0000:002a 00F0             add  al,dh
0000:002c 0DC000           or   ax,00C0
0000:002f F00E             lock push cs
0000:0031 C000F0           rol  byte [bx+si],F0
0000:0034 0FC000           xadd [bx+si],ax
0000:0037 F010C0           lock adc al,al
0000:003a 00F0             add  al,dh
0000:003c 11C0             adc  ax,ax
0000:003e 00F0             add  al,dh
u 0:20

0000:0020 A5               movsw
0000:0021 7E00             jle  0023 ($+0)
0000:0023 F8               clc
0000:0024 87E9             xchg cx,bp
0000:0026 00F0             add  al,dh
0000:0028 00F1             add  cl,dh
0000:002a 00F0             add  al,dh
0000:002c 0DC000           or   ax,00C0
0000:002f F00E             lock push cs
0000:0031 C000F0           rol  byte [bx+si],F0
0000:0034 0FC000           xadd [bx+si],ax
0000:0037 F010C0           lock adc al,al
0000:003a 00F0             add  al,dh
0000:003c 11C0             adc  ax,ax
0000:003e 00F0             add  al,dh


```

**Comment by andrewbird** [comment]
Yes, that seems wrong. Can I assume that you expect `u e05d` to disassemble `cs:e05d`?

**Comment by ecm-pushbx** [comment]
Yes.

**Comment by andrewbird** [comment]
I did have a further thought, perhaps `u offset` should disassemble in whatever segment the previous `u` was in, so for example:

```
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

u c800:0050
c800:0000 0000             add  [bx+si],al
c800:0002 0000             add  [bx+si],al
c800:0004 0000             add  [bx+si],al
c800:0006 0000             add  [bx+si],al
c800:0008 0000             add  [bx+si],al
c800:000a 0000             add  [bx+si],al
c800:000c 0000             add  [bx+si],al
c800:000e 0000             add  [bx+si],al
c800:0010 0000             add  [bx+si],al
c800:0012 0000             add  [bx+si],al
c800:0014 0000             add  [bx+si],al
c800:0016 0000             add  [bx+si],al
c800:0018 0000             add  [bx+si],al
c800:001a 0000             add  [bx+si],al
c800:001c 0000             add  [bx+si],al
c800:001e 0000             add  [bx+si],al

u 1200
c800:1200 0000             add  [bx+si],al
c800:1202 0000             add  [bx+si],al
c800:1204 0000             add  [bx+si],al
c800:1206 0000             add  [bx+si],al
c800:1208 0000             add  [bx+si],al
c800:120a 0000             add  [bx+si],al
c800:120c 0000             add  [bx+si],al
c800:120e 0000             add  [bx+si],al
c800:1210 0000             add  [bx+si],al
c800:1212 0000             add  [bx+si],al
c800:1214 0000             add  [bx+si],al
c800:1216 0000             add  [bx+si],al
c800:1218 0000             add  [bx+si],al
c800:121a 0000             add  [bx+si],al
c800:121c 0000             add  [bx+si],al
c800:121e 0000             add  [bx+si],al
```
In your example it would amount to the same, but perhaps it's more useful? Or perhaps we just need to check the validity of the address and error out when the segment is not specified, after all the user can prefix the address with the correct segment or even a register? Is the shorthand useful, what do you think @stsp ?

**Comment by stsp** [comment]
> I did have a further thought, perhaps u offset should
> disassemble in whatever segment the previous u was in, so for example:

This doesn't look too useful now, when you
already allowed u w/o args to continue previous
disasm. But it will definitely add complexity, so
unless you really want to implement that, I see
no use.

I also wonder if it makes sense to use CS by
default. Initially it looks like a useful feature for
COM files, but in practice you rarely stop at
the segment you want to disassemple, I think
this mostly only happens after bpint, because
we made it to stop before the int instruction.
So even that change will IMHO have fewer use
than the added complexity.

> and error out when the segment is not specified

Likely so, but I think @ecm-pushbx reports a bug.
He has `0000:0000 0000             add  [bx+si],al`
and `0000:0000 02C0             add  al,al`
at the same time!
So the question is not what it should do, but rather
what it does and why.

**Comment by andrewbird** [comment]
Yep, I got it's wrong. I'm just trying to establish what the expected behaviour is.

**Comment by stsp** [comment]
This is up to implementor, but I think we need
the simple solutions these days, or no one is to
code them up. :)

**Comment by andrewbird** [comment]
So it seems `mhp_getadr()` returns the plain hex value if there's no colon in the ADDR, but it sets seg and ofs to zero. I think that's where the disparity comes in.
```C
       if (!(srchp = strchr(a1, ':'))) {                                        
          sscanf(a1, "%lx", &ul1);                                              
          *s1 = 0;                                                              
          *o1 = 0;                                                              
           return ul1;                                                           
       }                                                                        
```
This looks purposeful to handle a single value, is it for unix or linear mode entry? If so should I check the mode and return error if dos?

**Comment by stsp** [comment]
I think this was supposed to return linear
address instead of the segmented one,
regardless of the mode. So will it help to
just fill in s1/o1 based on the address at
hands?

**Comment by andrewbird** [comment]
Okay I wrote a patch for `u` but since `mhp_getadr()` returns zero value to indicate error, potentially all callers will see this problem. It also prevents the user doing `u 0000:0000`
```C
diff --git a/src/tools/debugger/mhpdbgc.c b/src/tools/debugger/mhpdbgc.c
index 7e47dac9..f4b8dd12 100644
--- a/src/tools/debugger/mhpdbgc.c
+++ b/src/tools/debugger/mhpdbgc.c
@@ -822,6 +822,10 @@ static void mhp_disasm(int argc, char * argv[])
 
    if (argc > 1) {
       seekval = mhp_getadr(argv[1], &seg, &off, &limit);
+      if (seekval == 0) {
+         mhp_printf("Invalid ADDR\n");
+         return;
+      }
       strcpy(lastu, argv[1]);
    } else {
       if (!strlen(lastu)) {
@@ -1067,11 +1071,12 @@ static unsigned int mhp_getadr(char * a1, unsigned int * s1, unsigned int *o1, u
           *o1 = 0;
           return ul1;
        }
-       if (!(srchp = strchr(a1, ':'))) {
+       srchp = strchr(a1, ':');
+       if (!srchp) {
           sscanf(a1, "%lx", &ul1);
           *s1 = 0;
           *o1 = 0;
-          return ul1;
+          return (linmode == 0) ? 0 : ul1;
        }
        if ( (seg1 = mhp_getreg(a1)) == -1) {
                *srchp = ' ';
```
Ideally `mhp_getadr()` would not mix error state with returned value

**Comment by andrewbird** [comment]
Sorry, missed your last comment. How can I turn a linear address into the correct seg:ofs, isn't it a conversion with many possible values?

**Comment by stsp** [comment]
Try normalized pointer, it offloads only
4 bits to offset and the rest to segment.

**Comment by ecm-pushbx** [comment]
> He has `0000:0000 0000 add [bx+si],al` and `0000:0000 02C0 add al,al` at the same time!

*She

FreeDOS debug uses cs for the only-offsets-given case and u_addr for no address given. The latter is initialised to cs:(e)ip by dumpregs (r command or after execution returns to the debugger).

**Comment by andrewbird** [comment]
@ecm-pushbx it seems that dosdebug allows a user to enter ADDR values in seg:ofs, dos linear, or unix format whatever the current `mode` setting is. So it seems that if there's no colon then the address is interpreted as linear (i suspect later the mode is checked to determine dos or linux). I'm not particularly keen on this myself (why have `mode` if it's not respected ?). I'm coding something up at the moment, but I expect in your case something to happen like:
```
system state: emulated,stopped
AX=0001  BX=7c00  CX=0001  DX=0180  SI=07be  DI=7dfe  SP=7c00  BP=07be
DS=0000  ES=0000  FS=0000  GS=0000  FL=000b3346
CS:IP=0000:7c40       SS:SP=0000:7c00

0000:7c40 B8FD80           mov  ax,80FD
u e05d

0e05:000d 0000             add  [bx+si],al
0e05:000f 0000             add  [bx+si],al
0e05:0011 0000             add  [bx+si],al
0e05:0013 0000             add  [bx+si],al
0e05:0015 0000             add  [bx+si],al
0e05:0017 0000             add  [bx+si],al
0e05:0019 0000             add  [bx+si],al
0e05:001b 0000             add  [bx+si],al
0e05:001d 0000             add  [bx+si],al
0e05:001f 0000             add  [bx+si],al
0e05:0021 0000             add  [bx+si],al
0e05:0023 0000             add  [bx+si],al
0e05:0025 0000             add  [bx+si],al
0e05:0027 0000             add  [bx+si],al
0e05:0029 0000             add  [bx+si],al
0e05:002b 0000             add  [bx+si],al
u

0e05:002d 0000             add  [bx+si],al
0e05:002f 0000             add  [bx+si],al
0e05:0031 0000             add  [bx+si],al
0e05:0033 0000             add  [bx+si],al
0e05:0035 0000             add  [bx+si],al
0e05:0037 0000             add  [bx+si],al
0e05:0039 0000             add  [bx+si],al
0e05:003b 0000             add  [bx+si],al
0e05:003d 0000             add  [bx+si],al
0e05:003f 0000             add  [bx+si],al
0e05:0041 0000             add  [bx+si],al
0e05:0043 0000             add  [bx+si],al
0e05:0045 0000             add  [bx+si],al
0e05:0047 0000             add  [bx+si],al
0e05:0049 0000             add  [bx+si],al
0e05:004b 0000             add  [bx+si],al
```

So whilst it fixes the consistency issue of printing wrong code for addresses, it's not that useful. BTW my other 'solution' just outlawed single addresses in DOS mode for least surprise.

**Comment by stsp** [comment]
> I'm not particularly keen on this myself (why have mode if it's not respected ?).

Yes, why? We can reduce it to DOS-only,
and segmented/linear can just be guessed.
I don't know why unix addresses are important
in dosdebug at all. That was added in 04377219
(just in 2009) and I suspect Bart used that for
some internal debugging of dosemu on 64bit.
Hardly someone else needs this.

> So whilst it fixes the consistency issue of printing wrong code for addresses, it's not that useful.

What's wrong with the example you quoted?
Looks like normalized pointers.
We can of course go for other alternatives
the way @ecm-pushbx suggests, but then
we have to first eliminate the linear addressing
completely (i.e. remove `mode`). Then we have
much more freedom on what we can do with
the entered addresses. Probably linear addresses
still make sense for DPMI, so `mode` can be
used only in dpmi for example.

**Comment by stsp** [comment]
> *She

Acknowledged, but google seems to resolve you under the name "Christian".

**Comment by ecm-pushbx** [comment]
> Acknowledged, but google seems to resolve you under the name "Christian".

That's wrong, but I can't change it everywhere.

**Comment by stsp** [comment]
What's the status of this?
Can we close?

**Comment by andrewbird** [comment]
The problem I see here is that we have a generic address parsing routine (`mhp_getadr`) and for us to successfully parse `u 404e` as being the offset in the current code segment we have to 
- change the default behaviour of addresses without a colon being interpreted as dos linear to be offset only. I don't think this is too much of a problem as long as we can override it.
- either
  -  add a hint to the `mhp_getadr()` that the caller want the segment to be CS in this case. For example do people expect that `d 404e` is `ds:404e`?
  -  fixup the argument to be cs:404e before sending it to `mhp_getadr()` in the case of disassemble

I guess it's down to the users of dosdebug to decide the course of least surprise?

**Comment by andrewbird** [comment]
The bug was fixed. Dos linear are still accepted.

**Comment by stsp** [comment]
So I don't think anything useful can be
done here if linear addresses are still
accepted, as you can't distinguish it with
an offset.
So if the original bug is fixed - close?

**Comment by andrewbird** [comment]
Fine from me to close, what about @ecm-pushbx ?

**Comment by stsp** [comment]
I think she only reported bug and is not
interested in the rest.

**Comment by ecm-pushbx** [comment]
Actually testing it with the most recent revision, many "u" usages crash dosemu! This includes some of the commands I specified in the original report here. Refer to https://github.com/stsp/dosemu2/issues/653

**Comment by ecm-pushbx** [comment]
In lDebug, "u" uses the 48-bit u_addr (set initially and by "r" to point to the current cs:(e)ip), "u xxxx" uses cs:xxxx, "u yyyy:xxxx" uses yyyy:xxxx. All of them eventually update u_addr to point behind the last disassembled instruction. lDebug generally doesn't do linear addresses (except debugx's "dx" which only accepts linear addresses).

**Comment by ecm-pushbx** [comment]
Oh, and an empty line after any "u" is the same as typing "u" without parameters, ie it continues disassembly from u_addr.

**Comment by andrewbird** [comment]
I'll take a look, obviously I messed something up!

**Comment by ecm-pushbx** [comment]
> add a hint to the mhp_getadr() that the caller want the segment to be CS in this case. For example do people expect that d 404e is ds:404e?

In lDebug, "d" (or empty line repetition) uses d_addr, and "d xxxx" uses ds:xxxx.

**Comment by stsp** [comment]
So this looks fixed.
