### ISSUE TITLE
No keyboard control in Foxpro

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#495]
Commit c17c348 broke Foxpro. It loads to a prompt fine. There is no keyboard control.
````
2017-10-14 17:31 Stas Sergeev          o pic: revert 5ee681aa [#155]
````

**Comment by stsp** [comment]
Damn!
How did it got to devel?
It was supposed to sit in a separate branch! :(
Shit.
Lets rewrite devel then...

**Comment by stsp** [comment]
So I rewritten devel now.
Sorry to everyone for this inconvenience. :(
I don't know how this lipped in, had to sleep
better...

**Comment by stsp** [comment]
Thanks for your testing!

**Comment by stsp** [comment]
I wonder if launchpad builds will survive or
break on branch rewrite. Lets wait and see.

**Comment by stsp** [comment]
So now the commit in question is here:
https://github.com/stsp/dosemu2/commit/a99f66ac259779a510978509feeefad16ec94395
as it was supposed to be.
