### ISSUE TITLE
what happened to github's notification feed?

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#496]
I used to watch the summary of changes
at `https://github.com/` - it was showing the
feed with any new comments, wiki editing
etc of the projects I am watching.
Now, 20.10.17, the last events are:
```
@andrewbird
andrewbird edited a wiki page in stsp/dosemu2
14 days ago

    Edited MFS rework View the diff »

@j2969719
j2969719 starred stsp/dosemu2
on 17 Sep

@andrewbird
andrewbird edited a wiki page in stsp/dosemu2
on 11 Sep

    Edited MFS rework View the diff »

@andrewbird
andrewbird edited a wiki page in stsp/dosemu2
on 11 Sep

    Edited MFS rework View the diff »
```

There were many new events seen, but
nothing is shown. Can someone else confirm
the problem?

**Comment by andrewbird** [comment]
I just tweaked the wiki twice. I wouldn't expect any notification as I did it, but I would expect you to see something?

**Comment by stsp** [comment]
Yes, the feed have updated, thanks.
But there is no more notifications there
about new comments! If from now on it
will only notify about wiki updates, this is
a hell.

**Comment by stsp** [comment]
I've found the new location of notifications:
https://github.com/notifications
