### ISSUE TITLE
Some games don't start on my OpenSUSE system (fixed by running 1.5.0 tag)

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#500]
I have a weird problem on my OpenSUSE 42.3 system (doesn't happen on my notebook with Ubuntu 16.04).

When I run games like Speedy and Jungle Book, they just hang with 100% CPU usage, the title screen doesn't even show up.
Then I revert to 1.5.0 and they work.
Then I go back to the new revision and they work in the new version as well (so when bisecting it was always working).
Then I go to sleep (left my notebook on) and wake up around 9 hours later.
Then I try Speedy and Jungle Book in the new version and they don't start again.

It happens with both 'emulated' and 'kvm'.

Is there any kind of log that might be useful in figuring out what could cause this?

**Comment by stsp** [comment]
Try `git cherry-pick pic_revert`

**Comment by jschwartzenberg** [comment]
That doesn't help. I tried the cherry-pick with the devel branch and I also tried it with `git checkout pic_revert`.

**Comment by stsp** [comment]
Try attaching dosdebug and with `t` see
what does it do.

**Comment by jschwartzenberg** [comment]
I get this then:
```
stop
system state: stopped in real mode while in DPMI
AX=0073  BX=02d3  CX=0004  DX=00d1  SI=035a  DI=0004  SP=0f22  BP=0f40
DS=00d1  ES=ffff  FS=00d1  GS=9f19  FL=00003246
CS:IP=fc00:011d       SS:SP=00d1:0f22

fc00:011d F4               hlt
t
system state: stopped in real mode while in DPMI
AX=0000  BX=02d3  CX=000d  DX=43dd  SI=035a  DI=0004  SP=0f22  BP=0f40
DS=00d1  ES=ffff  FS=00d1  GS=9f19  FL=00003346
CS:IP=fc00:0102       SS:SP=00d1:0f22

fc00:0102 F4               hlt
```

**Comment by stsp** [comment]
So its DPMI, then please attach the
good and bad `-D9+M` logs.

**Comment by stsp** [comment]
Also what CPU does your notebook have?
If its some kind of VIA, then that would be
an interesting aspect too.

**Comment by jschwartzenberg** [comment]
No VIA here, this is the CPU: Intel(R) Core(TM) i3 CPU M 370  @ 2.40GHz. I'll arrange the logs.

**Comment by jschwartzenberg** [comment]
Here is a bad and a good log. This time it didn't work yet when I reverted after testing with 1.4, so I attached the good log from 1.4. I hope this is ok, otherwise I'll try to get a good log with the latest version.
[boot.log-issue500-D9+M-bad.gz](https://github.com/stsp/dosemu2/files/1425162/boot.log-issue500-D9.M-bad.gz)
[boot.log-issue500-D9+M-14good.gz](https://github.com/stsp/dosemu2/files/1425163/boot.log-issue500-D9.M-14good.gz)

**Comment by jschwartzenberg** [comment]
Here's a good log with the latest version:
[boot.log-issue500-D9+M-good.gz](https://github.com/stsp/dosemu2/files/1425567/boot.log-issue500-D9.M-good.gz)

**Comment by stsp** [comment]
Please list all affected programs.
Are they all DPMI-enabled?

**Comment by jschwartzenberg** [comment]
I've had the issue only with Jungle Book and Speedy so far. I think both use DPMI. I could test more to see if more software is affected.

**Comment by stsp** [comment]
Test win31 and other DPMI things.

**Comment by stsp** [comment]
If this is limited to the 1-2 buggy games,
then may not be very interesting.

**Comment by jschwartzenberg** [comment]
Alright, I will install more games on this notebook. On my other notebook I have a whole collection of games, but it seems useful to have them on both. The strangest thing to me is that dosemu behaves so differently on different systems.

**Comment by stsp** [comment]
We don't know yet. 1-2 buggy games
do not stay for "behaves so differently",
esp if you can "fix" the problem by just
running another dosemu version first.

**Comment by stsp** [comment]
Is this still a problem?

**Comment by stsp** [comment]
If you are bisecting something unreliable,
you can try 5 runs after each bisect cycle.

**Comment by stsp** [comment]
Please reopen if its still the problem.
