### ISSUE TITLE
Int13/04 verify on fatfs

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#503]
When testing pcmos booting from floppy, but having a fatfs disk defined I see errors posted when pcmos tries to verify 0\0\0 sector.
~~~
DISK 80 test [h:0,s:0,t:0](1)                                                   
ERROR: test: sector @(-8704) not found 6                                        
INT13: ax=0001 cx=0001 dx=0080                                                  
DISK 80 init                                                                    
INT13: ax=0201 cx=0001 dx=0080                                                  
DISK 80 read [h:0,s:0,t:0](1)->6a41:0676                                        
DISK: /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos: Trying to read 1 sectors at LBA 0-8704 at pos -8704
read 0x200 bytes from MBR, ofs = 0x0 (0x0 bytes left)                           
   got entire read done from memory. off:0, count:512                           
~~~

I believe that's because it's adding on the negative offset of the partition start, but in this case I think it wants to actually test MBR. Since this is fatfs do we need a special case to return okay if the request is for sector 0?

**Comment by stsp** [comment]
Had to rewrite some brain-damaged code before
being able to answer this. Could you review the
patch in branch `disk_sec`?

**Comment by andrewbird** [comment]
I was about to say no regressions on the tests and it fixed the whinges on pcmos, **BUT** it's changed so I'll need to test again.

**Comment by andrewbird** [comment]
Looks good to me, thanks.

**Comment by stsp** [comment]
Thanks!
So what do we have?
Could you please provide an
updated status to #502?

**Comment by stsp** [comment]
By the way, we can as well allow
writing to mbr (in memory) and then
verify will not be no-op too. I was
just too lazy to code this up today. :)
Should be very small change.
