### ISSUE TITLE
dosdebug 'tc' strange register values

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#504]
When checking out a disk get parameters call, I see strange return register values in dosdebug after the int 13 call when using dosdebug's 'tc' command. If I instrument the code with show_regs the values are as expected, but in dosdebug they appear odd.

log file
~~~
INT13: ax=0840 cx=0064 dx=7980                                                  
disk get parameters 0x80                                                        
Real-mode state dump:                                                           
EIP: fc00:00000116 ESP: 6b61:00000d6c  VFLAGS(b): 00000 00110000 01000110       
EAX: 00000000 EBX: 00002ca0 ECX: 00003151 EDX: 00000301 VFLAGS(h): 00003046     
ESI: 00000040 EDI: 00000e5f EBP: 00000e76 DS: 6a41 ES: 6b61 FS: 0000 GS: 0000   
FLAGS: PF ZF IF  IOPL: 3                                                        
STACK: 76 0e 41 6a 40 08 15 c0 00 f0 -> ef 16 f1 76 46 32 4e 17 ca 13           
~~~

dosdebug 'tc'
~~~
76f1:2cbf B408             mov  ah,08                                           
AX=0840  BX=2ca0  CX=0064  DX=796a  SI=0040  DI=0e5f  SP=0d7e  BP=0e76          
DS=6a41  ES=6b61  FS=0000  GS=0000  FL=000a3306                                 
CS:IP=76f1:2cc1       SS:SP=6b61:0d7e                                           
                                                                                
76f1:2cc1 B280             mov  dl,80                                           
AX=0840  BX=2ca0  CX=0064  DX=7980  SI=0040  DI=0e5f  SP=0d7e  BP=0e76          
DS=6a41  ES=6b61  FS=0000  GS=0000  FL=000a3306                                 
CS:IP=76f1:2cc3       SS:SP=6b61:0d7e                                           
                                                                                
76f1:2cc3 CD13             int  13                                              
AX=6a02  BX=0e5f  CX=0064  DX=7926  SI=0070  DI=0e5f  SP=0e26  BP=0e76          
DS=76f1  ES=6b61  FS=0000  GS=0000  FL=000a3306                                 
CS:IP=76f1:3cc4       SS:SP=6b61:0e26                                           
                                                                                
76f1:3cc4 5B               pop  bx                                              
~~~

AX looks odd, should be zero
BX ??
What about the return address - looks to be 0x1000 too high?

**Comment by andrewbird** [comment]
Hold fire on this, the problem was seen with my dosdebug-09 branch. For now, seeing as the standard dosdebug pipes are lossy, I haven't yet been able to confirm that it occurs with devel version.

**Comment by stsp** [comment]
> What about the return address - looks to be 0x1000 too high?

0xfff too high, to be precise, as `int` opcode is 2 bytes.
So this is just an output lost, `tc` should go to the file.
Lets close then.

**Comment by stsp** [comment]
How about just dumping the dosdebug output
to the log file? Whether is it tc or not. This will
solve all the problem, won't it?

**Comment by andrewbird** [comment]
Since I saw it on my [dosdebug-09](https://github.com/andrewbird/dosemu2/tree/dosdebug-09) branch, I don't think I lost any output as it's dumping all from mhp_send() to a file, so not crossing pipe or socket etc. But I can't say I didn't introduce a bug elsewhere when converting to use socket etc.

**Comment by stsp** [comment]
But why would you need the conversion at
all if you can instead dump tc to the log file?
Much fewer work.
