### ISSUE TITLE
LFN: Creating a new file for writing with long filename fails on all DOS versions

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#517]
MFS/LFN new file create routine is a two step process (longfilename is created in Unix, then short filename is opened in DOS). It seems that the file is created by Unix, but the DOS open fails.

See the following example [lfnwrite.zip](https://github.com/stsp/dosemu2/files/1435420/lfnwrite.zip)

**Comment by stsp** [comment]
You mean it never worked or what?

**Comment by andrewbird** [comment]
Never worked as long as I've been testing it.

**Comment by andrewbird** [comment]
And git blame on that part of lfn.c shows dates 2003-2007

**Comment by andrewbird** [comment]
Oh I forgot to say, the lfntest.c is compiled with djgpp and so has automatic LFN support within the open() call.

**Comment by andrewbird** [comment]
I wonder it this can be done a little differently
# now
~~~
Intercept the int 21 0x716c open call
Spot it's trying to create a LFN file
Create the LFN file in unix
Generate SFN
Offload to asm handler (with special flag)
asm handler notices the special flag and changes int21/0x6c Create into Open call of SFN
calls int21/0x6c Open with SFN
asm handler fixes up the cx value to indicate create instead of open
asm handler does iret with handle and cx value
~~~

# proposal
~~~
Intercept the int 21 0x716c open call
Spot it's trying to create a LFN file
Generate SFN (or temporary name) and save LFN for later
Offload to asm handler
asm handler calls int21/0x6c Create with SFN
asm handler saves handle and cx
asm handler calls int 21/0x7156 to rename SFN to LFN
asm handler retrieves file handle and cx value
asm handler does iret with handle and cx value
~~~

I see the advantages that
- file is created with correct DOS file permissions by DOS
- no changing of create/open values

**Comment by stsp** [comment]
I am surprised its that bad. :)
Why such a complexity?
Just create SFN in DOS and then, if
needed, rename to LFN in unix, no?

**Comment by andrewbird** [comment]
Yes renaming in unix would be best, but since the asm handler does `iret` I wasn't sure we could regain control?

**Comment by andrewbird** [comment]
Also my proposal relies upon DOS not caring about renaming and open file, would that be a problem?

**Comment by stsp** [comment]
Asm helper can call another inte6 helper
after calling int21.
But you can even do this in a single step!
All creations, even for SFN, come to MFS.
So why not simply un-mangle SFN when
creating? You can save LFN somewhere
before that.

**Comment by stsp** [comment]
So:
1. Unix creates LFN
2. Unix calls DOS to create SFN.
3. MFS sees the mangled SFN and
matches it to the already created LFN - bingo! :)

**Comment by stsp** [comment]
So basically you can just remove this step
from the currently existing ones:
`asm handler notices the special flag and changes int21/0x6c Create into Open call of SFN
calls int21/0x6c Open with SFN`

**Comment by stsp** [comment]
Even simpler technique:
1. Unix creates LFN
2. Unix calls DOS to create "LfNHack.SFN" file (literally)
3. MFS sees "LfNHack.SFN" and realizes that it should
just return success.

Is this simple enough? :)

**Comment by andrewbird** [comment]
So just to be sure
> 1. Unix creates LFN

Q: You do mean the filename in the cache and not the file? If so how is this done?

> 2. Unix calls DOS to create "LfNHack.SFN" file (literally)

I'm okay with this.

> 3. MFS sees "LfNHack.SFN" and realizes that it should just return success.

Q: Do you mean MFS sees request for "LfnHack.SFN" create, but actually creates LFN file?

**Comment by stsp** [comment]
Another idea:
1. Unix stores pointer to LFN in bios area, lets call is `LFN_ptr`.
2. Unix calls DOS to create mangled SFN -
note that SFN name resides in `LFN_short_name`
in bios.S.
3. MFS checks if DS:SI points to `LFN_short_name`,
and if so - picks up LFN from `LFN_ptr`!

I think this is absolutely great because it will
allow to move LFN handling behind MFS.

**Comment by stsp** [comment]
> Q: You do mean the filename in the cache and not the file? If so how is this done?

I mean in a file. And MFS, seeing "LfnHack.SFN",
just returns success w/o doing anything useful.
But I think my next idea is way better. :)

**Comment by andrewbird** [comment]
I think the next idea is better too, :smile:!

**Comment by andrewbird** [comment]
Just so you know, after the merge of mfs04 I ran the test suite again. The create problem is the most outstanding issue, see
~~~
$ grep ^FAIL: after.tst 
FAIL: Test DR-DOS-3.40 FAT16B image file
FAIL: Test DR-DOS-3.40 FAT16B vfs directory boot.blk
FAIL: Test DR-DOS-3.41 FAT16B image file
FAIL: Test DR-DOS-3.41 FAT16B vfs directory boot.blk
FAIL: Test DR-DOS-6.00-930319 MFS LFN file create
FAIL: Test DR-DOS-7.00 MFS LFN file create
FAIL: Test DR-DOS-7.02-971119 MFS LFN file create
FAIL: Test DR-DOS-7.02-980123 MFS LFN file create
FAIL: Test DR-DOS-7.03 MFS LFN file create
FAIL: Test FR-DOS-1.00 MFS LFN file create
FAIL: Test FR-DOS-1.10 MFS LFN file create
FAIL: Test FR-DOS-1.20 MFS LFN file create
FAIL: Test MS-DOS-3.10 MFS LFN file create
FAIL: Test MS-DOS-3.20 MFS LFN file create
FAIL: Test MS-DOS-3.21 MFS LFN file create
FAIL: Test MS-DOS-3.30-Nec MFS LFN file create
FAIL: Test MS-DOS-3.30 MFS LFN file create
FAIL: Test MS-DOS-3.31 MFS LFN file create
FAIL: Test MS-DOS-4.01 MFS LFN file create
FAIL: Test MS-DOS-5.00 MFS LFN file create
FAIL: Test MS-DOS-6.00 MFS LFN file create
FAIL: Test MS-DOS-6.20 MFS LFN file create
FAIL: Test MS-DOS-6.21 MFS LFN file create
FAIL: Test MS-DOS-6.22 MFS LFN file create
FAIL: Test MS-DOS-7.00 Floppy image file
FAIL: Test MS-DOS-7.00 MFS LFN file create
FAIL: Test MS-DOS-7.10 MFS LFN file create
FAIL: Test PC-DOS-3.00-Compaq MFS LFN file create
FAIL: Test PC-DOS-3.00 MFS LFN file create
FAIL: Test PC-DOS-3.10-850307 MFS LFN file create
FAIL: Test PC-DOS-3.10-850422 MFS LFN file create
FAIL: Test PC-DOS-3.10-Compaq MFS LFN file create
FAIL: Test PC-DOS-3.20-851230 MFS LFN file create
FAIL: Test PC-DOS-3.20-860221 MFS LFN file create
FAIL: Test PC-DOS-3.30 MFS LFN file create
FAIL: Test PC-DOS-3.31-Compaq MFS LFN file create
FAIL: Test PC-DOS-4.00 MFS LFN file create
FAIL: Test PC-DOS-4.01 MFS LFN file create
FAIL: Test PC-DOS-5.00 MFS LFN file create
FAIL: Test PC-DOS-5.02 MFS LFN file create
FAIL: Test PC-DOS-6.10 MFS LFN file create
FAIL: Test PC-DOS-6.30 MFS LFN file create
FAIL: Test PC-DOS-7.00 MFS LFN file create
FAIL: Test PC-DOS-7.10 MFS LFN file create
FAIL: Test PC-DOS-7.2K MFS LFN file create
~~~

And the obligatory trend graph. Don't worry the fails and skips aren't growing, I've been adding more tests and so as a proportion it's coming down.
![test-trend](https://user-images.githubusercontent.com/220835/32352085-9df0b85c-c017-11e7-8131-c126a60614c4.png)

**Comment by stsp** [comment]
While very unlikely, DOS can copy the SFN
and then the check for `LFN_short_name`
will fail. We should better use this:
http://www.ctyme.com/intr/rb-4392.htm
to get the original DS:SI.
It would be even better to find the original
AX and see if it contains the LFN call number,
but this doesn't look possible.

**Comment by stsp** [comment]
There is also an interesting function:
http://www.ctyme.com/intr/rb-4399.htm
which we probably can use to get CDS.

**Comment by andrewbird** [comment]
> http://www.ctyme.com/intr/rb-4399.htm

Needs to use the DOS stack, in mfs_lfn_() is that the current _SS:_SP?

**Comment by stsp** [comment]
> Needs to use the DOS stack, in mfs_lfn_() is that the current _SS:_SP?

In case DOS did the MFS call-out - yes.

**Comment by andrewbird** [comment]
Not quite sure why but when I try to get CDS in truename() using int 2f/17 or 1f I get CF set and no valid data. I wonder why?

**Comment by stsp** [comment]
Maybe because you don't push the
word to stack correctly.

**Comment by andrewbird** [comment]
Im using pushw macro. I'll have another look in a while

**Comment by bartoldeman** [comment]
Actually the test case has a little bug: it specifies O_CREAT in open() but omits the third argument (in DJGPP only S_IRUSR and S_IWUSR are relevant, and of those only S_IWUSR is used).

The file is then by accident created read only in lfn.c and then mfs.c then cannot open it in write mode.

The question is then really: what should happen if you create a read/only file and then write to it (this works in Linux, but I am not sure of DOS semantics). It certainly looks contradictory.

**Comment by andrewbird** [comment]
I'll try to change the test case, it certainly explains why. I do use the same code to test with short file names with success, but I suppose that's because it's a single stage creation via DOS, not the create in unix/open in DOS that the LFN code does.

**Comment by andrewbird** [comment]
I tried altering the test case, and as @bartoldeman said the problem is that if the arg is missing the file is created read only. I tried with mode 0222 write only and the test passes, with 0444 it fails. However bug in test case notwithstanding (eek!) there is still a problem, because according to the Linux manpage on open(), 
~~~
Note that this mode applies only to
              future accesses of the newly created file; the open() call
              that creates a read-only file may well return a read/write
              file descriptor.
~~~
So with the two stage (create in unix, open in DOS) approach, unless unix always creates a wide open permission on the file, DOS would have trouble opening it. It would then have to chmod() to correct perms after open().

**Comment by andrewbird** [comment]
So I corrected the test suite, and added another test for open() create and mode set to readonly
~~~
Test MS-DOS-7.00 MFS LFN file append ... ok
Test MS-DOS-7.00 MFS LFN file create ... ok
Test MS-DOS-7.00 MFS LFN file create readonly ... FAIL
Test MS-DOS-7.00 MFS LFN file find ... ok
Test MS-DOS-7.00 MFS LFN file read ... ok
Test MS-DOS-7.00 MFS LFN file truncate ... ok

Test MS-DOS-7.00 MFS SFN file append ... ok
Test MS-DOS-7.00 MFS SFN file create ... ok
Test MS-DOS-7.00 MFS SFN file create readonly ... ok
Test MS-DOS-7.00 MFS SFN file find ... ok
Test MS-DOS-7.00 MFS SFN file read ... ok
Test MS-DOS-7.00 MFS SFN file truncate ... ok
~~~
As you can see SFN is okay, but LFN is not.

**Comment by andrewbird** [comment]
Not connected to the problem, but we spoke about this function earlier in the thread.

This code works faultlessly against FreeDOS 1.2, but in Win95 the sometimes the carry flag is set, and never does the CDS ptr returned point to a valid CDS, or have the same value as the one we get via SYSVARS

I can only imagine that somehow the stack in Win95 is different. How would one go about obtaining the SS:SP for DOS internal stack as suggested in the RBIL page on int2f/1217?

```
       unsigned int ssp, sp;

        /* ask DOS for the CDS */

        ssp = SEGOFF2LINEAR(_SS, 0);
        sp = _SP;
        pushw(ssp, sp, (uint16_t) result);
        _SP -= 2;

        _AX = 0x1217;   // Get CDS for drive
        do_int_call_back(0x2f);
        _SP += 2;       // reset stack

        Debug0((dbg_fd, "CARRY flag = %d\n", isset_CF()));
        cds = MK_FP32(_DS, _SI);

```

**Comment by stsp** [comment]
> but in Win95 the sometimes the carry flag is set

Maybe you should clear it before the call?
RBIL does not document CF for this functions,
so I may guess that:
1. it may leave it set if it was before
2. you are probably not supposed to check
it (but what to check?)
3. maybe if you set it initially and its not
cleared, then assume this call is unsupported
(I do this for LFN, seems to work fine)

> SS:SP for DOS internal stack as suggested in the RBIL page on int2f/1217?

Most redirector functions are marked in RBIL
as having SS = DOS DS, but not all. Maybe
you are doing this in a function that is not
called on a DOS stack?

**Comment by andrewbird** [comment]
> Maybe you are doing this in a function that is not called on a DOS stack

I'm attempting to use this from lfn.c - specifically truename function int21/71/60. There's no mention of that using DOS stack, so I guess that's the problem.
As a test I moved the same code to int21/11/23 (qualify filename) and it now works on Win95 too.

**Comment by stsp** [comment]
As I already mentioned, these are to
work from the redirector.

**Comment by andrewbird** [comment]
Yes you did, but I didn't get the significance.

Now getting the cds via this int2f/12/17 function is great for killing the manual figuring out of the cds in the redirector, but as we see we can't use it in lfn.c. For SFN int21/60 the truename calls go through to the redirector's int2f/11/23 qualify_filename, but as I've just checked the LFN int21/7160 do not, so I think that's confirmation of what you said yesterday about LFN not being expected to work on network drives.

**Comment by stsp** [comment]
Please see also this func:
http://www.ctyme.com/intr/rb-4391.htm

**Comment by andrewbird** [comment]
That's the function I'm using :)

**Comment by andrewbird** [comment]
Closing now as there's now a more relevant issue that describes current behaviour.
