### ISSUE TITLE
RFC: truename / qualify filename rework

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#523]
I'm thinking that I might be able to remove reliance on CDS in lfn.c by doing:
- Implement QUALIFY_FILENAME int2f/11/23 in mfs.c (can use int2f/12/17 to get CDS here)
- Replace int21/71/60 body with a call to int21/60. According to the int21/60 docs the function is passed a source pathname in DS:SI that doesn't even have to exist and it can return upto 128 char pathname via ES:DI which should be enough for our LFN. The problem see with this is that in the normal call from DOS it would return a mangled pathname, whereas here we want the LFN. Perhaps there are some possibilities here:
  - Indicate somehow in the call that we want LFN - might be difficult as there's no guarantee that anything we pass to int21/60 will make it through to int2f/11/23
  - Indicate via a variable in bios.S what int21/70/60's CL value was and then return SFN/LFN etc, but need to be careful about setting it back to give normal int21/60 behaviour for next call. 
  - Have int2f/11/23 always populate a static buffer in bios.S with LFN result, then the int21/71/60 can pick it up from there.

**Comment by stsp** [comment]
My current understanding is that we
should keep LFN and mfs separated
as much as possible. There are very
few LFN functions that _really_ needs
to be passed to DOS. I guess something
like the following list:
3b, 47, 6c.
Currently 60 doesn't seem to call to DOS,
so your proposal to make it so, looks
counter-productive. Of course I may be
missing something here.

**Comment by andrewbird** [comment]
Well it seems to me that lfn.c is partially acting like a front end redirector (like early Novell), whilst the rest is done in our backend redirector mfs.c. All the stuff in lfn.c with CDS manipulation is in the wrong place IMHO. Of course if we can get CDS in lfn.c properly without needing SYSVARS LOL then this argument goes away, but the redirection facility is still split.

**Comment by stsp** [comment]
It may be a front end to redirector,
but the question is whether we call
redirector redirectly or via DOS. In
the ideal world DOS would handle
71 on its own and do the redirector
call-outs only for remote drives, with
LFNs clearly indicated.
But this is not that way. So we can
just assume lfn is part of the redirector.
Note that now our LFN is in second-revect
hook, which means it will not (really?)
be called for local drives, so DOS still
has the chance of implementing vfat if
it wants to. We don't need to check
cds_flags now, by the mere fact that
we moved to second-revect.

**Comment by stsp** [comment]
I think for those functions that _have_
to be passed to DOS, mfs should check
the bios.S pointer and call info lfn.c
for further processing, rather than trying
to deal with LFNs on its own. By this
we will indicate that this is just an unwanted
round-trip: we will handle everything LFN-specific
in lfn.c.

**Comment by andrewbird** [comment]
So just so I am clear, the mfs_lfn() code is only ever executed if DOS doesn't implement int21/71/xx because it's second_revect?
I do like this idea, but I wonder why I see LFN operations on my A: vfat floppy on win95
~~~
LFN: doing LFN!, AX=71a0 DL=df                                                  
LFN: build_posix_path: a:\                                                      
truename(a:\)                                                                   
INT21 (0) at fc00:01e9: AX=440c, BX=0001, CX=037f, DX=d86d, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=3800, BX=0001, CX=037f, DX=de14, DS=9055, ES=9055    
INT2F at fc00:01e9: AX=b700, BX=0001, CX=037f, DX=de14, DS=9055, ES=9055        
INT21 (0) at fc00:01e9: AX=4000, BX=0001, CX=0002, DX=9232, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=0220, BX=0001, CX=037f, DX=de20, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=1a3f, BX=0001, CX=0000, DX=d299, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=113f, BX=0001, CX=0000, DX=0055, DS=9055, ES=9055    
INT2F at fc00:01e9: AX=1123, BX=090a, CX=0000, DX=0055, DS=00c9, ES=00c9        
MFS: Entering dos_fs_redirect, FN=23                                            
MFS: selecting drive fn=23 sda_cds=0x7f8378c02c3f                               
MFS: FNX=A:????????.???                                                         
MFS: no drive selected fn=23                                                    
INT13: ax=0201 cx=0002 dx=0000                                                  
~~~

The culprit lfn.c function for CDS use is truename(). It's using CDS to find the current directory, root length, joined /subst drives and obviously flags.

**Comment by stsp** [comment]
> So just so I am clear, the mfs_lfn() code is only ever executed
> if DOS doesn't implement int21/71/xx because it's second_revect?

That was the idea.

> I do like this idea, but I wonder why I see LFN operations on my A: vfat floppy on win95

Maybe it doesn't apply lfn to floppy?
Who knows. You can try vfat hdimage.

**Comment by andrewbird** [comment]
Same thing happens with hdimage and vfat.
~~~
LFN: doing LFN!, AX=71a0 DL=df                                                  
LFN: build_posix_path: d:\                                                      
truename(d:\)                                                                   
INT21 (0) at fc00:01e9: AX=440c, BX=0001, CX=037f, DX=d86d, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=3800, BX=0001, CX=037f, DX=de14, DS=9055, ES=9055    
INT2F at fc00:01e9: AX=b700, BX=0001, CX=037f, DX=de14, DS=9055, ES=9055        
INT21 (0) at fc00:01e9: AX=4000, BX=0001, CX=0002, DX=9232, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=0220, BX=0001, CX=037f, DX=de20, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=1a3f, BX=0001, CX=0000, DX=d299, DS=9055, ES=9055    
INT21 (0) at fc00:01e9: AX=113f, BX=0001, CX=0000, DX=0055, DS=9055, ES=9055    
INT2F at fc00:01e9: AX=1123, BX=090a, CX=0000, DX=0055, DS=00c9, ES=00c9        
MFS: Entering dos_fs_redirect, FN=23                                            
MFS: selecting drive fn=23 sda_cds=0x7f4556a24d4f                               
MFS: FNX=D:????????.???                                                         
MFS: no drive selected fn=23                                                    
~~~

**Comment by stsp** [comment]
And then it doesn't work or what?
No LFNs on image?

**Comment by andrewbird** [comment]
Well I copied autoexec.bat to d:verylongfilename.txt and DIR d: shows "verylong.txt". I think it should show "verylo~1.txt" or some such mangling on the left and "verylongfilename.txt" over on the right.

**Comment by stsp** [comment]
You can disable LFN in dosemu config
and then see.

**Comment by bartoldeman** [comment]
LFN's don't work on FAT images, unless you use a TSR such as DOSLFN or LFNDOS.

**Comment by bartoldeman** [comment]
This is because Win9x DOS does not implement LFNs, only the GUI does that. Neither does lfn.c make any attempt into creating the LFN "illegal" directory entries in the FAT directory structures.

**Comment by stsp** [comment]
Even on DOS7+? But why it then
states the lfn support? :(

**Comment by bartoldeman** [comment]
The LFN code needs to figure out the drive letter in the path name, and see it is not a redirected drive, before it decides it will not take any further action.

**Comment by bartoldeman** [comment]
and int21/71/60 cannot be replaced by int21/60. LFN's and SFN's use different rules, even the list of illegal filename characters is different.

**Comment by andrewbird** [comment]
setting `$_lfn_support = (off)` stops the LFN messages in the log

**Comment by stsp** [comment]
> The LFN code needs to figure out the drive letter in the path name,
> and see it is not a redirected drive, before it decides it will not take any further action.

But are you sure DOS7+ does not handle
LFN on its own for non-redirected drives?

> setting $_lfn_support = (off) stops the LFN messages in the log

And nothing changes in a way it doesn't work
on hdimage?

**Comment by andrewbird** [comment]
> And nothing changes in a way it doesn't work on hdimage?

No, I still get really odd file name truncation.

**Comment by stsp** [comment]
> This is because Win9x DOS does not implement LFNs, only the GUI does that.

OK, that explains what happens here.

**Comment by andrewbird** [comment]
> OK, that explains what happens here.

Why is truename() called in LFN and ends up on the redirector to qualify filename when the disk is vfat?

**Comment by stsp** [comment]
> Why is truename() called in LFN

Because DOS does not implement 0x71 API
even for vfat. :(

> and ends up on the redirector to qualify filename when the disk is vfat?

Don't know, likely because of some bug. :)

**Comment by bartoldeman** [comment]
The MFS log entries come from INT21 (0) at fc00:01e9: AX=113f, BX=0001, CX=0000, DX=0055, DS=9055, ES=9055  (Find First using FCB). the DOS prog calls this function if LFNs are not available, so this is just a regular SFN call. ALL filenames passed as SFNs are checked passed via int21/ax=1123 to the redirector (but in this case MFS doesn't do anything with it)

**Comment by andrewbird** [comment]
> Because DOS does not implement 0x71 API even for vfat. :(

Mmm, that would explain it.

> ALL filenames passed as SFNs are checked passed via int21/ax=1123 to the redirector (but in this case MFS doesn't do anything with it)

So that means I'm back where I started, the qualify_filename int2f/11/23 will get called for any drive on the system and not just the ones it owns.

**Comment by stsp** [comment]
So it appears DOS calls redirector even
for local drives?

**Comment by andrewbird** [comment]
Slightly off topic, but in my quest to remove direct cds access from lfn.c I'm looking at 0x7147 get LFN current directory. I want to replace the cds access with a call to int21/47 to get the SFN directory. I tried using a slightly modified call_dos_helper() but I don't seem to be able to get the answer back from the call. Does it run in the same thread, as when I add logging I seem to see things printed out of order? I thought about using call_msdos(), would that be suitable in lfn.c?

**Comment by stsp** [comment]
Try call_msdos(), see if it helps.
I think lfn.c is a quite safe place for
call_msdos(), as, unlike mfs.c, it is
not called from DOS itself but rather
from user code.
Maybe you can also make it conditional
depending on the DOS version, to not
disturb the current code.

**Comment by andrewbird** [comment]
What's the difference, why do we use LWORD(eax) in some places and _AX in others? Lfn.c uses _AX etc, but call_msdos() works with the LWORD(eax) style of register access.

**Comment by stsp** [comment]
Just a historical difference.
Currently we use LWORD() notation
for realmode regs and _lowercase (_ax)
for prot. mode regs. _UPPERCASE (_AX)
is currently avoided to not be confused
with the prot. mode notation.
But its quite possible to review and change
these things if you want. Feel free to invent
your own notation for real and prot mode
regs.

**Comment by andrewbird** [comment]
So in lfn.c are they interchangeable, I mean in the 7147 function the _DS:_SI regs are filled with segment offset of the buffer to fill, do I have to set  SREG(ds)  and LWORD(esi) before calling call_msdos()?

**Comment by stsp** [comment]
> So in lfn.c are they interchangeable

Yes, they refer to the same thing.

**Comment by andrewbird** [comment]
Thanks, I have it working now.
