### ISSUE TITLE
Bug in modemu.c

### ISSUE THREAD

**Issue by newbluemoon** [stsp/dosemu2#527]
Hi,

I think there is a bug in `src/plugin/modemu/modemu.c`:

```
437 #ifdef HAVE_GRANTPT
443 getPtyMaster(char **line_return)
531 #else
538 getPtyMaster(char *tty10, char *tty01)
561 #endif
717     char *ptyslave;
724     tty.rfd = tty.wfd = getPtyMaster(&ptyslave);
```
`HAVE_GRANTPT` is defined in `defs.h`:
```
#if defined(__GLIBC__) || defined(SVR4)
#define HAVE_GRANTPT
#endif
```

If `HAVE_GRANTPT` isn’t defined the second `getPtyMaster` function is used. But regardless of the outcome of the if condition `getPtyMaster` is always called as if `HAVE_GRANTPT` was present.

**Comment by stsp** [comment]
Thanks, should now be fixed.

**Comment by newbluemoon** [comment]
Thank you for the prompt fix. Compilation works now :) but should the prototype in `cmdarg.c`, line 77,  have a return type? It’s defined as 

    537 static int
    538 getPtyMaster(char *tty10, char *tty01)

in `modemu.c`.

Btw.: I stumbled upon this because I’m trying to compile dosemu2 against the musl libc. Musl has `grantpt` though. So in `defs.h` the line `#if defined(__GLIBC__) || defined(SVR4)` is too restrictive in that case. It compiles when I patch `__GLIBC__` to `__linux__` for the build, but I don’t think that’s a good idea in general. Musl suggests to check for a feature itself.

But now the main problem is that musl doesn’t have `execinfo.h`. The easiest way would probably be to disable all debugging code for musl with some `#ifdef`s, but I have no idea where to start (and if it’s even feasible).

**Comment by stsp** [comment]
> but should the prototype in cmdarg.c, line 77,

Strictly speaking, no, because the missing
return type defaults to int. But I've added it now.

> disable all debugging code for musl with some #ifdefs

Done now too.
It seems many people are now concerned about
the portability, so lets move it forward.

**Comment by stsp** [comment]
Note that the main debugging code will
still work: we just run gdb on our crashed
process. And if not, we provide the debugging
code via libbfd. `execinfo.h` was just a last
resort thing.

**Comment by newbluemoon** [comment]
Thanks again! But I’m afraid one problem solved the next one arises. On the plus side: the build runs until the linking stage where there are a couple of undefined references (see below). To get there I had to adjust some headers:

```
--- src/dosext/net/ipx.c.orig	2017-11-08 15:26:02.000000000 +0100
+++ src/dosext/net/ipx.c	2017-11-13 15:03:14.040917938 +0100
@@ -23,9 +23,15 @@
 #include <sys/socket.h>
 #include <sys/time.h>
 #include <sys/types.h>
-#include <netipx/ipx.h>
 #include <netinet/in.h>
 #include <errno.h>
+#ifndef __GLIBC__
+# include <linux/ipx.h>
+# define IPX_TYPE 1
+# define SOL_IPX 256
+#else
+# include <netipx/ipx.h>
+#endif
 
 #include "emu.h"
 #include "timers.h"

```

```
--- src/dosext/net/ipxglt.c.orig	2017-11-08 15:26:02.000000000 +0100
+++ src/dosext/net/ipxglt.c	2017-11-13 15:06:48.056952388 +0100
@@ -22,9 +22,15 @@
 #include <sys/time.h>
 #include <sys/ioctl.h>
 #include <net/route.h>
-#include <netipx/ipx.h>
 #include <netinet/in.h>
 #include <errno.h>
+#ifndef __GLIBC__
+# include <linux/ipx.h>
+# define IPX_TYPE 1
+# define SOL_IPX 256
+#else
+# include <netipx/ipx.h>
+#endif
 
 #include "emu.h"
 #include "utilities.h"

```

The next one is to avoid a redefinition of `ethhdr`.
```
--- src/dosext/net/libpacket.c.orig	2017-11-08 15:26:02.000000000 +0100
+++ src/dosext/net/libpacket.c	2017-11-13 19:44:05.964811045 +0100
@@ -23,10 +23,12 @@
 #include <net/if.h>
 #include <netinet/in.h>
 #include <linux/if_tun.h>
-#include <netinet/if_ether.h>
 #include <netpacket/packet.h>
-#include <net/ethernet.h>
 #include <assert.h>
+#ifdef __GLIBC__
+# include <net/ethernet.h>
+# include <netinet/if_ether.h>
+#endif
 
 #include "emu.h"
 #include "utilities.h"
```

The following two might be good for glibc builds, too?
```
--- src/include/disks.h.orig	2017-03-05 17:02:10.000000000 +0100
+++ src/include/disks.h	2017-11-13 11:57:33.422720904 +0100
@@ -21,6 +21,7 @@
 
 #include <stdint.h>
 #include <sys/types.h>
+#include <fcntl.h>
 
 /* disk file types */
 typedef enum {
```

```
--- src/base/misc/fatfs.c.orig	2017-11-08 15:26:02.000000000 +0100
+++ src/base/misc/fatfs.c	2017-11-13 14:41:33.553704227 +0100
@@ -59,6 +59,7 @@
 #include <sys/stat.h>
 #include <errno.h>
 #include <assert.h>
+#include <limits.h>
 
 #include "disks.h"
 #include "fatfs.h"
```


Linking stops with the following errors:
```
cc -Wl,-warn-common -pthread -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -rdynamic -o ../2.0-pre7/bin/dosemu.bin emu.o \
   -Wl,--whole-archive lib/libbase_video.a lib/libbase_dev_vga.a lib/libbase_async.a lib/libbase_kbd_unicode.a lib/libarch_linux_async.a lib/libarch_linux_mapping.a lib/libarch_linux_mcontext.a lib/libbase_misc.a lib/libbase_misc_libpcl.a lib/libbase_dev_misc.a lib/libemu-i386.a lib/libemu-i386_simx86.a lib/libbase_speaker.a lib/libbase_dev_pic.a lib/libdosext_mfs.a lib/libdosext_misc.a lib/libbase_init.a lib/libbase_serial.a lib/libbase_mouse.a lib/libbase_dev_dma.a lib/libenv_translate.a lib/libenv_builtins.a lib/libtools_debugger.a lib/libdosext_net.a lib/libbase_dev_sb16.a lib/libbase_sound.a lib/libdosext_drivers.a lib/libbase_bios.a lib/libdosext_dpmi.a lib/libdosext_dpmi_msdos.a lib/libplugin_extra_charsets.a lib/libplugin_midimisc.a lib/libplugin_charsets.a lib/libplugin_modemu.a -Wl,--no-whole-archive -lpthread -ldl -lm -lrt 
lib/libarch_linux_async.a(sigsegv.o): In function `dosemu_fault0':
sigsegv.c:(.text+0xc82): undefined reference to `pthread_getname_np'
lib/libarch_linux_async.a(signal.o): In function `sigasync0':
signal.c:(.text+0x68): undefined reference to `pthread_getname_np'
lib/libbase_misc.a(dos2linux.o): In function `find_drive':
dos2linux.c:(.text+0x1514): undefined reference to `canonicalize_file_name'
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_get_context':
pcl_ctx.c:(.text+0xe8): undefined reference to `getcontext'
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_create_context':
pcl_ctx.c:(.text+0x122): undefined reference to `getcontext'
pcl_ctx.c:(.text+0x168): undefined reference to `makecontext'
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_swap_context':
pcl_ctx.c:(.text+0xc4): undefined reference to `swapcontext'
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_set_context':
pcl_ctx.c:(.text+0xd4): undefined reference to `setcontext'
lib/libemu-i386.a(do_vm86.o): In function `_do_vm86':
do_vm86.c:(.text+0x1de): undefined reference to `feenableexcept'
lib/libemu-i386_simx86.a(cpu-emu.o): In function `Cpu2Scp':
cpu-emu.c:(.text+0x236): undefined reference to `feenableexcept'
collect2: error: ld returned 1 exit status
```

`getcontext`, `makecontext`, and `swapcontext` are only dummy functions. I found [this commentary](http://openwall.com/lists/musl/2016/02/04/5) by the musl developer regarding those functions.

`pthread_getname_np` and `feenableexcept` don’t exist. Regarding the latter I found [this comment](http://www.openwall.com/lists/musl/2012/12/14/18).

I guess fixing this would require a check for those functions and then again some `#ifdef`s (if possible). But I don’t have any idea how much trouble this would be.

And lastly, in `src/base/misc/utilities.c`, line 275, `__va_copy` is used. Is this for compatibility reasons? Because it doesn’t exist, too, but `va_copy` does. I guess this would also require a check. A definition as in stdarg.h works, too: `#define __va_copy(d,s)  __builtin_va_copy(d,s)`.

**Comment by stsp** [comment]
> I found this commentary by the musl developer regarding those functions.

They all refer here for rationale:
http://pubs.opengroup.org/onlinepubs/009695399/functions/makecontext.html
And of course we see that it is a nonsense:
```
There are very few applications today that use the *context() routines.
Those that do use them are almost always using them to implement co-routines.
...
Threads can be used to implement the functionality provided by makecontext(), getcontext(), and
swapcontext() but they are more complex to use. It was felt inventing new ISO C standard-compatible
interfaces that describe what can be done with the XSH, Issue 5 functions and then converting
applications to use them would cause more difficulty than just converting applications that use them
to use threads instead.
```

So they mention that threads are more
complex to use for this, and yet suggest
to use them? This is not to mention that
using threads for user-space coroutines
will be horribly slow, as they will stop being
user-space, to start with.
Crap aside, I already have added the asm
replacement. We do no longer depend on
the libc implementation. So if, as you say,
musl provides the dummy functions, that
should still work. So where are they?

> pthread_getname_np and feenableexcept don’t exist.

pthread_getname_np() can be conditionalized -
its for error logging only. feenableexcept() lose
is a bit upsetting as it helped to catch divizions
by zero, but it can be conditionalized too.

> And lastly, in src/base/misc/utilities.c, line 275, __va_copy is used. Is this for compatibility reasons?

5808b09
Looks like the compatibility with gcc-2.95, which
we are not interested in today.

Would you mind providing the pull requests
for the things you fix, and different bug-reports
for the things you don't fix?
It all can't live well in a single closed ticket.

**Comment by stsp** [comment]
> `+#ifdef __GLIBC__`

`#ifdef __MUSL__` please.
The net header problems look definitely like
a musl bugs, so they should be under
musl-specific ifdefs.
