### ISSUE TITLE
ucontext issue when using musl libc

### ISSUE THREAD

**Issue by newbluemoon** [stsp/dosemu2#531]
Error message:

```
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_get_context':
pcl_ctx.c:(.text+0xe8): undefined reference to `getcontext'
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_create_context':
pcl_ctx.c:(.text+0x122): undefined reference to `getcontext'
pcl_ctx.c:(.text+0x168): undefined reference to `makecontext'
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_swap_context':
pcl_ctx.c:(.text+0xc4): undefined reference to `swapcontext'
lib/libbase_misc_libpcl.a(pcl_ctx.o): In function `ctx_set_context':
pcl_ctx.c:(.text+0xd4): undefined reference to `setcontext'
```

`ucontext.h` exists in musl, but it’s just a stub (mistook this earlier as if dummy functions were defined, sorry). It just contains:

```
#ifndef _UCONTEXT_H
#define _UCONTEXT_H
#ifdef __cplusplus
extern "C" {
#endif

#include <features.h>

#include <signal.h>

#if defined(_GNU_SOURCE) || defined(_BSD_SOURCE)
#define NGREG (sizeof(gregset_t)/sizeof(greg_t))
#endif

struct __ucontext;

int  getcontext(struct __ucontext *);
void makecontext(struct __ucontext *, void (*)(void), int, ...);
int  setcontext(const struct __ucontext *);
int  swapcontext(struct __ucontext *, const struct __ucontext *);

#ifdef __cplusplus
}
#endif
#endif

```

The Musl-Wiki says (https://wiki.musl-libc.org/open-issues.html):

> **ucontext.h**
> Legacy functions operating on ucontext_t (getcontext, setcontext, makecontext,
> swapcontext) are not implemented. They are no longer part of POSIX, but
> cooperative multi-tasking applications use them. ucontext_t also appears as an
> argument to sigaction handlers which cannot be used portably.

You mentioned in #527:
> I already have added the asm
> replacement. We do no longer depend on
> the libc implementation.

So this might be an easy fix?

**Comment by stsp** [comment]
> So this might be an easy fix?

Except for the fact that musl provides the
header and prototypes! This is lame because
the simple autoconf check will detect them.
Why could they add prototypes for something
they don't provide, if not to trick configure?
So we'll have to resort to more complex checks
that try to link an example code... :(

**Comment by newbluemoon** [comment]
Would a check to see if linking worked be enough?

**Comment by stsp** [comment]
I think so - only you can tell for sure after testing. :)

**Comment by stsp** [comment]
> So this might be an easy fix?

Indeed. By just disabling it.
I am not sure why I was thinking about
a complicated checks if the replacement
is used by default for long now.
