### ISSUE TITLE
__va_copy doesn’t exist in musl

### ISSUE THREAD

**Issue by newbluemoon** [stsp/dosemu2#533]
Error message:

```
lib/libbase_misc.a(utilities.o): In function `verror':
utilities.c:(.text+0x48f): undefined reference to `__va_copy'
```

The man page for va_copy says
> Some systems that do not supply va_copy() have __va_copy instead, since that was the name used in the draft proposal.

So I see two possibilities:
a) change `__va_copy` to `va_copy` and drop support for gcc 2.95 or
b) make it conditional

**Comment by stsp** [comment]
Please create the PR to just rename it.

**Comment by newbluemoon** [comment]
Done :)
