### ISSUE TITLE
LFN: Creating a file with LFN from djgpp app gives mangled name file on linux

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#535]
As per the note in PR #525 there is an issue when creating a file with an app that uses djgpp's LFN open command that results in the on disk filename being the mangled representation of the LFN, rather than the true LFN. [lfn_create_read_only.zip](https://github.com/stsp/dosemu2/files/1479320/lfn_create_read_only.zip) .

Notes:
- The test here is run against Freedos 1.2 but the problem occurs with all variants of DOS I have.
- Make sure you delete the file from Linux before starting dosemu and running the test program.
- The problem occurs with both LFN R/W and R/O opens.
- The requested LFN `verylongname.txt` actually ends up being called `veryl~d#.txt` but has the correct content.

**Comment by stsp** [comment]
Just to make sure, the LFN is also not
seen under DOS, right? Because not seeing
it only under linux does not qualify as a bug.

**Comment by stsp** [comment]
I am asking because you said "on disk filename being the mangled",
which means linux-only to me.

**Comment by andrewbird** [comment]
It's both, here's a screenshot. In any case not seeing the LFN on linux would be a change in behaviour to that which existed before the recent readonly open fix.
![mfslfn01](https://user-images.githubusercontent.com/220835/32903690-96ccffbe-caed-11e7-8607-3aa03dfbf3bd.png)

**Comment by stsp** [comment]
Yep, the patch was hardly tested.
I applied what looks to be a simple fix.

**Comment by andrewbird** [comment]
Yes, that works better for DOS with real LFN functions. It looks like I have a little work to track down why the failback LFN functions for DOS < 4.0 aren't working for create.
Thanks.

**Comment by stsp** [comment]
> Yes, that works better for DOS with real LFN functions.

???
I think we agreed there are none.

**Comment by andrewbird** [comment]
Mmm, getting terminology confused, I meant 'works better for DOS that has real int21/6c Extended open'

I have a fix now for the earlier MS/PC-DOS, but just trying to track down why DR-DOS >7.00 is not working.
