### ISSUE TITLE
MFS FCB rename returning success in DR-DOS and FreeDOS when source file nonexistant

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#538]
With some DOS versions the [int21/17](http://www.ctyme.com/intr/rb-2582.htm) rename function returns success for a simple rename even when the source file does not exist. Other DOS versions seem to work correctly
~~~
Test DR-DOS-6.00-930319 MFS FCB file rename source missing ... FAIL
Test DR-DOS-7.00 MFS FCB file rename source missing ... FAIL
Test DR-DOS-7.02-971119 MFS FCB file rename source missing ... FAIL
Test DR-DOS-7.02-980123 MFS FCB file rename source missing ... FAIL
Test DR-DOS-7.03 MFS FCB file rename source missing ... FAIL
Test FR-DOS-1.00 MFS FCB file rename source missing ... FAIL
Test FR-DOS-1.10 MFS FCB file rename source missing ... FAIL
Test FR-DOS-1.20 MFS FCB file rename source missing ... FAIL
~~~

test files attached including log of run against FreeDOS 1.2 
[fcb_rename1.zip](https://github.com/stsp/dosemu2/files/1488268/fcb_rename1.zip)

**Comment by stsp** [comment]
I think I didn't return error code properly.
Could you please check now?

**Comment by andrewbird** [comment]
No, that didn't fix it, but I'm not actually sure the problem is connected to your recent wildcard work. The test has only just been added to the suite and is only handling the simple case rename file.a file.b, no wildcards. From what I see in the log the it seems that int2f/findfirst returns some error (as it should since the source file is missing), DOS knows something is wrong as it doesn't continue to the the int2f rename, but still flags success to the caller. I wonder if the error code is wrong.

**Comment by andrewbird** [comment]
Comparing logs from MS-DOS 6.22 and FR-DOS 1.20, we can see that each DOS translates the int21/17 into the following int2f calls

MS-DOS
- Qualify source filename
- Qualify target filename
- Rename

FR-DOS
- Qualify source filename
- Findfirst source file

It's my suspicion that Findfirst isn't returning error in AL, but does set the CARRY flag.

**Comment by stsp** [comment]
> FR-DOS

DR-DOS I guess.

**Comment by andrewbird** [comment]
> DR-DOS I guess. 

No, problem occurs with both FreeDOS and DR-DOS, whereas MS-DOS and PC-DOS are okay.

**Comment by andrewbird** [comment]
I can't see any problem either with what our int2f/rename returns in the case that the source file does not exist or also by reading the freedos int21/1700 rename source code from fdkernel git I can't see that there's any problem there. I'm a little mystified as to why I don't see an error return in the test case, so I'm not sure how to proceed.

**Comment by andrewbird** [comment]
I think it's a bug in freeDOS. I copied the test program and FreeDOS 1.20 to an hdimage and booted it under qemu. I get the same success result when actually it should fail as the source file is missing. This was unexpected as I see it with some versions of DR-DOS too. What a waste of time!!

**Comment by andrewbird** [comment]
Close now, as it's almost certainly to be a bug in each DOS that shows the issue.

**Comment by stsp** [comment]
Have you looked it up in a freedos sources?

**Comment by andrewbird** [comment]
I looked, but I'm unfamiliar with the code there, so it wasn't obvious to me where the problem was. I raised and issue there but have no freedos developer reply yet.

**Comment by stsp** [comment]
And likely will not.
Eventually we may need to fork freedos.
I am currently working on a fork locally,
but I may as well run out of time and drop
it. Its quite too difficult to get it to something
what could be called "freedos2". :)
But that explains why I wasn't contributing
to dosemu2 for a week now. Not sure how
long will I last with that idea, but not giving
up yet.
