### ISSUE TITLE
Question: What does LFN function in21/71a0 return on Win95 with FAT?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#539]
I want to know what get_volume_info function [int21/71a0](http://www.ctyme.com/intr/rb-3210.htm) should return on a real Windows 95 system for a plain FAT, not VFAT drive. Does anyone have either a Win95 qemu image (I understand that's a tricky installation) or some other instance of Win95 that you could run a test program for me on?

Here's what we currently get on Dosemu on an MFS drive
~~~
C:\>lfnvinfo c:\
FSTYPE(MFS), FILELEN(255), PATHLEN(260), BITS(0x4002)
~~~

Here's the test program (and source) 
[lfnvinfo.zip](https://github.com/stsp/dosemu2/files/1515180/lfnvinfo.zip)

**Comment by stsp** [comment]
What in particular do you want to know?
Wouldn't it return the same except for "MFS"?

**Comment by andrewbird** [comment]
Filelen, pathlen, and bits (though I presume that'll be 0 for plain FAT.
I'm thinking it could be
- 11 or maybe 12 for filelen and 67 for pathlen
- 0 filelen, 0 pathlen
- or maybe just an error

**Comment by stsp** [comment]
Am I right that dos-7+ does nothing here?
But what's the idea, why do you want to
know that values from win95? Maybe you
can try XP instead?

**Comment by andrewbird** [comment]
Isn't win95 msdos7?  I don't believe that the lfn functions are available except whilst the GUI is running. I guess win98 or winME would be ok, but I don't know enough about XP to say. That said, I don't have any of those myself anyway. I want to know because currently dosemus lfn code returns error Sector not found when running this code on FAT drive. That seems odd, don't you think?

**Comment by stsp** [comment]
I think your best bet would be to get
the fat16+lfn tools (there are many)
and test with then on hdimage.

Could you please clarify what exactly
returns sector not found rather than
the volume parameters you outlined
above?

**Comment by andrewbird** [comment]
The djgpp docs show that if _get_volume_info() returns 0 then errno should be used to determine if that's an error. In our FAT case that value is 27, which I think in DOS terms is SECTOR_NOT_FOUND. I think it's because the current lfn int21/71a0 code uses build_posix_path() to get the drive number and in the case that it's not MFS (drives[x].root == NULL) it returns some odd value for drive. I have patch here to remove the use of build_posix_path() for this, after all it's just validating the drive letter in the path supplied, but I'm looking for the correct values to use.

**Comment by stsp** [comment]
Try doslfn.

**Comment by stuaxo** [comment]
If you want to enable long filenames in Dos 7 (the Dos with Windows 95) you can load IFSHLP.SYS in CONFIG.SYS or using a utility that does the same.

**Comment by andrewbird** [comment]
@stuaxo that sounds promising!  With the Dosemu LFN code being done through second_revector I should be able to use IFSHLP.SYS in preference to it. I'll have a crack at it later and let you know how it goes. :smile:

**Comment by stuaxo** [comment]
I'm think IFSHLP.SYS bypasses a bunch of DOS, but from a user POV it certainly still feels like your in DOS, I haven't really tried it much apart from running COMMAND, EDIT and poking around a bit.

**Comment by stsp** [comment]
I wouldn't bet too much on ifshlp.
doslfn will work for sure though.

**Comment by andrewbird** [comment]
I tried
- IFSHLP.SYS in dosemu but dosemu's LFN was still used, seemingly IFSHLP.SYS wasn't installed in memory successfully
- IFSHLP.SYS in win98 (TrueDOS mode), but couldn't use my test program as it required DPMI
- Installing a full copy of Win98 in kvm, but never managed to get to a usable system
- DOSLFN in dosemu does show me 'FAT, 255, 260, 0x4006' even on plain FAT (not VFAT) floppy, and I can see by reading the source those values are hardcoded.

So no further on I'm afraid.

**Comment by stsp** [comment]
> IFSHLP.SYS in win98 (TrueDOS mode), but couldn't use my test program as it required DPMI

cwsdpmi?

**Comment by jschwartzenberg** [comment]
I have a Windows 98 system here. (I hope to connect it soon again, I just moved into a new place.)

Also all versions of Windows 9x should install fine inside QEMU as long as KVM is disabled.

**Comment by andrewbird** [comment]
@jschwartzenberg Thanks for the hint about using qemu without kvm, I now got win98 started and was able to run the test program in dos window. The results are the same as doslfn
~~~
FAT, 255, 260, 0x4006
~~~
I think Win98 presumes that since the disk is FAT, it can convert to VFAT and have LFN support if it wishes. I tried setting the floppy to read-only but get the same result. So in the case of our fatfs based drives I wonder what lfn volume information we should return?

**Comment by stsp** [comment]
Why have you thought it should return
an error? I am not surprised it matches
doslfn, as obviously doslfn authors checked
win9x first of all.

> drives I wonder what lfn volume information we should return?

Should we? We don't implement LFN support
on fat, so all we need is to return ax=0x7100
and leave CF untouched, no?

**Comment by stsp** [comment]
Or, how about returning 0 in BX?
In particular, bit 14 seems to do what
you want.

**Comment by andrewbird** [comment]
No I don't think it should return an error(but we currently do). The value are per volume, rbil mentions that the first call per volume will interrogate the disk, I think it should return
~~~
FAT, 11, 67, 0x0000
~~~

I think the Ax=7100 indicates no lfn support globally, not just for the volume being queried?

**Comment by stsp** [comment]
> I think the Ax=7100 indicates no lfn support globally, not just for the volume being queried?

The more interesting question is what
will you return on hdimage drives - they
can support lfns via doslfn. That's why I
thought returning 7100 may make sense
so that doslfn can make sure no one else
provides the support. But yes, I don't
think 7100 is the best choice unless there
are no redirected drives at all, in which
case we can well use it.

**Comment by andrewbird** [comment]
I had considered that we could probe the hdimage etc, but it's more difficult than just that because an image may be partitioned into several distinct DOS disks so we'd need to figure out the partitioning and not all DOSs support all types. Mmm a can of worms!

**Comment by stsp** [comment]
Probe for what?

**Comment by andrewbird** [comment]
See if the disk is FAT or VFAT.

**Comment by stsp** [comment]
But we don't support LFNs for either,
so what's the difference?

**Comment by andrewbird** [comment]
Yes you are quite correct. In that case I think we can just return
~~~
FAT, 11, 67, 0x0000
~~~
For all non MFS drives.

I also notice that freedos  has an issue open to add native LFN support. I suppose that will mess up our second revect LFN support for MFS?

**Comment by stsp** [comment]
> Yes you are quite correct. In that case I think we can just return

Not sure. I think it would be better to
return an error instead, actually.
Saying that the volume doesn't support
LFNs for the volume that _does_ support
it and only needs doslfn to be loaded,
sounds wrong. If we don't support LFNs
for some volume, then we can't support
also 71a0 for it. If 7100 is the wrong return
on your opinion, then some error code.
But it is already there, so why to bother?

> I suppose that will mess up our second revect LFN support for MFS?

It should return error or 7100.
If it chooses to return an error, that error
should very clearly indicate "not supported",
like code
`59h (89)  (DOS 4.0+) function not supported on network`
For that code we can run our second_revect
stuff.

**Comment by andrewbird** [comment]
But if you load doslfn to support vfat hdimage, won't you lose lfn support for MFS drives?

**Comment by andrewbird** [comment]
And if that's okay, then you could disable lfn support in dosemu.conf to the same effect.

**Comment by stsp** [comment]
> But if you load doslfn to support vfat hdimage, won't you lose lfn support for MFS drives?

That depends on what it returns.
If it returns 7100, we can work.
If it returns success - we can't.
If it returns error - that becomes
tricky because it could as well
change the initial registers, so
currently in this case second_revect
is not run. But we can save registers
and allow second_revect to run
if doslfn returns an error that clearly
indicates it doesn't support this volume.
That's why I think we have to be
very careful, i.e. returning something
meaningful from 71a0 for the volumes
we don't support, is almost certainly
undesirable.

**Comment by andrewbird** [comment]
Well I think doslfn doesn't play fair. If I load it, then when I run lfnvinfo on the MFS drive then I get the hardcoded values. I wonder what happens if I try to open a file by LFN on the MFS drive with doslfn loaded. Unless both dosemu and doslfn cooperate, I don't think using the two together will work.

~~~ 
C:\>lfnvinfo c:\
FSTYPE(MFS), FILELEN(255), PATHLEN(260), BITS(0x4002)
 
C:\>cd doslfn
 
C:\doslfn>doslfn
DOSLFN 0.40e (haftmann#software & jmh 10/06): loaded consuming 12896 bytes.

C:\DOSLFN>c:\lfnvinfo c:\
FSTYPE(?), FILELEN(255), PATHLEN(260), BITS(0x4006)
~~~

**Comment by stsp** [comment]
Well, I guess its all open source. :)

**Comment by andrewbird** [comment]
I'll close this as I got the answer. Thanks all.

**Comment by andrewbird** [comment]
Just a little follow up learnt after reading the djgpp library source:
- the error set by the _get_volume_info() is an errno translated from the doserror we return, so in the non MFS case, the error is ENOSYS, not SECTOR_NOT_FOUND.
- in the case that the call fails due to disk not in drive etc, it has some unexpected defaults
   (), 13, 80, 0x80000000U # that last value means _FILESYS_UNKNOWN
- In the case that we don't have valid parameters for the filesystem e.g. FAT we need to set the CARRY flag, and return error to trigger the djgpp non-fatal lfn code above.

And finally I agree that it's right to not set any values for FAT (whether fatfs or native), but we do need to set CARRY and return a suitable error.

**Comment by stsp** [comment]
AX = 59h (89) (DOS 4.0+) function not supported on network

**Comment by andrewbird** [comment]
Yes it might as well be, djgpp doesn't care especially as long as CARRY is set. It seem we don't have that value defined in mfs.h, but I could add it.

http://www.delorie.com/djgpp/doc/rbinter/it/80/16.html

**Comment by stsp** [comment]
Good, or find any other error that
you think suits, preferably with
"unsupported" in its name.
In fact we can simply bypass the calls
we do not support, in which case it
will end up in 7100 w/o carry, but I'll
leave that to implementer to decide,
especially as second_revect makes
much fewer sense in 7100 than it
could have been in a normal case.

**Comment by andrewbird** [comment]
I'm pretty sure that 7100 means "no LFN functions supported by DOS", not "LFN not supported on this drive", certainly djgpp has that distinction.
```C
  r.x.flags = 1;        /* Always set CF before calling a 0x71NN function. */   
  r.x.ax = 0x71a0;      /* Get Volume Information function */                   
  r.x.ds = tbuf_seg;    /* DS:DX points to root directory name */               
  r.x.dx = 0;                                                                   
  r.x.es = tbuf_seg;    /* ES:DI points to a buffer for filesys name */         
  r.x.di = (tbuf_la - __tb) & 0xffff;                                           
  r.x.cx = 32;          /* max size of filesystem name (Interrupt List) */      
  __dpmi_int(0x21, &r);                                                         
                                                                                
  if (!(r.x.flags & 1) && (r.x.ax != 0x7100))                                   
  {                                                                             
    char *p = fsystype, c;                                                      
                                                                                
    retval   = r.x.bx;                                                          
    if (maxfile)                                                                
      *maxfile = r.x.cx;                                                        
    if (maxpath)                                                                
      *maxpath = r.x.dx;                                                        
                                                                                
    if (fsystype)                                                               
    {                                                                           
      /* Only copy as much as required, in case the                             
         buffer isn't large enough for 32 bytes.  */                            
      _farsetsel (_dos_ds);                                                     
      while ((c = _farnspeekb (tbuf_la++)))                                     
        *p++ = c;                                                               
      *p = '\0';                                                                
    }                                                                           
  }                                                                             
  else                                                                          
  {                                                                             
    if (r.h.ah == 0x71)                                                         
    {                                                                           
      errno = ENOSYS;                                                           
      retval = 0;       /* meaning none of the features supported */            
    }                                                                           
    else                                                                        
    {                                                                           
      /* If the call failed, but not because the OS doesn't support             
         the function (e.g., invalid drive), don't disable LFN.  */             
      errno = __doserr_to_errno(r.x.ax);                                        
      retval = _FILESYS_UNKNOWN;                                                
    }                                                                           
    if (maxfile)                                                                
      *maxfile = 13;                                                            
    if (maxpath)                                                                
      *maxpath = 80;                                                            
    if (fsystype)                                                               
      *fsystype = '\0';                                                         
  }                                                                             
                                                                                
  return retval;                                                                
}                                                                               
```

**Comment by stsp** [comment]
The problem is that there is no
"LFN not supported on this drive",
so all we can do is to use approximation.
Plus 7100 is not what you put in
ax yourself - this just happens if
you pass the call to the next caller
w/o handling it. And passing the
call down the chain for any unsupported
function - is reasonable thing to do.
But not as much with a second_revect,
so fine with other solutions.

**Comment by andrewbird** [comment]
> The problem is that there is no
"LFN not supported on this drive",
so all we can do is to use approximation.

Agreed

> Plus 7100 is not what you put in
ax yourself - this just happens if
you pass the call to the next handler
w/o handling it.

This I don't quite understand. On interrupt entry AX=0x71a0, but if there's no handler, what changes it to AX=0x7100?

> And passing the
call down the chain for any unsupported
function - is a reasonable thing to do.

Agreed

> But not as much with a second_revect,
so fine with other solutions.

Is that because we are last in the chain? Is it even possible that some DOS interrupt handler could be installed after us?

**Comment by stsp** [comment]
> what changes it to AX=0x7100?

Default DOS handler.
How would you suppose otherwise?
If you don't support some call, you
sure as hell is not supposed to even
hook it, not to mention changing its
registers to say "I don't support it".
Not supported means no handler,
so in that case DOS have to set the
needed value. That's why second_revect
have to restore the original value to
see what it was.

> Is that because we are last in the chain? Is it even possible that
> some DOS interrupt handler could be installed after us?

If only very intentionally, with tricks. Normally not.
