### ISSUE TITLE
Question: Is it possible to read fatfs serial number by starting with a valid DPB

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#540]
So I'm thinking about how the hard drives are enumerated in order to determine which to promote to MFS. Currently if an hdimage that has more than one partition appears to DOS before a fatfs drive, the mapping of that fatfs drive will be wrong. So I'm thinking about scanning through all the drives that DOS knows about and would like to redirect with MFS just the fatfs ones. I suspect this could also be used to solve the #539 problem with LFN get volume info.
Example:
- user has hd disks defined as follows:
  hd0 fatfs
  hd1 hdimage (two partitions)
  hd2 fatfs
- DOS sees the following drive assignments C:, D:, E:, F:
- Mfs automatic redirection of fatfs promotes C: and E: because it assumes drive letter == 'C' + phys drive

I can iterate through the drive letters known to DOS using int2f/1217 to grab each CDS, but I need to be able to determine if the drive referenced by CDS is fatfs. I figured I could identify it as fatfs if the serial number had the correct prefix we assign to fatfs. Within each CDS I can find pointer to DPB, but I'm not sure if it's possible to use that somehow that to find the serial number. I'd like to avoid using int21/6900 as I'm running this from the redirector and so is already inside DOS, also that function isn't supported until DOS v4.0. So is there a way to get the serial number, or perhaps there's a better way to identify the fatfs drive?

**Comment by stsp** [comment]
I think things should be as simple as
it was before, if possible.
So IIRC mkfatimage16 was only producing
an images with just 1 partition.
Did this change?

**Comment by andrewbird** [comment]
No nothing changed, but of course we support hdimages made by the OS and other fdisk programs.

If we can accept that then, we can assume harddisk num + 'C' == drive letter. Then I think I can  get serial number by reading vbr with int13.

**Comment by stsp** [comment]
Have this happened since I allowed
the header-less images? Quite an unexpected
consequence. :(
How about stopping the automatic redirection
as soon as the first non-redirectable drive is met?

**Comment by andrewbird** [comment]
Yes, that seems reasonable.

**Comment by andrewbird** [comment]
Oh and yes headerless images made it easier, but I guess if one was really keen it would have been possible anyway.

**Comment by stsp** [comment]
Just make sure to write some error
perhaps. This is not worth more efforts
than this, as no one really uses hdimages.

**Comment by andrewbird** [comment]
So I just checked again the ordering with mixed fatfs / hd images after reading [wikipedia]( https://en.wikipedia.org/wiki/Drive_letter_assignment). At least on MS-DOS 6.22 it's not necessarily wrong as I had thought. It seems that the first partition on each physical disk is assigned a drive letter in sequence, then the rest of the partitions follow after all the firsts have been done. Here's an example taken from my test system with `$_hdimage = "drives/c hd.img drives/d"`

Letter | PhysDisk | Partition | DPB drive number | DPB reserved sectors
----- | ----- | ---- | ---- | ----
C: | 0 | 1 | 2 | 1
D: | 1 | 1 | 3 | 1
E: | 2 | 1 | 4 | 1
F: | 1 | 2 | 5 | 4

For identifying the fatfs using DPB I think I can read one sector at offset reserved sector and that should be the VBR for the filesystem, and so see the serial number. The problem I have is that I don't see how to programmatically establish which physical disk the partition to be examined is on as I can't use DOS to read the sector so I need to use int13.

**Comment by stsp** [comment]
Then we need to start moving this logic
to emufs.sys. I think you've found the
compelling case for start doing so.
So my suggestion is:
- fix this for emufs.sys
- for non-emufs.sys case just redirect
the amount of drives that were listed
before the first hdimage, printing an
error if there are more.

**Comment by andrewbird** [comment]
Actually the PR I'm working on removes the redirector version detection logic from emufs.sys and leaves it with just the revectoring you added. Two places for redirector initialisation never seemed right. I think doing the redirection stuff inside emufs.sys is the wrong thing as the CDS position and size isn't stable due to lastdrive not being finalised and potentially installable disk drivers in config.sys etc. I can now see a way to have the initialisation to be started within the 32 bit code, call into redirector using int21/5f01 SetRedirectionMode, and initialise redirector / setup fatfs drives there all without needing CDS from LOL.
I think for now I'll do the automatic mapping of fatfs drives, in similar fashion to how it's done now, then let you review the patch series.

**Comment by stsp** [comment]
> Actually the PR I'm working on removes the redirector version
> detection logic from emufs.sys and leaves it with just the revectoring you added.

But that's the same thing, or do you
mean second_revect, or what?

**Comment by andrewbird** [comment]
It's easier to show you the code #541

**Comment by PerditionC** [comment]
As far as dos drive letter to disk, keep in mind msdos has a fixed order but FreeDOS kernel it's user selectable if it follows msdos ordering or all from same disk first then next disk.  Also it's possible for external tools to change drive mapping and a future fd kernel (with gpt support) may allow arbitrary order.

**Comment by andrewbird** [comment]
@PerditionC do you know of a way using DOS structures (or DOS function that's reentrant) to find any of?
- VBR from a drive's DPB
- VBR from a drive's CDS entry
- Physical Disk that the drive resides on 

Yes relying on disk enumeration ordering seems wrong. I didn't know about FreeDOS being able to change it, though I had seen that DR-DOS could do it. Alas at the moment I don't see an alternative.
