### ISSUE TITLE
Compilation error with musl libc

### ISSUE THREAD

**Issue by newbluemoon** [stsp/dosemu2#546]
When trying to build the latest git version on musl (I used commit 5e9bf39518c3ff13eb7f7ad363fcfff1fe84c1b8) compilation fails with

```
In file included from ../../../src/include/dpmi.h:6:0,
                 from instremu.c:51:
../../../src/include/../dosext/dpmi/dpmi.h:104:24: error: field 'fpu_state' has incomplete type
   struct _libc_fpstate fpu_state __attribute__ ((aligned(16)));
                        ^~~~~~~~~
```

Edit: the line that worked was

    struct _fpstate fpu_state __attribute__ ((aligned(16)));

Has been changed in 4581e6bc5a531312888e4ef9f30aea53985f7016.

**Comment by newbluemoon** [comment]
Just tested, everything is fine again. Thank you! :)

**Comment by stsp** [comment]
So I am going to try some work-around for
a stack-protector problem. You can open a
ticket for it.
