### ISSUE TITLE
stack-protector issue with musl libc

### ISSUE THREAD

**Issue by newbluemoon** [stsp/dosemu2#548]
Protected mode programs only run when musl’s syscall function is attributed with no-stack-protector.

**Comment by stsp** [comment]
Could you please try this patch?

**Comment by newbluemoon** [comment]
It works! Downgraded to the unpatched musl and build dosemu2 with that patch.

**Comment by stsp** [comment]
Thanks.
So it seems we'll be able to get
something barely functional once
musl applies 2 trivial patches.

**Comment by stsp** [comment]
In fact, lets apply the work-around for
sigaltstack too... Please open a ticket. :)

**Comment by newbluemoon** [comment]
Will do, but then I need some sleep ;)
