### ISSUE TITLE
sigaltstack work-around for musl libc

### ISSUE THREAD

**Issue by newbluemoon** [stsp/dosemu2#549]
To run protected mode programs a work around for a bug in musl’s sigaltstack is needed.

**Comment by stsp** [comment]
Please try this fix.

**Comment by newbluemoon** [comment]
Did not apply <i>any</i> patch to dosemu2 and musl, just built the latest devel branch and, yes, it works! Didn’t expect any less ;)

So to summarize: now dosemu2 can run protected mode programs on a musl system without <i>any </i> additional patch. But I will try to address the musl `SS_AUTODISARM` issue on their mailing list anyway.

**Comment by stsp** [comment]
Thanks!
