### ISSUE TITLE
slow startup

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#550]
dosemu2 is quite slow at start-up.
Takes over 1sec before it starts booting DOS.
It would be nice to have an instant startup.
Someone have to profile the code.

**Comment by stsp** [comment]
`time dosemu -td` with `exitemu` in autoexec.bat shows:
```
real	0m1,364s
user	0m0,257s
sys	0m0,094s
```

**Comment by stsp** [comment]
Hm, at home pc the time is only 0.7
seconds - twice faster. Interesting why
at work I have it so slow...
Andrew, what time does it show for you?

**Comment by andrewbird** [comment]
ms-dos 6.22
~~~
real	0m2.717s
user	0m0.335s
sys	0m0.057s
~~~

pc-dos 3.00
~~~
real	0m0.630s
user	0m0.249s
sys	0m0.054s
~~~

**Comment by stsp** [comment]
Is this consistent?
I guess you measured a cold start
in the first  case.

**Comment by andrewbird** [comment]
Seems to be. In both cases the boot directory was new, and only accessed by me beforehand to add the `exitemu`

I repeated the PC-DOS test 10 times in the same boot directory and it didn't seem to vary that much
~~~
$ for i in `seq 10` ; do time bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir -o test.log ; done 2>&1 | grep real
real	0m0.700s
real	0m0.618s
real	0m0.634s
real	0m0.678s
real	0m0.633s
real	0m0.670s
real	0m0.692s
real	0m0.698s
real	0m0.673s
real	0m0.690s
~~~

**Comment by stsp** [comment]
Half a second seems adequate.

The profiler shows that `unicode_to_charset_primitive()`
function is being called a million times during
start-up, I wonder if that is intentional...

**Comment by stsp** [comment]
`init_charset_keys()` seems to be the big
offender. It first runs the big loop over
`trconfig.keyb_config_charset` and then
calls `check_video_mem_charset()`
that runs the loop over
`trconfig.video_mem_charset`.

Needs to check if nothing of this duplicates
`init_all_DOS_tables()`

**Comment by stsp** [comment]
Hmm, it seems mfs.c does nasty things:
it traverses unicode tables and creates
the translation tables for its own use.
All other subsystems are not using these
tables and do translations on their own.
This needs to be fixed.

**Comment by stsp** [comment]
I've found an offender: `start_vde()` does
`select()` with 1s delay to wait for `vde_switch`
to start. And if it doesn't contain patches
from dosemu, then it starts but doesn't
reply as expected, so select() sleeps for entire
second. I wonder how to fix this... Moving to
a separate thread looks difficult.

**Comment by andrewbird** [comment]
Perhaps make vde_switch support a non default option?  i.e. you enable its startup if you want it, and presumably have the patched version installed.

**Comment by stsp** [comment]
Unfortunately we don't yet have anything better.
For example tap support requires a lot of setup
from user, with root privs.
The same problem is with timidity btw.
But its not default, so probably nobody cares(
and maybe it already got all the needed patches in).

**Comment by stsp** [comment]
```
ERROR: VDE startup failure

real	0m0,263s
user	0m0,178s
sys	0m0,087s
```

Looks good.
