### ISSUE TITLE
PC/GEOS crashes DOSEmu2 when renaming or moving files with LFN enabled

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#556]
PC/GEOS has a specific driver for LFN (mslf.geo), which has been working very well. Starting with the commit 734dfa4304d58306806ebb948c3c4a37ca7c9434, renaming or moving files in PC/GEOS crashes the DOSEmu2. Using SFN still works fine. This was reported by a GEOS user and has been reproduced / bisected on my machine.

RENAMING a file produces the following:
```
ERROR: Accessing reserved memory at 7fd53c021000
	Maybe a null segment register
Segmentation fault (core dumped)
```

MOVING a file produces the following:
```
ERROR: Accessing reserved memory at 7f09335d5000
	Maybe a null segment register
ERROR: Fault handler re-entered! signal=11 _trapno=0xD
```

I'm not familiar with the LNF code of the DOSEmu2. How can I assist to solve this issue ? Special debug options ?

**Comment by stsp** [comment]
The second case should produce the log with
stack trace, if things are built with debug info.
Please attach that.
Also please run dosemu under valgrind.
```
valgrind --trace-children=yes --track-origins=yes dosemu
```
This will work only in `$_cpu_emu="vm86sim"` mode,
and will be horribly slow.

**Comment by stsp** [comment]
I reproduced.

**Comment by bolle732** [comment]
I'm currently back on devel, where it doesn't write a stack trace. Will return to first bad commit and try it again later this day.

**Comment by stsp** [comment]
Do you mean on bad commit it did produce a
stack trace, but not any longer?
That would be good for a separate report!
Please bisect when it stopped producing the
stack trace, while I am fixing the original problem.

**Comment by stsp** [comment]
Actually I think there is no regression with
trace printing. Its just that the bug overwrote
the entire memory, so the backtracer also broke.
Nasty bug but hope not too many people will hit it.

**Comment by bolle732** [comment]
Thanks again very much for solving the issue. You're really fast!

**Comment by stsp** [comment]
I applied a different fix.
Please see if it works right.

**Comment by bolle732** [comment]
Yes, it still works. Tested with creating, renaming and moving file(s).
