### ISSUE TITLE
Problem with mouse under X with full screen (out of range mouse coordinates)

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#557]
Since the commit b126c63b9d724c8becaabcb0fc925997811ea654, I have problems running PC/GEOS with `-X` in the full screen mode.

For example, host system has 1920x1080. PC/GEOS runs with 1280x854x16 VESA mode under DOSEmu2. Starting up in windowed mode, every thing works fine.

Starting up in full screen `-w` or switching to full screen using Ctrl-Alt-F and then moving the mouse to most right or down, will hit  the following message:
```
ERROR: MOUSE: Y out of range: 869 > 853
ERROR: MOUSE: Y out of range: 854 > 853
ERROR: MOUSE: Y out of range: 861 > 853
ERROR: MOUSE: Y out of range: 854 > 853
ERROR: MOUSE: Y out of range: 870 > 853
ERROR: MOUSE: Y out of range: 854 > 853
ERROR: MOUSE: Y out of range: 879 > 853
ERROR: MOUSE: Y out of range: 854 > 853
ERROR: MOUSE: Y out of range: 888 > 853
...
ERROR: MOUSE: Y out of range: 854 > 853
ERROR: MOUSE: Y out of range: 854 > 853
ERROR: MOUSE: Y out of range: 854 > 853
ERROR: general protection at 0x7fbbbca1da4d: 2
ERROR: PCM: "ao" too large delay, start=4295671.000000 min=13977061.000000 d=9681390.000000
```
At this point, the mouse stops working and DOSEmu2 gets unresponsive. Switching back to windowed mode needs about 20 seconds. But at the end, I have to kill the DOSEmu2 session.

**Comment by stsp** [comment]
Yes, this commit was introduced exactly
to trigger the anomalies. You can replace
`dosemu_error` with `error` there, and
fare well.
I will analyse this a bit later, maybe its just
a false-positives in the checks I added.
For now I am striving to get something
presentable from my freedos fork till FOSDEM.
Sleepless nights for entire week. :)
Only 2 days left (2 nights actually, as during
the day I have to code on my daily job), and
I am really desperate to get at least the boot-up
screen picture to show. Such a small goal
for 3 months of a very hard work - failing even
that would be a shame. :)

**Comment by bolle732** [comment]
Thanks, with `error` it works fine on this machine here. So, no hurry...

I wish you the best to get ready for the FOSDEM presentation. Marked the schedule of Barts speak at Sunday in my calendar.

**Comment by stsp** [comment]
Should now be fixed.
