### ISSUE TITLE
RENAME is broken with full path destination

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#558]
````
D:\FPD26>rename D:\FPD26\CONFIG.TMP D:\FPD26\fx.bat
Syntax error. - 'D:\FPD26\fx.bat'
 
D:\FPD26>rename D:\FPD26\CONFIG.TMP fx.bat
D:\fpd26>
````

**Comment by andrewbird** [comment]
A couple of questions:
- Which DOS is this under?
- Is it a regression, if so when did it work?

**Comment by andrewbird** [comment]
FreeDOS 1.2's command.com dosen't seem to support full path destination.
~~~
C:\bob>rename /?
Renames a file/directory or files/directories.
 
RENAME [drive:][path][directoryname1 | filename1] [directoryname2 | filename2]
REN [drive:][path][directoryname1 | filename1] [directoryname2 | filename2]
 
Note that you cannot specify a new drive or path for your destination. Use
the MOVE command for that purpose.
~~~
~~~
C:\bob>dir
 Volume in drive C is ir/dXXXXs/c
 Directory of C:\BOB
 
.                    <DIR>  02-04-18 12:32p
..                   <DIR>  02-04-18 12:32p
VERSION  BAT            17  01-23-18  5:30p
         1 file(s)             17 bytes
         2 dir(s)     35,812 Mega bytes free
~~~
~~~
C:\bob>rename c:\bob\version.bat c:\bob\version.tst
Syntax error. - 'c:\bob\version.tst'
~~~
~~~
C:\bob>rename c:\bob\version.bat \bob\version.tst
Syntax error. - '\bob\version.tst'
~~~
~~~
C:\bob>rename c:\bob\version.bat version.tst
C:\bob>
~~~

**Comment by stsp** [comment]
Hmm, interesting point!
But I suspect it used to work nevertheless,
before I fiddled with mfs rename code recently.

**Comment by andrewbird** [comment]
In the log I don't see rename even being called and the syntax error comes from FreeDOS. 
~~~
$ strings test-imagedir/dXXXXs/c/command.com | grep 'Syntax'
Syntax error. - '%s'
~~~
As a test I try it on fatfs
~~~
C:\>lredir2 -d c:
Redirection for drive C: was deleted.
C:\>cd bob
C:\BOB>dir
 Volume in drive C is DXXXXS C
 Volume Serial Number is 4ADD-1B8A
 Directory of C:\BOB
 
.                    <DIR>  02-04-18  3:16p
..                   <DIR>  02-04-18  3:16p
VERSION  BAT            17  01-23-18  5:30p
         1 file(s)             17 bytes
         2 dir(s)     116,701,184 bytes free
C:\BOB>rename c:\bob\version.bat c:\bob\version.tst
Syntax error. - 'c:\bob\version.tst'
~~~

**Comment by stsp** [comment]
So was it reported right after my rename
changes, just by a coincident? Oh.

**Comment by andrewbird** [comment]
Also fails on dosemu2 pre7, so unless the reporter is using a different version of DOS (and it has an identical 'Syntax error' string), this doesn't look to me like fallout from your rename changes.

**Comment by stsp** [comment]
Thanks for your help!
Lets close it then, until reporter provides more info.

**Comment by severach** [comment]
The breaking change is in 98237909e . It definitely fixed something because before that the DOS `rename` gave `ERROR: Accessing reserved memory at 7f134231a000`. The API call did not cause any crashes.

`FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]`

I wasn't using RENAME from DOS. The API call that has worked since 2003 broke. It didn't occur to me that FreeDOS would also be broken. DOS has always accepted full path in the rename destination.

**Comment by stsp** [comment]
PC-DOS's ren also doesn't allow this.
You can try `move`.
But move doesn't seem to work either. :)
So lets open this and fix something.

**Comment by severach** [comment]
`move` is probably the easiest demo. Borland C++ help says:

````
rename:
Directories in oldname and newname do not need to be the same, so rename can
be used to move a file from one directory to another.
````
If not, here's a demo.
[rentest.zip](https://github.com/stsp/dosemu2/files/1693334/rentest.zip)

**Comment by stsp** [comment]
OK, should now be fixed.

**Comment by stsp** [comment]
Yes, `rename` currently doesn't seem to
support LFNs. But its a bit wrong place of
reporting that. You can try report this to
freedos, or even code yourself - should be
quite simple I suppose.

**Comment by andrewbird** [comment]
Does the rename call in djgpp's c api support lfns? I know that its open call does without extra work if the DOS underneath supports lfn, else it falls back to sfn.

**Comment by stsp** [comment]
Sorry I meant `move`.
