### ISSUE TITLE
lredir redirects too much

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#561]
If you lredir something, lredir also restores
the previously deleted (if any) redirections
of fatfs drives.

**Comment by stsp** [comment]
This is fixed, but there seems to be a problem:
if redirect_devices() is called just once, from emufs.sys,
then it doesn't work. When it is called from post_boot()
(autoexec), either alone or after emufs.sys, then it
works perfectly. So for now I made it so that it is always
called from post_boot(), regardless of what emufs.sys did.

Andrew, is it the same problem you were talking
about, which is that it is not possible to enable the
redirector from config.sys?
You can uncomment int.c:1886 to see the problem
yourself.

**Comment by andrewbird** [comment]
Yes, I think that's because the CDS array is created again in a different location after config.sys is closed. I'm not sure if any of the DOS versions copy the old contents to the new location, so it's likely any dosemu redirected drive mappings are lost.

**Comment by stsp** [comment]
Maybe you can uncomment the line
I pointed, and see what DOSes do have
that problem?

**Comment by andrewbird** [comment]
Okay will try tomorrow. However I do believe it's wrong to do redirect_devices() from config.sys as CDS location will change and maybe its size too after config.sys is closed.

**Comment by stsp** [comment]
Sigh. Then we need to think up something new,
but post_boot() solves the problem in the short
terms, which is also very good to know.
To think up a better solution it would be good
to know what DOSes are affected.

**Comment by andrewbird** [comment]
Mmm, why move functionality from lredir2 to lredir?
- it doesn't make it any more secure even if you remove lredir later. IMHO you have to protect the 'risky' functionality on the redirector side, not client side. What's to stop the rogue DOS binary doing the int21/5f03 call itself?
- It's confusing as we've done the whole `lredir` is old compatible syntax move to `lredir2` thing. Now batch files we moved to `lredir2` now need to return to using `lredir` if we wish to map linux paths.

BTW getting a crash here with `lredir` list after mapping a drive `lredir e: LINUX\FS\bin`
~~~
$ cat test-imagedir/dosemu.conf 
$_lpt1 = ""
$_hdimage = ""
$_floppy_a = "dXXXXs/c:fiveinch_360"
$_bootdrive = "a"
~~~

~~~
ERROR: Fault in dosemu code, in_dpmi=0
ERROR: cpu exception in dosemu code outside of VM86()!
trapno: 0x0e  errorcode: 0x00000004  cr2: 0x5d5620a0
eip: 0x080d12e9  esp: 0x9a5fed70  eflags: 0x00010202
cs: 0x0073  ds: 0x007b  es: 0x007b  ss: 0x007b
fs: 0x0000  gs: 0x0033
~~~

Nothing interesting in boot.conf even with debug flags '+DdRWj\#'

BTW I didn't try uncommenting the line yet, testing just devel with MS-DOS 6.22

**Comment by stsp** [comment]
> Mmm, why move functionality from lredir2 to lredir?

The idea is to leave only the safe subset in lredir2.

> IMHO you have to protect the 'risky' functionality on the redirector side, not client side.

This is certainly true.
But if I don't do the changes on the client side
first, then the changes on a redirector side will
lead to strange effects, that some perfectly valid
commands no longer work (which is what some
people see even now, but this is not intentional).
So my idea is to first spare the default setup from
the risky functionality and disable it by default.
Then, if I also add the checks inside the redirector,
nothing will practically change.

> It's confusing as we've done the whole lredir is old compatible
> syntax move to lredir2 thing. Now batch files we moved to lredir2
> now need to return to using lredir

This is a temporary solution. I do not advice
anyone to move their batch files to lredir1.
What I am going to do is to add the configuration
options for things that are currently done with
DOSDRIVE_XTRA and CDROM_PATH. They
currently require lredir's syntax of mapping linux
pathes, but with the config options added, they
won't. So people will not have to move back to
lredir.com - they will instead have to write their
pathes into their .dosemurc. Maybe I didn't have
to expose this early change to devel before the
new options are introduced. I can of course
revert this all and move to a separate branch,
but as you can see, this exposes some interesting
bugs, which would otherwise be not tested.

I am open to any suggestions. I just don't think
this can be done w/o another compatibility break.

> Nothing interesting in boot.conf even with debug flags '+DdRWj#'

Can you run this under gdb, breakpoint to
`error` or `dosemu_error` and provide the
stack trace? In a mean time I'll see if maybe
valgrind can find something, as surprisingly
all works well here!

**Comment by stsp** [comment]
```
C:\>lredir e: linux\fs\bin
Error: drive E: already redirected.
       Use -d to delete the redirection or -f to force.
C:\>lredir -f e: linux\fs\bin
Redirection for drive E: was deleted.
E: = \\LINUX\FS\BIN attrib = READ/WRITE     
```

No crash... and this is under valgrind.
All works well!
Heeeelp! :)

**Comment by stsp** [comment]
> Nothing interesting in boot.conf even with debug flags '+DdRWj#'

What is boot.conf?
You need `~/.dosemu/boot.log` which should
contain the stack trace.

**Comment by andrewbird** [comment]
'boot.conf` was a stupid typo, but even more stupid was forgetting that I'd specified an alternative logfile on the command line. Here it is
[test.log.txt](https://github.com/stsp/dosemu2/files/1734829/test.log.txt)

Perhaps the problem occurs for me because I have no MFS drives mapped by default, I'm booting from floppy dir

Any reason we can't have the old syntax on lredir2, then check the path to be mapped on the redirector side and depending upon a config option allow or deny the linux paths? Any special values that may need to be flagged could be done using int 21/5f03's CX just like readonly is done now.

**Comment by stsp** [comment]
I re-enabled the old syntax in lredir2 until
the final solution is complete.
So now we just need to understand what
bug do we have here.

**Comment by stsp** [comment]
> Any reason we can't have the old syntax on lredir2,
> then check the path to be mapped on the redirector
> side and depending upon a config option allow or deny the linux paths?

Yes, in my eyes such a reason does exist.
There are 2 possible approaches to security:
one is to have some enforcing policy that will
out of sudden say
"oops, you can't do this. error redirecting drive".
I don't like that approach. It was tried in dosemu-1.0
in the form of `$_secure=(on)`.
Another approach is to design your software
the way no common scenarios and syntaxes
can do anything insecure. In this case, instead
of removing some functionality by the means
of a security policy, you instead add an extra
(insecure) functionality by providing more tools
for the advanced user that the normal users
would never need. Then the only "security
policy" is to just disable those tools by default.

Of course, as you correctly stated, int 21/5f03
should have to be dealt with, no matter what.
But in the second case, when you have the
safe syntax by default, all you have to do in
the redirector is to check whether the new
path is inside one of the previously mapped
pathes. This is only possible if you moved all
the interesting functionality (DOSDRIVE_XTRA,
CDROM_PATH) that is now achieved by the
means of an unsafe syntax, into the config
file - then the redirector can do a very easy
check based on an existing pathes.
If you don't move things and keep depending
on an unsafe syntax for them, then you'll be
up to the security-enforcing policy that checks
if the path is "safe" etc.

**Comment by stsp** [comment]
Compare that with `unix.com`.
If it would still be a mix of secure and
insecure features, then you are up to
a security policy that restricts the parts
of `unix.com`. But as all safe & useful
functionality was split into `system.com`,
you only declare `unix.com` an extra tool
for advanced users, and disable it.

**Comment by andrewbird** [comment]
> "oops, you can't do this. error redirecting drive".
I don't like that approach. It was tried in dosemu-1.0
in the form of $_secure=(on).

That really surprises me that you don't like it. All clients that setup redirection should expect that the server(in our case dosemu's internal redirection) might deny the request. Removing the command altogether is far harder to deal with as a user than receiving a message saying what you tried to do was denied.

I think that allowing a previously mapped path or a subtree of one is an elegant idea. I'm fine with the idea of removing the need to use the absolute path for CDROM etc.

As always I have to qualify that I don't use Dosemu for anything other than testing its own functionality, so I may be misguided.

BTW, I think the crash i saw is something to do with select_drive() being called as a result of int21/5f02, when of course there's no specific drive or CDS entry associated with listing redirections. It may only have just appeared for me due to the changes in the MFS init sequence?

**Comment by stsp** [comment]
> All clients that setup redirection should expect that the
> server(in our case dosemu's internal redirection) might deny the request.

The main idea here is that functionality
should not be needed by default. As we
currently depend on it - yes, it all looks
the way you imagine. If I disable some
tool that the default setup or most users
depend on, this is hard to deal with.
BUT, move all the interesting functionality
out of this, allow mapping the needed
pathes in the config file w/o `$_hdimage`
cost, and suddenly no one even needs
to deal with the unsafe redirections! And
then, instead of removing the command,
you can think of it as adding an extra
command that is needed only for advanced
users. And only that advanced command
should deal with the possibility of some
request's denial. All is needed is just a
proper functionality split, like was with
unix.com. Hardly anyone blamed me for
that split, and hardly anyone will complain
if unix.com is disabled by default. But lredir
was missed. I just ported all lredir1's functionality
into lredir2 w/o thinking of any split, and now
that's the problem.

**Comment by stsp** [comment]
> All clients that setup redirection should expect that the
> server(in our case dosemu's internal redirection) might deny the request.

So the simple question is: if (IFF) we can
create the setup where this never happens,
why wouldn't we do just that, and instead
make everything prepared for the request
denials? Because this will turn off some
important functionality? Yes, but we can
find the way of providing that functionality
by another techniques (like in a config file).
And then why? Because we are too lazy? :)
I think the only right answer here is because
of the backward compatibility.

**Comment by stsp** [comment]
So in practice.
Say you need to access everything inside
your home dir. You just set:
```
$_extra_drive = "/home/${USER}"
$_lredir_tool = (on)
```
and this is it.
Or you may want to map everything inside
/tmp. Or anywhere else. All you do is like the
above.
Now if you don't move DOSDRIVE_XTRA
into the config and it still depends on an ability
to access the whole FS, how would you apply
any limits? Adding some options like
`$_secure_pathes` or how? In general I don't
want to see any options of the `$_secure_xxx`
pattern.

**Comment by stsp** [comment]
> Perhaps the problem occurs for me because I
> have no MFS drives mapped by default, I'm booting from floppy dir

So I booted from ms-dos 6.22 hdimage
with lredir on it:
```
C:\>ver
MS-DOS Version 6.22
C:\>dosemu\lredir d: linux\fs/home
D: = \\LINUX\FS/HOME attrib = READ/WRITE
```

So why everything works perfectly, and yet
everyone out there reports the problem? :)

**Comment by stsp** [comment]
Please open a new ticket about your crash then.

**Comment by andrewbird** [comment]
I think booting from floppy dir (no drives mapped) is not the same as booting from HD and doing lredir -d

**Comment by andrewbird** [comment]
Sorry just misread your last post, please ignore!

**Comment by stsp** [comment]
```
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
A:\>lredir
No drives are currently redirected to Linux.
A:\>lredir c: linux\fs/home
C: = \\LINUX\FS/HOME attrib = READ/WRITE
A:\>lredir
Current Drive Redirections:
C: = \\LINUX\FS\home\     attrib = READ/WRITE
A:\>
```

This seems to be fully replicating your setup.

**Comment by stsp** [comment]
So if only calling redirect_devices() from
config.sys corrupts something inside freedos,
and things broke differently for people (and
not for me).

**Comment by andrewbird** [comment]
An interesting observation is that if the drive redirected is `c:` or `d:` the subsequent lredir list starts to be printed, whereas if it's `e:` the crash occurs immediately.

**Comment by stsp** [comment]
```
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
A:\>lredir e: linux\fs/home
E: = \\LINUX\FS/HOME attrib = READ/WRITE
A:\>lredir
Current Drive Redirections:
E: = \\LINUX\FS\home\     attrib = READ/WRITE
A:\>
```

**Comment by stsp** [comment]
Could you try w/o emufs.sys?
Then redirect_devices() will only be called
from autoexec (via post_boot hook).

**Comment by andrewbird** [comment]
After commenting out emufs.sys it still crashes.

**Comment by stsp** [comment]
Then I have no idea what to do, or how
to reproduce, as the only real change
was that I call redirect_devices() earlier...
Maybe you can take a look yourself then?

**Comment by stsp** [comment]
Aren't you using ia16-gcc freedos by any chance?

**Comment by andrewbird** [comment]
Sure, can you check that the mapped drive shows the contents you expect,  e.g. `DIR C:`

**Comment by andrewbird** [comment]
Not yet, just MS-DOS 6.22

**Comment by stsp** [comment]
```
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
A:\>lredir
No drives are currently redirected to Linux.
A:\>lredir c: linux\fs/home/stas/.dosemu
C: = \\LINUX\FS/HOME/STAS/.DOSEMU attrib = READ/WRITE
A:\>c:
C:\>dir
 Volume in drive C is tas/    dos.
 Directory of C:\
 
BOOT     LOG         3,362  02-19-18  5:05p
RUN                  <DIR>  02-19-18  5:05p
BOOTL~8B 3         901,445  03-04-17  1:00a
DRIVE_C              <DIR>  02-19-18  5:04p
BOOTL~8B 1           3,606  02-19-18  5:05p
C        IMG    268,435,456  02-19-18  2:02a
DRIVES               <DIR>  09-26-17  5:10a
DISCL~-!               412  03-04-17 12:56a
BOOTL~8B 2           3,678  03-04-17  1:00a
         6 file(s)    269,347,959 bytes
         3 dir(s)   1,226,276,864 bytes free
C:\>
```

So everything is fine.
But I can see this during boot:
```
 - InitDiskno hard disks detected
```
when no drives are mapped.
Maybe there is some corruption here,
as InitDiskno should be a bumber I guess.

**Comment by ecm-pushbx** [comment]
` - InitDiskno hard disks detected`

My bet is it's "InitDisk" followed by "no hard disks detected".

**Comment by stsp** [comment]
:)
Good eye.
