### ISSUE TITLE
PharLap DOS Extender

### ISSUE THREAD

**Issue by sduensin** [stsp/dosemu2#563]
EMUfailure says:

> Older versions of the Pharlap Extender (run286) need ring-0 access
> under DOSEMU to install their own DPMI server. The use of proprietary
> undocumented extensions to the DPMI protocol makes DOSEMU's DPMI server
> unsuitable for this extender.

Does anyone know what "Older versions" actually is?  Is there a version known to work?

**Comment by stsp** [comment]
Phar Lap's 286|DOS-Extender(tm) won't work
Phar Lap's 386|DOS-Extender(tm) works.
