### ISSUE TITLE
Second fullscreen with -X is offset

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#567]
Under Ubuntu 17.10 64 bit with Gnome Shell -

If you toggle fullscreen twice, using the -X driver then the screen is offset by the height of the gnome shell title bar.

The bottom of the screen being chopped off is how it appears on the real screen -

![image](https://user-images.githubusercontent.com/179677/36647986-f87f5d06-1a84-11e8-95a0-3bb3a29bb42d.png)

**Comment by stsp** [comment]
I can't reproduce this and actually think
this depends on a WM.
But I reproduced lock-ups and crashes
when switching rapidly, both in X and in
SDL modes.

**Comment by stuaxo** [comment]
That sounds right, I use gnome-shell, but it certainly has it's issues.   I'll see what happens in the ubuntu-desktop thing in the VM I setup and see what happens.

Ubuntu is getting rid of their infrastructure and moving to one based on gnome shell, so it might affect more people.  - I should probably test under wayland vs X as well and see what happens. 

I haven't had any crashes, but the lockups seemed to happen almost every time.

**Comment by stsp** [comment]
Crashes are SDL-specific.
In fact I am thinking about offering the bounties
for this bugzilla (whole bugzilla, not this particular
ticket), as I clearly can't spend my whole life in it. :)
Does anyone have the suggestions regarding the
bounty values? Does this work in practice?

**Comment by stuaxo** [comment]
The bug tracker can eat your life - would be nice if there was a way I could put in a bug like this, with a label that means "this doesn't affect me, just letting you know in case it helps".

**Comment by stsp** [comment]
> label that means "this doesn't affect me, just letting you know in case it helps".

Its quite a problem that this bug affects only me.
Maybe the bounties will help to make it affecting you instead? :)

**Comment by stuaxo** [comment]
It's time that I'm really short of (OK, attention span does seem to get divided between too many OS projects too).   

But yeah, I can definitely try and concentrate on this one bug on my limited dosemu time.

Usually fairly good at triggering bugs, but then that's not what takes the time.

**Comment by stsp** [comment]
This particular bug is not a problem.
It would be good if you just make sure it is
WM-related, as it doesn't seem to happen
for me.
It would be much better to fix other 66 bugs
in this bugzilla though. :)

**Comment by stsp** [comment]
Is this still reproducible?

**Comment by stuaxo** [comment]
I had a quick go on the devel branch just now, following the instructions in INSTALL but wasn't able to get dosemu to find freedos.

I downloaded  dosemu-freedos-1.0-bin.tgz  and ran 

```bash
$ make
$ sudo make install
```

After this there is no directory /usr/local/share/dosemu/freedos, which it seems to look for

```bash
$ ls /usr/local/share/dosemu/
commands  dosemu2-cmds-0.1  dosemu2-cmds-0.2  drive_z  icons  keymap  Xfonts
```


```
sudo make install
make[1]: Entering directory '/home/stu/projects/external/dosemu2/src'
/usr/bin/install -c -d /usr/local/share/dosemu
rm -rf /usr/local/share/dosemu/commands /usr/local/share/dosemu/freedos/dosemu
rm -rf /usr/local/share/dosemu/fdboot
rm -rf /usr/local/share/dosemu/dosemu2-cmds-0.2/dosemu
rm -rf /usr/local/share/dosemu/dosemu2-cmds-0.2
/usr/bin/install -c -d /usr/local/etc/dosemu
/usr/bin/install -c -d /usr/local/share/dosemu/dosemu2-cmds-0.2
/usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/src/bindist/config.sys /usr/local/share/dosemu/dosemu2-cmds-0.2
/usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/src/bindist/autoexec.bat /usr/local/share/dosemu/dosemu2-cmds-0.2
/usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/src/bindist/fdconfig.sys /usr/local/share/dosemu/dosemu2-cmds-0.2
/usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/src/bindist/autoemu.bat /usr/local/share/dosemu/dosemu2-cmds-0.2
/usr/bin/install -c -d /usr/local/share/dosemu/dosemu2-cmds-0.2/dosemu
for i in `find ../commands/* -type f`; do \
  /usr/bin/install -c -m 0644 $i /usr/local/share/dosemu/dosemu2-cmds-0.2/dosemu; \
done
cd ../commands; for i in `find * -type l`; do \
  ln -sf generic.com /usr/local/share/dosemu/dosemu2-cmds-0.2/dosemu/$i; \
done
ln -sf dosemu2-cmds-0.2 /usr/local/share/dosemu/commands
if [ ! -f /usr/local/etc/dosemu/dosemu.conf ]; then \
  /usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/etc/dosemu.conf /usr/local/etc/dosemu; \
fi
/usr/bin/install -c -d /usr/local/share/dosemu/keymap
for i in /home/stu/projects/external/dosemu2/etc/keymap/*; do \
  if [ -f $i ]; then \
    /usr/bin/install -c -m 0644 $i /usr/local/share/dosemu/keymap; \
  fi; \
done
/usr/bin/install -c -d /usr/local/share/dosemu/icons
for i in /home/stu/projects/external/dosemu2/etc/*.xpm; do \
  if [ -f $i ]; then \
    /usr/bin/install -c -m 0644 $i /usr/local/share/dosemu/icons; \
  fi; \
done
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -m 0755 ../bin/dosemu.bin /usr/local/bin
/usr/bin/install -c -m 0755 ../bin/dosemu /usr/local/bin
/usr/bin/install -c -m 0755 ../bin/mkfatimage16 /usr/local/bin
/usr/bin/install -c -m 0755 ../bin/dosdebug /usr/local/bin
/usr/bin/install -c -d /usr/local/lib/dosemu
for i in ../bin/*.so; do \
  if [ -f $i ]; then \
    /usr/bin/install -c -m 0644 $i /usr/local/lib/dosemu; \
  fi; \
done
/usr/bin/install -c -d /usr/local/share/doc/dosemu2
for i in README.bindist NEWS THANKS BUGS changelog; do \
    /usr/bin/install -c -m 0644 ../$i /usr/local/share/doc/dosemu2; \
done
for i in README EMUfailure tweaks; do \
  /usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/doc/$i.html /usr/local/share/doc/dosemu2; \
done
/usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/doc/NOVELL-HOWTO.txt /usr/local/share/doc/dosemu2
/usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/doc/README.gdb /usr/local/share/doc/dosemu2
/usr/bin/install -c -d /usr/local/share/dosemu/Xfonts
echo "-> Installing the X PC fonts..."
-> Installing the X PC fonts...
for i in ../etc/*.pcf.gz; do \
    install -m 0644 $i /usr/local/share/dosemu/Xfonts; \
done
/usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/etc/dosemu2.alias /usr/local/share/dosemu/Xfonts/fonts.alias; \
! which mkfontdir >/dev/null || mkfontdir /usr/local/share/dosemu/Xfonts
if [ -d "/usr/local/etc/X11/fontpath.d" ]; then \
    rm -f /usr/local/etc/X11/fontpath.d/dosemu2:unscaled:pri=20; \
    ln -sf /usr/local/share/dosemu/Xfonts /usr/local/etc/X11/fontpath.d/dosemu2:unscaled:pri=20; \
fi
echo "-> Installing man pages..."
-> Installing man pages...
make -C ../man install
make[2]: Entering directory '/home/stu/projects/external/dosemu2/man'
/usr/bin/install -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 0644 *.1 /usr/local/share/man/man1
for i in ru; do \
    /usr/bin/install -c -d /usr/local/share/man/$i/man1; \
    /usr/bin/install -c -m 0644 $i/*.1 /usr/local/share/man/$i/man1; \
    /usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/man/$i/*.1 \
      /usr/local/share/man/$i/man1; \
done
make[2]: Leaving directory '/home/stu/projects/external/dosemu2/man'
cd /home/stu/projects/external/dosemu2; \
if [ -n "" -a -f "" ]; then \
  echo "-> Installing FreeDOS..."; \
  rm -rf /usr/local/share/dosemu/freedos; \
  tar -C /usr/local/share/dosemu/.. --no-same-owner -xpzvf ; \
  rm -f /usr/local/share/dosemu/FDchange.log; \
  rm -f /usr/local/share/dosemu/README.bindist; \
  rm -rf /usr/local/share/dosemu/freedos/tmp; \
fi
if [ -d /usr/local/share/dosemu/freedos ]; then \
  ln -sf /tmp /usr/local/share/dosemu/freedos/tmp; \
  /usr/bin/install -c -d /usr/local/share/dosemu/fdboot; \
  cd /usr/local/share/dosemu/fdboot; \
  find -L ../commands -maxdepth 1 -type f -printf '%p %P\n' | xargs -L 1 ln -s; \
  ln -s ../freedos/kernel.sys kernel.sys; \
  ln -s ../freedos/command.com command.com; \
fi

---------------------------------DONE Installing-------------------------------

  - You can type 'dosemu' to run DOSEMU. If you installed the FreeDOS tarball
    too (see the warning above), then DOSEMU will set up a directory structure
    in your home directory when you run it for the first time.
make[1]: Leaving directory '/home/stu/projects/external/dosemu2/src'
make[1]: Entering directory '/home/stu/projects/external/dosemu2/man'
/usr/bin/install -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 0644 *.1 /usr/local/share/man/man1
for i in ru; do \
    /usr/bin/install -c -d /usr/local/share/man/$i/man1; \
    /usr/bin/install -c -m 0644 $i/*.1 /usr/local/share/man/$i/man1; \
    /usr/bin/install -c -m 0644 /home/stu/projects/external/dosemu2/man/$i/*.1 \
      /usr/local/share/man/$i/man1; \
done
make[1]: Leaving directory '/home/stu/projects/external/dosemu2/man'
```

```bash
$ dosemu
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: FreeDOS not found, not doing install
/usr/local/share/dosemu/freedos/kernel.sys missing
ERROR: Bootable drive not found, exiting
```

**Comment by stsp** [comment]
> I downloaded dosemu-freedos-1.0-bin.tgz and ran
> $ make
> $ sudo make install

Not enough.
Need to also run `./default-configure` after downloading freedos.

**Comment by stsp** [comment]
Note that freedos-less setup is possible
from this day.

**Comment by stuaxo** [comment]
Bug is still reproducable, it's slightly different to my original screenshot - I had 'pixel saver extension enabled', which hides the titlebar for maximised windows.

With no extensions enabled, on second fullscreen:

Window is still offset in the vertical direction, but it has a titlebar.

**Comment by stsp** [comment]
Are the screen shots here? Dont see.
May be because of my mobile, but I see
the first screen shot.

**Comment by stuaxo** [comment]
Apologies, I had a bit of trouble screenshotting, here is a screencast

You can pause the video at:

First fullscreen at 5 seconds, 
Second at 10 seconds

https://youtu.be/ccRHkPGmqmQ

**Comment by stsp** [comment]
> I haven't had any crashes, but the lockups seemed to happen almost every time.

Can you still reproduce lock-ups?
I think they are fixed.

**Comment by stuaxo** [comment]
I can't reproduce them (though I think I'm newer Ubuntu now).

One slightly odd thing in freedos edit:

If I open the file-open dialog in fullscreen and drag the title bar, everything seems fine:  the window border moves until I let go of the mouse.

If I do the same thing in windowed mode, the border goes green but then doesn't seem to move until I let go of the mouse and then the window draws in the destination.
