### ISSUE TITLE
toggling fullscreen in -X mode may lock up

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#568]
Quickly toggling freezes dosemu window.

**Comment by stuaxo** [comment]
I'll test this later and see if it helps with FD-EDIT.    I've realised FD-EDIT happens without fullscreen.

```
$ dosemu -X
EDIT
```

Now the mouse will flicker for about 5 seconds and then the EDIT TUI appears.

Hit Alt-F to open the file menu and the same thing happens.

**Comment by stsp** [comment]
> I've realised FD-EDIT happens without fullscreen.

Then its a different bug, please open another ticket.
