### ISSUE TITLE
Lockup / flickering mouse pointer in Freedos EDIT

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#570]
Tested under Dosemu with X backend and SDL2 
on Ubuntu 64 bit 17.10

```
$ dosemu -X
EDIT
```
Mouse flickers really fast for about 4-5 seconds then EDIT TUI shows up.

Click ```File``` wait about 4 seconds until the menu shows up.

The first time under SDL, there was no lockup until using the file menu, the second time it worked the same as under X.

**Comment by stsp** [comment]
Please try the change mentioned here:
https://github.com/stsp/dosemu2/issues/417#issuecomment-347486841

**Comment by stsp** [comment]
Any progress?

**Comment by stuaxo** [comment]
I tried on devel, but am not able to reproduce this.

By now I'm on a different laptop and newer Ubuntu (probably wayland now, may have been X before).

Closing, since can't repro - hopefully this has been fixed / gone away :)
