### ISSUE TITLE
crashes when booting lDOS iniload + testpl as KERNEL.SYS (except with dosdebug t or tc) [int0 handler missing, FreeDOS loading should provide BPB, dosdebug t returns after div by zero inst]

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#577]
The source of the programs I'm using here is available at https://bitbucket.org/ecm/ldosboot/src/fc367ac5b5652741f5e3e94168c0dcab50ad6c89 plus https://bitbucket.org/ecm/lmacros/src/fbb65e3f6e7b9a96c61d360a7b817c4a305d4a4a

```
$ NAME=KERNEL EXT=SYS SUFFIX=tpl; for FAT in 12 16; do nasm -D_COMPAT_LDOS -D_LOAD_NAME="'$NAME'" -D_LOAD_EXT="'$EXT'" -D_CHS=1 -D_LBA_SKIP_CHECK -D_USE_PART_INFO=1 -D_QUERY_GEOMETRY=1 -D_FAT$FAT=1 boot.asm -o boot${FAT}${SUFFIX}.bin -D_MAP=boot${FAT}${SUFFIX}.map -l boot${FAT}${SUFFIX}.lst -I../lmacros/; done; nasm -D_COMPAT_LDOS -D_LOAD_NAME="'$NAME'" -D_LOAD_EXT="'$EXT'" -D_CHS=1 -D_LBA_SKIP_CHECK -D_USE_PART_INFO=1 -D_QUERY_GEOMETRY=1 boot32.asm -o boot32${SUFFIX}.bin -D_MAP=boot32${SUFFIX}.map -l boot32${SUFFIX}.lst -I../lmacros/../lmacros/lmacros1.mac:404: warning: unterminated string
boot.asm:1143: warning: FAT 12: 4 bytes still available. [-w+user]
../lmacros/lmacros1.mac:404: warning: unterminated string
boot.asm:1143: warning: FAT 16: 9 bytes still available. [-w+user]
../lmacros/lmacros1.mac:404: warning: unterminated string
boot32.asm:911: warning: FAT 32: 33 bytes still available. [-w+user]
boot32.asm:1267: warning: FSINFO: 12 bytes still available. [-w+user]
$ SUFFIX=tpl; nasm -D_MAP=testpl.map -l testpl.lst -o testpl.bin testpl.asm -I../lmacros/ && nasm -D_MAP=iniload.map -l iniload.lst -I../lmacros/ -o KERNEL.SYS -D_PAYLOAD_FILE='"testpl.bin"' iniload.asm && echo -ne "\$_hdimage = \"boot${SUFFIX}.img\"\n\n\$_bootdrive = \"c\"\n" > boot${SUFFIX}.cfg && mkfatimage16 -l "lDOS BOOT" -b boot16${SUFFIX}.bin -k 102400 -p -f boot${SUFFIX}.img KERNEL.SYS && dosemu -f boot.cfg --Fimagedir . -X
../lmacros/lmacros1.mac:404: warning: unterminated string
../lmacros/lmacros1.mac:404: warning: unterminated string
iniload.asm:567: warning: iniload: 29 bytes in front of ms7_entry [-w+user]
iniload.asm:929: warning: iniload: 21 bytes in front of ldos_entry [-w+user]
iniload.asm:1263: warning: iniload: 10 bytes in front of end [-w+user]
iniload.asm:1432: warning: iniload: 320 bytes in front of end2 [-w+user]
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
$ 
```

The above command chains properly boot this KERNEL.SYS using the lDOS load protocol. I expect that it therefore would work from FreeDOS load protocol too.

```
$ cp -iat ~/.dosemu/drives/c/ KERNEL.SYS
```

With the testpl KERNEL.SYS in the drive C: directory (and no IO.SYS, IBMBIO.COM, etc), I start dosemu2. Expected: The following display, though the exact values of registers may differ:

```
dosemu2 2.0pre8-20180306-142-g30950247d
Configured: 2018-03-09 22:32:52 +0100
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
 
 SS=9BB5 BP=0220 SP=0200 CS=00E0 IP=0000 FL=3346
 DS=9BB5 SI=2000 ES=9BB5 DI=2000
 AX=0000 BX=1111 CX=0001 DX=0000
 S0=A000 S1=9BB4 S2=9DFD S3=0120 S4=0100 S5=0000 S6=1111 S7=1111
 S8=0000 S9=0000 SA=FFFF SB=FFFF SC=9BFB SD=1111 SE=FFFF SF=0000
1st name: (None)
2nd name: (None)
3rd name: (None)
4th name: (None)
Test payload loaded.
```

What happens: Only the dosemu2 signon message is shown, the cursor is blinking, dosemu fully utilises a CPU core of the host system, nothing happens. It seems to be stuck. Debugging with dosemu -H1 and dosdebug exhibits the same behaviour if I run the program without breakpoints with a G command.

Running with repeated T commands or a TC command from dosdebug results in the expected output however.

Also, note that I expect ss:bp to point at a boot sector with (E)BPB in it, the way FreeDOS kernel boot sectors provide. (They have ss=1FE0h bp=7C00h, but the protocol as I interpret it isn't fixed to these addresses.) I can probably write up a patch to provide that. However, I don't think that this is the reason for the crash, as it should hang with dosdebug T/TC then too.

**Comment by ecm-pushbx** [comment]
Oops. I just started dosemu without -H1 *then* attached to it with dosdebug. It shows the following:

```
$ dosdebug

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
Reading map file nm /usr/local/bin/dosemu.bin | grep -v '\(compiled\)\|\(\.o$\)\|\( a \)' | sort
7836 symbol(s) processed
highest address 00776b50(_end)
system state: emulated,running
AX=ffff  BX=0000  CX=0004  DX=0000  SI=0000  DI=7dfe  SP=07a8  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00133246
CS:IP=f000:c002       SS:SP=1fe0:07a8

f000:c002 F4               hlt
r
system state: emulated,running
AX=ffff  BX=0000  CX=0004  DX=0000  SI=0000  DI=7dfe  SP=07a8  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00133246
CS:IP=f000:c002       SS:SP=1fe0:07a8

f000:c002 F4               hlt
t
must be in stopped state

must be in stopped state
stop
system state: emulated,stopped
AX=ffff  BX=0000  CX=0004  DX=0000  SI=0000  DI=7dfe  SP=07ae  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00003246
CS:IP=0060:0675       SS:SP=1fe0:07ae

0060:0675 F7F3             div  bx
t
system state: emulated,stopped
AX=ffff  BX=0000  CX=0004  DX=0000  SI=0000  DI=7dfe  SP=07ae  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00003346
CS:IP=0060:0677       SS:SP=1fe0:07ae

0060:0677 91               xchg cx,ax
t
system state: emulated,stopped
AX=0004  BX=0000  CX=ffff  DX=0000  SI=0000  DI=7dfe  SP=07ae  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00133346
CS:IP=0060:0678       SS:SP=1fe0:07ae

0060:0678 51               push cx
g
```

Note that it stopped at an interrupt handler called by the div bx in iniload.asm:1374. This is a division by zero because the sector size field of the missing BPB is set to 0. The hang is the correct behaviour, assuming that the interrupt 00h handler is functionally an "iret". dosdebug T or TC apparently return from the interrupt to *behind* the division instruction that caused the interrupt, which is in error.

**Comment by ecm-pushbx** [comment]
What can be done:

- dosemu should install a default interrupt 0 handler which is informative and shows what went wrong, and doesn't return to the same instruction.
- dosdebug T / TC shouldn't return to the instruction behind a division by zero.
- I can check for zero before doing divisions. (Could also install an interrupt 0 handler, but that is out of scope of iniload.)
- dosemu can pass the BPB.

**Comment by stsp** [comment]
Please split this ticket to the one per problem.

I think we do provide BPB, see `fatfs.c:read_boot()`.
In particular, `set_bpb_common()` should set
up sector size. So please see if maybe you can
find a bug there.

**Comment by stsp** [comment]
dosdebug problem seems to be jit-specific.
Doesn't happen on sim or kvm.
