### ISSUE TITLE
clang compile quitting foxpro crashes DOSEMU window

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#579]
Does not happen in gcc compile.

[boot.log.clang.zip](https://github.com/stsp/dosemu2/files/1799129/boot.log.clang.zip)

**Comment by stsp** [comment]
clang is not supported yet.
I added a patch to force the compilation failure.
However, if for you it still compiles (maybe newer
clang), then we'll re-open this.

**Comment by stsp** [comment]
From the log it almost looks as if
pthread_kill() invokes the wrong signal.
Which would be strange.

**Comment by stsp** [comment]
I re-added the clang support.
Please check if it is still the problem,
and if so - reopen.
