### ISSUE TITLE
Missing a proper interrupt 0 handler

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#580]
Refer to https://github.com/stsp/dosemu2/issues/577 or the following test case, running on 
dosemu2 2.0pre8-20180310-147-gce799391e, ie with https://github.com/stsp/dosemu2/commit/e817d8841a84a78f9e97b97d338b4e7ae8f8e8f4 (It correctly does not step across the div anymore.)

```
$ cat test.asm
cpu 8086
org 0

start:
	xor bx, bx
	div bx
	xor ax, ax
	int 16h
	int 19h
$ nasm test.asm -o KERNEL.SYS
$ dosemu -H1
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
```

```
$ dosdebug

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
Reading map file nm /usr/local/bin/dosemu.bin | grep -v '\(compiled\)\|\(\.o$\)\|\( a \)' | sort
7834 symbol(s) processed
highest address 00775b50(_end)
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
system state: emulated,stopped
AX=00c1  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=001b0202
CS:IP=f000:e05d       SS:SP=0000:fffe

f000:e05d B008             mov  al,08
t
system state: emulated,stopped

[...]

system state: emulated,stopped
AX=80fd  BX=0080  CX=0001  DX=0180  SI=07be  DI=7dfe  SP=7c00  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00083346
CS:IP=0060:0000       SS:SP=1fe0:7c00

0060:0000 31DB             xor  bx,bx

system state: emulated,stopped
AX=80fd  BX=0000  CX=0001  DX=0180  SI=07be  DI=7dfe  SP=7c00  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=000b3346
CS:IP=0060:0002       SS:SP=1fe0:7c00

0060:0002 F7F3             div  bx


must be in stopped state
stop
system state: emulated,stopped
AX=80fd  BX=0000  CX=0001  DX=0180  SI=07be  DI=7dfe  SP=7bfa  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00033246
CS:IP=f000:c002       SS:SP=1fe0:7bfa

f000:c002 F4               hlt
t
system state: emulated,stopped
AX=80fd  BX=0000  CX=0001  DX=0180  SI=07be  DI=7dfe  SP=7c00  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00083346
CS:IP=0060:0002       SS:SP=1fe0:7c00

0060:0002 F7F3             div  bx

stop
system state: emulated,stopped
AX=80fd  BX=0000  CX=0001  DX=0180  SI=07be  DI=7dfe  SP=7bfa  BP=07be
DS=0060  ES=0060  FS=0000  GS=0000  FL=00033246
CS:IP=f000:c002       SS:SP=1fe0:7bfa

f000:c002 F4               hlt
q
$ 
```

**Comment by stsp** [comment]
So what is the problem here?
What kind of a proper handler should
bios provide?

**Comment by ecm-pushbx** [comment]
It should display a message like "Divide by zero." and optionally dump register values, then optionally wait for a keypress, then either terminate dosemu, hang dosemu, or reboot. Currently, it hangs without any message (in the DOS window or terminal) or any other indicator as to why it hangs.

**Comment by stsp** [comment]
> It should display a message like "Divide by zero." and optionally dump register values

This is already done by DOS.
I don't know what default bios handler
should do. Perhaps the one needs to
look that up in seabios sources.

**Comment by stsp** [comment]
Looking at seabios sources, I can't
see any special vector for it but iret.
Let me know if this is wrong.

**Comment by ecm-pushbx** [comment]
You're right, my 686 PC also seems to behave that way (iret causing an infinite loop / hang). I still believe the BIOS *should* provide a better handler, but it seems that they often don't.

**Comment by stsp** [comment]
I don't see any possibility for bios to do this.
Firstly, bios have no way of terminating the
process that caused the problem. DOS has.
Secondly bios can't easily print something on
the screen as there may be non-text mode.
Thirdly, whatever bios provides, should be prepared
to being chained. For example if we provide the
handler that terminates dosemu, it is not unexpected
for DOS to call it after/before its own handler.
Definitely not what we want.
It might be possible for bios to set the NULL
handler though. This exactly means that it
should be handled by someone else and never
chained. But I think its too late (40 years too late)
to do that, as now this may cause some compatibility
problems.
