### ISSUE TITLE
Drives setup in config.sys don't persist (CDS isn't copied when resized and moved)

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#587]
I remarked a while ago that the CDS size and location could change after config.sys was processed. That's due to `lastdrive` value maybe being set in config.sys and potentially block devices being created via `device=`. I remembered that you'd asked for proof and now I think I have it. I noticed that `emufs.sys` appears to start the MFS redirection of my c: and d: drives, but they aren't used as MFS until after the redirection is redone at first int2f/ae00. This suggests to me that the CDS flags set in the first init are being ignored due to the CDS moving. I've provided logs (both full, and grepped) to show the CDS state after a hexdump patch is applied. The logs are from MS-DOS 6.22, so definitely not some old esoteric version. You should be able to see in the first CDS dump after redirection the flags are setup correctly, but at the start of the int2f/ae00 initiation they are no longer set. You'll also see that COMMAND.COM is read from fatfs, not mfs.
[cds_move_resize.zip](https://github.com/stsp/dosemu2/files/1822876/cds_move_resize.zip)

It's my assertion that emufs.sys should only install the interrupt handler and redirection should be initiated later (via some method other than int2f/ae00 it's later than ideal and is v3.3+ only). The only wrinkle I see with this is what happens if people want to do `install=c:\dosemu\lredir x: /path` in config.sys?

**Comment by stsp** [comment]
> I remembered that you'd asked for proof and now I think I have it.

No, I didn't, I myself know this happens.
I only asked for the list of all DOSes on which
this happens. Because if it happens with
freedos, we can fix it on freedos, for example.
But some DOSes are unfixable.

> It's my assertion that emufs.sys should only install the interrupt handler
> and redirection should be initiated later

That's why I want the list first.
If some major DOSes react correctly on this,
then I'd better leave the current behaviour
as is, and only think what to do with others.

> with this is what happens if people want to do install=c:\dosemu\lredir x: /path in config.sys?

Indeed.
So I don't see the problem in current code.
So far I don't know if it crashed some DOS
or whatever. But it is ineffective with some
DOSes, and I want to know the full list.

**Comment by andrewbird** [comment]
Set of DOS versions that have current MFS support AND version >= 3.30 so int2f/ae00 works.

~~~
Test DR-DOS-6.00-930319 CDS Propagate ... FAIL
Test DR-DOS-7.00 CDS Propagate ... FAIL
Test DR-DOS-7.01 CDS Propagate ... FAIL
Test DR-DOS-7.02-971119 CDS Propagate ... FAIL
Test DR-DOS-7.02-980123 CDS Propagate ... FAIL
Test DR-DOS-7.03 CDS Propagate ... FAIL
Test DR-DOS-8.00 CDS Propagate ... FAIL
Test FR-DOS-1.00 CDS Propagate ... FAIL
Test FR-DOS-1.10 CDS Propagate ... FAIL
Test FR-DOS-1.20 CDS Propagate ... FAIL
Test MS-DOS-3.30-Nec CDS Propagate ... FAIL
Test MS-DOS-3.30 CDS Propagate ... FAIL
Test MS-DOS-3.31 CDS Propagate ... FAIL
Test MS-DOS-4.01 CDS Propagate ... FAIL
Test MS-DOS-5.00 CDS Propagate ... FAIL
Test MS-DOS-6.00 CDS Propagate ... FAIL
Test MS-DOS-6.20 CDS Propagate ... FAIL
Test MS-DOS-6.21 CDS Propagate ... FAIL
Test MS-DOS-6.22 CDS Propagate ... FAIL
Test MS-DOS-7.00 CDS Propagate ... FAIL
Test MS-DOS-7.10 CDS Propagate ... FAIL
Test PC-DOS-3.30 CDS Propagate ... FAIL
Test PC-DOS-3.31-Compaq CDS Propagate ... FAIL
Test PC-DOS-4.00 CDS Propagate ... FAIL
Test PC-DOS-4.01 CDS Propagate ... FAIL
Test PC-DOS-5.00 CDS Propagate ... FAIL
Test PC-DOS-5.02 CDS Propagate ... FAIL
Test PC-DOS-6.10 CDS Propagate ... FAIL
Test PC-DOS-6.30 CDS Propagate ... FAIL
Test PC-DOS-7.00 CDS Propagate ... FAIL
Test PC-DOS-7.10 CDS Propagate ... FAIL
Test PC-DOS-7.2K CDS Propagate ... FAIL
~~~

CDS doesn't seem to get copied on any DOS I tested (checked for REMOTE flag on int2f/ae00 initiated init). So `emufs.sys` initialised redirect seems to be valid only for the life of config.sys processing.

**Comment by stsp** [comment]
Unbelievable. :)
@bartoldeman could you please give us a hint
why this happens on freedos and everywhere
else?

**Comment by stsp** [comment]
> So emufs.sys initialised redirect seems to be valid only for the life of config.sys processing.

Which is IMHO still good, but not enough...

**Comment by stsp** [comment]
> So emufs.sys initialised redirect seems to be valid only for the life of config.sys processing.

So if I remove that for config.sys why do
you think it would be any better? IMHO this
does the trick for config.sys at least, and
ae00 does the rest, so for now the problem
almost does not exist in practice. But remove
the trick for config.sys, and it becomes worse?

**Comment by stsp** [comment]
Andrew, so what do you think about just
adding a new option to lredir2 that will call
`DOS_SUBHELPER_EMUFS_REDIRECT`,
and add that to the beginning of autoexec.bat?
This will solve the <3.3 problem, and the
rest is already covered with ae00.
Yes, it looks like fighting the symptoms rather
than curing the disease, but when disease is
incurable...

**Comment by stsp** [comment]
And yes, if/when we can use fdpp, there
will be another fix. But not yet.

**Comment by andrewbird** [comment]
I'm currently looking for another solution other than `int2f/ae00` as it's very late. In the msdos 6.22 log I posted above you can see that MFS doesn't start being used for file access until command.com is loaded and autoexec.bat is being processed. Even in the normal case using your new lredir2 suggestion would be better for all DOS versions, not just < 3.30

**Comment by stsp** [comment]
> Even in the normal case using your new lredir2 suggestion would be better

I don't actually see why: I think ae00 happens
earlier than anything loaded from autoexec.bat.
So I really don't see how to improve the "too late"
situation, but at the same time does it hurt much?
I suspect those large file problems can resurface
though.

**Comment by stsp** [comment]
So it you'd like to make the lredir2 patch, that
would be excellent! I don't think it will fix the
"too late" problem, but it will definitely fix the
<3.3 problem, which is good. We'll think up
other hacks to plumb whatever remains. :)

**Comment by andrewbird** [comment]
If I can't think of a better solution than running lredir2 from autoexec, I can make the patch for it.

In the meantime whilst I'm looking for alternatives, are you totally opposed to hooking into the INT21 open() of command.com, as I could I could either make the name configurable or have a list of candidate filenames to cope with oddities like 4DOS?

**Comment by stsp** [comment]
What will that change?
ae00 is called upon the first (and any subsequent)
command by command.com, so the difference will
be only for the command.com itself. Do you think
this matters? IMHO there are a few downsides and
almost no improvement.

**Comment by stsp** [comment]
Or do you mean for completely avoiding the lredir2
change by this?

**Comment by andrewbird** [comment]
Yes to avoid lredir change, avoid the need for a different solution for < v3.30 DOS and at least be sure that command.com and autoexec.bat are run from r/w mfs drive not r/o fatfs.

**Comment by stsp** [comment]
> Yes to avoid lredir change, avoid the need for a different solution for < v3.30 DOS

I view the lredir2-based solution as generic.
In this case ae00 should work only as a
fall-back. Which it is currently not, as it triggers
earlier. So my idea was to change lredir2 first,
then think how to turn post_boot() into a fall-back,
but your intention is reversed.
Not sure.
I guess we need to clearly outline the implementation
details that we have in mind (so far I don't know
how to turn post-boot into a fallback of lredir2, but
I'll look for a way) and then decide what looks better.

**Comment by stsp** [comment]
> and at least be sure that command.com and autoexec.bat are run from r/w mfs drive not r/o fatfs.

But are you sure ae00 does not cover autoexec.bat case?

**Comment by andrewbird** [comment]
in my msdos 622 egrep log you can see `int2f/ae00` occurs at line 184, but fatfs read of autoexec.bat occurred at line 171. Something similar would occur if lredir initiated redirection, hence I'm looking at my pc/dr/msdos logs for an alternative. Perhaps I hope too much that a better solution was overlooked by whomever implemented the ae00 solution :-)

**Comment by stsp** [comment]
Yes, this is indeed annoying.
Whoever implemented ae00 solution (me?), at least
didn't know that command.com doesn't call ae00 when
opening autoexec. Could you please verify if it is the
case with freecom too?
However, IIRC command.com does not keep autoexec.bat
open. IIRC it should close it after every command, then
open again and seek to the remembered pos. Could you
please check if this is the case? If so, then again, the
problem with autoexec.bat almost doesn't exist as it
will be immediately reopened from redirected drive.

**Comment by andrewbird** [comment]
> Whoever implemented ae00 solution (me?)

I don't know whom, and it's fine idea, as I've yet to come up with a better one!

I'll try freecom.

**Comment by stsp** [comment]
The more interesting is to check the
autoexec.bat close/reopen behaviour.
Because in this case if would still be
taken from the redirected drive.

**Comment by andrewbird** [comment]
PC-DOS 3.00 seems to open autoexec.bat 6 times
DR-DOS 5.00 seems to open it 3 times
MS-DOS 6.22 seems to open it 6 times ( 2 times as fatfs, 4 as mfs )

What about triggering mfs initialisation from `int21/4b` as we already intercept it and it's earlier than now? Of course we'd still need to match on command.com filename.

**Comment by stsp** [comment]
So if autoexec ends up being opened from mfs
anyway, why to care about a command.com hack?
Also `SHELL` can be set to anything, even to `win.com`
I suppose.

**Comment by andrewbird** [comment]
Are you sure `int2f/ae00` gets called when using another command processor as isn't it there to extend command.com? What does this 'int2f/ae00' call, isn't it command.com itself [(rbil)](http://www.ctyme.com/intr/rb-5189.htm)? I'm not sure why testing mfs init on program start is considered a hack whereas performing the same before every command is not.

**Comment by stsp** [comment]
> whereas performing the same before every command is not.

Its also a hack of course.
That's why I think it would be better to move
to lredir2 trick globally, leaving ae00-alike hack
(but not ae00 itself) only as a fall-back.
The only reason I prefer the ae00 hack over
command.com's name comparison is because
it is universal across command.coms, but I don't
like it to control the redirection forever.

**Comment by stsp** [comment]
So your solution may be slightly better
in some cases and has an obvious disadvantage
of comparing the command.com and clones
file names. We may or may not replace one
hack with another, but why not to think about
something that is _much_ better? It would be
excellent to have a hack that will allow lredir2
to go first. Or maybe with lredir2 we won't need
any hack at all?

**Comment by stsp** [comment]
By the way, could you please check if
`INSTALL` in config.sys also works before
the CDS is recreated?

**Comment by stsp** [comment]
So its not like I want to force ae00 technique -
quite the opposite. But lets discuss more than
one alternative. For example if `INSTALL` works
on a new cds array - problem solved.

**Comment by andrewbird** [comment]
It seems that `INSTALL` is DOS 4+, so not ideal from my perspective. Anyway I tested on DOS 5 (with redir_it call commented out) by adding `install=dosemu\lredir2.com e: /tmp` to my config.sys.

DOS did complain about error on line 3 which was the install line, but the screen messages seemed to indicate success. I wonder if you have lredir2 returning non zero as it warns about deprecation?
I don't understand why but it did persist all through boot, such that I could `dir e:` on the command line and see my /tmp directory.

Mmm what now?

**Comment by stsp** [comment]
> I wonder if you have lredir2 returning non zero as it warns about deprecation?

No, I don't do that.
Please fill a bug (would be bettr to see if it
is a problem outside of a config.sys too).

> I don't understand why but it did persist all through boot

Isn't that because `INSTALL` works after the cds copy?

> Mmm what now?

Add a new option to `lredir2` and put it into `fdconfig.sys`?

**Comment by andrewbird** [comment]
I will have to check but I think it works because it uses the cds supplied in the int2f/11 call not that obtained by lol. I think it might be time to look at avoiding lol cds array.

**Comment by stsp** [comment]
Yes, would be very interesting to find
out the details. Though I wouldn't bet
on your theory that there are 2 cds
arrays at the same time.

**Comment by andrewbird** [comment]
But for sure emufs.sys gets CDs array from lol and passes it to 32bit code. The changes we make there don't propagate back to the final CDs array.

**Comment by stsp** [comment]
I would bet on a classic view that DOS just
recreates the CDS array, but `INSTALL` works
later. Lets see. :)

**Comment by andrewbird** [comment]
I have the beginnings of an idea that I could use int2f/1217 from emufs.sys initiated code to get the CDs to work on. Leave it with me...

**Comment by bartoldeman** [comment]
The FreeDOS kernel essentially regards the filesystem during most of config.sys processing (everything in there *before* INSTALL and SHELL are executed) as temporary. It then completely reinitializes everything, including setting up stdin, stdout, etc. I never considered copying the temp into the final fs.

if you look at all the non-dosemu redirectors out there you see they are all .exe's (mscdex.exe, msnet, etc), and not .sys files, so they aren't really designed to be loaded as .sys drivers.

now dosemu used to redirect on the first open (int21/ah=3d), which plays well with freedos which uses open("config.sys") via int21 early on (not an accident that!). Other DOSes may not do that and use internal calls to open config.sys etc.

I am not sure about dos_post_boot either... indeed int2f/ae00 is not guaranteed... There is also int21/ax=4b00 (exec) and int2f/ax=1123 (remote qualify filename, used by every DOS fs call, even on non-redirected drives). I think from a programmer's point of view the cleanest is to only have lredir or lredir2, and get rid of emufs and autoredirect, it's not the most user-friendly though and means that everything until install=lredir.exe or lredir in autoexec.bat needs to be in fatfs, whereas with the old way at least with freedos basically nothing was needed in fatfs, just something that made DOS think it was booting from a hard drive.

**Comment by stsp** [comment]
Yes, this is basically what I was expecting.
Thanks for info.
My idea is to have both emufs and install=lredir2.
If nothing else, emufs will allow config.sys to be
processed on a redirected drive. But it also enables
revectoring of int21 and int2f these days. Then it
doesn't matter that ae00 is not guaranteed: its just
a fall-back. No autoredirect by default.
Also this way you have nothing from fatfs:
everything is still from the redirector.
So I really think the best scheme is to
have both redirectors in config.sys and
ae00 as a fall-back.

Thoughts?

**Comment by stsp** [comment]
> everything until install=lredir.exe or lredir in autoexec.bat needs to be in fatfs

Note that putting lredir in autoexec have
disadvantages. The obvious one is that
then you get command.com and autoexec
from fatfs. And the non-obvious disadvantage
is that you'll have troubles making a fall-back.
For example there would be no room for ae00:
it works earlier, so it should either be removed
or lredir in autoexec is useless.
But `install=lredir2` is IMHO a break-through of
the day. It allows everything (including command.com
and autoexec, and config.sys too if emufs is used)
from mfs, and it allows a fall-back in the form of ae00.

**Comment by stsp** [comment]
I think we need to implement `emufs.com`
that will (try to) open the `EMUFS$  ` device
and do the init ioctl on it. Then put it into
`fdconfig.sys` under `install=`.

**Comment by andrewbird** [comment]
Interesting idea `install emufs.sys` and `emufs.com`, but what happens in that case that `emufs.sys` cannot be installed on pre v4 DOS due to lack of `install` keyword?

**Comment by stsp** [comment]
See int.c:
```
            /* for old DOSes without INSTALL= support, we need this */
            if (config.force_redir && !redir_state &&
                    strcasestr(cmd, "\\command.com")) {
                ds_printf("INT21: open of command processor triggering post_boot
\n");
                if (do_redirect(1))
                    redir_state++;
```

Plus ae00 will happen too.
Don't worry, no one is stealing your old DOSes. :)

**Comment by andrewbird** [comment]
:smile:

**Comment by stsp** [comment]
As the remaining redirector problems are
being dealt with, I am started to really think
about maybe to release something.
@skitt How goes your djgpp packaging effort?
Will you also create the PPA for that?
