### ISSUE TITLE
EDR-DOS: invalid opcode if emufs.sys loaded + lredir in iNSTALL=

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#588]
[edrdos-invalid-opcode-emufs.zip](https://github.com/stsp/dosemu2/files/1844334/edrdos-invalid-opcode-emufs.zip) has DRBIO.SYS, DRDOS.SYS, DCOMMAND.COM, from https://web.archive.org/web/20160326184121/http://www.drdosprojects.de/index.cgi/download.htm "Enhanced DR-DOS 7.01.08 WIP binaries" dconfig.sys, autoexec.bat, and KERNEL.SYS -- the latter is a renamed lDebug bootable debugger, https://bitbucket.org/ecm/ldebug/commits/d882d1e7e76a7e19057bc7ad4a6230252d812db4

dconfig.sys:
```
DEVICE=c:\dosemu\emufs.sys
INSTALL=c:\dosemu\lredir.com z: linux\fs\${DOSEMU_LIB_DIR}/drive_z ro
SHELL=c:\dcommand.com C:\DCOMMAND.COM /E:1024 /P:AUTOEXEC.BAT
```

command entered and output:

```
-boot protocol edrdos ldp
In bootcmd
In bootcmd.proto_settings
In parseloadunit.load_ld
In parseloadunit.load_ld with ldp
In bootcmd.fn_done
-g
 
The DR-DOS/OpenDOS Enhancement Project              http://www.drdosprojects.de
 
Starting Enhanced DR-DOS 7.01.08 WIP (21.7.2011)
 
Supported version of int 13 extensions: EDD-3.0
EMUFS host file and print access available
Z: = \\LINUX\FS\${DOSEMU_LIB_DIR}/DRIVE_Z attrib = READ/WRITE
Invalid opcode
AX=5380 BX=E0DC CX=0000 DX=0000 SP=FFF8 BP=0100 SI=0000 DI=0000
DS=0D69 ES=0070 SS=0D69 CS=0D69 IP=001E OV UP EI NG NZ NA PO NC
0D69:001E FF                db      FF
-
```

**Comment by stsp** [comment]
So does it work properly w/o emufs.sys?

**Comment by ecm-pushbx** [comment]
Refer to https://github.com/stsp/dosemu2/issues/589 for an issue even without emufs.sys

**Comment by stsp** [comment]
Do you have `LASTDRIVE` properly set?
Does this work with smaller drives than Z?

**Comment by andrewbird** [comment]
So I did a little tracking down on this.
- 7.01.06 - works okay
- 7.01.07 - broken, starts processing further config.sys commands from MFS after loading emufs.sys, but then suddenly it can't find filenames in sda.
- 7.01.08wip - broken, much as per above

Anyway a little digging later indicates that 7.01.07 added moving of LASTDRIVE into HMA or UMB. I think SDA and LOL are moving as a part of this. I tried asking DOS for the SDA location in each call to the redirector, and that allowed me to reach the end of config.sys processing. Then to get further I needed to get LOL updated as well but that MSDOS call didn't play well inside the redirector, 

I don't think there's much mileage in fixing this as there's only two versions that don't work, one release and a work in progress that will never be finished.

**Comment by stsp** [comment]
If we are to get rid of LoL lookups, then why
to bother now? Maybe it will work better then.

**Comment by stsp** [comment]
Andrew, what do you think about rehashing
an sda pointer once, somewhere in
post_boot? Or is it a more difficult problem?
Should we close it with some doc update?

**Comment by andrewbird** [comment]
It seems that the DOS Data segment is changing, which affects both LOL and SDA. I can use int2f/1203 to get it in the redirector which fixes the problem under 7.01.07, but I'll need to change the way the lol and sda pointers are passed to the redirector.

**Comment by stsp** [comment]
But it shouldnt be changing always, right?
Thats why I propose a minimal change:
boot with fatfs  and update the pointers
after boot to switch on redirector.
We can likely avoid lol usage.

**Comment by andrewbird** [comment]
Looking at RBIL I'm not sure int2f/1203 can ever fail, so it could be smaller if I remove the error check and change the function to return the value.

I agree from what I've seen on EDR-DOS 7.01.07 I don't think it will change more than once. I think we get back to needing to know for certain that DOS has booted fully. Then we could say
```C
if (!DosBooted) { // update the pointers as they may still be moving
  dosdataseg = GetDataSegmentInDOS();
  lol = SEGOFF2LINEAR(dosdataseg, lol_offset);
  sda = MK_FP32(dosdataseg, sda_offset);
}
```

I think booting with fatfs would be fine providing nothing loaded in config.sys needs to write to disk. But I'm sure you know that I'm going to ask that at the point autoexec.bat is processed it should be using MFS and be R/W.

**Comment by stsp** [comment]
So you seem to have already found
the minimal change that works properly?
https://github.com/stsp/dosemu2/pull/705/commits/391f11fa3c0ec1e3ba842060d5e8e20861c3861d
In that case we don't need to involve
post_boot.

**Comment by andrewbird** [comment]
Yes, I'm just tweaking re your feedback and retesting now. If later you switch to the fatfs R/O boot we can review if it's still needed, or at least just update the pointers once.

**Comment by stsp** [comment]
> If later you switch to the fatfs R/O boot

It will happen with comcom32 for some time,
but I don't see a need to change any code.
I want an r/w boot, and will eventually implement
`INSTALL=emufs.com`, ae00 in comcom32 and
everything else to get the r/w boot back.
Its just that both dosemu2 and myself are
having hard times (dosemu2 changes DOS and
me changing flat), but this doesn't mean I
want r/o boot. It just happens in the course
of those transitions.

**Comment by stsp** [comment]
I think this is fixed.

**Comment by ecm-pushbx** [comment]
Had to add "LASTDRIVE=Z" to DCONFIG.SYS, and link emufs.sys and lredir.com from dosemu2-cmds-0.2 to the drive C:'s directory dosemu. Also added a link from /usr/local/share/dosemu/drive_z/dosemu to ../dosemu2-cmds-0.2/dosemu/

```
~/.dosemu/drives/c$ ls -lgG -R
.:
total 772
-rw-r--r-- 1     0 Oct  4 15:53 '4)'
-rw-r--r-- 1   589 Nov 24 12:39  autoexec.bat
-rw-r--r-- 1 94771 Dec 10  2003  CMD.HTM
lrwxrwxrwx 1    43 Aug  7 12:15  command.com -> /usr/local/share/dosemu/freedos/command.com
-rw-r--r-- 1 93266 Aug 14 18:43  COMMANDG.COM
-rw-r--r-- 1 91086 Aug 14 14:02  COMMANDT.COM
-rw-r--r-- 1 85416 Aug 14 13:42  COMMANDW.COM
-rw-r--r-- 1 64641 Mar 24  2018  DCOMMAND.COM
-rw-r--r-- 1   177 Nov 24 12:39  dconfig.sys
drwxr-xr-x 2  4096 Nov 24 12:42  dosemu
-rw-r--r-- 1 35556 Jul 21  2011  DRBIO.SYS
-rw-r--r-- 1 36597 Jul 21  2011  DRDOS.SYS
lrwxrwxrwx 1    53 Aug  7 12:15  fdconfig.sys -> /usr/local/share/dosemu/dosemu2-cmds-0.1/fdconfig.sys
-rw-r--r-- 1 31257 Dec 24  2017  FREECOM.HTM
-rw-r--r-- 1  5008 Sep 21 21:27  instfd32.com
-rw-r--r-- 1  5984 Sep 21 21:27  instsect.com
-rw-r--r-- 1  5008 Sep 21 13:51  instsefd.com
-rw-r--r-- 1  5038 Apr 12  2018  jn_warn.mac
-rw-r--r-- 1 56832 Mar 24  2018  KERNEL.SYS
-rw-r--r-- 1 18323 Dec 24  2017  LICENSE.TXT
-rw-r--r-- 1 26598 Apr 24  2018  lmacros1.mac
-rw-r--r-- 1 22421 May 24  2018  lmacros2.mac
-rw-r--r-- 1 12585 Jun  9 14:10  lstruct.mac
-rw-r--r-- 1  1754 Aug 16 02:43  README.TXT
-rw-r--r-- 1   596 Apr 12  2018  test.asm
-rwxr-xr-x 1    81 Apr 12  2018  test.cmd
-rw-r--r-- 1   568 Aug 21 16:20  testoom2.asm
-rw-r--r-- 1   547 Aug 21 16:21  testoom2.exe
-rw-r--r-- 1  2000 Aug 21 16:21  testoom2.lst
-rw-r--r-- 1   554 Aug 21 16:16  testoom.asm
-rw-r--r-- 1   547 Aug 21 16:19  testoom.exe
-rw-r--r-- 1  1906 Aug 21 16:19  testoom.lst
-rw-r--r-- 1   667 May 24  2018  testpar.asm
-rw-r--r-- 1   238 Apr 14  2018  testsat.asm
-rwxr-xr-x 1    90 Apr 12  2018  test.sh
drwxr-xr-x 2  4096 Oct  4 15:53  tmp

./dosemu:
total 0
lrwxrwxrwx 1 57 Nov 24 12:42 emufs.sys -> /usr/local/share/dosemu/dosemu2-cmds-0.2/dosemu/emufs.sys
lrwxrwxrwx 1 58 Nov 24 12:42 lredir.com -> /usr/local/share/dosemu/dosemu2-cmds-0.2/dosemu/lredir.com

./tmp:
total 0
~/.dosemu/drives/c$ ls -lgG /usr/local/share/dosemu/drive_z/
total 328
drwxr-xr-x  2  4096 Nov 18  2006 appinfo
-rw-rw-r--  1   535 Nov 13  2006 autoexec.bat
drwxr-xr-x  2  4096 Nov 24 12:12 bin
-rw-r--r--  1 66945 Aug 29  2006 command.com
-rw-rw-r--  1   350 Nov 13  2006 config.sys
drwxr-xr-x  2  4096 Aug 29  2006 cpi
drwxr-xr-x 36  4096 Nov 18  2006 doc
lrwxrwxrwx  1    27 Nov 24 12:37 dosemu -> ../dosemu2-cmds-0.2/dosemu/
drwxr-xr-x  2  4096 Sep 19  2003 gnu
drwxr-xr-x  2  4096 Nov 18  2006 help
-rw-r--r--  1 79880 Sep 22  2017 kernel.sys
-rw-r--r--  1 45341 Aug 18  2006 kernel.sys.2036.old
-rw-r--r--  1 79880 Sep 22  2017 kernel.sys.2042.old
drwxr-xr-x  2  4096 Nov 18  2006 nls
lrwxrwxrwx  1     4 Nov 24 12:12 tmp -> /tmp
-rw-r--r--  1 15373 Aug 25  2005 WDe.com
~/.dosemu/drives/c$ cat dconfig.sys 
LASTDRIVE=Z
DEVICE=c:\dosemu\emufs.sys
INSTALL=c:\dosemu\lredir.com z: linux\fs\${DOSEMU_LIB_DIR}/drive_z ro
SHELL=c:\dcommand.com C:\DCOMMAND.COM /E:1024 /P:AUTOEXEC.BAT

~/.dosemu/drives/c$ cat autoexec.bat 
@echo off
rem autoexec.bat for DOSEMU + FreeDOS
path c:\bin;c:\gnu;z:\dosemu
set HELPPATH=c:\help
set TEMP=c:\tmp
set FFD_CHECKEXTRA=OFF
blaster
prompt $P$G
system -s DOSDRIVE_D
if "%DOSDRIVE_D%" == "" goto nodrived
lredir del d: > nul
lredir d: linux\fs%DOSDRIVE_D%
:nodrived
rem uncomment to load another bitmap font
rem loadhi display con=(vga,437,2)
rem mode con codepage prepare=((850) z:\cpi\ega.cpx)
rem mode con codepage select 850
rem chcp 850
:: lredir e: linux\fs/media/cdrom c
system -s DOSEMU_VERSION
echo "Welcome to dosemu %DOSEMU_VERSION%!"
system -e
~/.dosemu/drives/c$ 
```

This boots properly, finding both DCONFIG.SYS and AUTOEXEC.BAT, and all dosemu commands:

```
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
 
 
The DR-DOS/OpenDOS Enhancement Project              http://www.drdosprojects.de
 
Starting Enhanced DR-DOS 7.01.08 WIP (21.7.2011)
 
Supported version of int 13 extensions: EDD-3.0
EMUFS host file and print access available
Z: = \\LINUX\FS\${DOSEMU_LIB_DIR}/DRIVE_Z attrib = READ/WRITE
Invalid COMMAND search directory specified
 
 
Enhanced DR-DOS 7.01.08 WIP (21.7.2011) based on Caldera OpenDOS 7.01
Copyright (c) 1976, 1997 Caldera, Inc. All rights reserved.
Patches to original OpenDOS source code Copyright (c) 2002-2011 Udo Kuhnt
 
LICENSED FOR NON-COMMERCIAL USE ONLY
 
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
"Welcome to dosemu 2.0pre8-20181120-656-g03d08f8ea!"
C:\>
```

The only remaining issue is that it still says "Invalid COMMAND search directory specified".
