### ISSUE TITLE
Asm/vm86.h has changed structure field types, but those structs are used in system call

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#59]
I'm looking into whether dosemu can be built with the standard system headers instead of the local copies. I came across this commit 6bd1a2f468a023ef4745ac123ab6b51eae7ef556 which changes some types. Now I notice in Asm/vm86.h that the vm86plus_struct and other have field types changed from unsigned long to unsigned int. Isn't a pointer to that struct used in the vm86() system call on 32 bit machines? How can the kernel deal properly with the size change?
http://man7.org/linux/man-pages/man2/vm86.2.html
http://lxr.free-electrons.com/source/arch/x86/include/uapi/asm/vm86.h

Am I wrong to be concerned?

**Comment by stsp** [comment]
Good finding.
Indeed it is used for a syscall on 32bit machines,
but then on 32bit machines nothing have changed,
because AFAIK long on 32bit machines is 32 bit.
It changed only for 64bit machines, where no such
syscall exist.

I can think of 2 possible fixes:
1. For 64bit build define that struct in a different header.
2. Use explicit types in that struct, like uint32_t
perhaps (have to see the kvm headers for better
example), and bring the problem to the attention
of the kernel developers by posting a patch to them.

We can as well do both of the above.

**Comment by stsp** [comment]
Hmm, how about the following:
add ifdef to our vm86.h: for i386 it will
include the system header, but for x86_64 -
its current content will be used.
A very simple fix IMHO, just rename it to
something like vm86_wrp.h to avoid confusion.

**Comment by andrewbird** [comment]
I hadn't checked the actual sizes of the int vs long on 32 bit, until your comment. But yes they are the same, so my immediate panic is over. Yes, I like the ifdef fix, but I also found there were missing constants etc in the system header, so I think it's not just a simple task to swap the headers too. I'll experiment for a while, but I may just find something else to do. Sorry about the noise :-)

**Comment by stsp** [comment]
If there are missing constants in system header,
then someone have mistakenly added the unrelated
stuff to dosemu's copy. Not the best thing to do at
all. If not you - I'll sort out the mess myself.

**Comment by andrewbird** [comment]
I'm not aiming to cause you extra work. I'll persevere.

**Comment by stsp** [comment]
I mean if you don't do that, I'll have to myself.

**Comment by andrewbird** [comment]
Oh yes, I I know. I just feel a little guilty for finding things to fix that aren't causing any known bug :-)

**Comment by andrewbird** [comment]
I see you started a new branch. Did you see the TF_MASK / IF_MASK etc are missing from uapi. I'm not sure if they were ever there or in the kernel version, or got added locally.

**Comment by stsp** [comment]
Should now be fixed.
Yes, difficult to test on 2 arches...

**Comment by andrewbird** [comment]
I'm glad you fixed this, as it's so much better than if I did it. Thanks again.
