### ISSUE TITLE
Accessing USB floppy drive

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#594]
Hey,

I have an USB floppy drive which lists as /dev/sdb. I can mount it, e.g. in /mnt/sdb. How can I use the device in dosemu? Obviously I can specify the mount directory to get a read-only virtual floppy or use lredir2 but either works after I change the floppy.

I tried
`$_floppy_a = "threeinch:/dev/sdb"`
which results in
`Error reading from drive A: DOS area: sector not found`
boot.log also shows:
`CONF: **** Warning: floppy /dev/sdb not accessible, disabled`
hinting at some missing rights.
So I tried running as root. In boot.log:
`device: /dev/sdb type 2 h: 0  s: 0   t: 0 floppy A:`
when accessing it, dosemu crashes with:
`ERROR: can't get floppy parameter of /dev/sdb (Invalid argument)
`

I guess the problem is the device not being connected via FDD port but modern mainboards don't have them so I need to use USB drives...
This is tested on ubuntu 16.04 64bit with dosemu-pre6. If you need me to update to devel because of "recent" changes just tell me.

**Comment by stsp** [comment]
> lredir2 but either works after I change the floppy.

I can't parse this.
So you've found the way to get read-only virtual
floppy and r/w lredir. Can't see any problem here.

**Comment by skitt** [comment]
>> lredir2 but either works after I change the floppy.
> 
> I can't parse this.
> So you've found the way to get read-only virtual
> floppy and r/w lredir. Can't see any problem here.

I’m guessing there’s a missing ‘n’, as in

> neither works after I change the floppy

Mounting or lredir2 mean the current floppy can be accessed, but 
changing doesn’t work. But DOSEMU can’t directly control a USB floppy 
drive like it can control an FDC-connected floppy drive...

**Comment by haenschen** [comment]
Sorry, this was meant to read neither.
If I use lredir2 I get a r/w drive but after changing floppy it wont update in dosemu until I open the drive in Ubuntu although the mount option is set to auto...

**Comment by haenschen** [comment]
> Mounting or lredir2 mean the current floppy can be accessed, but changing doesn’t work. But DOSEMU can’t directly control a USB floppy drive like it can control an FDC-connected floppy drive...

Exactly... Hmm yeah as I expected. So I guess my only option is to lredir2 to A: and try and get the mounting in Ubuntu right.

**Comment by stsp** [comment]
> But DOSEMU can’t directly control a USB floppy

I think this can be implemented for USB too, but
this may be a bit unreasonable, as in the general
case usb drive doesn't match the floppy geometry,
so DOS won't treat it as such.
But as for the read-only virtual floppy on top of the
mounted directories - changing should work.
So am I right that the bug here is that changing
doesn't work even with a virtual read-only floppy?

**Comment by stsp** [comment]
> If I use lredir2 I get a r/w drive but after changing floppy it wont update in
> dosemu until I open the drive in Ubuntu although the mount option is set to auto...

In theory I don't see any reason why this shouldn't
work, either. If dosemu2 keeps some fds opened on
a mounted drive, then it should just stop doing so.
You should be able to see the new content.
I think both problems (lredir2 and vfloppy) needs
to be investigated to find out what exactly prevents
the content change from happening.

**Comment by stsp** [comment]
Can you bypass your problem with virtual
read-only floppy instead?

**Comment by stsp** [comment]
No. silly question, it will fail for the same reason then. :)

**Comment by haenschen** [comment]
Apparently this isn‘t possible.
https://askubuntu.com/questions/1028454/automount-when-changing-usb-floppy#_=_
Thanks anyways!

**Comment by stsp** [comment]
OK, I finally realized you have a real
usb floppy drive, rather than the USB flash
formatted as floppy - this is what I thought
you have.
There are tricks I can recall from 20 years
old experience. What I did back then is set
a mount timeout. When no one accesses
the mount point for a few seconds, it unmounts.
When you access the mount point, it mounts
again. I don't remember what software I used
for that, but it worked.

**Comment by haenschen** [comment]
A very good advice as usual! :)
autofs (https://help.ubuntu.com/community/Autofs) comes with such a feature, I was able to configure it as needed. At the moment it only mounts my floppy as read-only but I am trying to work out the necessary mount options.
For now I can switch floppys in dosemu using lredir to the mount point specified in autofs.
