### ISSUE TITLE
UPPERCASE vs lowercase

### ISSUE THREAD

**Issue by ccarcel** [stsp/dosemu2#599]
Is there any way to force the emulator to make the files that are created in DOS to be saved as UPPERCASE in Linux. MS-DOS 6.22 defaults to UPPERCASE but when a file is created it is in lowercase on Linux.

I don't know about other versions of DOS but in our situation we copy from a DOS system that is in UPPERCASE and then we end up with two sets of the same file in the directory.

Thanks.

**Comment by stsp** [comment]
dosemu keeps the existing file names,
whether they are upper or lower case.
The rest should hardly matter.
So if you "copy from a DOS system that is in UPPERCASE"
under dosemu, then the duplicates should
not happen.
If you insist on "create under dosemu, copy
under linux" scenario, will this help?
http://www.brain-dump.org/projects/ciopfs/

**Comment by bartoldeman** [comment]
What tool do you use to "copy from a DOS system that is in UPPERCASE"? mtools, mounting fatfs via Linux kernel, unzipping an archive, something else?

Linux shows SFNs (short file names) in lower case by default on mounted FAT file systems, so that is where dosemu's behaviour comes from.

**Comment by ccarcel** [comment]
HI, we move stuff in Linux from one to the other so any new files created are in lower case. I was thinking about running the emulator mounts on vfat, with this solve my issue. As the 

CIOPFS is not really a good idea for us.

 

Thanks

**Comment by bartoldeman** [comment]
vfat will probably work. dosemu even has special hooks into lredir'ed vfat drives so it can access the original short and long filenames and DOS file attributes, as this was a common scenario.

**Comment by stsp** [comment]
I've just found this comment of my own:
https://github.com/roelandjansen/pcmos386v501/pull/22/commits/3ef932cafb95f8ac69b87daebf46ee12ae01210f#diff-dfa405e378e8ccb7325d596304daf10aR11

So it seems like dosemu can actually create the
collisions itself? In this case I'd treat this as a bug.

**Comment by ccarcel** [comment]
HI,

 

My issue is not about *.SYS files, it’s purely that we take files from an old Novell / Dos environment and all files are in uppercase if any new files are added / created on the dosemu system they end up in lowercase, this makes wired issues when trying to compile dbase for example as it creates DBO files on the fly.

 

I have not had time to create a partition with FAT32 yet to see how the emulator would behave , but it really would be a nice to have from my point if there was a config setting that forced all to be in uppercase.

 

Thank you for your time on this issue.

 

Regards,

 

Claude

**Comment by stsp** [comment]
> files are in uppercase if any new files are added / created on the dosemu system

By dosemu itself, or under linux?
If dosemu itself creates the collision (and from
my older comment it seems like it actually does!),
then its definitely something to fix.
But if you create the name collisions behind
dosemu's back, that's a different story.

> if there was a config setting that forced all to be in uppercase.

Why ciopfs is not what you want?
It seems it does exactly that, w/o involving fat32?

**Comment by ccarcel** [comment]
I have tried to simulate and it seems like your correct if the file is there weather it in upper or lower (only 1) then the emulator will overwrite the file in the case it is in.

 

There is an instance where this is not the case, I will look into it more, I know what your saying about Linux etc. we are now avoiding using any Linux tools to zip and move files, and stick to PKZIP in Dos, but I am sure there is an issue, it may be down to dbase doing something low level that the emulator does not interpret correctly (I have no idea).

 

What I do know is that we start with all in UPPERCASE and then the emulator any directory or file that is created is always in lower if it did not exist, or there maybe a cache issue when dBase compiles it may delete the dbo file before creating them again. And then thinks the file is already there on occasions. 

 

I could not get the ciopfs working on my Ubuntu 18.04 test system to try, I don’t really want to have another overhead on the server either as we do polling that kills the CPU on the vm’s. Novell 6.5 is case sensitive so if we create in windows the files are in lower but anything done on real dos work stations and dBase etc. is always only in upper.

 

Regards

**Comment by stsp** [comment]
> There is an instance where this is not the case, I will look into it more

Thanks, I think this is a bug then.
I'll also dig up my older pcmos test-case
and see why I was getting the collisions.
Lets just have the problems separated, if
we have more than one problem, the separate
ticket should be opened. So if you see the
problem with getting the collisions under
dosemu2, please open a ticket for it.

> What I do know is that we start with all in UPPERCASE and then the emulator any directory or file that
> is created is always in lower if it did not exist, or there maybe a cache issue when dBase compiles it
> may delete the dbo file before creating them again. And then thinks the file is already there on
> occasions.

I am not sure if you refer to another bug or to
the same one. If your prog removes and re-creates
the file, it may end up in a lower case indeed.
Or do you see something else?

**Comment by ccarcel** [comment]
Sorry, I am not being clear,

 

I think the problems are related to the way the file system is handled, if it is a new copy it always works first time. I will jump on this in the morning and try and simulate with screen shots to give you a clear picture.

 

It may be two issue but they both appear together.

 

Regards,

**Comment by stsp** [comment]
> we are now avoiding using any Linux tools to zip and move files, and stick to PKZIP in Dos

What about writing a simple bash script
for a case-insensitive copy under linux?
That script can check the destination files
and preserve their case, or use the source's
case if no dest file.

**Comment by jschwartzenberg** [comment]
I think I switched to using `7z` from `unzip` for my scripts so I could easily extract everything with lowercase filenames.

**Comment by stsp** [comment]
So I think we can't do anything about this
on dosemu2 side.
