### ISSUE TITLE
Asm/ldt.h has changed structure field type, but those structs are used in system call

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#60]
This a similar problem to the earlier one, but with an ldt.h structure. It seems that since kernel 2.6.24 commit (torvalds/linux@f6a2e7f2012eeced1dbf093bb98a1c38fee91f78) that structure has its base_addr field typed as per the local copy we have.

Prior to that commit the structure was different between i386 and x86_64
~~~
$ diff -u include/asm-i386/ldt.h include/asm-x86_64/ldt.h
--- include/asm-i386/ldt.h	2015-08-19 17:12:22.022978491 +0100
+++ include/asm-x86_64/ldt.h	2015-08-19 17:12:22.114975088 +0100
@@ -12,9 +12,12 @@
 #define LDT_ENTRY_SIZE	8
 
 #ifndef __ASSEMBLY__
+/* Note on 64bit base and limit is ignored and you cannot set
+   DS/ES/CS not to the default values if you still want to do syscalls. This
+   call is more for 32bit mode therefore. */
 struct user_desc {
 	unsigned int  entry_number;
-	unsigned long base_addr;
+	unsigned int  base_addr;
 	unsigned int  limit;
 	unsigned int  seg_32bit:1;
 	unsigned int  contents:2;
@@ -22,6 +25,7 @@
 	unsigned int  limit_in_pages:1;
 	unsigned int  seg_not_present:1;
 	unsigned int  useable:1;
+	unsigned int  lm:1;
 };
 
 #define MODIFY_LDT_CONTENTS_DATA	0
~~~

It would be really nice to cull the local copy of ldt.h, but 2.6.24 seems a little too new to drop support for prior versions. Note also that x86_64 also has an extra field, so the overall struct size will be different between our local copy and the kernels view. What do you think?

**Comment by stsp** [comment]
Please note that the latest versions have a new
field under the ifdef __x86_64__, which is very good.
As such, I'd suggest to just refresh our copy with the
newest one, and be done for now.

**Comment by andrewbird** [comment]
Ok, will do




Sent from Samsung tablet

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 19/08/2015  17:50  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk> 
Subject Re: [dosemu2] Asm/ldt.h has changed structure field type, but those
  structs are used in system call (#60) 
 
Please note that the latest versions have a new
field under the ifdef x86_64, which is very good.
As such, I'd suggest to just refresh our copy with the
newest one, and be done for now.
