### ISSUE TITLE
cpatch.c compile error: ‘force_align_arg_pointer’ attribute ignored [-Werror=attributes] 

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/dosemu2#600]
using gcc 4.9.2 on a x64 LMDE2 system

/home/sam/dosemu2/build/../src/emu-i386/simx86/cpatch.c:96:1: error: ‘force_align_arg_pointer’ attribute ignored [-Werror=attributes]
 {
 ^
/home/sam/dosemu2/build/../src/emu-i386/simx86/cpatch.c:201:1: error: ‘force_align_arg_pointer’ attribute ignored [-Werror=attributes]
 {
 ^
/home/sam/dosemu2/build/../src/emu-i386/simx86/cpatch.c:215:1: error: ‘force_align_arg_pointer’ attribute ignored [-Werror=attributes]
 {
 ^
/home/sam/dosemu2/build/../src/emu-i386/simx86/cpatch.c:229:1: error: ‘force_align_arg_pointer’ attribute ignored [-Werror=attributes]
 {
 ^
/home/sam/dosemu2/build/../src/emu-i386/simx86/cpatch.c:244:1: error: ‘force_align_arg_pointer’ attribute ignored [-Werror=attributes]
 {
 ^
/home/sam/dosemu2/build/../src/emu-i386/simx86/cpatch.c:259:1: error: ‘force_align_arg_pointer’ attribute ignored [-Werror=attributes]
 {

**Comment by stsp** [comment]
Such an old gcc is currently not supported.
Does anyone thinks it should?
What distro is this?

**Comment by stsp** [comment]
I resurrected the `--disable-cpuemu` configure switch.
You can now try building with it.
If that works, I'll add the configure check.

**Comment by stsp** [comment]
Should now be fixed.
