### ISSUE TITLE
error in libao/configure.ac?

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/dosemu2#601]
Thanks for the compile fix! There were no further compiler errors.

A minor point: During autoconf / configure, I get this error msg:

...
configure: Creating plug-in hooks...
=== configuring in libao
./configure: line 1666: syntax error near unexpected token `,'
./configure: line 1666: `XIPH_PATH_AO(, as_fn_error $? "libao development libs not found" "$LINENO" 5)'
Configuration for libao failed, disabling
=== configuring in gpm
checking for gcc... gcc
...

I didn't mention it yesterday, because it isn't a show-stopper and just disables libao "plugin". The package libao-dev v1.1.0-3 is installed on the system.

**Comment by stsp** [comment]
You don't have to run `autoconf`, you need to
run `autogen.sh` instead.
Also make sure you have `realpath` package installed
before running `autogen.sh`.

**Comment by Baron-von-Riedesel** [comment]
Ok, I ensured that realpath is installed and run autogen.sh,
But, when running default-configure, the same error occurs as described above.

**Comment by Baron-von-Riedesel** [comment]
Hm , the error obviously was that I did run default-configure from a sub-directory ( ../default-configure ). If I run it from inside the dosemu2 directory. the error disappears.

**Comment by stsp** [comment]
Was it an empty sub-directory for the
out-of-tree build?
Please attach the file
`your_dir/src/plugin/libao/aclocal.m4`
and also
`dosemu2_dir/src/plugin/libao/aclocal.m4`

**Comment by Baron-von-Riedesel** [comment]
Yes, it was a try for an out-of-tree build.

There was no aclocal.m4 in "your_dir/src/plugin/libao/aclocal.m4".

I guess the problem is that when I first run ../default-configure, libao-dev wasn't installed yet. So I installed it, but didn't clear all files inside my self-created subdir, and the error persisted. 

Now, after having manually cleared my subdir, the error doesn't show up again, no matter if I call ./default-configure or ../default-configure ... and NOW a file "your_dir/src/plugin/libao/aclocal.m4" DOES exist.

**Comment by stsp** [comment]
No, libao-dev shouldn't cause this because our
source tree has the needed m4 files extracted
from the dev packages. So it does not need dev
packages to correctly generate configure.
I think I've found your bug, sad you can verify
it fixes your problem. Then please at least check
it still works well. :)

**Comment by Baron-von-Riedesel** [comment]
> sad you can't verify it fixes your problem.

Well, if I uninstalll libao-dev and then run ../default-configure from my empty sub-dir, the error reappears - I just tried. So actually I probably COULD verify if a change improves things.

**Comment by Baron-von-Riedesel** [comment]
no change

1. deinstall libao-dev
2. cleared contents of my build subdir
3. run ../default-configure -> error appears
4. install libao-dev
5. run ../default-configure -> error appears
6. clear my build subdir again
7. run ../default-configure -> error has disappeared

**Comment by stsp** [comment]
Even with the fix?
What git revision is this?

**Comment by stsp** [comment]
Please navigate to `"your_dir/src/plugin/libao`
and run
```
make realclean
make
```

Post the output here.

**Comment by stsp** [comment]
You are right, this bug is a bit more difficult.

**Comment by stsp** [comment]
Applied a more intrusive fix.
Please see if that helps.

**Comment by Baron-von-Riedesel** [comment]
Yes, the error is gone now

**Comment by stsp** [comment]
Thanks.
