### ISSUE TITLE
Mouse not working in FreeDOS's 'edit'.

### ISSUE THREAD

**Issue by magiblot** [stsp/dosemu2#603]
Hi there. I tried the `edit` application that comes with FreeDOS but mouse support doesn't seem to work very well. I experienced the following:

- In X11 / SDL mode: the cursor disappears over dosemu's window. It replies very slowly to mouse actions.

- In tty, with `-t` option: GPM mouse pointer disappears only when running this application.

Other programs, such as DOS's `edit.com`, work properly for me in both modes.

If I missed any information in the documentation regarding this issue, please tell me.

Lots of thanks.

**Comment by stsp** [comment]
I can't reproduce this: mouse working
perfectly for me in freedos's edit. The
only minor problem I can see is that
mouse is no longer visible in dosemu
window after I exit edit.exe.
OTOH in pc-dos's edit I can't always
click menus (sometimes they respond
to click and sometimes not), but the
same I see with the DOS mouse driver.

**Comment by stsp** [comment]
> In tty, with -t option: GPM mouse pointer disappears only when running this application.

-t usually gives xterm mouse, not gpm.
Unless you switched to the text console
w/o X server.

**Comment by stsp** [comment]
I now tried text console and -t (gpm)
and it still works for me perfectly.
Not sure what you may be seeing.

**Comment by magiblot** [comment]
Okay. Here is one: https://drive.google.com/open?id=1CBs6LbZYEIZH8GiAVi4ZuvU8ycn_zGT2

In the first part I run dosemu under tty. The first time I run `edit`, the GPM mouse pointer is not shown. Then I close dosemu, set the tty width to 80 columns (so that DOS's `edit.com` will be displayed properly), and run it again. Mouse for both `edit.com` (MSDOS) and `edit` (FreeDOS) works now (at the time of writing the OP, however, I didn't know it would work for `edit` with this configuration).

In the second part I run dosemu under a X session. What happens then is the same I explained in the OP. I also run htop showing the CPU usage during the slowness.

> Are you using edit.exe from dosemu-freedos-1.0-bin.tgz, or from other sources?

It should be that version. I didn't change it on purpose. I run the `ver` command at minute 2:00, just in case.

I'm using ArchLinux, so my installation source is https://aur.archlinux.org/packages/dosemu2-git/. From what I can see in the PKGBUILD file, source code is downloaded and compiled from this github repository, so the code should be updated. If you need me to compile and run dosemu with debug features, I can do it.

Regarding the DPMI error message displayed at 0:25, I'm aware I don't have LDT enabled. I compiled the kernel with the suggested options a few updates ago. Appearently, it's not necessary to run `edit` or `edit.exe`.

Thanks.

**Comment by stsp** [comment]
OK, firstly we have different edits.
Yours is 0.9a and mine (and the one from
dosemu-freedos-1.0-bin.tgz) is 0.7d.
The update likely came from archlinux.
While I am not going to blame anyone
for updating the software, this is a bit
inconvenient that people think they use
the virgin packages when they do not.
So I'll think what to do with that management
issue, and in a mean time please try
edit.com that is in dosemu-freedos-1.0-bin.tgz.

> It should be that version. I didn't change it on purpose. I run the ver

Unfortunately this only shows the version
of command.com. I think @severach updated
some utilities. You can find the version of
edit.exe in its help/about.

> I also run htop showing the CPU usage during the slowness.

But this doesn't match your initial
`It replies very slowly to mouse actions.`,
which is why I wanted to see it on video.
Its just a slow redraw, not a slow reaction.
I think it is somehow arch-specific, and
there are work-arounds to try here:
https://github.com/stsp/dosemu2/issues/417#issuecomment-347486841
Could you please try that change?

**Comment by magiblot** [comment]
Okay, I replaced `/usr/share/dosemu/freedos` with `dosemu-freedos-1.0-bin.tgz/freedos` and ran `edit` 0.7d. It didn't solve the issue, however.

I would like to change some of my statements from the OP:

> In X11 / SDL mode: the cursor disappears over dosemu's window. It replies very slowly to mouse actions.

**As you said, it's a slow redraw and not a slow reaction, and it is an external issue. It doesn't happen with MSDOS's `edit`, though** (this is what initially made me think it could be a dosemu issue). I'll try the workaround you pointed out later.

> In tty, with `-t` option: GPM mouse pointer disappears only when running this application.

**In tty, with `-t` option: GPM mouse pointer for FreeDOS's `edit` appears only if `stty columns 80` was ran before dosemu. For MSDOS's `edit.com` it will appear under any circumstances, but the screen will be drawn properly only if `stty columns 80` was ran.**

If I had realized this before, I probably wouldn't have opened this thread, because this might not even be a issue.

Does the GPM mouse work for you within dosemu, in a tty with more than 80 columns, for FreeDOS's `edit`?

**Comment by stsp** [comment]
> 0.7d. It didn't solve the issue, however.

Try skipping config/autoexec by pressing
F5 at early boot. Then we will have the more
reliable test that excludes any possible changes
of archlinux.

> I'll try the workaround you pointed out later.

Thanks, please do.

> In tty, with -t option: GPM mouse pointer for FreeDOS's edit appears only
> if stty columns 80 was ran before dosemu.

But for me 80 is default, so I don't need to run this.

> Does the GPM mouse work for you within dosemu, in a tty with
> more than 80 columns, for FreeDOS's edit?

Sorry, I can't set more than 80, KMS console
does not permit me to. But I tried 70, 40 - all worked.
In a few cases I noticed the wrong mouse confinement,
i.e. after running at 40 and then switching to 80, the
mouse was still confined to 40, which was cured by
switching a consoles. So while I can see some small
bugs (likely a gpm or tty bugs), the mouse was always
visible for me in freedos edit, and it worked correctly.
If the problem is specific to over-80 modes, then I
can't even test it.
Please attach the -D9+m log.

**Comment by magiblot** [comment]
> Try skipping config/autoexec by pressing F5 at early boot. Then we will have the more reliable test that excludes any possible changes of archlinux.

dosemu's early boot? I ran `dosemu -t` and immediately started pressing F5 repeatedly. I didn't notice anything different either in the boot message or `edit`. I don't know if I did it well.

> Please attach the -D9+m log.

These are without pressing F5 or applying workarounds to the source code:

[tty128columns.log](https://github.com/stsp/dosemu2/files/2005066/tty128columns.log)
[tty80columns.log](https://github.com/stsp/dosemu2/files/2005067/tty80columns.log)

> I can't set more than 80, KMS console does not permit me to.

Maybe this is just making things even more complicated, but I can reproduce a similar issue in `konsole` or `xterm`. However it could also mean the issue does not depend on GPM.

If I run `export TERM=linux && dosemu -t`:
- 80 columns or less: mouse interacts with `edit`.
- More than 80 columns: mouse doesn't work.

-D9+m logs for this:

[xterm>80columns.log](https://github.com/stsp/dosemu2/files/2005128/xterm.80columns.log)
[xterm<=80columns.log](https://github.com/stsp/dosemu2/files/2005127/xterm.80columns.log)

> > I'll try the workaround you pointed out later.
> 
> Thanks, please do.

I'll do this next.

**Comment by stsp** [comment]
> dosemu's early boot?

You need to comment out the second line
in `fdconfig.sys`:
`; SWITCHES=/F`
Then you'll have the early boot delay.

> If I run export TERM=linux && dosemu -t:

Yes, I can reproduce the problem even with
gnome-terminal without any `TERM=linux`, so
its quite simple.
I'll take a look, but I highly suspect it is an
edit.com's bug.

**Comment by stsp** [comment]
So freedos edit simply doesn't enable mouse
when the terminal is too large. I see no int33
calls in the log.
I think this should be closed.
You can try to reach some freedos devs for this.
Probably dosemu should warn about non-standard
tty geometry, as some programs can't handle that.

**Comment by severach** [comment]
The slowness started with Kernel 4.12. Try Kernel 4.9 LTS which also won't cause DPMI errors.

Edit 0.9 is from FreeDOS 1.1. The version of edit should have no effect. The Arch package uses FreeDOS 1.1 + GNU utilities from FreeDOS 1.0. The package does not modify autoexec or config.

Every program that uses the mouse will be affected. It just takes a while to find a sequence that shows it. For edit, hover the mouse over the dosemu window and bring up a menu (Alt-F) and hold the down arrow, no slowness. Now hold the right arrow, lots of slowness. The slowness has everything to do with how much is painted. In Norton Commander ^O paints the maximum amount so goes the slowest. In Foxpro the only operation I could find that goes slow is drag-n-drop BROWSE columns. Menu right arrow does not go slow.

The programs are never slow when the mouse is outside of the dosemu window. `dosemu -t` does not interface with the X11 mouse so is never slow but has a mouse problem for now. #578

For missing dependencies no need to reinstall, `pacman -Qi dosemu2-git`

**Comment by magiblot** [comment]
> So freedos edit simply doesn't enable mouse when the terminal is too large.

Oh... sad ending 😢
I agree with closing the issue.

> Try Kernel 4.9 LTS which also won't cause DPMI errors.

Is there any way of doing this other than compiling from source?

> For missing dependencies no need to reinstall, > pacman -Qi dosemu2-git

Thanks. The last time I installed dosemu2, I was using OpenSUSE and I had to compile from source and install manually, so finding missing dependencies was just as manual. I hadn't changed my mindset yet.

**Comment by stsp** [comment]
> Oh... sad ending
> I agree with closing the issue.

If the problem is real for you, this doesn't
have to be an ending. You can try to reach
a freedos ppl with this, or maybe you can
ask me for a config option to force the default
geometry no matter how large the terminal is.
Or you can think up some other solution, or
even code it up, if you want. :)

Please let us know about the testing results
with kernel etc, then lets close.

**Comment by severach** [comment]
You can compile with the AUR package [linux-lts49](https://aur.archlinux.org/packages/linux-lts49/) or install from the [Arch Linux Archive](https://wiki.archlinux.org/index.php/Arch_Linux_Archive).

Manjaro still supplies kernel 4.9 compiled.

**Comment by magiblot** [comment]
> you can ask me for a config option to force the default geometry no matter how large the terminal is.

I don't know how many DOS applications other than FreeDOS's `edit` support more than 80 columns. In the case of `edit` it is a problem because mouse is then not supported. In the case of the MSDOS applications I tried, it is a problem because they still assume there are 80 columns and don't display properly.
I tried `C:\> mode con cols=80` with dosemu running in a fullscren console but it makes no difference. So, if there is no way to force this within the command prompt (similar to linux's `stty`), `autoexec.bat` or `config.sys`, that would be a useful option.

> You can try to reach a freedos ppl with this

This should be the actual solution. I just opened a ticket in SourceForge. We'll see what happens..
https://sourceforge.net/p/freedos/bugs/214/

> Please let us know about the testing results with kernel

> You can compile with the AUR package linux-lts49 or install from the Arch Linux Archive.

Thanks. It now works wonderfully in SDL/X11 mode just as you said. The rendering slowiness is a kernel issue.

**Comment by stsp** [comment]
> The rendering slowness is a kernel issue.

More likely a kernel config's problem.
In any case, someone have to write a
small test-case to get this solved.

**Comment by severach** [comment]
>I don't know how many DOS applications other than FreeDOS's edit support more than 80 columns

Foxpro and WordPerfect support 132 columns. I don't use WordPerfect but I know that Foxpro only supports 80 or 132. Any other number will garble the screen.

#319 fixed the mouse in some VESA 132 column [modes](http://cs.lmu.edu/~ray/notes/pcvideomodes/). I couldn't find any Trident 132 column modes with proper mouse support. There are other modes that `mode` can generate that don't seem to be on that list.

**Comment by jharrison022** [comment]
I don't know if this is helpful but I've seen this behavior and loading cutemouse made the mouse cursor work properly in the FreeDOS editor.

**Comment by stsp** [comment]
How do you load cutemouse under dosemu2?
I am not saying its absolutely impossible, but I
don't think I ever documented this possibility.

**Comment by magiblot** [comment]
What steps did you follow?
I downloaded CuteMouse v2.1 beta 4 from [SourceForge](http://cutemouse.sourceforge.net/) and ran `CTMOUSE.EXE` within dosemu but I didn't notice any changes.

**Comment by stsp** [comment]
> and ran CTMOUSE.EXE within dosemu but I didn't notice any changes.

Because it doesn't find the mouse.
You _can_ do that, but not without some
config tweaking in an undocumented ways.

**Comment by magiblot** [comment]
Thanks. Works well.

Would it be possible to restore the terminal to its original size after exiting dosemu (Ctrl-Alt-PgDown)?

**Comment by stsp** [comment]
Yes, should be possible.
Please open a ticket for this, or, preferably,
a pull request. :) So that this is not left forgotten.

**Comment by magiblot** [comment]
I'm sorry I can't write a pull request. I will open a ticket.
