### ISSUE TITLE
lredir smb1 share

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#607]
On dosemu2-2.0pre6 I am having problems with a smb share which is mounted as following:

`sudo mount -t cifs //192.168.0.100/Volume_1/ /home/username/mount -o,rw,guest,auto,nounix,dir_mode=0777,file_mode=0777,uid=1000,gid=1000,vers=1.0
`
The share doesn't allow smb versions higher than 1. I also tried using a username and password instead of anonymous mode.
In Dosemu i use lredir2 to map the directory:
`lredir2 F: linux\fs/home/username/mount`

While I can copy and remove files in nautilus and terminal I can't open, delete or copy files from that share in dosemu, I always get
`Cannot open source file - F:\xxx\xxx.txt`

Other shares are working fine. Any way to debug this?

**Comment by stsp** [comment]
Are those `xxx` bogus or changed by you to hide names?

**Comment by haenschen** [comment]
Changed by me

**Comment by stsp** [comment]
Please update to latest and provide the `-D9+dD` log.

**Comment by stsp** [comment]
Of course when you do, you'll have to
reveal the real file names so that people
can quickly find them in the log.

**Comment by haenschen** [comment]
Attached the -D9+dD log for pre6, trying to xcopy F:\vitrine1 directory
Devel following shortly

[bootold.log](https://github.com/stsp/dosemu2/files/2048686/bootold.log)

**Comment by haenschen** [comment]
This is the log for pre6 where I manually edited mfs.c and recompiled, reinstalled and tried the copy again, hope this works out.

[boot.log](https://github.com/stsp/dosemu2/files/2049192/boot.log)

**Comment by haenschen** [comment]
[boot.log](https://github.com/stsp/dosemu2/files/2049671/boot.log)

**Comment by stsp** [comment]
No, does not contain the last change.
Please grep for "access denied" and see yourself.

**Comment by haenschen** [comment]
[boot.log](https://github.com/stsp/dosemu2/files/2049725/boot.log)

**Comment by haenschen** [comment]
`Ist kein Verzeichnis` translates to `Is not a directory`

**Comment by stsp** [comment]
Ah

**Comment by haenschen** [comment]
Yes!

**Comment by stsp** [comment]
This is likely some cifsfs bug.
Various sources suggests to try `nounix`
or `nodfs` options to mount...

**Comment by haenschen** [comment]
Oh well... thanks for debugging another non-dosemu related problem... I removed my usual `nounix`  and now it seems to work. Just out of curiosity, what is different to the processing nautilus / terminal does and dosemu to get to such an error?

**Comment by stsp** [comment]
Hard to even imagine, as dosemu does
nothing fancy but a casual `open(file, O_RDONLY)`.
Likely it breaks the server (or client) earlier
by doing other unix-specific things like `stat`,
`access` etc, and after that it just returns an
error to everything.
You won't know for sure unless you fill in the
bug-report to the right place.
