### ISSUE TITLE
package-depends-on-an-x-font-package

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#611]
When building on ubuntu-18.04, I am getting this:
```
E: dosemu2: package-depends-on-an-x-font-package depends: xfont-utils (>= 1:7.5+2)
```

I only have `Depends: ${misc:Depends}, ${shlibs:Depends}`
in `control`, so it seems debuild complains to its own deps?

@skitt any clues to this? :)

**Comment by stsp** [comment]
Wow!
Are you sure this
https://lintian.debian.org/tags/package-depends-on-an-x-font-package.html
is an adequate reaction on a depend referring
to a non-existent package?
But in fact - yes, typed `sudo apt-get upgrade`
and the error disappeared. :) I was upgrading
just a few days ago, so it seems the update was
pushed just about now.
Thanks.

**Comment by skitt** [comment]
It’s not strictly speaking a reaction to the dependency on a non-existent package, it’s a reaction to the dependency on a package named xfont-something ;-). The dependency on a non-existent package would be caught by other tools in the build infrastructure (piuparts in particular).

**Comment by stsp** [comment]
> dependency on a package named xfont-something ;-)

Oh my, wildcard matching...
Not that I can trust this debhelper code from now on. :)
Thanks for info!
