### ISSUE TITLE
Another, more tricky "cpu exception in dosemu code outside of DPMI client!"

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/dosemu2#612]
Attached is a testcase, including dosemu's boot.log with -D9+M

The test case is a simple Makefile, the programs involved are NMAKE.EXE and JWASM.EXE. Both a normal Win32 applications, running inside DosEmu with the help of HX's Win32 emulation. The problem occurs AFTER jwasm is finished and control has returned to nmake.

To run the testcase first run CONFIG.BAT, then start NMake. This works in pure DOS, but causes DosEmu to crash ( or "hang" ).

Besides boot.log there are also 2 log files included, written by a debug version of HX's dpmi loader ( also included in the test case, filename is DPMILD32.EX_ ). The first log file, Dos.log, created inside DOS, shows how things should look like if everything's ok. The second log file, Linux.log, shows what the DPMI loader has to say inside DosEmu. The interesting part in the logs is:

---------------- Linux.log ---------------------------------
*** bye from DPMILDXX ***
dpmildr: int 21, ah=4Ch; checking psp
checkpsp: current psp segment is 0B2A                    <<<<------ SHOULD BE 02E1
checkpsp: compare with 02E1
checkpsp: PSP not found, will route to previous handler
-------------------------------------------                      <<<<---- this line and the next 2 should occur directly after the *** bye ... *** line
dpmildr 21-4bh: back from int 21h, ax=4B00h
dpmildr 21-4bh: returning to launching app
---------------- Linux.log end -----------------------------

---------------- Dos.log ---------------------------------
*** bye from DPMILDXX ***
-------------------------------------------
dpmildr 21-4bh: back from int 21h, ax=4B00h
dpmildr 21-4bh: returning to launching app
dpmildr: int 21, ah=4Ch; checking psp
checkpsp: current psp segment is 02EF
checkpsp: compare with 02EF
---------------- Dos.log end ---------------------------------

[testcase.tar.gz](https://github.com/stsp/dosemu2/files/2054267/testcase.tar.gz)

**Comment by stsp** [comment]
Could you please check also on dosemu1?

**Comment by stsp** [comment]
`Reading symbols from /usr/local/bin/dosemu.bin...(no debugging symbols found)...done.`
Bad log.
Please use `./default-configure -d` to enable debugging.

**Comment by stsp** [comment]
`To run the testcase first run CONFIG.BAT, then start NMake.`

```
C:\TEST>nmake
DPMILD32: Module=MSVCRT.dll
DPMILD32: File not found error
dpmild32: MSVCRT.dll: cannot load PE file
```

Bad test case. :)

**Comment by Baron-von-Riedesel** [comment]
I updated the testcase in the first post ( added msvcrt.dll and new boot.log ) :)

**Comment by Baron-von-Riedesel** [comment]
Here's a much simplified test case, without the Win32 emulation stuff. Just a dpmi application (exec3.exe) which lauches another dpmi application (exec3a.exe) ; both apps using the hx dpmi loader.

Dosemu shows the same problem in the log, but doesn't crash this time, just displays "unhandled exception 0x0e .... ". Boot.log is just 200 kB long.


[testcase2.tar.gz](https://github.com/stsp/dosemu2/files/2054509/testcase2.tar.gz)

**Comment by stsp** [comment]
Crash log would nevertheless be good to have.
I suspect dosemu is trying to decode the instruction
at wrong addr, which causes the crash. We need
to add the preventive checks.

**Comment by Baron-von-Riedesel** [comment]
the second test case runs in dosemu 1.4, so this bug is probably a regression.

**Comment by stsp** [comment]
DOS exec was rewritten.
In dosemu2 it is handled in msdoshlp.c:exechlp_thr().
In particular it calls DPMI save/restore prot-mode context,
which dosemu1 did not do.
Maybe we need to pass some registers from child
to parent, rather than to restore everything?
Or there may be just a bug.

**Comment by stsp** [comment]
Should now be fixed.
Had to write a proper allocator for
HX-specific linear allocs.
Your test now passes:
```
launching exec3a.exe
in exec3a
back in exec3.exe
```
But in the log I don't see it launching exec3a.
I think it is completely dummy.

**Comment by stsp** [comment]
No, it only does dummy things if
`config.bat` is not executed.
So all seems well.

**Comment by Baron-von-Riedesel** [comment]
Yes, it's fixed - test case 2 runs now. 

However, the first test case, which lauches 2 Win32 console apps ( NMake and JWasm ), now behaves differently: when the dpmi loader tries to load JWasm, it can't to this because memory region 0x400000 is in use already, and the binary cannot be relocated because it's without relocation infos. So the loader has to terminate with error msg "relocs stripped, cannot load".

In the second test case, both binaries ( exec3.exe and exec3a.exe ) were relocatable, so there was no such problem.

**Comment by stsp** [comment]
As I said in
https://github.com/stsp/dosemu2/issues/612#issuecomment-393163922
I have problems running first test-case.
But I tested quake2 and it still works
(and yes, I again had to remove w32dhcp.tmp
to get it working).
It would be good if you open a new ticket,
add an updated test-case1 and also an
updated DPMI log.
But I'll be at vacations in a few hours, so
likely this will have to wait a couple of weeks.

**Comment by stsp** [comment]
Also in the log of the second test-case
I see one linear alloc succeeded and another
one failed, as being overlapped with the
first one. So its not like I broke the linear
allocs with this change.
If any of your code expects the overlapping
linear allocs to succeed, that should be fixed
in your code. As your second test-case did
not fail because of this, I took it as an indication
that it expected the second alloc to fail, which
would be correct.

**Comment by Baron-von-Riedesel** [comment]
> I have problems running first test-case.

To cite myself:
> I updated the testcase in the first post ( added msvcrt.dll and new boot.log ) :)

so you should have had no problems with the first test case anymore.

However, since you mentioned that quake2 still runs: I didn't doubt that, that was simply not the point. 

Anyway, it's somewhat fixed now, no regression compared to dosemu 1 anymore.

I wish you nice holidays! :)

**Comment by stsp** [comment]
> To cite myself:

Ah, you re-uploaded the file to the
same old posting... This is very counter-intuitive
provided that you also added the new
test-case to new posting. So I thought the
new one is an updated and simplified
version of the first one...
In general I think it would be good to not
re-upload files to edited comments, but
rather to create a new comments and with
attachments.

> However, since you mentioned that quake2 still runs: I didn't doubt that, that was simply not the point.

But didn't it require the linear allocs to work
properly? The regression was introduced
exactly with a quake2 work. It was that I
unintentionally allowed the overlapping linear
allocs, which surely leaded to a crashes and
corruptions if someone tried to do the overlapped
allocs (he shouldn't). So if quake2 works,
I expect the win32 support things are in general
correct.

> Anyway, it's somewhat fixed now, no regression compared to dosemu 1 anymore.

So the bug was in the test-case that expected
the overlapping allocs to work?

> I wish you nice holidays! :)

Thanks. :)

**Comment by Baron-von-Riedesel** [comment]
> I unintentionally allowed the overlapping linear allocs,

A yes, I see now. I thought it was a - very useful - feature. The first test case obligatory requires that both clients are to be loaded a the very same linear address ( 0x400000 ). HDPMI optionally allows that, giving each client its own address space, LDT and IDT. I'm aware that Dosemu can't do that, but with a certain amount of "descriptior magic" implemented in dosemu it might have been possible to fake at least the address space separation.

**Comment by stsp** [comment]
> amount of "descriptior magic" implemented in dosemu it might have been possible
> to fake at least the address space separation.

Indeed this is possible.
dosemu already relocates the entire DOS
address space by offsetting all segment bases.
Even the linear allocs are relocated that way,
so there should be no problems to introduce
multiple memory windows.
The question is only how do you tell the DPMI
to switch address space?

**Comment by Baron-von-Riedesel** [comment]
> The question is only how do you tell the DPMI to switch address space?

In HDPMI that's no problem. Since the clients are almost totally separated, there is no interrupt or exception vector daisy chaining. So if a client launches another client, it remains inactive until the called client has terminated. The context switch is just needed at one occasion: when the client terminates with int 21h, ah=4Ch.

There might be troubles if the first client changes real-move int vectors and implements real-mode callbacks. tSuch callbacks won't work and must be disabled while the second client is active ( popular example are mouse events ).

**Comment by stsp** [comment]
> In HDPMI that's no problem. Since the clients are almost totally separated,
> there is no interrupt or exception vector daisy chaining.

i think I had problems with that.
You can search for "inherit_idt" in dpmi.c.
So if a new client starts with the same bitness,
it will by default forward interrupts to prev
client. I think this was needed for windows's
DOS prompt and for BC environment.
Note that BC environment is absolutely
weird, for example if it starts tlink.exe under
bcc.exe, then tlink.exe immediately uses
raw mode switch, w/o doing any DPMI init
calls. So it really expects to work in the
address space of its parent.

Overall it might be an interesting task to
start every new client in its separate "fake"
address space. But the additional complication
is that it wants to see the first mega at the
proper location, so I will need to map lowram
into every client by hands. Again something
similar was already tried, and the code that
duplicates first mega, resides in a branch
"kvm_base". Maybe I can take it from there
and implement something. But for that I will
need a lot of profit, like 1024+ win32 apps
working. :) As it will be quite a large work.

**Comment by stsp** [comment]
If HX could run some serious game titles
from win98 era, I would drop fdpp project
immediately and implement the address
space separation instead. :)
But AFAIK it only supports some opengl
games, but not DX games?

**Comment by Baron-von-Riedesel** [comment]
> But I tested quake2 and it still works
> (and yes, I again had to remove w32dhcp.tmp
> to get it working).

IIRC I did already mention that in the HX package there is a "dummy" WSOCK32.DLL ( in the UNSUPP sub-directory ).  If this file is copied to the quake2 dir, tcp isn't used at all and no w32dhcp.tmp is generated.

**Comment by stsp** [comment]
> IIRC I did already mention that in the HX package there is a "dummy" WSOCK32.DLL
> ( in the UNSUPP sub-directory ).

Its the first time you mentioned the `UNSUPP`
subdir, where there is indeed a second instance
of `WSOCK32.DLL`, much smaller than the one
in `BIN`. I suppose you assume the user has to
understand the presence of different file with
the same names. In any case, if I put the dummy
wsock32.dll to the q2 dir, it doesn't start at all,
just a black screen.

**Comment by Baron-von-Riedesel** [comment]
>  I suppose you assume the user has to understand the presence of different file with the same names

IIRC it's documented somewhere.

> it doesn't start at all, just a black screen.

Yes, that was what I also thought at first. But if you then press Ctrl-Break, it starts. Weird! :))

**Comment by stsp** [comment]
Indeed, works. :)
So just changing one bug to another...

**Comment by stsp** [comment]
Why does HX do the linear allocs at the
very high addresses, like `fffc0000`?
This randomly fails under dosemu2.
And HX seems to be OK with the failure
in most cases, but sometimes I see crash.
I made the failures a bit more predictable
now, but it would be nice if HX just stops
doing so?

**Comment by Baron-von-Riedesel** [comment]
> Why does HX do the linear allocs at the very high addresses, like 

It doesn't. It uses linear alloc ( dpmi function 0x504 ) only if the binary has no relocation info, and this usually means the binary "wants" to be loaded at address 0x400000. Dlls usually do have relocation infos and the loader just uses a simple dpmi 0x501 call for memory alloc.

**Comment by stsp** [comment]
0x400000 is fine. I coded up the machinery
for this to always succeed. The problem is along
the lines of:
```
DPMI: int31, ax=0504, ebx=0ae30000, ecx=000a0000, edx=00000000
        edi=00000000, esi=0ae30000, ebp=02246d74, esp=02246d4c
        eip=0225fb4c, eflags=00093246
        cs=00ff, ds=0107, ss=0107, es=0107, fs=0137, gs=0000
DPMI: allocate linear mem attempt for siz 0x000a0000 at 0x0ae30000 (uncommitted)
DPMI: dpmi function failed, CF=1
...
DPMI: int31, ax=0504, ebx=0b580000, ecx=002d0000, edx=00000000
        edi=00000000, esi=0b580000, ebp=02246d6c, esp=02246d44
        eip=0225fb4c, eflags=00093246
        cs=00ff, ds=0107, ss=0107, es=0107, fs=0137, gs=0000
DPMI: allocate linear mem attempt for siz 0x002d0000 at 0x0b580000 (uncommitted)
      malloc returns address 0xb580000
                using handle 0x0000001b
...
DPMI: int31, ax=0504, ebx=0a910000, ecx=00040000, edx=00000000
        edi=00000000, esi=0a910000, ebp=022468c0, esp=02246898
        eip=0225fb4c, eflags=00093246
        cs=00ff, ds=0107, ss=0107, es=0107, fs=0137, gs=0000
DPMI: allocate linear mem attempt for siz 0x00040000 at 0x0a910000 (uncommitted)
DPMI: dpmi function failed, CF=1
...
DPMI: int31, ax=0504, ebx=0be40000, ecx=00200000, edx=00000000
        edi=00000000, esi=0be40000, ebp=02246944, esp=0224691c
        eip=0225fb4c, eflags=00093246
        cs=00ff, ds=0107, ss=0107, es=0107, fs=0137, gs=0000
DPMI: allocate linear mem attempt for siz 0x00200000 at 0x0be40000 (uncommitted)
      malloc returns address 0xbe40000
                using handle 0x00000022
...
DPMI: int31, ax=0504, ebx=0c040000, ecx=000a0000, edx=00000000
        edi=00000000, esi=0c040000, ebp=0224697c, esp=02246954
        eip=0225fb4c, eflags=00093246
        cs=00ff, ds=0107, ss=0107, es=0107, fs=0137, gs=0000
DPMI: allocate linear mem attempt for siz 0x000a0000 at 0x0c040000 (uncommitted)
      malloc returns address 0xc040000
                using handle 0x00000023
```
etc etc. As you can see, these allocs are randomly
success or fail because the addresses are strange.

**Comment by Baron-von-Riedesel** [comment]
> because the addresses are strange.

AFAICS such "strange" addresses were returned by dosemu if a dpmi call ax=504h with ebx=0 for uncommitted memory is issued. The application does not "require" such addresses, and with hdpmi there are none to be found in the log.

**Comment by stsp** [comment]
But as is clear from the above log snip, `ebx!=0`.
There are many allocs with `ebx==0` too, which are
properly logged and handled. I excluded them from
the above log.
The strange addresses are _requested_.

**Comment by andrewbird** [comment]
I just wonder if the upper 16 bits of ebx aren't being preserved somewhere before int31 call and are in fact random?

**Comment by stsp** [comment]
> I just wonder if the upper 16 bits of ebx aren't being preserved

Only Japheth knows, but note that also ESI
contains the same value. So at least its not
entirely random. :)

**Comment by andrewbird** [comment]
Is the client 16bit? If so would it be expected to zero the whole of ebx to indicate the don't care about address? Does the server know then client is 16bit?

**Comment by stsp** [comment]
> Ok, but exactly those allocs return these "strange" addresses.

Maybe (will have to check with your test-case),
but could you please explain the logic? Do you
get these addresses with ebx==0, then free(),
then alloc again to that addr explicitly?
Otherwise I simply don't see the connection between
what ebx==0 returns and what happens next
when ebx!=0.
In the log above, the entry ebx is printed, not the returning value.

> IIRC function 0504h is supposed to be supported for 32-bit clients only.

DPMI spec says:
```
A DPMI 1.0 host that is 16-bit only will not support this function.
A 16-bit client of a 32-bit DPMI 1.0 host can use this function.
```

However, full ebx is accounted in either case, obviously.

> If so would it be expected to zero the whole of ebx to indicate the don't care about address?

Whole ebx, or did you mean only the higher word of it?

> -         unsigned int base_address = _ebx;
> +         unsigned int base_address = D_16_32(_ebx);

This clearly can't work as the function 0x504 deals
with the linear addresses, not segmented addresses.
Of course we still fake the linear addresses with the
segment base offsets, but that's another story.

**Comment by Baron-von-Riedesel** [comment]
> I think your HX makes some assumptions on the address space layout. 
No, not really. However:
1. when it allocs uncommitted memory, it first allocs 64-4 kB more than was requested and then may reduce the size via call 0505h. This is because in Win32, uncommitted memory is guaranteed to start on a 64 kB boundary, while in dpmi, this is not.
2. if allocating uncommitted memory fails, it just uses the old 0x501 call. This is to make it work with 0.9 hosts.
3. on a few occations, it tries to enlarge a committed linear memory block. If this fails, it just allocates another one.

**Comment by stsp** [comment]
This all is good, but where do those
0x504 calls with non-zero ebx come from?
I am pretty sure your code seems to work
not the way you describe.

**Comment by Baron-von-Riedesel** [comment]
> but where do those 0x504 calls with non-zero ebx come from?

Just load the log file in your favorite editor and use the "find previous instance" function for one of those "strange" adresses. It will find the address returned as a result of a 504h-call with ebx==0. The only exception is the address 0x400000 used by HX's program loader.

**Comment by stsp** [comment]
But could you please clarify what exactly
happens? HX gets some addr with ebx==0,
and then tries to allocate it again, or what?
I don't understand.

**Comment by Baron-von-Riedesel** [comment]
> HX gets some addr with ebx==0, and then tries to allocate it again, or what?

It tries to emulate the Win32 HeapCreate() function. With this function you can create a heap with a "maximum" size and an initial size. The initial size is committed memory, the maximum size is reserved memory. Since you can't emulate this with one dpmi call, HX does:

1. allocate an uncommitted memory region (with ax=504, ebx=0, ecx=max size, edx=0
2. commit a part of this region ( usually the first 4 kB, but may vary ) with ax=504, ebx=base, ecx=1000, edx=1

**Comment by Baron-von-Riedesel** [comment]
> It will find the address returned as a result of a 504h-call with ebx==0.

This sentence in my comment was not correct. HX may try to enlarge a memory block, but cannot allow the block to be moved, since the additional memory is meant to grow a heap. So it tries to allocate the region BEHIND the block that is to "grow". In this case it calls dpmi with ax=504 and ebx<>0, and the value in ebx is: base address of a previously allocated block + size of this block. 


HX gets some addr with ebx==0,
and then tries to allocate it again, or what?

**Comment by stsp** [comment]
So this is exactly what I said in https://github.com/stsp/dosemu2/issues/612#issuecomment-398380260
and you said "No". :)
OK, so that's clear.
Now the question is: would you like to
fix this on HX side?

**Comment by stsp** [comment]
Of course there may be nothing to fix if
HX is fine about the failures of such allocs,
but I've seen rare crashes upon Q2 loading
with CS==0, which, as I assumed, was because
of the failing malloc.

**Comment by Baron-von-Riedesel** [comment]
hx can live perfectly with such failures.

The need to press ctrl-break ( and possibly also the crashes) may be due to the hx thread mechanism not working too well in dosemu. AFAICS quake2 does not use multiple threads, but a ctrl-c/ctrl-break signal handler is installed, and in Win32 such handlers got their own thread.

**Comment by stsp** [comment]
Ctrl-c does nothing in my case.
Only Ctrl-Break, and only with Left Control
does the trick! Very strange, indeed.

**Comment by stsp** [comment]
Note that this Ctrl-Break stuff happens
only with your "dummy" winsock. So the
problem may not be with threads.

**Comment by Baron-von-Riedesel** [comment]
This "Ctrl-Break" lag mystery has finally been solved. Or, at least, it doesn't happen anymore with the current HX Win32 emulation. Somehow, an FPU exception occurs in Quake 2 during the startup sequence, and HX's Win32 emulation was unable to handle FPU exceptions if  CR0.NE bit was 1 and exceptions were reported to the client by IRQ 13.

**Comment by stsp** [comment]
Please also make dummy winsock
a default to avoid the need of configuring
the network, removing tmp files and
all the alike.
