### ISSUE TITLE
A couple of minor DPMI issues

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/dosemu2#617]
1. function int 0x31, ax=0x500 (get free memory information) returns an inplausible value for field at offset 0x0C ( linear address space in pages ). This value "should" always be equal or greater than the value in field "free linear address space in pages" at offset 0x1C. In dosemu2 it isn't, it is way too small.

2. a client can only allocate 13 realmode callbacks in dosemu2. The dpmi specification says that there should be at least 16 free callbacks available.

[dpmi.tar.gz](https://github.com/stsp/dosemu2/files/2085322/dpmi.tar.gz)

**Comment by stsp** [comment]
msdos.c was allocating a few, big deal?
Anyway, should now be fixed.
