### ISSUE TITLE
VGA mode in WeirdX -> crash

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#635]
When I use WeirdX as the X11 server, I get a crash when an application uses VGA mode. This is with latest Git. I used `dosemu -X` for launching.
[boot.log](https://github.com/stsp/dosemu2/files/2174131/boot.log)

**Comment by stsp** [comment]
Try to disable `if` clause at `remap.c:3412` like this:
`if (0&&old->color_lut_size && dst->color_lut_size == old->color_lut_size)`

**Comment by jschwartzenberg** [comment]
Then the crash is indeed gone!

**Comment by stsp** [comment]
But it is still unclear what went wrong.
Please run it under valgrind and reproduce
the crash. Tu run under valgrind, set it
to use "vm86sim" and run
`valgrind --trace-children=yes --track-origins=yes dosemu.bin`
It will be veeeery sloooow!

**Comment by jschwartzenberg** [comment]
It seems that it's due to the bit depth. I set it to 16-bit in WeirdX and the crash went away. Possible dosemu2 doesn't handle very low bit depths properly.

**Comment by stsp** [comment]
Should now be fixed.
