### ISSUE TITLE
make deb gives lots of refinition warnings

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#637]
Using current devel branch `make deb` gives lots of redefinition warnings. Interestingly there seem to be both default and overridden values for each variable.

~~~
In file included from /clients/common/dosemu2.git/build/../src/include/config.h:1:0,
                 from /clients/common/dosemu2.git/build/../src/tools/debugger/dosdebug.c:11:
/clients/common/dosemu2.git/build/../src/include/config.hh:17:0: warning: "DATADIR" redefined
 #define DATADIR "/usr/local/share"
 ^
In file included from <command-line>:0:0:
../../../src/include/config.hh:17:0: note: this is the location of the previous definition
 #define DATADIR "/usr/share"
 ^
~~~

**Comment by andrewbird** [comment]
I think this is somehow finding the config.hh down from the directory above `build`, perhaps VPATH is being helpful?
Doing
- `rm -rf build/ ; make deb` gives same warnings
- `rm -rf build/ src/include/config.hh; make deb` warnings go away

**Comment by stsp** [comment]
Could you please try removing `#include "config.h"`
from dosdebug sources? And if that helps - from all
sources. :)
