### ISSUE TITLE
dosdebug log command

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#643]
In another PR coming soon I added the ability to log the dosdebug trace to the logfile as discussed in issue #504 . Subsequently I noticed the dosdebug log command has a 'log on' and 'log off' that isn't documented in the help, so I fixed that. Anyway when testing 'log on' I found I don't really like the interaction with tracing to the logfile. See the following
~~~
dosdebug>
DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
system state: running
AX=0100  BX=0000  CX=00f9  DX=007f  SI=010d  DI=01fb  SP=0a90  BP=0000
DS=0139  ES=0139  FS=0000  GS=0000  FL=000b3246
CS:IP=fc00:0203       SS:SP=0139:0a90

fc00:0203 F4               hlt
dosdebug> log on
dosdebug> 
done
done
MHP:>
done
dosdebug> ldt
dosdebug> 
MHP:< ldt
dosdebug> 
008f: 09092000 00000156 Code16 3 P RA  0x9092000
0097: 09092000 00000156 Code32 3 P RA  0x9092000
008f: 09092000 00000156 Code16 3 P RA  0x9092000
0097: 09092000 00000156 Code32 3 P RA  0x9092000
MHP:>
008f: 09092000 00000156 Code16 3 P RA  0x9092000
0097: 09092000 00000156 Code32 3 P RA  0x9092000
dosdebug> 
 ~~~

The MHP: prefixed lines are the dosdebug conversation being written to the log. I don't like the duplication of log output into the dosdebug terminal. I know that's the feature, but I wonder if you ever use it, or see a use for it?

**Comment by stsp** [comment]
Never used it, and I agree it may be worth
removing. Terminal is much slower than file,
so the big log like `tc` should only go to file.
