### ISSUE TITLE
Manpage for dosemu.bin suggests format of .dosemurc == global.conf

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#66]
See -I section
~~~
"Parse the string behind -I with the same syntax as global.conf or .dosemurc"
~~~

I could correct .dosemurc to ".dosrc", but I'm not sure if that's even used anymore? Or if you think it should just say "same syntax as global.conf", you had had better fix both the English and Russian, as changing the Russian is non obvious to me. :-)

**Comment by stsp** [comment]
> I could correct .dosemurc to ".dosrc"

But .dosemurc is valid.
What's the deal?

Who, -I? It was used even by the dosemu startup
script until very recently. It might be possible to start
deprecating it, but I don't see the point.
If someone wants to rewrite the config system completely
to not use this horrible php-style global.conf - that would be
great.

**Comment by stsp** [comment]
> say "same syntax as global.conf"

That would likely be better.
OTOH we already deprecated global.conf. :)
I'd say just don't touch this piece of shit, or rewrite
it properly with new parser.

**Comment by andrewbird** [comment]
Yes, perhaps I didn't explain properly. The sentence on the English manpage suggests that global.conf and .dosemurc have the same format, which is incorrect. The question is just how to fix that manpage.

I have no problem with the -I option, and I do use it myself.

I never really understood why there is both global.conf and dosemu.conf. I only ever needed to tweak dosemu.conf myself. So I guess if we could kill global.conf but allow dosemu.conf variables to be overridden on the command line, like -I does with global.conf, that would be ideal.

**Comment by stsp** [comment]
> I have no problem with the -I option, and I do use it myself.

Or really? Doesn't this suck? :)

> I never really understood why there is both global.conf and dosemu.conf.

Old dosemu authors had an exceptionally bad habit of
over-engineer things. The results were too complex to
ever work correctly. This is one of those: global.conf is
supposed for tweaking every corner of dosemu with
something almost scriptable, and dosemu.conf is for
"novice users".

> So I guess if we could kill global.conf

It is already killed, see commit 1a807208a.
But all the code complexity is still there. :(

> allow dosemu.conf variables to be overridden on the command line,
> like -I does with global.conf, that would be ideal.

Surely... Would you take up that task? I wonder...

By the way, there is a simpler and more "urgent"
task is to write a freedos installer script. I want dosemu2
to depend on a freedos package optionally, and if it is
not there - just downloads the freedos packages directly
and unzip them. We already have the install procedure
that can just call such script. Someone should write it. :)

**Comment by andrewbird** [comment]
Ahh, I hadn't noticed that global.conf and dosemu.users were not installed any more as I share the sysconf directory with dosemu 1.4.0.

Yes I quite fancy doing the config file rework. So as I understand it any new solution should be able to:
- assign default values to config variables.
- parse /etc/dosemu/dosemu.conf in its current format, overwrite any variable required.
- parse .dosemurc in its  current format, overwrite any variable required.
- parse contents of -I "string" replacement option in 'dosemu.conf' format, overwrite any variable.

I figure a much simpler lex/yacc replacement would be suitable, or have you another suggestion?

**Comment by stsp** [comment]
> Ahh, I hadn't noticed that global.conf and dosemu.users were not installed
> any more as I share the sysconf directory with dosemu 1.4.0.

1.4.0 have simply forgotten to remove them, so to say.
global.conf is not needed for, say, 15 years.

> assign default values to config variables.

That's simple. See src/base/init/dosemu_c.c - it
is auto-generated. You then parse it as a normal
config to get a default values.

> parse contents of -I "string" replacement option in 'dosemu.conf' format, overwrite any variable.

Except that it should have a different name and
syntax - you can't change the format of the existing
switches.

> I figure a much simpler lex/yacc replacement would be suitable, or have you another suggestion?

Really, haven't been researching on this.
But I'd figure, lex/bison parser just for a simple config?
Too much! There should be the simple config parsing
libraries out there.
I hope you estimate the amount of time you'll have
to spend on this. :) But that would be really appreciated.
The main thing is to make it trivial to add a new options.

**Comment by andrewbird** [comment]
Close - won't fix
