### ISSUE TITLE
dosdebug: dynamic support for symbol maps

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#665]
Currently dosdebug has the symbol map support
and uses the one for bios.S. But for fdpp it would
be very useful (I mean, really very useful) to be
able to load the map dynamically via some API,
rather than the one prepared during build, like is
done for bios.S. Besides loading, the API should
also exist for relocation, i.e. when freedos relocates,
the map should be updated.

Andrew, how feasible is that? I think you've done
already all the needed work, so API is the only
missing part? If we have any idea on what such
API should look like, then I can quickly implement
in fdpp and try out. Without symbols, debugging
fdpp is a pain.

**Comment by andrewbird** [comment]
It doesn't have an API, but doesn't `rusermap` do what you ask (if you have a mapfile of course)?

**Comment by stsp** [comment]
Mapfile exists, but `rusermap` likely doesn't
support relocations. freedos relocates a couple
of times, and the map have to be updated.
I wonder how `rusermap` works at all, it probably
can only be used for bios.S that have a static
location, and is therefore completely useless.
Or is it better than I think it is?

**Comment by andrewbird** [comment]
It is possible to adjust the addresses in a mapfile by specifying an origin as you load it, but I've never had cause to use that myself. Using `rusermap` overwrites all the current symbols (but not the bios.S ones), so appending is not possible and might work fine for your case of symbols moving.

Anyway probably the API would make things easier for you I guess.

**Comment by stsp** [comment]
> It is possible to adjust the addresses in a mapfile by specifying an origin as you load it

Where to get it from?

> appending is not possible and might work fine for your case of symbols moving.

You mean by re-loading it by hands, w/o even
knowing the relocation address?

**Comment by andrewbird** [comment]
I had figured you knew the relocation address. What do you have in mind for an API?

**Comment by stsp** [comment]
> I had figured you knew the relocation address.

But even when you load an unrelated prog, where
do you get that addr? I just wonder if `rusermap` is
of any use, because w/o the start addr it certainly is
not.
As for freedos - it decides on its own where to
relocate (to HMA or elsewhere), but I am installing
the hook and update the symtab in fdpp. I can call
the same hook into dosemu2.

> What do you have in mind for an API?

Perhaps just same as rusermap: load the symbol
file from disk, and a function of this kind:
`void RelocHook(UWORD old_seg, UWORD new_seg, UDWORD len)`

**Comment by andrewbird** [comment]
I don't know much about DOS debugger memory maps, looking at the `kernel.map` from fdpp, the symbols to load look like the ones starting at
~~~
Address        Symbol                                                           
=======        ======                                                           
                                                                                
Module: kernel.obj(../kernel/kernel.asm)                                        
0000:0002      _LowKernelConfig                                                 
0010:0100      _intvec_table                                                    
0010:0119      _int1e_table                                                     
0010:0127      _TEXT_DGROUP                                                     
0079:0000*     DATASTART                                                        
0079:0000      _DATASTART                                                       
0079:000e      _NetBios                                                         
0079:001a      _NetRetry                                                        
...
~~~

So when FreeDOS relocates, does it move all the symbols from the file, or just some portion of them? If it's a portion, do you see your `RelocHook()` function select all symbols based upon `old_seg`, and change them to `new_seg`, if so what's the `len` for?

**Comment by andrewbird** [comment]
I also wonder about the mapfile creation as currently it's done by jwlink, but fdpp has an [issue](https://github.com/stsp/fdpp/issues/11) to remove that. After that's done will there even be any mapfile to load?

**Comment by stsp** [comment]
I myself am only getting familiar how freedos
relocates, and update fdpp code with the new
findings (fdpp should know exactly where the
freedos symbols are located).
My current understanding is that freedos
relocates at least 2 times. First it relocates
fully from 0x60:0 to some higher location,
and second time it relocates only the part
of the code. I recently added the hook to
purge what is left. But since the first relocation
happens too early, we don't care about it, and
only load the map file after it happened. So we
need to track one partial relocation.
`len` is the size of the relocated block,
because it is partial, not spanning entire map.

About jwlink - good question, and the answer
is I don't know. What I do know is that it is very
unlikely to get rid of jwlink any soon (unless
someone helps), as there are many higher-prio
tasks on this front, and I am actually more thinking
about comcom32 these days, as fdpp at least a
kind of works. And even if we get rid of jwlink, we
would still get some mapfile. It may have different
format,, but the loading API will remain the same.
So in practice I think this doesn't matter as nothing
will really change.

**Comment by andrewbird** [comment]
Okay, so I have this working from the dosdebug client see #880
I can:
- load mslink map file (with origin if necessary) (respects Absolute symbols too)
- list
- delete a single symbol
- move a block

So how do you see yourself driving this from FDPP, will you want to add symbols directly or shall I need to write a parser for a different map file format? I figure that having FDPP load the symbols itself would be the best method, as I guess it needs to be synchronised with the relocations. But how best to generate the initial symbol data in FDPP?

**Comment by stsp** [comment]
What do you mean?
I thought you can read the linker map file?

**Comment by andrewbird** [comment]
I can read the Mslink map file, but as yet I don't understand the one from LD, particularly the different sections.

**Comment by stsp** [comment]
OK, lets just apply the first patch for
now, with a small change to only return ok/err.

**Comment by andrewbird** [comment]
Would it be acceptable to add another function to the FDPP api to ask dosemu to load the symbols? I'm assuming it would look something like
`void sym_load(const char *filename, uint16_t origin)`
The filename be a full path to kernel.map, which I'm assuming could be in the same location as fdppknrl.sys, so that relocated symbols would then always be present when debugging with FDPP.

**Comment by andrewbird** [comment]
Actually I'm now thinking that dosemu probably finds the fdppknrl.sys, so perhaps the filename shouldn't have a path and dosemu can look for it in the same place as the kernel?

**Comment by andrewbird** [comment]
Or is it better to just have a `const char *FdppKernelMap(void);` that returns just the name and have the plugin call the symbol load, as it knows the location of the kernel and the origin?

**Comment by stsp** [comment]
Exactly.

**Comment by andrewbird** [comment]
Can we close this now?

**Comment by andrewbird** [comment]
Wow, that was fast!
