### ISSUE TITLE
Installing says it cant find a file that actually exists

### ISSUE THREAD

**Issue by DovaMerith** [stsp/dosemu2#670]
**Describe the bug**
A description of what the bug is.
When i try to install in cygwin from source (have as many of the dependancies installed as possible)
**To Reproduce**
Use MobaXterm and install
**Expected behavior**
What you expected to happen.
At the vary least, spewing an error saying some required software wasnt installed
**Attach the log**
When running "sh autogen.sh" i get this error even though the file exists

`bunny[~/git/dosemu2]:>> sh autogen.sh`
`Generating toplevel configure script...
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf-2.69: failed to run aclocal: No such file or directory
Failure!`
`bunny[~/git/dosemu2]:>> ls /usr/share/autoconf/Autom4te/
C4che.pm         ChannelDefs.pm   Channels.pm      Configure_ac.pm  FileUtils.pm     General.pm       Getopt.pm        Request.pm       XFile.pm`

**Comment by stsp** [comment]
This is not a dosemu bug.
Its something with cygwin:
https://stackoverflow.com/questions/47168311/cygwin-and-failed-to-run-aclocal-no-such-file-or-directory
However, even if you fix the cygwin setup,
you won't be able to compile dosemu2.
dosemu2 is linux only.
Please try dosbox instead.

**Comment by stsp** [comment]
> OT note: back when colinux worked it was possible to run dosemu in it

I'e heard that too but never tried.
Have you tried that yourself?

**Comment by stuaxo** [comment]
I did succesfcully run dosemu in colinux with X a few times in the past, just to see if it worked, but don't spend any time in windows so haven't tried WSL.

**Comment by stsp** [comment]
Would be very interesting if someone can
capture the video of dosemu2 under colinux. :)
