### ISSUE TITLE
Initial window size after fullscreen startup

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#672]
Hey,

how can I change the initial window size dosemu switches to via STR+ALT+F after it booted in fullscreen?
I tried 
`$_X_winsize = "800,600"`
but it seems it only works with
`$_X_fullscreen = (off)`

Right now it looks like the attached first picture after switching from fullscreen but I need it smaller like in the second picture.

It works if `$_X_fullscreen = (off)`
And I know it worked with 2.0pre6 but that won't build with Ubuntu 18.04...

![bildschirmfoto von 2018-09-11 13-05-11](https://user-images.githubusercontent.com/9266844/45356482-a2d63e80-b5c3-11e8-8f7a-0795ca0b2c0f.png)

![bildschirmfoto von 2018-09-11 13-09-30](https://user-images.githubusercontent.com/9266844/45356608-f6488c80-b5c3-11e8-8252-d43b067304f1.png)

**Comment by haenschen** [comment]
Seems like this isnt a dosemu problem because devel works (resolution-wise) as I need it on Ubuntu **16**.04.5.
Although fullscreen doesnt work properly here but I guess that‘s a different bug...
![73c3e215-adea-4917-83f6-a9187e1246d1](https://user-images.githubusercontent.com/9266844/45370160-e6db3a80-b5e7-11e8-9164-7d457957bf93.jpeg)

**Comment by stsp** [comment]
It has nothing to do with pre6.
Some SDL bug caused this.
I added a work-around.
Should now be fixed.

**Comment by haenschen** [comment]
Thanks, that did the job.
And for the second bug with devel on Ubuntu **16.**04: I did a bisect 
```
pa@pa-pc:~/dosemu$ git bisect good
42f43c413b0ca253ef6caf269e48a48ffe1fbf48 is the first bad commit
commit 42f43c413b0ca253ef6caf269e48a48ffe1fbf48
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Fri Jan 27 17:02:23 2017 +0300

    sdl: rename $_SDL_nogl to $_SDL_swrast and enable by default [#205]
    
    We have threading and performance problems with the hw renderer.

:040000 040000 07eb5dd604989c5d0d950b3a349453afd020f962 828f4dbee0b46079378a1ffd5e8f3de891d9b3de M	etc
:040000 040000 b1b79f7f6d738a6918d7656f7c346c594b3082ee 7feef68c5da8199c7c6e00311e189524bce3fc04 M	src

```

As I figured out the variable name and default value have changed over the years to todays hardware rendering off. So if I do
`$_SDL_hwrend = (on)`
it also works fine with 16.04.

**Comment by stsp** [comment]
Please ask ubuntu-16.04 to back-port this sdl fix:
https://bugzilla.libsdl.org/show_bug.cgi?id=1859
This have nothing to do with dosemu.
sdl is very buggy, so using the old versions of it
will gain you nothing but a headache.
