### ISSUE TITLE
Insight debugger is very sluggish, unresponsive

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#673]
**Describe the bug**
When starting the Insight debugger ( http://www.bttr-software.de/products/insight/ or https://bitbucket.org/ecm/insight/ ), its interface is sluggish and unresponsive.

**To Reproduce**

1. Start dosemu, eg `$ DOSDRIVE_EXTRA=. dosemu -E "insight.com G:insight.com"`

2. Press eg Up arrow, Down arrow (move code pointer), Alt (show menus), letters to the menus.

**Expected behavior**
Responsive and quick interface, that receives all key presses as intended.

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/2383445/boot.log)

**Comment by ecm-pushbx** [comment]
Just loaded it on my actual DOS machine (MS-DOS 7.10 on a 686). Works as expected, all keys are responsive.

**Comment by ecm-pushbx** [comment]
Keyboard grab (with Ctrl+Alt+K) doesn't improve the situation.

**Comment by stsp** [comment]
Can you try `speed 0`?

**Comment by stsp** [comment]
Insight is buggy, it calls int16 in a busy
loop with interrupts disabled. I checked
SeaBIOS and it has a work-around to
temporary re-enable interrupts. So I
added the same thing.
But someone should fix insight instead.
If not for SeaBIOS, I wouldn't be doing this.

**Comment by ecm-pushbx** [comment]
> Insight is buggy, it calls int16 in a busy
> loop with interrupts disabled. I checked
> SeaBIOS and it has a work-around to
> temporary re-enable interrupts. So I
> added the same thing.
> But someone should fix insight instead.
> If not for SeaBIOS, I wouldn't be doing this.

Thanks! Patched it in https://bitbucket.org/ecm/insight/commits/f7bc4d936a880e52606574e364ed6efff190783d 

But one problem remains: Pressing Alt alone doesn't bring up the menu. F10 works. This happens most of the time in the most recent commit of dosemu2 527c74e787a02fff5aee6777532c8452350939f0 as follows:

* no STI, no HLT, hogthreshold 0
* no STI, no HLT, hogthreshold 1
* only STI, no HLT, hogthreshold 0
* only STI, no HLT, hogthreshold 1
* STI and HLT, hogthreshold 0

However, with STI and HLT and hogthreshold 1, Alt alone works!

It doesn't happen (ie, Alt alone works to open the menu) with only STI (no HLT) or with STI, HLT and dosemu2 45dbc24b7d2ad82ca62672ab2fef21d923c541d1 both with hogthreshold 0 or 1. Also, with that same revision and neither STI nor HLT, we get the sluggish result, but Alt alone does work (as much as any keys at all work).

Should I open a new bug report for that?

**Comment by ecm-pushbx** [comment]
With my patch from https://github.com/stsp/dosemu2/issues/674#issuecomment-421815590 applied on top of 527c74e787a02fff5aee6777532c8452350939f0 it changes slightly. The following cases still fail to open the menu with Alt alone:

* no STI, no HLT, hogthreshold 0
* no STI, no HLT, hogthreshold 1
* only STI, no HLT, hogthreshold 0
* only STI, no HLT, hogthreshold 1

With STI and HLT, both with hogthreshold 0 or hogthreshold 1, the Alt key does open the menu.

**Comment by stsp** [comment]
> Should I open a new bug report for that?

Only if you know what insight actually does.
It seems to be installing the int9 handler and
calls int16 from it sometimes, and sometimes
not. I have no idea what it does and why.

**Comment by stsp** [comment]
OK, I fixed that now.
The problem was that, as I said already,
I don't understand coopthreads. :) So after
running PIC, I forgot to tell coopthreads to
switch to the irq handler.
I'll try to make coopthreads more vocal, so
that if someone forgets to tell it something,
it will at least complain, rather than silently
break.

**Comment by ecm-pushbx** [comment]
Thanks, now Alt alone always works to open the menu, with any of no STI no HLT, only STI, or STI and HLT, as well as with hogthreshold zero or one.

**Comment by stsp** [comment]
Yes, coopth dispatching was screwed, so
depending on delays, it could dispatch
int16 in the context of int9. I added the
dispatching barrier, so reordering in this
place can not happen any more, regardless
of hogthresholds.
