### ISSUE TITLE
Int2F.1680 and/or sti\hlt should release timeslices

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#674]
**Describe the bug**
When running with -I"hogthreshold 0" (or after running "speed 0" in dosemu), I expect that calling Int2F.1680 repeatedly while checking for keys should idle the machine. However, dosemu continues to take up 100% CPU time on one core during this.

**To Reproduce**
```
$ cat testkey.asm 

        cpu 8086
        org 256
start:
.:
        mov ax, 1680h
        int 2Fh
        sti
        hlt
        mov ah, 1
        int 16h
        jz .
        mov ah, 0
        int 16h
        mov ax, 4C00h
        int 21h

$ nasm testkey.asm -o testkey.com
$ DOSDRIVE_EXTRA="$PWD" dosemu -I"hogthreshold 0" -dumb -quiet -E G:testkey.com
```

Observe CPU usage in eg GNOME/MATE system monitor: one core is fully utilised the entire time testkey.com waits.

**Expected behavior**
dosemu's CPU usage should be very low if Int2F.1680 was supported. Note that it currently does return ax = 0, which is meant to indicate that the call is supported. (So, at least it should return ax unchanged if releasing a timeslice is not supported.) Failing that, "sti \ hlt" should idle the CPU while waiting for the next hardware interrupt, with the same expected effect.

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/2385559/boot.log)

**Comment by ecm-pushbx** [comment]
With the following patch, 2F.1680 idles the machine as I expected:

```
$ git diff
diff --git a/src/base/async/int.c b/src/base/async/int.c
index d7712820b..f04df944a 100644
--- a/src/base/async/int.c
+++ b/src/base/async/int.c
@@ -2090,6 +2090,9 @@ static int int2f(int stk_offs)
 
     switch (LWORD(eax)) {
     case INT2F_IDLE_MAGIC:     /* magic "give up time slice" value */
+       set_IF();
+       coopth_wait();
+       clear_IF();
        idle(0, 100, 0, "int2f_idle_magic");
        LWORD(eax) = 0;
        return 1;
$ 
```

I copied this from https://github.com/stsp/dosemu2/blob/devel/src/base/bios/int16.c#L89

**Comment by ecm-pushbx** [comment]
I tried adding a "coopth_wait()" call to https://github.com/stsp/dosemu2/blob/663b7b7f7561c02db204551586981d7bc6507007/src/base/bios/hlt.c#L138 too, but that terminates dosemu with 

```
$ DOSDRIVE_EXTRA="$PWD" dosemu -I"hogthreshold 0" -dumb -quiet -E G:testkey.com
ERROR: Coopth: coopth_wait: not in thread!
dosemu.bin: coopth.c:965: coopth_wait: Assertion `_coopth_is_in_thread()' failed.
```
I don't understand the coopth stuff enough to make this work.

**Comment by ecm-pushbx** [comment]
Looking at https://github.com/stsp/dosemu2/blob/663b7b7f7561c02db204551586981d7bc6507007/src/emu-i386/cputime.c#L392 I think my patch to 2F.1680 should drop the "idle" call and just always call (only) coopth_wait, because the latter is also called by idle (but only if config.hogthreshold != 0).

**Comment by ecm-pushbx** [comment]
Can someone point me to where the function "int16" of src/base/bios/int16.c is called?

**Comment by stsp** [comment]
> I don't understand the coopth stuff enough to make this work.

I applied the completely untested patch that
does the same thing from the dummy coopth
thread. In that case coopth shouldn't complain.
Don't worry, no one understands it. Including
me, as I've forgot the details too.

> Can someone point me to where the function "int16" of src/base/bios/int16.c is called?

See int.c:2680:
`int_handlers[0x16].interrupt_function[NO_REVECT] = _int16_`
There are many permutations. IIRC this was needed because
`int16` or `_int16` collided with some built-in type on clang, so
I did `_int16_`. Overall, trying to understand the inthandling
code of dosemu2 may cause various brain damages, you've
been warned. :)

**Comment by ecm-pushbx** [comment]
> I applied the completely untested patch that
> does the same thing from the dummy coopth
> thread. In that case coopth shouldn't complain.

This presumably works to idle the machine with "sti \ hlt" when hogthreshold is non-zero. (But in that case, the Int16.01 call already idles some on its own.) However, this doesn't yet fix things for when hogthreshold is zero. With the following patch, all "strong idle callers" can actually idle even when hogthreshold is zero:

```
diff --git a/src/emu-i386/cputime.c b/src/emu-i386/cputime.c
index 08d985e4b..41a0ddaef 100644
--- a/src/emu-i386/cputime.c
+++ b/src/emu-i386/cputime.c
@@ -397,10 +397,12 @@ int idle(int threshold1, int threshold, int threshold2, const char *who)
 {
   static int trigger = 0;
   int ret = 0;
-  if (config.hogthreshold && CAN_SLEEP()) {
+  if ((threshold1 == 0 || config.hogthreshold) && CAN_SLEEP()) {
     pthread_mutex_lock(&trigger_mtx);
     if(trigger1 >= config.hogthreshold * threshold1) {
-      if (trigger++ > (config.hogthreshold - 1) * threshold + threshold2) {
+      if (trigger++ > (config.hogthreshold
+                       ? (config.hogthreshold - 1)
+                       : 0) * threshold + threshold2) {
        if (debug_level('g') > 5)
            g_printf("sleep requested by %s\n", who);
        pthread_mutex_unlock(&trigger_mtx);
```

> Don't worry, no one understands it. Including
> me, as I've forgot the details too.

Well thanks for that patch anyway, I think supporting idling with hlt is a good thing.

> See int.c:2680:
> `int_handlers[0x16].interrupt_function[NO_REVECT] = _int16_`
> There are many permutations. IIRC this was needed because
> `int16` or `_int16` collided with some built-in type on clang, so
> I did `_int16_`. Overall, trying to understand the inthandling
> code of dosemu2 may cause various brain damages, you've
> been warned. :)

And that table entry's called by do_int_from_hlt -> do_int_from_thr -> run_caller_func, right?

**Comment by stsp** [comment]
> the Int16.01 call already idles some on its own.) However, this doesn't yet fix things for when 
> hogthreshold is zero.

Why should it?
hogthreshold=0 is just to quickly test
"slow" things to make sure the problem
is elsewhere. Its not for anyone's use.
You can use hogthreshold=10 or 100
instead, if you want.

> And that table entry's called by do_int_from_hlt -> do_int_from_thr -> run_caller_func, right?

Indeed.

**Comment by ecm-pushbx** [comment]
> Why should it?
> hogthreshold=0 is just to quickly test
> "slow" things to make sure the problem
> is elsewhere. Its not for anyone's use.
> You can use hogthreshold=10 or 100
> instead, if you want.

With both of these, and an idling loop, dosemu takes up all the CPU time of a core. So in these cases, clearly things don't work the way I want them to. However, I checked with -D+6g (activating the g_printf calls in https://github.com/stsp/dosemu2/blob/e02be2df2c2cf47cbcb530de682927cb12277851/src/emu-i386/cputime.c#L404 ) and it seems that with hogthreshold = 1 actually the function "idle" only sleeps from the explicit idling, not from the int16 idle() call. So that's what I want, apparently.

```
$ nasm -I/home/evln/coding/proj/lmacros/ testkey.asm -o test.com -D_USE_2F1680 -D_USE_STI_HLT=0 -D_HLT_AMOUNT=4 && DOSDRIVE_EXTRA="$PWD" dosemu -I"hogthreshold 1" -D+6g -dumb -quiet -E "G:test.com"
$ cat testkey.asm

%if 0

Test key input and idling, by C. Masloch, 2018

Usage of the works is permitted provided that this
instrument is retained with the works, so that any entity
that uses the works is notified of this instrument.

DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.

%endif

%include "lmacros2.mac"

	defaulting

	numdef USE_2F1680, 0
	numdef USE_STI_HLT, 0
	numdef HLT_AMOUNT, 1

	cpu 8086
	org 256
start:
.:
%if _USE_2F1680
	mov ax, 1680h
	int 2Fh
%endif
%if _USE_STI_HLT
	sti
 %rep _HLT_AMOUNT
	hlt
 %endrep
%endif
	mov ah, 1
	int 16h
	jz .
	mov ah, 0
	int 16h

	mov ax, 4C00h
	int 21h

$ 
```

However, if hogthreshold is zero, the Int2F.1680 call should return with ax unchanged, because the call never actually idles at all.

**Comment by ecm-pushbx** [comment]
Also, the Int16.00 handler https://github.com/stsp/dosemu2/blob/e02be2df2c2cf47cbcb530de682927cb12277851/src/base/bios/int16.c#L95 directly calls coopth_wait. Shouldn't that be an idle() call, too?

**Comment by stsp** [comment]
> and it seems that with hogthreshold = 1 actually the function "idle" only sleeps from the explicit idling,
> not from the int16 idle() call.

True, int16() is not the "strong" idler
(unless waits for a key), so it starts sleeping
only after 500 consequent polls, as is specified
by the first arg to the idle() call. Making it sleep
after every poll will slow down polling apps to
the unworkable state (the app may do some
drawing in between, or playing music etc).

> However, if hogthreshold is zero, the Int2F.1680 call should return with ax unchanged,
> because the call never actually idles at all.

I can hardly suppose this ever matters, but feel
free to submit such patch. :)

> directly calls coopth_wait. Shouldn't that be an idle() call, too?

Explicitly waiting for an event in an infinite loop
is not the same as idling. Obviously you can't sit
in a busy loop w/o sleep, regardless of the hogthreshold.
`hogthreshold=0` only means "return to the caller
as soon as possible". When you are waiting for event,
"as soon as possible" doesn't exist. `coopth_wait()`
goes down to `sigsuspend()`, which can kinda be
awaken by an event, so it shouldn't over-wait.
