### ISSUE TITLE
Display open + executing files on exception

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#68]
#64 and exceptions caused by programs run *inside* dosemu can be tricky to track down, it could be a lot easier if currently open executables, loading devices drivers and normal files could be displayed on exception.

(Also - display the exception info in the console - e.g. this bit):

```
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

Invalid Opcode at 0024 027B 3246 1357 906D 0008 0000 9DE2 0000 2178 A8EA 0000 027B
```

Some examples:

error caused when loading device driver ems.sys in config.sys:
```
Last executed:
loading device driver:   ems.sys

open files:
config.sys
ems.sys
```

error caused loading command.com
```
Last executed:
command.com

open files:
command.com
```

more complex example - user has run '4dos.exe', then in there run 'qbasic.exe', loaded gorrilla and somehow caused an exception:

```
Last executed:
command.com -> 4dos.exe -> qbasic.exe

open files:
gorilla.bas
```

**Comment by stsp** [comment]
This is not what dosemu can do - please ask the
FreeDOS ppl for help (invalid opcode also comes
from FreeDOS). dosemu does a horrible heuristic
to even try to display the last started program in
an X window title - it is already more than it could
reasonably do on that front.
Note: when dosemu prints something, you see that
on a terminal or a log, not on a DOS window.
