### ISSUE TITLE
[INFO] MS-DOS 7.0 Boot message string

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#681]
I stumbled across this little bit of code whilst poking about in @ecm-pushbx ldebug which seems to explain the meaning of the four bytes preceding the MS-DOS 7.0 boot block message string [msg.asm](https://bitbucket.org/ecm/ldebug/src/6f1572b48e81e8b33525c15e50f8e33ae17142c7/source/msg.asm?fileviewer=file-view-default#msg.asm-908). 
Here's the place in fatfs.c where it's used by Dosemu https://github.com/stsp/dosemu2/blob/0e1cff8a8f71cf5cdd4ce008795b7ba706c8c6b9/src/base/misc/fatfs.c#L1865-L1880

So it seems like there may be other messages to be added and the correct offsets calculated.

**Comment by stsp** [comment]
Very interesting indeed!
Since there is no any notion of message ID, I
suppose exactly these 4 messages should be
there, exactly in that order.
Currently we don't provide any, so does the
DOS-7 display garbage when printing of one
of those? It looks a bit difficult to provoke any
of them to trigger...

**Comment by andrewbird** [comment]
Here's a dump of a real MS-DOS 7.0 boot block starting at the position referenced in 0x1ee/0x1ef
~~~
000180 03 18 01 27 0d 0a 49 6e 76 61 6c 69 64 20 73 79  >...'..Invalid sy<
000190 73 74 65 6d 20 64 69 73 6b ff 0d 0a 44 69 73 6b  >stem disk...Disk<
0001a0 20 49 2f 4f 20 65 72 72 6f 72 ff 0d 0a 52 65 70  > I/O error...Rep<
0001b0 6c 61 63 65 20 74 68 65 20 64 69 73 6b 2c 20 61  >lace the disk, a<
0001c0 6e 64 20 74 68 65 6e 20 70 72 65 73 73 20 61 6e  >nd then press an<
0001d0 79 20 6b 65 79 0d 0a 00 49 4f 20 20 20 20 20 20  >y key...IO      <
0001e0 53 59 53 4d 53 44 4f 53 20 20 20 53 59 53 80 01  >SYSMSDOS   SYS..<
0001f0 00 57 49 4e 42 4f 4f 54 20 53 59 53 00 00 55 aa  >.WINBOOT SYS..U.<
~~~

So it seems like
- message 1 is `Invalid system disk` starting at 0x184 (0x181+0x3) terminated with 0xff
- message 2 is `Disk I/O error' starting at 0x19a (0x182+0x18) terminated with 0xff
- message 3 references message 1 data i.e. at 0x184 (0x183+0x1)
- message 4 is `Replace the disk, and then press any key` starting at 0x1ab (0x184+0x27) terminated with 0x00

**Comment by stsp** [comment]
Well, this is pretty clear from an asm file you referenced. :)
All 4 messages in that order are there.

**Comment by stsp** [comment]
I was wondering what happens if dos-7 is
booted from our fatfs.c where such messages
are missing. Is there any observable problem?

**Comment by andrewbird** [comment]
I think I managed to trigger printing of one message a long while back when testing it out. I think I did it by removing `msdos.sys` and disabling the dosemu check for its existence. I suspect there may have been one or more non printable characters prepended to the message string.

**Comment by stsp** [comment]
So it took the msg not from the boot sector after all?

**Comment by andrewbird** [comment]
No, I'm saying that it did print the message from the boot sector, but it wasn't shown quite as was expected. Here's the dosemu boot block
~~~
000040 b8 fd 80 cd e6 00 00 00 04 03 02 01 0d 0a 53 6f  >..............So<
000050 72 72 79 2c 20 63 6f 75 6c 64 20 6e 6f 74 20 6c  >rry, could not l<
000060 6f 61 64 20 61 6e 20 6f 70 65 72 61 74 69 6e 67  >oad an operating<
000070 20 73 79 73 74 65 6d 20 66 72 6f 6d 0d 0a 2f 63  > system from../c<
000080 6c 69 65 6e 74 73 2f 63 6f 6d 6d 6f 6e 2f 64 6f  >lients/common/do<
000090 73 65 6d 75 32 2e 67 69 74 2f 74 65 73 74 2d 69  >semu2.git/test-i<
0000a0 6d 61 67 65 64 69 72 2f 64 58 58 58 58 73 2f 63  >magedir/dXXXXs/c<
0000b0 0d 0a 50 6c 65 61 73 65 20 74 72 79 20 74 6f 20  >..Please try to <
0000c0 69 6e 73 74 61 6c 6c 20 46 72 65 65 44 4f 53 20  >install FreeDOS <
0000d0 66 72 6f 6d 20 64 6f 73 65 6d 75 2d 66 72 65 65  >from dosemu-free<
0000e0 64 6f 73 2d 2a 2d 62 69 6e 2e 74 67 7a 0d 0a 0d  >dos-*-bin.tgz...<
0000f0 0a 50 72 65 73 73 20 61 6e 79 20 6b 65 79 20 74  >.Press any key t<
000100 6f 20 72 65 74 75 72 6e 20 74 6f 20 4c 69 6e 75  >o return to Linu<
000110 78 2e 2e 2e 0d 0a 00 00 00 00 00 00 00 00 00 00  >x...............<
~~~

0x48 is where the message structure starts and doing the same calculation as I did before with the real boot.blk I get (0x49+0x04) = '0x4d'. So I think the first message will get printed okay except that first 0x0d will be missing. Further strings will not be processed as the message is terminated with 0x00 indicating it's is the last message.

I'm not sure how to get DOS to print either of the other messages. but it seems that the offset values chosen all point to the same string. I think the original code in fatfs_boot.S used these offsets before I converted it to be done in 32bit code, so I doubt it's just pure chance that they are what they are. 
```asm
/*
 * Currently this sequence is ignored in fatfs.c as we are unable to trigger
 * MS-DOS 7.10 to print it to confirm it's actually required. After checking
 * over 40 different boot blocks I cannot find this sequence occurring so I
 * doubt the actual values are significant. If subsequently we find that a
 * failing MS-DOS 7+ boot is printing our failure message with five bytes
 * missing off the front we can investigate adjusting the string address for
 * MS-DOS 7+ in fatfs.c and reenable this if necessary.
 *
 * 5 magic bytes (for IO.SYS compatibility) :-)
 *
	.byte	4, 3, 2, 1, 13
 */
```

I also note that there's a note about the value to specify the message structure start
```C
-      /*
-       * IO.SYS normally re-uses the boot block's error message. We
-       * could give it a distinct one here (simply have t_o point to it).
-       *
-       * But don't forget, it's not a simple ASCIIZ string!!!
-       *
-       * NOTE: There is a discrepancy between IO.SYS's and the bootblock's
-       * interpretation of this address. IO.SYS expects t_o to be
-       * relative to 0, but the value actually stored is relative to 0x7c00.
-       * (Leading IO.SYS to display no error message.)
-       * I will assume IO.SYS to be correct for now.
-       */
```
And we maintain that value even today, but I see from the original MS-DOS 7.0 boot block above that doesn't seem to be correct, yet it works. (see values in 0x1ee/0x1ef)

**Comment by andrewbird** [comment]
I don't seem to be able to trigger printing of the message, I tried
- disabling dosemu's check for `msdos.sys` and removing the file
- creating empty `msdos.sys` and setting permissions 000
- deleted `command.com`
- added `shell=b:\command.com` to `config.sys`

Ideas?

**Comment by stsp** [comment]
I mean, if there were a few non-printable
chars but then the valid msg, then it was
definitely not taken from boot sector, as
we don't seem to put it there?

**Comment by andrewbird** [comment]
With this patch I can make it print the message
```C
diff --git a/src/base/misc/fatfs.c b/src/base/misc/fatfs.c
index 128ac8c5a..aaa2d67a3 100644
--- a/src/base/misc/fatfs.c
+++ b/src/base/misc/fatfs.c
@@ -1832,6 +1832,8 @@ void mimic_boot_blk(void)
   dos_read(fd, loadaddress, size);
   close(fd);
 
+  unlink(f->obj[1].full_name);
+
   SREG(cs)  = seg;
   LWORD(eip) = ofs;
 }
@@ -1876,6 +1878,10 @@ void build_boot_blk(fatfs_t *f, unsigned char *b)
   /* add the boot block signature */
   b[0x1fe] = 0x55;
```
![msg1](https://user-images.githubusercontent.com/220835/46569444-106c5500-c94d-11e8-9089-e1014c494479.png)

Also by tweaking each of the offsets until the printed string changed I can see that in this instance it's the second message that is being printed, which would normally be `Disk I/O error`.

I'm not sure if there's anything necessary to change here, except perhaps revising the commentary?

**Comment by stsp** [comment]
But I dont remember dosemu to support
any halting. This all is very suspecious.
Why do you think that dos prints this?

**Comment by ecm-pushbx** [comment]
The four prefix bytes should be 3,2,1,0 to display the same message correctly for all offsets, including the first CR. As the message is 0-terminated, it will always be taken as the last one. As Andrew wrote, "Further strings will not be processed as the message is terminated with 0x00 indicating it is the last message."


Regarding this:

```
-       * NOTE: There is a discrepancy between IO.SYS's and the bootblock's
-       * interpretation of this address. IO.SYS expects t_o to be
-       * relative to 0, but the value actually stored is relative to 0x7c00.
-       * (Leading IO.SYS to display no error message.)
-       * I will assume IO.SYS to be correct for now.
```

See the comment in https://bitbucket.org/ecm/ldebug/src/0e0dd296a1eb1bea9fb5f0176c59c93a9e5283a1/source/boot.asm#lines-2052 as follows:

```
		; this pointer points to the MS-DOS 7 message table.
		; note that in actual MS-DOS 7 boot sectors, this value is
		; eg 17Fh, which is incorrectly used with the boot sector's
		; ss to load the table into the initial loader.
```

> I don't seem to be able to trigger printing of the message, I tried
> 
> * disabling dosemu's check for msdos.sys and removing the file
> * creating empty msdos.sys and setting permissions 000
> * deleted command.com
> * added shell=b:\command.com to config.sys
> 
> Ideas?

MSDOS.SYS isn't used by MS-DOS 7/8 booting at all, only later on (and then optionally) to load settings from it. COMMAND.COM is loaded much later (after CONFIG processing) so an error doesn't lead to the loader message table to be used.

You can patch things (or use a debugger to simulate the same) so that the disk reads done in the early loader portion (first 2048 bytes of IO.SYS, equivalent to my ldosboot's iniload) fail, in which case the error handler in that early loader is used. Disk reads are retried 5 times by that loader, so you need to fail the reads repeatedly.

Another way to cause an error during the early loader's run is to corrupt the signature "MS" at offset 7FEh (just below 2 KiB). This is a simplistic detection of whether the full early loader was loaded. (MS-DOS 7 boot sectors load a contiguous 4 sectors, assumed to be at least 512 bytes in size, but do not use the FAT at all. So if the file is fragmented in the first 2 KiB, the early loader isn't fully loaded.)

> MS-DOS 7+ prints the message stored in the boot block and pressing any key does cause the window to close, which I presume is because DOS halts the PC.

After displaying the error messages, the early loader calls Int16.00, resets the interrupt 1Eh vector to the original value passed on the stack from the boot sector loader, then calls Int19. I expect that this should restart the boot process.

**Comment by ecm-pushbx** [comment]
> MS-DOS 7+ prints the message stored in the boot block and pressing any key does cause the window to close, which I presume is because DOS halts the PC.

If you observe this when applying your "unlink(f->obj[1].full_name);" patch, perhaps dosemu exits when it can't find that file when restarting the boot process?

**Comment by ecm-pushbx** [comment]
> The four prefix bytes should be 3,2,1,0 to display the same message correctly for all offsets, including the first CR.

Actually, none of the displacements are allowed to be 0, because the relocation of the message table treats the whole table as one ASCIZ string, terminating with the first zero byte.

That's why the assembly code quoted shows 4,3,2,1,13. The 13 is just filler to avoid a displacement of 0. So I'd suggest "\x04\x03\x02\x01\xFF", which is slightly clearer.

**Comment by andrewbird** [comment]
> Why do you think that dos prints this?

I'm sure DOS prints this, the proof is that changing the displacements to 
```C
snprintf((char *)b + t_o, eos - t_o, "\x04\x06\x02\x01" MSG_F, f->dir);
```
cause the printed string to start at the first `r` in `Sorry` rather than the LF.

I'm thinking that there's probably a couple of things to do here
- add a 0xff filler byte into the start of the string as per @ecm-pushbx suggestion
- tidy up the commentary to explain properly what's happening based on text in ldebug

> If you observe this when applying your "unlink(f->obj[1].full_name);" patch, perhaps dosemu exits when it can't find that file when restarting the boot process?

~~~
ERROR: Drive unbootable, exiting
~~~
Yes I'm embarrassed to say I missed that and had presumed it was DOS doing the termination :smile:

**Comment by andrewbird** [comment]
Following @ecm-pushbx suggestion about corrupting the 'MS' signature I tweaked the loader to only load 2 sectors
```C
diff --cc src/base/misc/fatfs.c
index 7b1e90d46,dc154a16a..000000000
--- a/src/base/misc/fatfs.c
+++ b/src/base/misc/fatfs.c
@@@ -1610,7 -1610,7 +1610,7 @@@ void mimic_boot_blk(void
        seg = 0x0070;
        ofs = 0x0200;
        loadaddress = SEGOFF2LINEAR(seg, 0x0000); // different to cs:ip
--      size = 4 * SECTOR_SIZE;
++      size = 2 * SECTOR_SIZE;
  
        LWORD(ebp) = sp = 0x7c00;
        pushw(0, sp, (d_o >> 16));          // DX passed on the stack
```

This triggered the message display without needing to delete the file and cause Dosemu to error. Now the behaviour on keypress is as expected
![msg2](https://user-images.githubusercontent.com/220835/46573794-09b40100-c992-11e8-8666-fdca749b63b1.png)

**Comment by ecm-pushbx** [comment]
I extended the comment in msg.asm to reflect the fact that the table is terminated by the first zero byte, in https://bitbucket.org/ecm/ldebug/commits/839825a41387b6e6a58be6cde3b1b59b1fe01164
