### ISSUE TITLE
Crash with 'net start'

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#685]
**Describe the bug**
I hadn't used dosemu2 on this system in quite a while. I just compiled the latest git and it crashes when I run it with my existing files in ~/.dosemu.

**To Reproduce**
It appears some networking needs to be installed to reproduce this. This installation is very old, so I don't remember exactly what I had been doing. Let me know is the stacktrace is not enough or if this may not even be a bug.

**Expected behavior**
No crash.

**Attach the log**
It is located in ~/.dosemu/boot.log
[boot.log](https://github.com/stsp/dosemu2/files/2470210/boot.log)

**Comment by andrewbird** [comment]
Looks like `select_drive()` asserted when called with unknown (to us) redirector function 0x80. RBIL shows this http://www.ctyme.com/intr/rb-4355.htm. I wonder what the correct response to that call should be?

**Comment by stsp** [comment]
Please attach the `-D9+Dd` log.
I'd like to know the function that was used.

**Comment by jschwartzenberg** [comment]
Here is it:
[boot.log](https://github.com/stsp/dosemu2/files/2470478/boot.log)

**Comment by stsp** [comment]
OK, Andrew already new its 0x80. :)
How?

**Comment by andrewbird** [comment]
gdb in the first log
~~~
#9  0x000055e062ed4ccb in select_drive (drive=<synthetic pointer>, 
    state=0x55e063811960 <vm86u>) at mfs.c:552
        dd = <optimized out>
        fn = 128
~~~

**Comment by andrewbird** [comment]
@jschwartzenberg do you already have some TSR loaded that should provide the remote drive functions for `net start`?

**Comment by stsp** [comment]
> It seems there are other functions to int2f/11xx that we don't support, so perhaps
> it wasn't wise for me to assert() on unknowns?

Sure, never assert on user's input.
Just when there is a software bug.

**Comment by andrewbird** [comment]
@jschwartzenberg could you test the branch in the PR please? It might solve things for you or just delay the issue. I would be nice to know what DOS redirector the 'net start' is expecting to communicate with, too?

**Comment by jschwartzenberg** [comment]
At least the crash is gone. The output of `net start` is `The command completed successfully.". I don't think it could really work though, I do not really remember why I had this installed. I think I tried to find out whether there was a driver that could somehow work with dosemu included with that stack.

**Comment by andrewbird** [comment]
Does `net view` show anything?

**Comment by jschwartzenberg** [comment]
![dosemu-net-use](https://user-images.githubusercontent.com/877112/46893061-ed233780-ce6f-11e8-9cec-41a6ca612d70.png)

**Comment by andrewbird** [comment]
As a curiosity I was hoping that `net view` might show the lredired disks, but since you haven't got the underlying network running I suppose you don't get that far. So I guess no crash is the best we can hope for here, thanks for testing. :smile:

**Comment by jschwartzenberg** [comment]
Yep, I think in the end I couldn't find any ODI/NDIS driver that supported either going via a packet driver or a serial/parallel port connection as I wanted to try the included IP+TCP stack. Maybe the SMB part could run on top of dosemu's IPX support, but that would seem quite useless.

**Comment by stsp** [comment]
What was supposed to work here?
Could you briefly explain?
The error on a screen-shot says IPX is
needed, and we have one (or even two).

> Maybe the SMB part could run on top of dosemu's IPX support, but that would seem quite useless.

Do you want to access network drives via IPX?
Why useless?

**Comment by andrewbird** [comment]
@jschwartzenberg could you let me know which version of Lan Manager this is and if from the internet where you got it please?
