### ISSUE TITLE
FDPP plugin not finding fdppkrnl.sys

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#688]
**Describe the bug**
When using fdppkrnl.sys and no kernel.sys fatfs says drive is not bootable

**To Reproduce**
I added the following patch that shows the name is missing
```C
index f6a160432..6d9ed32cb 100644
--- a/src/base/misc/fatfs.c
+++ b/src/base/misc/fatfs.c
@@ -882,6 +882,8 @@ void scan_dir(fatfs_t *f, unsigned oi)
   struct dirent **dlist;
   int num;
 
+  fatfs_msg("scan_dir: fdpp_name is '%s'\n", sfiles[FDP_IDX].name);
+
   // just checking...
   if(!o->is.dir || o->size || !o->name || o->is.scanned) {
     fatfs_msg("scan_dir: oops #1\n");
```
I also checked the name is defined when building fdpp lib
~~~
clang++ -std=c++11 -iquote /clients/common/fdpp.git/fdpp/../hdr -Wall -c -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-exceptions -fno-threadsafe-statics -fno-rtti -fpic -Wno-format-invalid-specifier -Wmissing-prototypes -ggdb3 -O2 -DI386 -DWITHFAT32 -I . -I /clients/common/fdpp.git/fdpp/../kernel/ -I /clients/common/fdpp.git/fdpp -DDATADIR=/usr/local/share/fdpp -DKRNL_NAME=fdppkrnl.sys -o objhlp.o /clients/common/fdpp.git/fdpp/objhlp.cpp
clang++ -shared -Wl,-Bsymbolic -Wl,--build-id=sha1 -static-libgcc -o libfdpp.so blockio.o break.o chario.o dosfns.o dsk.o error.o fatdir.o fatfs.o fattab.o fcbfns.o inthndlr.o ioctl.o memmgr.o lfnapi.o newstuff.o network.o nls.o strings.o sysclk.o systime.o task.o config.o initoem.o main.o inithma.o dyninit.o initdisk.o initclk.o prf.o smalloc.o dosobj.o farhlp.o thunks.o objhlp.o
~~~

**Expected behavior**
To boot with fdpp.
I don't understand how it works for you unless you are installing the kernel file as kernel.sys?

**Attach the log**
~~~
fatfs: init: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c                 
fatfs: Using FAT12, sectors count=20791                                         
fatfs: new_obj: created obj 0 (1 left)                                          
fatfs: init: volume label set to "DXXXXS C   "                                  
fatfs: scan_dir: fdpp_name is ''                                                
fatfs: scan_dir: reading "/clients/common/dosemu2.git/test-imagedir/dXXXXs/c"   
fatfs: full_name: 0 = "/clients/common/dosemu2.git/test-imagedir/dXXXXs/c/"     
fatfs: system files not found!                                                  
fatfs: system type is "Non-system partition" (0x0)                              
fatfs: full_name: 0 = "/clients/common/dosemu2.git/test-imagedir/dXXXXs/c/boot.blk" (cached)
fatfs: fatfs: boot block generated                                              
~~~

**Comment by andrewbird** [comment]
Okay it seems that because I didn't install fdpp, the kernel name is not set in the plugin constructor
```C
diff --git a/src/plugin/fdpp/fdpp.c b/src/plugin/fdpp/fdpp.c
index 94ec9a862..644028b1e 100644
--- a/src/plugin/fdpp/fdpp.c
+++ b/src/plugin/fdpp/fdpp.c
@@ -142,6 +142,7 @@ CONSTRUCTOR(static void init(void))
        const char *fdkrnl = FdppKernelName();
        const char *fdpath = assemble_path(fddir, fdkrnl, 0);
        if (access(fdpath, R_OK) == 0) {
+           error("fdpp constructor name is '%s'\n", fdkrnl);
            strcpy(fdpp_krnl, fdkrnl);
            strupper(fdpp_krnl);
            fddir_boot = strdup(fddir);
```
Message is never shown.

Why is the kernel name conditional on the fdpplib being installed?

**Comment by stsp** [comment]
If you do `make install`, things will work.
As you don't do that, the path hardcoded in
fdpp library is not valid. I'll think about moving
this path to pkgconfig.

**Comment by stsp** [comment]
OTOH this is not a bug.

**Comment by stsp** [comment]
> Why is the kernel name conditional on the fdpplib being installed?

Because install.c does never install fdppkrnl.sys.

**Comment by stsp** [comment]
You can change pathes in fdpp/defs.mak

**Comment by andrewbird** [comment]
Mmm, yes I understand it's not a bug per se, but it seems very difficult to avoid having to follow the dosemu/fdpp idea of how my drives should be configured.


Doing this allows the boot to proceed.
```C
diff --git a/src/plugin/fdpp/fdpp.c b/src/plugin/fdpp/fdpp.c
index 94ec9a862..fdeb21cbf 100644
--- a/src/plugin/fdpp/fdpp.c
+++ b/src/plugin/fdpp/fdpp.c
@@ -141,9 +141,11 @@ CONSTRUCTOR(static void init(void))
     if (fddir) {
        const char *fdkrnl = FdppKernelName();
        const char *fdpath = assemble_path(fddir, fdkrnl, 0);
+
+       strcpy(fdpp_krnl, fdkrnl);
+       strupper(fdpp_krnl);
+
        if (access(fdpath, R_OK) == 0) {
-           strcpy(fdpp_krnl, fdkrnl);
-           strupper(fdpp_krnl);
            fddir_boot = strdup(fddir);
        }
     }
```

No worries :smile:

**Comment by stsp** [comment]
> Mmm, yes I understand it's not a bug per se, but it seems very difficult
> to avoid having to follow the dosemu/fdpp idea of how my drives should be configured.

You mean a non-standard drives layout?
Please stop breaking things! :)
I'll friendly let you avoid `make install` by the use
of pkgconfig for all pathes, but if you fiddle with
drives layout, don't count on me any more. :)

**Comment by stsp** [comment]
> Doing this allows the boot to proceed.

You will not need to do this if the pathes are
populated via pkgconfig. You'll have to hack
only the .pc file, which is what you already do...

**Comment by andrewbird** [comment]
> You mean a non-standard drives layout?

From that I guess you mean the @stsp standard, not the plain 'I have only a C: drive, boot files in its root' standard?

Don't waste too much time on tweaking it for me, I'll get used to it, I'm sure!

**Comment by stsp** [comment]
Drive C: is exclusively for the user.
Do whatever you want with it.
But don't change other drives, and fdpp
will be fine (even w/o make install, in the future).

**Comment by stsp** [comment]
Now loading directly from the buld dir should work.
In debug builds only, but I made them default.
Does this fit your needs?

**Comment by andrewbird** [comment]
Thanks, that seems to fix the paths for me. I have another problem: I get a Dosemu crash as I did earlier but wasn't sure if it were my hacking attempts to get it booting in my testdir

**Comment by stsp** [comment]
What crash?

**Comment by andrewbird** [comment]
I opened #689 now

**Comment by stsp** [comment]
I reverted the previous hacks to this.
You can now use `FDPP_KERNEL_DIR`
var to specify the alternative fdpp location.
