### ISSUE TITLE
lredir doesn't check cds flags

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#695]
Currently as we know, the redirector initialization
may fail if we don't have the right command.com.
For example comcom32 doesn't support ae00 yet.
But lredir/lredir2 displays the redirections as if they
are all there, while there are none.
They should check cds for every drive, and if the
redirection is not there, write `(disabled)` suffix, or
something like that.
This problem is not present in dosemu1 for hundreds
of different reasons, one of which being, IIRC, that
mfs always re-calculated the redirections at run-time,
depending on CDS flags. We don't have that code,
and the code that redirects on file open was also
removed, etc etc. Basically there is no way back, we
just need to finish the new redirector model properly.

So for now lredir2 should be updated to check cds.

**Comment by andrewbird** [comment]
Okay will do, but I think it's best that the redirector int2f/11/1e `GetRedirection()` look at the CDS flags and set a bit in CX (next to readonly) for lredir(2) to display.

**Comment by stsp** [comment]
Thanks, would be cool if you do! :)

**Comment by stsp** [comment]
As you probably know, I am at the last
stages of stabilizing the fdpp+comcom32
combo. With the latest patches I was able
to run windows properly, and even mouse
works (which required quite a work to make
int33 revectored and modify emufs.sys and
dpmi accordingly).
The only remaining problem is redirector,
which in that combination doesn't work at all.
So I am going to concentrate on that.

Btw, the interesting thing happened when I
was debugging the windows startup on fdpp.
When fdpp is crashing, it stops dosemu with
the message "fdpp crashed, press any key
to exit". When that msg appears, windows
GUI freezes, but the windows's mouse cursor
was still moving and could even take a form
of hour glasses. So the amazing (to me) thing
was that while coopth stopped the DOS thread,
it was still allowing the higher priority windows
threads to run, so mouse still worked.

**Comment by andrewbird** [comment]
There seems to be problem with GetCDSInDOS() on FDPP, I get different values for the same drive
~~~
MFS: cds from GetCDSInDOS is 0xb00e4000                                         
MFS: cds from drive_cds is 0xb008b840
~~~

The value that  drive_cds returns is the one that DOS is looking at, as if you disable the call to calculate_drive_pointers() DOS no longer sees the drive as redirected.

**Comment by stsp** [comment]
How can I reproduce this?

**Comment by andrewbird** [comment]
I also notice that GetCDSInDOS() always returns the same value no matter if drive is C: or D: 
~~~
MFS: cds from GetCDSInDOS is 0xb00e4000
MFS: cds from GetCDSInDOS is 0xb00e4000
MFS: cds from GetCDSInDOS is 0xb00e4000
MFS: cds from GetCDSInDOS is 0xb00e4000
~~~

**Comment by andrewbird** [comment]
Just add these lines and check the log
```C
index 82bdc3781..3c278e823 100644
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -1662,6 +1662,8 @@ calculate_drive_pointers(int dd)
 
   cds = drive_cds(dd);
 
+  Debug0((dbg_fd, "cds from drive_cds is %p\n", cds));
+
   /* if it's already done then don't bother */
   if ((cds_flags(cds) & (CDS_FLAG_REMOTE | CDS_FLAG_READY)) ==
       (CDS_FLAG_REMOTE | CDS_FLAG_READY))
@@ -2536,6 +2538,8 @@ static int RedirectDisk(struct vm86_regs *state, int drive, char *resourceName)
     return FALSE;
   }
 
+  Debug0((dbg_fd, "cds from GetCDSInDOS is %p\n", cds));
+
   path[0] = 0;
   path_to_ufs(path, 0, &resourceName[strlen(LINUX_RESOURCE)], 1, 0);
 
@@ -2546,6 +2550,7 @@ static int RedirectDisk(struct vm86_regs *state, int drive, char *resourceName)
     return FALSE;
   }
 
+
   calculate_drive_pointers(drive);
 
   cds_flags(cds) = CDS_FLAG_READY | CDS_FLAG_REMOTE | CDS_FLAG_NOTNET;
```

**Comment by stsp** [comment]
Looking at fdpp sources, this boils down
directly to `get_cds_unvalidated()`, so I wonder
what could go wrong here.

**Comment by andrewbird** [comment]
ajb@polly:/clients/common/dosemu2.git$ grep 'cds from GetCDSInDOS' test.log
Same test done on MS-DOS 3.31
~~~
MFS: cds from GetCDSInDOS is 0xb008dde2
MFS: cds from GetCDSInDOS is 0xb008de33
MFS: cds from GetCDSInDOS is 0xafffbe72
MFS: cds from GetCDSInDOS is 0xafffbec3
~~~

See the CDS move between line 2  and 3.
See the 0x51 byte sizeof CDS entry between 1 and 2 / 3 and 4

**Comment by andrewbird** [comment]
`get_cds()` should suffer the same problem as `get_cds_unvalidated()` on FDPP.

**Comment by stsp** [comment]
```
ERROR: cds from drive_cds is 0x7f9390f837a0
ERROR: cds from drive_cds is 0x7f9390f837f8
ERROR: cds from drive_cds is 0x7f9390f83850
ERROR: cds from drive_cds is 0x7f9390f838a8
```

This is a log from `mfs.c:1665`

**Comment by andrewbird** [comment]
That's correct the CDS entry size on that version of the redirector is 0x58, what does the GetCDSInDOS() value show in the same log?

**Comment by stsp** [comment]
```
ERROR: cds from GetCDSInDOS is 0x7f7b21fdc000
ERROR: cds from drive_cds is 0x7f7b21f837a0
ERROR: cds from GetCDSInDOS is 0x7f7b21fdc000
ERROR: cds from drive_cds is 0x7f7b21f837f8
ERROR: cds from GetCDSInDOS is 0x7f7b21fdc000
ERROR: cds from drive_cds is 0x7f7b21f83850
ERROR: cds from GetCDSInDOS is 0x7f7b21fdc000
ERROR: cds from drive_cds is 0x7f7b21f838a8
```

What???

**Comment by andrewbird** [comment]
Yep that's what I'm seeing - constant value from `GetCDSInDOS()`

**Comment by stsp** [comment]
Well, so what, wrong format char...
Just replace `%p` with `%s` and see this:
```
ERROR: fdpp booting, this is very experimental!
ERROR: cds from GetCDSInDOS is C:
ERROR: cds from GetCDSInDOS is D:
ERROR: cds from GetCDSInDOS is E:
ERROR: cds from GetCDSInDOS is F:
```

**Comment by andrewbird** [comment]
Yes it looks better, but I can't believe it's correct.
- The location was the same each time it was called with %p whereas FreeDOS 1.20 and MS-DOS 3.31 varied as expected. 
- The root path is missing
- The %p value should be the name as that retrieved by `drive_cds()` for the same drive.
- The flags are wrong AND not even the right bits are set for physical drive (JOIN???)

Since we use GetCDSInDOS() elsewhere in Dosemu, I think what you are seeing when using %s is a write of `Drive:` to a fixed location somewhere immediately prior to us querying it.

**Comment by stsp** [comment]
Could you please be more specific, I
guess you are pointing to flags mismatch?

**Comment by andrewbird** [comment]
Flags wrong, pointer value unchanging, and when you change format to string you only see C: not c:\, plus same code works on freedoms and msdos.

**Comment by stsp** [comment]
Confirmed, investigating.

**Comment by stsp** [comment]
I applied the fix, please retry.

**Comment by andrewbird** [comment]
Thanks that works well. As a test I commented out `calculate_drive_pointers()`, ran the tests and nothing broke, so that's certainly fixed. Note: `calculate_drive_pointers()` can not be removed until we can stop lfn.c using CDS directly.
I'm just revising the patch in my mfs22 branch, will post a PR shortly.

**Comment by andrewbird** [comment]
It would be interesting for you to run your FDPP/comcom/windows test again, as I'm sure that `GetCDSInDOS()` problem would have seriously screwed things up?

**Comment by stsp** [comment]
It still works, didn't regress. :)
Since its running w/o redirector anyway,
there should be no change. But overall
this was a very important fix indeed.

**Comment by andrewbird** [comment]
Yes, but I wondered if it would work with redirector now?

**Comment by andrewbird** [comment]
Oh only that, I figured you had more fundamental problems. Did you try using the post_boot() hook you added for DOS < 3.30 just to see it works?

**Comment by stsp** [comment]
> Oh only that, I figured you had more fundamental problems.

All of them are fixed within this week.
Only this remained.

> Did you try using the post_boot() hook you

But it works fine even w/o the redirector now.
Yes if you edit some file in notepad, the edits
are not saved etc. And yet it all works. :)

**Comment by stsp** [comment]
I had to revert this patch as it was wrong.
See commit msg.
Could you please re-do it?

**Comment by andrewbird** [comment]
So I'm looking to test the Netware 4.x client and its `netuser` tool so I may see how it interacts with the redirector. Do you know the name of the netware archive that contains it, as it's not with the 16bit client tools (VLM etc)?

**Comment by andrewbird** [comment]
I found v4.2, but can't get the netuser command to query the redirector without being logged in to netware server, but not sure I can be bothered to set one up yet.

**Comment by stsp** [comment]
Is this all just for this 0x80 flag?

**Comment by andrewbird** [comment]
Yeah, sad isn't it.

**Comment by stsp** [comment]
I think you can just ignore that.

**Comment by stsp** [comment]
So how about ignoring this silly flag?
If we take care about every small detail
found in a legacy code, we'll never release
any beta, and I really hope we can do so
this year.

**Comment by andrewbird** [comment]
I've been playing with pcgeos to reproduce the effect found by @bolle732 in #710 as at the moment it's the only client I know of that uses int21/5f02 and I can get working. BTW I wanted to try the MS client. but that needs an NDIS network driver. I looked for a Packet -> NDIS shim like PDEther does Packet -> ODI and didn't find one, I don't suppose you know of any? Anyway currently I have a dosemu crash with pcgeos immediately after the drive is restored, so I'm trying to track that down first.
Yes I'd be happy to drop the 0x80 bit, at least then if someone is bothered by the problem we should be able to get a proper Netware test case, and if the Netware client sets the signature perhaps conditionally set it.

**Comment by stsp** [comment]
My memory may be wrong, but I seem to
recall msclient worked under dosemu. You
probably can't get ndis, but IIRC msclient
supported other backends via some setup
program. It was like 15 years since I tried that,
so maybe this is all wrong.

Crash of pcgeos is usually cured by `STACKS=0`
in config.sys

**Comment by andrewbird** [comment]
> but IIRC msclient
supported other backends via some setup
program.

I'll have a further look for this then.

> Crash of pcgeos is usually cured by STACKS=0
in config.sys

I'll try that, the strange thing is that only in the case of network drive restoration does it crash, whereas in normal operation it works fine for me.

**Comment by stsp** [comment]
https://forums.techguy.org/threads/networking-dos-operating-system.855447/
```
 ftp://ftp.microsoft.com/bussys/clients/msclient/dsk3-2.exe
Extract it into the same folder as Disk 1; there are 2 duplicate files, AVEXTRA.TXT and LICENSE.TXT. 
You can overwrite or not, they are the same file.
Then, in step 12, after removing IPX, choose TCP/IP instead of NetBEUI.
```

So my memory is not wrong on that it was configurable.
I _think_ I used IPX as a back-end. There was some major
IPX stack update in dosemu by me in that era, so maybe indeed
I was able to get the msclient running that way. Can't remember.

**Comment by andrewbird** [comment]
I just watched this https://www.youtube.com/watch?v=ngtk3vPBCRo which suggests that it's possible to use packet driver with msclient, **BUT** he has an NDIS driver in the network card directory, so I'm not really convinced he's using the packet driver. Still I'll try it after doing the dosdebug thing.

**Comment by stsp** [comment]
Would be very interesting to find more
documentation on tcpdrv.dos API than this:
http://www.delorie.com/djgpp/doc/rbinter/id/54/28.html

**Comment by stsp** [comment]
> BUT he has an NDIS driver in the network card directory, so I'm not really convinced

He is also referring to 0x60 as being a memory address...

**Comment by andrewbird** [comment]
Reading the boot messages I see the packet driver v3.40 loaded and later a v3.23 network driver, which I presume is the NDIS, so I think he's loading the packet driver unnecessarily and fooling himself that it's actually doing something.

**Comment by stsp** [comment]
Yep, at "address 0x60" that is.

There is no ndis over pkt, but if we had
a pktdrv.dos API description, we could
implement it in dosemu2.
Anyway, his video shows you can use
also ipx, netbeui and "other protocols..."

**Comment by andrewbird** [comment]
I managed to find [ndis201.txt](https://github.com/stsp/dosemu2/files/3470865/ndis201.txt) which is contemporary to the msclient. I thought if the spec were small enough (it isn't) then a built in ndis driver (just like we have for pkt) might be fairly simple. To give us a head start, source to a network card's DOS NDIS driver would be excellent, but I don't know if manufacturers ever release these things at EOL.

> Anyway, his video shows you can use
also ipx, netbeui and "other protocols..."

I can understand how IPX could work as I believe dosemu has built in IPX, but won't the other protocols require a driver too?

**Comment by stsp** [comment]
ndis is out of question even if you
find sources (very unlikely).
What we could implement is a tcpdrv.dos
API. That driver works on top of ndis
and should have a fairly small api.

Ipx can work over packet driver.

**Comment by stsp** [comment]
Your document says that it describes
only the mac driver and other document
will describe the transport driver.
This other document doesnt seem to
be available.

**Comment by andrewbird** [comment]
I found ndis201.txt via the wayback machine. If you have dead links to the tcpdrv doc, you might be able to find it there.

**Comment by stsp** [comment]
In fact, mac driver is  not that
difficult as well.
- query config from lanman
- register itself with param table
- pass the handshake with transport driver
(via the above table that also has the
handshake callbacks)
- do the data io with sg lists
- do the data and link status notifications

This is not something to write in a day,
but is not a rocket science either.

**Comment by stsp** [comment]
Btw, if you really want a short path of
getting the ndis support in - something like
20 years ago someone have posted the
NIC emulation patch to linux-msdos ML,
but no one was interested.
If you apply that patch then the native
driver may work.

**Comment by andrewbird** [comment]
I wasn't able to find that, but I did find lots of threads about people trying to do what I'm trying to do! I'm also amazed by how many people back in 200x seem to be running dosemu as root for real network card access.
I think I'm going to try the IPX method with msclient, after all I don't actually need it to mount any shares, just be able to do `net view` or `net use` etc.

**Comment by stsp** [comment]
> I wasn't able to find that

Darn, after a few hours of trying, I was about
to believe its not there indeed and my memory
is playing serious tricks with me! And right before
posting this conclusion here...
https://marc.info/?l=linux-msdos&m=96073283622906&q=p3

**Comment by andrewbird** [comment]
Well done! Interesting, how times change, now direct hardware access is pretty much unpalatable and a virtual adapter is really the only way to go. I bet Scott would be surprised if it were to become part of Dosemu now.  I could probably reintegrate it with Dosemu, but the accompanying [post](https://www.mail-archive.com/linux-msdos@vger.rutgers.edu/msg02023.html) suggests it was only 90% complete. Is TUN/TAP the way to interface it to the real world?

**Comment by stsp** [comment]
> now direct hardware access is pretty much unpalatable

It simply doesn't work these days.
Well dosemu have some kind of a PCI emulator
(thanks to Bart) that allows to pass-through PCI
configs selectively, but DMA won't work no matter
how hard you try, and IRQ support is not trivial these
days either. i.e. how would you pass the level-delivered
_shared_ IRQ? I know how hard is that because I
implemented that in a commercial emulator at work
(PCI-express provides some relief, but its still difficult).
Passing the legacy IRQs was much, much easier as
they were not shared (and were mostly level-triggered).
So pass-through on a network devices can just be forgotten,
and as you are not supposed to get the PC with ISA slots,
I'd say any pass-through with dosemu can be forgotten today.

> I bet Scott would be surprised

I bet he won't find that out. :)

> 90% complete.

That sounds still like a very good start.

> Is TUN/TAP the way to interface it to the real world?
See net/libpacket.h which provides the simple
abstraction around the supported backends
(which is basically just TAP these days, maybe
someone still uses vde too).

**Comment by stsp** [comment]
So coming back to lredir, would it be possible
to re-apply the patch?

**Comment by andrewbird** [comment]
Yep, leave it with me.

**Comment by andrewbird** [comment]
Just a heads up here. It seems that the msclient 3.0 networking clobbers the output from lredir, have to see if we can find a way to make them interoperate.
~~~
C:\>cd net
 
C:\NET>lredir
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\c\ attrib = READ/WRITE
E: = \\LINUX\FS\clients\common\dosemu2.git\test-libdir\dosemu2-cmds-0.2\ attrib = READ/WRITE
F: = \\LINUX\FS\clients\common\dosemu2.git\..\fdpp.git\fdpp\ attrib = READ/WRITE
G: = \\LINUX\FS\usr\share\comcom32\ attrib = READ/WRITE

C:\NET>startnet
 
C:\NET>SET PATH=C:\NET
 
C:\NET>C:\NET\net initialize
Microsoft NE2000 NDIS Driver
Copyright 1992 Microsoft Corporation
All Rights Reserved Version:  2.0
Microsoft DOS TCP/IP Protocol Driver 1.0a
Copyright (c) Microsoft Corporation, 1991.  All rights reserved.
Copyright (c) Hewlett-Packard Corporation, 1985-1991.  All rights reserved.
Copyright (c) 3Com Corporation, 1985-1991.  All rights reserved.
Microsoft DOS TCP/IP NEMM Driver 1.0
The command completed successfully.
 
C:\NET>C:\NET\netbind.com
MS-DOS LAN Manager v2.1 Netbind
 
C:\NET>C:\NET\umb.com
 
C:\NET>C:\NET\tcptsr.exe    
Microsoft DOS TCP/IP 1.0a
 
C:\NET>C:\NET\tinyrfc.exe
 
C:\NET>C:\NET\nmtsr.exe
 
C:\NET>C:\NET\emsbfr.exe
 
C:\NET\net start
Type your user name, or press ENTER if it is FRED:
Type your password:
There is no password-list file for FRED.
Do you want to create one? (Y/N) [N]:
The command completed successfully.
 
C:\NET>
 
C:\NET>net use
There are no entries in the list.
 
C:\NET>lredir
No drives are currently redirected to Linux.
~~~

**Comment by stsp** [comment]
What to do with this one?

**Comment by andrewbird** [comment]
Two issues here:

1. Msclient redirector would seem to be first in the queue(from memory) to process int2f/11xx, but considers itself to be authoritative and doesn't pass the call on to a following redirector. Since as far as I can tell the listing function isn't designed to allow multiple redirectors to return their results, I'm not sure much can be done about this. From comments in mfs.c it seems that in the past dosemu may have been first in the queue and played some tricks with the caller's index parameter to allow a following redirector's responses to appear in the client's list.
2. Displaying the redirection status (enabled flag, and may other stuff sometime) is Dosemu specific, the redirector should set some well known indication in its return so that the client knows whether to display the extensions or not, as it might be talking to another redirector.

**Comment by stsp** [comment]
I don't understand.
Isn't this ticket about just checking if
the CDS remote flag is consistent?

**Comment by andrewbird** [comment]
Almost, not CDS remote flag but the CDS 'ready' (sometimes called 'physical') flag. Leave it with me, I have a solution to item 2 above.

**Comment by andrewbird** [comment]
s/not CDS remote/not just CDS remote/

missed word 'just'!

**Comment by andrewbird** [comment]
Should mapping a cdrom e.g. `lredir -nC2 /tmp` automatically set the readonly option? I'm unfamiliar with Dosemu and cdroms, with my patch currently a drive mapped as above is writable.

**Comment by stsp** [comment]
No, -R is read-only.
cdrom should be R/W. but write should
return an error.
We have a bug #989 where this is not the
case if the underlying FS is R/O. For cdrom
we need to ignore R/O.
Would you like to take a look into that mess?
