### ISSUE TITLE
Thoughts about lfn.c use of CDS

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#699]
So there is now only one user of `drive_cds()` and hence the global CDS array and that is lfn.c. So I wonder if you have any thoughts of how to get rid of its use in lfn.c?
- Switching to use `GetCDSInDOS()` is not possible because as an int2f/12 based function it requires that it run with a DOS stack. The LFN code is a front end to int21 and so runs outside of DOS, conversely the redirector is called by DOS itself and hence has the DOS stack setup for it.
- Users of CDS within lfn.c are
  - `truename()`
  - `build_truename()`
  - `mfs_lfn()` for int 21 get current directory

**Comment by stsp** [comment]
IIRC we simply ignore many redirector
functions that change cds. If we implement
them, we could get all the needed info from
the `drives` array.
Also please take a look in `lfnapi.c` of freedos.
I don't yet know what it does, but if it is really an
LFN api, then there may currently unknown possibilities.

**Comment by andrewbird** [comment]
Anything that needs CDS within the redirector is fine, the only issue is LFN which runs outside of DOS.

i.e. 
(application) open() -> int21/3d -> (DOS) -> int2f/1116 (mfs.c) -> int2f/1217  okay
(application) get_lfn_curdir() -> int21/7147 -> (lfn.c)                       int2f/1217  not okay as not called from DOS

**Comment by stsp** [comment]
So what do you think about this caching
possibility? For example in `SET_CURRENT_DIRECTORY`
we could store the new CDS path.

**Comment by stsp** [comment]
> And finally I thought why do we need it

Don't we need it because we can reliably
get CDS only from redirector, but not from
LFN? Of course it would be better to call out
for LFN from within the DOS kernel, but
currently I don't know what `lfnapi.c` of freedos
does, so caching looks like a simpler possibility.

> better calculating once when we change directory rather than every time a file is looked up

Why not? But this caching is primarily for LFN,
not for redirector. Maybe it can be used in a
redirector too.
No, I don't think some app is going to patch
CDS instead of doing chdir. As dosbox authors
say, "please tell me what game does this". :)

**Comment by andrewbird** [comment]
> Don't we need it because we can reliably
get CDS only from redirector, but not from
LFN?

Yes that's true and it's my purpose for the tidy up, but I should have been more clear in my question - why does LFN need CDS and what does it use it for? One problem I have is that find the lfn.c code difficult to follow. Maybe I need to start pulling it apart and see what breaks :smile:

**Comment by stsp** [comment]
For example to check if the drive is
redirected (flags), or to translate CWD
into an LFN format. But CWD you can
get from DOS, w/o getting CDS. Whether
is redirected, can be checked via `drives`
array. So I think there are no _real_ uses.

**Comment by stsp** [comment]
`lfnapi.c` seems to be only for local fat drive
LFN support. Plus it seems to be using some
functions that are not in our git tree, like
`get_f_node()`. But it is in freedos cvs:
https://sourceforge.net/p/freedos/mailman/freedos-cvs/?limit=100&style=flat&page=6
Confused. Maybe its something very old...
I'll better exclude `lfnapi.c` from the build, it seems.

**Comment by andrewbird** [comment]
> For example to check if the drive is
redirected (flags), or to translate CWD
into an LFN format. But CWD you can
get from DOS, w/o getting CDS. Whether
is redirected, can be checked via drives
array. So I think there are no real uses.

I like this assertion, but I see some CDS usage within LFN `truename()` for SUBST and JOIN. Is there a programmatic way for an app (or in this case our lfn.c) to determine JOIN and SUBST values without looking at CDS?

**Comment by stsp** [comment]
```
INT 21 - DOS 3.1+ - IOCTL - CHECK IF BLOCK DEVICE REMOTE
        AX = 4409h
        BL = drive number (00h = default, 01h = A:, etc)
Return: CF clear if successful
            DX = device attribute word
                bit 15: drive is SUBSTituted
                bit 13: (DR DOS 3.41/5.0 local drives only) always set
                        media ID needed
                bit 12: drive is remote
                bit  9: direct I/O not allowed
```

Not sure about JOIN.

**Comment by andrewbird** [comment]
Are these statements true?:
- JOIN path is held in the CDS current path entry of the physical drive it's to map i.e. 
  command of `JOIN A: C:\\MNTPNT_A` gives cds_current_path(cds[0]) == "C:\\MNTPNT_A" with cds_flags(cds[0]) == READY|JOIN
- Since cds_current_path() is an SFN, join can only ever work with SFN paths?
- `JOIN` command would have to be aware of the LFN->SFN mangling scheme or call truename() Int 21/AX=7160h/CL=01h in order to populate the CDS current_path entry with the correct SFN.

Perhaps I should look at the `JOIN` command of FreeDOS and MS-DOS 7.x to see if they are capable of working with LFNs?

**Comment by stsp** [comment]
I don't have a lot of idea how join works
(I think what you say about cds path, is
related to subst, not join), but lfn.c seems
to be checking it only to return an error.
In which case I suppose the answer to
your questions are all No, and we don't
need to worry about join too much.

**Comment by stsp** [comment]
https://github.com/stsp/dosemu2/pull/650#issuecomment-408646366
Here I seem to claim we need to store
cds path in unc. In particular I blame
the inefficient demangling that can then
be removed. Could you please see if
this is still valid?

**Comment by stsp** [comment]
I mean put in some cache as you do now,
but in unc.

**Comment by andrewbird** [comment]
I read the issue #650 again and as ever we discussed some `truename()` -> qualify_filename(int2f/1123) migration. I'll have a play at doing that.

**Comment by stsp** [comment]
But what is the plan?
Since we have too long qualified filenames,
I think Bart was right that we can't properly
support it.

**Comment by andrewbird** [comment]
I think he's right about the basic SFN qualify filename, but I wonder if we can augment it to return LFN to our caller LFN truename. Let's see how far I get, at least it may generate some further ideas.

**Comment by stsp** [comment]
But LFN truename doesn't call qualify_filename
IIRC, or does it do so with SFN?
OK, I am puzzled, but lets see how far will you get
and whether you really see something interesting there.

**Comment by stsp** [comment]
So if LFN truename calls qualify_filename with
SFN and you try to "fix it up" by returning the LFN
to it, then I don't think this can work, for multiple
reasons. But lets see.

**Comment by andrewbird** [comment]
No, LFN truename can't call redirector functions directly, but it could call into int21/60 truename which would do it. RBIL shows no SRC string length limitations only DST at 128, but since we as dosemu lfn.c are the only caller for LFN we can return the LFN somewhere in 32bit space.

**Comment by andrewbird** [comment]
To see if things get easier and cleaner with lol etc, perhaps even reinstate join/subst support. Let's see what falls out.

**Comment by stsp** [comment]
I think some patch was applied.
