### ISSUE TITLE
DOS mouse lost

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#700]
As of c6eef28e2 there is no mouse in Norton Commander.

**Comment by stsp** [comment]
Do you still have mouse in other programs?
Do you load emufs.sys?

**Comment by severach** [comment]
Foxpro has also lost the mouse.

````
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
EMUFS host file and print access available
Kernel: allocated 46 Diskbuffers = 24472 Bytes in HMA
````

**Comment by stsp** [comment]
Seems to be working _without_ emufs.sys though, interesting.

**Comment by stsp** [comment]
Should now be fixed.
int33 needs a special fixup which I forgot to add.

**Comment by severach** [comment]
Mouse is working.

**Comment by severach** [comment]
Mouse is working.
