### ISSUE TITLE
BLASTER.COM reports "Environment too small for MIDI! (needed 20 bytes)

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#702]
BLASTER.COM reports "Environment too small for MIDI! (needed 20 bytes) while I have 886 bytes remaining.

Needless to say it doesn't set BLASTER or MIDI.

**Comment by stsp** [comment]
Quite bad practice, you removed the bug-reporting
template, but haven't provided any needed info about
reproducing the problem.
Anyway, I added more verbose error reporting, so
hope it will full-fill this gap. Please see what it says.

**Comment by stsp** [comment]
Is this report still valid?

**Comment by stsp** [comment]
Please reopen if its still a problem.
