### ISSUE TITLE
Crash if no FreeDOS found automatically ?

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#706]
**Describe the bug**
Since commit 569a672fa8a9bcb8452de3bda675847ffda32f95, dosemu2 crashes at startup.

**To Reproduce**
Setup up  a manual drive_c with hand copied FreeDOS files (kernel.sys / command.com).

**Expected behavior**
DOSEMU starts up successfully.

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/2529332/boot.log)

**Comment by stsp** [comment]
No debugging symbols found.
Please fix that.

**Comment by bolle732** [comment]
I've set "debug on":
[boot.log](https://github.com/stsp/dosemu2/files/2529867/boot.log)

Hope it's better now. Or do I have to install debug versions of system packages too?

**Comment by stsp** [comment]
Thanks, should now be fixed.
I forgot to remove freedos from install.c.
Now hope we _really_ have the freedos-less
setups. :)

> Setup up a manual drive_c with hand copied FreeDOS files (kernel.sys / command.com).

This is a still supported configuration, but
please move on to installing fdpp+comcom32.

**Comment by bolle732** [comment]
I've tested on 2 machines and it works again. Thanks a lot!
