### ISSUE TITLE
On exit shell, exit dosemu instead of displaying "missing Command interpreter" ?

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#707]
Currently, on the freedos config (not tested in fdpp), if I boot successfully, type exit:

```
C:\> exit
Bad or missing Command Interpreter: command.com /e:1024 /k d:\autoexec.bat
 Enter the full shell command line: 
```

In this case I was actually in a shell and then exited, in this case could dosemu exit instead of displaying the message ?

**Comment by stsp** [comment]
In fdpp its the same, but you can press
"^d" instead of command.com's name to
exit. I'll see about making it to exit w/o
returning to that prompt.
For freedos your best bet is to use `/P`
option which will always return back to
command.com w/o any re-asking.

**Comment by stsp** [comment]
> For freedos your best bet is to use /P

... in a `SHELL=` string, this is a command.com's option.
You can use `exitemu` to exit.

**Comment by stsp** [comment]
Are you using freecom?
IIRC you need to remove `/k xxx` to get `/p`
working - this may be a bug.
