### ISSUE TITLE
Using comcom32 breaks custom setup with 'drive_c'

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#709]
Opening the issue from comcom32 here:

https://github.com/stsp/comcom32/issues/3

Do I need to copy the content of the issue here or is linking sufficient ?

**Comment by stsp** [comment]
When I have activated comcom32 (together with fdpp), I cannot start anymore my custom setup, which has the files too in a folder named drive_c, as the default under ~/.dosemu.

Error message:
ERROR: Bootable drive not found, exiting

Renaming either ~/.dosemu/drive_c or ~/<CUSTOM>/drive_c to another name makes it work again.

The custom setup use this to start DOSEMU2:
/usr/local/bin/dosemu.bin --Fimagedir $G_DOSEMU_HOME -f $G_DOSEMU_HOME/dosemurc $@

**Comment by bolle732** [comment]
GIT has eaten away my variable `<CUSTOM>`:
> Renaming either `~/.dosemu/drive_c` or `~/<CUSTOM>/drive_c` to another name makes it work again.

From the second post:
In `dosemurc` I have specified:

`$_hdimage = "./drive_c"`

**Comment by stsp** [comment]
This is actually a dupe of #80.
I've finally made the large-scale surgery on this.
Hope it works fine now.

**Comment by stsp** [comment]
I also fixed install to respect altered hdimagedir.
It will now install into --Fimagedir.
So only the bug #215 remained from that category.

**Comment by bolle732** [comment]
That looks fine. I can have again my own "drive_c". Thanks a lot for that!

But now it looks like I MUST use the name `fdconfig.sys`. If my file is named `config.sys`, DOSEMU2 ignores it and instead it creates a symbolic link named `fdconfig.sys` and booting will fail. For that reason, I have created a symbolic link myself. DOSEMU2 still tries to create the symbolic link which produce an error message on startup, but it boot fine / correctly.

Maybe there should be a switch to disable the whole install thing for those who setup their own manual installation... I have an old (>10 years) DOSEMU1 installation where I completely removed the install process because of this. Otherwise it was impossible to automatically generate different setups. Should I put this idea to a feature issue ?

**Comment by andrewbird** [comment]
> Maybe there should be a switch to disable the whole install thing for those who setup their own manual installation...

That appeals to me too :smile:

**Comment by stsp** [comment]
Who said you should do a custom setup
with fdpp? :) There are plenty of other
doses where this works as expected.
But if you create the fdconfig symlink and
dosemu is trying to overwrite it, then
please create a bug.

**Comment by stsp** [comment]
I dont think such switch is needed.
If install is wrongly triggered and tries
to overwrite manual fdconfig.sys, we'll
fix.

**Comment by stsp** [comment]
I think the problem with custom setups was
that install.c didn't respect imagedir. But now
it does. So any custom setup with fdpp can
just be accomplished with an install procedure.
Does any one knows why this may be insufficient?
I don't want people to install fdpp by hands,
and automatic installation now works, so does
this suite everyone's needs?

**Comment by bolle732** [comment]
> I dont think such switch is needed.
> If install is wrongly triggered and tries
> to overwrite manual fdconfig.sys, we'll
> fix.

I really think an advanced switch to disable the install would be a great thing. Surely, this would never be a candidate for the default. The ones using it explicitly would now how to fix their manual setup. In my eyes, this would give a lot of freedom. It even could be declared as an unsupported feature.

Currently, it makes life more complicated due to automatically created folders, files and links in case of an error. One always have to double check and clean up his custom setups.

Will put this into a feature request.

**Comment by bolle732** [comment]
> I think the problem with custom setups was
> that install.c didn't respect imagedir. But now
> it does. So any custom setup with fdpp can
> just be accomplished with an install procedure.
> Does any one knows why this may be insufficient?

Custom setups works fine and install with fdpp is a great thing. For the standard user the right way. But the ones who like to do it by hand and knows that it could break should be able to do all by hand without hassle.

> I don't want people to install fdpp by hands,
> and automatic installation now works, so does
> this suite everyone's needs?

Beside of the ability to disable install, I don't imagine another use case at the moment.

**Comment by stsp** [comment]
> I really think an advanced switch to disable the install would be a great thing.
> Surely, this would never be a candidate for the default.

And do you really think _always_ running dosemu
with some non-default option will make you any good?
Once you forget to add it, the install will happen again,
and you says "oh shit, let me ask to make it a default".
It is much better to fix the false triggering of install, so
that you don't have to always "fight" it.

> Custom setups works fine and install with fdpp is a great thing.

People are fooling themselves when they
think they install fdpp by hands, because fdpp
is in fact `libfdpp.so`, with `fdppkrnl.sys` being
mostly a loader and some glue code. `libfdpp.so`
changes, your `fdppkrnl.sys` becames outdated
and stops working. You ask me to implement
versioning, so that it tells you when to update
`fdppkrnl.sys`... But at one point I'll say that
people demand too much for no reason. :)

**Comment by bolle732** [comment]
> People are fooling themselves when they
> think they install fdpp by hands, because fdpp
> is in fact `libfdpp.so`, with `fdppkrnl.sys` being
> mostly a loader and some glue code. `libfdpp.so`
> changes, your `fdppkrnl.sys` becames outdated
> and stops working. You ask me to implement
> versioning, so that it tells you when to update
> `fdppkrnl.sys`... But at one point I'll say that
> people demand too much for no reason. :)

I let install fdpp to its system location the normal way with "make install". Then I create a symbolic link from my custom setup to `/usr/local/share/fdpp/fdppkrnl.sys`. That works fine.

Regarding versioning, doesn't DOSEMU2 tells the user if it doesn't match ? Currently, I don't have a problem with it.

And if I demand too much, let me know. I don't want to hurt anyone. I only give my opinion in the hope to make it better.

Better we keep talking at the feature request:
https://github.com/stsp/dosemu2/issues/712

**Comment by stsp** [comment]
> I let install fdpp to its system location the normal way with "make install".
> Then I create a symbolic link from my custom setup to /usr/local/share/fdpp/fdppkrnl.sys.
> That works fine.

This works because of a bug.
dosemu2 finds fdppkrnl.sys in its
system-wide location, and assumes
it will also be available to the boot
process from that location. But at one
point it forgets the full path, and when
it finds it on C, it thinks "ah, here you are, my dear".
If in the future it will stop forgetting the
full path, then it will not pick it up from
C, because the path is different.

> Regarding versioning, doesn't DOSEMU2 tells the user if it doesn't match ?

I had to add that because Andrew already
started that mayhem of finding the bugs and
quickly depending on them before I could fix
them.
