### ISSUE TITLE
DOSEMU2 tries to create symbolic link for fdconfig.sys even it exist already

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#711]
Problem appears on custom setup with and without fdpp.

**Comment by stsp** [comment]
Please don't strip the default bug
layout unless you are going to provide
the reproducer details yourself.
I took the reproducer instructions from
your previous bug and that worked, but
please provide the needed info in the future.
Should now be fixed.

**Comment by bolle732** [comment]
Ok, will try to respect the layout in the future. Sorry about it.

Can confirm that it don't longer tries to create the link.
