### ISSUE TITLE
lfn rename crashes DOSEmu2

### ISSUE THREAD

**Issue by rouseabout** [stsp/dosemu2#716]
**Describe the bug**
dosemu2 (git HEAD) crashes when renaming long input filename. This is not a duplicate of <https://github.com/stsp/dosemu2/issues/556>, but appears related.

**To Reproduce**
Type this into dosemu2 command prompt:

```
echo test > a.txt
rename a.txt 1$$djren$$.$$temp$$
rename 1$$djren$$.$$temp$$ b.txt
```

Crash occurs on second rename. The dot in the filename appears to trigger the crash, i.e. the crash does not occur if the dot is removed.

The $$djren$$.$$temp$$ filename is used by DJGPP-based applications, and therefore is something dosemu2 should support.

**Expected behavior**
Self explanatory.

**Attach the log**

```
DOSEMU-2.0pre8-20181120-656-g45596a6e is coming up on Linux version 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64
Compiled with gcc version 7.3.0 64bit
[...]
ERROR: bad sfn name .$$temp$$
ERROR: Accessing reserved memory at 7f746affe000
        Maybe a null segment register
```

**Comment by andrewbird** [comment]
Don't worry I reproduced it under FreeDOS 1.20

**Comment by rouseabout** [comment]
the problem exists in extract_filename. patch:

[0001-extract_filename-rework-function-to-prevent-crash-on.patch.txt](https://github.com/stsp/dosemu2/files/2599710/0001-extract_filename-rework-function-to-prevent-crash-on.patch.txt)

**Comment by andrewbird** [comment]
I think the problem comes about because `_dos_rename()` is called both by the redirector and the LFN frontend and so should deal with 8.3 and LFNs, but the rename code seems to be assuming 8.3 only.
I also notice that in DOS if `copy` is used instead of `rename` the resultant file open code works fine, presumably because the actual open is done in the redirector only with SFNs.
@stsp do you want to paper over this for now or rewrite to be more like open? I'm a little busy myself for a rewrite at the moment.

**Comment by stsp** [comment]
> I think the problem comes about because _dos_rename() is called both by the redirector and the LFN
> frontend

Yes, you are right.
As a quick fix I just pushed the old LFN version of
`dos_rename()`, prior to the bug existence.
But the patch of @rouseabout simplifies the unnecessary
complex code of `extract_filename()` and adds the missing
length guards, so I applied also it. It doesn't hurt.

**Comment by stsp** [comment]
As a side effect, there will be no wildcard renames
for LFN now. I wonder if anyone cares.

**Comment by andrewbird** [comment]
>As a side effect, there will be no wildcard renames
for LFN now.

I'm not sure that's legal in the int21/7156 call anyway. I'm looking for it as we speak but haven't found anything saying it is. Obviously it's supported at the command line, but maybe that's implemented via find_first/next and multiple calls to rename?

**Comment by stsp** [comment]
> Obviously it's supported at the command line, but maybe that's implemented via find_first/next
> and multiple calls to rename?

By command.com you mean?
I guess so.
It is actually very silly to throw wildcards on a
redirector, and FreeDOS doesn't do this AFAIK,

**Comment by stsp** [comment]
@rouseabout thanks for the patch, btw. :)

**Comment by andrewbird** [comment]
> By command.com you mean?

Yes

> It is actually very silly to throw wildcards on a redirector

Yes it also means that the DOS wildcard processing is implemented differently between local and network drives.

I notice in the original bug for the code you reverted #526 you mention that non free DOS are a problem with `rename file.ext *.new`, but I just tested that on MS-DOS 6.22 and it works, so I wonder if you recall the DOS that was broken?

**Comment by stsp** [comment]
I didn't do a full revert.
I only reverted the (unneeded/wrong) LFN part of it.
Wildcards should still work.

**Comment by stsp** [comment]
> I just tested MS-DOS 7.1 with a rename *.* *.new where at least one file was LFN

In my case there were no lfn files.
#526 is purely about SFNs.

**Comment by stsp** [comment]
That's the reason why I simply reverted
the LFN part now and I think all is still well.

**Comment by andrewbird** [comment]
I've just tested again with MS-DOS 6.22 and SFN. It seems that command.com calls FCB rename int21/17 with `*` wildcards then passes on to the redirector with `?` wildcards. Which is all fine and dandy except that it doesn't explain why when you had no wildcard support in the redirector the free DOSs were fine. Unless of course the redirector somehow supported `*` but not `?` and the broken FCB rename in FreeDOS helped out.
You are definitely right to split the wildcard handing between LFN and SFN as from what we saw earlier on the FDPP rename ticket the expansion semantics are different.

It's a shame there's no method to update RBIL, as I'm sure we'll forget that int2f/1111 supports `?` wildcards.

**Comment by stsp** [comment]
> doesn't explain why when you had no wildcard support in the redirector the free DOSs were fine. Unless of 
> course the redirector somehow supported * but not ? and the broken FCB rename in FreeDOS helped out.

No, there were neither `*` nor `?` thrown to the
redirector by freedos. I guess you just need to
find the fatfs-local wildcard handling there. Since
it can expand them for fatfs, there is no surprise
it does the same for remote drives. The opposite
is surprising though (even for Ralph Brown :)

**Comment by andrewbird** [comment]
I just checked FreeDOS 1.20 (with freecom) and it's using LFN functions first, then falling back to SFN ones if unavailable but essentially findfirst/findnext -> rename -> redirector rename.

So I see now why you saw the behaviour you did, it avoids using int21/17. This also explains why that call is broken in FreeDOS and nobody noticed.
