### ISSUE TITLE
restructure DOS commands

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#728]
Invoke them via ae00 to make `generic.com`
optional. Move it and other commands back
to plugins, separately from C builtins.
This should be a step towards solving portability
problems. If the DOS executables are optional,
portability is easier.

**Comment by stsp** [comment]
Hmm, switching to ae00 appears to be
exceptionally difficult. I created the `blt_2f`
branch and added the preliminary support
there. But its quite bad. Any help is welcome.

**Comment by stsp** [comment]
Horribly difficult porting...
Andrew, could you please see on
what DOSes our commands work
if you remove `generic.com`, and
if nothing have regressed when
`generic.com` is present?
ae00 is so convoluted API that I
won't expect it to work correctly
everywhere. Seems to work with
freecom and command.com from
pc-dos7 at least.

**Comment by stsp** [comment]
And unfortunately it takes the preference
over `generic.com`, at least where it is supported.
So I am really afraid of a regressions. I'd rather
use it as a fall-back, but its not possible, either
you use it or not, but not as a fall-back.

**Comment by andrewbird** [comment]
~~~
gcc -c -MMD -DCFLAGS_STR="-Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -Wwrite-strings -fplan9-extensions -Wno-maybe-uninitialized -fno-pie -fsanitize=undefined -fno-sanitize=alignment -ggdb3 -O   " -I../../../src/include -I../../../src/plugin/include -I/clients/common/dosemu2.git/src/include  -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -Wwrite-strings -fplan9-extensions -Wno-maybe-uninitialized -fno-pie -fsanitize=undefined -fno-sanitize=alignment -ggdb3 -O    -o int.o int.c
In file included from /usr/include/string.h:494:0,
                 from int.c:2:
In function ‘strcpy’,
    inlined from ‘run_program_ae01’ at int.c:2155:5,
    inlined from ‘int2f’ at int.c:2277:2:
/usr/include/i386-linux-gnu/bits/string_fortified.h:90:10: warning: ‘__builtin___strcpy_chk’: writing at least 1 byte into a region of size 0 overflows the destination [-Wstringop-overflow=]
   return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

**Comment by stsp** [comment]
This is only a warning.
I've seen it on some gcc version in ubuntu,
but not on fedora and not on clang.

**Comment by andrewbird** [comment]
yep, but it's new, I figured you'd want to fix it.

**Comment by stsp** [comment]
I can only fix it by bug-reporting to ubuntu.

**Comment by andrewbird** [comment]
BTW, I like how you've split dos drivers and commands. I wonder if `src/plugin/dosdrv/isemu.s` is in the wrong place though?

> I can only fix it by bug-reporting to ubuntu.

Oh it's a false positive then, no worries.

**Comment by andrewbird** [comment]
And is this correct, on PC-DOS 3.30 which does have int2f/ae00 support?

~~~
C:\>lredir
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\c\ attrib = READ
/WRITE
D: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\d\ attrib = READ
/WRITE
 
C:\>del dosemu\generic.com
 
C:\>lredir
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\c\ attrib = READ
/WRITE
D: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\d\ attrib = READ
/WRITE
 
C:\>c:\dosemu\lredir
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\c\ attrib = READ
/WRITE
D: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\d\ attrib = READ
/WRITE
~~~

It seems to me that if you fully path something it shouldn't be interpreted as an internal command, thoughts?

**Comment by stsp** [comment]
> BTW, I like how you've split dos drivers and commands.

This split was there before.
In `src/env/commands` and `src/env/builtins`.
The new split I did now, is builtins C code and
`generic.com *.com` are now separated.

> I wonder if src/plugin/dosdrv/isemu.s is in the wrong place though?

This was so before.
And I think it should stay because you can't
code `isemu.com` as a builtin. It should work
without dosemu so its not a builtin. Of course
one can argue dosdrv is also not the right place
for it, but there is simply nothing better.

> Oh it's a false positive then

At least I think so. On fedora I have gcc-8.2
without this problem.

**Comment by stsp** [comment]
> It seems to me that if you fully path something it shouldn't be interpreted
> as an internal command, thoughts?

This is exactly what happens to be with newer
command.coms. Please see what exactly does
it pass to ae00.

**Comment by stsp** [comment]
As a counter-measure I can check the
existence of `generic.com` at startup,
in its standard location, and disable the
ae00 handling accordingly. But of course
you do not use the standard locations,
so for you this won't work.
Anyway, would be nice to know what exactly
doses have any problems, then decide.

**Comment by andrewbird** [comment]
~~~
(gdb) step
do_run_cmd (cmd=0xafe8f390, str=0xafe8f5ab) at int.c:2183
2183	    memcpy(arg0, str->s, str->len);
(gdb) p str
$3 = (struct lowstring *) 0xafe8f5ab
(gdb) p *str
$4 = {len = 8 '\b', s = 0xafe8f5ac ' ' <repeats 11 times>}
(gdb) p cmd
$5 = (struct ae00_tab *) 0xafe8f390
(gdb) p *cmd
$6 = {max_len = 128 '\200', cmd = {len = 17 '\021', s = 0xafe8f392 "c:\\dosemu\\lredir2\r"}}
~~~

**Comment by andrewbird** [comment]
> As a counter-measure I can check the existence of generic.com

Or perhaps just disable ae00 support if `generic.com` was built?

**Comment by stsp** [comment]
> (gdb) p *str
> $4 = {len = 8 '\b', s = 0xafe8f5ac ' ' <repeats 11 times>}

As you can see, arg0 is taken from `str`, not `cmd`.
So in  your example I would expect `run_command_plugin()`
to return 0 and external command is used. Or?

> Or perhaps just disable ae00 support if generic.com was built?

... or just check the redirector version.
Would be nice to have the list of DOSes and
understand what the problem actually is.

**Comment by andrewbird** [comment]
I had deleted generic.com, I'm just wondering now if I need to delete lredir2.com as well for the test?

**Comment by stsp** [comment]
Its a symlink to generic.com.
Better to delete all dangling symlinks.
