### ISSUE TITLE
On first run, have to run dosemu twice

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#73]
On first run of dosemu, it seems to setup DOS and quit, 2nd run runs normally.

To reproduce, run with no ~/.dosemu

First time:

```Welcome to DOSEMU ...

Press Enter to Confirm ..```

Press enter and window shuts


2nd time:

Boots normally.

**Comment by stsp** [comment]
In install.c:341 try changing 0 to 1.
I don't remember why I did that, but there was
likely the problem. The good testing will help.

**Comment by stuaxo** [comment]
That seems to fix it, I'll leave it that way and see if anything comes up

**Comment by stsp** [comment]
Should now be fixed.
Please test!

**Comment by jschwartzenberg** [comment]
Working again for me! Both option 1 and 2 are working correctly again!!
