### ISSUE TITLE
How to install and use FDPP in dosemu2?

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#730]
Running `./configure && make && sudo make install` in the FDPP directory then `./default-configure -d` in the dosemu2 directory results in `"configure: WARNING: fdpp not available!"`. What am I missing? What else do I need to do to select either a classic FreeDOS kernel or FDPP when the latter is installed?

**Comment by stsp** [comment]
> Running ./configure && make && sudo make install in the FDPP directory

You mean, in fdpp directory of dosemu source, or
fdpp directory of fdpp itself? If you did that in the fdpp
directory of fdpp itself, or in topdir of fdpp, then that's
the right thing to do.
Now please do ./configure in fdpp directory of dosemu2
and post the output here.

**Comment by ecm-pushbx** [comment]
Found an fdpp subdirectory, but ./configure errors out.

```
~/coding/proj/dosemu2/src/plugin/fdpp$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for FdppInit in -lfdpp... no
configure: error: fdpp development libs not found
```

**Comment by ecm-pushbx** [comment]
Found an fdpp subdirectory, but ./configure errors out.

```
~/coding/proj/dosemu2/src/plugin/fdpp$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for FdppInit in -lfdpp... no
configure: error: fdpp development libs not found
```

**Comment by stsp** [comment]
> checking for FdppInit in -lfdpp... no

What? Are you kidding?
The FdppInit check was removed by

commit e913c28eb5627091f87500b4ef4fce3782faba35
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Tue Jul 31 00:15:39 2018 +0300

Half a year ago!
What the hell are you compiling there? :)

**Comment by ecm-pushbx** [comment]
I've checked out dosemu2 revision 843ea577fecb98661441e4d850a784c631416380

**Comment by ecm-pushbx** [comment]
Oh it seems that the "configure" file is outdated. It doesn't appear in the gitk tree view of the most recent commit. What command do I use to regenerate that?

**Comment by ecm-pushbx** [comment]
Guessing this was the wrong way:

```
~/coding/proj/dosemu2/src/plugin/fdpp$ autoconf
~/coding/proj/dosemu2/src/plugin/fdpp$ ./configure 
./configure: line 1684: syntax error near unexpected token `FDPP,'
./configure: line 1684: `PKG_CHECK_MODULES(FDPP, fdpp,,'
~/coding/proj/dosemu2/src/plugin/fdpp$ 
```

**Comment by stsp** [comment]
Its strange, because configure gets regenerated
when configure.ac changes. And "make clean" should
remove it, so try "make clean" or "make realclean"
and see if its still there. Then the top-level configure
should regenerate them all.

**Comment by ecm-pushbx** [comment]
make clean then make (both in the src/plugin/fdpp directory) worked. I then did ./default-configure -d and make and sudo make install in the dosemu2 top directory, and it boots:

```
C:\>ver /r
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 7.10
FDPP kernel 0.1beta-2-50-g40ebd11 (compiled Dec 10 2018)░
C:\>    
```

Now, how do I select the old FreeDOS for booting (or anything else loaded from kernel.sys) if I want to not use fdpp?

**Comment by ecm-pushbx** [comment]
Also from the sign-on I just noticed fdpp is GPL v3+. Why didn't you stay with v2+ ?

**Comment by stsp** [comment]
> Now, how do I select the old FreeDOS for booting

Very easy, just put kernel.sys on C:.
While I am trying to push fdpp forward, freedos is and
will be supported, so just do whatever you did in the past,
and it will work.

> Also from the sign-on I just noticed fdpp is GPL v3+. Why didn't you stay with v2+ ?

GPL v2+ allows me to put the entire project under
GPL v3+. Be there GPL2-only code, I wouldn't be
able to do that. As far as I understand, that choice
doesn't impose any troubles on exchanging patches.
Plus, freedos people ignore fdpp anyway, so why to
even care.

**Comment by stsp** [comment]
I just "touched" configure.ac in fdpp subdir of
dosemu2, then ran `make` at top-dir, and configure
got regenerated. I didn't do any `make clean`.
So unless you can provide the exact steps how
to stick with an older configure and up-to-date
configure.ac, I think this bug is invalid.

**Comment by ecm-pushbx** [comment]
> GPL v2+ allows me to put the entire project under GPL v3+.

Yes, I didn't doubt that, just wondering why you chose that.

> Be there GPL2-only code, I wouldn't be able to do that. As far as I understand, that choice doesn't impose any troubles on exchanging patches.

Well there, for example, is MetaKern and a nice terminal program both by Eric Auer which, albeit from 2005, are GPL v2-only. [I asked him but he did not yet change that.] So that'd be incompatible.

> Plus, freedos people ignore fdpp anyway, so why to even care.

Sure, but it's another complication.

> I just "touched" configure.ac in fdpp subdir of dosemu2, then ran make at top-dir, and configure got regenerated. I didn't do any make clean. So unless you can provide the exact steps how to stick with an older configure and up-to-date configure.ac, I think this bug is invalid.

Yeah technically I used the Feature requests and Questions template, because I just wanted to find out what I was doing wrongly. So thanks.

**Comment by stsp** [comment]
> Well there, for example, is MetaKern and a nice terminal program both by Eric Auer

fdpp does not re-implement any of the DOS apps.
Its only a kernel. So we need to only consider the
patch interchangeability between fdpp and fdkernel,
and that should be fine. There will also be a comcom32
and eventually comcom64, and nothing more, so
GPL3+ should not be of any troubles.

> Yeah technically I used the Feature requests and Questions template, because
> I just wanted to find out what I was doing wrongly.

OK, then I'll rephrase myself: I still don't know what
you were doing wrongly, because I wasn't able to reproduce
the scenario where we have an old configure script
and up-to-date everything else. So your question can't
be answered properly unless you provide the steps to
reproduce that situation (in which case it will be a bug-report).

**Comment by ecm-pushbx** [comment]
> So your question can't be answered properly

On the contrary, you did solve my request on how to build with fdpp proper.
