### ISSUE TITLE
dosbox compatibility - mount and exit

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#74]
It could be desirable to have 'mount' and 'exit' work like dosbox, then the user won't have to think as much and scripts should work the same.

In the past I've done this in a slightly hacky way - using an extra shell in dosemu, and ending my autoexec.bat with 

```
command
exitemu
```

and for mount a batch file which at it's core is:

```
LREDIR %1: LINUX\FS%2
```

Would compatibility here be desirable?

If so mount should probably be an executable, not a batch wrapper around lredir, and the last 'exit' should probably be setup to exit dosemu, since the subshell method is a bit wasteful of memory.

**Comment by stsp** [comment]
I don't think why mount can't be implemented
as mount.bat. What would be a problem?
As for last exit - I don't know how you suppose
to implement that. There is a hook that command.com
calls for every command, so you can intercept
"exit", but I am not sure how to check whether this
is a main instance of command.com or a sub-shell.
You can ask freedos ppl to help with this.

**Comment by stuaxo** [comment]
OK, started to have a look at this - not 100% sure which Makefile to change to get the file to install yet, but will have a bit of a dig..

**Comment by stsp** [comment]
What is the problem of having mount.bat?

**Comment by stuaxo** [comment]
No problem, I saw everything else not implemented this way and thought it might be an issue.

I've started trying to work out how to get the Makefile in src/plugins/commands  to copy an lredir.bat in.

**Comment by stsp** [comment]
I simplified the makefile, HTH.

**Comment by stuaxo** [comment]
Cheers - that is a lot easier to grok :)

**Comment by stsp** [comment]
Please open a new pull request for lredir2-based
mount.bat.
A good testing of lredir2 is appreciated.

**Comment by stuaxo** [comment]
Yup, I'll write more info in here when I complete more on that branch.

Testing of the user commands seems useful, would batch files be alright ?

**Comment by stsp** [comment]
Likely so.
We already have src/tests for the like things.

**Comment by stuaxo** [comment]
Ah, you got this working with getopt - somehow I made it crash when I tried it.   lredir2 code is *much* easier to grok.

Have some time in next few days, when I can test this + try and build mount + hopefully some of the features I mentioned for lredir2.

**Comment by stsp** [comment]
glibc requires a non-portable and undocumented
trick for getopt to work, namely:
optind = 0;
to initialize the parser.

**Comment by stuaxo** [comment]
Ah, that was nice of them :/ .    Is there a reason lredir* uses it's own getcwd ?   - if not, then I'll patch it to use the one from unistd, along with seeing if any other patches I did in this branch make sense

https://github.com/stuaxo/dosemu2/blob/lredir2/src/plugin/commands/lredir.c

**Comment by stsp** [comment]
Of course it should use its own getcwd() - it
resolves the DOS path.

**Comment by stuaxo** [comment]
Doh !   cheers.
