### ISSUE TITLE
Dosdebug: writing a find command

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#741]
I'm writing a `find` command for dosdebug that will scan DOS memory for a string or sequence of bytes. Rough syntax will be
~~~
dosdebug> find
dosdebug> 
USAGE: find [-start ADDR] [-length SIZE] [-ignorecase] [-dump] [-unassemble] SEARCHVALUE
~~~
~~~
dosdebug> find -d COMMAND.COM
dosdebug> 
Match found at 0x0000f02f

0f02:000f 43 4F 4D 4D 41 4E 44 2E 43 4F 4D 00 00 00 00 00  COMMAND.COM.....
0f02:001f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
Match found at 0x0000f401

0f40:0001 43 4F 4D 4D 41 4E 44 2E 43 4F 4D 0D 0A 21 49 6E  COMMAND.COM..!In
0f40:0011 73 65 72 74 20 64 69 73 6B 20 77 69 74 68 20 25  sert disk with %
Match found at 0x0000ffdb

0ffd:000b 43 4F 4D 4D 41 4E 44 2E 43 4F 4D 00 50 52 4F 4D  COMMAND.COM.PROM
0ffd:001b 50 54 3D 24 50 24 47 00 50 41 54 48 3D 43 3A 5C  PT=$P$G.PATH=C:\
Match found at 0x00010e20

10e2:0000 43 4F 4D 4D 41 4E 44 2E 43 4F 4D 00 00 43 3A 5C  COMMAND.COM..C:\
10e2:0010 41 55 54 4F 45 58 45 43 2E 42 41 54 00 0D 43 3A  AUTOEXEC.BAT..C:
Match found at 0x00010e8a

10e8:000a 43 4F 4D 4D 41 4E 44 2E 43 4F 4D 00 3D 61 7A 20  COMMAND.COM.=az 
10e8:001a 43 4B 41 10 00 F0 FF 3A 1C 2A 00 00 00 00 00 BF  CKA..p:.*.....?
Match found at 0x00011129

1112:0009 43 4F 4D 4D 41 4E 44 2E 43 4F 4D 20 66 69 6C 65  COMMAND.COM file
1112:0019 2E 0D 0A 4D 20 20 64 65 76 69 63 65 20 20 20 20  ...M  device    

<snip>
~~~

I have a question about DOS memory in dosemu. I expected to be able to search the range 
LINEAR2UNIX(0) to LINEAR2UNIX(0xfffff) but I get segfaults from `memchr()` once I get within 5-6k of the end. What am I missing?

**Comment by stsp** [comment]
You mean somewhere in HMA?
Not sure, but you can try using
lowmem_base directly for now.
When you get things working that
way, I can look at why the proper
conversion breaks.

**Comment by andrewbird** [comment]
Not sure really, DOS memory management is a bit of a mystery to me. I was was hoping to search the first megabyte which I think should be accessible by real mode DOS programs. If I limit the range to LINEAR2UNIX(0) to LINEAR2UNIX(0xfdfff) all works fine, so I can live with that for now.

**Comment by stsp** [comment]
There are many mysteries and
tricky places, and the lack of intetested
developers makes it unnecessary to
document anything. There are several
views of dos mem, with lowmem_base
being the linear, unprotected view. So
it should not segfault.
But LINEAR2UNIX() should also work,
so if you prepare a simple test case, I'll
help.

**Comment by stsp** [comment]
Ah, I forgot to tell you that LINEAR2UNIX()
does not span large areas. So as soon as
you are above 0x9ffff, you should
call it repeatedly, preferably at 64k
boundaries.

**Comment by stsp** [comment]
Even 16k boundaries.
But as for the first 640k - should be
covered by one call.

**Comment by stsp** [comment]
In contrast, LOWMEM() is a simpler
view, as it is entirely linear. It may not
match the dos view, but for dosdebug
needs should suffice.

**Comment by andrewbird** [comment]
> Ah, I forgot to tell you that LINEAR2UNIX()
does not span large areas. 

That's disturbing, I have been expecting this to work.

```C
unsigned char *base, *end, *p;
unsigned char *sval = "COMMAND.COM";
int matchlen = strlen(sval);

base =  LINEAR2UNIX(0);
end =  LINEAR2UNIX(0xfffff) - matchlen;

for (p = base; p && p < end; p++) {
   p = memchr(p, sval[0], end - p);
   if (p && memcmp(p, sval, matchlen) == 0) {
      print whatever
   }
}
```

It also crossed my mind that I have been `find`ing on DOS memory without it being stopped in dosdebug, so it's possible that memory contents are changing whilst I'm reading.

**Comment by stsp** [comment]
Content changing wont crash (and
wont happen while the single debug
cmd is working, it can only change in
between). Use LOWMEM() for now.

**Comment by stsp** [comment]
LINEAR2UNIX() is an accurate
representation of dos mem, but its
not contiguous. You need to know
what region you are asking to translate.
LOWMEM() is contiguous, but its
representation is not very accurate,
it matches the dos mem in most cases,
and should be sufficient for you needs.
MEM_BASE32() is both contiguous
and accurate, but has a set of its own
problems. We introduce the new views
by demand, but I dont think dosdebug
is a worthy consumer. The pending
new views are vm86_base and kvm_base.
One day Ill get to implementing them. :)
dosdebug should use something existing.

**Comment by stsp** [comment]
The reason we cant just have a one
"good for all" view is because some
consumers have specific needs
(MAP_32BIT or MAP_FIXED), and
others are very agressive (vgaemu
and simx86 play with protection bits,
thats why you can't use MEM_BASE32(),
and also because it uses MAP_32BIT).
dosemu-1.0 tried using a single mapping,
and that was very buggy.
The reason why we cant have the
"sane" mapping in addition to all others,
is that likely we can. I know Bart tried
that and later reverted. I think the reason
for a revert was that the combination of
LOWMEM() and LINEAR2UNIX() covers
all "extra" needs if carefully used. And
dosdebug definitely falls into an "extra"
category, its not a first-class client here.

**Comment by andrewbird** [comment]
My stupid mistake, final `memchr()` set p = NULL as there was no match, then the loop incremented it to an address (0x1) out of process space hence the segfault on next `memchr()`! It's working now with both `LOWMEM()` and `LINEAR2UNIX()`, which is preferable?

**Comment by stsp** [comment]
The reason that LINEAR2UNIX() "works"
is likely because for an address 0 it
returns same what LOWMEM(0) would
return, so you end up working with
LOWMEM() in both cases. See if
LINEAR2UNIX(0xE000) == LINEAR2UNIX(0)+0xE000 for example,
and you may notice it didnt actually
worked.

**Comment by stsp** [comment]
Wrong numbers, should be
LINEAR2UNIX(0xE0000) == LINEAR2UNIX(0)+0xE0000
for a test.

**Comment by andrewbird** [comment]
I added a PR #743 for you to consider.
