### ISSUE TITLE
No Dos Cursor Installed Centos7 64bit

### ISSUE THREAD

**Issue by mcshanenoel** [stsp/dosemu2#742]
**Describe the bug**
A description of what the problem is.

**To Reproduce**
Steps to reproduce the behaviour:

**Attach the binaries**
If the problem needs specific DOS files to reproduce, please attach.

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.

**Comment by mcshanenoel** [comment]
When you install dosemu2 on Centos7 64 bit and start up dosemu it works great but cursor appears to stay on the first character on the first line.

**Comment by stsp** [comment]
Please attach -D9+v log.

**Comment by mcshanenoel** [comment]
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing built-in global.conf file.
CONF: config variable version_3_style_used unset
CONF: config variable version_3_style_used set
CONF: opened include file /etc/dosemu/dosemu.conf
CONF: closed include file /etc/dosemu/dosemu.conf
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Disabling use of pentium timer
CONF: dosbanner on
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe400
CONF: DPMI-Server on (0x5000)
CONF: DPMI base addr = 0xffffffff
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
SER0: /dev/nettty/S0
SER1: /dev/nettty/S1
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout keyb-user
CONF: Keyboard-layout uk
CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: /dev/nettty/S0  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
device: /etc/dosemu/drives/c type 4 h: -1  s: -1   t: -1 drive C:
device: /etc/dosemu/drives/d type 4 h: -1  s: -1   t: -1 drive D:
CONF: cdrom MSCD0001 on /dev/cdrom
CONF: config variable c_system unset
debug flags: -p
Linux kernel 3.10.0; CPU speed is 900019000 Hz
CPU-EMU speed is 900 MHz
work around FreeDOS UMB bug
CONF: running exclusively as ROOT: uid=0 (cached 0) gid=0 (cached 0)
DBG_FD already set
DOSEMU-2.0pre4 is coming up on Linux version 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64
Compiled with GCC version 4.8.5 -m64
CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -fno-stack-protector -fplan9-extensions -Wno-maybe-uninitialized -O2
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 48Kb at 0xF4000 for 'r' (Dosemu reserved area)
CONF: reserving 64Kb at 0xB0000 for 'v' (Video memory)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0217
initial segment bases: fs: 0x7f082cb46740  gs: (nil)
WARN: using non-zero memory base address 0x40767000.
WARN: You can use the better-tested zero based setup using
WARN: sysctl -w vm.mmap_min_addr=0
WARN: as root, or by changing the vm.mmap_min_addr setting in
WARN: /etc/sysctl.conf or a file in /etc/sysctl.d/ to 0.
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
Registering HWRAM, type=e base=0x507000 size=0x400000
CONF: reserving 4096Kb at 0x507000 for 'e' (VGAEMU LFB)
CONF: reserving 4Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
SERIAL $Id$
registering /dev/nettty/S0 for serial
registering /dev/nettty/S1 for serial
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xF0000 for 'E' (EMS page frame)
CONF: reserving 64Kb at 0xA0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 140Kb at 0xC1000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
DPMI: mem init, mpool is 20992000 bytes at 0x41d0b000
TIME: using 9154 usec for updating ALRM timer
Using V86 mode inside KVM
MFS: couldn't find root path /media/CDROM
DOS termination requested
leavedos(dos_helper:525|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped

**Comment by stsp** [comment]
This is not a -D9+v log, you need to run
`dosemu -D9+v`

**Comment by stsp** [comment]
Also it would be better to attach the log,
not copy/paste.

**Comment by stsp** [comment]
Please re-open when you have a proper log.
And even from this log its clear you are running
DOSEMU-2.0pre4 which is not supported.
