### ISSUE TITLE
Revision gc96fcfeef fails to build

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#744]
Already tried "make clean" then "./autogen.sh" then "./default-configure -d" then "make".

Result:

```
make[1]: Nothing to be done for 'default'.
echo "Updating version.h"; \
echo "#ifndef	VERSION_HH" > ../src/include/version.hh; \
echo "#define	VERSION_HH" >> ../src/include/version.hh; \
echo "#define	VERSTR	\"2.0pre8-20190106-823-gc96fcfeef\"" >> ../src/include/version.hh; \
echo "#define	VERSION_NUM	2" >> ../src/include/version.hh; \
echo "#define	SUBLEVEL	0" >> ../src/include/version.hh; \
echo "#define	PATCHLEVEL1	\"pre8\"" >> ../src/include/version.hh; \
echo "#define	REVISION	4522" >> ../src/include/version.hh; \
echo "#define	VERDATE \""2019-01-06"\"" >> ../src/include/version.hh; \
echo "#endif /* VERSION_H */" >> ../src/include/version.hh
Updating version.h
cd .. && [dosemu2 path]/scripts/mkpluginhooks
make -C ../src/base/bios/x86 bios_offsets.hh
make[2]: *** No rule to make target '[dosemu2 path]/src/media/ssd-data/coding/proj/dosemu2/src/base/bios/x86/Makefile', needed by 'bios2.o'.  Stop.
make[1]: *** [[dosemu2 path]/src/Makefile.common:63: ../src/base/bios/x86/bios_offsets.hh] Error 2
make: *** [Makefile:25: default] Error 2
```

(I redacted my directory names, replacing them with "[dosemu2 path]".)

**Comment by stsp** [comment]
https://code.launchpad.net/~dosemu2/+recipe/dosemu2-daily
It builds there perfectly.
Why you dont have `dosemu2/src/base/bios/x86/Makefile'`?

**Comment by ecm-pushbx** [comment]
I do have that file. However, I just noticed something:

    make[2]: *** No rule to make target '[dosemu2 path]/src/[dosemu2 path]/src/base/bios/x86/Makefile', needed by 'bios2.o'.  Stop.

Notice that the dosemu2 path is included twice in that path!

**Comment by ecm-pushbx** [comment]
Huh. Doing "./default-configure -d" from the "physical" pathname (in my case, the path including ssd-data mountpoint) then "make" works fine. Doing "./default-configure -d" from a pathname with symlinks (via my home directory here) then "make" fails as specified.

**Comment by stsp** [comment]
So `SUBDIR` seems to be evaluated wrongly.
In `Makefile.common` you can see:
```
SUBDIR := $(subst $(abs_top_builddir)/src,,$(CURDIR))
SUBDIR := $(patsubst /%,%,$(SUBDIR))
```
Please figure out how these lines fail.
You can put `$(warning SUBDIR=$(SUBDIR))` after
each to see how it evaluates.

**Comment by stsp** [comment]
Please try again.

**Comment by ecm-pushbx** [comment]
Seems to work now in g311412462, thanks!

**Comment by stsp** [comment]
Had to re-push, the fix was wrong.
Should now still work.

**Comment by ecm-pushbx** [comment]
gd284ce624 seems to work.
