### ISSUE TITLE
dosemu --help says -E should be "don't exit afterwards"

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#745]
**Describe the bug**
In the dosemu --help page, -E is listed as

    -E STRING pass DOS command on command line (but don't exit afterwards)

This is wrong; with -E dosemu does exit after the specified DOS command terminates. In addition, I didn't find any switch that actually modifies -E not to exit afterwards (nor a replacement for -E with that changed behaviour).

**To Reproduce**
dosemu -E whatever

**Comment by stsp** [comment]
Should now be fixed, but you can use man instead.

**Comment by ecm-pushbx** [comment]
Ah so it's -T that modifies the behaviour of -E. Thanks!
