### ISSUE TITLE
Missing every 16th byte of data from dosemu serial port to a real DOS machine

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#748]
**Describe the bug**

When I connect dosemu's com 2 to /dev/ttyS0, the Linux machine's port which is connected with a null modem cable to a DOS machine, and then run the same example program on both machines, when transmitting a long string, dosemu seems to skip the 32nd byte and after that every 16th byte.

The text starts as follows:

    This is a very long test string. It serves the purpose of
    demonstrating that our interrupt-driven routines are capable

This is what I receive on the DOS machine:

    This is a very long test strig. It serves th purpose of
    deonstrating thatour interrupt-diven routines ae capable

There is a linebreak in front of the first line, and linebreaks are translated by the sender from CR to CR LF, so what we should send is:

```
13 - 1st	10 - 2nd	T - 3rd		h - 4th
i - 5th		s - 6th		  - 7th		i - 8th
s - 9th		  - 10th	a - 11th	  - 12th
v - 13th	e - 14th	r - 15th	y - 16th
  - 17th	l - 18th	o - 19th	n - 20th
g - 21st	  - 22nd	t - 23rd	e - 24th
s - 25th	t - 26th	  - 27th	s - 28th
t - 29th	r - 30th	i - 31st	n - 32nd
g - 33rd	. - 34th	  - 35th	I - 36th
t - 37th	  - 38th	s - 39th	e - 40th
r - 41st	v - 42nd	e - 43rd	s - 44th
  - 45th	t - 46th	h - 47th	e - 48th
  - 49th	p - 50th	u - 51st	r - 52nd
p - 53rd	o - 54th	s - 55th	e - 56th
  - 57th	o - 58th	f - 59th	13 - 60th
10 - 61st	d - 62nd	e - 63rd	m - 64th
o - 65th	n - 66th	s - 67th	t - 68th
r - 69th	a - 70th	t - 71st	i - 72nd
n - 73rd	g - 74th	[etc]
```

Missing bytes are: "n" 32nd, "e" 48th, "m" 64th

**To Reproduce**

Test program's source is at https://bitbucket.org/ecm/serialp/src/81d0ef29635c1a415a00f0addcea968123642f8f (+ lmacros from the same bitbucket.org account)

On Linux side (sz is from lrzsz 0.12.21-10 from Debian repository):

```
$ cat "$(which zsend)"
#!/bin/sh

DEV=/dev/ttyS0

stty -F $DEV 115200
sz "$@" > $DEV < $DEV
$ ./mak.sh -D_ECHO_RX_TO_TX=0 -D_RX_OUTPUT_ADD_LF=0 -D_RX_TO_TX_ADD_LF=0 -D_INTNUM=0Bh -D_OFFMASK=0000_1000b -D_UART_BASE=2F8h -D_BI_TX_FIFO_SIZE=15 && cp -a serialp.com ser2ser2.com && zsend ser2ser2.com
$ ./mak.sh -D_ECHO_RX_TO_TX=0 -D_RX_OUTPUT_ADD_LF=0 -D_RX_TO_TX_ADD_LF=0 -D_INTNUM=0Bh -D_OFFMASK=0000_1000b -D_UART_BASE=2F8h && cp -a serialp.com ser2ser3.com && stty -F /dev/ttyS0 9600 && dosemu -I"serial { com 2 device /dev/ttyS0 }" -K "$PWD" -E "ser2ser3.com"
```

Within the dosemu session, press &lt;F1&gt; (or &lt;Ctrl+A&gt;).

On DOS side (zm is Public Domain Zmodem release 1.24):

```
> zm -os2d -o1 -b115200 rz
> SER2SER2.COM
```

Note that when using ser2ser2 in dosemu too (with "-D_BI_TX_FIFO_SIZE=15" being operative), it runs fine and doesn't expose this bug. This means when, upon THRE, we transmit 16 bytes at a time (to flll the UART's internal buffer), the bug is exposed. If we transmit only 15 bytes upon THRE, then the bug is not exposed.

**Attach the binaries**

[ser2ser-binaries.zip](https://github.com/stsp/dosemu2/files/2742584/ser2ser-binaries.zip) (ser2ser2 runs on DOS side, ser2ser3 runs in dosemu.)

**Attach the log**

Here's the [boot.log](https://github.com/stsp/dosemu2/files/2742593/boot.log). Unfortunately when I enable logging with -D+9s, the transmission loses a lot of its data so I can't give you that log (it would be useless I reckon).

**Comment by ecm-pushbx** [comment]
I removed "-D_DEBUG_RX_OFFSETS=1024" from the command lines given here, but the binaries in the attached archive were built with that option. This should not affect the bug though, just mentioning it for completeness.

**Comment by ecm-pushbx** [comment]
> when transmitting a long string,

(From the ser2ser3.com running in dosemu, to the receiving ser2ser2.com on the DOS machine.)

**Comment by stsp** [comment]
Try lower debug levels, like -D2+s.
Try KVM instead of cpu_emu.
Without a lot it would be impossible to do
something. Besides, if the traffic is
uni-directional, you can use cat or socat
to monitor it w/o dosemu2 to make sure
it is otherwise valid.

**Comment by ecm-pushbx** [comment]
I reran the test with -D1+s on the dosemu side. This sometimes results in various different corruptions of the transmitted string, but occasionally I can reproduce a specific error pattern. The received text then starts as:

    This is a very long test string. It serves te purpose of
    dmonstrating tha our interrupt-riven routines re capable

And this is the boot.log: [boot.log](https://github.com/stsp/dosemu2/files/2783052/boot.log)

Note that it says "SER0: ERROR: TX overrun" for each of the missing characters.

**Comment by stsp** [comment]
This just means that you don't check LSR
before writing. Sorry but this is your bug.

**Comment by stsp** [comment]
```
SER0: Func transmit_engine requesting TX_INTR
SER0: Func pic_request intlevel=11, int_requested=2
SER0: Func pic_request intlevel=11, int_requested=0
SER0: Transmit 0xa
SER0: Transmit 0x61
SER0: ERROR: TX overrun
```

In TX handler you sent 2 bytes w/o checking LSR in between.

**Comment by ecm-pushbx** [comment]
https://stackoverflow.com/a/43686410/738287 

>> The transmitter holding register interrupt (02) occurs when the XMIT FIFO is empty; it is cleared as soon as the transmitter holding register is written to (1 to 16 characters may be written to the XMIT FIFO while servicing this interrupt) or the IIR is read.

When I get THRE from the LSR once, writing 16 data words should be allowed to fill the FIFO. **Without** re-checking LSR for each word.

**Comment by ecm-pushbx** [comment]
With this patch, the test successfully transfers the entire string.

```
$ git diff
diff --git a/src/base/serial/ser_ports.c b/src/base/serial/ser_ports.c
index f20643197..536b4bdb0 100644
--- a/src/base/serial/ser_ports.c
+++ b/src/base/serial/ser_ports.c
@@ -329,7 +329,7 @@ static void put_tx(int num, char val)
   }
   /* Else, not in loopback mode */
 
-  if (!(com[num].LSR & UART_LSR_THRE)) {
+  if (0 && !(com[num].LSR & UART_LSR_THRE)) {
     s_printf("SER%d: ERROR: TX overrun\n", num);
     /* no indication bit for this??? */
     return;
```

**Comment by ecm-pushbx** [comment]
http://www.sci.muni.cz/docs/pc/serport.txt

> You might call this a bug, though: in FIFO mode, THRE (bit 5 or LSR) is cleared when there is at least one character in the Tx FIFO, not if the FIFO can't take any more bytes; that's rather absurd, but that's the way it is.

That is, when THRE is **set**, the entire FIFO is empty, so should allow 16 words to be written to it.

**Comment by stsp** [comment]
You are right, thanks!
