### ISSUE TITLE
Transmitting between two dosemu instances' serial ports drops data

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#749]
**Describe the bug**
Connecting two dosemu's serial ports to one another (using socat), then sending a long string with a serial communications test program (link given below), causes most of the string's data to be dropped. It appears to be non-deterministic exactly which bytes are dropped, but it's always a majority.

The following two screens are from the same run, pressing F1 from each dosemu once:

```
About to Execute : ser2ser2.com
 
This is a very long test string. It serves the purpose of
demonstrating that our interrupt-driven routines are capable
of c't lose
a single character as long as you don't overload the fifos, no
matter how hard you try!
```

```
About to Execute : ser2ser2.com
 
This is a very long test string. It serves the purpose of
demonstrating that our interrupt-driven routines are capable
of cwon't lose
a single character as long as you don't overload the fifos, no
matter how hard you try!
```

**To Reproduce**

Test program's source is at https://bitbucket.org/ecm/serialp/src/81d0ef29635c1a415a00f0addcea968123642f8f (+ lmacros from the same bitbucket.org account)

Preparation:

    $ ./mak.sh -D_ECHO_RX_TO_TX=0 -D_RX_OUTPUT_ADD_LF=0 -D_RX_TO_TX_ADD_LF=0 -D_INTNUM=0Bh -D_OFFMASK=0000_1000b -D_UART_BASE=2F8h -D_DEBUG_RX_OFFSETS=1024 -D_BI_TX_FIFO_SIZE=15 && cp -a serialp.com ser2ser2.com
    $ socat pty,echo=0,raw,link=/tmp/vptty-1 pty,echo=0,raw,link=/tmp/vptty-2 & disown

One dosemu:

    $ dosemu -I"serial { com 2 device /tmp/vptty-1 }" -K "$PWD" -E ser2ser2.com

The other dosemu:

    $ dosemu -I"serial { com 2 device /tmp/vptty-2 }" -K "$PWD" -E ser2ser2.com

**Attach the binaries**
[ser2ser-binaries.zip](https://github.com/stsp/dosemu2/files/2742717/ser2ser-binaries.zip) (ignore ser2ser3.com in this file, it belongs to https://github.com/stsp/dosemu2/issues/748)

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/2742743/boot.log) (without -D+9s though, as specified in https://github.com/stsp/dosemu2/issues/748 this logging option seems to alter the result).

Did another run with -D+9s this time, here's the vptty-1 connected dosemu's screen:

```
About to Execute : ser2ser2.com

This is a very long test string. It serves the purpose of
demonstrating that our interrupt-driven routines are capable
of c
```

And here's the screen of the vptty-2 connected dosemu:

```
About to Execute : ser2ser2.com
 
This is a very long test string. It serves the purpose of
demonstrating that our interrupt-driven routines are capable
of coping with pressure situations like the one we provoke
l transmission and
reception should be programmed interrupt-driven. You won't lose
a single character as long as you don't ovrload the fifos, no
matter how hard you try!

```

Here's the boot.log after that: [boot.log](https://github.com/stsp/dosemu2/files/2742750/boot.log) (This seems to be from the vptty-2 connected dosemu.)

**Comment by stsp** [comment]
Please study the log a little.
It has the lines `SER0: Got data byte: 0xa` and alike.
It dumps all the traffic.
Please see if the missing bytes are still there.
If so - locate them and tell me exact lines in the log
to look into.
`Got data byte` means that dosemu reads these bytes.
`SER0: Receive 0x20` means that the DOS prog received
that byte. `SER0: Transmit 0x0a` means that DOS prog
sent the byte. Please have a search of an inconsistencies.
Instead of sending the lines of text, try sending the incremental
numbers. Then the inconsistencies will be much more visible
(even maybe up to the point where I'll stop asking you to look
for them yourself).

**Comment by ecm-pushbx** [comment]
Here's a useful script to make the log more readable. I'll continue trying to decipher it at another time.

$ cat boot.log | perl -pe 's/(Got data byte: |Receive |Transmit )(0x[0-9a-fA-F]+)/$1.$2.'"'"' "'"'"'.((hex($2) > 32 and hex($2) != 127) ? chr(hex($2)) : ".").'"'"'"'"'"'/ge' | grep --colour=always -E "Got data byte: |Receive |Transmit |" | grep --colour -E '"."|'

**Comment by stsp** [comment]
But why not to xmit the incremental numbers
instead of the text lines? You won't need any script!

**Comment by ecm-pushbx** [comment]
https://bitbucket.org/ecm/serialp/commits/4e292e772b7ee392d364cdff6f136e4592b07b2c

Without -D+9s (vptty-1 connected):

```
About to Execute : ser2ser2.com
 
0-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
1-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstubcdefghijklmnopqrstuv
wxyz
8-012
```

(vptty-2 connected):

```
About to Execute : ser2ser2.com
 
0-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
1-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu

```

This is the source:

```
long_text  db  0dh
%if _XMIT_INCREMENTAL_NUMBERS
	db "0-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "1-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "2-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "3-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "4-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "5-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "6-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "7-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "8-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db "9-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",13
	db 0
%else
```

**Comment by ecm-pushbx** [comment]
With -D+9s (vptty-1 connected):

```
About to Execute : ser2ser2.com
 
0-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
1-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuyz
5-0123456789ABCDEFGHIJKLMNOP
```

(vptty-2 connected):

```
About to Execute : ser2ser2.com
 
0-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
1-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstunopqrstuvwxyz

```

And the boot.log (vptty-2 connected): [boot.log](https://github.com/stsp/dosemu2/files/2755233/boot.log)

**Comment by stsp** [comment]
Your program is likely buggy.
In the code I can see it loops in interrupt
handler until IIR says go out. This is supposed
to be correct. But in the log there are just a
couple of IIR reads during the entire session,
and the internal buffers constantly overflow
and fifo timeouts signal the new IRQs.
Your code works not in the expected way.

**Comment by stsp** [comment]
And despite things like
`SER0: Receive timeout (128 bytes), requesting RX_INTR`
(maximum buffer fillup), I still see `Receive xx` messages
are consistent. Don't see any gaps. So your prog reads
valid data and drops it elsewhere.

**Comment by ecm-pushbx** [comment]
Result: "Transmit" lines list all the data sent by this dosemu. "Got data byte" lines also list all the data we want to receive. "Receive" *also* lists all the data we want to receive.

I added _DEBUG_LOSTCOUNTER https://bitbucket.org/ecm/serialp/commits/f696f4ccd20d7f0c975e1a0ecefd7759c2f8e31d and observe eg 

```
SER2SER2.COM
-g
 
0-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
1-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
2-0123456IJKLMNOPQRSTUVWXYZabcdefghijklmnSTUVWXYZabcdefghEFGHIJKLMNOPQRSTDEFGHIJ
KLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
Detected Control pressed 5 seconds
AX=010A BX=F10D CX=0010 DX=0000 SP=FFFA BP=0000 SI=0652 DI=0000
DS=13AB ES=F000 SS=13AB CS=FF10 IP=0000 NV UP EI PL ZR NA PE NC
FF10:0000 F4                hlt
-r
AX=010A BX=F10D CX=0010 DX=0000 SP=FFFA BP=0000 SI=0652 DI=0000
DS=13AB ES=F000 SS=13AB CS=FF10 IP=0000 NV UP EI PL ZR NA PE NC
FF10:0000 F4                hlt
-t
AX=010A BX=F10D CX=0010 DX=0000 SP=FFFA BP=0000 SI=0652 DI=0000
DS=13AB ES=F000 SS=13AB CS=13AB IP=0251 NV UP DI PL ZR NA PE NC
13AB:0251 9D                popf
-
AX=010A BX=F10D CX=0010 DX=0000 SP=FFFC BP=0000 SI=0652 DI=0000
DS=13AB ES=F000 SS=13AB CS=13AB IP=0252 NV UP EI PL ZR NA PE NC
13AB:0252 F8                clc
-
AX=010A BX=F10D CX=0010 DX=0000 SP=FFFC BP=0000 SI=0652 DI=0000
DS=13AB ES=F000 SS=13AB CS=13AB IP=0253 NV UP EI PL ZR NA PE NC
13AB:0253 C3                retn
-
AX=010A BX=F10D CX=0010 DX=0000 SP=FFFE BP=0000 SI=0652 DI=0000
DS=13AB ES=F000 SS=13AB CS=13AB IP=011D NV UP EI PL ZR NA PE NC
13AB:011D 73F8              jae     0117                                jumping
-d cs:64c l 2
13AB:0640                         -            8D 01                   ..
-
```

[boot.log](https://github.com/stsp/dosemu2/files/2755604/boot.log)

This means that the receive buffer (128 byte) overflowed: https://bitbucket.org/ecm/serialp/src/f696f4ccd20d7f0c975e1a0ecefd7759c2f8e31d/serialp.asm?fileviewer=file-view-default#serialp.asm-275

```
int_rx:
  mov  si, word [rxhead]
irx_more:
  mov dx, [baseport]
  in al, dx		; read from RBR
  mov  byte [si], al
  mov ax, si
  inc  si
  ; check for wrap-around
  rx_checkwrap
  cmp word [rxtail], si
  je @FF
  ; see if there are more bytes to be read
  add dx, 5
  in al, dx		; read LSR
  test al, 1		; Data Available ?
  jnz irx_more
.end:
%if _DEBUG_RX_OFFSETS
	call update_rx_offsets
%endif
  mov word [rxhead], si
;  test al, 20h	; Transmitter Holding Register Empty ?
;  jnz int_tx	; yes, do transmit next -->
	; Sometimes when sending and receiving at the
	; same time, TX ints get lost. This is a cure.
;  retn
  jmp int_tx		; (this checks for THRE)

@@:
  mov dx, [baseport]
  in al, dx		; read RBR (discard)
%if _DEBUG_LOSTCOUNTER
  inc word [lostcounter]
%endif
  db __TEST_IMM16	; (skip mov)
@@:
  mov si, ax
  add dx, 5
  in al, dx		; read LSR
  test al, 1		; Data Available ?
  jnz @BB
  jmp .end
```

This is because dosemu to dosemu connections do not consider the timing indicated by the programmed baud rate, but seem to send all data immediately. When sending from a real serial port on a physical DOS machine to a dosemu instance, the timing means that the 128-byte buffer doesn't overflow. (As indicated in https://github.com/stsp/dosemu2/issues/748 which has a different bug.)

**Comment by ecm-pushbx** [comment]
Why should I read IIR between each character? Whenever IIR indicates there is something to be read, the code reads a word then polls the LSR bit "Data Available" and loops as long as it is set.

**Comment by stsp** [comment]
OK, so this problem is that your internal buffer
overflows? Should be closed then?

**Comment by ecm-pushbx** [comment]
The problem is that dosemu seems to receive/transmit data as fast as possible, which in the case of a socat connecting two dosemu instances overflows my buffers. If it really transmitted at 9600 baud, it wouldn't overflow the buffer.

**Comment by stsp** [comment]
You can as well not transmit that fast
on another end. dosemu won't transmit faster
than you do.
Plus it is not prone of losing chars, so if you
take some time to process the chars, nothing
bad will happen. Don't overflow your buffer, you
have everything needed for that.

**Comment by stsp** [comment]
Use flow control.

**Comment by ecm-pushbx** [comment]
> Plus it is not prone of losing chars, so if you take some time to process the chars, nothing bad will happen. Don't overflow your buffer, you have everything needed for that.

To avoid the overflow I need to "wait" until the buffer is drained. But what interrupt would I use to indicate that?

**Comment by stsp** [comment]
For what? dosemu does not drop chars, it will
give you as much time as you want to process
any data.
Use flow control to shut up the other end, process
all the data, then allow further traffic. This is how
the properly written prog should behave.
Or use real uart, but even with real uart your prog
is not guaranteed to be scheduled fast enough, so
eventually you may need to read large chunks.

**Comment by ecm-pushbx** [comment]
> Or use real uart, but even with real uart your prog is not guaranteed to be scheduled fast enough, so eventually you may need to read large chunks.

But in practice it is fast enough to deal with the data, at least when running at 9600 baud.

So is this "won't fix"?

**Comment by stsp** [comment]
Yes, and maybe you can ask socat authors
if they can implement speed control, but this
is very unlikely.
So what is there about #748?
Are you sure its not your prog losing data?

**Comment by ecm-pushbx** [comment]
I am fairly certain, yes.

**Comment by ecm-pushbx** [comment]
> Yes, and maybe you can ask socat authors if they can implement speed control, but this is very unlikely.

Mhmm. socat does already have speed options, but they seem to only set the speed of actual serial ports, not anything in the software that'd be relevant for us.

**Comment by stsp** [comment]
Yes, that's what I mean.
They have the speed options, so maybe it
could make some (very-very slightly above zero)
sense to implement speed control for the
backends where HW speed control doesn't work.
But I wouldn't bet on that.
Another solution is to write your own bridge that
will connect 2 PTYs and emulate speed. This looks
the most plausible, considering that only your prog
needs this.

**Comment by stsp** [comment]
If you only disable interrupts in IER, then
it is still not enough. The data queue keeps
growing underneath of dosemu2. Its good
that it works for your test-case, but once it
breaks on a more heavy traffic, don't tell me
you hasn't been warned. :)
I would suggest sending XOFF and then
suck up the entire queue, then XON.

**Comment by ecm-pushbx** [comment]
I do get "Too many bytes (128) in buffer" multiple times with my example, and it ultimately does receive all characters anyway. So the buffer of the OS (I assume) seems to handle this correctly.

**Comment by stsp** [comment]
Yes, but 2 problems.
1 - system buffer is also not unlimited
2 - If you buffer that much, you can't really
do any practical bi-derectional communication,
as you will reply to the bytes that were sent
long ago. For example, I tried to enlarge the
xmit buffers to some large sizes, and some
serial port UC firmware loaders failed to work.
I understand there may be no problems for
your current setup, but XOFF is the right way
of solving things. Sadly, there is probably no
protocol in linux PTYs to allow us to emulate
RTS/CTS, and until someone implements it,
XOFF should be used.

**Comment by ecm-pushbx** [comment]
> For example, I tried to enlarge the xmit buffers to some large sizes, and some serial port UC firmware loaders failed to work.

What do you mean by UC? "Micro Controller"?
