### ISSUE TITLE
 ERROR: Neither FreeDOS nor comcom32 installation found.

### ISSUE THREAD

**Issue by RossBoylan** [stsp/dosemu2#754]
**Describe the bug**
When I try to start dosemu it complains that it can't find a DOS.
The particular ones it lists are probably not present, but I did install fdpp.
Or maybe that's just a warning and the trouble is elsewhere.  Here's the transcript, running inside of emacs:

``
ross@secure-stretch:~$ dosemu &
[1] 13719
ross@secure-stretch:~$ ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: Fault in dosemu code, in_dpmi=0
ERROR: cpu exception in dosemu code outside of VM86()!
sig: 8 trapno: 0x13  errorcode: 0x00000000  cr2: 0x00000000
eip: 0x7f0498d8ec0a  esp: 0x7fff50222b90  eflags: 0x00010246
cs: 0x0033  ds: 0x0000  es: 0x0000  ss: 0x002b
fs: 0x0000  gs: 0x0000
fsbase: 0x7f049d365700 gsbase: (nil)

ERROR: Please install gdb, update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/stsp/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

ERROR: Fault handler re-entered! signal=11 _trapno=0xE
Terminated with signal 127

[1]+  Exit 255                dosemu
``

**To Reproduce**
Environment was a Debian stretch VM under VirtualBox 4.3. amd64 architecture for host and VM
Got fdpp and dosemu2 from github.  Installed build-dependencies.
In top-level directory of each project did
 dpkg-buildpackage -b -ui
which is a standard way to build Debian packages (make deb is not, though it ends up doing the same thing).
Installed the packages including the symbols package.  
I installed fdpp before building dosemu2 (though not before my first attempt, so maybe config didn't have a chance to find it?).
I had Debian's dosemu package installed; the installation of dosemu2 kicked it out.  I manually renamed ~/.dosemu and ~/.dosemurc to move them out of the way before my first run of the new dosemu.

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/2757247/boot.log)

Also, at the end of the dosemu2 build it issues this warning:
``
---------------------------------DONE Installing-------------------------------

WARNING
No FreeDOS tarball (/home/ross/src/dosemu2/dosemu-freedos-1.0-bin.tgz)
found. If you are not
upgrading a working existing installation then please download one
from http://www.dosemu.org and re-run make install.
You can also use this procedure to upgrade an existing *FreeDOS*
installation when a new tarball is available.
Alternatively you can set fdtarball to none in compiletime-settings
and use another DOS, which can be installed using dosemu -install,
referred to using $_hdimage in /etc/dosemu/dosemu.conf or ~/.dosemurc
or symbolically linked from ~/.dosemu/drives/c.
``
Below that, presumably unrelated but FYI:
``
make[1]: Entering directory '/home/ross/src/dosemu2'
dh_shlibdeps -X.so
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/dosemu2/usr/bin/dosemu.bin was not linked against libz.so.1 (it uses none of the library's symbols)
dh_shlibdeps -- -dRecommends -pshlibs-
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/dosemu2/usr/bin/dosemu.bin was not linked against libz.so.1 (it uses none of the library's symbols)
``

**Comment by stsp** [comment]
It crashes somewhere in libSDL2.
You need to install dbgsym for libsdl2 and re-do the log.
Another thing to try is `dosemu -X`

**Comment by stsp** [comment]
> /dosemu.bin was not linked against libz.so.1 (it uses none of the library's symbols)

Unfortunately some version of libbfd require it, see #566.
But its harmless.

**Comment by stsp** [comment]
vde was just forgotten to remove from debian/rules.
It is now done.
As for window closing right away, I suppose it
every time adds the message
`ERROR: Bootable drive not found, exiting`
It shouldn't just close w/o any error.

[comcom32.exe.gz](https://github.com/stsp/dosemu2/files/2757768/comcom32.exe.gz)
This is a command.com, gzipped.
It is built from here:
https://github.com/stsp/comcom32
but so far you can't easily build it, so I am attaching.
Put `comcom32.exe` into `/usr/local/share/comcom32`
and symlink to `command.com` in the same dir.
After that, dosemu2 should start normally (with `-X`
in your case).

**Comment by RossBoylan** [comment]
I took your latest changes from github and installed comcom32 as instructed.
I can now launch with dosemu -X, and I seem to have a working dos prompt.

The startup message refers to ~/.dosemurc, but that file isn't used anymore, right?

I also found out where the symbols are: I needed to add
deb http://debug.mirrors.debian.org/debian-debug/ stretch-debug main non-free-contrib
to /etc/apt/sources.list.  I installed the sdl symbols, but fortunately they may not be necessary.

From a debian standpoint, to get a functional package something should be done about comcom32.

**Comment by RossBoylan** [comment]
Even in a regular terminal, dosemu without the -X just crashes.  Should that work?

**Comment by RossBoylan** [comment]
Huge win! I had a critical operation that caused an exception every time I ran it in dosemu.  dosemu2, as packaged above, sailed right past the problem spot.

This is a huge relief, since all my financial records are in the DOS program Managing Your Money.

Thanks very much.

**Comment by stsp** [comment]
So have you managed to produce
the new crash log? I dont see one.

**Comment by RossBoylan** [comment]
> .dosemurc can still be used, but its
> just an override to global config. Its
> not created by default. It is mentioned
> only on first boot, so doesnt seem to
> hurt.
My concern with the message about .dosemurc was not the name but the location; the startup text says it's in ~/, but I saw some other comment in the code that it had moved to the directory ~/.dosemu/.  I don't recall whether it still had a "." in front.
Ross

**Comment by RossBoylan** [comment]
On the crash log: it's not crashing anymore.  Do you still want to see boot.log?

**Comment by stsp** [comment]
~/, but I saw some other comment in the code that it had moved to the directory ~/.dosemu/.

The old location is still checked, but I changed the
comment for the sake of completeness.

> On the crash log: it's not crashing anymore. Do you still want to see boot.log?

No, but please re-open this once you get a crash log.
Did it stop crashing after installing debug info or what?

**Comment by RossBoylan** [comment]
It stopped crashing after I installed comcom32 and the symlink for command.com.
Using the -X argument was important too, I think.
I had installed the debug symbols at that point, but I don't think that was necessary to avoiding the crash; it certainly wasn't sufficient.
Ross

________________________________________

**Comment by stsp** [comment]
In this case please undo everything
and attach the log of the crash with
debug symbols installed.

**Comment by stsp** [comment]
Much better log, thanks!
Now please install the source package
of sdl2 and upload here the file called
SDL_x11modes.c

**Comment by stsp** [comment]
FYI bad or missing interpreter msg in
fdpp can be interrupted with ^D

**Comment by stsp** [comment]
Thanks, should now be fixed.

**Comment by RossBoylan** [comment]
I can confirm, after rebuilding with the latest develop branch, that when I invoke with dosemu and no comcom32 there is no hard error.  A DOS window opens and it complains it can't find command.com.

After restoring comcom32, dosemu seems to produce a working DOS session.

So I don't need to use the -X argument to get a window anymore?

**Comment by stsp** [comment]
-X is now default for you.
Your SDL is too old, and is disabled.

**Comment by RossBoylan** [comment]
SDL2.0.5 is too old?  It looks as if 2.0.9 is the latest upstream released version.
Or perhaps the fact that SDL 1.2 is also on the system is messing things up?

**Comment by stsp** [comment]
> SDL2.0.5 is too old?

Yes, 2.0.6 is minimum, INSTALL says that.

**Comment by stsp** [comment]
> From a debian standpoint, to get a functional package something should be done about comcom32.

FYI, I added the comcom32 package to launchpad.
Its not building from sources, just takes the pre-built
binary. But its much better than nothing.
Things now work.

**Comment by ZoccoCss** [comment]
I'm installing the software on a fresh Debian 9.9 and I get the same message on the log file. It is very strange because I can run the program perfectly on another Debian 9.9 computer. It seems to me that I am missing a library at the time of compilation. No custom modifications this time. 

I'm attaching the bootlog and screenshot. 

![Screenshot from 2019-05-03 09-55-34](https://user-images.githubusercontent.com/47893772/57142065-a94f3b80-6d89-11e9-86c1-30f2beab2aa2.png)

[boot.log.gz](https://github.com/stsp/dosemu2/files/3142176/boot.log.gz)

**Comment by stsp** [comment]
Please open new tickets for bugs.
