### ISSUE TITLE
Question: Why do I get in_dpmi_pm=0x00 within run_pm_int all the time?

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#756]
When I capture the stack frame created by run_pm_int (at https://github.com/stsp/dosemu2/blob/90d8c65760aa0540f7c3d27286fc1603443e7db9/src/dosext/dpmi/dpmi.c#L2823 ), the in_dpmi_pm seems to always evaluate to zero.

(I want to enable my debugger to use this stack frame in order to break out of debuggee execution in Protected Mode, similar to what I already do in 86 Mode using an interrupt 8 handler. Only the stack frame for PM exceptions is well-defined by the DPMI spec, but dosemu also seems to provide a certain stack frame for interrupts.)

dosemu command:

`$ dosemu -K "$PWD" -E "debugx.com dpmiint8.com" -I "serial { com 2 device /tmp/vptty-dos }" -D+9M`

Screen text:

```
Welcome to dosemu2!
    Build 2.0pre8-20190114-862-g90d8c6576
About to Execute : debugx.com dpmiint8.com
About to Execute : debugx.com dpmiint8.com
Determining processor type
Found 186+ processor
Found 286+ processor
Found 386+ processor
Found 486+ processor
Found processor with CPUID support
Executing CPUID 0
CPUID 0 executed
Executing CPUID 1
CPUID 1 executed
Determining floating-point unit
DPMIINT8.COM
DPMIINT8.COM
-r dco |= 4000
Protected mode breakpoint at 015Ah.
32-bit code segment breakpoint at 016Ch.
 
Welcome in 32-bit protected mode.
```

Serial line text:

```
lDebugX connected to serial port. Enter KEEP to confirm.
= keep
-g
Unexpected breakpoint interrupt
AX=0200 BX=00E6 CX=0205 DX=000A SP=FFFC BP=0000 SI=03AB DI=F500
DS=14F4 ES=24F5 SS=14F4 CS=14F4 IP=013B NV UP EI PL ZR NA PE NC
14F4:013B 89E5              mov     bp, sp
-t
AX=0200 BX=00E6 CX=0205 DX=000A SP=FFFC BP=FFFC SI=03AB DI=F500
DS=14F4 ES=24F5 SS=14F4 CS=14F4 IP=013D NV UP EI PL ZR NA PE NC
14F4:013D B80100            mov     ax, 0001
-
AX=0001 BX=00E6 CX=0205 DX=000A SP=FFFC BP=FFFC SI=03AB DI=F500
DS=14F4 ES=24F5 SS=14F4 CS=14F4 IP=0140 NV UP EI PL ZR NA PE NC
14F4:0140 FF5E00            call    far [bp+00]
-
AX=0001 BX=00E6 CX=0205 DX=000A SP=FFF8 BP=FFFC SI=03AB DI=F500
DS=14F4 ES=24F5 SS=14F4 CS=F000 IP=F500 NV UP EI PL ZR NA PE NC
F000:F500 53                push    bx
-
AX=0001 BX=00E6 CX=0205 DX=000A SP=FFFC BP=FFFC SI=03AB DI=F500
DS=00AF ES=00B7 SS=00AF CS=00FF IP=0143 NV UP EI PL NZ NA PO NC
00FF:0143 7315              jae     015A                                jumping
#g
Unexpected breakpoint interrupt
AX=0200 BX=00FF CX=40FB DX=000A SP=FFFC BP=FFFC SI=03CF DI=F500
DS=00AF ES=00AF SS=00AF CS=00FF IP=0185 NV UP EI PL ZR NA PE NC
00FF:00000185 66B80402      mov     ax, 0204
#g
Unexpected breakpoint interrupt
AX=0000 BX=0040 CX=0000 DX=FFB5 SP=FFFC BP=FFFC SI=03CF DI=F500
DS=00AF ES=0117 SS=00AF CS=00FF IP=01E4 NV UP EI PL NZ NA PO CY
00FF:000001E4 66B80502      mov     ax, 0205
#d 268
00AF:0260                         -30 00 00 00 97 00 10 00         0.......
00AF:0270  00 00 B7 00 AF 00 01 90-90 90 90 90 90 90 90 90 ................
00AF:0280  80 16 00 00 01 00 00 00-00 F5 00 00 CF 03 00 00 ................
00AF:0290  17 01 00 00 AF 00 00 00-05 00 00 00 97 00 00 00 ................
00AF:02A0  46 32 01 00 C9 01 00 00-FF 00 00 00 FC FF 00 00 F2..............
00AF:02B0  AF 00 00 00 00 00 00 00-00 00 00 00 F0 00 00 00 ................
00AF:02C0  FF FF FF FF FF FF FF FF-FF FF FF FF FF FF FF FF ................
00AF:02D0  00 00 00 00 4E 6F 20 44-50 4D 49 20 68 6F 73 74 ....No DPMI host
00AF:02E0  20 69 6E 73 74 61 6C 6C-                         install
#g

Program terminated normally (0000)
-
```

This is the data section that starts at address 268h:

```
	align 4
data:
.old_int_8:	times 6 db 0
	align 4
.int_8_counter:	dd 0
.pspsel:	dw 0
.stacksel:	dw 0
.in_int_8:	db 1
	align 16
.stackdump:	times 4 * (6 + 10 + 4) db -1
		dd 0
```

And this is the build-up of the stack frame used by the interrupt 8 handler:

```
	align 2
int8handler:
	push ds
	push es
	push esi
	push edi
	push ecx
	push eax
```

Source, listing, and binary of dpmiint8.com are in [dpmi_int8_test.zip](https://github.com/stsp/dosemu2/files/2761684/dpmi_int8_test.zip) (I also added a DPMI-capable build binary of the debugger.) Here's the [boot.log](https://github.com/stsp/dosemu2/files/2761712/boot.log)

This is the stack frame decoded, first the lower words (created by my interrupt handler) and then the stack frame as set up by run_pm_int.
```
eax = 80 16 00 00
ecx = 01 00 00 00
edi = 00 F5 00 00
esi = CF 03 00 00
es = 17 01 00 00
ds = AF 00 00 00
eip = 05 00 00 00, cs = 97 00 00 00 (of the DPMI-host-internal breakpoint)
eflags = 46 32 01 00 (belongs to iret stack frame to DPMI-host-internal breakpoint)
eip = C9 01 00 00, cs = FF 00 00 00 (this is after the int 2F.1680 call at line 110 of dpmiint8.lst)
esp = FC FF 00 00, ss = AF 00 00 00 
in_dpmi_pm() = 00 00 00 00
reserved = 00 00 00 00
imr = F0 00 00 00
```

In the boot.log (which was created with -D+9M), there are also run_pm_int entries for 08h and 0Bh, which are all logged with "in_dpmi_pm=0x00".

I expected that in_dpmi_pm should be nonzero to indicate that the handler interrupted PM code. (cs = 00FFh and ss = 00AFh certainly are PM selectors.)

So, my question is, why do I receive zero there, and how does it work anyway? If I cannot find out this way whether PM code was interrupted, how do I tell in what mode execution will be returned (and thus whether to specify a selector or segment)?

**Comment by stsp** [comment]
You can use -D9+Mrg to see also
realmode and pic log. This will give
you a clue where the int arrived.
Besides, you can replace in_dpmi_pm()
call with zero and recompile, see if it
then crashes.
But what you do is not going to work.
There is always a pm address on stack,
regardless of this value.

**Comment by ecm-pushbx** [comment]
Here's the boot.log from running with -D9+Mrg: [boot.log.zip](https://github.com/stsp/dosemu2/files/2763728/boot.log.zip)

**Comment by stsp** [comment]
```
$ grep in_dpmi_pm=0x01 boot.log |wc -l
1
```
So your log indicates at least 1 arrival of IRQ8 from PM:
`DPMI: run_pm_int(0x08) called, in_dpmi_pm=0x01`
And it also indicates that your prog spends most of the
time calling realmode DOS services, so no surprise the
IRQs come from RM.
As I said, you are not supposed to look into this value.
The stack addr is always PM, you can't put RM addr
there.

**Comment by stsp** [comment]
I started win31 and logged lots of IRQ8s from PM.
So there is no bug here.
