### ISSUE TITLE
Scary warning message could lead to user deleting his DOS drives

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#758]
**Describe the bug**
If user has an old installation of dosemu tools then the following message is issued
~~~
ERROR: emufs is too old, ver 1 need 3
ERROR: emufs is too old, ver 1 need 3, but trying to continue
To upgrade you can remove ~./dosemu and it will be re-created.
~~~

Firstly the path is wrong it should be `~/.dosemu` anyway, but a user might actually do what it suggests and delete everything below ~/.dosemu including any DOS drives he has been using.

**Comment by stsp** [comment]
So many bugs in a single place...
Need to sleep better. :)
Thanks.
