### ISSUE TITLE
SYSTEM command mentioned in 'HELP' does not exist.

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#76]
This is the same as the ```unix``` command and can probably be removed from the help, unless it people use it and it is genuinely missing ?

**Comment by stsp** [comment]
Please remove it from help, thanks.

**Comment by stuaxo** [comment]
Will do, just working out where the help lives at the mo.

**Comment by stuaxo** [comment]
Turns out this is part of dosemu-freedos-1.0.bin.tgz

I guess this can be sorted at the same time as upgrading freedos, as seen in the sourceforge ticket:

https://sourceforge.net/p/dosemu/feature-requests/63/
