### ISSUE TITLE
Some Dosemu provided tools don't work under PC-MOS

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#760]
**Describe the bug**
Some(Most) of dosemu's tools don't work under PC-MOS 

**To Reproduce**
Boot PC-MOS
Try the following dosemu tools (note that the executable file dates are all in 1993)
 
#### these do work
~~~
[C:\DOSEMU]isemu
Dosemu version 2.0.0 detected
 
[C:\DOSEMU]fossil
dosemu FOSSIL emulator: disabled in config.
~~~

#### these don't work
~~~
[C:\DOSEMU]system ls
  
[C:\DOSEMU]exitemu

[C:\DOSEMU]lredir
~~~

**Comment by andrewbird** [comment]
And now I turn on debug flag for logging interrupts, and magically they work. I turn it off again and they still work. So I'll close for now, until I can reproduce reliably!

**Comment by stsp** [comment]
Does emufs.sys, ems.sys, umb.sys work?
What is "system ls"?

**Comment by andrewbird** [comment]
I think the problem was a one off, I haven't seen it since. Drivers seem to load, but as far as emufs.sys there's no redirector on pcmos so difficult to tell if it's functional.

**Comment by stsp** [comment]
So can you load MOS with dosemu's
config/autoexec? If so, maybe even
`dosemu -E` (aka system.com) works?
