### ISSUE TITLE
Custom COMMAND.COM ignored if COMCOM32 is available

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#765]
**Describe the bug**
Since commit 8318127b417e5f5960ca68aed4b37e61c327e947, a custom COMMAND.COM is ignored if COMCOM32 exist on the system. As a result, this triggers the "dos install" with all the side effects to the custom install.

**To Reproduce**
Extract the attached ZIP file and execute `./start.sh`.

**Attach the binaries**
[fdpp-test.zip](https://github.com/stsp/dosemu2/files/2799544/fdpp-test.zip)

**Comment by stsp** [comment]
I fixed MCB corruption in fdpp and "DPMI must be disabled" here.
More to come.

**Comment by stsp** [comment]
I've found quite a lot of small bugs with
your test-case, but not the ones you were
talking about.
Please use the following start-up line in your
test script:
`/usr/local/bin/dosemu.bin --Fimagedir $G_DOSEMU_HOME -f $G_DOSEMU_HOME/dosemurc
--Fdrive_c $G_DOSEMU_HOME/drive_c $@`

**Comment by stsp** [comment]
> but not the ones you were talking about.

No-no, "MCB corruption" was real and important one.
Though it was in fdpp, just as I expected.

**Comment by bolle732** [comment]
Updated FDPP and DOSEmu2 to latest Git version. Then used your start-up line.

Now, with COMCOM32 at it's place, I get:
```
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: general protection at 0x7fdcee74a3ef: 0
```
Without COMCOM32 available:
```
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: drive F: no device/file-name given!
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: plugin 0 not registered
ERROR: general protection at 0x7f2c6f72d3ef: 0
```
With my old start-up line (no `--Fdrive_c`), DOSEmu2 with FDPP and COMCOM32 starts up fine. If COMCOM32 isn't there, the shell is not found.

I'm a little bit lost now...

**Comment by stsp** [comment]
Didnt I say you to stop renaming
fdppkrnl.sys to kernel.sys? You went
even further than Andrew in these
"clever tricks", but not going to work.
I disabled also that hole, find another
one. :)

**Comment by bolle732** [comment]
Ok, sorry for the wrongly named `kernel.sys`. I moved to `fdppkrnl.sys` and the errors regarding `plugin 0` went away.

**Comment by stsp** [comment]
You can as well remove it, it is
now ignored. Dont try to feed
custom fdpp kernel - I removed
all possibilities, you won't find
any new holes. :)

**Comment by bolle732** [comment]
Now, with COMCOM32 in place, DOSEmu2 boots and use the custom `command.com` in my `drive_c`. But the install runs and creates the `drives` folder with all the drives I never use.

If I move COMCOM32 out of the way, there are 2 cases:

1. Folder `drives` exist from previous run:
DOSEmu2 boots with all the drives (in my case unwanted)

2. Folder `drives` does not exist:
DOSEmu2 doesn't boot
```
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: comcom32 not found, not doing install
ERROR: Bootable drive not found, exiting
```
Hm. I think I'm really unable to use this things any more as it seams I don't understand it correctly. Don't have the time to find another hole like you say. So it's your win.

I don't want to complain. A good default and some self healing for the standard setup is really fine. But I think a lot of old DOS users never worked with a complex setup. Most simply had a C: and maybe a D: for data or some like.

**Comment by stsp** [comment]
You can as well delete or remap these
drives with lredir2 - how could they do
any harm?

**Comment by stsp** [comment]
For the case 2 you can use the
variable it suggests and point it
to comcom32, and you are back
to case 1.

**Comment by stsp** [comment]
By the way, currently it is impossible
to delete the drive completely, you can
only remap it or un-network, but not
remove. But I think its easy to add such
capability to lredir2, just need to remove
the ready flag from cds, or something
like this. Andrew, what do you think?
Should we do a favor to the drive-haters? :)

**Comment by bolle732** [comment]
I'm not a drive-hater :( I only don't understand why you want to force everyone to that setup, as it has been working fine all the time before. Ok, you stated it several times and things will change. But I'm a minimalist and I like it KISS.

It looks very strange for me, especially with latest improvements to support more other DOSes like PC-MOS.

Is there a documentation what setups are supported ? Is my real problem the combination of FDPP and FreeCOM ?

**Comment by stsp** [comment]
> I only don't understand why you want to force everyone to that setup, as it has

Not everyone, just you and Andrew. :)
The thing is, there is already a compatibility
option that returns everything to 1-drive setup,
and there is of course still exists the loop-hole
to boot fdpp from it. But the default setup should
be worked on too, and if I just let you go with
the compatibility option, no one will tell me what
scenarios are not supported in the default setup.
So the idea is to keep implementing things, but
at the end you are not obligated to use them.
But at least you need to see them, and then
maybe you don't even want to get back. So far
some features are missing, so why not to implement
them, and rather ask for a compatibility option?
My proposal is just to work together for a while,
and see the result. Then act. You can't judge about
what is not yet done.

> It looks very strange for me, especially with latest
> improvements to support more other DOSes like PC-MOS.

You are probably confusing the MOS support with
MOS _build_ support. I am concerned about MOS
build under fdpp (currently fails), and Andrew is
concerned about MOS itself - its his playground and
he is currently the number 2 (number 1 actually)
contributor to the MOS project, according to the
github stats. Ask him why MOS is so important -
I don't know. :) I can only guess that he likes asm
over C++, and so chooses MOS and not fdpp.

> Is there a documentation what setups are supported ?
> Is my real problem the combination of FDPP and FreeCOM ?

The only problem that things are not written yet,
so a bit of patience will help. :) The idea is to keep
only one official and documented setup (fdpp), and
of course keep all other DOSes supported for those
who prefer the particular DOS. But given the level
of integration that is possible for fdpp, no other DOS
can be supported nearly as good.

**Comment by andrewbird** [comment]
> You can as well delete or remap these
drives with lredir2 - how could they do
any harm?

They get in the way for me when I want to test fatfs.

If course I'm bound to say let's have a --Fnomagicdrives, you know I want it. I also understand your motivation for the easy default fdpp/comcom setup for casual users, but I don't think they are mutually exclusive.

Currently I can test all the other DOS's by -Fimagedir with $_hdimage="dXXXXs/c" + $_bootdrive="c" and things don't get installed or drives mapped (as of yesterday when I tested anyway). If I want to do the same tests with fdpp I run a local patch that recognises `fdppkrnl.sys` back in the old place. I know that's bad and could create fdpp/kernel versioning problems with a file, but it could equally be a symlink to the matching fdpp kernel.

**Comment by stsp** [comment]
> same tests with fdpp I run a local patch that recognises fdppkrnl.sys

You can as well use FDPP_KERNEL_DIR I think.
Same effect, no patch.

> If course I'm bound to say let's have a --Fnomagicdrives, you know I want it.

Its there of course, but why can't your
tests use "any" letter instead? This is quite
inflexible to use the particular letter.
What functionality do you need for "any" letter?
Some env var to identify the extra drive?

**Comment by andrewbird** [comment]
> and Andrew is
concerned about MOS itself - its his playground and
he is currently the number 2 (number 1 actually)
contributor to the MOS project, according to the
github stats. Ask him why MOS is so important -
I don't know. :) I can only guess that he likes asm
over C++, and so chooses MOS and not fdpp.

Interestingly I don't know myself why I started contributing to pc-mos, but I don't think there'll be much more from me as I already unsubscribed three days ago as there's too much finger pointing there.

> You can as well use FDPP_KERNEL_DIR I think.

I think this used to work, but not recently. I'll try again

> Its there of course, but why can't your
tests use "any" letter instead?

Any letter is fine for MFS, but not fatfs or hdimage files. I guess it's the same reason you don't map the fdpp/comcom/tools drives  as W:,X:,Y:,Z: you need fatfs first before transitioning them to MFS?

**Comment by andrewbird** [comment]
I'm sure you are correct about repo ethics, but I don't really know what my motivation for getting involved was anyway. Perhaps I was looking for an 'out', and I hadn't invested too much time so far, so the choice was easy.

There are many other things to contribute to, perhaps I'll see about packaging djgpp for Debian. I did email DJ to see if he was interested in doing it, but I had no reply.

I mean that in a similar fashion to my needing to test fatfs drives and images, any DOS needs to see block device drives to boot from, network drive usage is not possible without starting the boot on fatfs.
I'm not suggesting you do this, but consider for a moment, could your FDPP boot from an MFS drive X:?

>  I suppose we can invent the hot-plug
for fatfs, i.e. create the new drives at run-time
by some tool.

That would be interesting, but is it possible that DOS could handle disk enumeration or geometry changes?

**Comment by stsp** [comment]
> There are many other things to contribute to, perhaps I'll see about packaging djgpp for Debian.

But there is already a repo with most of
the work done. It can DL binaries and build
them. All we need to do is to upload that
repo together with binaries (it can build them
if they are already DLed), and make sure
DESTDIR works. Thats basically it.
Maybe DESTDIR already works?

> I'm not suggesting you do this, but consider for a moment,
> could your FDPP boot from an MFS drive X:?

Why couldn't it?
If dosemu1 used to enable redirector when just
opening config.sys, then the answer is hell yes,
this is possible. So what is the problem with test
fatfs drive not being C or D?

**Comment by stsp** [comment]
So what do you think about some tool
(perhaps lredir2 extension) to add/remove
fatfs drives? Will this help?

**Comment by stsp** [comment]
@bolle732 Ok, it seems you need the following:
`/usr/local/bin/dosemu.bin -f $G_DOSEMU_HOME/dosemurc --Fdrive_c $G_DOSEMU_HOME/d
rive_c $@`
With that setup, no "drives" dir is created.
Is this what you need?

@andrewbird When you boot non-fdpp, all you
need is `$_default_drives = (off)`. They are
obviously not needed for other DOSes. The
question here is only how to properly adapt
your tests for fdpp. Is it really that difficult to
make then use non-fixed drive letter?

**Comment by stsp** [comment]
> Is there a documentation what setups are supported ?

Yes, default one and `$_default_drives = (off)` for non-fdpp.
2 supported setups.
But see recipe above to keep within the default setup.

**Comment by bolle732** [comment]
Ok, that's the comment I've been looking for. There has been so much forth and back, I lost it a little bit.

Thanks for mentioning the `$_default_drives = (off)`. With this and `--Fdrive_c` I can use FreeDOS / FreeCOM for a "stable" setup.

Regarding testing FDPP and COMCOM32, which is the correct way to have different CONFIG.SYS and AUTOEXEC.BAT for different DOS programs?

**Comment by stsp** [comment]
Yes but you dont have to disable
that option. There is a lot of unneeded
stuff for non-fdpp, but still the old
setups should work regardless.
So if w/o disabling default drives
you old setup breaks, please open
a bug. Extra drives are not a bug.
You can disable them later, and if
things work properly, I dont even
see why would you.

What do you mean by different
config.sys for different programs?
You usually dont need that.
There is a `$_emusys` option that
allows you to change config.sys
extension, say config.sy1. You put
that file on C and it will be loaded
(I hope it will prioritize it over fdconfig.sys
from D, or else please open a bug).

**Comment by stsp** [comment]
I mean, by just not changing imagedir
and only using --Fdrive_c, you already
get the setup that should match your
expectations. Let me know why it is not
true and what makes you to apply the
legacy option even in presence of
--Fdrive_c. My expectation was that
adding --Fdrive_c will close the gap
between 2 setups.

**Comment by bolle732** [comment]
> What do you mean by different
> config.sys for different programs?
> You usually dont need that.
> There is a $_emusys option that
> allows you to change config.sys
> extension, say config.sy1. You put
> that file on C and it will be loaded
> (I hope it will prioritize it over fdconfig.sys
> from D, or else please open a bug).

I think that different programs may have different memory requirements. Therefor I was thinking to control this over the `CONFIG.SYS`. Also I was thinking how to specify another `AUTOEXEC.BAT` so I can define aliases or run directly a program.

Will try the `$_emusys`, but it looks a little bit hackish.

I need some time to experiment so I can understand the details better. But first, I must clean up my setups. Too much files and dirs from old experiments.

**Comment by stsp** [comment]
> I think that different programs may have different memory requirements.

Default config.sys should cover all possible memory
requirements. In fact, memory is configured in dosemu.conf,
and config.sys only needs to "propagate" that setup to DOS.

> Also I was thinking how to specify another AUTOEXEC.BAT so I can define
> aliases or run directly a program.

Again, default autoexec allows you to execute the
command specified in `-E`, so will it run the program
or not, depends on the command line of dosemu.
You don't need to change default autoexec, just tell
it what to do with the command line of dosemu.
Probably it would be a good idea to allow autoexec
to look for some user-provided bat file on C, so that
the user can add some more stuff to the boot process.
But for now I haven't seen the need for this from users.
Of course if you change config.sys, you can as well
point it to the alternative autoexec via `SHELL=` string.

> Will try the $_emusys, but it looks a little bit hackish.

It is. It was supposed for dual-booters, who also have
the native config.sys that shouldn't be run by dosemu.
