### ISSUE TITLE
relocate boot drives

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#771]
Currently they are D-F.
Relocate elsewhere, and make it so that the
driver letters are not hard-coded in config/autoexec.

**Comment by stsp** [comment]
All extensions to make drives relocatable, are
implemented here and in fdpp.
They are quite interesting.
For example, you can now pass env block
from dosemu to fdpp, and autoexec is now
different (called autofdpp.bat).
There are no hardcoded drives in fdppconf.sys/autofdpp.bat.
Quite surprisingly, no extensions were needed
to any command.com. They all are ready to
expand the variables in their cmd line (not only
in a bat file they process). So the
`shellhigh=command.com /e:1024 /k %FDPP_AUTOEXEC%`
works with any command.com.

**Comment by stsp** [comment]
So now there is no longer the install, and also
the boot drives can be relocated.

@andrewbird @bolle732 
Can we now re-hash your requirements and see
if you still can't use the new features w/o the compatibility
options? I can't promise to keep the compatibility
layout forever, even if I am not going to remove it
right now. So it would be nice to see if the current
knobs allow you to control everything you want, or
more work is still needed.

**Comment by bolle732** [comment]
My FreeDOS based setup still runs fine with the latest changes.

The startup line is `/usr/local/bin/dosemu.bin --Fimagedir $G_DOSEMU_HOME -f $G_DOSEMU_HOME/dosemurc --Fdrive_c $G_DOSEMU_HOME/drive_c $@`.

I use `$_hdimage = "./drive_c"` and still `$_default_drives = (off)` to suppress the drives `D:` to `G:`.

**Comment by bolle732** [comment]
Out of curiosity, what is the reason for the naming "fdconfig.sys" and "autofdpp.bat" ? In my eyes, "fdppconf.sys" and "fdppauto.bat" could be clearer. This distinguishes better from FreeDOS and use the same naming schema for both files.

**Comment by stsp** [comment]
But $_default_drives will likely soon
disappear. One can't stick to compat
options forever.

But it is already fdppconf.sys, not
fdconfig.sys.

**Comment by bolle732** [comment]
In my `~/.dosemu/drive_c` I have:
```
command.com -> /usr/local/share/comcom32/command.com
fdconfig.sys -> /usr/local/share/dosemu/dosemu2-cmds-0.2/fdconfig.sys
```
This has been created today with DOSEmu2 from git. Maybe I did something wrong ?

Regarding `fdppconf.sys`, I still like more `fdppauto.bat` then `autofdpp.bat` for consistency sake.

**Comment by stsp** [comment]
> This has been created today with DOSEmu2 from git. Maybe I did something wrong ?

This is for compatibility with FreeDOS.
It should not be used by FDPP.
But thanks for reminding me, I should probably remove also that.

> Regarding fdppconf.sys, I still like more fdppauto.bat then autofdpp.bat for consistency sake.

If you look at src/bindist, you'll find there also autoemu.bat,
which comes from dosemu1 or even earlier. I just followed
that tradition. autofdpp.bat still suggests an autoexec.bat's
derivative, while fdppauto.bat can't be tracked back to autoexec.

**Comment by bolle732** [comment]
It was only a suggestion. If you prefer that name for historical reason, that's OK.

**Comment by stsp** [comment]
I removed the remaining freedos symlinks from install.
HTH.

**Comment by stsp** [comment]
Do you think that the fdtarball support should just
as well be removed? Or too early? Hmm...

**Comment by bolle732** [comment]
I never used fdtarball... I use my hand-selected kernel and command from FreeDOS.

So, this is up to you and others to decide.

**Comment by stsp** [comment]
Any reason you dont use comcom32?
Not that you have to, but it would be good to
know why freecom is better.

**Comment by bolle732** [comment]
I'd liked to use comcom32. But it seems that comcom32 forces me to use EMS along with DPMI. For my real needed (productively) setup I only want conventional, UMB, HMA and XMS...

Further, I couldn't keep up with all the changes back and forth which consumed my rare spare time. So I had to decide to let this tests at the side for the moment.

**Comment by stsp** [comment]
But I thought I fixed this EMS problem long long ago!

**Comment by bolle732** [comment]
It's not a problem that it doesn't work. I only disliked to have them activated floating around... So, I really need to do a retry.

**Comment by stsp** [comment]
You don't need to activate EMS. I fixed that
from the first time you reported that, and let
you know that I did so.

**Comment by stsp** [comment]
There was also the MCB corruption problem, at
the same report of yours, and I fixed also that.

**Comment by bolle732** [comment]
Oh yes, my memory gets old. EMS isn't loaded.

**Comment by bolle732** [comment]
At the moment I encounter some problem:
```
ERROR: fdpp booting, this is very experimental!
ERROR: booting with comcom32, this is very experimental
ERROR: unknown return value from vm86()=6,6-1
Not a good day to die!!!!!
```
Need to check tomorrow.

**Comment by stsp** [comment]
Should probably now be fixed.

**Comment by bolle732** [comment]
Thanks, the error has gone.

Now, it hangs forever while loading PC/GEOS. Should I better open another ticket ?

**Comment by stsp** [comment]
Yes please.
And check different settings of `$_cpu_vm`.
