### ISSUE TITLE
regression: no lfn support

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#776]
**Describe the bug**
There is no LFN support anymore

**To Reproduce**
1. Create a file with LFN name in .dosemu/drive_c
2. Boot dosemu
3. dosemu cannot see the long file name

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/2831007/boot.log)
![image](https://user-images.githubusercontent.com/7417263/52257292-dc319100-294c-11e9-8804-2972bc60d309.png)
![image](https://user-images.githubusercontent.com/7417263/52257351-1438d400-294d-11e9-8dd9-9040a48edbbc.png)

**Comment by ecm-pushbx** [comment]
Also, if you're using FreeDOS's FreeCOM, you need to pass the /LFN switch to DIR in order to make it list LFNs. As found in https://github.com/stsp/dosemu2/issues/769

**Comment by bpranoto** [comment]
> Not a git build.

this is from ppa

**Comment by andrewbird** [comment]
@bpranoto I suspect you may need to wait for the PPA to sync with git, as second revect support which is used by LFN, was broken for a short while. This may already have happened by the time you read this.

**Comment by bpranoto** [comment]
> @bpranoto I suspect you may need to wait for the PPA to sync with git as second revect support, which is used by LFN, was broken for a short while. This may already have happened by the time you read this.

Yes, I rebuild from source. All work fine now.

**Comment by stsp** [comment]
Note that LP builds also lack the
debug info. So while testing them
is valuable, there should be a git
tree around to check things.
