### ISSUE TITLE
AUTOFDPP.BAT sets path to only %DOSEMUDRV%:\dosemu

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#785]
**Describe the bug**
The new AUTOFDPP.BAT doesn't set the PATH variable properly to access my DOS commands.

```
$ ls -l /usr/local/share/dosemu/dosemu2-cmds-0.2/
total 28
-rw-r--r-- 1 root root  561 Feb 23 12:57 autoemu.bat
-rw-r--r-- 1 root root  770 Feb 23 12:57 autoexec.bat
-rw-r--r-- 1 root root  541 Feb 23 12:57 autofdpp.bat
-rw-r--r-- 1 root root  550 Feb 23 12:57 config.sys
drwxr-xr-x 2 root root 4096 Feb 23 12:57 dosemu
-rw-r--r-- 1 root root  260 Feb 23 12:57 fdconfig.sys
-rw-r--r-- 1 root root  237 Feb 23 12:57 fdppconf.sys
$ cat /usr/local/share/dosemu/dosemu2-cmds-0.2/autoexec.bat 
@echo off
rem autoexec.bat for DOSEMU + FreeDOS
path d:\dosemu;f:\bin;f:\gnu
set HELPPATH=f:\help
set TEMP=c:\tmp
sound /e
prompt $P$G
system -s CDROM_PATH
if "%CDROM_PATH%" == "" goto nocdrom
lredir -nC \\linux\fs%CDROM_PATH%
:nocdrom
system -s DOSDRIVE_EXTRA
if "%DOSDRIVE_EXTRA%" == "" goto nodrived
lredir -n \\linux\fs%DOSDRIVE_EXTRA%
:nodrived
rem uncomment to load another bitmap font
rem lh display con=(vga,437,2)
rem mode con codepage prepare=((850) f:\cpi\ega.cpx)
rem mode con codepage select 850
rem chcp 850
echo Welcome to dosemu2!
system -s DOSEMU_VERSION
echo     Build %DOSEMU_VERSION%
system -ep
if not "%DOSEMU_EXIT%" == "1" goto noexit
exitemu %ERRORLEVEL%
:noexit
if "%DOSEMU_KEEPDRV%" == "1" goto keepdrv
C:
:keepdrv
$ cat /usr/local/share/dosemu/dosemu2-cmds-0.2/autofdpp.bat 
@echo off
rem autoexec.bat for DOSEMU2 + FDPP
path %DOSEMUDRV%:\dosemu
set TEMP=c:\tmp
prompt $P$G
sound /e
system -s CDROM_PATH
if "%CDROM_PATH%" == "" goto nocdrom
lredir -nC \\linux\fs%CDROM_PATH%
:nocdrom
system -s DOSDRIVE_EXTRA
if "%DOSDRIVE_EXTRA%" == "" goto nodrived
lredir -n \\linux\fs%DOSDRIVE_EXTRA%
:nodrived
echo Welcome to dosemu2!
system -s DOSEMU_VERSION
echo     Build %DOSEMU_VERSION%
system -ep
if not "%DOSEMU_EXIT%" == "1" goto noexit
exitemu %ERRORLEVEL%
:noexit
if "%DOSEMU_KEEPDRV%" == "1" goto keepdrv
C:
:keepdrv
$
```

**Comment by stsp** [comment]
You can do things this way:
`dosemu 'path=f:\bin;%O'`
`%O` expands to the old path, and
there are other templates to play with.
I am planning to employ @jschwartzenberg 's
download scripts to install different DOSes,
which will also make sure the pathes are
correct. But this is somewhere in the future.

**Comment by ecm-pushbx** [comment]
Neither of these points addresses the issue. Why shouldn't the path for FDPP be the same as for FreeDOS ?

**Comment by stsp** [comment]
> Neither of these points addresses the issue.

The only way of addressing this issue, is to code a lot.
If you can do the work, then we can have a deal.

> Why shouldn't the path for FDPP be the same as for FreeDOS ?

Because there is no dosemu-freedos in FDPP.

**Comment by stsp** [comment]
And its unclear why `dosemu 'path=f:\bin;%O'`
doesn't address your problem.

**Comment by ecm-pushbx** [comment]
> And its unclear why dosemu 'path=f:\bin;%O' doesn't address your problem.

I don't want to enter that every time I start dosemu. If I have the FreeDOS and GNU stuff installed, I want FDPP to access these just the same as FreeDOS does.

> Because there is no dosemu-freedos in FDPP.

Right, but I can have both installed alongside each other.

> The only way of addressing this issue, is to code a lot.
> If you can do the work, then we can have a deal.

I'm not sure what work you mean. I just want dosemu to install the same PATH statement in AUTOFDPP.BAT as it does in FreeDOS's AUTOEXEC.BAT, provided that FreeDOS is installed too.

**Comment by stsp** [comment]
AUTOFDPP.BAT doesn't know what you have installed.
One way of doing thing is to see (from AUTOFDPP.BAT)
if c:\autoemu.bat is present, and if so, call it.
This file can be generated by the install scripts.
If its not a big work, patches welcome. :)

**Comment by stsp** [comment]
> I don't want to enter that every time I start dosemu.

No problems, then copy AUTOFDPP.BAT to C:\
and do the local modifications there. Any boot config
files can be overridden with a copy on C:\.

**Comment by ecm-pushbx** [comment]
Ah okay, thanks.

**Comment by stsp** [comment]
This should now be fixed.
