### ISSUE TITLE
Cups printing white pages

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/dosemu2#786]
I set up to print via CUPS-PDF and it worked very good from the command prompt. Next I ran a program and printed a report and got a blank page. I am attaching a -D9+ciT log file.

[boot6.log.gz](https://github.com/stsp/dosemu2/files/2902713/boot6.log.gz)

Is there something wrong with my setup?

**Comment by stsp** [comment]
See `$_lpt1` option in dosemu.conf
and the comments there.
If that doesn't help, you can print
to a file, like `$_lpt1 = cat >file`, and
then see with what command you can
print that file.

**Comment by stsp** [comment]
Simply saying, you can just print
to LPT2 which is pre-configured to
cups-pdf.

**Comment by ZoccoCss** [comment]
I've set up the dosemu.conf to print through cups-pdf

$_lpt1 = "lpr -P PDF"
$_lpt2 = "lpr -P PDF"

and when I run a comand from the prompt it works very well. For example if I run "dir > lpt1" I get the following file through cups-pdf.

[stdin___fina_PDF.pdf.gz](https://github.com/stsp/dosemu2/files/2905984/stdin___fina_PDF.pdf.gz)
 
Therefore, the setup seems correct. The problem is when I ask to print a report from the program that I get a blank page. 

I followed your suggestion and tested the command "$_lpt1 = "cat > /home/josefina/test" and Ii got my report !!!!!

[test2.gz](https://github.com/stsp/dosemu2/files/2906697/test2.gz)

I can open it through text editor and print it from there but if I run  "cat test2 | lpr -P PDF" I get a blank page again. 

It could be an issue with the special characters that the report gives to the printer that's causing the problem so I tried $_lpt1 = "cat | sed $'s/[^[:print:]\t]//g' | lpr -P PDF" but  dosemu.conf does not allow this type of commands. 

My conclusion up to this point, this is more a CUPS issue. For some reason it cannot interpret the format that the report is coming out. 

I want to use CUPS because in a second stage I'll set it up to print directly to a network printer.

**Comment by stsp** [comment]
It is likely that you specified the wrong printer type
in your DOS program. Try something like "generic text printer"
to avoid special chars.
Or you can try printing to PostScript and cups will
convert that to pdf.
