### ISSUE TITLE
Pass thorugh commands

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/dosemu2#789]
I'm setting up dosemu through a desktop shortcut launcher to run a dos program automatically and it seems to run prior to running the autoxec.bat.

Is it possible to run the autoexec.bat and the config.sys prior to the passing DOS command?

**Comment by stsp** [comment]
Neither config.sys nor autoexec.bat
do matter. What runs before any dos
command, is fdppconf.sys/autofdpp.bat.

**Comment by ZoccoCss** [comment]
Yes, fdppconf.sys/autofdpp.bat are the equivalent to config.sys/autoexec.bat in DOS and they are executed after the passing DOS command. 

I noticed this when setting up the shortcut and to verify it I made a test. One of the commands in my autofdpp.bat is to change to a different drive so the passing DOS command that I executed was "dir" and the result that I got was the directory of D: and the prompt that I had was that of the new drive (this lead me to believe that autofdpp.bat was properly configured)

**Comment by stsp** [comment]
To execute the commands under dosemu2, you
need to pass them via -E and -K command-line
switches. You are not supposed to do any local
mods in a config files, as this brings you an
unsupported (on this github) configuration.
There are additional -T and -U options that let
you do some advanced things.
If I do `dosemu -E dir`, the content is of drive
C, not any other drive, so I assume you did mods
to config files.

**Comment by ZoccoCss** [comment]
I just did dosemu dosemu -T -E dir and the directory I got was D:

I am attaching a picture. 

![captura de pantalla de 2019-03-01 09-23-24](https://user-images.githubusercontent.com/47893772/53641117-62678d00-3c04-11e9-9af5-0ac07e0db949.png)

I din't know that we were not supposed to modify the config and autoexec files. I'm not familiar with the -K -T and -U options so I will go back and learn how they can help me.

**Comment by stsp** [comment]
You are not supposed to put them on C drive too.
So if you remove them from C and repeat the command,
is it still D?

**Comment by stsp** [comment]
Hmm, what is S:?
This looks similar to the bug reported by @ecm-pushbx .
Can you provide me an ssh for this?

**Comment by stsp** [comment]
So you added lredir to S: to mimic the
nearby bug report, dispite I asked you to
not modify the config files, you gotta be
kidding. :(
Though I fixed a small bug with doing dir
on drive D. For me it didn't happen because
I put fdppconf.sys to C: before testing...

**Comment by ZoccoCss** [comment]
You are right. I didn't put fdppconf.sys/autofdpp.bat back in the default state to avoid adding more variables to the problem. Bad judgement call on my part.

**Comment by ZoccoCss** [comment]
Could you point me where I can find documentation on the use of the command-line
switches, specially -T -U and -K that you mention above? I didn't find it in -help nor in the internet.

**Comment by stsp** [comment]
In man.

**Comment by stsp** [comment]
Damn, no, wrong. :)

**Comment by stsp** [comment]
Well, they are indeed in the man...
But there seems to be some caching,
and if I do "man dosemu.bin", I am not
getting the up-to-date info...

**Comment by stsp** [comment]
One have to do the following:
`sudo rm /usr/local/man/man1/dosemu.bin.1 /usr/local/man/man1/dosemu.1`
in order to get the up-to-date man from /usr/local/share/man.
It seems older dosemu versions used to put man into /usr/local/man.

**Comment by ZoccoCss** [comment]
/usr/local/man/man1/dosemu.bin.1 and /usr/local/man/man1/dosemu.1 do not exist.  /usr/local/share/man is empty. 

I guess I can use https://github.com/stsp/dosemu2/blob/devel/man/dosemu.bin.1.in as the most up-to-date?

**Comment by stsp** [comment]
Since you are using pre-built packages,
remove "local" from all pathes.

**Comment by ZoccoCss** [comment]
Now I have clear how to use -T -U -E and -K to set up the path to run the program. 

What I don't know how to set up is the following. The program requires that in config.sys "Buffers=200 and files=200" also in autoexec.bat needs that the following line be added "SET 87=N"

**Comment by stsp** [comment]
What does `87=N` mean?
When I set it, Dos Navigator crashes.
But for example `86=N` is OK, `87=Y`
is OK too. So clearly it recognizes that
variable. Does it say to disable FPU?

Anyway, you can do this:
`dosemu -E set -T '87=N'`
and you'll see that the variable is set.
Another option is to write the custom
bat file, like startmypg.bat, that will set
this var and then run your prog.

Its a bit more difficult with config.sys's
buffers and files. For now the only way
is to put fdppconf.sys to drive C and do
the local mods to it. In the future I am
planning the hook files that will be called
from the main one. But I need some people
to request that functionality. Your voice for
that is counted.

**Comment by ZoccoCss** [comment]
These are requirements of the program in order to function properly. 

I found this on the web which explains what SET 87=N is for. 

As shipped, some of the Turbo Pascal programs make use of a numeric
coprocessor and others do not.  The first type of programs will sense a
coprocessor and use it when it is installed (otherwise they will emulate it). 
On some machines without a coprocessor, this detection procedure erroneously
reports presence of a coprocessor in which case the program will not run
properly.  The remedy is then to enter the DOS command, SET 87=n, which turns
off the sensing mechanism in the Turbo Pascal programs such that they work
without invoking a coprocessor.

Maybe under Dosemu I don't need not use this command.

**Comment by stsp** [comment]
Of course you don't.
Thanks for info, Dos Navigator is indeed
turbo-pascal written, so it senses that variable
(and crashes).

**Comment by ZoccoCss** [comment]
In regards to the config.sys, can I edit and move the fdppconfig.sys in linux to folder where the c drive is located or do I need to do this in DOS?

**Comment by stsp** [comment]
Any way you prefer.
The idea  is not to edit the system-wide
files in /usr/share. After you copy it to C,
you can edit it (though of course this became
an unsupported configuration).
When any need arises to do such a thing,
you can open a ticket here, so that I can
consider adding something that will allow
you to do the same w/o any local mods.
In this particular case the config.sys hook
file is needed.

**Comment by stsp** [comment]
I created #791 for implementing the hook support.
