### ISSUE TITLE
implement hook file for fdppconf.sys

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#791]
In fact, the hook file is not difficult to implement:
`CHAIN=HOOK.SYS`
just works.

But there are a few more things to consider:
1. If the hook file is missing, you get an (non-fatal) error.
This is undesirable. So either we need dosemu2 to
be able to control the suppression of such error, or
we need a new directive `CHAIN_SILENT` or alike.
I favour the dosemu2-controlable approach, but we
are currently out of registers to pass yet another
extension to fdpp. So this should be implemented
first:
https://github.com/stsp/fdpp/issues/59
2. The nasty `SWITCHES=/F` should be moved to
the hook, as it is the most frequent commented-out
string. But in this case, the hook should always be
created by install.c.

So seemingly one-liner change again turns into
a batch of work items...

**Comment by stsp** [comment]
It would be interesting to thing about the
possibility to extend the `CHAIN` syntax to
something like
`CHAIN=HOOK.SYS,$H`
which will mean run this `CHAIN` only if
`$H` is defined (by dosemu2). In which
case the one can as well write
`CHAIN=$H,$H`
and pass the hook name from dosemu2.
But `$H,$H` looks redundant, so instead
there can be another operator, say, `$+`
which will evaluate to boolean, whereas
`$` evaluates to the string. In which case
the one writes:
`CHAIN=$H,$+H`

Oh man, not sure where such ideas would
lead me to. :)

**Comment by stsp** [comment]
@ZoccoCss You can try `c:\userhook.sys` for your
extra config.sys stuff.

**Comment by stsp** [comment]
It turned out I can't move `SWITCHES=/F` to userhook.sys
because `SWITCHES` is processed before `CHAIN` and
before anything else at all.

**Comment by ZoccoCss** [comment]
I am testing the DOs program without making any configuration changes to Dosemu and it has been working perfectly up to this point.

**Comment by stsp** [comment]
Thanks for testing!
