### ISSUE TITLE
Illegal Instruction (Core Dumped)

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/dosemu2#796]
I'm trying to get the last juice out of an old Pentium III computer with 256Ram. So I installed Lubuntu 18.04 LTS 32bit Alt version. I installed dosemu2 from the ppa and got the following error message. 

Illegal Instruction (core dumped)
Terminated with signal 4

I tried compiling it from source and got the same message. 

Is this processor too old to run dosemu?

**Comment by stsp** [comment]
Its not dosemu, just the compiler flags.
You can pass them to configure like this:
`CFLAGS=-mcpu=i386 ./default-configure`
There are a few flags of interest, like `-mcpu`,
`-march`, `-mtune` etc.
You need to find the ones correct for your CPU.

**Comment by stsp** [comment]
> with 256Ram

I used dosemu on a 486 with 32Mb of RAM, and it
worked perfectly. But as I was buying newer hw, I
was making dosemu fatter and fatter. I wonder how
well will it work on your config these days. Likely not
very well. :) At least on Athlon 700Mhz in dosemu2
it wasn't possible to play any games, as it starts many
hungry threads for soft synth and video rendering.
I think its reasonable to say that dosemu2 now requires
quad-core CPU. Also `top` seems to say that dosemu2
eats 260Mb of memory at startup (RES column, which
is more than firefox eats) and 2.5G of virt address space...
Good luck with your pentium! :)

**Comment by stsp** [comment]
Note that you may as well need to
rebuild fdpp. I think this is actually why
it crashes for you. I.e. the flags should
be correct by default.

**Comment by stsp** [comment]
> Also top seems to say that dosemu2
> eats 260Mb of memory at startup

Fortunately, only by the fact that fluidsynth loads
huge soundfont files. So w/o fluidsynth, you have
some chances, as then dosemu2 eats only 85Mb. :)
And I suspect those come from other dependencies
too.

**Comment by stsp** [comment]
And "only" 30Mb in terminal mode, which is much more
plausible.

**Comment by stsp** [comment]
Try freedos boot w/o fdpp.

**Comment by JL2210** [comment]
@ZoccoCss It's an issue with your processor. If you get an "Illegal Instruction" message, it means that the instruction DOS/FDPP/Dosemu2 is trying to run isn't supported on your processor. Best possibility: Run FreeDOS directly on the hardware.

**Comment by stsp** [comment]
Please don't write the meaningless comments.
There is no need to run freedos or something,
the one should just recompile dosemu2/fdpp
with the proper `-mcpu` flag to avoid the unsupported
instructions.

**Comment by JL2210** [comment]
Yes, but it's because of an old processor that this is occuring. A newer
one should have no issue.

**Comment by stsp** [comment]
This is exactly what the `-mcpu` flag is for.
It selects the target CPU and allows you to
compile for older ones.

**Comment by ZoccoCss** [comment]
I tried several flags and couldn't get it to work. I guess it's time for a honorable retirement for that old computer.

**Comment by stsp** [comment]
You can open an ssh for me to try that out myself.

**Comment by stsp** [comment]
Works perfectly after I compiled fdpp with `-march=i486`.
But I refuse to wait 7 minutes to compile fdpp w/o optimization,
and 13 minutes with optimization! Ridiculous. :)
I wonder how long does dosemu2 itself compile...
OTOH I am quite surprised that dosemu2 boots fine
and fast on your pentium3, and in terminal mode only
takes 28Mb of ram. It even works quite fast with
cpu-emu, but with vm86 it boots instantly.
Surprisingly I could also test dosbox. Even though
it doesn't support terminal mode natively, it booted
with ascii-art mode (aalib), which was fine to watch. :)

**Comment by stsp** [comment]
So it seems, other than waiting forever for the
compilation to complete, people can still use the
old pentium3 quite well. :)

**Comment by ZoccoCss** [comment]
Yes, I was also delighted on how well it booted up. However, when I perform a `lredir` it enters into a loop in which the only way out is to quit the program. I'm attaching an image to help explain the problem. 

![2019-04-02-164527_1024x768_scrot](https://user-images.githubusercontent.com/47893772/55435116-2f981800-5567-11e9-9826-40d5d5b5fd11.png)

**Comment by stsp** [comment]
No, this is just not an up-to-date build.
I re-built only fdpp for you. Please upgrade your dosemu.
Also make sure to reset mmap_min_addr after a reboot,
or vm86 will go away (you'll see the appropriate errors at
startup).

**Comment by ZoccoCss** [comment]
OK. Upgraded and compiled and now `lredir` is working. For reference, compilation of dosemu2 in the Pentium III took 5m57s.  Now the issue seems to be the video. I ran `sudo sysctl -w vm.mmap_min_addr=0` as suggested by the dosemu startup errors. 

![2019-04-02-192936_1024x768_scrot](https://user-images.githubusercontent.com/47893772/55480206-b8599700-55ed-11e9-822f-d765537a5773.png)

**Comment by stsp** [comment]
This looks like your text-mode DOS prog can't
handle the non-standard terminal size. Try
`$_term_set_size = "25x80"`

**Comment by ZoccoCss** [comment]
OK. That worked. 

Is there a way to make `sudo sysctl -w vm.mmap_min_addr=0` permanent? 
 
Now I'm getting strange characters when I run the program. I guess it has to do with the character set. I'm trying different ones to see which one will work.

It's curious that when I run the same accounting program in dosemu2 in a modern processor I have no trouble with neither the terminal size nor the character set.

**Comment by JL2210** [comment]
Create a little script that runs on bootup that runs that command. It's
what I do for x32 development.

**Comment by stsp** [comment]
> Is there a way to make sudo sysctl -w vm.mmap_min_addr=0 permanent?

You need to put that to `/etc/sysctl.d/*`, see `man sysctl.d`.

> I'm trying different ones to see which one will work.

Probably you need to set `$_internal_char_set` correctly.

> It's curious that when I run the same accounting program in dosemu2 in a modern processor

This have nothing to do with the processor, you
simply run it normally in SDL mode, not in a text terminal.

> Create a little script that runs on bootup that runs that command. It's

Senseless comments will not help.
The command in question (sysctl) would need the root
privs to run from a script.

**Comment by JL2210** [comment]
I was thinking something like rc.d. I do find it insulting when you say my
comments are "senseless". I'm just trying to help.

**Comment by stsp** [comment]
> I was thinking something like rc.d.

sysctl settings should be put to `/etc/sysctl.d`.
Its a system-wide settings, they do not need to
be put to any script.

> comments are "senseless". I'm just trying to help.

Help is always appreciated, but you can lurk around
for some time and get used to dosemu2. There is no
need to rush with helping. :)

**Comment by stsp** [comment]
Testing for regressions is a great help btw.
