### ISSUE TITLE
Unable to load software which uses packet driver

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#797]
**Describe the bug**
I am unable to load any software which uses the packet driver interface, such as pdether or ipxpd.  I was able to use the packet driver on previous versions of DOSemu, but I do not recall which version exactly.  The version which last worked was from approximately two months ago.

**To Reproduce**
Attempt to load a program which uses the packet driver interface, and the program will return an error message, specific to the program in question. (ie.  ipxpd returns "Could not find Packet Driver Interface.").

**Attach the binaries**
I have attached ipxpd.com.

**Attach the log**
I have attached boot.log generated with -D+a.  This is a boot sequence which attempts to load the Novell VLM redirector with pdether.com, which fails.

[ipxpd.zip](https://github.com/stsp/dosemu2/files/2985927/ipxpd.zip)
[boot.log.zip](https://github.com/stsp/dosemu2/files/2985928/boot.log.zip)

**Comment by jharrison03** [comment]
I have have attached dosemurc.

[dosemurc.zip](https://github.com/stsp/dosemu2/files/2986888/dosemurc.zip)

**Comment by stsp** [comment]
Should now be fixed.
