### ISSUE TITLE
Makefile.conf is written with -no-pie

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#798]
**Describe the bug**
Makefile.conf is generated somewhere when running ./default-configure.  Makefile.conf then contains a line like this:

ALL_LDFLAGS:=-pthread -no-pie $(LDFLAGS)

This needs to be

ALL_LDFLAGS:=-pthread -fno-pie $(LDFLAGS)

On Debian 8 with gcc 4.9.2.

**Comment by stsp** [comment]
No, this is not correct because we already have
`-fno-pie` in CFLAGS. `-no-pie` is rather a linker flag:
```
       -no-pie
           Don't produce a dynamically linked position independent
           executable.
```

Besides, I use that flag only on a 32bit arch.
Are you building for 32bit?

**Comment by stsp** [comment]
https://github.com/xd009642/tarpaulin/issues/7#issuecomment-317180523
This comment says `-no-pie` may be missing in
gcc, depending on the options it was built with.
How feasible would it be to report that to debian instead?

**Comment by skitt** [comment]
> How feasible would it be to report that to debian instead?

We’re not likely to do much about it, Debian 8 is no longer supported. It might be worth reporting this to [Debian LTS](https://wiki.debian.org/LTS/FAQ#Where_can_bugs_be_reported.3F) but I doubt it would be fixed.

`-no-pie` works in Debian 9.

**Comment by stsp** [comment]
So a configure check?
Oh well...

**Comment by jharrison03** [comment]
> `-no-pie` works in Debian 9.

It doesn't here.  I have to change it to -fno-pie.

**Comment by stsp** [comment]
I added the check, but I don't know if vm86()
will work that way. `-no-pie` was needed to get
the higher load address...

**Comment by skitt** [comment]
> It doesn't here. I have to change it to -fno-pie.

I thought you were using Debian 8. It doesn’t work on Debian 8, but it does work on Debian 9.

**Comment by stsp** [comment]
> It doesn’t work on Debian 8

To what value does it default on Debian 8?
May I hope that it doesn't work because it is
a default anyway?

**Comment by jharrison03** [comment]
250abe3 fixed the problem on Debian 8.

**Comment by jharrison03** [comment]
-fno-pie probably didn't actually do anything but prevented the linker from complaining.
