### ISSUE TITLE
Borland Pascal 7 IDE won't start from EMS drive

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#799]
**Describe the bug**
The Borland Pascal 7 IDE won't start on recent DOSemu.  The executable prints the copyright message and then hangs indefinitely.  The IDE would start on DOSemu from approximately two months ago.  The Borland Pascal 7 command-line compiler, and the Borland C 3.2 IDE will, however start and run without error.

**To Reproduce**
Start the Borland Pascal 7 IDE with bp.exe.

**Attach the binaries**
I have attached bp7.zip

**Attach the log**
I have attached boot.log.zip and dosmurc.zip.  DOSemu was shut down after the IDE was hung with Ctrl-C.

[bp7.zip](https://github.com/stsp/dosemu2/files/2992941/bp7.zip)
[boot.log.zip](https://github.com/stsp/dosemu2/files/2992944/boot.log.zip)
[dosemurc.zip](https://github.com/stsp/dosemu2/files/2992945/dosemurc.zip)

**Comment by stsp** [comment]
I unpacked your archive and started `bin\bp.exe` w/o
any problems.  I can see some network activity in your
log, and also the use of drive `I`.
Can you try w/o ipxpd and with default drives layout?

**Comment by jharrison03** [comment]
OK, drive I: was an EMS ramdisk, and getting rid of that allowed the BP IDE to start up.

Obviously this isn't needed under Linux, but I'm trying to simulate a particular DOS machine, so that's why it's there.  It's not a deal-breaker for me.

[rd.zip](https://github.com/stsp/dosemu2/files/2994505/rd.zip)

**Comment by stsp** [comment]
Yes, EMS ramdisk cant work with bp
currently, because we abuse the ems
page frame for communications
between bp and dos. So ems ramdisk
either does not expect that someone
re-used the frame, and can't see his
data. Or maybe he is careful enough
to restore his ems mapping, but in this
case it won't see the data passed from bp.
I can only add an option to not use the
ems frame for that, which you will have
to manually enable.

**Comment by jharrison03** [comment]
I don't need this and it's not a big deal.

**Comment by stsp** [comment]
OK, lets keep this open as a reminder.
It might not be difficult to add such
option if time permits.

**Comment by jharrison03** [comment]
Is there something that has changed with how drive letters are assigned?

in my "drives" dir on the Linux side, I have "C", "D" and "E" assigned to local directories, the "I" was previously the RAM disk, and "F" was the CD-ROM, assigned from within Dosemu like this: c:\shsucdx\shsucdx.com /d:mscd0001,f

If I make "I" a local directory, Dosemu won't map this, and it bumps the CD-ROM drive letter up to "G".

**Comment by stsp** [comment]
Yes, there are changes, and tweaking
drives/* was always discouraged. You
can use compatibility mode with
`$_default_drives=(off)`

**Comment by jharrison03** [comment]
I have $_default_drives=(off), and my 'drives' folder looks like this:

c (C drive)
d (D drive)
e ../../.. (my home folder)
i: (to simulate the RAM disk)

**Comment by jharrison03** [comment]
I can change this around if this isn't the right way to map the drives.

**Comment by jharrison03** [comment]
If I have "I" in my 'drives' folder, the CD-ROM is pushed to "G", and this messes up my network drive mapping when I log into Netware.

**Comment by andrewbird** [comment]
Regarding your I: drive is it a also a directory in drives called 'i'? I don't think dosemu cares about the naming only the order when enumerating the drives, most likely it's creating a drive F: and that's why your CDROM gets bumped to G:

**Comment by andrewbird** [comment]
Probably best to lredir the I: drive after the CDROM has been setup.

**Comment by jharrison03** [comment]
OK, I see what's going on now.  You're correct about the drive letter assignments.  The lredir works for "I".

**Comment by stsp** [comment]
Yes, you need to either do what
Andrew says for compatibility layout,
or enable degault_drives, use
`-home` and `-cdrom` to map home
and cdrom, and put only your I drive
to drives/ but it wont be I. If you
insist on I letter, you need to map
it by hands with lredir2.

**Comment by jharrison03** [comment]
Just to be clear, I wasn't starting or running the IDE *from* the EMS ramdisk.  

I had the scratch space in the IDE set to the ramdisk, which is what is failing on recent Dosemu.

**Comment by stsp** [comment]
Do you think it worked before?
I dont think so, but it would be
interesting then.

**Comment by jharrison03** [comment]
It did work previously.

**Comment by stsp** [comment]
Maybe you didn't set `TEMP` to `i:`?
The last thing it does before hang, is removing
the temporary file `I:\TP0C0DC7.$$$`.

Try setting
```
$_set_int_hooks = (on)
$_force_int_revect = (on)
```
to undo some of the recent changes.

**Comment by jharrison03** [comment]
The BP IDE hangs with just the presence of the RAM disk driver --

TMP/TEMP is set to a local disk, the link buffer in the IDE is set to a local disk, and $_set_int_hooks, and $_force_int_revect are both (on).

**Comment by jharrison03** [comment]
When I try to enable debugging with -D+a, I'm getting *gigabytes* of this in my log file (no -D doesn't produce this):

```
VGAEmu: vga_emu_fault: write access to some region, address 0x01cea, page 0x1, vga page 0x0
VGAEmu: vga_emu_fault: cs:eip = f709:011e, instr: 80 fc d8 75 0c 3c 50 72 08 3c 51 77 04 2e a2 46
VGAEmu: vga_emu_fault: unhandled page fault (not in 0xa0000 - 0xc3000 range)
Return for SIGNAL

        eax=0fe7004c ebx=00640002 ecx=0000f0d6 edx=000003c4
        esi=00000a18 edi=00000a36 ebp=00000003 esp=000008f6
         vf=00033206  cs=c774      ds=f660      es=f660
         fs=0000      gs=0000      ss=013f     flg=00030206

Fetch ff2e9cfa at 000c83f9 mode 3
SIGPROF 1 n=    6034 p=      81 x=      96 ix= 21 cln= 3

        eax=0fe7004c ebx=00640002 ecx=0000f0d6 edx=000003c4
        esi=00000a18 edi=00000a36 ebp=00000003 esp=000008f6
         vf=00033206  cs=c774      ds=f660      es=f660
         fs=0000      gs=0000      ss=013f     flg=00030206
```

**Comment by jharrison03** [comment]
I'm going to install a newer distro today so I'm not the caboose in this project.

**Comment by stsp** [comment]
You don't need `-D9+a`.
Just use `-D9+EDd#` for smaller logs.
Then search the log for `I:\TP0C0DC7.$$$`.
If its there, your BP is trying to manage the
tmp files on I, which is not what you want.

**Comment by stsp** [comment]
The tmp name may of course differ.
I suppose `I:\TP` is a good search pattern.

**Comment by andrewbird** [comment]
A little off topic note here:
It seems emsdsk piqued my interest in how it can load a block driver (from command line) and connect up an arbitrary numbered(lettered) drive to it. I figure this procedure could be useful for something perhaps. I looked for sources online but didn't find them, I emailed the author but haven't received a reply or bounce, and so now I resort to dosdebug. My problem is that it seems both emsdsk.exe and xmsdsk.exe cause a crash in dosemu. I wasn't expecting emsdsk.exe to work as per the comments in this thread, but I was hoping it would load so that I could poke around. So does it actually load for others and if so is there any special magic required; I have minimal dosemu/dos config on MS-DOS 6.22?

**Comment by jharrison03** [comment]
I load EMSDSK like so:

loadhigh c:\rd\emsdsk.exe 32767 i: /y

And it "works" for me, in the sense that I have an issue with one piece of software (Borland Pascal IDE) that didn't previously exhibit a problem.  But the driver loads and I otherwise don't have problems with other software.

**Comment by andrewbird** [comment]
Thanks. Your line worked just fine after I realised that I'd stupidly forgot to load `ems.sys`. Now off to play!

**Comment by stsp** [comment]
Andrew, please check the bp
behaviour when it doesnt try to
manage the tmp files on a ems
drive. That should still work.

**Comment by jharrison03** [comment]
That EMSDSK driver is somehow not working with BP7 IDE, regardless of where the link buffer and TMP/TEMP vars are pointing to.

I nuked the BP configuration file and set TMP/TEMP to c:\temp, and the program just won't start.

**Comment by stsp** [comment]
You should still search the log for
the tmp files on I. This is the only
reliable check.

**Comment by stsp** [comment]
OK, I've tested just now:
```
I:\>dir
 Volume in drive i is MS-RAMDR.IVE
 Directory of i:\
 
File not found
 
I:\>c:
 
C:\BP\BIN>bp
Borland Pascal  Version 7.0  Copyright (c) 1983,92 Borland International
< see bp IDE here. Exit it >
C:\BP\BIN> 
```

So it works perfectly here.
Though I have used my own install, not yours.
