### ISSUE TITLE
Unable to check existence of dir using NUL

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#800]
**Describe the bug**
I am unable to check the existence of a directory from a batch file using the following syntax under the MS 6.22 COMMAND.COM --

if exist c:\NUL echo "Directory exists"

I can do a "dir c:\NUL" which returns a directory listing listing consisting of a single 319 byte file with the filename of "nul", which is unorthodox behavior under DOS.

**To Reproduce**
Attempt to use the above command line in a DOS batch file, which will fail.

**Attach the binaries**
I have attached test.zip.

**Attach the log**
I have attached boot.log.zip produced with dosemu -D+a.

[test.zip](https://github.com/stsp/dosemu2/files/3002732/test.zip)
[boot.log.zip](https://github.com/stsp/dosemu2/files/3002733/boot.log.zip)

**Comment by stsp** [comment]
```
C:\>dir c:\nul
 Volume in drive C is EMU DRIVE_C
 Directory of C:\
 
NUL                     12  04-12-91 11:19p
         1 file(s)             12 bytes
         0 dir(s)    203,708 Mega bytes free
C:\>if exist c:\NUL echo "Directory exists"
"Directory exists"
```

What is the problem here?
And what directory are you actually testing with that?

**Comment by andrewbird** [comment]
I think the intention is to actually check the existence of the drive `C:`. I remembered a discussion on old freedos issues tracker where this behaviour was broken and then restored see [sf](https://sourceforge.net/p/freedos/mailman/message/35629362/) discussion.

**Comment by jharrison03** [comment]
In the case of MS-DOS, at least, this isn't the expected behavior, ie. --

if exist c:\NUL echo "Directory exists"

This will succeed, and print "Directory exists", while --

"dir c:\NUL"

will return "file not found"

Under Dosemu, nothing is printed with that command in the batch file, and the directory listing returns "nul" as a 319 byte file.

**Comment by jharrison03** [comment]
FWIW. this is different behavior from an older Dosemu I used approx 2mos. ago, so something has changed to how NUL is handled.

**Comment by stsp** [comment]
> I think the intention is to actually check the existence of the drive C:.

Unclear.

> will return "file not found"

Tried on PC-DOS 7 under dosemu2, on dosbox,
on FreeDOS under dosemu2 with redirection disabled:
if the drive exists, `dir c:\NUL` returns the listing with 1 file.
Consistent across all the tests I did, no matter whether
the drive is redirected or not, whether it is dosemu2 or
dosbox, etc.

> FWIW. this is different behavior from an older Dosemu I used approx 2mos.
> ago, so something has changed to how NUL is handled.

Maybe, but your report is very vague.
Please explain first, what directory are you trying
to check, or are you trying to check existence of
drive C itself?

**Comment by stsp** [comment]
> freedos issues tracker where this behaviour was broken and then restored see sf discussion.

Obviously he meant something else, as things
like `dir p:\NUL` (where p: doesn't exist) correctly
return error under fdpp.

So either the problem needs to be properly described,
or closed.

**Comment by jharrison03** [comment]
OK,

This is "test.bat"

if exist c:\NUL echo "Dosemu directory exists"
if exist i:\NUL echo "Redirected directory exists (created from lredir2)"
if exist g:\NUL echo "Netware redirected directory exists (created from MAP)"

This is the output:

C:\>test
C:\>if exist c:\NUL echo "Dosemu directory exists"
C:\>if exist i:\NUL echo "Redirected directory exists (created from redir2)"
C:\>if exist g:\NUL echo "Netware redirected directory exists (created from MAP)"
"Netware redirected directory exists (MAP)" 

I would expect the output of "echo" to report all these paths to exist.

I wouldn't expect to see a 319 byte file called "nul" if I performed a "dir *:\NUL" on any of these paths.

**Comment by jharrison03** [comment]
"dir c:\NUL" reports the existence of 'nul" as a 319 byte file.
"dir i:\NUL" reports the existence of 'nul" as a 319 byte file.
"dir g:\NUL" reports 'Invalid function'

**Comment by jharrison03** [comment]
I'm trying to test for the existence of the I: drive created with lredir2.

**Comment by andrewbird** [comment]
Tested here on MS-DOS 6.22 I see the oddity with dir display of `c:\nul` too.

The `dir c:\nul` showing a file seems to be an effect seen only on MFS drive, fatfs behaves as I would expect
~~~
C:\>dir c:\nul
 
 Volume in drive C is IR DXXXXS C
 Directory of C:\

NUL                    313 03-25-19  11:37a
        1 file(s)            313 bytes
                   2,147,450,880 bytes free
 
C:\>lredir -d c:
Redirection for drive C: was deleted.
 
C:\>dir c:\nul
 
 Volume in drive C is DXXXXS C
 Volume Serial Number is 4ADD-1B8A
 Directory of C:\
 
File not found
~~~

Interestingly I get a different file size shown if I use the the `con` device instead, not sure were dosemu is getting that from.

**Comment by jharrison03** [comment]
"dir c:\NUL" shouldn't return a directory listing.

**Comment by jharrison03** [comment]
And "dir c:\CLOCK$", and "dir c:\COM1" returns the existence of 112 byte files.  I'm sure that not a invalid output.

**Comment by jharrison03** [comment]
You can read from these files this like.  That's not right.

**Comment by stsp** [comment]
> This is "test.bat". All of these directories exist.

Things like `C:`, `D:` etc are called "drives" under DOS,
not directories.

> C:\>lredir -d c:

lredir2 perhaps? `-d` doesn't look valid for lredir IIRC.

> File not found

Any idea why do I am not getting this even with
redirection disabled?

**Comment by jharrison03** [comment]
I don't know what to tell you?  Running those tests produce the output I observed.

Anyhow, something like "dir c:\NUL", or "dir c:\COM1" I don't think should ever return a directory listing, but should produce a valid output with the test case like "if exist..." in a batch file.

**Comment by stsp** [comment]
> "dir c:\NUL" shouldn't return a directory listing.

Try on dosbox: `dir z:\NUL` - it returns the listing.
Is this correct by your judgement?

**Comment by stsp** [comment]
So we have 2 strange things:
1. @jharrison03 claims the wrong behaviour in what was
verified with dosbox.
2. @andrewbird claims the behaviour I don't even see.

Looks like the most mysterious report in this tracker.

**Comment by jharrison03** [comment]
I guess it has something to do with redirection.

It's valid on redirected drives (like in my Netware example), but not on the on "c" drive in my ".dosemu/drives" directory, or with my "I" drive that was previously a RAM disk.

**Comment by stsp** [comment]
> I guess it has something to do with redirection.

This is what Andrew says as well.
But I can't reproduce! For me it always returns the
listing, no matter if I delete the redirection or not.

**Comment by jharrison03** [comment]
Something like "dir c:\NUL" seems like it would be philosophically correct, but I don't ever recall DOS behaving like this (returning a directory listing).

Anyhow, I brought this up because batch files I have which used that test worked until I recently build a new Dosemu, and they certainly work under MS-DOS 6.22 on hardware.

**Comment by jharrison03** [comment]
I get a similar output to andrewbird's test, but the file size of NUL differs by 6 bytes:

C:\>dir c:\nul
 
 Volume in drive C is ON DRIVES C
 Directory of C:\
 
nul
        1 file(s)            319 bytes
                   2,147,450,880 bytes free
 
C:\>lredir.com -d c:
Redirection for drive C: was deleted.
 
C:\>dir c:\nul
 
 Volume in drive C is DRIVES C
 Volume Serial Number is 4ADD-1B8A
 Directory of C:\
 
File not found

**Comment by jharrison03** [comment]
You can do something like this, too:

```
C:\>dir c:\emufs$
 
 Volume in drive C is ON DRIVES C
 Directory of C:\
 
emufs$
        1 file(s)            642 bytes
                   2,147,450,880 bytes free
```

**Comment by jharrison03** [comment]
I think in Dosbox all the drives are treated as redirected.

**Comment by stsp** [comment]
> C:\>lredir.com -d c:

Grr, so it seems the commit 2066d103 have dropped
the old lredir syntax w/o any notice in the log! Someone
should get his commit access disabled for such things!

So I still can't reproduce the "file not found" error, even
after disabling redirection with lredir. This is strange.

**Comment by stsp** [comment]
So lets get back to the original problem.
When drive is set up and redirected, everyone
here gets the directory listing. If the drive is
missing, there is an error. The odd case is only
when the drive is there but the redirection is
disabled, which we don't need to care about.

So what is the problem here with detecting the
drives?

**Comment by andrewbird** [comment]
I've just returned home, so sorry if I missed anything.

I just tested the existence of `c:` using the method `if exist c:\nul` and I see an incorrect result on MFS but on fatfs it's fine.
~~~
 
C:\>if exist c:\nul echo hello
 
C:\>lredir -d c:
Redirection for drive C: was deleted.
 
C:\>if exist c:\nul echo hello
hello
~~~

**Comment by jharrison03** [comment]
The problem I'm observing is a command like this isn't returning "OK" , where I think it should be on a drive (or directory) that exists --

"if exist c:\NUL echo OK"

"c:\NUL" can also be "c:\temp\NUL" (a directory), and it also does not return the expected result "OK".

**Comment by andrewbird** [comment]
Strangely, `if exist c:\nul echo hello` doesn't fail every time on MFS for me, so perhaps there's a random element?

**Comment by jharrison03** [comment]
I also don't think you should be able to see device drivers in a dir listing like "dir c:\COM1", but maybe that's completely OK and unrelated.

**Comment by jharrison03** [comment]
Just to make sure I'm not using Dosemu totally wrong, I have --

1.  'c', 'd', and 'e' drives in the equivalent of ~/.dosemu/drives/
2. 'f' is my CD-ROM, assigned with MSCDEX.
3. 'i' is also a local drive, assigned with lredir2.
4. I have G, H, N, O, P, R, S, X, Y, Z mapped from a Netware login script.

I can access all of these drives, but the test for "NUL" fails on the C, D, E, and I drives.

**Comment by stsp** [comment]
> Strangely, if exist c:\nul echo hello doesn't fail every time on MFS for me, so perhaps there's a random
> element?

Could you please investigate that a bit?
I can't reproduce this even once.

**Comment by andrewbird** [comment]
I think I found the trigger, it seems to be doing `dir` before the test
~~~
C:\>if exist c:\nul echo hello
hello
 
C:\>dir
 
 Volume in drive C is IR DXXXXS C
 Directory of C:\
 
MFSSFNTN O           1,012 03-25-19  11:36a
AUTOEXEC BAT            76 03-25-19  11:36a
VERSION  BAT            14 03-25-19  11:36a
IO       SYS        40,774 05-14-14   7:40p
MFSSF~9R ELF         4,968 03-25-19  11:36a
MSDOS    SYS        38,138 05-14-14   7:40p
CONFIG   SYS            43 03-25-19  11:36a
MFSSFNTN S             841 03-25-19  11:36a
TEST_MFS BAT            19 03-25-19  11:36a
COMMAND  COM        54,645 05-14-14   7:40p
MFSSFNTN COM           261 03-25-19  11:36a
DOSEMU       <DIR>         03-25-19  11:28a
       12 file(s)        140,791 bytes
                   2,147,450,880 bytes free
C:\>if exist c:\nul echo hello
 
C:\>
~~~

**Comment by jharrison03** [comment]
That's a good catch I think.  It doesn't work for me here --

The "dir _X_:\NUL" works on my Netware drives, and the drives I previously used with a RAM disk driver.

It doesn't work with drives assigned from Dosemu or lredir.

**Comment by andrewbird** [comment]
@stsp I updated the post above with the corresponding log file

**Comment by stsp** [comment]
I tried `dir` in between tests, and still nothing happens.
redirected drive always responds w/o error.
By the way, you have fatfs returning an error - do I need
to use `dir` to provoke also that?

Could you please test with normal dosemu2 install,
w/o various directory tricks? Maybe its something
with hdimage relocation?

**Comment by stsp** [comment]
Also I am using comcom32. Though on freecom
it seems the same, it would be nice if everyone here
double checks to use comcom32.

**Comment by stsp** [comment]
Andrew, could you please outline
the interesting log parts?
Also I think it would be good to have
an ssh for this.

**Comment by stsp** [comment]
I've fixed the uninitialized variable problem
that could be responsible for the randomness
factor.
It doesn't change anything visible for me, but
I suspect at least the test results will now be
consistent and reproducible for all of us.

**Comment by andrewbird** [comment]
Sorry  I didn't get the chance to test yesterday. I've just quickly tested your latest and the existence test seems to be fine for me now.
~~~
c:\>if exist c:\nul echo hello
hello
 
C:\>dir
 
 Volume in drive C is IR DXXXXS C
 Directory of C:\
 
AUTOEXEC BAT            76 03-25-19  11:36a
VERSION  BAT            14 03-25-19  11:36a
IO       SYS        40,774 05-14-14   7:40p
MFSSF~9R ELF         4,968 03-25-19  11:36a
MSDOS    SYS        38,138 05-14-14   7:40p
CONFIG   SYS            43 03-25-19  11:36a
MFSSFNTN S             841 03-25-19  11:36a
TEST_MFS BAT            19 03-25-19  11:36a
COMMAND  COM        54,645 05-14-14   7:40p
MFSSFNTN COM           261 03-25-19  11:36a
DOSEMU       <DIR>         03-25-19  11:28a
       11 file(s)        139,779 bytes
                   2,147,450,880 bytes free
 
C:\>if exist c:\nul echo hello
hello
~~~

I don't suppose you expected the DIR of device to change, as it didn't, there's still the strange behaviour on MFS as below.

~~~
 
C:\>dir c:\nul
 
 Volume in drive C is IR DXXXXS C
 Directory of C:\
 
NUL                    338 03-27-19  11:25a
        1 file(s)            338 bytes
                   2,147,450,880 bytes free
 
C:\>lredir -d c:
Redirection for drive C: was deleted.
 
C:\>dir c:\nul
 
 Volume in drive C is DXXXXS C
 Volume Serial Number is 4ADD-1B8A
 Directory of C:\
 
File not found
 
C:\>
~~~

I have to go out again now, I'll check back later.

**Comment by stsp** [comment]
This is what I still can't reproduce.
Are you sure you are on fdpp and not on freedos?
As I don't think these freedos bugs you mentioned
before, could affect fdpp (I tried to fix such bugs during
the porting process)

**Comment by stsp** [comment]
> there's still the strange behaviour on MFS as below.

You mean, strange on fatfs? As I think MFS is now
correct... or?

**Comment by andrewbird** [comment]
> Are you sure you are on fdpp and not on freedos?

I didn't get the chance to try fdpp or freedos yet, my testing here has only ever been on MS-DOS 6.22. Perhaps I confused you by linking to that sourceforge thread, which was my attempt to explain what @jharrison03 was doing, I didn't actually think there was any known bug in FreeDOS with it now. Sorry for creating some confusion.

>You mean, strange on fatfs? As I think MFS is now
correct... or?

No I don't think so. Doing a `DIR c:\nul` and seeing a filesystem entry seems wrong. MS-DOS 6.22 with fatfs shows file not found which I think is correct, Dosemu's redirector (MFS) shows an entry with different sizes for different people which makes no sense to me.

**Comment by stsp** [comment]
> I confused you by linking to that sourceforge thread

Of course. You haven't identified your test platform,
so of course I assumed either the default (fdpp), or
freedos (because of the referenced bug report).
So if there is a consistent difference on a non-redirected
drives, then it is likely in freedos/fdpp. But I don't think
this ever matters, as long as the `if exist` check now
works.
Do people agree with that judgement?

> No I don't think so. Doing a DIR c:\nul and seeing a filesystem entry seems wrong.

But dosbox does this, and @jharrison03 says he has the
same on a redirected networking drives (non-mfs). So lets
just say this is either correct, or doesn't matter. :)

> Dosemu's redirector (MFS) shows an entry with different sizes for different
> people which makes no sense to me.

Indeed, this is something to look into.

**Comment by stsp** [comment]
Hmm, I would expect that "different sizes for different
people" effect have vanished with the recent patch, BUT
there may still be an effect of "different sizes for different
DOSes"?

**Comment by jharrison03** [comment]
The check works for me now, even though NUL, etc appear in directory listings.

The drives assigned through Netware always worked with the check, and they don't show the directory listings.

**Comment by stsp** [comment]
MFS definitely has that by design, not as the
result of any bug. See `get_dir()`:
```
* DANG_BEGIN_REMARK
 *
 * Added compares to device so that newer versions of Foxpro which test dire
ctories
 * using xx\yy\device perform closer to whats DOS does.
 *
 * DANG_END_REMARK
 */
  if (mname && is_dos_device(mname)) {
    dir_list = make_dir_list(1);
    entry = make_entry(dir_list);
```

This just means that the device file is a hidden
file in any directory. When you do plain `dir`, you
don't see it among other files. But if you do dir
on it explicitly, then you see it.

```
C:\>dir ipxpd.com
 Volume in drive c is EMU DRIV.E_C
 Directory of c:\
 
2019-03-20 02:20         37610 IPXPD.COM
         1 file(s)          37610 bytes
         0 dir(s)               0 byte(s) free 
```

In this example I do `dir` on a regular file, and it works.
So unless it doesn't work on a non-redirected drive in
some DOS, I'd say this all is by design.

**Comment by jharrison03** [comment]
```C:\>dir nul
 
 Volume in drive C is ON DRIVES C
 Directory of C:\
 
File not found```

```C:\>dir c:nul
 
 Volume in drive C is ON DRIVES C
 Directory of C:\
 
File not found```

```C:\>dir c:\nul
 
 Volume in drive C is ON DRIVES C
 Directory of C:\
 
NUL                    319 03-27-19   9:27a
        1 file(s)            319 bytes
                   2,147,450,880 bytes free```

**Comment by stsp** [comment]
What is this? Bad formatting?

**Comment by andrewbird** [comment]
>What is this? Bad formatting?

I think it's a valid observation that:
`dir nul` - default drive + default drive's current directory + device name - gives 'file not found'
`dir c:nul` - specific drive + specific drive's current directory + device name - gives 'file not found'
`dir c:\nul` - specific drive + specific directory - displays some odd file entry with 'nul' name

> * Added compares to device so that newer versions of Foxpro which test directories
>  * using xx\yy\device perform closer to whats DOS does.

I think that's an odd comment because:
-  at least in our tests MS-DOS on FAT does different behaviour.
-  on any network filesystem this effect would seem to be implemented by the redirector, as far as I am aware there's no reference DOS redirector, so what DOS filesystem behaviour are they trying to replicate?

**Comment by stsp** [comment]
Andrew, you can't ignore the fact that both
dosbox and freedos behave that way. I mean,
even if I disable that in the redirector, what will
this give, but the inconsistency with the non-redirected
drive? So in that case I'll also have to remove that
from fdpp, and what about freedos and dosbox?

Plus have you seen my example above on doing `dir`
on a regular file - that works too.

The only odd thing I see here, is that I can't reproduce
anything! All 3 cases above give me the listing with
exactly 1 file. So for me everything works consistently.
How can I repro "file not found" in cases 1 and 2?

**Comment by andrewbird** [comment]
So following up on your FreeDOS FAT behaviour note, I wrote a test to see which DOSs behave that way on FAT. As you can see it's only FreeDOS that does this (the MS-DOS 3.10 failed for some other reason), all other DOSs I have return "File not found" for `DIR C:\NUL`
~~~
Test DR-DOS-3.40 None ... ok
Test DR-DOS-3.41 None ... ok
Test DR-DOS-5.00-900615 None ... ok
Test DR-DOS-5.00-900814 None ... ok
Test DR-DOS-6.00-930319 None ... ok
Test DR-DOS-6.00 None ... ok
Test DR-DOS-7.00 None ... ok
Test DR-DOS-7.01 None ... ok
Test DR-DOS-7.02-971119 None ... ok
Test DR-DOS-7.02-980123 None ... ok
Test DR-DOS-7.03 None ... ok
Test DR-DOS-8.00 None ... ok
Test FR-DOS-1.00 None ... FAIL
Test FR-DOS-1.10 None ... FAIL
Test FR-DOS-1.20 None ... FAIL
Test FR-DOS-GIT None ... FAIL
Test MS-DOS-3.10 None ... FAIL
Test MS-DOS-3.20 None ... ok
Test MS-DOS-3.21 None ... ok
Test MS-DOS-3.30-Nec None ... ok
Test MS-DOS-3.30 None ... ok
Test MS-DOS-3.31 None ... ok
Test MS-DOS-4.01 None ... ok
Test MS-DOS-5.00 None ... ok
Test MS-DOS-6.00 None ... ok
Test MS-DOS-6.20 None ... ok
Test MS-DOS-6.21 None ... ok
Test MS-DOS-6.22 None ... ok
Test MS-DOS-7.00 None ... ok
Test MS-DOS-7.10 None ... ok
Test PC-DOS-3.00-Compaq None ... ok
Test PC-DOS-3.00 None ... ok
Test PC-DOS-3.10-850307 None ... ok
Test PC-DOS-3.10-850422 None ... ok
Test PC-DOS-3.10-Compaq None ... ok
Test PC-DOS-3.20-851230 None ... ok
Test PC-DOS-3.20-860221 None ... ok
Test PC-DOS-3.30 None ... ok
Test PC-DOS-3.31-Compaq None ... ok
Test PC-DOS-4.00 None ... ok
Test PC-DOS-4.01 None ... ok
Test PC-DOS-5.00 None ... ok
Test PC-DOS-5.02 None ... ok
Test PC-DOS-6.10 None ... ok
Test PC-DOS-6.30 None ... ok
Test PC-DOS-7.00 None ... ok
Test PC-DOS-7.10 None ... ok
Test PC-DOS-7.2K None ... ok
Test PP-DOS-GIT None ... SKIP: Need to rebuild (/clients/common/fdpp.git/fdpp/fdppkrnl.sys) in git
~~~

I'm not familar with Dosbox, but perhaps it shares some code with FreeDOS kernel?

**Comment by stsp** [comment]
But does `dir` matter at all, as long as the
`if exists` check works properly? Plus, dont
you think that `dir` should be consistent with
`if exists`?
I mean, if we have some major but old doses
do it one way, and other major and NEW doses
doing it the other way, we can decide ourselves
whatever is better.
And IMHO:
1. having the parity between `if exists` and `dir` is better
2. having the match to major NEW doses is better
than to match major but old ones
3. the code obviously had that by design, so someone
already considered that, and his vote counts

**Comment by jharrison03** [comment]
DOSbox and FreeDOS are doing this different than "real" DOSs.  That much is certain.

**Comment by stsp** [comment]
But this is not a problem if they do this better.
Replacing the good functionality with bad one
only because someone else did that, is not a
good argument.

**Comment by stsp** [comment]
The same happened with freecom: they ripped
the useful functionality to stay compatible with
command.com rather than with 4DOS. Now we
have problems with freecom under dosemu2.
This mistake should not be repeated.
We need to judge what is better for us, rather
than to blindly remove whatever looks incompatible.

**Comment by jharrison03** [comment]
As long as the check works I don't see a problem with that.  It seems to be philosophical issue at this point.
