### ISSUE TITLE
Dosemu2 fails if not linked properly

### ISSUE THREAD

**Issue by JL2210** [stsp/dosemu2#802]
**Describe the bug**
Dosemu2 (when built with FDPP) does not function properly unless linked with FDPP.

**To Reproduce**
1. Install FDPP
2. Install dosemu2
3. Run dosemu2

Along with this, it's not your issue, but FDPP has to be linked with libc++ (for anyone out there also having this issue).

Process to fix:

```
patchelf --add-needed libfdpp.so dosemu
patchelf --set-rpath `pkg-config --variable=fdpplibdir fdpp` dosemu
patchelf --add-needed libc++.so.1 `pkg-config --variable=fdpplibdir fdpp`/libfdpp.so
```

**Comment by stsp** [comment]
You are not supposed to know how dosemu2
works, so I omit the meaningless comment.
But where is the log?

**Comment by stsp** [comment]
Linking with libc++ is actually not even recommended
to try, unless your entire distro uses only that and not
libstdc++, see #708

**Comment by stsp** [comment]
See generated `config.hh`, it should contain
something like this:
`#define DOSEMUPLUGINDIR "/usr/local/lib/dosemu"`
and
`#define USE_DL_PLUGINS 1`
I suppose you either configured w/o DL_PLUGINS,
or somehow installed the plugins to wrong dir.

**Comment by JL2210** [comment]
libc++ is something needed by FDPP, because FDPP is C++ and has to be compiled with LLVM.
I enabled everything available, and `DOSEMUPLUGINDIR` was defined to `/usr/local/lib64/dosemu`.
I'm working on the log right now.

**Comment by stsp** [comment]
clang uses libstdc++ by default, unless you
use `-stdlib=libc++`. I don't know what distro
do you use where this is not the case.

**Comment by JL2210** [comment]
I'm on a Chromebook, but for some reason FDPP still used the header files for libc++. Anyway, as I mentioned before, it's not an issue with Dosemu2. What bothers me is this:
```
chronos@localhost ~/Downloads/git/dosemu2 $ dosemu
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!
```
This only shows up when Dosemu2 is not linked against FDPP.

**Comment by stsp** [comment]
What binutils version is this?

**Comment by stsp** [comment]
And what is the linker?
ld or gold or lld?

**Comment by stsp** [comment]
It seems this problem is specific to binutils
prior to 2.25.51, which is quite old.

**Comment by stsp** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=16452

**Comment by JL2210** [comment]
2.32, to be exact. It's ld.bfd, the default:
```
GNU ld (GNU Binutils) 2.32
```

**Comment by stsp** [comment]
Note that DT_NEEDED for libfdpp.so should be
in libplugin_fdpp.so, not in dosemu.bin:
```
$ ldd libplugin_fdpp.so 
	linux-vdso.so.1 (0x00007ffe87b4b000)
	libfdpp.so => /usr/local/lib/fdpp/libfdpp.so (0x00007fbe31d90000)
```

The above binutils bug report however says:
```
This happens because the executable has no DT_NEEDED entry for the library that defines the versioned symbol,
but at the same time the executable has an entry for that symbol and library in .gnu.version_r section,
so, when dynamic linker sees this unversioned symbol (provided by another library), assertion is
triggered.
```

So it seems like `.gnu.version_r` section refers to
some symbol that is versioned in libfdpp.so and is
unversioned elsewhere, which would be strange.
Would be nice if you can find out what symbol this
could be.

**Comment by stsp** [comment]
OK, the above comment does not apply to 2.32.

**Comment by stsp** [comment]
Can you try 2.31 (as I have), or gold?
Maybe the bug is recent.

**Comment by JL2210** [comment]
Do you have 2.31.1 or 2.31? 2.31 is not available in Chromebrew.

**Comment by JL2210** [comment]
What operating system are you on?

**Comment by stsp** [comment]
Fedora, ubuntu - everything works fine.
Also see this:
https://github.com/NixOS/patchelf/pull/85
I wonder if you use patchelf with a bug.

**Comment by JL2210** [comment]
`patchelf` is the only thing that fixes this issue, but it does mention something about fixing a Linux kernel bug.

**Comment by JL2210** [comment]
Here's an issue:
```
chronos@localhost ~/Downloads/git/dosemu2/2.0-pre8/bin $ ldd libplugin_fdpp.so 
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!
chronos@localhost ~/Downloads/git/dosemu2/2.0-pre8/bin $ 
```

**Comment by stsp** [comment]
I think you should upload this libplugin_fdpp.so to
binutils bugzilla and ask them what to do next.

**Comment by JL2210** [comment]
Good idea.

**Comment by stsp** [comment]
Any progress?

**Comment by JL2210** [comment]
Haven't tried yet. I figure an LLVM update could fix it.

**Comment by JL2210** [comment]
Now I can't build at all. See #804

**Comment by JL2210** [comment]
I've just decided to build it under a Gentoo environment where things like LLVM actually work. It works fine now. Just goes to show what happens if you build things under a regulated environment instead of a hodgepodge of thrown-together software.

**Comment by stsp** [comment]
But it could still be interesting to find out
what binutils guys think. There could be a
bug somewhere...
