### ISSUE TITLE
rethink drive handling

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#803]
Currently there are 3 options in dosemu.conf
to control drives layout:
```
# $_default_drives = (on)
# $_hdimage = ""
# $_hdimage_start = ""
```
... and also `--Fdrive_c`.
Of course they all do not play well with each
other, and hardly anyone really knows what
they do.
Needs a simpler approach.

**Comment by stsp** [comment]
After a lot of thinking (of course!:),
it seems all these new options were
added for just one purpose: to make
the default layout created by the
install procedure, compatible with
different custom setups that people
used to have.
As there is no longer an install, I see
no reason against just reverting
everything, making no "new" and
"compatible" layout. There can again
be just one layout.
The mistaks that costed a half year
of development, was that I failed to
recognize the install as the main enemy.
I actually seen nothing wrong in it,
dispite everyone telling the opposite.
Have to think faster next time.

**Comment by stsp** [comment]
Of course the removal of install
became possible only after a lot of
development on fdpp front, which wasn't
initially planned, as initially fdpp was
thought just as a nice way of glewing
freedos to dosemu2. So the redundancy
of install was hidden from my attention
quite deeply. :)

**Comment by stsp** [comment]
I removed `$_default_drives`, `$_hdimage_start` and the
rest of `install.c`. I figured `--Fdrive_c` may still be useful,
so I left it for now. But there is no problem to remove it if
no one is going to use it.

**Comment by bolle732** [comment]
Could you please correct line 166 of etc/global.conf ? It's missing a comma at the end...

This fix this message:
```
Error in built-in global.conf: (line 167) syntax error
1 error(s) detected while parsing the configuration-file
```

**Comment by stsp** [comment]
Thanks, force-pushed the fix.
Strangely, it works perfectly here...
