### ISSUE TITLE
Problems running PC/GEOS with default FDPP and ComCom32

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#807]
**Describe the bug**
Running PC/GEOS with FDPP and ComCom32 crashes a lot.

**To Reproduce**
Install Dosemu2, FDPP and ComCom32 from GIT on Ubuntu 18.04.2. Create `~/.dosemu/drive_c/userhook.sys`:
```
FILESHIGH=120
```
Copy / install PC/GEOS to `~/.dosemu/drive_c/ensemble`, start dosemu with `dosemu -X` and run PC/GEOS with `loader /log`. Open programs / documents. it will crash earlier or sooner.

**Attach the binaries**
If the problem needs specific DOS files to reproduce, please attach.

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.
[boot.log](https://github.com/stsp/dosemu2/files/3049756/boot.log)

**Comment by bolle732** [comment]
So, I try again to run PC/GEOS with FDPP and ComCom32. I'm not sure, If I do it the right way. The most important thing is, that the FILES is set to a high value (100 and more) and that there is enough conventional memory and either XMS / EMS (max. 32MB).

Please give me an advice how to test further.

**Comment by bolle732** [comment]
PC/GEOS still runs fine with FreeDOS kernel.sys / command.com.

**Comment by stsp** [comment]
Is this specific to comcom32 or fdpp?
Where is the hang you were talking
about in another thread?

**Comment by bolle732** [comment]
Regarding the hang, it seems that I was produced due to a forgotten `$_ems_uma_pages = (0)`.

For this crash here, I can't say for sure if it's specific for fdpp or comcom32, as they are not usable without each other. My feeling says fdpp. Need to do more tests.

Is it ok to use this line for startup:
`dosemu -X -f dosemurc -E 'C:\ENSEMBLE\LOADER /LOG'`

**Comment by stsp** [comment]
Why not usable?
They both are usable on their own,
no any interconnections.

**Comment by stsp** [comment]
As for uma pages, its a geos bug then.

**Comment by bolle732** [comment]
> Why not usable?
> They both are usable on their own,
> no any interconnections.
No I'm confused. Didn't you told that fdpp will not be usable without comcom32 and you filled every hole to circumvent this ? Or has this been reverted ?

> As for uma pages, its a geos bug then.
The possibility exist. But I've used it in so many environments, and errors like this I haven't seen a lot...

Ok, back to the error I'm facing now:
`ERROR: general protection at 0x7f2e6e931c38: ff`

This only happen with fdpp and comcom32. FreeDOS works still fine.

Defaults with `$_cpu_emu` and `$_cpu_vm` I also get:
```
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=000a51bc while in vm86 (DOS)
Real-mode state dump:
EIP: 0700:00000125 ESP: c544:000007f6  VFLAGS(b): 00011 00000000 00000010
EAX: 4bcbe941 EBX: 00000000 ECX: 00000016 EDX: 00004de2 VFLAGS(h): 00030002
ESI: 000001b7 EDI: 00000dce EBP: 00001670 DS: 0070 ES: 2556 FS: a000 GS: a000
FLAGS: IF RF VM  IOPL: 0
OPS  : 00 28 00 00 00 1c 00 00 00 2c -> 8d fd ff 36 00 00 00 00 43 0e 
```
Regarding PC/GEOS, sometimes I get KR-06 or KR-09. Have to investigate more.

**Comment by bolle732** [comment]
KR-06 is defined as KS_TE_BREAKPOINT, KR-09 is KS_ILLEGAL_HANDLE. KS stand for kernel string. I really don't know what breakpoint is meant here. Maybe a special CPU instruction used which interfere with fdpp/comcom32.

**Comment by bolle732** [comment]
If I see it right, to apps I have this problem with are run by an interpreter. So, it could be really something with the handling of the CPU / breakpoint. Now, I use this interpreter since several years on the crash does not occur with FreeDOS.

Any hint or toughs ?

**Comment by stsp** [comment]
That had nothing to do with comcom32.
I removed only the possibility to load
fdpp by a symlink. Your memory is
currupted, please run memtest86 on it. :)

So please find out if this is related to
fdpp or comcom32.

**Comment by stsp** [comment]
Fixed problem with build timestamps.
Reproduced the problem with crash.
Wow. Something regressed a lot.

**Comment by stsp** [comment]
The initial problem seems to be that freedos is
not re-entrant. It calls the prev int handler for the
unsupported calls these days (in fdpp version).
This is used when `$_set_int_hooks = (off)`.
In that case the prev handler happens to be LFN,
which calls to DOS open, and that causes the
re-entering.
I made a very simple patch that just checks the
`InDOS` flag, and if it is non-zero, don't switch
stacks. That seems to work!

But I would be very surprised if the DOS reentrancy
problem, known and fundamental, can just be "fixed"
with such a trivial patch. Maybe I broke something else.
Would be good to test things, and maybe someone
familiar with freedos, can review that change...

**Comment by bolle732** [comment]
Hm, I remember that I had FDPP with FreeDOS command.com running stable some time ago. Is it practical to bisect FDPP only or does one have to compile DOSEmu2 too from the same time ?

**Comment by bolle732** [comment]
With latest FDPP 4cc4bdb, I have the following behaviour:

FreeDOS `command.com`:
```
ERROR: fdpp booting, this is very experimental!
ERROR: general protection at 0x7fa7a4cc62af: 0
```

Your `comcom32`:
```
ERROR: fdpp booting, this is very experimental!
ERROR: booting with comcom32, this is very experimental
ERROR: Coopthreads recursion depth exceeded, ints thread non-revect off=e6
ERROR: 	thread 0 state 3 dbg 0x1360
ERROR: 	thread 1 state 3 dbg 0x2c0
ERROR: 	thread 2 state 3 dbg 0x2142
ERROR: 	thread 3 state 3 dbg 0x3b60
ERROR: 	thread 4 state 3 dbg 0x2f42
```
On both, I only set `$_set_int_hooks = (on)`.

**Comment by stsp** [comment]
> bisect FDPP only or does one have to compile DOSEmu2 too from the same time ?

Very unfortunately, yes. Plus, new things like `$_set_int_hooks`
are not bisectable anyway, as they had bugs from the very beginning. :)

> On both, I only set `$_set_int_hooks = (on)`.

And if off? No change?

**Comment by stsp** [comment]
Please try default config.sys (with ems.sys/emufs.sys)
and default dosemu.conf.

**Comment by bolle732** [comment]
With `$_set_int_hooks = (off)`, both FreeDOS and ComCom32 produce the same `ERROR: general protection at 0x7f8baca2f2af: 0`.

In both cases, I don't have a `dosemu.conf` or `config.sys`, only file `dosemurc` with `$_set_int_hooks = (xxx)` and file `userhook.sys` with `FILESHIGH=120`. That's because I want to test as vanilla as possible...

**Comment by stsp** [comment]
OK, that's strange as I tested geos just 2 days
ago and didn't reproduce this... Will try again this
evening.
I hope int_hooks/hdimage stuff were the last
intrusive changes for now. I'll try to enter the
"stabilization mode", as the fdpp integration seems
to be mostly done.

**Comment by bolle732** [comment]
I do my tests on two different laptop. Both with Ubuntu 18.04.2 64-bit with HWE.

Now back at home on my Thinkpad, I pulled and rebuilt dosemu and fdpp. I can start PC/GEOS again. Starting an R-Basic program or opening a ZIP file crashes immediately. The same with int hooks on or off. Always I get a `ERROR: unexpected CPU exception`.

PS: R-Basic can be found here:
http://www.rbettsteller.de/BASIC/BASICDLE.HTM

**Comment by stsp** [comment]
Any idea how to replicate the problem
with crash on start-up? What is the difference
between those 2 laptops?

**Comment by stsp** [comment]
Try `stacks=0` in `userhook.sys` as a work-around.

**Comment by stsp** [comment]
> ERROR: Coopthreads recursion depth exceeded, ints thread non-revect off=e6

This should now be fixed.
So you can use comcom32, and with `stacks=0`
also fdpp.

**Comment by stsp** [comment]
> Yes, that makes my test working again with the options $_lfn_support = (on).

LFN should now be fixed too (rather than only not
to crash the test-case).

**Comment by stsp** [comment]
I don't think I can fix this problem.
There is a NULL ptr deref happens in geos
in func `VidInfo`:
```
mov ds, es:[W_bmSegment]
```
It reads 0 from here, and then corrupts the
DOS memory. Note that in other places there
is the following check:
```
EC <            tst     es:[W_bmSegment]                ; if zero, hosed >
EC <            ERROR_Z VIDMEM_HUGE_ARRAY_PROBLEM 
                    mov     ds, es:[W_bmSegment]            ; get bitmap segment
```
But in `VidInfo` the NULL check is omitted.
Inserting the check will likely avoid the crash,
but of course I don't know why it reads 0 from
there. Maybe there is some other corruption
that happens earlier, or maybe its just a geos
bug. Why in this particular place the check is
omitted?

**Comment by stsp** [comment]
I also don't like the ES valie at that point,
because `es=b136` here. Does it point into
UMB or what?
I think its undebugable on dosemu side.
Someone needs to debug that on a geos
level.

**Comment by stsp** [comment]
OK, I can now _prove_ its a geos bug.
The test is very simple.
In `dosdebug` you type `d 70:500`.
This will dump memory from that address.
If the first byte contains zero, then you do
`m 70:500 1` to write non-zero there. On
fdpp and freedos there is a non-zero value,
but on PC-DOS there is zero, so on PC-DOS
you need to modify it before the test.
Then start geos. Check this value with dosdebug.
It didn't change. Then click on a zip file -
something that causes crash on fdpp.
No matter what DOS you use, at `70:500`
you will now see zero! This is a corruption
of DOS memory. Just by a pure luck, on fdpp
that corrupts an interrupt handler, so the
crash is imminent. On PC-DOS it corrupts
the simingly unused area, and on freedos
there is some data but I don't know what it
does.
So you must be thankful to fdpp for showing
you this problem. And to me for debugging it
up to the particular code in geos sources
(believe me, it wasn't easy! :)
Of course there is still the slight chance that
this corruption is somehow dosemu-specific,
but not DOS-specific. I'll let this up to you to
find out, as the probability of that is very low.

The corruption itself is produced by this line:
```
mov ds:[si].VDI_bmFormat, ah ; assume NOT editing mask
```
because earlier 0 is loaded into DS without
a check (and ES seems wrong too).

**Comment by bolle732** [comment]
> I don't think I can fix this problem.
> There is a NULL ptr deref happens in geos
> in func `VidInfo`:
> 
> ```
> mov ds, es:[W_bmSegment]
> ```
> 
> It reads 0 from here, and then corrupts the
> DOS memory. Note that in other places there
> is the following check:
> 
> ```
> EC <            tst     es:[W_bmSegment]                ; if zero, hosed >
> EC <            ERROR_Z VIDMEM_HUGE_ARRAY_PROBLEM 
>                     mov     ds, es:[W_bmSegment]            ; get bitmap segment
> ```
> 
> But in `VidInfo` the NULL check is omitted.
> Inserting the check will likely avoid the crash,
> but of course I don't know why it reads 0 from
> there. Maybe there is some other corruption
> that happens earlier, or maybe its just a geos
> bug. Why in this particular place the check is
> omitted?

GEOS binaries can be compiled either as EC with error checking code or NC without this checks. EC is used for debugging together with SWAT, the GEOS debugger from the SDK.

Which GEOS installation did you used ? If i remember, the copy I gave you once was an EC version.

**Comment by bolle732** [comment]
> OK, I can now _prove_ its a geos bug.
> The test is very simple.
> In `dosdebug` you type `d 70:500`.
> This will dump memory from that address.
> If the first byte contains zero, then you do
> `m 70:500 1` to write non-zero there. On
> fdpp and freedos there is a non-zero value,
> but on PC-DOS there is zero, so on PC-DOS
> you need to modify it before the test.
> Then start geos. Check this value with dosdebug.
> It didn't change. Then click on a zip file -
> something that causes crash on fdpp.
> No matter what DOS you use, at `70:500`
> you will now see zero! This is a corruption
> of DOS memory. Just by a pure luck, on fdpp
> that corrupts an interrupt handler, so the
> crash is imminent. On PC-DOS it corrupts
> the simingly unused area, and on freedos
> there is some data but I don't know what it
> does.
> So you must be thankful to fdpp for showing
> you this problem. And to me for debugging it
> up to the particular code in geos sources
> (believe me, it wasn't easy! :)
> Of course there is still the slight chance that
> this corruption is somehow dosemu-specific,
> but not DOS-specific. I'll let this up to you to
> find out, as the probability of that is very low.
> 
> The corruption itself is produced by this line:
> 
> ```
> mov ds:[si].VDI_bmFormat, ah ; assume NOT editing mask
> ```
> 
> because earlier 0 is loaded into DS without
> a check (and ES seems wrong too).

I'll really thank you a lot for this in deep investigation. Have to ask on the other channels for comments about this issue. That's like with other larger software, where some bugs are coming out of the darkness 20 or 30 years later...

**Comment by stsp** [comment]
It doesnt matter what build I use,
because in this place the check is
forgotten. The check example was
from another function that accesses
the same value.

**Comment by stsp** [comment]
Also please don't quote that much, if possible.

**Comment by bolle732** [comment]
Ok, I'll try to keep the quotes short.

On my Thinkpad (TP) notebook, I can run PC/GEOS successfully with the default configuration of DOSEmu2 + FDPP + ComCom32, only FILES and STACKS set in the hook file. On my other HP notebook, it still crashes on start-up. Will try with a copy from my TP tomorrow on the HP.

**Comment by stsp** [comment]
You can as well add a check into `VidInfo` to quickly
test my findings.

**Comment by stsp** [comment]
> Will try with a copy from my TP tomorrow on the HP.

Please keep me updated on this.
I really want to make the first beta release of dosemu2,
and only your notes still sound discouraging.

**Comment by bolle732** [comment]
I had some minutes on the HP notebook. All this tests has been done on that machine where I had the `general protoection error`. Spoiler: I'm puzzled!

First on the HP notebook, I moved the existing `.dosemu` folder to `.dosemu-local`. Then I extracted the working folder `.dosemu` from the TP notebook on this HP notebook. I could start this successful several times! R-Basic programs and ZIP files, all worked as it should.

After that, I tried to start the moved installation in `.dosemu-local`, which started now too?!?

But after more tests with renaming this folders to other names, all versions begun to produce the `general protection error` again. I didn't had the time to investigate more at the moment, but I will try again tomorrow.

**Comment by bolle732** [comment]
On question to your GEOS installation:
What is the video driver you have chosen ? My one is 1280x854x16.

**Comment by bolle732** [comment]
So, I've tested more on my TP notebook and it seems we are back on the LFN problem :( Need to verify tomorrow on the HP notebook...

**Comment by bolle732** [comment]
To configure the file system driver in PC/GEOS one has to edit the `geos.ini` file.

For SNF:
```[system]
fs = msnet.geo
;primaryFSD = mslf.geo
```

For LNF:
```[system]
fs = msnet.geo
primaryFSD = mslf.geo
```

The difference is only by specifying `primaryFSD` or not.

**Comment by stsp** [comment]
Please describe your problem in details.
What is SNF and LNF?
Does it mean that one is crashing and the
other is not?

**Comment by bolle732** [comment]
Ups, sorry. SFN and LFN. I've updated the comment. I only would state, that I'm back on field one with LFN crashing under FDPP / COMCOM32 (general protection error). Without LFN support enabled in PC/GEOS (only SFN), it works as far I could test.

I only wanted to document the specific options on PC/GEOS side.

**Comment by stsp** [comment]
Could you please attach the -D9+Dd log?
Does it cure by set_int_hooks?

**Comment by bolle732** [comment]
It doesn't depend on `$_set_int_hooks`. Both `(on)`and `(off)` crash. Only the address of the GPF changes.

`dosemu -X -f dosemurc -E 'C:\ENSEMBLE\LOADER /LOG' -D9+Dd`

[boot.log.gz](https://github.com/stsp/dosemu2/files/3090442/boot.log.gz)

**Comment by stsp** [comment]
> It doesn't depend on $_set_int_hooks

Now it does again.
Please use `$_set_int_hooks=(on)` as a work-around.

**Comment by stsp** [comment]
No, that seems to be a complete fix actually.
No need for work-arounds.
LFN should work.

**Comment by bolle732** [comment]
That's really great! Thanks a lot for fixing this!

Regarding `VidInfo` which you have debugged:
Which video driver with what resolution / colour deep have you tested ?

If this is a bug inside of PC/GEOS, then it would be good to know how to reproduce.

**Comment by stsp** [comment]
What do you mean?
Just remove stacks=0 and reproduce
the video crash on your own?

**Comment by stsp** [comment]
> What is the video driver you have chosen ? My one is 1280x854x16.

I don't even know where to look this up.
I took what  you gave me, never modified
a slightest bit of it.

**Comment by stsp** [comment]
Will you be able to fix this problem?

**Comment by bolle732** [comment]
I'm in contact with the current devs of the PC/GEOS code. The SDK for Linux is still not finished and I don't have any Windows installation to do recompiling and swating (debugging). I'll let you know when I get more information.

 >> What is the video driver you have chosen ? My one is 1280x854x16.

> I don't even know where to look this up.

Seems my last post hasn't arrived here. In short: There is a program called `Preferences` or you can look at the file `geos.ini` under section `[screen 0]`. But as I know how to reproduce, no worry.

**Comment by stsp** [comment]
Its not even buildable under dos?

**Comment by bolle732** [comment]
It seams that at the moment has been the time for vacations. Myself was away and after that @stsp too.

From my side the following update:
- Still waiting for some more hints / opinions from the devs from PC/GEOS. Have to dig deeper over there.
- I can build the driver with the new SDK directly under Linux. But there could be still bugs from the SDK itself, so at the moment not fully trusted
- Tried some time ago running the DOS SDK with BCC 3.1 under DOSEmu2, but didn't succeeded due to problems with the Borland RTL
- Have been stopped with a `SMALLOC: Out Of Memory on alloc, requested=128` error with the version when @stsp went to holiday, but current DOSEmu2 / FDPP / ComCom32 works again

**Comment by stsp** [comment]
Good to know there is a progress on this.

**Comment by stsp** [comment]
> I can build the driver with the new SDK directly under Linux.

If you can, I think you should. :)

> But there could be still bugs from the SDK itself, so at the moment not fully trusted

No "but"s. :) If you can build only the driver and use the
trusted build of everything else, then you can debug the
problem very quickly, w/o involving yourself into the SDK
compatibility bugs.

**Comment by bolle732** [comment]
There is still one unresolved bug regarding ChunkArrays affecting my GeoLadder, so my trust is not too high at the moment.

Maybe I could help regarding to document the way regarding setting `STACKS=0`. Where would be be the desired place to document workaround regarding specific programs ?

**Comment by stsp** [comment]
There is tweaks.txt, but its mostly for
games. Games are many, each with its
own set of bugs. It would be quite shame
to put there a work-around for open-source
os. Why cant you rebuild a video driver?
I dont believe it alone affects your
stability.

**Comment by stsp** [comment]
> Starting an R-Basic program or opening a ZIP file crashes immediately.

@bolle732 can this ticket be updated
a bit, elaborating on "opening a ZIP file"?
I see in https://github.com/bluewaysw/pcgeos/issues/83
that they have a crash with GeoZip.
So do they hit the same video
driver bug that was mentioned here:
https://github.com/dosemu2/dosemu2/issues/807#issuecomment-483061711
Were you also using GeoZip to
reproduce this?

**Comment by bolle732** [comment]
I can't say for sure, that I had the problem with GeoZip. It was more with larger apps like R-Basic. I believe to remember someone telling me that the GeoZip in the Breadbox Ensemble had some sort of a bug. It's difficult to say.

But more important:
With current DOSEMU2 / FDPP / COMCOM32 and the Breadbox Ensemble 4.13 together with the new VGA16 driver, I'm unable to reproduce the crash. Neither with GeoZip or the 3rd party program R-Basic. Even with `STACKS=0`.

userhook.sys
```
FILESHIGH=120
rem STACKS=0
```
dosemurc
```
$_cdrom = ""
$_umb_b0 = (on)
$_ems = (0)
$_xms = (32768)
$_X_vesamode = "1920,1080 1920,1200"
$_X_vgaemu_memsize = (8192)
```
```
C:\>ver /r
comcom32 v0.1
 Source Control Revision ID: alpha-2-46-g54b0b2d
 
Reported DOS version (Int21.3000): 5.00 OEM: FDh
Reported true DOS version (Int21.3306): 7.10
Version string (Int21.33FF): FDPP kernel 1.3 [GIT: 1.4-13-g2cceda6] (compiled Dec  1 2021)
```

**Comment by stsp** [comment]
`STACKS=0` was actually a cure,
not  a reproducer.
Have you noticed how much more
free memory does fdpp+comcom32
combo now give?
I thought you would admit that. :)
Its probably out of reach by any
other setup.

**Comment by stsp** [comment]
I think the only reliable way
of checking for a bug, is to
use instructions in this comment:
https://github.com/dosemu2/dosemu2/issues/807#issuecomment-483077114
Since fdpp's memory layout
have changed, the old reproducers
may not work, but checking the
specific address with dosdebug
would rule out the bug's presence.

Also the aforementioned comment
mentions zip file:
`Then click on a zip file -
something that causes crash on fdpp.`
Does the click on a zip file
invoke GeoZip, or is it something
else?

**Comment by bolle732** [comment]
> I thought you would admit that. :)
Its probably out of reach by any
other setup.

That's really fantastic and yes, I noted it. I'll admit it for sure! I even hack the FDPP for getting the 3 SFTs from conventional to upper memory. Windows may crash then, but GEOS does not ;-) Maybe it could be a switch in the future. Ok, I stop kidding...

**Comment by bolle732** [comment]
> Does the click on a zip file
> invoke GeoZip, or is it something
> else?

If clicking in the GeoManager on the GeoZip, it could be that the GeoManager is reading the token (icon) from the GeoZip binary itself and installing this token to the token database. Could be related too to some slight instability several months ago in MSF, but at the moment I don't have any problems with file system access.

Unfortunately, I can't reproduce the crash with GeoZip (anymore). DOSEMU2 and FDPP runs extremely stable!

**Comment by stsp** [comment]
> If clicking in the GeoManager on the GeoZip,

No, just on a zip file.

> Unfortunately, I can't reproduce the crash with GeoZip (anymore). DOSEMU2 and FDPP runs extremely stable!

I applied the patch to fdpp now,
which would allow you to do this:
```
diff --git a/src/plugin/fdpp/hooks.c b/src/plugin/fdpp/hooks.c
index a43a56c56..c6a91f632 100644
--- a/src/plugin/fdpp/hooks.c
+++ b/src/plugin/fdpp/hooks.c
@@ -114,10 +114,15 @@ static int fdpp_pre_boot(unsigned char *boot_sec)
     kptr = lowmem_alloc_aligned(16, krnl_len + HEAP_SZ);
     daddr = DOSEMU_LMHEAP_OFFS_OF(kptr);
     assert(!(daddr & 15));
+#if 0
     heap_seg = 0x90;  // for low heap
     seg = DOSEMU_LMHEAP_SEG + (daddr >> 4);
     khigh++;
     hhigh++;
+#else
+    seg = 0x60;
+    heap_seg = 0;
+#endif
 #else
     /* alternative layout for testing */
 #define HEAP_SZ (1024*3)
```

That will return the previous
memory layout to help you reproduce
the bug.
As a bonus, the just-applied
patch will also allow you to do this:
```
diff --git a/src/plugin/fdpp/hooks.c b/src/plugin/fdpp/hooks.c
index a43a56c56..18dd67ade 100644
--- a/src/plugin/fdpp/hooks.c
+++ b/src/plugin/fdpp/hooks.c
@@ -114,7 +114,7 @@ static int fdpp_pre_boot(unsigned char *boot_sec)
     kptr = lowmem_alloc_aligned(16, krnl_len + HEAP_SZ);
     daddr = DOSEMU_LMHEAP_OFFS_OF(kptr);
     assert(!(daddr & 15));
-    heap_seg = 0x90;  // for low heap
+    heap_seg = 0x70;  // for low heap
     seg = DOSEMU_LMHEAP_SEG + (daddr >> 4);
     khigh++;
     hhigh++;
```

... to get even more memory.
It will write an error about unsupported
config, but should work fine.

**Comment by stsp** [comment]
Applied yet another patch to
fdpp. Now you can set heap_seg
to 0x50, getting yet more memory.

**Comment by bolle732** [comment]
> Applied yet another patch to
> fdpp. Now you can set heap_seg
> to 0x50, getting yet more memory.

That's absolute fantastic, there should be really a hall of fame for this ;-)

**Comment by bolle732** [comment]
> That will return the previous
> memory layout to help you reproduce
> the bug.

I've set the `#if` on line 112 to `0` to enable the `#define HEAP_SZ (1024*3)`. DOSEMU2 prints the following:

```
Load at seg 0x60, 0xfa40 is not supported
dosemu.bin: /home/opti.net/bollhalderan/Development/fdpp/fdpp/objtrace.cpp:68: void objtrace_gc(far_t): Assertion `gc.idx > 0' failed.```

But even with this I'm unable to reproduce a crash. Maybe I can try some more things later.

**Comment by bolle732** [comment]
> But even with this I'm unable to reproduce a crash. Maybe I can try some more things later.

I forgot to remove `STACKS=0`. Have to test more...

**Comment by stsp** [comment]
> dosemu.bin: /home/opti.net/bollhalderan/Development/fdpp/fdpp/objtrace.cpp:68:
> void objtrace_gc(far_t): Assertion `gc.idx > 0' failed.

Please attach the log, I
can't reproduce this. Have
never seen any errors from
the garbage collector before.

Anyway, this is not the change
I asked you to do.

**Comment by stsp** [comment]
@bolle732 do you still need to set
`FILESHIGH=120`? During this thread
I set the fdpp default to 64, so maybe it
now works out of the box?

**Comment by bolle732** [comment]
> @bolle732 do you still need to set
> `FILESHIGH=120`? During this thread
> I set the fdpp default to 64, so maybe it
> now works out of the box?

PC/GEOS itself will start with the 64 files setting. But it crash later when opening some programs and/or documents. I did a short test on my side to verify that.

Even on a bare metal DOS computer, best practice has been to set files up to 100 or 120.

**Comment by stsp** [comment]
OK, thanks for info.
I reverted the fdpp default back to
16 and set `fileshigh=128` in fdppconf.sys
instead. Not sure what made me to
tweak fdpp instead of the config...

**Comment by stsp** [comment]
So does PC-GEOS work out-of-the-box
w/o any custom tweaks on dosemu2 since
today?
Can you perform the simple dosdebug check:
https://github.com/dosemu2/dosemu2/issues/807#issuecomment-483077114
to see if the NULL-deref is no longer there?

**Comment by bolle732** [comment]
Hi Stas

I really did forgot about this issue. Currently, FreeGEOS works on Ubuntu 24.04 and 26.04 extremely well with the default configuration by-side I have to specify the parameter `-p`.

I'll forward the findings of Claude to a new issue at the FreeGEOS site and ask them for their advice.

**Comment by stsp** [comment]
> I'll forward the findings of Claude

These are all my finding from 2019:
https://github.com/dosemu2/dosemu2/issues/807#issuecomment-483077114
Claude only refreshed them and tested
on the latest Geos. But he proposes the
ready-to-use patch, which is the only
improvement from from mine.

**Comment by stsp** [comment]
> I really did forgot about this issue.

Which is why I asked Claude to
refresh it. I knew that you didn't apply
the fix, and that it wont get fixed by
itself.
