### ISSUE TITLE
Runtime error 200 at 090D:0091 running turbo pascal program

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#808]
When I try and run my ancient VGA textmode font editor, dosemu quits with

Runtime error 200 at 090D:0091

Program is attached
[ascii deception - font editor.zip](https://github.com/stsp/dosemu2/files/3051020/ascii.deception.-.font.editor.zip)

DOSBOX screenshot for reference
![Screenshot from 2019-04-06 23-56-51](https://user-images.githubusercontent.com/179677/55676215-0f9a8880-58c8-11e9-9b89-00b8e9ae0557.png)

**Comment by skitt** [comment]
This is probably the Turbo Pascal speed-related error, see [this page](http://www.pcmicro.com/elebbs/faq/rte200.html) (among many others) for a fix.

**Comment by stuaxo** [comment]
I wonder if it's possible to detect this?

(do TurboPascal generated exes have a predictable structure?) 

Having some compatibility patches, like Windows does could be interesting.

**Comment by stsp** [comment]
It might be possible by analysing
the code pattern from the int0 handler,
but this is not what dosemu usually does.
You can install the tsr fix that will do
exactly that.

**Comment by stuaxo** [comment]
Apart from memory usage, are there any downsides to me running the TSR all the time - will it slow things down ?

**Comment by stsp** [comment]
No. And tsr is only an example.
There are tools to patch out the
problem in a binary - more practical.
