### ISSUE TITLE
freepascal installer crashes with $_set_int_hooks = (on)

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#809]
I tried downloading the freepascal installer and running install.exe, but it came back with

runtime error 6 at 5B59:

![Screenshot from 2019-04-13 19-36-22](https://user-images.githubusercontent.com/179677/56083942-b2e92180-5e23-11e9-84df-2540d2dcccfb.png)

The version I tried using is the go32v2 version for i386
https://www.freepascal.org/down/i386/go32v2.html

**Comment by stsp** [comment]
I can't reproduce this.
Downloaded and unpacked `dos304.zip`.
Installation runs to the end. Except that it
complains at start about the missing LFN support.

**Comment by stsp** [comment]
Tried `$_set_int_hooks = (on)` to see if LFN
would work then, but it crashes!
OK, something to look at.

**Comment by stsp** [comment]
```
ERROR: Coopthreads recursion depth exceeded, ints thread non-revect off=e6
ERROR: 	thread 0 state 3 dbg 0x1360
ERROR: 	thread 1 state 3 dbg 0x2c0
ERROR: 	thread 2 state 3 dbg 0x2142
ERROR: 	thread 3 state 3 dbg 0x6c60
ERROR: 	thread 4 state 3 dbg 0x2f42
```

Something fdpp-related I suppose.

**Comment by stuaxo** [comment]
Dosbox crashes in this as well... it gets further and then the TUI displays that it can't read install.dat.

Probably completely off topic, but maybe a clue that it's doing something weird.

**Comment by stsp** [comment]
No, its not.
It only crashes with particular non-default
option, so something is wrong in dosemu2.
I am in a process of recovering the knowledge
about decoding the coopth errors...

**Comment by stsp** [comment]
I improved the crash dump a little, it now looks like this:
```
ERROR: 	thread 0 state 3 dbg 0x0000136000000001
ERROR: 	thread 1 state 3 dbg 0x020002c000000033
ERROR: 	thread 2 state 3 dbg 0x7100214220001802
ERROR: 	thread 3 state 3 dbg 0x00006c6000000001
ERROR: 	thread 4 state 3 dbg 0x11232f4213800e01
ERROR: 	thread 5 (rejected) dbg 0x12032f4213800e01
```

If I decode that rightly, then threads 0 and 3 belong
to fdpp, thread 1 belongs to system.com, and the rest
belongs to bios. Why bios wants 3 threads, is something
to find out...

**Comment by stsp** [comment]
The crash started to happen after this patch
by Andrew: 595bdc9b6
It consumes one more thread for `GetDataSegment()`.
As a quick fix I made lfn.c to release the thread
before calling to DOS open.

**Comment by stsp** [comment]
6c8da4c started to consume the coopthread
for system.com, in case of comcom32 (but not 4dos).
This made comcom32 look responsible for some
crashes.
Reverted.
Or maybe just increase the maximum number of threads in coopth.c? :)

**Comment by stsp** [comment]
@stuaxo What's the status of this?
I see that I fixed the dosemu crash here,
but was the freepascal crash also fixed?

**Comment by stuaxo** [comment]
I will give this another test and let you know.

**Comment by stsp** [comment]
Please open another ticket in this case.
