### ISSUE TITLE
How to switch into simx86 mode?

### ISSUE THREAD

**Issue by JL2210** [stsp/dosemu2#811]
I'm testing a program that I'm not sure is safe and I don't want to crash dosemu/run directly on my processor. How do I switch into simx86 mode?

**Comment by stsp** [comment]
`dosemu -I 'cpu_vm emulated'`

Nevertheless, if you encounter any crash
(with or without that option), please report it here.

**Comment by JL2210** [comment]
How to do this within dosemu?

**Comment by stsp** [comment]
Mm, currently there is no such way (older
dosemus had ecpuon.com). Why do you need
it within dosemu?

**Comment by JL2210** [comment]
Because it's too slow to startup. I know I was able to do it before, I just don't remember how. Anyway, my application almost works, it just doesn't show any output.

**Comment by JL2210** [comment]
Just had to re-link it. It works now.

**Comment by stsp** [comment]
Do you mean dosemu is slow to boot?
Let me see:
```
$ time dosemu -I 'cpu_vm emulated' -E mem
real	0m2,289s
user	0m1,846s
sys	0m0,376s

$ time dosemu -I 'cpu_vm kvm' -E mem
real	0m1,783s
user	0m1,343s
sys	0m0,370s
```

So its just 0.5 seconds slower!
How can I reproduce the startup slowdown?

**Comment by JL2210** [comment]
It wasn't startup slowdown. I enabled an option inside DOS (probably a FreeDOS command) and it started running very slowly. The bootup time is definitely very fast.

**Comment by JL2210** [comment]
There's also some weird error messages, but I'll put those in another issue.

**Comment by stsp** [comment]
These days I am not aware of some very
bad slowdowns with cpu-emu. However, if
the good case is demonstrated, I can return
`ecpuon`.

**Comment by JL2210** [comment]
Personally, I wouldn't like to restart dosemu to configure options. However, I would say that one good reason to bring it back is compatibility with other dosemu/FreeDOS versions.

**Comment by stsp** [comment]
The thing is, cpu-emu is not even enabled by
default. So it is not "slow" by default. I was a bit
confused when said this can be the case for
returning `ecpuon`, as the current default is
fast running on a real CPU.

**Comment by stsp** [comment]
So the case for returning `ecpuon` can be
some prog that doesn't run on a real CPU
and does on cpu-emu (which would be a bit
strange).
