### ISSUE TITLE
Weird error messages on startup

### ISSUE THREAD

**Issue by JL2210** [stsp/dosemu2#812]
See image.

![Screenshot 2019-04-13 at 7 04 16 PM](https://user-images.githubusercontent.com/38843657/56086180-4704ba00-5e1f-11e9-892d-10a4bcb2a6bc.png)

**Comment by stsp** [comment]
This is an fdpp version mismatch.
Please update.
Hmm, but fdpp version is usually checked at
run-time. So maybe this is something else, like
`fdppconf.sys` renamed to `fdconfig.sys`?
Are you booting fdpp or freedos?

**Comment by stsp** [comment]
By the way, you don't need to do image.
You can copy/paste with mouse from dosemu2 window.
Hold LShift and select text with the mouse.

**Comment by JL2210** [comment]
FDPP with FreeDOS commands.

**Comment by JL2210** [comment]
I build FDPP from Git source and install it whenever there's a new update.

**Comment by stsp** [comment]
Please attach the `-D9+dD` log.

**Comment by JL2210** [comment]
Just recompiled FDPP and dosemu from source, get this error:

```
fdpp.c:29:2: error: #error wrong fdpp version
 #error wrong fdpp version
  ^~~~~
```

`FDPP_API_VER` is `13`. I think you forgot to update it in the dosemu sources.

**Comment by JL2210** [comment]
```
fdpp.c:33:28: fatal error: 13: No such file or directory
 #include STRINGIFY(FDPP_API_VER)
                            ^
```

**Comment by stsp** [comment]
https://github.com/stsp/dosemu2/commit/2ecb700f61fcc2ba0241277b9f200f9687508f79
This commit updates the version to 13, so nothing
is forgotten.

**Comment by JL2210** [comment]
Related commit: https://github.com/stsp/fdpp/commit/4cc4bdbe183ffb28b8b9e268906d82ecc0aa9419

**Comment by stsp** [comment]
Exactly.
Problem solved?

**Comment by JL2210** [comment]
Aha! I figured out the issue: I was building from my personal fork.

**Comment by JL2210** [comment]
Works like a charm now! Just had to clean up a few things and it works without complaint.
