### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JL2210** [stsp/dosemu2#813]
```
ERROR: general protection at 0x7137d479fd71: 66
Child exited with status: 4
```
This crashes DOSEMU when running this program:
[start.com](https://github.com/stsp/dosemu2/files/3077935/start.com.txt)

**Comment by stsp** [comment]
Why shouldn't it crash?
dosbox also doesn't run it.

**Comment by JL2210** [comment]
Darn it. What's the error log?

**Comment by stsp** [comment]
Another useless comment like the above,
and I'll ban you. Seriously.

**Comment by JL2210** [comment]
I wrote the program myself. Could you help me debug it?

**Comment by stsp** [comment]
No.
Use dosdebug to debug your program.
This site is not for debugging your program.

**Comment by JL2210** [comment]
OK. Thanks.
