### ISSUE TITLE
Crash while trying to use interrupt 15 - APM management

### ISSUE THREAD

**Issue by JL2210** [stsp/dosemu2#814]
I'm trying to write a little program to shut down DOSEMU. It works fine in FreeDOS and QEMU, but not in DOSEMU. It causes a crash/reboot.

Error log:
```
ERROR: bad dos helper function: AX=0x011a
ERROR: fdpp booting, this is very experimental!
dosemu.bin: int.c:309: register_plugin_call: Assertion `!plops.call' failed.
```

Program: [boot.com](https://github.com/stsp/dosemu2/files/3086972/boot.com.txt)

Relevant source code (on my end):
```
.globl bios_shutdown
bios_shutdown:
        pusha
        xor %bx, %bx
        mov $0x5301, %ax
        int $0x15
        xor %cx, %cx
        mov $0x530e, %ax
        int $0x15
        mov $0x5307, %ax
        inc %bx
        mov $0x03, %cx
        int $0x15
        popa
        ret
```

**Comment by stsp** [comment]
Use `exitemu` or just `exit`.

**Comment by JL2210** [comment]
That's not the point. It's a crash. Something that should be fixed.

**Comment by stsp** [comment]
I dont think crash has anything to do
with that. For example I see the weird
error msg even before boot msg!
So its just some build experiments of yours.

**Comment by stsp** [comment]
Or do you mean it is trying a reboot,
and the boot msg displays for the second
time? Then its a problem.

**Comment by JL2210** [comment]
The boot message displays a second time and then an assertion fails.

**Comment by stsp** [comment]
I don't see any crash.
All I see, is:
`Booting from disk... (press escape key to continue)`
And there is no even hang, I can type letters.

**Comment by JL2210** [comment]
Yes. Then press escape.

**Comment by stsp** [comment]
Still no crashes, asserts or a weird double-boot messages.
```
ERROR: fdpp booting, this is very experimental!
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=00000000 while in vm86 (DOS)
```

**Comment by JL2210** [comment]
The behavior changes every time it's run. That's odd.

**Comment by stsp** [comment]
If it says exception 6, then your program executes
the random memory. Its not odd that then it acts randomly.
Of course it shouldn't assert anyway, but it would be
quite difficult to fix for example the jit backend to never
do bad things on a wrong input.

**Comment by stsp** [comment]
So I can't reproduce any reboot or assert.
Just executing the random data.

**Comment by JL2210** [comment]
It's not random data. The interrupt is failing to shut down DOS.

**Comment by stsp** [comment]
int15 returns CF to you a couple of times, after
which your prog starts to execute random data.
You need to terminate your program correctly if
int15 returned an error.

**Comment by andrewbird** [comment]
I didnt check but since int15 returns CF, does that mean Dosemu's BIOS doesn't support the APM functions that OP is trying to use?

**Comment by stsp** [comment]
It does. And?

**Comment by andrewbird** [comment]
No and, just that nowhere in this thread does it say that is the case. It seems to me that OP is under the the impression that something is wrong with Dosemu, when it seems to be the case that the BIOS doesn't support APM function and his program doesn't check to make sure.
Just hoping to add some clarity.

**Comment by stsp** [comment]
I think he just got an assert somehow, which
would be a bug, but not reproducible. And since
his code executes random data, perhaps something
got wrong indeed, maybe in cpu emulator.

**Comment by JL2210** [comment]
@stsp @andrewbird Thanks. I've fixed this (the `jp` instruction is useful for this).
