### ISSUE TITLE
QEMM's MFT hangs at startup on 32bit machine

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#819]
**Describe the bug**
When starting QEMM 9.01's MFT it never progresses past the splash screen. This occurs only on a 32bit machine (tested in hardware vm86 and also fullsim). With exactly the same DOS installation MFT works correctly on a 64 bit machine (tested in kvm and also fullsim).

![mft](https://user-images.githubusercontent.com/220835/56977439-16d25080-6b6d-11e9-9569-f2365cd4c83d.png)
mentioned in #817 

for reference here is the config.sys that was used
~~~
rem DEVICE=C:\QEMM\QEMM386.SYS RAM                                              
lastdrive=Z                                                                     
device=dosemu\emufs.sys                                               
rem device=dosemu\ems.sys                                                       
device=himem.sys                                                                
device=dosemu\umb.sys                                                           
DOS=LOW                                                                         
~~~

DOS used was MS-DOS 6.22

**To Reproduce**
1/ Use 32 bit machine
2/ cd qemm
3/ mft
4/ see hang

**Attach the log**
[t1.zip](https://github.com/stsp/dosemu2/files/3132186/t1.zip)

**Comment by stsp** [comment]
How about trying the default dos/config instead?
I'll be away for vacations, so no fixes for a few weeks.
Maybe you can take a look at that yourself in a mean time. :)

**Comment by jharrison03** [comment]
QEMM 9 MFT works here on a Debian 32-bit environment, but this is Xeon X5460 machine.  Obviously not running QEMM386 as the memory mananger.

device=c:\dosemu\emufs.sys
device=c:\dosemu\ems.sys
devicehigh=c:\dosmax\dosmax.exe /r- /p- /n+ /x+ /c- /m1
dos=high,umb
files=30
buffers=6
fcbs=1,0
stacks=0,0
lastdrive=z
devicehigh=c:\utils\nansi.sys /s /p
devicehigh=c:\dosemu\cdrom.sys
installhigh=c:\dos\share.exe /f:3640 /l:40
shell=c:\dosmax\shellmax.com /r- c:\command.com c:\ /e:1280 /p

**Comment by jharrison03** [comment]
![MFT](https://user-images.githubusercontent.com/44394516/57121024-efcd7780-6d42-11e9-80c3-77570d6e3cf6.png)

**Comment by stsp** [comment]
Thanks for confirming.
So does mft dislike a particular cpu? :(
Andrew, can you gather more info
on a broken pattern?

**Comment by jharrison03** [comment]
Not actual 32-bit CPU here but 32-bit kernel:

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Xeon(R) CPU           X5460  @ 3.16GHz
stepping	: 6
microcode	: 0x60f
cpu MHz		: 2002.012
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 6317.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 38 bits physical, 48 bits virtual

**Comment by andrewbird** [comment]
I no longer have this 32 bit system, I'll close for now. Thanks.

**Comment by stsp** [comment]
> I no longer have this 32 bit system, I'll close for now. Thanks.

And surely no cpuinfo from it? :(

**Comment by stsp** [comment]
> This occurs only on a 32bit machine (tested in hardware vm86 and also fullsim).

Obviously w/o switching $_cpu_vm?

**Comment by andrewbird** [comment]
> And surely no cpuinfo from it? :(

Actually it is this same physical machine 'Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz', but I wiped the 32bit system and reinstalled a 64bit one.

>  Obviously w/o switching $_cpu_vm?

I very much doubt it. In those days I ran 32bit so I could use hardware vm86 and I never ran kvm.

**Comment by stsp** [comment]
> I very much doubt it. In those days I ran 32bit so I could use hardware vm86 and I never ran kvm.

But you said about fullsim.
This problem should not manifest on it.

**Comment by andrewbird** [comment]
> But you said about fullsim.
This problem should not manifest on it.

Yes. I don't remember specifically, but I would hope that if I said 'hardware vm86' and 'fullsim', that's where I saw the problem. Perhaps it's only coincidental that the mft program gave a similar effect on kvm.

**Comment by stsp** [comment]
But isn't it more likely that you didn't
change $_cpu_vm and so it wasn't fullsim
at all?
You did that thing many times on various
occasions.

**Comment by andrewbird** [comment]
It is quite possible, as there's a definite lack of understanding on my part. There is a log file in the first post (t1.zip) that you might be able to understand what options were used, but unfortunately I didn't post both.
