### ISSUE TITLE
Where to document config options

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#82]
Printing to PDF doesn't "just work" - you get a blank page .. in itself this is probably a bug...    should I add this to tweaks, or as a comment in dosemu.conf ?

In the meantime I'd like to document the fix here   https://www.centos.org/forums/viewtopic.php?t=3323

**Comment by stsp** [comment]
Could you please describe what the
problem is exactly? dosemu simply executes
the command specified in "$_lptX", so if you
use the same command on a generic text file,
will you also get a blank page or what?
cat a.txt | lpr -l

**Comment by stuaxo** [comment]
Ah, this is a cups thing.   Guess I was a bit naive to think that cups-pdf would just work installing from apt-get.

It seems like to make blank pages in raw mode, going to close this.

**Comment by stsp** [comment]
Does it work fine without -l?
I guess we can set up one port with -l and
one without - for better example.

**Comment by stsp** [comment]
So... I guess I will apply the patch that
sets up $_lpt2 for PDF printing. Feel free to
do a pull request.
