### ISSUE TITLE
ERROR: Neither FreeDOS nor comcom32 installation found.

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/dosemu2#820]
I'm installing the software on a fresh Debian 9.9 and I get the same message on the log file. It is very strange because I can run the program perfectly on another Debian 9.9 computer. It seems to me that I am missing a library at the time of compilation. No custom modifications this time.

I'm attaching the bootlog and screenshot.

![Screenshot from 2019-05-03 09-55-34](https://user-images.githubusercontent.com/47893772/57164916-935e6c80-6dc3-11e9-86ac-3ca038867793.png)

[boot.log.gz](https://github.com/stsp/dosemu2/files/3143523/boot.log.gz)

**Comment by stsp** [comment]
Is this still a problem?
ssh?

**Comment by ZoccoCss** [comment]
Yes, I still have this problem. 

I cannot ssh from that computer. 

I'm trying to do this install in Debian by the book without any special modifications i.e. no symlinks between comcom32 and command.com, without using the freedos binary, etc. 

The problem has to do with comcom32 and it seems that it's not included when I compile dosemu2. So I tried to compile comcom32 and I get an error. 

![Screenshot from 2019-05-17 12-00-53](https://user-images.githubusercontent.com/47893772/57959908-05f73e00-78d4-11e9-80ba-f32ac7ea6b7f.png)


Like I said, I might be missing a library somewhere.

**Comment by stsp** [comment]
I disabled the boot with missing deps.
You can install comcom32 from PPA, or you
can use `make dep` or `./build.sh`.

**Comment by ZoccoCss** [comment]
Fixed. Thank you.
