### ISSUE TITLE
High density video modes

### ISSUE THREAD

**Issue by RossBoylan** [stsp/dosemu2#823]
**Describe the bug**
I have a dos program that has a "vga" mode option that gives more vertical space.  There are 2, likely related, issues with this:

1. The display is all squished and basically unreadable;
2. The dosemu window does not resize when this alternate mode is activated.

Unless the window expands, there is no way to have a reasonable display.

Here's screenshot:
![smooshedgv](https://user-images.githubusercontent.com/2514994/57594595-c7d5d500-74f5-11e9-848a-83ef5f5a2931.png)

**To Reproduce**
Locally built debs and installed them for dosemu2, fdpp, comcom32.
Launched dosemu2, which opened a window.  Within that, switched to the program directory and did gv.exe /v /l
/v = "vga mode" as I recall.  Gets about double the number of lines to display.
/l reuse last configuration/open files..

**Desired Behavior**
In the original dosemu for sure, earlier version of dosemu2 I think, and dosbox, I think, the window resizes and the resulting display has letters about the same size as the vanilla mode.

This may depend somewhat on the availability of suitable fonts.

On exiting the program the window reverts to its original size.

**Comment by skitt** [comment]
> In the original dosemu for sure, earlier version of dosemu2 I think, and dosbox, I think, the window resizes and the resulting display has letters about the same size as the vanilla mode.

Are you sure of this? On real VGA, and DOSBox and DOSEMU (“original”), and anything else emulating VGA, 50-line mode is obtained by setting mode 3 (80×25) and selecting an 8-line font, which results in the “squashed” display you’re seeing. There are some SuperVGA text modes which provide higher resolution text, but in all cases an 80×50 display with a 4:3 ratio the text is going to appear squashed. (The Windows console can be set to 80×50 with 16-line fonts, but that’s different.)

**Comment by RossBoylan** [comment]
I'm sure about the behavior of dosemu under linux.  I did tweak the fonts and window geometry.  Actually, when I apply the same tweaks for dosemu2 it behaves the same way.

I found (under dosemu v1) the font worked in either regular or extended video mode.  My recollection of the meaning of the switch for gv may not be quite right (though I'm pretty sure v was for vga), but the effect was definitely 80x50.  I think vga11x19 was distributed to accompany dosemu.

Personal .dosemurc (for dosemu, not dosemu2):
# 640 is default value, but I set it higher in /etc
$_dosmem = (640)

# 8192 is default, but /etc says 1024
$_ems = (8192)

# 0 = all CPU power to DOSEMU; default = 1 = nicest, then higher:more CPU power

$_hogthreshold = (4)
# for Debian display
$_X_font="vga11x19"

# for cygwin X
#$_X_font="10x20"

# override default of
# $_cdrom = "/dev/cdrom"
$_cdrom = ""

The system dosemu.conf had these non-commented lines:
$_dosmem = (768)
$_ems = (1024)
$_speaker = "native"
$_X_winsize = "800,600"

Ah: with the personal setting above in ~/.dosemu/.dosemurc (do I need the . in front of dosemurc?) I get the same behavior under dosemu2.

So my immediate problem seems solved.  The out of the box behavior could be better IMO, but I understand it's easier to let it be.

BTW, I'm very impressed that the CPU useage is almost undetectable when I have the program up.  A program like grandview that is waiting for mouse (maybe keyboard too, but it seemed more of an issue for "graphical" programs)* would typically chew up noticeable CPU even when "idle".  That was true, though not as badly, with the hogthreshold (which I did copy with the rest to the dosemu2 config).

*Grandview isn't graphical in the way a video game would be; it's more like a curses interface: full screen, mouse sensitive, but textual.  Still the best outliner I've found.

________________________________________

**Comment by skitt** [comment]
> I'm sure about the behavior of dosemu under linux. I did tweak the fonts and window geometry.

Right, the latter explains what you get: you’re specifying the font to use, instead of the default behaviour (which is to use the font programmed into the VGA, either from ROM or whatever was loaded into the card). The default behaviour is to squash everything; but specifying a font means that the window stretches, in both DOSEMU and DOSEMU2.

**Comment by stsp** [comment]
Yes, thanks for the good explanation.
But one thing I dont understand is why
both squashed and unresizable together.
They should be either/or IIRC.
Resizable by default.
Will check later.

**Comment by stsp** [comment]
> The dosemu window does not resize when this alternate mode is activated.

Could you please confirm that it resizes otherwise?
Does the resizing stop only when this mode is set?

**Comment by stsp** [comment]
> Ah: with the personal setting above in ~/.dosemu/.dosemurc (do I need the . in front of dosemurc?)
> I get the same behavior under dosemu2.

I am confused.
If you specify the custom font, the window won't
resize, as we don't resize the custom fonts.
But this has nothing to do with the mode that the
app have set.
Lets close as I think its an operator error.

**Comment by RossBoylan** [comment]
I think you've got it backwards: the window only resizes if I specify a custom font (and window size--unclear if that matters) and run my app that wants 80x50 mode.

The default behavior is that if the app wants 80x50 dosemu switches to a tiny font that allows it to fit twice the lines into the same vertical space.

If you want to say that failing to realize that customization was necessary to have anything legible was operator error, you can.  But I probably wouldn't agree :)

Under dosemu2 I have always made the changes of setting the font and prespecifying the window dimensions to something larger than default together, I'm not sure if specifying the font alone would do the trick.  The fact that I added the dimensions suggests that, at least under dosemu v1, both were necessary to get good results.

It's also a bit odd the prespecifying the font fixes the font size, but prespecifying the window dimensions does not fix the window size.

Thinking about it, the virtual screen resolution probably is important: a real 640x480 screen can't display 50 lines properly.

I'm also not sure how all this would play out with a high dpi physical display.

Ross

________________________________________

**Comment by skitt** [comment]
> Thinking about it, the virtual screen resolution probably is important: a real 640x480 screen can't display 50 lines properly.

Right, VGA text mode is 640×400 or 720×400 ;-).

**Comment by stsp** [comment]
> I think you've got it backwards: the window only resizes if I specify a custom font

I thought by resize you mean the ability to
manually resize it with the mouse, dragging
by th4e edge. But now I understand you mean
an automatic resize.

> It's also a bit odd the prespecifying the font fixes the font size, but prespecifying the window
> dimensions does not fix the window size.

Again, 2 definitions of "fixed window size".
One is that you can't resize it with the mouse,
and another is that it doesn't resize itself.
We always try to allow the user to resize manually,
and as for resizing itself - you can disable that
by doing the following steps:
1. disable custom font
2. set `$_X_winsize`
3. disable `$_X_fixed_aspect`
Of course you would ask to achieve the same
w/o doing step 1, but for this we'll need to use
SDL_ttf/resizable fonts.

> I'm also not sure how all this would play out with a high dpi physical display.

We have the scaling filters, but currently they do
not affect custom fonts. If we switch to ttf, they will.
So there is a problem here, but not a bug.
Someone should just write the code.
