### ISSUE TITLE
VirtualBox compatibility

### ISSUE THREAD

**Issue by RossBoylan** [stsp/dosemu2#824]
dosemu2 is using KVM for virtualization.  Does this mean that a host running dosemu2 can not also run (host) VirtualBox?  VirtualBox uses (or used to, maybe it's changed with the latest version) a different virtualization driver on Linux, and only one can be loaded at a time.

Or perhaps whichever program starts first wins, and the other one falls back to software emulation?

**Comment by stsp** [comment]
dosemu2 does not require kvm,
it just works much faster with it.
So if you disable kvm you can still
use dosemu2.
Whether or not is vbox currently
compatible with kvm, I dont know.
Maybe someone else does.

**Comment by RossBoylan** [comment]
So is it "the first one wins" scenario: if one has another application that uses some virtualization driver other than kvm, if "other app" starts first then dosemu will fail to load kvm and go with software emulation?  And,  conversely, if dosemu starts first, "other  app" will find it can't load its virtualization driver and either fail or emulate, depending on its capabiities?

Does dosemu unload kvm when it's done?

Actually, suppose "other app" is qemu-kvm, which does use the kvm kernel module: is it OK to run virtual machines under it at the same time dosemu is running on the host?

________________________________________

**Comment by stsp** [comment]
You can explicitly disable kvm in
dosemu2 by `$_cpu_vm` option.
Or you can unload the kvm module
and load vboxdrv before starting
dosemu2. In both cases there will
be no first wins scenario. AFAIK you
need to unload kvm before loading
vboxdrv.
No app does unload kvm when its done.
Yes, running other kvm apps in parallel
is fine.

**Comment by skitt** [comment]
> Whether or not is vbox currently
> compatible with kvm, I dont know.
> Maybe someone else does.

It’s not (the same goes for VMware). See the big red “Warning” in [the VirtualBox manual](https://www.virtualbox.org/manual/ch10.html#hwvirt).

**Comment by stsp** [comment]
OK, thanks.
Let me speculate that this does not contribute
well to their user base growth.

**Comment by RossBoylan** [comment]
>From: Stas Sergeev <notifications@github.com>
> Let me speculate that this does not contribute
> well to their user base growth.

To the extent that's true, I'd expect it's even more an issue for dosemu2 than the others, given the number of users.  Which was one of my reasons for bringing it up.

qemu and virtualbox, like dosemu2, can fall back to software emulation (or at least, non-hardware assisted virtualization; the VirtualBox manual makes much of the way they handle this situation cleverly).  So they are all in the same boat: running one leads to suboptimal performance for the others.  I'm not sure about VMWare.  I think Xen is in a slightly different (bare-metal) game.  The meaning of "sub-optimal" could range from barely noticeable to intolerable.  I can also imagine that virtual machines might appear somewhat different to themselves if run under software vs hardware virtualization, and that might throw things off (e.g., licensing schemes, device names, validity of suspended images).

This is all assuming that if software A1 with kernel virtualization module A2 loaded is running, and someone starts software B1 requiring kernel virtualization module B2, the result is not to unload A2, crashing A1, and insert B2.  That would be much worse.  In my limited experience that doesn't happen, and previous comments in this thread also indicate it won't happen.  But I don't know it's for sure, and it may depend on how aggressively the applications are written.

Ross

**Comment by RossBoylan** [comment]
I am trying to draw your attention to what the experience will be like for users, not get into a debate over which software is "responsible" for the problem.  I believe there are many more people running VirtualBox than dosemu.  If one of those people decides to try dosemu2 and finds that it is running slowly, or if they happen to start dosemu first and find their VMs are running slowly, they will not be happy and will ditch dosemu2.

Every program that uses virtualization tends to assume that it is the only one that will be doing so.  It's a reasonable assumption, but not always correct.  And since dosemu is more like an application to run individual programs than a host for VMs, the assumption of exclusivity seems weakest for it.

Barring some complex and risky bit of programming, like getting dosemu2 to work with different kernel virtualization modules (I'm not advocating it), I think the best way to deal with these issues is to document them.  There might be an argument for defaulting to software-only emulation, since it minimizes the risks of interference.

Ross

**Comment by stuaxo** [comment]
I'm always hitting this between different virtualisation solutions - it's been a bit better since I moved to Gnome boxes (qemu/kvm), but before I'd have a situation where I would try and mostly use virtualbox, but then there would be one thing that kept me using VMWare (Windows audio working better for Ableton, or an OSX installation).

Now I mostly use kvm/qemu, but occasionally I end up using virtualbox.

As for DOSEMU2, I use that occasionally, but mostly for fun.

**Comment by stsp** [comment]
> I believe there are many more people running VirtualBox than dosemu.

And yet many many more running qemu than vbox.

> Every program that uses virtualization tends to assume that it is the only one that will be doing so.

No, this is only the assumption of the programs
that use incompatible modules. Not a problem
with qemu. As for vmware - I really do not expect
anyone wants to run it and dosemu2 on the same
host.

> I think the best way to deal with these issues is to document them.

Documenting something needs to do the proper
testing first. If you can do all the tests with running
the different VM combinations, please send a doc
patch or describe your findings here. Docs can't be
written based on an assumptions, even if they are
based on looking into the vbox manuals, dosemu2
code etc.
Plus I really don't think there is something to care
much. vbox is too minor compared to qemu (IMHO),
and vmware is too specific for anyone to run dosemu2
on the same host. I may be wrong on this of course.

**Comment by stsp** [comment]
> Now I mostly use kvm/qemu, but occasionally I end up using virtualbox.

Indeed.
This is what I assume to be the quite generic
scenario.

**Comment by stuaxo** [comment]
virtualbox used to be the default when running vagrant for webdevelopment tasks.

I'd assume that most people have moved off vagrant onto docker (which has different backends - originally virtualbox was a default, but I think lxc might be the default now).

**Comment by stsp** [comment]
> Now I mostly use kvm/qemu, but occasionally I end up using virtualbox.

Even for DOS games?

**Comment by RossBoylan** [comment]
________________________________________

**Comment by stsp** [comment]
No, this is wrong. As I said already,
there should be no "first started"
condition. Modules do not replace
each other when their app starts.
Also we don't know how dosemu2
reacts on a missing kvm module.
We only know how it should react,
and we extrapolate that the effect
will be the same as disable kvm in
the config. But this should be tested
(quite simple to, fortunately).

**Comment by stsp** [comment]
So if you are confident there is a "first wins"
situation and I am sure in an opposite, isn't
there a need for a test?
There is, if you ask me.
The doc can't be written based on a controversial
assumptions.

**Comment by RossBoylan** [comment]
Come on.  You said, and I agree, that only one kernel virtualization module at a time can be active and that such modules can't be unloaded when in use.  So what, exactly, is the disagreement?

Is there any way around the implication that the first program to activate a kernel virtualization module will succeed, and that later ones using different kernel modules will find they can't load them, and must therefore either rely on software emulation or just not run?

As for how dosemu2 reacts if the kernel module it wants to use is missing or unloadable, I thought it just fell back to software only mode, which you have said it supports.  If the behavior in those cases is uncertain, I agree that it should be tested, because it's information about this program, not some third party program.  If we weren't just talking about documentation, I might even suggest that if dosemu2 doesn't fall back to software emulation automatically, it would be good to change it so that it does :)

Ross

________________________________________

**Comment by stsp** [comment]
> So what, exactly, is the disagreement?

That there is a "first wins" situation.

> and that later ones using different kernel modules will find they can't load them

They don't load anything, as that operation would
require root privs.

> it would be good to change it so that it does :)

Indeed. Maybe it already does. But nobody tested.

**Comment by RossBoylan** [comment]
OK.  Here are the statements that lead me to conclude first wins, in at least the sense of getting hardware assisted virtualization:
1. Only one hardware virtualization module can be loaded at the same time in linux.
2. Different programs may want different hardware virtualization modules.
3. Two programs can not run simultaneously using two different virtualization modules.
4. If the programs can fall back to operating without hardware virtualization, they will run.  Otherwise they will likely fail or have limited functionality.
5. Since the first program to run has no competition, it will succeed in loading the kernel module it needs (assuming availability).
6. Later programs will be unable to load conflicting kernel virtualization modules.
7. Running without hardware virtualization is generally slower.

Addendum, inessential to the main point:
8. Behavior while running without hardware virtualization may  differ from that with virtualization in ways other than speed (CPU, hardware types, MAC addresses inside the VM come to mind), if only because it's a different code path (this applies equally to doesmu2 and other virtualization hosts).

So, are any of the preceding statements incorrect?
Are you saying you disagree with 5, which also knocks out 6?  I thought the kernel autoloaded modules even if one was not root, and at any rate one can run virtualization programs as root.
If, for example, the loaded hardware virtualization is determined by boot time configuration/blacklisting, then it's true the order of running the programs wouldn't matter.  And if the virtualization module were built into the kernel (not sure if anyone does that, but I suppose they could), then there's no choice at all.  But the conflict of point 3 would remain, or even be intensified since programs using disfavored kernel modules wouldn't be able to use them even if they were the only active virtualization consumers.

Also, all of my comments concern Linux, and really only Intel/AMD architectures; I'm not sure what range of systems dosemu2 is targetting, or what the story would be with others.

The above analysis is insufficient to imply either that 2 programs using the same kernel virtualization module can or can't run at the same time, whether they be multiple instances of the same program (I usually have 2 dosemu's running at once for two different applications) or different programs (dosemu2 + qemu-kvm).  However, I think you have said that multiple instances using one kernel module should be fine, at least for the kvm kernel module.   Strictly, it was just a statement that one instance of dosemu2 and one of qemu-kvm could run together.

Ugh: This also doesn't address the question of what happens if you run dosemu2 inside some other virtualization software, as I somewhat unwittingly did awhile ago.

________________________________________

**Comment by skitt** [comment]
> OK. Here are the statements that lead me to conclude first wins, in at least the sense of getting hardware assisted virtualization:
> 1. Only one hardware virtualization module can be loaded at the same time in linux.

    $ lsmod | grep -E 'kvm|vbox'
    vboxdrv               483328  0
    kvm_intel             200704  0
    kvm                   598016  1 kvm_intel
    irqbypass              16384  1 kvm

> 2. Different programs may want different hardware virtualization modules.

Yes. But as can be seen above, the modules can be loaded simultaneously.

> 3. Two programs can not run simultaneously using two different virtualization modules.

That needs to be tested.

> 4. If the programs can fall back to operating without hardware virtualization, they will run. Otherwise they will likely fail or have limited functionality.

Same here. With the same virtualisation tool, some VMs will run, others won’t, depending on their settings.

> 5. Since the first program to run has no competition, it will succeed in loading the kernel module it needs (assuming availability).

No, programs don’t load kernel modules.

> 6. Later programs will be unable to load conflicting kernel virtualization modules.

See points 1 and 5.

> 7. Running without hardware virtualization is generally slower.

> Addendum, inessential to the main point:
> 8. Behavior while running without hardware virtualization may differ from that with virtualization in ways other than speed (CPU, hardware types, MAC addresses inside the VM come to mind), if only because it's a different code path (this applies equally to doesmu2 and other virtualization hosts).

For some features yes, although in many cases it won’t have any effect on the VM. MAC addresses in particular shouldn’t change.

**Comment by stsp** [comment]
> Yes. But as can be seen above, the modules can be loaded simultaneously.

Does this mean a "first wins" situation indeed?
And if so, is it enough to just shut down vbox to
keep using qemu, and vice versa?
Is simultaneous load a default setup?

**Comment by jschwartzenberg** [comment]
The situation described here will affect every hypervisor that does not use `/dev/kvm` on Linux hosts. The real solution will be when such hypervisors, including VirtualBox, switch to using `/dev/kvm`. On a Windows host, I think VirtualBox already has support for using the OS provided virtualization API.

**Comment by RossBoylan** [comment]
From the [KVM FAQ](https://www.linux-kvm.org/page/FAQ#I_have_VMware.2FParallels.2FVirtualBox_installed_and_when_I_modprobe_KVM.2C_my_system_deadlocks).

> Neither Intel VT nor AMD-V provide a mechanism to determine whether software is currently using the hardware virtualization extensions. This means that if you have two kernel modules loaded attempting to use hardware virtualization extensions, very bad things will happen. If you are using another type of virtualization software and experience any sort of weirdness with KVM, make sure you can reproduce the problem without the kernel modules for that software loaded before you report a bug in KVM. 

Also, it sounds as if it's not so much a "first wins" as "everybody loses" if multiple modules are in use.

So the status of my original list of statements is

1. ~~Only one hardware virtualization module can be loaded at the same time in linux.~~ [False.]
1b. Using more than one hardware virtualization module at once is unsafe. [New]
2. Different programs may want different hardware virtualization modules. 
3. ~~Two programs can not run simultaneously using two different virtualization modules.~~ [Not quite true. False if "run" means "launch"; True if "run" means "run reliably."]
3b. Two programs using different kernel virtualization modules should not be run simultaneously *if both are using their respective kernel drivers*. [New. Carefully avoiding the statement the programs can't be run at all, given that many can work w/o h/w virtualization.]
 4. ~~If the programs can fall back to operating without hardware virtualization, they will run. Otherwise they will likely fail or have limited functionality.~~ [irrelevant.  The putative fallback was to be triggered by a failure to load the appropriate virtualization module.  I'm still a little skeptical of the statement that programs can't trigger such a load--if true, there's no load event, and so no load event failure--but it doesn't matter.  Even if the programs can load kernel modules (surely with root privileges they could), the kernel permits loading conflicting modules and so would have no failure to trigger a fallback.]
5. ~~Since the first program to run has no competition, it will succeed in loading the kernel module it needs (assuming availability).~~ [order apparently irrelevant]
6. ~~Later programs will be unable to load conflicting kernel virtualization modules.~~ [same]
7. Running without hardware virtualization is generally slower. 

Addendum, inessential to the main point: 

8. Behavior while running without hardware virtualization may differ from that with virtualization in ways other than speed (CPU, hardware types, MAC addresses inside the VM come to mind), if only because it's a different code path (this applies equally to doesmu2 and other virtualization hosts). [Virtualization providers should have control over MAC addresses].

A lot of corrections, but many of them involve a change from you *can't* do something to you *shouldn't* do something.

**Comment by stsp** [comment]
This is why such things need testing.
We can write down something very generic,
like "running dosemu2 with vbox is not recommended"
to stay on a safe side, but, firstly, its quite obvious from
the kvm faq you quoted, and second, this may change.
I.e. I see no problems why kvm and vboxdrv can just
add some code to refuse to load simultaneously with
each other. Documenting this bizarre finding that they
actually can, doesn't look very productive. And if they
change this way, suddenly you can run dosemu2 with
vbox, it will just be slower. And rewrite the doc.
But please send something very brief and neutral as a
PR if you want.

**Comment by RossBoylan** [comment]
Take 2:

COMPATIBILITY
If you use dosemu2 with other virtualization solutions, such as qemu-kvm, VirtualBox, Xen or VMWare you should be aware all of them are likely to try to use hardware virtualization if it is available.  Such virtualization depends on kernel drivers, and different solutions may use different drivers; dosemu2 uses kvm.  Currently, using more than one such driver at the same time is not safe, and you should avoid doing so.

The safest course is not to install more than one such kernel driver.  Alternately, blacklist all but one on startup.  Another approach would be to configure virtualization programs that use the non-preferred kernel module to use software virtualization only.  dosemu2 has such an option; others may or may not.

Most  virtualization programs, like dosemu2, can operate without hardware virtualization.  Doing so is likely to make them slower, and may cause other changes as well.



[Make positive statement about running multiple copies of doesmu2 with h/w virtualization? running doesmu2 & qemu-kvm, both with h/w virtualization?]

[Deliberately omitted question of whether serial loading would be OK, though I'd guess it is.  That is, run app A1 with kernel module A2; stop A1; unload A2 and insert B2; run B1 that uses kernel module B2.]

[Would be good to say something about running dosemu2 inside another hypervisor, but I don't know what it is.  It seemed I got away with it inside VirtualBox.]

**Comment by jschwartzenberg** [comment]
Note that as long as I remember, VirtualBox displays an error when it detects the KVM modules are loaded.

**Comment by stsp** [comment]
> dosemu2 uses kvm

... on 64bit.
On 32bit it uses vm86.

> Note that as long as I remember, VirtualBox displays an error

And keeps working in sw mode?

**Comment by stsp** [comment]
> Alternately, blacklist all but one on startup. Another approach would be to configure virtualization
> programs that use the non-preferred kernel module to use software virtualization only. dosemu2
> has such an option; others may or may not.

Such statements are very poor for the documentation.
You either need to tell the user exactly what to do
(with examples and all that), or keep silence.
"blacklist on startup"?
"non preferred kernel  modules"?
"configure to use software virtualization only"?
Nobody is going to understand that, unless there
are explicit recipes and examples.

**Comment by jschwartzenberg** [comment]
> And keeps working in sw mode?

VirtualBox has a non-hypervisor mode, but it still needs its kernel module. Here is a screenshot of the error dialog that VirtualBox shows when KVM is loaded:
https://www.dedoimedo.com/computers/kvm-virtualbox.html

It seems the VirtualBox developers were really against the idea of supporting KVM 7 years ago:
https://forums.virtualbox.org/viewtopic.php?f=9&t=47825

A lot has changed since then though. Back then, Linux developers also refused to look at issues when the VirtualBox kernel modules were loaded. They were out-of-tree and known to be buggy. On Windows the same problem appeared and VirtualBox supports the Hyper-V API there now:
https://forums.virtualbox.org/viewtopic.php?f=6&t=90853

VirtualBox uses a status bar icon to indicate what mode is used. Having something similar in DOSEMU2 would be nice. Two ideas:
1. Have a variable that can be used for the title bar showing whether KVM/VM86/etc. is used (DOSBox also uses the titlebar for emulation info.)
2. Have an environment variable with this information. This variable could then be queried/echo-ed at start-up from `autoexec.bat`. (It's already possible to do this with the configuration variables, but they do not reflect the actual situation when DOSEMU2 is falling back to another mode.)

**Comment by stsp** [comment]
> VirtualBox has a non-hypervisor mode, but it still needs its kernel module.

Thanks for the info.
This just shows how naive is to try to document
the things like this, w/o doing the proper testing first.

> A lot has changed since then though.

What?

> Having something similar in DOSEMU2 would be nice.

I don't see a big reason.
cpuemu mode these days is just a fall-back.
It is rarely activated in the config (mainly for testing),
and we have never even tested the automatic fall-back
when the kvm module is missing.
So does this really deserve a bar icon?

**Comment by stsp** [comment]
> I'm still a little skeptical of the statement that programs can't trigger such a load--if true,
> there's no load event

I am not an expert in that, but AFAIK the apps could
trigger the load events in devfs times.
Currently there is an entirely different model, in which
the load event is triggered by the device hot-plug, not
by the programs. If the device does not support hot-plug,
it goes to the "platform devices" and gets loaded on boot.
For some (unknown to me) reasons the kvm drivers are
not a platform device, and seems to be hardcoded into
the udev rules. Maybe someone knowledgeable in this
are can explain why it is so.

**Comment by jschwartzenberg** [comment]
> So does this really deserve a bar icon?

There's no bar in DOSEMU2 or you mean something else?

My proposal would be having something like:
1. `$_X_title_show_appname` but instead `$_X_title_show_cpu_vm`
And/or
2. Set an environment variable so that a user can add something to `autoexec.bat`.

By default it won't be shown, but when someone likes to be aware, they could add this info to the titlebar or let their `autoexec.bat` echo it at start-up.

**Comment by jschwartzenberg** [comment]
> > I'm still a little skeptical of the statement that programs can't trigger such a load--if true,
> > there's no load event
> 
> I am not an expert in that, but AFAIK the apps could
> trigger the load events in devfs times.

There is no such thing as auto-loading of kernel modules. VirtualBox uses an init script to load its kernel modules. If the modules are not loaded, VirtualBox displays a dialog with instructions how to run this init script as root so that the modules are loaded.

**Comment by stuaxo** [comment]
The blacklisting sounded a bit extreme, I've never had to reboot switching between say virtualbox and vmware.   Possibly do some things that are a bit of a pain, e.g. unload some modules:

https://www.dedoimedo.com/computers/kvm-virtualbox.html

**Comment by stsp** [comment]
> There is no such thing as auto-loading of kernel modules.

There is (but not for kvm, as I already mentioned).

**Comment by stsp** [comment]
> Possibly do some things that are a bit of a pain, e.g. unload some modules:

I wouldn't even bother: dosemu works sufficiently
well and reliable under cpu emulation. Most people
won't even notice that it switched to sw mode.
Playing with modules is OTOH not fun.

**Comment by jharrison03** [comment]
I don't see any problem running multiple instances of programs which use KVM.  I run multiple Dosemu's and QEMUs, for instance:

```
kvm_intel             253952  6 
kvm                   495616  1 kvm_intel
irqbypass              16384  1 kvm
```

That kvm_intel module increments by two for each instance of a program using KVM,.

**Comment by stuaxo** [comment]
It would be good to have a small note in the docs.

I only run DOSEMU as a hobbyist and it works well enough that I've never noticed I was using cpu emulation at the same time as I used virtualbox (or maybe I just only use virtualbox for dev/work tasks and dosemu at other times).

**Comment by jschwartzenberg** [comment]
> By default it won't be shown, but when someone likes to be aware, they could add this info to the titlebar or let their `autoexec.bat` echo it at start-up.

This is actually supported already. With the current version of DOSEMU2, add the following lines to `userhook.bat`:
```
unix find /proc/`cut "-d ' '" -f 4 /proc/$$/stat`/fd -lname '/dev/kvm' -exec false {} +
if not errorlevel 0 xmode -title "DOSEMU2 (KVM)"
```

When DOSEMU2 is using KVM, the titlebar will show this.
