### ISSUE TITLE
Can't find command.com with reduced memory size

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#827]
**Describe the bug**
If $_dosmem is set to 600 instead of default 640 (Done for testing PR #826) FreeDOS 1.2 fails to find command.com

**To Reproduce**
- Use FreeDOS 1.20
- Set `$_dosmem = (600)` in dosemu.conf
- See the message
~~~
dosemu2 2.0pre8-20190519-1051-g86ae4c406
Configured: 2019-05-20 02:00:38 +0100
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
 
FreeDOS kernel 2042 (build 2042 OEM:0xfd) [compiled May 11 2016]
Kernel compatibility 7.10 - WATCOMC - FAT32 support
 
(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=   112 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
EMUFS host file and print access available
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
Kernel: allocated 45 Diskbuffers = 23940 Bytes in HMA
Bad or missing Command Interpreter: command.com /e:1024 /k autoexec.bat
 Enter the full shell command line:     
~~~

- Try `mcbs` command (maybe chain is corrupt due to failure to finish boot?)
~~~
dosdebug> mcbs
dosdebug> 
ADDR      PARAS  OWNER
02a3:0000 0x0016 [DOS]
02ba:0000 END

ADDR(UMA) PARAS  OWNER
95ff:0000 0x3700 [DOS]
MCB chain corrupt - missing final entry in UMA
~~~

**Attach the log**
[dosmem.zip](https://github.com/stsp/dosemu2/files/3197113/dosmem.zip)

**Comment by andrewbird** [comment]
Note if I comment out both umb.sys and ems.sys boot succeeds.
~~~
rem config.sys for DOSEMU + FreeDOS                                             
SWITCHES=/F                                                                     
DOS=UMB,HIGH                                                                    
dosdata=umb                                                                     
lastdrive=Z                                                                     
files=40                                                                        
stacks=0                                                                        
buffers=10                                                                      
device=dosemu\emufs.sys                                                         
rem device=dosemu\umb.sys                                                       
rem devicehigh=dosemu\ems.sys                                                   
shellhigh=command.com /e:1024 /k autoexec.bat                                   
~~~
~~~
dosdebug> mcbs
dosdebug> 
ADDR      PARAS  OWNER
02a3:0000 0x026c [DOS]
0510:0000 0x0a23 [DOS]
0f34:0000 0x0006 [FREE]
0f3b:0000 0x12c1 [COMMAND]
21fd:0000 0x6d16 [FREE]
8f14:0000 0x0619 [COMMAND]
952e:0000 0x0090 [COMMAND]
95bf:0000 END
dosdebug> 
~~~

**Comment by stsp** [comment]
> Edit: just noticed I was using FreeDOS not FDPP, so it must be a Dosemu bug.

Grr, Andrew, don't drive me mad. :)

**Comment by andrewbird** [comment]
Yep, I shouldn't test things at 2:30 am, but it's still a bug, right? Maybe it's a umb thing?

**Comment by stsp** [comment]
Maybe, but this is not a freedos bugzilla.
And I would be surprised to see it on freedos
bugzilla, too, as you won't test freedos (w/o dosemu)
with 600Kb of conv mem.

**Comment by andrewbird** [comment]
Okay it's not something I'm likely to do again anyway, so I'll just forget it. Sorry for the noise!

**Comment by stsp** [comment]
My suggestion is to forget freedos entirely and
only test it when some bug is triggered in fdpp.
Ideally there should be no fdpp bugs that are not
freedos bugs at the same time. (we are not quite
there yet)
Its like dosemu1: we test it only when we want to
find out if a particular bug is a regression. If we
consider fdpp a freedos2, then why do we test
freedos1...
Your problems with fdpp drives are already solved,
btw. I think even @bolle732 have switched to the
new config options (which is what he certainly did,
as I removed the compatibility options anyway :)
If there are still the problems to run your test-suit
with fdpp, please let me know.

**Comment by andrewbird** [comment]
This will make you happy. I reran the test using FDPP / 600 kB main memory and things look good.
~~~
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
 
FDPP kernel 0.1beta5 [GIT: beta-5-47-g36ef7a4] (compiled May 20 2019)
Kernel compatibility 7.10 - GNUC - 80386 CPU required - FAT32 support
 
Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.
 
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
 
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=   112 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
EMUFS host file and print access available
Kernel: allocated 117 Diskbuffers = 62712 Bytes in HMA
Process 0 starting: C:\command.com /e:1024 /k %FDPP_AUTOEXEC% 
~~~

~~~
dosdebug> mcbs
dosdebug> 
ADDR      PARAS  OWNER
0290:0000 0x000d [DOS]
029e:0000 END

ADDR(UMA) PARAS  OWNER
95ff:0000 0x0000 [DOS]
9600:0000 0x0040 [50455]
9641:0000 0x09bd [FREE]
9fff:0000 0x2300 [DOS]
c300:0000 0x0215 [DOS]
c516:0000 0x12c1 [COMMAND]
d7d8:0000 0x0826 [FREE]
dfff:0000 0x1000 [DOS]
f000:0000 0x0554 [FREE]
f555:0000 0x0619 [COMMAND]
fb6f:0000 END(UMA)
~~~

**Comment by andrewbird** [comment]
Do you think the first MCB in UMA is a little odd, why have zero length allocation?

**Comment by stsp** [comment]
If you don't put the intermediate MCB into the
last para of conv mem, then you can't have the
single linked chain after you change the last MCB
from 'Z' to 'M' when lining in UMB chain.
It usually is not "empty", because it sits in 0x9fff0
and points into 0xb000 or where the UMB really starts.
But in your case UMB starts immediately after UMA
(very unusual case), so you get the "empty" link MCB.

**Comment by andrewbird** [comment]
Thanks, that makes sense now.

**Comment by stsp** [comment]
It does more now: I applied the patch that displays
them properly.

**Comment by stsp** [comment]
By the way, I find it a bit funny that dosemu
does not allow you to waste any memory space.
If you reduce conv memory, it just puts an UMBs
into a freed space. This code is quite old, I am not
sure who wrote it that way. But I think be it me, I'd
only consider addresses >= a0000 for UMBs.
But not sure if it worth changing now. Its just a
funny effect of reducing conv mem.

**Comment by andrewbird** [comment]
Should probably print the size of END mcbs too.

**Comment by stsp** [comment]
Done.
But this code really needs some clean-ups and
de-duplications.
