### ISSUE TITLE
API call for Unicode fonts

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#832]
Please implement an API call to access Unicode fonts.  We're running under X, so we're not limited to a ROM-based character-set with with a single byte index.

**Comment by stsp** [comment]
Please, dosemu2 is not an SDK.
It emulates VGA, and in VGA text mode there
is no room for unicode chars. It can neither
store them, nor display.
You can write the program that displays unicode
chars in gfx mode. You can likely even download
one.
There is absolutely nothing that dosemu2 can
do for you.

**Comment by stsp** [comment]
And X doesn't matter too, as dosemu2 renders
the DOS font from rom. It uses an X font only if
you specify the custom font. But if you make some
silly API to directly print an arbitrary X char, then
it will not participate in the bios scrolling etc.

**Comment by jharrison03** [comment]
The MS mouse service didn't support a wheel either, but DOSemu can support this though extended API calls.  

Obviously, you're not going to access Unicode fonts in the same manner as character fonts.  This would be supported through calls such as "print character X", "printer charater X at postion X, Y", and a call to access a pointer to the actual font data itself.  It would need DOSemu to leverage something like Freetype also.

**Comment by stsp** [comment]
This is not possible.
Please, try to understand that simple fact.
You can render anything on the dosemu window.
But it won't participate in the text scrolling, won't
be erased when video mode changes, etc. It won't
be controllable from the DOS side at all. Its like
drawing the GUI above main dosemu window.

**Comment by stsp** [comment]
You can just add the window overlay on top of
dosemu, and draw anything you like on it. You
can communicate with the DOS prog via the
emulated serial port, and render on linux side
what it asks for.
