### ISSUE TITLE
Dosemu runs slower after a reboot from within Dosemu

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#834]
Dosemu runs slower after a reboot from within Dosemu.  The following is observed in the console on the second and subsequent reboots from within Dosemu.  The DOS is MS-DOS 6.22 with a minimal CONFIG.SYS and AUTOEXEC.BAT.

```
ERROR: touched jit-protected page
ERROR: touched jit-protected page
ERROR: touched jit-protected page
ERROR: touched jit-protected page
```

It appears EMS.SYS may be exposing this error when it is loaded.

[boot.log.zip](https://github.com/stsp/dosemu2/files/3254696/boot.log.zip)
[dosemurc.zip](https://github.com/stsp/dosemu2/files/3254698/dosemurc.zip)
[c.zip](https://github.com/stsp/dosemu2/files/3254699/c.zip)

**Comment by jharrison03** [comment]
This is where the boot process hangs -- it eventually gets past this after ~10 seconds but then the rest of the session runs very slow:

![hang](https://user-images.githubusercontent.com/44394516/59014271-39a9f180-880a-11e9-8ecb-dd3d102b3e7c.jpeg)

**Comment by jharrison03** [comment]
This might help --

https://www.youtube.com/watch?v=HZqmcT2SECk

**Comment by stsp** [comment]
Should probably now be fixed.
Please check.

**Comment by jharrison03** [comment]
This is fixed now.  Thank you.
