### ISSUE TITLE
UI font issues with Sierra AGI titles

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#835]
Sierra AGI games display most characters as cedillas in the user interface.  This is observed in the AGI versions (non-booter) of King's Quest I and The Black Cauldron.  This worked in previous versions of Dosemu, maybe as of a year ago.

![kq1](https://user-images.githubusercontent.com/44394516/59007500-a1554200-87f4-11e9-90d3-649eb30f53ae.jpeg)
![bc](https://user-images.githubusercontent.com/44394516/59007502-a5815f80-87f4-11e9-8b4c-acc0597b8c61.jpeg)

These two versions have been patched with the AGIMIDI utility, so they assume Roland-style hardware to render the Tandy 3-voice sounds through MIDI hardware (not germane to the bug, but required to start the games).

[kq1.zip](https://github.com/stsp/dosemu2/files/3260041/kq1.zip)
[bc.zip](https://github.com/stsp/dosemu2/files/3260042/bc.zip)

**Comment by jharrison03** [comment]
The UI elements that are highlighted display correctly, as in the "File" menu in the first screenshot.

**Comment by stsp** [comment]
Interesting.
Dont you use the custom X font by
chance? I suspect it doesnt matter
in gfx mode, but worth a check.

**Comment by jharrison03** [comment]
If you mean a custom X font specified in dosemurc, no, I don't use that.

**Comment by stsp** [comment]
The regression is as old as 1.4.0.8.
Bisect shows to 87b84c7c, which means the
new vgabios makes problems. Could you please
test this game on qemu?

**Comment by jharrison03** [comment]
It's working now under Dosemu, and works under QEMU.
