### ISSUE TITLE
Backspace is producing backslash

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#839]
**Describe the bug**
As of a78fac7fb after pressing backspace and backslash at the same time, backspace produces "\\" backslash until dosemu is closed.

**To Reproduce**
Mash backspace and "\\" backslash at the same time. After about 5 tries the backspace key will produce backslashes. Once broken, mash backspace with any other key and after about 5 tries backspace will change to that key.

**Comment by jschwartzenberg** [comment]
It seems backspace also stopped working with `dosemu -t`.

**Comment by stsp** [comment]
> until dosemu is closed.

Thanks, you've found a quite difficult-to-trigger race.
I think it is now fixed.

> It seems backspace also stopped working with dosemu -t.

Can't reproduce.
Please open another ticket.
For me backspace doesn't seem to work in `dosemu -td` mode,
but I don't think it ever did.

**Comment by andrewbird** [comment]
Is it even possible for backspace to work in dumb terminal, it's certainly not something I expect to work?

**Comment by stsp** [comment]
Why not?
It now works.
dumb terminal is an output property, so
we'll have troubles displaying backspace
(erasing chars). But it can still be handled
properly on an input level.

**Comment by stsp** [comment]
Of course the benefits of this are questionable,
as you'll see the chars that are no longer there...

**Comment by andrewbird** [comment]
Ahh okay. So it works as far as the app is concerned, it just doesn't look like it does to the user.

**Comment by stsp** [comment]
With the patch I've committed now - yes.
I wonder if there are no more regressions
on an sdl front though. The changes I did
look so nasty, that I guess one more
regression and I'll revert back to the
dosemu keymaps...
