### ISSUE TITLE
Why does unix ls -d ~ show Chdir failed, while ls ~ works?

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#841]
I have DOSEMU2 installed with FD++ & comcom32. While `unix ls ~` works fine, `unix ls -d ~` gives me:
```
C:\>unix ls -d ~
Chdir failed
```

I'm not really sure what is going on. In a plain terminal `ls -d ~` works fine:
```
julius@wijsvinger:~$ ls -d ~
/home/julius
```

**Comment by stsp** [comment]
Should now be fixed.

**Comment by jschwartzenberg** [comment]
Confirming it's fixed!
