### ISSUE TITLE
Alt-keys doesn't work

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#842]
**Describe the bug**
It's been a while I do not use dosemu. Today I found that alt combination key doesn't work. I update dosemu from the PPA. 

**To Reproduce**
Run edit.exe, normally we can exit from the editor by pressing alt-x. However, this time pressing alt-x does not exit the editor but put a "x" in the editor screen.

**Comment by stsp** [comment]
You are not attaching the log.
Namely, I think this is already fixed.

**Comment by bpranoto** [comment]
Yes you're right.
I refresh my source and rebuild. Now it works fine again.
Thanks.
