### ISSUE TITLE
CTRL-(key) treated as unmodified character

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#843]
This should be pretty self-explanatory --  CTRL-(key) combinations are treated as the unmodified character - ie. CTRL-C, is treated as pressing the "c" key on the keyboard, which makes sending a "break" in this fashion impossible.

[boot.log.zip](https://github.com/stsp/dosemu2/files/3275017/boot.log.zip)

**Comment by jharrison03** [comment]
EDIT: I'm aware of #842, but this still happens after a subsequent pull.

**Comment by jharrison03** [comment]
I don't want to open another issue for this, but, probably related --

At a DOS prompt, using ALT-(number pad digit) to input a character not normally accessible from the keyboard causes the use of Backspace to position the cursor over the previous character, rather than deleting the previous character.

Example:  Alt + 2, 5, 4 (on the number pad) writes a character that resembles a solid rectangle.  Pressing Backspace after the Alt-sequence moves the cursor once space to the left, and positions the cursor beneath the rectangle character.  The expected behavior is that the rectangle character is deleted, and the cursor is moved one space to the left.

**Comment by stsp** [comment]
The first problem you describe, happens only
in X, not in SDL. I wonder if it is a regression,
as I didn't touch the X kbd code.
The second problem I can't reproduce.
Backspace erases the solid rectangle.

**Comment by jharrison03** [comment]
I have a Debian 8 install, so I'll have to build with a newer SDL2 and I'll try it again.

Dosemu supports X, SDL1 and SDL2.  It's confusing to try to explain the behavior in this bug report across X and SDL1.

It's neat that Dosemu supports all these APIs, but maybe it's time something can go?

**Comment by stsp** [comment]
SDL1 is unrelated as it is only used under
KMS/fb console. You can't force its use under X.
Maybe an X back-end can go if/when Andrew
finishes his SDL plugin rework, lets see.
Anyway, when this worked as expected?
As I didn't touch an X code recently, I don't think
it could regress.

**Comment by stsp** [comment]
Try `$_X_keycode = (off)`

**Comment by stsp** [comment]
Regression.

**Comment by stsp** [comment]
Should now be fixed.
This xkb is poorly documented, and is very
very difficult to even find its sources (try to
google for sources of `XkbLookupKeySym()`
or for the numeric values of modifiers).
I spent countless hours trying to understand the
problem from the vague docs, but after spending
a few hours on finding the sources, the problem
became obvious. Which is that X KeySym does
not represent all modifiers, so it can't be translated
to unicode without an extra step of  translating it
to the locale charset first.

**Comment by stsp** [comment]
So in the past the scheme was:
`$_X_keycode = (off)`:
X_keycode->[xkb]->X_keysym->[unicode_cnv]->t_keysym->[put_modified_symbol()]->t_keynum->[dosemu table]->unicode

`$_X_keycode = (on)`:
X_keycode->[table]->t_keynum->[move_keynum()]->[dosemu table]->unicode

I changed `$_X_keycode = (on)` case to 2-way converter:
X_keycode->[xkb]->X_keysym->[xkb]->utf8->[unicode_cnv]->unicode->update_dosemu_table--\
X_keycode->[table]->t_keynum->[move_keynum()]->[updated dosemu table]<---------------------/
                                                                                                                       \---->unicode

Just documenting things, as I can barely remember that stuff.
So `$_X_keycode = (off)` trusts the keysym modulo its modifiers.
`$_X_keycode = (on)` almost didn't trust the keysym, only evaluating
the layout group from it. It trusted the dosemu layout table.
Now suddenly `$_X_keycode = (on)` gets reversed: it now fully
trusts the keysym, requiring it to represent all its modifiers, hence
this bug report. dosemu tables are not trusted at all (updated at runtime).

I wonder if, at the end, we need just one mode, so remove `$_X_keycode = (off)`?
Or maybe we need 3 different modes, so re-add old `$_X_keycode = (on)` mode?
In SDL we can only have the third mode, or we can't get I18N,
as keysyms in SDL do not seem to respect the current kbd layout
and no API to get the current layout.
And even third mode in SDL can only be implemented with lots of
hacks, while with xkb it looks much nicer.
