### ISSUE TITLE
deleting current drive leads to bad things

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#844]
```
G:\>lredir -d g:
Redirection for drive G: was deleted.
 
2╔☺>
```
Deletion of current drive should be forbidden.
Andrew? :)

**Comment by andrewbird** [comment]
okay

**Comment by andrewbird** [comment]
Strangely not so bad here
~~~
C:\>lredir g: /tmp
G: = \\LINUX\FS/TMP attrib = READ/WRITE
C:\>g:
G:\>lredir -d g:
Redirection for drive G: was deleted.
G:\>dir
File not found. - '.'
G:\>
~~~

anyway I've put a check into lredir

trying to delete the default drive
~~~
C:\>lredir g: /tmp
G: = \\LINUX\FS/TMP attrib = READ/WRITE
C:\>g:
G:\>lredir -d g:
Error G: is the default drive, aborting
G:\>
~~~

and the normal case
~~~
C:\>lredir -d f:
Redirection for drive F: was deleted.
C:\>
~~~

**Comment by stsp** [comment]
> Strangely not so bad here

What command.com?

**Comment by andrewbird** [comment]
FreeCOM

**Comment by andrewbird** [comment]
Actually I think there is a valid use case for `lredir $current_drive`, when the current drive is MFS that's been loaded over an underlying FATFS that the user wants to expose. I think this can be done by shifting the current drive logic up into the redirector and returning an appropriate error in that case. What do you think, too much trouble as there's a workaround except in case that there's only one drive?

**Comment by stsp** [comment]
I would't be against such solution if
you think its needed. After all, you can
create or change the redirection of
the current drive, so why not to delete
also.
