### ISSUE TITLE
national fonts in VGA

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#845]
Currently the national VGA fonts must be
loaded with display.sys/mode.com.
Unfortunately there is no such thing in fdpp
and I haven't tried if the ones from freedos
work on fdpp.
The following should be done:
1. Check if the freedos's l10n tools work
2. Implement internal CPI support that will load
the needed font, based on the `$_internal_charset`

As we are currently on fdpp, 2 should probably better
be implemented on fdpp side. But it seems the DOS
cp switch is a complex operation:
http://wiki.freedos.org/wiki/index.php/NLS
So as a start, we probably should just parse the
font file ourselves:
https://www.seasip.info/DOS/CPI/cpi.html

**Comment by andrewbird** [comment]
I've been doing this on fdpp and it seems to work okay
~~~
DISPLAY CON=(EGA,858,1)
MODE CON CP PREP=((858) C:\DOS\EGA.CPX)              
MODE CON CP SEL=858
~~~

~~~
FreeDOS DISPLAY ver. 0.13b
Buffers allocated: 000 in TPA, 001 in XMS
Uncompressing and loading UPXed CPI (CPX) file :-).
MODE select codepage 858 function completed
C:\>
~~~

I can get the euro symbol displayed okay

**Comment by stsp** [comment]
Thanks, good to know!
But as for 2, I think we can only provide
the ega.cpi in a binary form, since it does
not contain the code. display/mode.com
cannot be provided. So perhaps we should
embed some small CPI loader.
In case of a freedos, where is it? Is it in
display.com or in mode.com?

**Comment by stsp** [comment]
OKey google...
https://github.com/legionus/kbd/blob/master/contrib/codepage.c
So the CPI loader is already here.
Great news.

**Comment by stsp** [comment]
[cpi.tar.gz](https://github.com/stsp/dosemu2/files/3482787/cpi.tar.gz)
Unupxed freedos CPI files.

**Comment by stsp** [comment]
[codepage.c.gz](https://github.com/stsp/dosemu2/files/3482938/codepage.c.gz)
Fixed CPI loader program (original one doesn't work).

**Comment by stsp** [comment]
[codepage.c.gz](https://github.com/stsp/dosemu2/files/3483396/codepage.c.gz)
Now prints info about every found font.
This is enough to port to dosemu.
So cool finding!
