### ISSUE TITLE
does SWITCHES=/F still work?

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#847]
I might be doing something wrong, but
on my pc-dos setup, which was with me
for something like last 25 years, I can't
seem to get `SWITCHES=/F` to work any
more. Is it a dosemu regression, or just
my stupidness? Does it work on ms-doses?

**Comment by jharrison03** [comment]
It works here with MS-DOS 6.22.

[boot.log.zip](https://github.com/stsp/dosemu2/files/3304788/boot.log.zip)

**Comment by stsp** [comment]
[pcdos.tar.gz](https://github.com/stsp/dosemu2/files/3307719/pcdos.tar.gz)
Could you please check if it works on this pc-dos?
Thanks.

**Comment by stsp** [comment]
Works perfectly with the configs below on an ubuntu
machine. Have to try them on my fedora machine where
it doesn't work properly...
[c.tar.gz](https://github.com/stsp/dosemu2/files/3340084/c.tar.gz)

**Comment by stsp** [comment]
Found out that the presence of the `drvspace.bin`
file (even empty) breaks `SWITCHES`. Might be a
pc-dos bug.
