### ISSUE TITLE
XMS function 08h should not write high words if XMS disabled

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#853]
**Describe the bug**
XMS function 08h is the old-style (XMS version 2.00) "Query free memory" call. If XMS is disabled, dosemu in https://github.com/stsp/dosemu2/blob/78af24d71e69e7d309ca30c5c76d833167beea03/src/dosext/misc/xms.c#L612 writes the EAX and EDX registers in full, but it should write only the low words (AX and DX).

**Comment by stsp** [comment]
Thanks, thought why not to submit the patch.

**Comment by ecm-pushbx** [comment]
https://github.com/stsp/dosemu2/issues/852#issuecomment-502237464 I put a patch here. Your commit is wrong; for function 88h it should clear the high words as it used to.

**Comment by stsp** [comment]
OK, I undone the patch.
Please upload the PR>

**Comment by ecm-pushbx** [comment]
Done.
