### ISSUE TITLE
Problem with drives 

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/dosemu2#860]
Everything was working fine until a recent update when I started having an error when I ran the following command. 

`dosemu -K "/home/manuel/Documents/Business/Oficina/saintc" -E"ARRANCA.BAT" -U 1 -w`

It says 

`ERROR: Could not change to G:`

Also I get an infinite loop when I use `lredir`

**Comment by stsp** [comment]
Should now be fixed.

**Comment by ZoccoCss** [comment]
It's working again. Thank you.
