### ISSUE TITLE
Variable $_X_vesamode not working anymore

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#862]
**Describe the bug**
Setting user specific VESA modes with `$_X_vesamode` does not work anymore

**To Reproduce**
Set up `$_X_vesamode` and try to use it in a program

**Attach the log**
The problem has been bisected to the following commit:
```
90ca7e993f02ba2644e2fe24f7aebae6ddcdbf11 is the first bad commit
commit 90ca7e993f02ba2644e2fe24f7aebae6ddcdbf11
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Jun 22 01:01:39 2019 +0300

    remove $_X_keycode option [fixes #859]
    
    3 input methods is too much. 2 is enough.
    But leave all the code untouched. Maybe someone will need it
    for debugging or will want to get back.

:040000 040000 7f1befadde9e147a85cc5cffc5123e6d4f466450 c55a8bfb8f92694baf12fc965a34a4220fcfb7b5 M	etc
:040000 040000 a73a136cce6af8d5a9faa20699fbee9b33223d42 4723f9b9bf04ec1fed9972935dc0050e072d8e52 M	src
```
I tried to readd `$$xxx` in `global.conf`, but that didn't work. This file seems to be a beast...

**Comment by andrewbird** [comment]
Perhaps you need `$xxx = ""` just after the `## X param settings` comment. BTW I think global.conf is still compiled in, so changes to the installed file won't have any effect, you'll need to alter the file in git tree and rebuild.

**Comment by bolle732** [comment]
Thanks, I did a recompile and install after changing `global.conf`. That produced an error.

**Comment by stsp** [comment]
Should now be fixed, thanks.
Argh, what a silly bugs, this global.conf
is indeed a beast.

**Comment by bolle732** [comment]
Thanks too for fixing this in time! So my fault was, that the `$xxx` was not initialized. Good to know.

**Comment by andrewbird** [comment]
I now notice that since 1a80720 global.conf isn't installed any more, so my advice about changes to the installed file was incorrect. I'm glad that's gone.

**Comment by stsp** [comment]
> I now notice that since 1a80720 global.conf isn't installed any more, so my advice about changes to the
> installed file was incorrect.

If there _is_ an installed one, then your advise was correct.
Of course it is very unlikely that the installed one exists. :)
