### ISSUE TITLE
[Feature request] In -dumb mode, write DOS stderr to linux stderr

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#863]
It could be useful to have a DOS program write its stderr output to the linux host's stderr. Might need a CON device driver on the DOS side, as below that (at the int 29h and int 10h levels) the distinction is lost.

**Comment by stsp** [comment]
No, this isn't worth a trouble.
We already have the inte6 API to write to
dosemu log, and we can add an API to write
to stderr. But the replacement CON driver is
out of possibilities.

**Comment by stsp** [comment]
How about `2>&1` or the like?
But I don't suppose this works in DOS. :)

**Comment by ecm-pushbx** [comment]
`2>&1` is a bash-ism respectively cmd.exe-ism. But the DOS stderr isn't lost, it already goes to linux stdout.

**Comment by stsp** [comment]
Then something like `2>LNX` and a new con driver for LNX. :)

**Comment by stsp** [comment]
In principle, some clever patch to fdpp
that will preserve the fd number in some
(currently unused) register for int10, can
be accepted.

**Comment by stsp** [comment]
Since the move to fdpp, even such a crazy ideas
can be considered. :) I am sure the patch for propagating
this info to int10 will be small.
