### ISSUE TITLE
Ctrl-Enter is not correctly recognized

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#864]
**Describe the bug**
In my clipper program key press is identified by lastkey() function. 

Lastkey() for enter is 13
Lastkey() for Ctrl-Enter is 10

However, in recent dosemu2 version lastkey() cannot differentiate enter and ctrl-enter it always return 13  

**To Reproduce**
Steps to reproduce the behaviour:

Download this little program [LASTKEY.EXE](https://drive.google.com/file/d/1FAcpwTi0K_nkNTqU0LCY4LLbCdKAFiBP/view?usp=sharing)

Run the program

Press any key and it will displays the lastkey() for the key pressed.

Try press Enter and Ctrl-Enter, it will display the same number

Press escape to quit the program.

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.
[boot.log](https://github.com/stsp/dosemu2/files/3328350/boot.log)

**Comment by stsp** [comment]
Does it help to set `$_layout` to
some layout of yours?

**Comment by bpranoto** [comment]
Yes. 
$_layout = "us" works correctly.
Thank you

**Comment by stsp** [comment]
This doesn't mean it is fixed.
It just means we can't fully trust
the xkb mapping. There appears
to be an exceptions, I wonder if
Ctrl-Enter is the only exception
or there are more...

**Comment by stsp** [comment]
I think this is some kind of an xkb misconfiguration.
If you run `xev` program, you'll see that eg `Ctrl-m`
gives CR and `Ctrl-j` gives LF. So all ctrl chars are
working properly, but `Enter` and `Ctrl-Enter` both
give CR, whereas `Ctrl-Enter` should give LF.
Is anyone here familiar with how to reconfigure the
xkb mapping?

**Comment by stsp** [comment]
I applied the work-around to exclude `Ctrl-Enter`
from the xkb translation. But someone more familiar
with xkb can see why it is so, and maybe fill in a
bug report to xorg?
