### ISSUE TITLE
Travis-CI: Should it use the FDPP package from PPA?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#865]
I have a minimal test build working in Travis CI and currently it's using the FDPP from the PPA, but should I be cloning the latest GIT for each build instead?

**Comment by stsp** [comment]
Depends on how travis-ci work.
If it is possible to set up a single
suit to monitor commits/prs of
both dosemu2 and fdpp, then its
better to test git versions of both.
If there is only a per-repo suit and
you are testing only dosemu2, then
ppa may be fine (though this will
break on fdpp protocol changes).

**Comment by andrewbird** [comment]
In the end I found it better to clone and build FDPP, even though I don't see any way of doing monitoring of or triggering from both repos. Thanks.

**Comment by stsp** [comment]
What are the results?

**Comment by andrewbird** [comment]
I have these running so far.
https://travis-ci.com/andrewbird/dosemu2 [![Build Status](https://travis-ci.com/andrewbird/dosemu2.svg?branch=devel)](https://travis-ci.com/andrewbird/dosemu2)

I need to get djgpp on there for the others

**Comment by stsp** [comment]
Looks cool.
How to use that? :)

**Comment by andrewbird** [comment]
Every time I push to that branch it gets built and tested, just because there's a .travis.yml file in it. If you merge it and setup your github to oauth Travis, it will do same for you, and I believe PRs will get tested even before you merge too.

**Comment by stsp** [comment]
So do I need trvis.yml for that?
Can you prepare the PR with it?

**Comment by andrewbird** [comment]
I'm not quite finished yet. I didn't add freedos 1.20 test for reference or test a 'known fail'. Also in an ideal world someone would put DJGPP in the PPA :smile:, then I could put back the other tests that need it.

**Comment by stsp** [comment]
Cant you just wget djgpp?

**Comment by andrewbird** [comment]
I wanted the cross compiler rather than the DOS version, but I figure I'll wait until later to add those tests back in.

**Comment by stsp** [comment]
Why cant you dl a cross compiler
or anything else you like?

**Comment by andrewbird** [comment]
Of course you can, but I figured you meant DOS as DJ has EXEs on his site for download. My cross is a 32bit Ubuntu build and the Travis VM is 64bit Ubuntu, so I have to rebuild it anyway.

**Comment by stsp** [comment]
Dos djgpp just a better test on its own.
It doesnt matter what I mean, what
matters is that you can wget anything.
Btw, isnt there a static storage on
travis itself, so that you can upload
djgpp there just once?

**Comment by andrewbird** [comment]
There's no persistence on Travis see [here](https://docs.travis-ci.com/user/build-stages#data-persistence-between-stages-and-jobs).
BTW have you checked out the permissions that you need to give Travis for your Github account? It doesn't matter to me, but perhaps you have private repos?
![travis1](https://user-images.githubusercontent.com/220835/60396625-e478ab80-9b3b-11e9-81ce-5ee8966f3362.png)
![travis2](https://user-images.githubusercontent.com/220835/60396627-e9d5f600-9b3b-11e9-96c7-29c78eb2134d.png)
![travis3](https://user-images.githubusercontent.com/220835/60396628-ee021380-9b3b-11e9-9a22-74f3977e0fb6.png)

**Comment by stsp** [comment]
OK, I authorized travis-ci for fdpp and dosemu2 repos.
But it says "Your trial includes 100 trial builds and 2-concurrent-jobs, no credit card required."
I wonder if after 100 builds it will expire?

**Comment by andrewbird** [comment]
You don't need the trial, it's free for OS projects
