### ISSUE TITLE
DPMI unstable

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#869]
Random crashes in both KVM and native mode.
The log I am getting is weird:
```
DPMI: int 0x0031, AX=0x0300
DPMI: int31, ax=0300, ebx=00000021, ecx=00000000, edx=00000014
        edi=000c6ddc, esi=00000015, ebp=000c6da8, esp=000c6d98
        eip=0001aa93, eflags=00093246
        cs=00f7, ds=00ff, ss=0107, es=0107, fs=00af, gs=010f
DPMI: switching to realmode stack, in_dpmi_rm_stack=1
DPMI: RealModeCallStructure at 0x42702ddc
DPMI: int 0x21 fn 1a00
DPMI: Return to dosemu at 00f7:0001aa93, Stack 0x107:0x000c6d98, flags=0x13246
DPMI: realmode hlt: 0xff50b
DPMI: Return from Real Mode Procedure
DPMI: return from realmode procedure, in_dpmi_rm_stack=0
DPMI: cs=0xf7, ss=0x107, ds=0xff, es=0x107, fs=0xaf, gs=0x10f ip=0x1aa93
DPMI: switch to dpmi
DPMI: Return to client at 00f7:0001aa93, Stack 0x107:0x000c6d98, flags=0x93246
DPMI: switch to dosemu
MSDOS: msdos_fault, err=0x18a
DPMI: do_cpu_exception(0x0d) at 0xf7:0x1aa93, ss:esp=107:c6d98, cr2=0, err=0x18a
DPMI: eip: 0x0001aa93  esp: 0x000c6d98  eflags: 0x00013246
        trapno: 0x0d  errorcode: 0x0000018a  cr2: 0x00000000
        cs: 0x00f7  ds: 0x00ff  es: 0x0107  ss: 0x0107  fs: 0x00af  gs: 0x010f
EAX: 00000300  EBX: 00000021  ECX: 00000000  EDX: 00000014
ESI: 00000015  EDI: 000c6ddc  EBP: 000c6da8
OPS  : 47 30 00 00 66 b8 00 03 cd 31 -> 73 0d 66 a3 f8 65 04 00 b8 ff
STACK: 01 00 46 74 0c 00 14 00 00 00 -> ff 00 0c 00 ff 00 00 00 e1 76
GPF on selector 0xff base=02131000 lim=dffff
```

This almost makes no sense.
73 0d opcode GPFs with errcode 0x18a?
"GPF on selector 0xff"?
Cut the crap...
May be some kernel bug, as everything was rock-stable,
and no one touched DPMI for very long now...
```
$ uname -r
5.0.0-15-generic
```

**Comment by stsp** [comment]
Correction: not broken on kvm. Only native
mode is broken. So a kernel bug most likely...

**Comment by stsp** [comment]
@amluto are you aware about any recent
kernel changes (circa 5.0) that could break
`sigreturn()` the way I am getting the selector
error for the selector that is not in a sigcontext?
Here is the sigcontext dump:
```
(gdb) p /x *scp
$1 = {gregs = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11, 0xc7ef8, 0xc7ed8, 
    0x1b, 0x1fa, 0x200, 0x70, 0xc7ed4, 0x2b7cd, 0x13246, 0xff00af010f00f7, 
    0x18a, 0xff00ff000d, 0x0, 0x0}, fpregs = 0x19d71c0, __reserved1 = {0x0, 
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}
(gdb) p /x scp->gregs[REG_ERR]
$3 = 0x18a
```

As can be seen, errno is 0x18a, but there
is no such selector elsewhere, so I don't
try to load it with `sigreturn()`. I also noted
that VIF flag was set before `sigreturn()` but
is cleared after, in the signal, but this makes
no sense to me. There was no client code
execution: it seems GPF comes right from
`sigreturn()`, if this is at all possible... Because
I see that eip didn't change, plus I see the opcode
73 0d which is not expected to GPF.
@amluto any hints where to dig?
Nothing have changed in dosemu's DPMI
impl for years, and I attribute this problem
to the recent kernel upgrade.

**Comment by amluto** [comment]
On Mon, Jul 1, 2019 at 10:53 AM Stas Sergeev <notifications@github.com>
wrote:

> @amluto <https://github.com/amluto> are you aware about any recent
> kernel changes (circa 5.0) that could break
> sigreturn() the way I am getting the selector
> error for the selector that is not in a sigcontext?
> Here is the sigcontext dump:
>
> (gdb) p /x *scp
> $1 = {gregs = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11, 0xc7ef8, 0xc7ed8,
>     0x1b, 0x1fa, 0x200, 0x70, 0xc7ed4, 0x2b7cd, 0x13246, 0xff00af010f00f7,
>     0x18a, 0xff00ff000d, 0x0, 0x0}, fpregs = 0x19d71c0, __reserved1 = {0x0,
>     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}
> (gdb) p /x scp->gregs[REG_ERR]
> $3 = 0x18a
>
> As can be seen, errno is 0x18a, but there
> is no such selector elsewhere, so I don't
> try to load it with sigreturn(). I also noted
> that VIF flag was set before sigreturn() but
> is cleared after, in the signal, but this makes
> no sense to me. There was no client code
> execution: it seems GPF comes right from
> sigreturn(), if this is at all possible... Because
> I see that eip didn't change, plus I see the opcode
> 73 0d which is not expected to GPF.
> @amluto <https://github.com/amluto> any hints where to dig?
> Nothing have changed in dosemu's DPMI
> impl for years, and I attribute this problem
> to the recent kernel upgrade.
>
>
> Are you able to bisect this?  Nothing comes to mind.  If you have a
self-contained test (set up some registers and LDT entries and raise a
signal, perhaps?) then I can try to debug it.

**Comment by stsp** [comment]
@amluto even the test-case below prints `18a` but
does this make any sense? Confused.
```
#include <signal.h>
#include <stdio.h>
#include <unistd.h>
#include <inttypes.h>

static void my_sig(int sig, siginfo_t *info, void *uc)
{
    ucontext_t *uct = uc;
    struct sigcontext *scp = (struct sigcontext *)&uct->uc_mcontext;
    printf("err: %lx\n", scp->err);
    _exit(0);
}

int main()
{
    struct sigaction sa;

    sa.sa_flags = SA_RESTART | SA_ONSTACK | SA_SIGINFO;
    sa.sa_sigaction = my_sig;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGSEGV, &sa, NULL);
    asm volatile ("int $0x31\n");
}
```

**Comment by stsp** [comment]
@amluto able to reproduce with the above test-case?
I tried on fedora with 5.0.16-200.fc29.x86_64, and its
the same: `err` returns 0x18a. What does this value
mean? Definitely not what it should?

**Comment by amluto** [comment]
I have reproduced it, and I don't know what's wrong yet.  I'll keep you
posted.

**Comment by amluto** [comment]
No, wait, you faked me out.  0x18a is the correct error code for a failure
to deliver int 0x18a.  Look at SDM Volume 3 6.13: 0x18a is (0x31 << 3) } (1
<< 1).  The latter is "descriptor location", and it means that the index
points to the IDT.

**Comment by stsp** [comment]
Sorry for that.
Then I'll need to investigate further why `sigreturn()`
doesn't seem to work as expected.

**Comment by stsp** [comment]
OK, @amluto sorry for bothering you with this.
It appears that this debug build was gprof-enabled,
and so SIGPROF was armed. To fix the crash it
appears enough to just force the `SA_ONSTACK`
for it. Which is a bit strange, as I thought also
`UC_STRICT_RESTORE_SS` is a mandatory.
In either case, I wrapped it fully (with `UC_STRICT_RESTORE_SS`
too), so the crash is gone.

**Comment by amluto** [comment]
UC_STRICT_RESTORE_SS is only needed if you modify the sigcontext and want
the resulting behavior to make sense.  If you just get a signal and return,
it shouldn't make a difference.

**Comment by stsp** [comment]
My memory is probably unstable.
IIRC you explained that _any_ syscall would
clobber SS and force it to the default value.
So I was assuming, unless you specify
UC_STRICT_RESTORE_SS, this is the case
for `sigreturn()` too. In which case you would
need it no matter whether you've modified the
sigcontext. Could you please refresh
my memory on that understanding?

**Comment by amluto** [comment]
It's documented in [arch/x86/include/uapi/asm/ucontext.h](https://github.com/torvalds/linux/blob/eca94432934fe5f141d084f2e36ee2c0e614cc04/arch/x86/include/uapi/asm/ucontext.h#L24-L28).  Basically, if you modify the descriptor tables or the ucontext from the signal handler but you don't set UC_STRICT_RESTORE_SS then the kernel may change SS for you.  If you don't do either one of these thngs, then nothing changes.  I did this for compatibility with older versions of dosemu :)

The UC_STRICT_RESTORE_SS behavior makes much more sense, but preserving compatibility with old programs is important.

**Comment by stsp** [comment]
Mm, interesting:
```
 * Kernels that set UC_SIGCONTEXT_SS will also set UC_STRICT_RESTORE_SS
 * when delivering a signal that came from 64-bit code.
```

But this is how you seem to have documented it for dosemu:
https://github.com/stsp/dosemu2/blob/devel/src/arch/linux/async/signal.c#L445
```
 * For compatibility with old programs, the kernel will *not* set
 * UC_RESTORE_SS when delivering signals.
```
So have the behaviour changed? When?
And also I can vaguely remember yours saying
the syscalls (any) can clobber SS - or is this just
my memory wrong?

Also, these flags seems to be still not in glibc.
I put a cpp warning back when they appeared,
and it triggers up to these days...

**Comment by stsp** [comment]
> So have the behaviour changed? When?

Probably not, as delivering from 64bit is not our case...

**Comment by stsp** [comment]
```
 * if (saved SS is valid || UC_STRICT_RESTORE_SS is set ||
 *     saved CS is not 64-bit)
```

Ah, in this case I see why its unnecessary...
So I may just as well never set it at all?

**Comment by stsp** [comment]
Indeed, its not needed!
I tested w/o this flag and all works!
Puzzled... The code that sets it, came from
you. Plus, I have the checks like this:
```
    error("Your kernel does not support UC_STRICT_RESTORE_SS and the "
  "work-around in dosemu is not enabled.\n");
    leavedos_sig(11);
```

Certainly something have changed?
Or was this just some misunderstanding?

**Comment by stsp** [comment]
` * if (saved SS is valid`

Saved where? IIRC there was no place in a
sigcontext to save it? At least I have this now:
```
#define _ss     (((union g_reg *)&scp->gregs[REG_CSGSFS])->w[3])
```
So it looks like I just put it "somewhere".

So... how should it all look today?

**Comment by stsp** [comment]
```
    I do this by special-casing the interesting case.  On sigreturn,
    ucontext->ss will be honored by default, unless the ucontext was
    created from scratch by an old program and had a 64-bit CS
    (unfortunately, CRIU can do this) or was the result of changing a
    32-bit signal context to 64-bit without resetting SS (as DOSEMU
    does).
```

OK, so from this I can assume we don't need
the `UC_STRICT_RESTORE_SS` flag as you
check the saved SS validity, and setting this flag
to only get an exception, looks not very useful.

**Comment by stsp** [comment]
In fact, even forcibly _clearing_ `UC_STRICT_RESTORE_SS`
seems to work fine... Indeed I very much suspect the syscalls
used to clobber SS and now they do not?

**Comment by stsp** [comment]
Ah, it seems SS is switched to GDT before signal is delivered
now, so whether syscalls clobber it or not, does not
even matter...
And manually clearing `UC_STRICT_RESTORE_SS`
also doesn't matter because "saved SS is valid".
So I think I realize the picture now, except why
`UC_STRICT_RESTORE_SS` is ever needed.

**Comment by amluto** [comment]
OK, here's a summary of a few things.

All system calls should be assumed to clobber SS.  This is a hardware limitation -- the SYSCALL and SYSENTER instructions clobber SS and don't save the old value anywhere.  If you manually do a 32-bit system call with int $0x80, then CS and SS should be preserved.  This has little to do with signal handling, since signals are mostly a result of traps or faults, not system calls.

For 32-bit user code (that is, if you're on a 32-bit kernel, or if you're on a 64-bit kernel but you used 32-bit code to install the signal handler), CS and SS are saved in the signal context and restored by sigreturn.  This works exactly the way you'd expect and is pretty boring, unless your kernel is very, very old and loses the high bits of ESP.  UC_SIGCONTEXT_SS is, among other things, a promise that the kernel doesn't have that problem.

For 64-bit user code (that is, you used 64-bit code to install the signal handler), old kernels did not save SS into sigcontext at all.  Instead, you could more-or-less-reliably learn the original SS value by reading it from the SS *register* in the signal handler as long as you made sure not to clobber it first.  If you did a system call in the handler before reading %ss, it would get clobbered.  New kernels will set UC_SIGCONTEXT_SS and *do* save SS into the sigcontext.  See arch/x86/include/uapi/asm/sigcontext.h -- struct sigcontext has an ss field now.

This means that, on a kernel that does not set UC_SIGCONTEXT_SS, dosemu probably needs to go to some lengths to remember %ss (the hardware SS register) in a signal handler.

Now here's the nasty part.  On old kenels, when a 64-bit signal handler returns, even to 32-bit or 16-bit code, SS is reset to a flag 32-bit segment.  IIRC dosemu has or had some nasty 32-bit trampoline to restore SS.  New kernels (the ones that set UC_SIGCONTEXT_SS) don't need that hack, since the kernel will *attempt* to restore SS from sigcontext.  UC_STRICT_RESTORE_SS turns off the "attempt" heuristic and makes it absolute.

My advice would be to set UC_STRICT_RESTORE_SS in any code that modifies sigcontext or that might do modify_ldt() or set_thread_area() frmo a signal handler.  If you make a mistake and you don't set UC_STRICT_RESTORE_SS, then then kernel might try to cover up your mistake, and might end up hiding your bug and then causing some other subtle problem.

An older version of the patches had UC_RESTORE_SS instead of UC_STRICT_RESTORE_SS, but IIRC that was never in a released kernel.

Does that all make sense?

**Comment by stsp** [comment]
Thanks for the summary!
So now it won't be forgotten. :)
But couldn't the following work:
```
 * if (saved CS is 32)
 *         new SS = saved SS  (will fail IRET and signal if invalid)
 * else
 *         new SS = a flat 32-bit data segment
```
This probably misses some case, but I wonder which one.
Old dosemu:
- when saved CS is 32, uses trampoline, according to what
you said above, so is not a subject to the "saved CS is 32"
check in `sigreturn()`.
- When saved CS is 64, old dosemu wants flat SS.
New dosemu:
- when saved CS is 32, wants saved SS
- when saved CS is 64, wants flat SS (equal to the saved SS)

Maybe you envisioned someone wanting the LDT SS
even in 64bit? Which would be very strange, but even
then, couldn't the below just do:
```
 * if (saved CS is 32 || UC_STRICT_RESTORE_SS is set)
 *         new SS = saved SS  (will fail IRET and signal if invalid)
 * else
 *         new SS = a flat 32-bit data segment
```

In both cases the nasty "if (saved SS is valid)" part is
avoided, which is IMHO a plus. But I suppose I still miss
some pathological case here. :)

**Comment by amluto** [comment]
> Thanks for the summary!
> So now it won't be forgotten. :)
> But couldn't the following work:
> 
> ```
>  * if (saved CS is 32)
>  *         new SS = saved SS  (will fail IRET and signal if invalid)
>  * else
>  *         new SS = a flat 32-bit data segment
> ```
> 

...

> Maybe you envisioned someone wanting the LDT SS
> even in 64bit? Which would be very strange, but even
> then, couldn't the below just do:
> 
> ```
>  * if (saved CS is 32 || UC_STRICT_RESTORE_SS is set)
>  *         new SS = saved SS  (will fail IRET and signal if invalid)
>  * else
>  *         new SS = a flat 32-bit data segment
> ```
> 
> In both cases the nasty "if (saved SS is valid)" part is
> avoided, which is IMHO a plus. But I suppose I still miss
> some pathological case here. :)

I think this could break in a pathological case with old DOSEMU.  Suppose you get a SIGSEGV from 32-bit or 16-bit code.  Then, in the signal handler but before you save SS, you get *another* signal (SIGALRM, say, that isn't aware of UC_STRICT_RESTORE_SS).  That signal would clobber SS, and now you're screwed.  Similarly, if you try to switch from 64-bit to 32-bit code by first loading SS and then long jumping, there's a window where a signal would mess you up.

Admittedly, old kernels also got that wrong, but I was trying to be helpful when I designed this whole thing.

**Comment by stsp** [comment]
> That signal would clobber SS, and now you're screwed.

But because, as you said, also the old kernels would clobber
SS in that situation, dosemu1 seems to have this code:
https://sourceforge.net/p/dosemu/code/ci/master/tree/src/arch/linux/async/signal.c#l84
https://sourceforge.net/p/dosemu/code/ci/master/tree/src/arch/linux/async/signal.c#l111
So it sets the sigaction mask to blocks all the
async signals, and then even forgets to unblock them
it seems. This ugly code was rewritten from zero
in the very first days of dosemu2, but there was
no such race IIRC.

> try to switch from 64-bit to 32-bit code by first loading SS and then long jumping

This is why dosemu1 seems to have this:
https://sourceforge.net/p/dosemu/code/ci/master/tree/src/dosext/dpmi/dpmisel.S#l31
I.e. it is doing an atomic trampoline with "iret".

So there were the techniques to circumvent the
problem, and they were either employed (dosemu1)
or the app won't work back then. So maybe if you
ever come to cleaning up that code, I suspect that
"if (saved CS is 32)" would just be enough. Even if
you are not going to do such clean-up any soon,
agreeing on that it is enough, may mean the deprecation
of UC_STRICT_RESTORE_SS, in which case I'll just
remove it. As I mentioned, its still not part of any glibc
and people complain on the compile-time warnings I
added for checking its presence.
Deprecating?

**Comment by amluto** [comment]
> So there were the techniques to circumvent the
> problem, and they were either employed (dosemu1)
> or the app won't work back then. So maybe if you
> ever come to cleaning up that code, I suspect that
> "if (saved CS is 32)" would just be enough. Even if
> you are not going to do such clean-up any soon,
> agreeing on that it is enough, may mean the deprecation
> of UC_STRICT_RESTORE_SS, in which case I'll just
> remove it. As I mentioned, its still not part of any glibc
> and people complain on the compile-time warnings I
> added for checking its presence.
> Deprecating?

I still think that the UC_STRICT_RESTORE_SS behavior is better than the heuristic behavior without it.  If I could go back in time and change the kernel from day 1, I would make the strict behavior unconditional.

And the kernel has nice test cases to validate that it doesn't regress.

So I still think that you should use UC_STRICT_RESTORE_SS so that, if you ever make a mistake that corrupts SS, you'll notice right away rather than possibly having problems elsewhere in your code. :)

**Comment by stsp** [comment]
> I still think that the UC_STRICT_RESTORE_SS behavior is better than the heuristic behavior without it.

Yes, but unfortunately, it currently:
- does nothing (and unlikely ever will)
- is not accepted by any glibc in 4 years
These are the practical problems, and you
need to at least convince glibc people that it
is needed. As it is now, it only represents the
problem.
My proposal is to remove the heuristic actually,
or at least strip it to the bare minimum. This "SS is valid"
is the nasty heuristic in its implementation too.
If you still like UC_STRICT_RESTORE_SS, maybe at
least remove "SS is valid"? It looks like the tasks of
removing either, are completely independent.

> If I could go back in time and change the kernel from day 1, I would make the strict behavior unconditional.

https://groups.google.com/forum/?nomobile=true#!topic/linux.kernel/Z4hRSzO7908%5B101-125%5D
I tried very very hard to convince you that way,
but failed. :) But perhaps all is not lost, and you
can still do:
```
 * if (UC_STRICT_RESTORE_SS is set)
 *         new SS = saved SS  (will fail IRET and signal if invalid)
 * else
 *         new SS = a flat 32-bit data segment
```
... and only set it when coming out of 32 bit?

**Comment by stsp** [comment]
> New kernels will set UC_SIGCONTEXT_SS and do save SS into the sigcontext.
> See arch/x86/include/uapi/asm/sigcontext.h -- struct sigcontext has an ss field now.

Could you please clarify what happens to real SS
after that? Is it switched? I suppose not, but I've found
this comment:
https://github.com/stsp/dosemu2/blob/devel/src/arch/linux/async/signal.c#L296
I guess this refers not to the newer kernels,
but to those few versions of the past that did
it the wrong way?

If this is true and you make `UC_STRICT_RESTORE_SS`
w/o heuristic as above, then people would never need to
touch it (and glibc won't need to include) unless someone
wants to either:
- preserve SS at the start of a sighandler as you described above
- LDT SS even in 64bit

Since both sounds very very unlikely, I'd say this
UC_STRICT_RESTORE_SS will never ever come
up again. And there will be no heuristic.
So what do you think?

**Comment by amluto** [comment]
> ```
>  * if (UC_STRICT_RESTORE_SS is set)
>  *         new SS = saved SS  (will fail IRET and signal if invalid)
>  * else
>  *         new SS = a flat 32-bit data segment
> ```
> 
> ... and only set it when coming out of 32 bit?

If the kernel did this, then your SIGPROF issue would still exist -- a signal handler that was unaware of any of this stuff would corrupt SS.

> Could you please clarify what happens to real SS
> after that? Is it switched? I suppose not, but I've found
> this comment:
> https://github.com/stsp/dosemu2/blob/devel/src/arch/linux/async/signal.c#L296
> I guess this refers not to the newer kernels,
> but to those few versions of the past that did
> it the wrong way?

Take a look here:

https://github.com/torvalds/linux/commit/8ff5bd2e1e2767fbf737f84d5f92668dafe7e7b0

I was trying to balance two concerns.  First, old dosemu looked at the actual SS register in signal handlers.  Second, there was a genuine problem that a problem with the stack segment was unrecoverable, since a signal due to a bad SS could not be delivered.

So the current logic is that, when a 64-bit signal is delivered, SS contains its original value _if it was valid_ and otherwise gets reset to a flat 32-bit segment.

If I were writing something like DOSEMU and I wanted to support old and new kernels, I would structure my signal handler a bit like this:

```
/*
 * Old kernels don't save %ss.  We can approximate it like this, which is correct as long as
 * the signal isn't due to SS itself being invalid.
 */
if (!(...->uc_flags & UC_SIGCONTEXT_SS)) {
  asm("mov %%ss, %0" : "=rm" (sigcontext->ss);
} else {
  /* Opt into unconditional SS restoring on new kernels. */
  ucontext->uc_flags |= UC_STRICT_RESTORE_SS;
}

/* do the actual work */

if (!(...->uc_flags & UC_SIGCONTEXT_SS)) {
  /* this kernel will clobber SS when we return.  use a trampoline. */
  sigcontext->ip = trampoline_ip;
  /* set up the rest... */
}
```

And if I didn't care about trying to be compatible with old kernels, I would abort if UC_SIGCONTEXT_SS was clear and then set UC_STRICT_RESTORE_SS.

Also, are you sure about the glibc issue?  /usr/include/asm/ucontext.h has the constants on my system.

**Comment by stsp** [comment]
> If the kernel did this, then your SIGPROF issue would still exist --
> a signal handler that was unaware of any of this stuff would corrupt SS.

No, I get the old handler with `sigaction()` and
wrap it from my handler that uses `UC_STRICT_RESTORE_SS`.
And even if I just force the `SA_ONSTACK` on it,
then it would still work fine because I don't need
to keep SS during the sighandler run, as it gets
saved/restored where needed. So I won't mind it
got restored to GDT.
By the way, I don't think only forcing SA_ONSTACK
is sufficient because you also need to restore FS/GS.
Who known when SIGPROF will start to use TLS? :)

> So the current logic is that, when a 64-bit signal is delivered, SS contains
> its original value if it was valid and otherwise gets reset to a flat 32-bit segment.

Are there any valid cases with bad SS on signal delivery?
There definitely was one on a signal return, but on a delivery? :(
So maybe also that heuristic can go away?

> I would structure my signal handler a bit like this:

Done, thanks.

> And if I didn't care about trying to be compatible with old kernels, I would abort if
> UC_SIGCONTEXT_SS

Yeah, there will definitely be the time when this
iret work-around will go away. We are quite far now
from the kernels needing that.

> Also, are you sure about the glibc issue? /usr/include/asm/ucontext.h
> has the constants on my system.

OK, I included `<asm/ucontext.h>` and it went in, thanks.
Now where is `SS_AUTODISARM`? :) I still have a warning
on it.

**Comment by stsp** [comment]
> Are there any valid cases with bad SS on signal delivery?

You probably want to deliver the signal even
in any invalid case, so that was the point...

**Comment by stsp** [comment]
> OK, I included <asm/ucontext.h> and it went in, thanks.

Had to revert it, as it breaks the build:
https://launchpadlibrarian.net/431708300/buildlog_ubuntu-xenial-amd64.dosemu2_2.0~pre8-5619-411cb02+201907040416~ubuntu16.04.1_BUILDING.txt.gz
```
In file included from /usr/include/x86_64-linux-gnu/asm/ucontext.h:10:0,
                 from /<<PKGBUILDDIR>>/build/../src/arch/linux/async/signal.c:6:
/usr/include/asm-generic/ucontext.h:4:8: error: redefinition of ‘struct ucontext’
 struct ucontext {
```

So really `asm/xxx` does't seem to count as the
API was accepted by glibc...

**Comment by amluto** [comment]
The include issue seems to be related to [glibc PR21475](https://sourceware.org/bugzilla/show_bug.cgi?id=21457).  With [glibc commit 251287734e89](https://sourceware.org/git/?p=glibc.git;h=251287734e89a52da3db682a8241eb6bccc050c9) applied, I can compile this:

```
#define _GNU_SOURCE
#include <signal.h>
#include <sys/ucontext.h>
#include <asm/ucontext.h>
```

That being said, <asm/sigcontext.h> is still thoroughly busted.  So I guess some progress is being made.

**Comment by amluto** [comment]
I filed [PR 24813](https://sourceware.org/bugzilla/show_bug.cgi?id=24813) to try to get more of this sorted out.

**Comment by stsp** [comment]
Thanks for taking care of the glibc part!
However, while it is not fixed, I think its a
good opportunity to refactor/simplify the
API you proposed. There will be no such
chance in the future. :)
So if you want to make UC_STRICT_RESTORE_SS
unconditional, or remove it (either or, both
ways are possible IMHO), its the right time
to think about that. Its not the API that everyone
is going to use, its just an ad-hoc for dosemu[12].
And dosemu[12] doesn't seem to need it being
that complex (in particular I find the checks of
SS validity quite nasty).

> So the current logic is that, when a 64-bit signal is delivered,
> SS contains its original value if it was valid and otherwise gets reset to a flat 32-bit segment.

But do you really need to do that?
Maybe you can instead _try_ to deliver the
signal, and if iret fails, only then fix SS and
also change si_code/si_errno accordingly?
This will get rid of the SS validity checks forever.
Of course I am just guessing, haven't looked
into that code for decades... Anyway, just an
ideas to think about before this all is written
in the stone.

**Comment by amluto** [comment]
Unless there's an actual problem, I would prefer not to further change the kernel.  But here are some comments:

> However, while it is not fixed, I think its a
> good opportunity to refactor/simplify the
> API you proposed. There will be no such
> chance in the future. :)
> So if you want to make UC_STRICT_RESTORE_SS
> unconditional, or remove it (either or, both
> ways are possible IMHO), its the right time
> to think about that. Its not the API that everyone
> is going to use, its just an ad-hoc for dosemu[12].

> And dosemu[12] doesn't seem to need it being
> that complex (in particular I find the checks of
> SS validity quite nasty).

I agree. But I've still never seen a suggestion of anything better.

> 
> > So the current logic is that, when a 64-bit signal is delivered,
> > SS contains its original value if it was valid and otherwise gets reset to a flat 32-bit segment.
> 
> But do you really need to do that?
> Maybe you can instead _try_ to deliver the
> signal, and if iret fails, only then fix SS and
> also change si_code/si_errno accordingly?

That's no so easy.  The kernel doesn't distinguish a failure to IRET to a signal handler from any other IRET failure. Also, trying to deliver the signal and changing si_code if it fails would be obnoxious.  Suppose a DPMI program dies due to deleting an in-use segment.  Do you really want a special si_code just for that as opposed to simply delivering the #GP or #SS as it happened?

In any case, the actually sensible behavior would be to unconditionally fix SS.  As I recall, I tried that, but it broke old DOSEMU.  So the current kernel behavior is actually a compromise to keep old DOSEMU working while still doing something more or less reasonable.

The 32-bit Linux behavior is entirely reasonable here -- SS is saved in sigcontext and reset when a signal is delivered.  There's no funny business.  The only reason 64-bit needs to be different at all is for compatibility with older Linux versions that didn't handle SS at all.

**Comment by stsp** [comment]
> I agree. But I've still never seen a suggestion of anything better.

1. ```
But perhaps all is not lost, and you
can still do:

 * if (UC_STRICT_RESTORE_SS is set)
 *         new SS = saved SS  (will fail IRET and signal if invalid)
 * else
 *         new SS = a flat 32-bit data segment

... and only set it when coming out of 32 bit?
```
To that you stated the SIGPROF concern, but I don't
think this is a problem as I dispatch its handler after
things are prepared, and it is sa_mask'ed otherwise.
I wouldn't want it to dispatch on its own because the
TLS is also trashed for it then.

2. ```
then, couldn't the below just do:

 * if (saved CS is 32 || UC_STRICT_RESTORE_SS is set)
 *         new SS = saved SS  (will fail IRET and signal if invalid)
 * else
 *         new SS = a flat 32-bit data segment
```
You expressed the concern about the non-atomic
trampoline in dosemu1, but there was no such thing
or it wouldn't work with the older kernels too.

So I still consider both the above suggestions valid,
why don't you think they are? :)

> That's no so easy. The kernel doesn't distinguish a failure to IRET to a signal handler from any other IRET
> failure. Also, trying to deliver the signal and changing si_code if it fails would be obnoxious.

But the signals from DPMI space are not caused by iret.
They are caused by something else in userspace (eg sti).
You try to deliver them, and if you can't - there will be the
fault in kernel space on iret, which will automatically mean
the different si_code, at least as my limited understanding
of that code suggests.

> Do you really want a special si_code just for that as opposed to simply
> delivering the #GP or #SS as it happened?

I was assuming there would be different si_codes between
the DPMI fault from userspace and the iret fault from kernel,
so I thought this will just work.

> The only reason 64-bit needs to be different at all is for compatibility with older
> Linux versions that didn't handle SS at all.

Yes, I understand that, and this is why I was proposing
SA_xyz - the flag that will do exactly that and UC_STRICT_RESTORE_SS
and everything else - just in one flag! You didn't buy it. :)
Now as there is no such flag, I propose whatever looks
not quite that good but still avoids any heuristic all together:
try to deliver the signal from userspace, and if it fails - fix
SS and try again, but this time from kernel (so si_code
differs).

**Comment by stsp** [comment]
Why I think the last suggestion is valid,
is because I assume there will be no
such condition ever. DPMI simply cant
load bad SS, and neither it can modify
LDT w/o asking dosemu to, which means
sigreturn. So this second-attempt delivery
is just an extra care. There can be
do_exit() instead, just as well. So while
in theory it is better to have only one
delivery attempt (with initially fixed SS),
in practice its the same thing, as the
second attempt will never happen
anyway.

**Comment by stsp** [comment]
A better variation might be:
- do_exit() if failed to deliver the sig
from 32bit code (never happens)
- fix SS unconditionally if from 64bit code

**Comment by stsp** [comment]
So basically, if any signal delivery failed - do_exit().
But fix SS when from 64bit for the extra care.
I believe even fixing SS from 64bit is pretty much
"optional": even if the sighandler does modify_ldt()
as a very first operation (to invalidate SS), its SS
will already be fixed by the syscall itself, so remains
valid (pointing to GDT).

This all makes me think that there is no place at
all, neither in 32 or 64bit code, where the SS is
invalid. Its always valid, because even modify_ldt()
forces it to GDT immediately. The only problem was
that you stored SS in sigcontext and restored it on sigreturn()
when it was already invalid and shouldn't have been
restored. dosemu1 never used sigreturn() to 32bit,
so what happened is that you tried ot restore LDT SS
when actually returning to 64bit (because you took
the unused sigcontext field for it).
So the only problem seems to be that we can't
trust the saved SS value in sigcontext _when
returning to 64bit_. But in this case the only needed
fixup would be to force SS to default on returning
to 64bit. Nesting sighandlers won't suffer: the async
signals are all sa_mask'ed before the segment regs
are dealt with (otherwise there would be the problems
with LDT too).
So maybe I am walking in a circles, but once again
I fail to see the need for all the new flags and the changes
that were done... And its probably too difficult to keep
all the details in memory at once, so if we start by pieces:

1. am I right that there is never a place where SS can be
invalid?
2. am I right that the problem of your initial patch with dosemu1
was that dosemu1 simply didn't update the SS field you
used in sigcontext, so at return to 64bit the garbage SS
was attempted to be restored? (the last one from LDT likely,
as dosemu1 simply didn't overwrite that field, and that
LDT entry was invalidated)
3. am I right that there is no problem with nesting signals
because the one have to sa_mask them initially anyway,
and this is what dosemu1 is doing, and there are no other
problems with nested sighandlers?
4. am I right that the only needed fix then is to always
force SS to GDT when returning to 64bit? (this is because
dosemu1 never sigreturn()ed to 32bit space, so in sigreturn()
to 32bit space you _can_ trust saved SS, as this is when
you are dealing with dosemu2 only).

OK, I really feel hopeless for not understanding everything
once again. Maybe if we have that list of assertions and you
point which ones are wrong, this will finally take the form
which I can just re-read later and understand immediately
w/o re-asking. :)
