### ISSUE TITLE
Thoughts about FOSSIL driver

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#871]
Currently the effective memory impact of installing FOSSIL driver is 512 bytes which is mostly wasted in an freed env block (leaving a hole) and maintaining the PSP of the TSR.
~~~
1acd:0000 0x000d [FREE]
1adb:0000 0x0013 [FOSSIL]
~~~

In reality the driver only needs to call a dosemu helper and install a 15 byte signature / handler.
```asm
int14:                                                                          
        jmp     1f                                                              
        .byte   0,0,0,0                                                         
        .word   FOSSIL_MAGIC                                                    
maxffn:                                                                         
        .byte   FOSSIL_MAX_FUNCTION                                             
        .byte   0                                                               
1:                                                                              
        ljmp    *%cs:old14                                                      
```

 Thanks to the @ecm-pushbx ideas in https://github.com/stsp/dosemu2/issues/815#issuecomment-487407431 I have a couple of proposals.
- Repurpose the env block and no longer TSR, just terminate the program. (cost one MCB + 15 bytes in conventional memory)
  Call the dosemu helper as now.
  If I were to disassociate the env block from the FOSSIL program by tweaking its MCB and remove the reference from the PSP I could use this to store the signature/handler and resize to minimum.
  Install int14 handler.
  Print success and exit normally.

- Signature / handler block could be located in BIOS. (cost 15 BIOS bytes)
  Call the dosemu helper as now.
  Update specific fields for signature / handler in BIOS.
  Install int14 handler.
  Print success and exit normally.

So which is more attractive, use a little conventional memory when FOSSIL driver is needed with some MCB manipulation, or always steal 15 bytes of BIOS memory?

**Comment by stsp** [comment]
So we free the env but forget to
reset its pointer in psp, right? This
is a bug, but likely is a very small one
as no one would use that ptr.
Now, your idea is to move the code
to the env block and terminate the
program? Is it guaranteed that there
is enough space? Will progs like
msd/mft still display that properly?
Why do you mind a memory hole?

I won't be against a bios-based
solution of course, as we already do
the same for pkt.

**Comment by andrewbird** [comment]
> So we free the env but forget to reset its pointer in psp, right?

I hadn't noticed that bug, but yes it seems so
~~~
dosdebug> d 1adc:0000
dosdebug> 

1adc:0000 CD 20 EF 9F 00 9A F0 FE 1D F0 B4 A7 1C 08 C6 07  M o...p~.p4'..F.
1adc:0010 0C 08 47 02 1C 08 0C 08 01 01 01 00 02 FF FF FF  ..G..........
1adc:0020 FF FF FF FF FF FF FF FF FF FF FF FF CE 1A E6 FF  N.f
~~~
It's still set to `1ACE` after TSR. BTW the bug is mine as I started freeing the env block!

> Now, your idea is to move the code to the env block and terminate the program?

Yes.

> Is it guaranteed that there is enough space?

I'm not sure what the smallest possible env is in DOS as it seems to be set by a command.com command line switch `/E`. One minimum suggested on the web was 160 bytes, but with a different command.com it could be anything.

Maybe it's purely aesthetic, but holes look like wasted space as they restrict the biggest program size.

> I won't be against a bios-based solution of course, as we already do the same for pkt.

That's my preference, much as fiddling with MCB internals appeals to me personally, I think it's the more robust solution.

**Comment by stsp** [comment]
`and remove the reference from the PSP I`

So you suggested to remove the env
reference from psp, and its very strange
that you at the same time didnt notice
the bug. :)

I think command.com only passes
the _used_ env to the child, so /E
doesnt matter here, its just an upper
limit. If you dont have any envs, you
still need a space there for cmdline,
and that is a possible minimum.

I still dont understand what fiddling
with mcb internals do you mean, please
expand this part. You can usually
resize the memory blocks with dos api.

**Comment by andrewbird** [comment]
> I still dont understand what fiddling
with mcb internals do you mean, please
expand this part. You can usually
resize the memory blocks with dos api.

The env block is released when the program normally terminates (not TSR), but I wish it to remain as my new signature/isr. I need to break the association between the env block and the program so that release doesn't happen. If it's just the env reference in the PSP that's fine, but I believe the env's MCB will still have the owner PSP ID pointing to the program. @ecm-pushbx example has the env MCB being set to self own in this case, but I'm not sure if that works across all DOSs, is necessary, or enough to stop the env block being released on program termination.

In any case I'm coding something up now to move the FOSSIL signature into BIOS, it seems more robust.

**Comment by stsp** [comment]
Since we are now the masters of
the known univ...dos stack, we can
as well add the command to our
command.com to run prg w/o env.
Or alternatively you can move psp
and code to the env block and make
that psp current. Then make a dos
tsr call... no? :)

**Comment by ecm-pushbx** [comment]
> @ecm-pushbx example has the env MCB being set to self own in this case, but I'm not sure if that works across all DOSs, is necessary, or enough to stop the env block being released on program termination.

I'm not changing the env block's parent, I am changing the parent of the installed resident portion, which was allocated using 21.48. But yes, hacking the parent seems to be portable across all compatible DOS versions.

**Comment by andrewbird** [comment]
@ecm-pushbx You may have noticed I did a PR for a different solution for FOSSIL, but thanks for the clarification as I'm sure it will be useful in another instance.

**Comment by stsp** [comment]
But why not to move PSP and some code
to env seg, make that PSP current and then tsr?

**Comment by andrewbird** [comment]
Yes that would remove the hole, but in the FOSSIL case the PSP alone is bigger than the data and code that needs to stay resident - It just seems so wasteful.

**Comment by stsp** [comment]
In that case you could put the code in the
PSP's command line space.
