### ISSUE TITLE
First start please help

### ISSUE THREAD

**Issue by ThingUroboros** [stsp/dosemu2#873]
Hi a have this problems
$ dosemu
ERROR: No system files found at /usr/local/share/dosemu/fdboot
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : Adresář nebo soubor neexistuje open /dev/snd/midiC0D0 failed
ERROR: Bootable drive not found, exiting

Please do not have some startup instructions?

**Comment by stsp** [comment]
You haven't specified what exactly version you
have and from where have you got it. If you
used the packages from
https://github.com/stsp/dosemu2/releases
this shouldn't have happened, but you took
it from elsewhere.
We are working hard to allow people to use
dosemu2 installed from other sources, and
if you want, you can visit this PPA:
https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa
or build it from git branch "devel".

**Comment by ThingUroboros** [comment]
Hi sorry i download https://github.com/stsp/dosemu2.git and ./configure make make install -> i have problem. 

But when install https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa it is OK sorry.

**Comment by stsp** [comment]
You can do it the git way too, but you
need to do `git checkout devel` before
building. This will be corrected in the
future. dosemu2 is only being written.
