### ISSUE TITLE
cdrom support

### ISSUE THREAD

**Issue by ThingUroboros** [stsp/dosemu2#874]
Does the game crusader no regret work for you?
Is it also possible to connect CDROM multisession mixed data + audio TOC?

**Comment by jschwartzenberg** [comment]
It's possible that nobody seeing your message ever tested this game. In the documentation and issue tracker you see quite a few reports of games with issues, but those are exceptions. For each one that doesn't work there are maybe a 100 that run fine. It would be great if you could try the game and see if it works. I agree that having a database, especially one with screenshots, could make DOSEMU a lot more attractive.

Regarding CD-ROM emulation, be sure to use the included CD-ROM driver. This is not set up by default, but when configured properly should allow everything to work. Either in combination with a real disc or using CDEmu.

**Comment by ThingUroboros** [comment]
Don't have instructions for setting cdrom?

**Comment by ThingUroboros** [comment]
Crusader no regret demo not function for me when i start crusader.exe 
===================================================
Halted file MEMORY\CPROTMEM.C, LINE 1691
===================================================

THE same problem have old dosbox -> https://www.google.com/search?q=Halted+file+MEMORY%5CCPROTMEM.C%2C+LINE+1691&oq=Halted+file+MEMORY%5CCPROTMEM.C%2C+LINE+1691&aqs=chrome..69i57.199j0j7&sourceid=chrome&ie=UTF-8

**Comment by ThingUroboros** [comment]
When i used CDEMU -> dosemu -cdrom /dev/cdrom or /dev/sr0 in dosemu no function

G:\dir 
Volume has no label
Directory of g:\

file not found

**Comment by jschwartzenberg** [comment]
You should check out `dosemu.conf`/`.dosemurc`. There you need to specify the correct device. Also the hint there says `You need to load cdrom.sys and mscdex/nwcdex/shsucdx.exe.`, is that enough to help you further or you need more information?

**Comment by stsp** [comment]
Mount your cdrom in linux, then
specify the mount path after `-cdrom`

**Comment by jschwartzenberg** [comment]
> Mount your cdrom in linux, then
> specify the mount path after `-cdrom`

Does that allow mixed data + audio TOC to work?

**Comment by stsp** [comment]
https://github.com/stsp/dosemu2/commit/6d3935a5d17f6fc16e2ae927461f9b450274ada5
According to the log msg - yes.
I dont have a cdrom myself, but the
one should be able to check with an
image.

**Comment by stsp** [comment]
The reason of why is this possible, seems to
be because it works in conjunction with `$_cdrom`
option, which is defaulted to `/dev/cdrom`.
Which raises a few questions...
I suppose the mismatch is possible, but this
is probably not a problem: allows you to run
some game with the music from something else. :)
But how would that work with an images?

Maybe @bartoldeman can explain the current
cdrom architecture?

**Comment by stsp** [comment]
As for the game itself - its still being sold, cant get a copy.

**Comment by stsp** [comment]
I've got the game, but it can't be supported
at the moment, as it uses the unsupported
version of pharlap extender.
Even under win95 it would seem to require this
driver: http://www.cncsnw.com/pharlap3.zip
We do not support games that need a specific
drivers under win95 (AKA all games from Origin).

**Comment by stsp** [comment]
This is actuallu `RUN286` Pharlap's extender
which we don't support. Newer games that use
`RUN386` do work.

**Comment by ThingUroboros** [comment]
> Mám tu hru, ale 
> v tuto chvíli ji nelze podporovat , protože používá nepodporovanou 
> verzi pharlap extenderu. 
> Dokonce i pod win95 by to vyžadovalo tento 
> ovladač: http://www.cncsnw.com/pharlap3.zip
> Nepodporujeme hry, které potřebují specifické 
> ovladače pod win95 (AKA všechny hry od Origin).

So he wants to say if pharlap3.zip is used in win95 game would it work?

**Comment by ThingUroboros** [comment]
Funguje tedy ta cdrom nebo né? Když se připojí -cdrom přímo k tomu, aby údaje vidím ale to asi není uplně to co chci. Potřeboval bych vysvětlit co je tímto myšleno.
Musíte načíst cdrom.sys a mscdex / nwcdex / shsucdx.exe

This my config.sys

martin@martin-MS-7821:/usr/share/dosemu/dosemu2-cmds-0.2$ cat config.sys 
rem generic config.sys for DOSEMU + any DOS
rem must be edited in most circumstances
rem SWITCHES=/F
DOS=UMB,HIGH
lastdrive=Z
files=40
stacks=0,0
buffers=10
device=c:\dos\himem.sys
device=d:\dosemu\emufs.sys
device=d:\dosemu\umb.sys
devicehigh=d:\dosemu\ems.sys
devicehigh=d:\dosemu\cdrom.sys
rem uncomment to load another bitmap font (see also autoemu.bat)
rem devicehigh=c:\dos\display.sys con=(ega,,1)
rem for DR-DOS:
rem shell=command.com /e:1024 /p:autoemu.bat
rem for MS-DOS:
shell=c:\command.com /e:1024 /p /k autoemu.bat

**Comment by jschwartzenberg** [comment]
> But how would that work with an images?

When you use CDEmu, it will also provide a device below `/dev`. This device can then be set up in DOSEMU. When it gets a signal to play an audio track, CDEmu handles the playback of the audio data through ALSA/Pulseaudio.

**Comment by stsp** [comment]
> So does the cdrom or not work?

This is something we need to check (aka I have no cdrom).
The code is written, but its author @bartoldeman have not
yet commented in this thread.

> When you join -cdrom directly to see the data but it's probably
> not what I want. I need to explain what it means.

Its not only data. It should work in conjunction
with `$_cdrom` option, which is `/dev/cdrom` by default.
Then it can access everything. This is what I think
it does after looking into a code. But I haven't tested
that functionality myself (aka not supported by dosemu2 :)

> When you use CDEmu

Good point. They also provide libmirage which we can
use for the image access. But someone of course needs
to check if things work properly with cdemu, then write
the libmirage backend.
Do you volunteer for that test? :)

**Comment by ThingUroboros** [comment]
> that functionality myself (aka not supported by dosemu2 :)

what is it aka?

**Comment by stsp** [comment]
also known as

**Comment by ThingUroboros** [comment]
Please someone tried direct cdrom connection?

**Comment by stsp** [comment]
Why not you try?

**Comment by ThingUroboros** [comment]
it does not work for me.

**Comment by stsp** [comment]
All you said its "probably not what
you want". Now try again, set
`$_cdrom` properly, use -cdrom on
mount point, and express your
results clearly.

**Comment by stsp** [comment]
dont load cdrom.sys

**Comment by ThingUroboros** [comment]
I try it 
![Snímek obrazovky pořízený 2019-07-07 20-14-46](https://user-images.githubusercontent.com/20670108/60772241-e3272000-a0f3-11e9-8747-241c9c6a9a3a.png)

**Comment by ThingUroboros** [comment]
> dont load cdrom.sys

GSCDROM.sys i same or not?

In pcem emulator not problems.

**Comment by stsp** [comment]
I am from mobile now, sorry, havent
seen screenies. Will try later.

**Comment by stsp** [comment]
Normally with -cdrom you should
load no drivers at all.

**Comment by stsp** [comment]
Have you already tried cdrom.sys
(from dosemu2) and -cdrom on mount
point, and no any mscdex?

**Comment by jschwartzenberg** [comment]
Make sure that either `/dev/cdrom` exists and points to the correct device or that `/dev/sr0` is the only device in the list (if that contains your disc). Multiple CD-ROM devices will likely only work well with the `cdrom.sys` from DOSEMU.

**Comment by ThingUroboros** [comment]
martin@martin-MS-7821:~$ ls -l /dev/cdrom 
lrwxrwxrwx 1 root root 3 čec  7 19:22 /dev/cdrom -> sr0
 ?

**Comment by ThingUroboros** [comment]
Where is download MSCDEX?

**Comment by ThingUroboros** [comment]
I find this http://sophie.zarb.org/distrib/Arklinux/devel/x86_64/media/main/by-pkgid/86b0f2cff62d6947420c4cb33cafcf0a/files/30 -> To install it:

     * Create a (symbolic) link /dev/cdrom to the device file of your
       drive or use the cdrom statement in dosemu.conf to define it.
     * Make sure that you have read/write access to the device file of
       your drive, otherwise you won't be able to use the cdrom under
       Dosemu directly because of security reasons.
     * Load cdrom.sys within your config.sys file with e.g.:

        devicehigh=d:\dosemu\cdrom.sys

     * Mount the CD-ROM in Linux (some distributions do this
       automatically), and use

        lredir e: linux\fs/media/cdrom c

       to access the CD-ROM as drive E:. The "C" option specifies that
       the low-level access provided via cdrom.sys is used. Or ... start
       Microsoft cdrom extension as follows:

        mscdex /d:mscd0001 /l:driveletter

       or

        shsucdex /d:mscd0001 /l:driveletter

   To change the cd while Dosemu is running, use the DOS program
   'eject.com'. If is not possible to change the disk, when the drive has
   been opened by another process (e.g. mounted), then you need to
   unmount it first!

   Lredir has the advantage of supporting long file names, and not using
   any DOS memory, whereas MS/SHSUCDX are more low-level and perhaps more
   compatible. You would need to use a DOS TSR driver such as DOSLFN to
   use long file names with SHSUCDX.

   Remarks by zimmerma@rz.fht-esslingen.de:

   This driver has been successfully tested with Linux' SCSI CDROMS by
   the author, with the Mitsumi driver mcd.c and with the
   Aztech/Orchid/Okano/Wearnes- CDROM driver aztcd.c by me. With the
   latter CDROM-drives changing the CD-ROM is not recognized correctly by
   the drive under all circumstances and is therefore disabled. So
   eject.com will not work. For other CD-ROM drives you may enable this
   feature by setting the variable 'eject_allowed = 1' in file
   dosemu/drivers/cdrom.c (you'll find it near the top of the file). With
   the mcd.c and aztcd.c Linux drivers this may cause your system to hang
   for some 30 seconds (or even indefinitely), so don't change the
   default value 'eject_allowed = 0'.

   Support for up to 4 drives:

   If you have more then one cdrom, you can use the cdrom statement in
   dosemu.conf like this:
         $_cdrom = "/dev/cdrom /dev/cdrom2 image.iso"

   and have multiple instancies of the DOS driver:
      device=cdrom.sys
      device=cdrom.sys 2
      device=cdrom.sys 3

   The one and only parameter to the device driver is a digit between 1
   and 4, (if its missing then 1 is assumed) for the DOS devices
   MSCD0001, MSCD0002 ... MSCD0004 respectively. You then also need to
   use lredir or tell MSCDEX about these drivers such as

        lredir e: linux\fs/media/cdrom c
        lredir f: linux\fs/media/cdrom2 c 2
        lredir g: linux\fs/media/cdrom3 c 3

   where you need to loop-mount the image file, or

        mscdex /d:mscd0001 /d:mscd0002 /l:driveletter

   In this case the /l: argument defines the driveletter of the first
   /d:, the others will get assigned successive driveletters.

   History:

   Release with dosemu.0.60.0 Karsten Rucker (rucker@astro.uni-bonn.de)
   April 1995

   Additional remarks for mcd.c and aztcd.c Werner Zimmermann
   (zimmerma@rz.fht-esslingen.de) May 30, 1995

   Release with dosemu-0.99.5 Manuel Villegas Marin (manolo@espanet

**Comment by stsp** [comment]
You don't need mscdex.
I don't see your setup with cdrom.sys and -cdrom.

**Comment by stsp** [comment]
The driver name will be `MSCD0001`

**Comment by ThingUroboros** [comment]
It work!

![Snímek obrazovky pořízený 2019-07-07 22-30-17](https://user-images.githubusercontent.com/20670108/60773520-fa233d80-a106-11e9-8f00-6eb9557c5386.png)
![Snímek obrazovky pořízený 2019-07-07 22-30-30](https://user-images.githubusercontent.com/20670108/60773521-fb546a80-a106-11e9-8a45-cfb61f53a0f7.png)
![Snímek obrazovky pořízený 2019-07-07 22-31-54](https://user-images.githubusercontent.com/20670108/60773522-08715980-a107-11e9-9e06-5edead7ef2b9.png)

**Comment by stsp** [comment]
Could you please try removing cdrom.sys
and removing -cdrom (but not all together)
and see what functionality disappears by
each removal?
I suppose removing cdrom.sys will disable
audio and removing -cdrom will disable data,
but this needs to be checked.

**Comment by ThingUroboros** [comment]
But i not used -cdrom parametr

**Comment by stsp** [comment]
Do you have the cdrom drive with data then?

**Comment by ThingUroboros** [comment]
Yes data and audio both

**Comment by ThingUroboros** [comment]
I used for disk image when instaled MSDOS 6.22

**Comment by stsp** [comment]
Please remove mscdex already...

**Comment by ThingUroboros** [comment]
Can you please write more?

**Comment by stsp** [comment]
You have mscdex in autoexec.
I asked you several times to remove it,
because -cdrom should give the same
results, and we do not provide mscdex.
You can get it back later if you want, but
it would be good to test without one.

**Comment by ThingUroboros** [comment]
1. Removed mscdex in autoexec?
2. Removed parametr "$_cdrom = "/dev/sr0" with /etc/dosemu/dosemu.conf
3. Used parametr dosemu -cdrom /dev/sr0 ?

**Comment by stsp** [comment]
3. `dosemu -cdrom /mnt/cdrom` (or where have you mounted it)

**Comment by ThingUroboros** [comment]
Ok wait pls

**Comment by stsp** [comment]
Could you please give me a link to the
cd image that you play music with DN?

**Comment by ThingUroboros** [comment]
dosemu -cdrom /media/martin/990119_1039/ -> when is not i removed mscdex == > audio data is OK
and uncomment in 
![Snímek obrazovky pořízený 2019-07-07 22-54-45](https://user-images.githubusercontent.com/20670108/60773753-399f5900-a10a-11e9-878e-42111cef869c.png)

**Comment by ThingUroboros** [comment]
I have to many CDROM iso Spellcross and Earth2140 i used cdemu load

**Comment by ThingUroboros** [comment]
https://archive.org/download/Spellcross_Posledni_Bitva_Cauldron_1997

**Comment by ThingUroboros** [comment]
I have removed mscdex in autoexec and i used this -> lredir e: linux\fs/media/cdrom c?

**Comment by stsp** [comment]
Does it play something audible for you?

**Comment by ThingUroboros** [comment]
> Does it play something audible for you?

Yes

**Comment by ThingUroboros** [comment]
@stsp I tried it now but nothing audible is playing. :/ It used to work

**Comment by stsp** [comment]
Please open a new ticket with a full
explanation of what you do and what
fails. All those lredir things that I can
see here, may no longer work.
