### ISSUE TITLE
cdrom.sys doesn't load if no cdrom drive

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#886]
**Describe the bug**
```
dosemu CDROM driver installed (V0.2)


Access to cdrom denied.
Installation aborted.
```

**To Reproduce**
Just start dosemu2 when cdrom is unavailable.

It should instead load and check the cdrom
only when accessed by the DOS prog.

**Comment by jschwartzenberg** [comment]
Do you mean whether a drive is present or whether a disc is present? `cdrom.sys` supports up to four drives if I remember correctly.

**Comment by stsp** [comment]
I don't have cdrom, so maybe indeed this
is a problem and not a missing disk.
But most people don't have it either, and
seeing the error msg on start-up is wrong.
So something must be done.

**Comment by stsp** [comment]
The drive can actually appear at any point
of time (when you load cdemu), so it would
be better to always load the DOS driver and
defer the drive check to the use time.
Which will mean no cdrom drive and no disk
is the same thing.
