### ISSUE TITLE
Dosdebug 'bl' list breakpoints with mangled addresses

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#89]
Set a breakpoint using segment:offset
~~~
bp 1fe0:7DEA
~~~
List breakpoints (but address is mangled - possibly linear version)
~~~
bl
Breakpoints:
0: 00027bea
~~~

The breakpoint stops at the correct place, so presumably the problem is in the break point list display
~~~
g
Trap 3, system state: stopped
AX=0020  BX=0000  CX=0004  DX=0080  SI=0256  DI=0000  SP=7b9e  BP=7c00
DS=1fe0  ES=0470  FS=0000  GS=0000  FL=000a3246
CS:IP=1fe0:7dea       SS:SP=1fe0:7b9e

1fe0:7dea C3               ret
~~~

**Comment by stsp** [comment]
Yes, linear version.
Feel free to send the patch improving this.

**Comment by andrewbird** [comment]
Should the format follow the setting of the mode command, i.e. (0=SEG16, 1=LIN32, 2=UNIX32) ?

**Comment by stsp** [comment]
Would be good, but for "bl" the mode is simply
not supported. It will require a bit of code shuffling
to remember the breakpoint as seg:off and call
mhp_getadr() later.

**Comment by andrewbird** [comment]
I suppose also, that in DOS the same breakpoint address could be made by a number of seg:offset addresses. Meaning that when the breakpoint is hit or listed,  reversing the address into the DOS one that the user expects is not possible.

**Comment by stsp** [comment]
That's why you need to remember it as a seg:off
initially. As in far_t type
