### ISSUE TITLE
Scott Pitcher's ne2000 emulator

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#892]
20 years ago Scott Pitcher wrote the ne2000
emulator for dosemu-0.98.5.
Lets keep it here so that it won't be lost forever
(spent ~2 hours searching).
Someone should take a look at how difficult
would it be to port that for dosemu2.
[dosemu-ne2000.tar.gz](https://github.com/stsp/dosemu2/files/3473442/dosemu-ne2000.tar.gz)

**Comment by stsp** [comment]
> Someone should take a look

Not me as I am only interested in fdpp development
these days and for upcoming years.
Someone else should. :)

**Comment by jschwartzenberg** [comment]
The main benefit would be support for more networking stacks I guess? Like Microsoft's in WfW 3.11?

**Comment by andrewbird** [comment]
Yep, this find of Stas's is a direct result of my badgering him about getting the MS networking client for DOS working somehow.

**Comment by jschwartzenberg** [comment]
Is there any special reason you'd like that working? :)

**Comment by stsp** [comment]
> MS networking client for DOS working somehow.

Is there any special reason you'd like that working not with IPX?

**Comment by andrewbird** [comment]
At this point any tool that installs a redirector and uses int21/5f02 to list the mapped drives is useful to me. I'll try ipx which should at least allow the int21/5f02 to be called, but to actually map drives I'll need TCP/IP as Samba can only use that and I have no windows machines for IPX.

**Comment by stsp** [comment]
And you can't use geos for that because it
crashes? How about dealing with geos crash
instead?

**Comment by andrewbird** [comment]
Apart from the crash, pcgeos is uninteresting as it doesn't use signature or userdata values. I'm looking for additional data points from other redirectors to confirm RBIL as it's a little woolly around this subject.

**Comment by stsp** [comment]
If the crash is fdpp-specific, it would still be
good to get it fixed.

**Comment by andrewbird** [comment]
Did you sign up at bluewaysw.de for a licence key for Breadbox Ensemble? If not, mine took over a week so perhaps get it underway.

**Comment by stsp** [comment]
I have no idea what are you talking about.
@bolle732 gave me geos and that I run.

**Comment by andrewbird** [comment]
Until the open source version is buildable, the new owners are offering a license key for the last release of the commercial version just by registering at https://blog.bluewaysw.de/

**Comment by stsp** [comment]
I've heard its already buildable.

**Comment by stsp** [comment]
> registering at https://blog.bluewaysw.de/

This page says Hello World.

**Comment by andrewbird** [comment]
Yep, you have to register. Once done, and then when the admin notices your personal license key gets added to the MyGEOS page.

**Comment by andrewbird** [comment]
> I've heard its already buildable.

I don't believe so, but I didn't try see https://github.com/bluewaysw/pcgeos/issues/58

**Comment by stsp** [comment]
21feb and we are in aug already.

**Comment by andrewbird** [comment]
I have the ne2000 emulator building and a little success https://github.com/andrewbird/dosemu2/tree/ne2000-01

1/ dosemu will startup and the emulator is good enough for msclient 3.11 networking to be able to start happily. Can now use the `NET USE` command to list redirected drives.
2/ Can see arp request generated by tcptsr load leave `tap1` to go across the bridge
~~~
1949 5183.280045111 Xerox_61:60:59 → Broadcast    ARP 60 Gratuitous ARP for 192.168.123.25 (Request)
~~~
3/ Now calling a function on data ready to receive. Need to flesh this out to inject packets into the ne2000 virtual driver.

So now i need a little help.
1/ Am I right to implement this using just the TAP interface? Will it transport all the packet types that we can expect?
2/ How do I inject the packets back into the virtual driver?
3/ Not really sure about the Interrupt handling, what I've cobbled together by looking at packet driver seems to have some similar looking functions.

**Comment by stsp** [comment]
Wow, that's a fantastic news indeed!
One of those most-missing things. :)

> 1/ Am I right to implement this using just the TAP interface?

I don't think so, why don't you just use the libpacket API?

> Will it transport all the packet types that we can expect?

It should.

> 2/ How do I inject the packets back into the virtual driver?

What do you mean? What is "virtual driver"?
Do you want to it be used somehow by dosemu's
packet driver?

> 3/ Not really sure about the Interrupt handling, what I've cobbled
> together by looking at packet driver seems to have some similar looking functions.

Not sure what you mean here, but I suppose if you
already do "net start", then you got the IRQ bits right?

**Comment by andrewbird** [comment]
> I don't think so, why don't you just use the libpacket API?

So libpacket API is generic, not specific to pktdriver then?

> What do you mean? What is "virtual driver"?

Crap terminology, should be virtual hardware.

> Do you want it to be used somehow by dosemu's
packet driver?

No it's just that Scott stopped writing it before he wrote the receive path, probably because of the lack of response from people.  He mentions in the readme that he tested using `net send`, which I believe is a broadcast only. So currently in my example the emulator can send an ARP request for the client but has no method of passing the response back to the client.

So the upshot is that `net start` says 'already started' but some of the utilities are tricked into believing it's working anyway, probably because they don't do any round trip test.

I'm looking to write a function that's the opposite of `ne2000_do_xmit()`

**Comment by stsp** [comment]
> So libpacket API is generic, not specific to pktdriver then?

Of course! Its just that currently the pktdriver is its only user.

> I'm looking to write a function that's the opposite of ne2000_do_xmit()

So what is the question exactly?
The generic procedure (w/o looking into Scott's code) is:
- Get the ioselect notification that the data arrived
- Read that data from socket and put into the receive
page, offseted by the current write pointer
- Call irq

**Comment by andrewbird** [comment]
So it looks like I'm missing step 2. I'll investigate.

**Comment by andrewbird** [comment]
Fleshed out the receive path and whilst I can see the packets as I process them, I don't see any activity from the DOS side. I wonder if I'm generating the interrupt properly, this is what I have
https://github.com/andrewbird/dosemu2/blob/99bbb0c8493ff657fb96949fec8500259f69513a/src/dosext/net/ne2000.c#L437
I see this in the log, so it looks like I'm misguided. How should I generate the DOS interrupt as if a network card did it?
~~~
NE2000: Interrupt activated.
NE2000: ne2000_irq_callback() called.
NE2000: ne2000_receive_req_async() called
NE2000: ne2000_ether_recv() read 42 bytes
NE2000: dest[ff,ff,ff,ff,ff,ff]
         src[02,72,d0,e9,74,98]
        prot[08,06]
DEBUG: do_8390_irq() called
DEBUG:   if(!in_reset && irq_bit) was true
DEBUG:    if((irq_bit & d8390_imr) != 0 ) was true
NE2000: Activating irq
NE2000: Interrupt activated.
NE2000: ne2000_irq_callback() called.
NE2000: Interrupt activated.
NE2000: ne2000_irq_callback() called.
~~~

**Comment by stsp** [comment]
Its in pic_seti().
You simply don't need to use the "callback" argument.
Its for driver-devices, like int33-mouse or pkt.
As for check_receive arg, you don't need to use
it either, its just a "last point" where the IRQ can
be cancelled.
I pretty much think pic_seti() should only have 1
argument, but I won't spend time on rewriting
that crap. :)

**Comment by stsp** [comment]
So any progress with the above suggestion?

**Comment by andrewbird** [comment]
Yes seems better, thanks. I'm not there yet, though!

**Comment by andrewbird** [comment]
I seem to be having problems even in the transmit path with random loops and stalls. So I'm going to try a slightly different tack. Since there are vary many similarities between Scott's ne2000 and the one in qemu, it looks to me like they share a common parent. I'm going to start again by taking the current qmu [ne2000.c](https://github.com/qemu/qemu/blob/master/hw/net/ne2000.c) and bolt on Scott's Dosemu integration and our changes to that. At least that way I know we are starting from a known good implementation that's currently maintained. The licence for qemu's ne2000 seems to be GPLv2+, is there any reason this wouldn't be an acceptable course of action?

**Comment by andrewbird** [comment]
Actually, please read the header in qemu's ne2000.c, I'm not sure if that qualifies as a licence, if it does then it seems it's more permissive than the default GPLv2+.

**Comment by stsp** [comment]
> Actually, please read the header in qemu's ne2000.c

Looks MIT to me, should be perfectly valid and GPL-compatible.
Also see LICENSE:
```
1) QEMU as a whole is released under the GNU General Public License,
version 2.

2) Parts of QEMU have specific licenses which are compatible with the
GNU General Public License, version 2.
```
Which is quite bad. We do not accept v2.
Not sure actually.
I think we have a problem here, but OTOH I would
be surprised Scott could base his code on qemu, as
qemu probably did not exist back then.

**Comment by stsp** [comment]
https://svnweb.freebsd.org/socsvn/soc2015/iateaca/bhyve-ne2000-head/usr.sbin/bhyve/ne2000.c?revision=290045&view=markup

**Comment by andrewbird** [comment]
That licence statement's intent is unclear to me as also in the section 2 it shows
> Source files with no licensing
information are released under the GNU General Public License, version
2 or (at your option) any later version.

We have a statement in the ne2000.c file that appears to be MIT, so from my limited understanding it seems that the code in question is MIT if the file based statement is vaiid or if not GPLv2.

Yes I also saw the dates, but I figure that qemu and Scott's ne2000 have a common parent.

**Comment by jschwartzenberg** [comment]
Usually GPLv2 means GPLv2 or later when you look at the details. (One notable exception is Linux.)

**Comment by andrewbird** [comment]
It seems VirtualBox used qemu's https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Devices/Network/ne2000.c?rev=1076

**Comment by stsp** [comment]
> MIT if the file based statement is vaiid or if not GPLv2.

I don't see what you mean by that.
The statement you quoted, is only about the source files
with no license. The source file we look in, is MIT, so the
statement doesn't apply.

> Usually GPLv2 means GPLv2 or later when you look at the details.

No, qemu seems to be very explicit on being version 2.
For example,
```
As of July 2013, contributions under version 2 of the GNU General Public
License (and no later version) are only accepted for the following files
or directories:
```
Which means before 2013 it was entirely v2.

**Comment by stsp** [comment]
> It seems VirtualBox used qemu's

```
you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation,
in version 2 as it comes
```

Does not work.

**Comment by stsp** [comment]
https://git.greensocs.com/qemu/qbox/commit/8571fa57cd0426f40629ab77444704745631f168

Please use ne2k sources prior to this commit as
it fixes the license to v2. Of course it doesn't hurt
to later see the diff to make sure nothing critical is
omitted. :)

**Comment by jschwartzenberg** [comment]
> > Usually GPLv2 means GPLv2 or later when you look at the details.
> 
> No, qemu seems to be very explicit on being version 2.
> For example,
> 
> ```
> As of July 2013, contributions under version 2 of the GNU General Public
> License (and no later version) are only accepted for the following files
> or directories:
> ```
> 
> Which means before 2013 it was entirely v2.

From the same file:
```
Source files with no licensing information are released under the GNU General Public License, version 2 or (at your option) any later version.
```

So I guess they don't want GPLv3 only contributions, but they are still looking for GPLv2+ ones.

**Comment by stsp** [comment]
Please see the commit I referenced above.
It clearly states v2 only.
There are not many sources "with no licensing information"
and I am not even sure why this phrase bothers both you
and Andrew - it is absolutely irrelevant to ne2000.c file because
it does have the license information.

**Comment by andrewbird** [comment]
So are you saying that this file is pure MIT, except commits to it afher your referenced commit which are GPLv2 only?

**Comment by andrewbird** [comment]
The strange thing is that commit https://github.com/qemu/qemu/commit/8571fa57cd0426f40629ab77444704745631f168 references directories that the ne2000.c doesn't live in (master/hw/net/ne2000.c), so surely the MIT licence inside it prevails? Its commit message is more indicative of the intent of these licence clarifications and suggests that the GPLv2 only directories are those that contain Linux kernel derived code.

**Comment by stsp** [comment]
> So are you saying that this file is pure MIT, except commits to it afher
> your referenced commit which are GPLv2 only?

No.
I _think_ that we can assume v2+ before that commit.
That commit actually says exactly that: w/o explicit
statement you can assume that. So we do.

> The strange thing is that commit qemu/qemu@8571fa5 references
> directories that the ne2000.c doesn't live in (hw/net/ne2000.c), 

No, that's not the point either.
The point is:
```
1) QEMU as a whole is released under the GNU General Public License,
version 2.
```
Oops.

> more indicative of the intent of these licence clarifications and suggests that the GPLv2 only 

It says about the project in whole, and that's the
main problem.

**Comment by andrewbird** [comment]
I'm happy to go with anything you see fit, but I fail to see how "releasing a project as a whole as gplv2" can have any effect on a file specifically licensed as MIT, unless it's only the changes donn afterwards to it. I suppose that's why I'm no lawyer.
Anyway I'll  start from the commit immediatly prior to the licence restatement.

**Comment by stsp** [comment]
> have any effect on a file specifically licensed as MIT, unless it's only the changes done afterwards to it.

This is how I understand the "GPL infecting process".
When you release some project under GPL, GPL subdues
all the licenses that are compatible with it and removes
all that are incompatible. When you commit something
under GPL to some file, GPL also subdues the original
license of that file. You still need to mention the original
licenses, but mainly for historical reasons - they
are all "infected". At least that's my understanding.

In any case, if we can just go before the problematic
commit of qemu, why not to do just that. I do not suppose
that there were too many ne2k fixes recently anyway.
And if we go before that commit, then the only possible
options are either gplv2+ or MIT, depending on whether
my or your understanding is right. But both cases are
acceptable, so this looks like the safest bet.

**Comment by ecm-pushbx** [comment]
> This is how I understand the "GPL infecting process".
> When you release some project under GPL, GPL subdues
> all the licenses that are compatible with it and removes
> all that are incompatible. When you commit something
> under GPL to some file, GPL also subdues the original
> license of that file. You still need to mention the original
> licenses, but mainly for historical reasons - they
> are all "infected". At least that's my understanding.

IANAL, but when a portion of a work is released under GPL-compatible usage conditions, and these original conditions are preserved for that portion (file), then I think you are free to use the portion under either the GPL (whichever version is applicable) or the original conditions.

**Comment by stsp** [comment]
> but when a portion of a work is released under GPL-compatible usage conditions,
> and these original conditions are preserved

I can't parse this.
You mention releasing under GPL and preserving
it. Not sure where is the second licence in your phrase.

**Comment by ecm-pushbx** [comment]
https://github.com/qemu/qemu/blob/master/hw/net/ne2000.c has a MIT like license at the top of the file. It doesn't matter that it is shipped as part of a GPLed project, it is still valid to use it under the license provided at the top. That's because the original conditions (MIT like) are preserved for this file, so it is valid both under GPL (as the entire project is) or under MIT (as the single file is).

**Comment by stsp** [comment]
OK, noted as your understanding of the situation.
Unfortunately we can't rely on any one's understanding
(either mine or yours) so I propose the safe bet to
just use the older versions that would be acceptable
in either case.

**Comment by stsp** [comment]
https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#GPLIncompatibleAlone
---
 If a program P is released under the GPL that means any and every part of it can
 be used under the GPL. If you integrate module Q, and release the combined program
 P+Q under the GPL, that means any part of P+Q can be used under the GPL. One part
 of P+Q is Q. So releasing P+Q under the GPL says that Q any part of it can be used
 under the GPL. Putting it in other words, a user who obtains P+Q under the GPL can
 delete P, so that just Q remains, _still under the GPL_.
---

**Comment by stsp** [comment]
https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html
```
Whenever possible, the stewards of the codebase should consult with a lawyer to be sure that the file is sufficiently independent of and distinct from the core of the GPL’d project to permit continued licensing of the file under the permissive terms despite the application of the GPL to the project as a whole. 
````

So basically no, that doesn't work.
The "GPL infecting" process seems to work roughly
as I described above. No dial-licensing is (easily) possible.

**Comment by andrewbird** [comment]
Okay, I'm convinced using the old version is the only way to proceed, but a little intrigued nonetheless.

**Comment by andrewbird** [comment]
These look like the only material commits we might want to reimplement:
https://github.com/qemu/qemu/commit/fdc89e9
https://github.com/qemu/qemu/commit/415ab35
https://github.com/qemu/qemu/commit/aa7f996
https://github.com/qemu/qemu/commit/737d2b3 (CVE)
https://github.com/qemu/qemu/commit/9bbdbc6 (CVE)

**Comment by stsp** [comment]
Either reimplement (for 1-2-liners), or just ask
the contributors if they allow us to apply them
to the gplv2+ code.
But they are not show-stoppers.
I think we need to get it working first, then see.

**Comment by ecm-pushbx** [comment]
>  Putting it in other words, a user who obtains P+Q under the GPL can
>  delete P, so that just Q remains, _still under the GPL_.

This doesn't mean Q is forced to be GPL-licensed if it is also provided with some other conditions. It just means if Q is GPL-compatible, and shipped as part of a GPL project (P+Q), then it is valid to re-use only Q under the GPL. It does not exclude the other case.

Also from your link https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html :

> In addition to respecting the rights of the permissive licensor, preservation of notices on parts
> added to a GPL’d project may facilitate extraction of those parts by downstream users so that
> they may be used under the permissive terms instead of the GPL.

**Comment by andrewbird** [comment]
Okay I pushed what I have so far. https://github.com/andrewbird/dosemu2/tree/ne2000-02

I can see the initial Gratuitous ARP packet leave when tcptsr is loaded, but no response (there shouldn't be unless we have a duplicate). but subsequent pings out to 192.168.123.1 show nothing. I would expect to at least see a plain ARP request for the target.

Here's my installed client directory which you should install to `c:\net`, then run startnet.bat and finally tcptsr. [msnet-installed.tar.gz](https://github.com/stsp/dosemu2/files/3529621/msnet-installed.tar.gz)

My local network is setup as follows
~~~
tunctl -u ajb -t tap0
tunctl -u ajb -t tap1
ip tuntap list
ifconfig tap0 0.0.0.0 promisc up
ifconfig tap1 0.0.0.0 promisc up
brctl addif virbr0 tap0
brctl addif virbr0 tap1
brctl stp virbr0 off
brctl show virbr0
~~~
which connects tap1 to the kvm bridge on my machine, I also flush the firewall for now.
~~~

root@polly:~# brctl show virbr0
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.525400e83d3c	no		tap0
							tap1
							virbr0-nic
root@polly:~# ifconfig virbr0
virbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.123.1  netmask 255.255.255.0  broadcast 192.168.123.255
        ether 52:54:00:e8:3d:3c  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 138 (138.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 17  bytes 714 (714.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@polly:~# ifconfig tap1
tap1: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet6 fe80::9871:a6ff:fef4:cffb  prefixlen 64  scopeid 0x20<link>
        ether 9a:71:a6:f4:cf:fb  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 180 (180.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22  bytes 1224 (1.2 KB)
        TX errors 0  dropped 2 overruns 0  carrier 0  collisions 0
~~~

~~~
C:\net>C:\NET\net initialize
Microsoft NE2000 NDIS Driver
Copyright 1992 Microsoft Corporation
All Rights Reserved Version:  2.0
Microsoft DOS TCP/IP Protocol Driver 1.0a
Copyright (c) Microsoft Corporation, 1991.  All rights reserved.
Copyright (c) Hewlett-Packard Corporation, 1985-1991.  All rights reserved.
Copyright (c) 3Com Corporation, 1985-1991.  All rights reserved.
Microsoft DOS TCP/IP NEMM Driver 1.0
The command completed successfully.
C:\net>C:\NET\netbind.com
MS-DOS LAN Manager v2.1 Netbind
C:\net>C:\NET\umb.com
C:\net>rem C:\NET\tcptsr.exe
C:\net>rem C:\NET\tinyrfc.exe
C:\net>rem C:\NET\nmtsr.exe
C:\net>rem C:\NET\emsbfr.exe
C:\net>rem C:\NET\net start
C:\net>tcptsr
Microsoft DOS TCP/IP 1.0a
C:\net>ping 192.168.123.1
Copyright (c) Microsoft Corporation, 1991-1993.  All rights reserved.
Copyright (c) Hewlett-Packard Corporation, 1985-1993.  All rights reserved.
Copyright (c) 3Com Corporation, 1985-1993.  All rights reserved. 
[1] No response from 192.168.123.1 
~~~

tshark -i tap1
~~~
   28 2016.307276619 9a:71:a6:f4:cf:fb → Broadcast    ARP 60 Gratuitous ARP for 192.168.123.25 (Request)
~~~

and the log 
[test.log.gz](https://github.com/stsp/dosemu2/files/3529665/test.log.gz)

I'm not convinced that I have the interrupt connected properly.

**Comment by stsp** [comment]
> Also from your link https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html

You are quoting the summary here.
This is the informative part that just briefly
describes what the _normative_ part will later
explain in details. And indeed, the normative
part later explains how exactly the "preservation
of notices" _may_ (the word "may" is important,
don't confuse it with "should")
"facilitate extraction of those parts".
It presents the exact process of doing so,
which, in case of qemu, was not done. It also
explains very clearly that "preservation of notices"
is a pre-condition in that process, but is far from
being enough by itself.
Again, just my understanding. I really tried
to talk to lawers on that, but, as least in our
company, they are chicken to talk about
anything that looks remotely complex to them...
(which is strange, considering how large and
famous the company is)

**Comment by stsp** [comment]
> I'm not convinced that I have the interrupt connected properly.

Maybe you just don't update them properly?
I only briefly looked at what you do, and I wonder
about this part:
```
    if (s->rcnt <= len) {
        s->rcnt = 0;
        /* signal end of transfer */
        s->isr |= ENISR_RDC;
        ne2000_update_irq();
    } else {
        s->rcnt -= len;
}
```

Why no `ne2000_update_irq();` after decrement
of `rcnt`?
In any case, you can use the `+r` log channel to
log the IRQ events.

**Comment by andrewbird** [comment]
I made as few changes to the qemu source as possible and tried to mould the integration into Dosemu changes, so the logic there was as qemu. That said, I missed that the IRQ should be conditionally triggered see 4314fc1. Things are looking better now for send, this is from `tcptsr` followed by `ping 192.168.123.1`.
~~~
   30 6677.139305099 Xerox_f4:cf:fb → Broadcast    ARP 60 Gratuitous ARP for 192.168.123.25 (Request)
   31 6677.666522598 Xerox_f4:cf:fb → Broadcast    ARP 60 Gratuitous ARP for 192.168.123.25 (Request)
   32 6678.215750921 Xerox_f4:cf:fb → Broadcast    ARP 60 Gratuitous ARP for 192.168.123.25 (Request)
   33 6696.776433592 Xerox_f4:cf:fb → Broadcast    ARP 60 Who has 192.168.123.1? Tell 192.168.123.25
   34 6696.776470934 RealtekU_e8:3d:3c → Xerox_f4:cf:fb ARP 42 192.168.123.1 is at 52:54:00:e8:3d:3c
~~~

Now to work out why the ARP response didn't generate further traffic
~~~
NE2000: ne2000_io_write8() 0, 0x26                                              
NE2000: ne2000_write()                                                          
NE2000: ne2000_ioport_write()                                                   
NE2000: write addr=0x0 val=0x26                                                 
NE2000: ne2000_ether_send(0x871c94c, 60)                                        
NE2000: dest[ff,ff,ff,ff,ff,ff]                                                 
         src[00,00,01,f4,cf,fb]                                                 
        prot[08,06]                                                             
NE2000: Set IRQ to 1 (42 1f)                                                    
NE2000: ne2000_activate_irq                                                     
~~~
~~~
NE2000: ne2000_receive_req_async() called                                       
NE2000: ne2000_ether_recv() read 42 bytes                                       
NE2000: dest[00,00,01,f4,cf,fb]                                                 
         src[52,54,00,e8,3d,3c]                                                 
        prot[08,06]                                                             
NE2000: ne2000_receive()                                                        
NE2000: received len=42                                                         
NE2000: ne2000_buffer_full()                                                    
NE2000: Set IRQ to 1 (43 1f)                                                    
NE2000: ne2000_activate_irq                                                     
NE2000: ne2000_irq_trigger()                                                    
~~~

Perhaps the ARP response is seen as a runt, according to the log it's only 42 bytes.

**Comment by andrewbird** [comment]
Just to see I tried mTCP with ne2000.com packet driver over new ne2000 emulation and managed to get a DHCP address. Here's the tshark log
~~~
   63 11147.455267881      0.0.0.0 → 255.255.255.255 DHCP 305 DHCP Discover - Transaction ID 0xbb1c0000
   64 11147.455573640 192.168.123.1 → 192.168.123.70 DHCP 342 DHCP Offer    - Transaction ID 0xbb1c0000
   65 11147.464546011      0.0.0.0 → 255.255.255.255 DHCP 312 DHCP Request  - Transaction ID 0xbb1c0000
   66 11147.464744349 192.168.123.1 → 192.168.123.70 DHCP 348 DHCP ACK      - Transaction ID 0xbb1c0000
~~~

**Comment by andrewbird** [comment]
So I think there's still something wrong with irq handling. The qemu code used to call a function called `qemu_set_irq(irq, level)` I'm not sure how to replace that with `pic_request()`?

**Comment by stsp** [comment]
Likely just call it from more places, like
after decrementing rcnt.
If any case, as a test you can raise that
irq periodically from the timer. If that
improves something, then you are on a
right track.

**Comment by andrewbird** [comment]
The thing is the problem got much better when I made the call conditional on level, i.e. it was called less often. But it seems like `qemu_set_irq(irq, level)` was enabling and disabling, rather than triggering a service request. Perhaps that's the answer run a function from a timer, but only proceed to call `pic_request()` within it if level is 1.

Off to bed now, will try again tomorrow.

**Comment by stsp** [comment]
Sure it must be conditional.
You can also call `pic_untrigger()` if level is 0.
(but this won't solve any problem)

**Comment by andrewbird** [comment]
Seems to be working fine now with mTCP + real packet driver
~~~
C:\mtcp>dhcp
mTCP DHCP Client by M Brutman (mbbrutman@gmail.com) (C)opyright 2008-2015
Version: Jul  5 2015
 
Timeout per request: 10 seconds, Retry attempts: 3
Sending DHCP requests, Press [ESC] to abort.
 
DHCP request sent, attempt 1: Offer received, Acknowledged

Good news everyone!
 
IPADDR 192.168.123.139
NETMASK 255.255.255.0
GATEWAY 192.168.123.1
NAMESERVER 192.168.123.1
LEASE_TIME 3600 seconds
 
Settings written to 'c:\mtcp\mtcp.cfg'
C:\mtcp>ping 192.168.123.1
 
mTCP Ping by M Brutman (mbbrutman@gmail.com) (C)opyright 2009-2015
Version: Jul  5 2015
 
ICMP Packet payload is 32 bytes.
 
Packet sequence number 0 received in 0.00 ms, ttl=64
Packet sequence number 1 received in 0.00 ms, ttl=64
Packet sequence number 2 received in 0.00 ms, ttl=64
Packet sequence number 3 received in 0.00 ms, ttl=64
 
Packets sent: 4, Replies received: 4, Replies lost: 0
Average time for a reply: 0.00 ms (not counting lost packets)
~~~

~~~
  123 3145.034430495      0.0.0.0 → 255.255.255.255 DHCP 305 DHCP Discover - Transaction ID 0xd47c0000
  124 3145.034645947 192.168.123.1 → 192.168.123.139 DHCP 342 DHCP Offer    - Transaction ID 0xd47c0000
  125 3145.042655890      0.0.0.0 → 255.255.255.255 DHCP 312 DHCP Request  - Transaction ID 0xd47c0000
  126 3145.042814710 192.168.123.1 → 192.168.123.139 DHCP 348 DHCP ACK      - Transaction ID 0xd47c0000
  127 3150.163993677 RealtekU_e8:3d:3c → Xerox_95:41:d0 ARP 42 Who has 192.168.123.139? Tell 192.168.123.1
  128 3151.187989703 RealtekU_e8:3d:3c → Xerox_95:41:d0 ARP 42 Who has 192.168.123.139? Tell 192.168.123.1
  129 3152.211992462 RealtekU_e8:3d:3c → Xerox_95:41:d0 ARP 42 Who has 192.168.123.139? Tell 192.168.123.1
  130 3308.019565328 Xerox_95:41:d0 → Broadcast    ARP 60 Gratuitous ARP for 192.168.123.139 (Request)
  131 3308.483902718 Xerox_95:41:d0 → Broadcast    ARP 60 Who has 192.168.123.1? Tell 192.168.123.139
  132 3308.483930694 RealtekU_e8:3d:3c → Xerox_95:41:d0 ARP 42 192.168.123.1 is at 52:54:00:e8:3d:3c
  133 3308.488736348 192.168.123.139 → 192.168.123.1 ICMP 74 Echo (ping) request  id=0x4860, seq=0/0, ttl=255
  134 3308.488777588 192.168.123.1 → 192.168.123.139 ICMP 74 Echo (ping) reply    id=0x4860, seq=0/0, ttl=64 (request in 133)
  135 3309.564895274 192.168.123.139 → 192.168.123.1 ICMP 74 Echo (ping) request  id=0x4860, seq=1/256, ttl=255
  136 3309.564949069 192.168.123.1 → 192.168.123.139 ICMP 74 Echo (ping) reply    id=0x4860, seq=1/256, ttl=64 (request in 135)
  137 3310.590111096 192.168.123.139 → 192.168.123.1 ICMP 74 Echo (ping) request  id=0x4860, seq=2/512, ttl=255
  138 3310.590165363 192.168.123.1 → 192.168.123.139 ICMP 74 Echo (ping) reply    id=0x4860, seq=2/512, ttl=64 (request in 137)
  139 3311.615353783 192.168.123.139 → 192.168.123.1 ICMP 74 Echo (ping) request  id=0x4860, seq=3/768, ttl=255
  140 3311.615408302 192.168.123.1 → 192.168.123.139 ICMP 74 Echo (ping) reply    id=0x4860, seq=3/768, ttl=64 (request in 139)
  141 3313.491996315 RealtekU_e8:3d:3c → Xerox_95:41:d0 ARP 42 Who has 192.168.123.139? Tell 192.168.123.1
  142 3314.516001177 RealtekU_e8:3d:3c → Xerox_95:41:d0 ARP 42 Who has 192.168.123.139? Tell 192.168.123.1
  143 3315.539995072 RealtekU_e8:3d:3c → Xerox_95:41:d0 ARP 42 Who has 192.168.123.139? Tell 192.168.123.1
~~~

**Comment by andrewbird** [comment]
But still misbehaving with MSclient, sadly!

**Comment by stsp** [comment]
Your patch generates an extra pic requests,
and for that it helps. This is what I asked to check,
but you could check also other things, like calling
the update func after rcntr decrement.

Also please move it to `dev/ne2k`. `dosext` is
meant for extending DOS interrupts, which is
what pkt driver does but not ne2k.

**Comment by andrewbird** [comment]
> This is what I asked to check,
but you could check also other things, like calling
the update func after rcntr decrement.

Yes I know, I'm not ignoring this, but it's something I'm trying to delay doing as I figure the qemu logic must work fine and the problem must lie in how I'm connecting it up to dosemu.

> Also please move it to dev/ne2k.

Okay will do.

**Comment by andrewbird** [comment]
I redid the series, mainly to minimise the changes from std qemu. I also changed the location to base/dev/ne2k etc. I make a draft PR that you can update etc. If you have little time, could you try to fix the issue for msclient?

**Comment by stsp** [comment]
Well, don't you think its a bit impolite to ask me
to fix this, before at least checking what I already
asked to check? :)
(which costs just ~2 minutes)
Also, please give a small summary (either here
or in a log msgs):
Have you replaced the Scott's code with qemu's,
or just took the receive part that was not written,
or something in between? It would be nice (although
optional) to have the initial commit of just importing
the Scott's code, unless you later replaced it
completely. Which I think is what you actually did.

**Comment by andrewbird** [comment]
Sorry, I didn't mean to be impolite, I'm struggling a bit and imagined you'd fix it in 30 seconds. Will check what you asked  later. No this is a pure import of the qemu code from the commit you specified then I added build method, took away all the unnecessary stuff, added in the iodevice setup and send  path from Scott. Then I added the receive stuff myself.

**Comment by andrewbird** [comment]
See the draft PR #912 as now it seems that having more pic_requests() seems to make it worse.

**Comment by stsp** [comment]
Yes, this may be the right change, but the
fact that it "fixes" something indicates that
some status registers are probably not up-to-date
when IRQ handler works. Because the same
check you do now, should also be done by
the irq handler itself.
It would be nice to decorate all register reads
and writes with proper log prints, so it is clear
what exactly the DOS isr does and expects.
Maybe instead of "isr" register, it checks for
the read and write pointers to match, or
something like that.

**Comment by andrewbird** [comment]
Yes, Scott's emulator had all the reads/writes split out for printfs, but it really did increase code size. I'll see what I can do.

**Comment by jschwartzenberg** [comment]
Once this is merged, maybe there should be an init script that sets up a network interface to let things work out of the box. It seems easier to do that than to support vde2.

**Comment by stsp** [comment]
Maybe but quite unlikely.
It will require root and depends on the
firewall settings.
The best bet is to use libslirp.

**Comment by jschwartzenberg** [comment]
Yes, but `make install` already requires root. `make install` could just additionally install a systemd/init script that sets this up. This is what all similar software does.

**Comment by stsp** [comment]
How will you resolve the case if
tap0 is already allocated by "similar
software"? Or if forwarding blocked by
firewall (seems to be by default on
fedora). Being better than "similar
software" never hurts.

**Comment by jschwartzenberg** [comment]
I think the creation of the tap device doesn't need root permissions. But setting up the bridge and IP masquerading does. Maybe NetworkManager can be instructed to do a lot with some dbus calls as well.

**Comment by stsp** [comment]
> I think

But it only takes 10 seconds to check...
```
$ tunctl -u stas
TUNSETIFF: Operation not permitted
$ sudo tunctl -u stas
Set 'tap0' persistent and owned by uid 1000
$ ifconfig tap0 up
SIOCSIFFLAGS: Операция не позволена
LC_ALL=C ifconfig tap0 up
SIOCSIFFLAGS: Operation not permitted
```

So it requires root in 2 places.

**Comment by stsp** [comment]
This is added.

**Comment by stsp** [comment]
I think the aforementioned problem
with packet losses should now be fixed.
