### ISSUE TITLE
DPMI weirdness

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#897]
**Describe the bug**
A large Gnu make file triggered this
~~~
masm mosadm \;
Microsoft (R) Macro Assembler Version 5.10 
Copyright (C) Microsoft Corp 1981, 1988.  All rights reserved.


  47940 + 336795 Bytes symbol space free

      0 Warning Errors
      0 Severe  Errors
del mosadm.pub
one file removed.
Exiting due to signal SIGSEGV
General Protection Fault at eip=00035c84
eax=00000000 ebx=00000064 ecx=00000001 edx=000de224 esi=00000000 edi=00000001
ebp=000de3b8 esp=000de130 program=G:\BIN\GMAKE.EXE
cs: sel=00f7  base=02131000  limit=0014ffff
ds: sel=0000
es: sel=00ff  base=02131000  limit=0014ffff
fs: sel=00af  base=00004ba0  limit=0000ffff
gs: sel=010f  base=00000000  limit=0010ffff
ss: sel=00ff  base=02131000  limit=0014ffff
App stack: [000df9d0..0005f9d4]  Exceptn stack: [0005f8f0..0005d9b0]

Call frame traceback EIPs:
  0x00035c84
  0x0002c8b5
  0x0002ccea
  0x0002d65a
  0x0000f852
  0x000100a6
  0x00010686
  0x0001ee7a
  0x0001e4c7
  0x0001e4c7
DPMI: Unhandled Exception 0d - Terminating Client
It is likely that dosemu is unstable now and should be rebooted
G:\SOURCES\src\latest>if ERRORLEVEL 1 goto fail
G:\SOURCES\src\latest>echo failed > fail.txt
G:\SOURCES\src\latest>exit 1
~~~

**To Reproduce**
Not sure if it's possible - but I pushed a branch of the current work in progress https://github.com/andrewbird/pcmos386/tree/dmpi-wierdness
run ./travis_build

**Attach the log**
[boot.log.gz](https://github.com/stsp/dosemu2/files/3488827/boot.log.gz)

**Comment by stsp** [comment]
Is this under fdpp?
Does the same happen under freedos?
Try `$_ignore_djgpp_null_derefs = (on)`

**Comment by andrewbird** [comment]
> Is this under fdpp?

No it's freedos, I had other issues with fdpp.

> Try $_ignore_djgpp_null_derefs = (on)

Okay will do

**Comment by jschwartzenberg** [comment]
In which mode is this? When I set this:
```
$_cpu_emu = "full"
$_cpu_vm = "emulated"
```
I get this and do not even get a prompt:
```
Kernel: allocated 115 Diskbuffers = 62560 Bytes in HMA
Process 0 starting: F:\command.com /e:1024 /k %FDPP_AUTOEXEC%
DPMI: Unhandled Exception 0d - Terminating Client
It is likely that dosemu is unstable now and should be rebooted

Shell F:\command.com exited, press any key...
```

**Comment by stsp** [comment]
Dont use "full", its unsupported!
Should I remove it now as everyone wants
to use it...

**Comment by andrewbird** [comment]
it's a default 32 bit installation for me so hardware vm86.

**Comment by andrewbird** [comment]
> Should I remove it now as everyone wants
to use it...

Fine my me, as I only use it when I'm confused!

**Comment by stsp** [comment]
Done.

**Comment by stsp** [comment]
`/andrewbird/pcmos386/tree/dMpi-wierdness`
Typo?
Costed my 10 minutes of fighting with git. :)

**Comment by stsp** [comment]
`run ./travis_build`
Should be:
`./travis_build.sh` I suppose?

**Comment by andrewbird** [comment]
yes, and yes! You can see I was in a hurry.

**Comment by andrewbird** [comment]
funny thing the dpmi thing hasn't reoccurred

**Comment by stsp** [comment]
```
Microsoft (R) Macro Assembler Version 5.10 
Copyright (C) Microsoft Corp 1981, 1988.  All rights reserved.

print.ASM(88): error A2116: Include file not found: _osmos.def 
gmake.exe: *** [makeutil.gmk:5: print.obj] Error 6
```

**Comment by andrewbird** [comment]
sure, but the dpmi thing occurred before that. It happened during the process to get makeutil.gmk to fully build. If you see that error, you haven't reproduced the issue.
