### ISSUE TITLE
32rtm hangs when started from comcom32

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#898]
Works fine from freecom.
DPMI problem likely.

**Comment by stsp** [comment]
This one is quite bad.
32rtm is not prepared to be run from
DPMI client. It just jumps to the exit addr
to stay resident, but comcom32 later works
in 32rtm's context, as the DPMI client was
not exited, so dosemu didn't sense the switch.
I can add the trick to switch back to comcom32,
but djgpp then wipes out 32rtm from memory
because it thinks it was a "memory leak".
And if I fix djgpp then things do work for
sime time, but if I try to start bc, then it
detects the 32rtm's presence, and, instead
of properly initializing, just jumps to 32rtm,
which is comcom32 at that point, because
the trick above switched the client back...
Not sure what to do. Add more and more
work-arounds, or just give up on 32rtm,
making it yet another "official regression"? :(

**Comment by jschwartzenberg** [comment]
What about patching 32rtm?

**Comment by stsp** [comment]
Not possible, as DPMI-0.9 does not provide
the reliable way of making a program resident.
If I had the sources of 32rtm, I probably had
to do a lot of changes to patch this out.
And besides, patch is a bad idea anyway.
I don't think anyone will patch 32rtm only to
run it under comcom32 as no one really needs
32rtm. But people will use it for testing and
report the regression.
I'll see if some big hacks on DPMI side can
work around that, and if not - give it up.

**Comment by jschwartzenberg** [comment]
If nobody needs 32rtm, why not just document this?

**Comment by stsp** [comment]
Because for some reason I have `bc.bat`
that looks like this:
```
@echo off
if -%OS%==-Windows_NT goto WIN
set DPMIMEM=MAXMEM 4096
32rtm.exe
bc.exe %1 %2 %3
32rtm.exe /u
exit
:WIN
bc.exe %1 %2 %3
```

I am not sure where did it came from and is
it a default `bc.bat` or a result of installing something
on top of bc-3.1, but its there. So if bc.bat is
that by default, many people can be trapped
by that problem even without a will to run 32rtm.

**Comment by jschwartzenberg** [comment]
True that. But you have something to handle `win.com` already right? Maybe it'd be an idea to detect `32rtm.exe` similarly?

**Comment by stsp** [comment]
What would you do with it, after detection?
Not run it completely?
Well, maybe that's an option indeed, if all
else fails (but I still have a hope for some
work-around).

**Comment by jschwartzenberg** [comment]
Yes, just skip over. Possibly print something on stderr and/or the log file when that happens.

**Comment by stsp** [comment]
http://www.delorie.com/djgpp/mail-archives/browse.cgi?p=djgpp/2019/08/17/12:22:38

**Comment by stsp** [comment]
I managed to find the minimal work-around
that works correctly most of the time, and only
produces the leak (and still works correctly)
in some very pathological cases.
But unfortunately it needs the above djgpp fix.
