### ISSUE TITLE
drop support of dosemu-freedos

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#901]
Currently it is nearly impossible to have
dosemu1 and 2 installed in parallel.
If you want to run dosemu1, you need to
install dosemu-freedos, but after that,
dosemu2 also picks that up, which is
unwanted.
I am going to drop dosemu-freedos support
so that dosemu1 can load freedos and
dosemu2 can load fdpp at the same time.

**Comment by andrewbird** [comment]
What specifically does dosemu2 dislike about the dosemu-freedos support that dosemu1 installs?

**Comment by stsp** [comment]
It doesn't dislike anything, but it _switches_ to
it from fdpp for compatibility. This is an unwanted
side effect. Installing dosemu1 and then dosemu2
should revert to dosemu2 fully.

**Comment by andrewbird** [comment]
So by 'drop dosemu-freedos support' in dosemu2 you mean it won't look in the 'system' place for freedos, but will treat freedos like any other legacy DOS and only use it if found in the c_drive? If so that's fine by me as I'm not a fan of the magic that make things just work.

**Comment by stsp** [comment]
Yes, this, plus also optionally drop its install support
in Makefile. If we don't boot it, I suppose installing it
also makes very little sense.

**Comment by andrewbird** [comment]
Sounds good to me.

**Comment by stsp** [comment]
OK, I've found that we prefer fdpp over freedos
from day 1, and only freecom was a problem.
So instead of removing the support, I integrated
the dosemu-freedos support into an fdpp setup.
freecom no longer overrides comcom32.

**Comment by jschwartzenberg** [comment]
It seems Debian packages dosemu1 and freedos together in the same package. So an upgrade on Debian would not leave FreeDOS around.
