### ISSUE TITLE
get rid of lnk files

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#902]
Currently the dosemu1 and 2 setups are so
incompatible that it might be better to move
to ~/.dosemu2. It used to have the backward
compatibility up to pre8, but even then you
couldn't run dosemu1 with 2's setup because
of the .lnk files (no forward compatibility).
But currently even the backward compatibility
is broken as "drives" dir is no longer looked in.
I think this was recently reported as a bug by
@jschwartzenberg but I can't find that report,
where it is?

So, rather than keeping to ignore the problem,
it might be better to switch to using ~/.dosemu2.
This will allow the parallel runs of 1 and 2 to
look for regressions.

**Comment by stsp** [comment]
Hmm, thinking more about that - the problem
is not running with dosemu1 in parallel. Since
dosemu2 doesn't look into "drives", dosemu1
is free to put anything there, so they can run
in parallel. The problem comes when the one
wants to run also earlier dosemu2 versions
that put lnk files to "drives" which dosemu1
won't accept.
So no, this can't be solved by moving to
~/.dosemu2.

**Comment by stsp** [comment]
Maybe its time for an updater script?
All it should do is replace the .lnk files with
symlinks. Current dosemu2 won't care,
older dosemu2 can work with both and
dosemu1 will work too.
Introducing .lnk files was a big mistake.

**Comment by jschwartzenberg** [comment]
I don't think I reported a bug on that but we had some discussion on this at the time it was still working. I was just dropping directories or symlinks to directories in there to get them to show up as paths.

If you would like some inspiration for another mechanism, you could check out how Wine stores its drive mappings :)

**Comment by stsp** [comment]
IIRC wine uses symlinks, no?

**Comment by jschwartzenberg** [comment]
Yes, but in a special way, not just to directories. Also to devices, but then it uses for instance:
`~/.wine/dosdevices/d:: -> /dev/cdrom` (double colon)
`~/.wine/dosdevices/z: -> /`

For the first case it autodetects the mount point and also provides direct device access. For the second case it's just a directory. I think sometimes the variant with both a single and a double colon could exist to provide both the path and the device.

**Comment by stsp** [comment]
The question is not how to encode
more bits into a symlink, like adding
a colon. This is quite inflexible btw:
any need to encode something else
and they invent the lnk files. :)
The question is how to access the
system-wide locations that may change.
And the question is how to upgrade
the drive layout when symlinks are
already created.
I suppose wine uses installer scripts
for first and upgrading scripts for second.
But in dosemu2 camp there was never
a shortage of complains to the installer
script's mere existing because people
got used to configure drives by hands
(not so with wine) and you can't easily
tell them to stop (I tried). And upgrading
scripts no one ever wanted to write.
So while dosemu-1.4 was modelled
after wine scheme and that looked
like a step forward, dosemu2 experience
tells us this is unacceptable.
I suppose changing the drive layout
in wine is no-no or the upgrade script
should have to be written.

**Comment by jschwartzenberg** [comment]
Here's the configuration with the advanced stuff unhidden:
![afbeelding](https://user-images.githubusercontent.com/877112/64061973-86228480-cbe1-11e9-990c-d8c0016f38a8.png)

**Comment by stsp** [comment]
And? It found a mount point because
of extra colon or what?
Please provide comments to the
pictures you post or its not toi useful.

**Comment by jschwartzenberg** [comment]
No this is all autodetected. I just thought it made sense to have an impression of what Wine provides. As you wrote
> I suppose changing the drive layout in wine is no-no

So they are marking autodetected and manually added drives in a way.

**Comment by stsp** [comment]
By manipulating symlinks?
But dosemu can't manipulate the
already created symlinks.

**Comment by jschwartzenberg** [comment]
I don't know exactly. Possibly parts are done through the registry as well. If you're really interested let's look up the relevant source code. Sounds more like something for after 2.0 is released though.

**Comment by stsp** [comment]
Why I would be interested in partially
dynamic generation of links, if we have
them fully dynamic? Once again, being
better than "similar software" never hurts.

**Comment by stsp** [comment]
And by the way, I don't buy that they
are flexible enough to avoid upgrade
wizards. Try running steam/proton
and then pure wine, for example.
It will detect the old layout and run
upgrade wizard. That at least is what
I see it does, but being a complete dummy
in a wine technologies, may misunderstand.
