### ISSUE TITLE
LPT1 port is Wrong

### ISSUE THREAD

**Issue by jcagbay** [stsp/dosemu2#907]
DOS Clipper program error LPT1 not ready.  Found that LPT1 port in memory location 40:08 is wrong:
78 03 78 02 BC 03
instead of 
78 03 78 02 00 00

**Comment by stsp** [comment]
No, its correct.
The difference you show, corresponds the
the address of LPT3, not LPT1.
This is not a bug report unless you provide
the needed info like logs, dosemu version
and whatever else is written in a bug-filling
form.

**Comment by stsp** [comment]
Feel free to submit more info and I'll re-open.
