### ISSUE TITLE
A newly created .dosemu folder is non functional.

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#914]
**Describe the bug**
A newly created .dosemu folder is non functional.

**To Reproduce**
Remove or move ~/.dosemu to another name. Start dosemu.

Boot stops at 
````
Bad or missing Command Interpreter: command.com /P /E:256
 Enter the full shell command line:                             
````

Somewhere between e197782c0 and 67f105c90 my custom .dosemu stopped working. I can't fix it until a default .dosemu folder works.

**Comment by stsp** [comment]
Please attach the log and follow
other steps of a bug reporting form too.
They are not for ignoring.

**Comment by stsp** [comment]
Hmm, yes, indeed, that setup no longer works.
What a surprise. :)
Well, freedos can't live w/o install.c because it
can't pick up fdconfig.sys from any other drive
than C:, and therefore its not possible to point
him to a command.com it seems.
Maybe we'll resurrect that... sometime. Or maybe
not.
@jschwartzenberg how goes your install scripts?

**Comment by stsp** [comment]
Or maybe for freedos we can just have a
different drives layout, so that the first drive
to be r/o boot drive. Isn't a very practical
setup, but will at least boot.

**Comment by stsp** [comment]
Should now be fixed... a kind of.
The last time I fix that setup.
Most ppl will not even treat that as fixed, but
at least it now boots again.

**Comment by stsp** [comment]
Found much better work-around and re-pushed.

**Comment by jschwartzenberg** [comment]
> @jschwartzenberg how goes your install scripts?

Right now not... the weather is too hot here to work comfortably on a computer... I hope to find a good moment when it's a bit cooler.

**Comment by stsp** [comment]
I added a work-around and so I don't think
your scripts should support this... at least
not until it breaks again. :)
