### ISSUE TITLE
Sudden DPMI crash on ubuntu 16.04 may be due recently linux update?

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#916]
**Describe the bug**
Today my client reported all of my dos program on dosemu failed to run:

```
DPMI: Unhandled Exception 0d -Terminating Client
It is likely that dosemu is unstable now and should be rebooted

```
 It happens after ubuntu 16.04 software update. Problem is the computer is 100km from my place and I can only access the computer via ssh.

I suspect this is due the update, but I have no idea which update caused the failure

The programs run fine on my computer (ubuntu 18.04)

What might make the sudden failure? I attach the boot.log with -DM command line argument

**To Reproduce**
Run a protected mode dos program on newest ubuntu 16.04 newest update

**Attach the binaries**
If the problem needs specific DOS files to reproduce, please attach.

**Attach the log**
this is the boot.log file with command line -DM
[boot.log](https://github.com/stsp/dosemu2/files/3583198/boot.log)

**Comment by bpranoto** [comment]
setting $_cpu_vm_dpmi="kvm" solves the problem..

However, previously it never had a problem with the default setting # $_cpu_vm_dpmi = "auto"

**Comment by stsp** [comment]
I improved the logging a little.
Please provide the -D9+Mc log.

**Comment by bpranoto** [comment]
[boot.log](https://github.com/stsp/dosemu2/files/3583866/boot.log)

**Comment by bpranoto** [comment]
oops sorry, I suppose have to recompile....

**Comment by stsp** [comment]
> Version: dosemu-2.0pre8 versioncode = 0x02000000

Oh, really? Build of 2 years ago?

**Comment by bpranoto** [comment]
Here it is...

[boot.log](https://github.com/stsp/dosemu2/files/3584241/boot.log)

**Comment by stsp** [comment]
OK, I have no idea what is that.
Maybe an ssh can help.

**Comment by bpranoto** [comment]
that's on my clients computer..  I connect to that computer via their openvpn network. Sorry...

**Comment by stsp** [comment]
Why not to reproduce the problem yourself then?

**Comment by bpranoto** [comment]
The linux version of my computer is 18.04 and it doesn't have this problem..

**Comment by stsp** [comment]
Try booting his kernel.
I suppose only kernel can affect DPMI.

**Comment by stsp** [comment]
Alternatively try downgrading his kernel and
see if that helps.

**Comment by stsp** [comment]
Besides, this is a 32bit version.
Why 32bit?

**Comment by stsp** [comment]
I added another logging fix, please update.

**Comment by bpranoto** [comment]
[boot.log](https://github.com/stsp/dosemu2/files/3585754/boot.log)

**Comment by stsp** [comment]
At least log is now correct.
But I would need a reproducer/ssh for that.

**Comment by stsp** [comment]
Is it still a problem?

**Comment by bpranoto** [comment]
I don't know. I just changed the setting to $_cpu_vm_dpmi="kvm" and there is no hang anymore

I'll try to install an ubuntu 16.04 in a VM and will check with the newest dosemu2. I'll report.

**Comment by jschwartzenberg** [comment]
Maybe this is related to #976. If it's not caused by a kernel/glibc change, possibly a CPU microcode update?
