### ISSUE TITLE
elite first encounters crash

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#917]
**Describe the bug**
It crashes.
At startup it says "32loader error: Not enough extended memory".
Works fine on 1.4.

**Comment by jschwartzenberg** [comment]
Regarding all these games, does it make sense to do a bisect?

**Comment by stsp** [comment]
You mean, if you do?
Yes, would be extremely cool!
Thanks.

**Comment by jschwartzenberg** [comment]
On pre8 it crashes dosemu2. The setup doesn't start either.

**Comment by jschwartzenberg** [comment]
This one runs on latest DOSEMU2 as well here with FreeDOS, commit: f9e9abd26376bc0538e23b649799cb5ea01db77f

**Comment by jschwartzenberg** [comment]
Actually, only the intro runs, then it crashes, both with and without KVM.

**Comment by stsp** [comment]
So any chance to bisect? :)

**Comment by jschwartzenberg** [comment]
You can't reproduce this one right? It's running also on my system where things just work.

**Comment by stsp** [comment]
Havent tried recently.
But you said above that it crashes,
but provided no bisect since.

**Comment by stsp** [comment]
For me still crashes.
Intro works.
Just as you said above.

**Comment by stsp** [comment]
> At startup it says "32loader error: Not enough extended memory".

But this is gone.

**Comment by jschwartzenberg** [comment]
It seems we should compare our environments again, dos versions, etc. I switched to FreeDOS to prepare for a bisect, but maybe it's just broken in FDPP?

**Comment by stsp** [comment]
I am getting the crash on "any DOS" (tm).
Let me bisect it myself then. :)

**Comment by stsp** [comment]
Bisect: 981b9877
