### ISSUE TITLE
castle wolfenstein hangs

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#920]
**Describe the bug**
Hangs at game start.
Seems to work on 1.4.
Hmm, dosemu2 feels much more stable
if you don't test it.

**To Reproduce**
Run the game, press Enter to start.

**Comment by jschwartzenberg** [comment]
The version of the game I found says `Cannot open control file` on pre8.

**Comment by stsp** [comment]
With MS-DOS yes.
It only works with freedos.

**Comment by jschwartzenberg** [comment]
I tested with FreeDOS, not with MS-DOS.

**Comment by stsp** [comment]
I can't reproduce this with freedos and with
fdpp. Even by pressing f5 at start to skip all
drivers, I still can run `cw.exe`.
But its not a problem as long as I can reproduce
it with pc-dos.

**Comment by stsp** [comment]
Argh, sorry, bad testing on my side!
I _can_ reproduce this with freedos!
But not with fdpp. Can you confirm that?

**Comment by jschwartzenberg** [comment]
Indeed, with fdpp it goes further.

**Comment by stsp** [comment]
Update: mfs problem is debugged (thanks
to Andrew for help), and now this works properly
on PC-DOS and hangs on fdpp and freedos.

**Comment by stsp** [comment]
Update: it doesn't even hang.
But there are invisible menus within.

**Comment by stsp** [comment]
It doesn't look like its working properly
on PC-DOS either, but at least menus
are visible. The game is not playable.
With fdpp the game is playable (sort of)
if you go past the invisible menu...
