### ISSUE TITLE
alpha waves doesn't work

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#923]
**Describe the bug**
Hangs at start.
Works on 1.4.

**To Reproduce**
Just start.

**Attach the binaries or provide an URL**
http://www.abandonia.com/en/games/25594/Alpha+Waves.html

Almost no games seem to work.
Testing more looks like the waste of time.

**Comment by stsp** [comment]
Maybe the first beta doesn't need to run many games?

**Comment by jschwartzenberg** [comment]
This one crashes on 1.4 here as well.

**Comment by stsp** [comment]
With freedos - yes.
But not with PC-DOS.

**Comment by stsp** [comment]
I created the "freedos" label to mark it as such.

**Comment by stsp** [comment]
Doesn't seem to work on 1.4 either,
but works on anything else but freedos.
Not interesting.
