### ISSUE TITLE
'make install' doesn't honor MANPATH

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#927]
Man pages are installed under /usr/local/share/man regardless of PREFIX or MANPATH settings.  I install dosemu2 in another location but the installer insists on /usr/local for the man pages.

**Comment by jharrison03** [comment]
EDIT:  I've tried MANDIR and MANPATH in compiletime-settings with the same result.

**Comment by stsp** [comment]
No, that works, otherwise the deb build won't work.
How do you set prefix?

**Comment by jharrison03** [comment]
In 'compiletime-settings.devel', I have --

mandir /home/me/dosemu2/share/man

I do a default-configure -d, make, then make install.  The install fails because /usr/local/share/man isn't writeable from my user's account:

/usr/bin/install -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 0644 *.1 /usr/local/share/man/man1
/usr/bin/install: cannot create regular file ‘/usr/local/share/man/man1/dosdebug.1’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/share/man/man1/dosemu.1’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/share/man/man1/dosemu.bin.1’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/share/man/man1/mkfatimage16.1’: Permission denied
Makefile:16: recipe for target 'install' failed
gmake[1]: *** [install] Error 1

**Comment by stsp** [comment]
I just tried and for me it works perfectly.
What dosemu2 version?
What is in Makefile.conf?
For me it now has `mandir:=/home/stas/man`
as I set mandir that was for an experiment.

**Comment by stsp** [comment]
Will re-open when you provide more info.
