### ISSUE TITLE
castle wolfenstein mfs problem

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#928]
**Describe the bug**
As mentioned here:
https://github.com/stsp/dosemu2/issues/920#issuecomment-535638679
cw.exe says `Cannot open control file`
if MS-DOS is used, but loads with freedos.
This is the mfs problem.

**To Reproduce**
Run cw.exe under MS/PC-DOS.

**Attach the binaries or provide an URL**
https://www.myabandonware.com/game/castle-wolfenstein-3l

**Comment by stsp** [comment]
Correction: freedos has that problem too,
but not fdpp. Very strange.

**Comment by stsp** [comment]
This have something to do with the "fcb call"
at mfs.c:3923. If I comment that line, then on
freedos the problem disappears, but not on
PC-DOS. I look at RBIL int2f/1116h and see
no mention of any fcb call...
I guess only @bartoldeman or @andrewbird 
know what this code is doing. :)

**Comment by stsp** [comment]
Andrew, can you take a look into that one?

**Comment by andrewbird** [comment]
Yes, having a look now under freedos 1.20

**Comment by andrewbird** [comment]
According to RBIL `ES:DI -> uninitialized SFT` and yet we are using it to determine if it's an FCBcall. Like you I know not of any FCBcall for int2f/1116, but the code below `do_open_existing:` is used by other case sections in the switch as well. I hate jumping between case sections in a switch as it makes it very difficult to follow the logic, but I guess it's done for code reuse.
Under which PC-DOS version do you still have problems with the commented out code?

**Comment by andrewbird** [comment]
Actually I see under PC-DOS 7/2000 that the int2f/1116 is generated on behalf of an int21/0f open file using FCB. This suggests to me that RBIL is perhaps wrong in omitting the FCB info and suggesting that the SFT is uninitialised. Investigating ...
