### ISSUE TITLE
Slow on Debian Buster 32-bit due to lack of vm86

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#932]
It seems that the new Debian Buster release has vm86 disabled:
```
ERROR: vm86 service not available in your kernel, Functie is niet aanwezig
ERROR: using CPU emulation for vm86()
```

```
$ grep VM86 /boot/config-4.19.0-6-686-pae 
# CONFIG_X86_LEGACY_VM86 is not set
```

It's so slow that you can see text being drawn letter by letter, line by line. Maybe there should be an instruction somewhere to either recompile the kernel or obtain an alternative kernel.

**Comment by stsp** [comment]
No, there shouldn't.
Please figure out what exactly combination
of `$_cpu_vm` and `$_cpu_emu` settings gives
the bad performance.
Combinations to try:
```
$_cpu_emu = "vm86sim"
$_cpu_vm = "emulated"
```
```
$_cpu_emu = "vm86"
$_cpu_vm = "emulated"
```
```
$_cpu_emu = "off"
$_cpu_vm = "kvm"
```

**Comment by stsp** [comment]
And when you do, please see if the same
combination have not regressed from -pre8
or from 1.4.

**Comment by jschwartzenberg** [comment]
It seems `vm86sim` is a bit faster than `vm86`. Other than that, all variants are slow. `kvm` is not supported by the CPU.

**Comment by stsp** [comment]
What is slow? Boot is slow? comcom32 is slow?
Have you tried freecom instead of comcom32 to
avoid involving DPMI?

What exactly cpu is that?

**Comment by jschwartzenberg** [comment]
The whole boot is slow. Here's the cpuinfo:
```
Architecture:        i686
CPU op-mode(s):      32-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 32 bits virtual
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          15
Model:               2
Model name:          Intel(R) Pentium(R) 4 CPU 2.66GHz
Stepping:            9
CPU MHz:             2666.691
BogoMIPS:            5333.38
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe pebs bts cpuid cid xtpr pti
```

**Comment by stsp** [comment]
This CPU is roughly similar to what I have:
```
cpu MHz		: 2516.871
bogomips	: 8027.48
```

You have more MHz's and just 1.5 times fewer bogomips.
So its not something to be very slow.
Is dosbox also slow?

**Comment by jschwartzenberg** [comment]
Does that really say much? I'm quite sure my Intel Core2 Duo is way faster and both those values there are lower.

**Comment by skitt** [comment]
> It seems that the new Debian Buster release has vm86 disabled:

The Stretch kernel also had vm86 disabled (it’s been disabled since 4.1.2; see [#792003](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792003)). I take it you didn’t see this slowdown with the Stretch kernel; is that correct?

**Comment by stsp** [comment]
> Does that really say much? I'm quite sure my Intel Core2 Duo is way faster and both
> those values there are lower.

And this exactly is an indication that
something goes wrong!
Is dosbox also slow?

**Comment by stsp** [comment]
Is this still a problem?

**Comment by jschwartzenberg** [comment]
Probably yeah, I hope I can test more again soon.

**Comment by stsp** [comment]
Is this still a problem?
