### ISSUE TITLE
make install only do a partial instll

### ISSUE THREAD

**Issue by domichel** [stsp/dosemu2#935]
Making an ebuild on gentoo, only a partial install is done with make install.
The ebuild send the following commands to portage:

Configure step:
`./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/dosemu2-9999 --htmldir=/usr/share/doc/dosemu2-9999/html --libdir=/usr/lib64 --docdir=/usr/share/doc/dosemu2-9999 		--enable-plugins=libao,extra_charsets,term,sdl,sdl1,dosdrv,doscmd,periph,debugger,charsets,console,modemu,fdpp,alsa,fluidsynth,midimisc,munt,ladspa,gpm,X, 		--sysconfigdir=/etc 		--with-fdtarball=/var/tmp/portage/app-emulation/dosemu2-9999/distdir/dosemu-freedos-1.0-bin.tgz`

which result into:
```
Enabling plugins: 
	libao 
	gpm 
	alsa 
	ladspa 
	extra_charsets 
	term 
	X 
	sdl 
	midimisc 
	fluidsynth 
	charsets 
	console 
	modemu 
	sdl1 
	dosdrv 
	doscmd 
	periph 
	debugger 
	fdpp

```
Compile phase:
make -j3
It succeed.

Install (${D} is the temporary directory where portage install the software before to perform the real install, in that case /var/tmp/portage/app-emulation/dosemu2-9999/image):

```
DESTDIR="${D}" PREFIX="/usr" make install
...
for i in ../bin/*.so; do \
  if [ -f $i ]; then \
    /usr/lib/portage/python2.7/ebuild-helpers/xattr/install -c -m 0644 $i /var/tmp/portage/app-emulation/dosemu2-9999/image/usr/lib64/dosemu; \
  fi; \
done
/usr/lib/portage/python2.7/ebuild-helpers/xattr/install -c -d /var/tmp/portage/app-emulation/dosemu2-9999/image/usr/share/doc/dosemu2-9999 		--enable-plugins=libao,extra_charsets,term,sdl,sdl1,dosdrv,doscmd,periph,debugger,charsets,console,modemu,fdpp,alsa,fluidsynth,midimisc,munt,ladspa,gpm,X, 		--sysconfigdir=/etc 		--with-fdtarball=/var/tmp/portage/app-emulation/dosemu2-9999/distdir/dosemu-freedos-1.0-bin.tgz
/usr/bin/install: unrecognized option '--enable-plugins=libao,extra_charsets,term,sdl,sdl1,dosdrv,doscmd,periph,debugger,charsets,console,modemu,fdpp,alsa,fluidsynth,midimisc,munt,ladspa,gpm,X,'
Try '/usr/bin/install --help' for more information.
make[1]: *** [/var/tmp/portage/app-emulation/dosemu2-9999/work/dosemu2-9999/src/arch/linux/Makefile.main:136: install] Error 1

```

**Comment by domichel** [comment]
[Makefile.conf.txt](https://github.com/stsp/dosemu2/files/3714679/Makefile.conf.txt)

**Comment by stsp** [comment]
There is some problem with the
way you pass parameters to configure.
Firstly, why --docdir is specified twice?
Secondly, where have you took the
part of command line that enables
plugins? You are likely passing it the
wrong way (like quoted in apostrophes),
please show the full ebuild.

**Comment by domichel** [comment]
I get to the same conclusion and I am working on it. Now, I have a working ebuild, and I learned that to not quote the argument list variable during configure invocation is an acceptable gentoo policy, and in practice just works, which is the most important think. 

[dosemu2-9999.ebuild.txt](https://github.com/stsp/dosemu2/files/3717024/dosemu2-9999.ebuild.txt)

**Comment by domichel** [comment]
[Dosemu2FileList.txt](https://github.com/stsp/dosemu2/files/3717060/Dosemu2FileList.txt)
We can close that bug.

**Comment by domichel** [comment]
This also mean, if I understand well, than it should be possible to install dosemu2 without comcom32 as long than another DOS is provided by the system or by the user. Which in its turn, also imply than even fdpp can be made optional.

**Comment by stsp** [comment]
Yes, but those are not binary blobs and the
gentoo user is very unlikely to provide the
pre-installed DOS (and do it in a dosemu2-compatible
way). So it makes much fewer sense in making
them optional, and the unbootable emulator is a
very bad result of a modularity.
So the common sense suggestion is to make
everything possible for the user to get the
bootable emulator by default (unless he tries
very hard to disable essential things), but
disable the binary blob components (at least
by default).

**Comment by stsp** [comment]
Other package managers has "suggests",
"recommends", "depends" etc to specify exactly
the importance of the package deps.
We have fdpp/comcom32 in "recommends" and
dosemu-freedos in nowhere. It could be in "suggests",
but there is no separate package with it anyway. I think
gentoo's USE is much different than that and you don't
need dosemu-freedos as a separate package to USE it.
In which case that looks reasonable, but I don't know
the gentoo policy about binary blobs. If there are
some restrictions on that, just make that USE
disabled by default to avoid any troubles.

**Comment by stsp** [comment]
> We have fdpp/comcom32 in "recommends"

Оговорка по Фрейду. :)
I lied, they are currently in "depends" to prevent the
unbootable setups.

**Comment by domichel** [comment]
OK thanks.

In gentoo, we can prefix the USE flags with "+" or "-" into the ebuild in order to force them, but the sysadmin can choose to force them another way. Anyway, it will be no USE code for these 2 depends. I can let the ebuild like it is. It have now both comcom32 and fdpp as non conditional depends, and the freedos blob with USE="-fdbinary".

One more thing. configure check for valgrind support into fdpp and doesn't find it. What are the implication of that?

**Comment by stsp** [comment]
> What are the implications of that?

Nothing. Its only for debugging.
Btw, you don't have to rush satisfying everything
that configure is searching. it is searching for many
things, some are very optional, some are duplicating
others, some are deprecated, and all that.
Seeing "checking for XXX... no" is perfectly fine.
It is much better to look up the deps from the
debuild recipe and rpm spec that we provide.

**Comment by domichel** [comment]
> It is much better to look up the deps from the
> debuild recipe and rpm spec that we provide.

It is what I have done first. It is just I like to understand the implication of a choice, and in gentoo we have plenty of them. Maybe more than necessary, but it is the gentoo way. Sometimes it's great, sometimes it become just too time consuming. With your answers, you confirm me than I have sane default choices. Thank's a lot!

**Comment by domichel** [comment]
No, it still fail with a mmap() error. /dev/shm is mounted and works fine with jackd. I can open another bug with this mmap() issue.
