### ISSUE TITLE
GCC not longer able to create valid DOS binary

### ISSUE THREAD

**Issue by MaxPower2005** [stsp/dosemu2#938]
Hello

It seems like one of the fixes for https://github.com/stsp/dosemu2/issues/933 broke GCC ability to create a valid DOS binary.

`git bisect` identifies this commit https://github.com/stsp/dosemu2/commit/3be5394b93b34e7640064d4df8688a9f278e2f50 as the culprit.

The test program I use is the following one-liner:
`echo int main() { return 0; } | gcc -Wall -Os -x c -o t -`

Please note that the compilation process terminates normally (besides two `ERROR: Cannot set handle for /home/david/.dosemu/drive_c/nul` messages from dosemu during compilation), but the resulting DOS binary does not work. 

The same setup and test program works OK (without the dosemu ERROR messages) with an installation based on https://github.com/stsp/dosemu2/commit/4eb322434c9329442cdcecbe549ce4629cd51ebf

[boot.log](https://github.com/stsp/dosemu2/files/3746418/boot.log)

**Comment by stsp** [comment]
Should now work.
Thanks for testing!

**Comment by stsp** [comment]
Andrew, I think lfn.c no longer pokes to LoL.
Though I don't remember why did we need that.

**Comment by stsp** [comment]
The main difficulty around that 71a6 code is that
it uses handle as an input. That handle is returned
by 716c and it must not clash with the DOS opened
handles, so we run SFN helper and with coopth
trick I get back its return value. But the main problem
is that there is no corresponding Close call in 71h
API. I.e. the handle obtained with 716c, will go to
AH=3e for close. This means that LFN subsystem
can't track the handle<-->name mapping on its own,
because the handles are closed behind its back.
So now I intercept Close at redirector level and
look up the handle in user stack.
Previous approach of poking into psp->jft->lol->sft
was not much better.
And note that this all is _only_ for 71a6. No other
71xx funcs expect handle as argument.
I wonder how Windows95 deals with that mess.
Maybe we should just "unsupport" 71a6 and see
what breaks?
Or are there any bright ideas how this can be
handled more gracefully?

**Comment by andrewbird** [comment]
LoL is not bad in itself, just that it's indicative of use/manipulation of DOS internals like CDS, SDA etc. There's one more major use of LoL, `mangle.c:is_dos_device()` uses it to find/walk the device chain and it seems to be an overly complex function indeed. That's easy to get rid of in the redirector itself as we can use int2f/1223, but outside like in lfn.c I don't know.

> That handle is returned by 716c and it must not clash with the DOS opened handles

Aren't they the same thing? i.e. handles returned by 716c, 6cxx and 3cxx are equivalent.

I wonder what happens on Win95 when a file is opened using 6cxx, then subsequently 71a6 is called on its file handle.

> I wonder how Windows95 deals with that mess.

I expect that on Win95, its DOS is doing this part of the 71xx API, not the portion sitting on top of DOS.

> Previous approach of poking into psp->jft->lol->sft was not much better.

I couldn't see where if the old code handled Extended JFT where its size is greater than 20 files and it has been relocated, so I expect your current solution beats that anyway.

**Comment by stsp** [comment]
Yes, they are the same thing.
In win95 DOS can't do that on its own
for one simple reason: int2f/110f
does not return higher 32 bits of the
file size.
I am thinking on making a redirector
extension to support that functionality
in fdpp (and in bios.s as a fall-back).
If you want, you can try that too. :)

**Comment by andrewbird** [comment]
Extending the redirector sounds nice, I'm sure it's a big task though!

**Comment by stsp** [comment]
No, I mean only a6.
That means to create int2f/11a6 fn
by moving there int21/71a6 as is.
Very simple.

**Comment by stsp** [comment]
But it shoul of course accept sft, not
handle. This is the only difference.

**Comment by stsp** [comment]
I implemented it in fdpp and in mfs.
The yesterday's hacks are removed.
Hope now its written in a dosemu2 way. :)

**Comment by stsp** [comment]
> In win95 DOS can't do that on its own
> for one simple reason: int2f/110f
> does not return

Indeed but it could do that for local fat32,
which is what its LFN API is all about
(no redirector support for it I think)

**Comment by andrewbird** [comment]
Your new implementation looks nice, so I just started to write a test case.

**Comment by stsp** [comment]
Thanks, good idea.

**Comment by andrewbird** [comment]
So I like this mechanism you use here for extending redirector/FDPP and retaining compatibility for older DOSes, and maybe I'd like to do something similar for other LFN functions. But to be really useful in the redirector we'd need to setup a DOS stack beforehand so that all of the int2f/12xx functions are available for use in the redirector when called via the compat code. Can you think of any way a user level DOS program could setup a DOS stack prior to making an int2f/12xx call?

**Comment by stsp** [comment]
But in fdpp the user prog doesn't have to do that?

**Comment by andrewbird** [comment]
Agreed, FDPP is golden as we can setup the stack just as it does for other redirector calls, the problem is the compat (maybe in bios.s) is running the user stack. Looking at the FDPP code in kernel/entry.asm it appears to just do this
~~~
save user stack SS:SP
cli
sets SS from DGROUP
sets SP from _disk_api_tos
sti

does DOS stuff

restore user stack
returns
~~~

So maybe I'm overthinking this, as I'd always thought the SP would be some random value not top of stack. So if I can get SS from int2f/1203, then perhaps we know where each stack is in sda?

**Comment by stsp** [comment]
Have you looked at how exactly does it
check for being on a DOS stack, to refuse
to work otherwise?

**Comment by andrewbird** [comment]
No, but when testing in the past I found FreeDOS more forgiving than MS-DOS, so it might not be representative. I'll have a look.

**Comment by stsp** [comment]
Possibly MS-DOS does "push ss; pop ds"
and fails to access its variables?

**Comment by andrewbird** [comment]
I can't see anything obvious, I'll code up a test to see which DOS's are a problem.

**Comment by andrewbird** [comment]
So calling int2f/1217 for an existing drive with user stack
~~~
DR-DOS 7.00 okay
FR-DOS 1.20 okay
FDPP GIT    okay
MS-DOS 6.22 fail (CF set)
MS-DOS 7.00 fail (CF set)
PC-DOS 7.00 fail (CF set)
~~~

**Comment by andrewbird** [comment]
doing this, mostly works (msdos 7 and pcdos 7 okay, but msdos 6.22 crashes at program end)
~~~
diff --git a/test/test_dos.py b/test/test_dos.py
index 29898d074..6847444b1 100644
--- a/test/test_dos.py
+++ b/test/test_dos.py
@@ -3414,6 +3414,19 @@ rem end\r
     .globl  _start16
 _start16:
 
+    movw    %ss, old_SS
+    movw    %sp, old_SP
+
+    movw    $0x1203, %ax
+    int     $0x2f    # answer in DS
+
+    cli
+    movw    %ds, %ax
+    movw    $0x920, %bx
+    movw    %ax, %ss
+    movw    %bx, %sp
+    sti
+
 # DOS 3.0+ internal - GET CURRENT DIRECTORY STRUCTURE FOR DRIVE
 
 # AX = 1217h
@@ -3434,6 +3447,13 @@ _start16:
     pushw   $0x02
     movw    $0x1217, %ax
     int     $0x2f
 
+    popw   %ax
+
+    cli
+    movw    old_SS, %ss
+    movw    old_SP, %sp
+    sti
+
     jc  prfuncfail
 
     cmpb    $'C', %ds:(%si)
@@ -3470,6 +3490,11 @@ matchfailmsg:
 successmsg:
     .ascii  "CDS returned okay\r\n$"
 
+old_SS:
+    .word   0
+old_SP:
+    .word   0
+
~~~

0x920 sp value was found in fdppknrl.map but not sure if it should be 0xffff-0x920

**Comment by stsp** [comment]
I think it would be much better to list
the functions you like being available.
Maybe there are not too many and
some simple replacement is possible?

**Comment by stsp** [comment]
Besides, I don't think there is a big
difference whether they are in lfn.c
or mfs.c. If they can work in lfn.c, as
they now do, then what is the problem
when they moved?

**Comment by stsp** [comment]
I mean, they do not have dos stack
in both cases, and currently they work.
That means they will keep working.

**Comment by andrewbird** [comment]
> If they can work in lfn.c, as
they now do, then what is the problem
when they moved?

None if the goal is just to move lfn functions into the redirector, but I had in mind to break the dependency on LoL and CDS array finally. Int2f/1217 and Int2f/1223 would help me do that, and for those I need a DOS stack. If course there is always the hack of abusing an existing int2f/11xx function to provide further subfunctions, but we have to find one that is called by int21 without its interpretation of input parameters or returns.

**Comment by stsp** [comment]
How about this plan.
Move them to mfs.c, but allow
calling from an outside, like from
lfn.c. Caller will have to deal with
lol and cds. lfn.c will activate by
second_revect, and mfs caller will
activate by fdpp.

**Comment by andrewbird** [comment]
Interesting idea, and thinking on about this there's also another possibility; add a test in redirector to see if it's been called with a DOS or user stack, then take the appropriate action. That way lfn.c can be a small shim and mfs.c redirector can have all the logic.

**Comment by stsp** [comment]
That would be a programming
anti-pattern. If the caller has that
info already, he must provide it to
the callee rather than callee having
to guess (even if the guess is simple).
And I dont see how you can handle
the "otherwise" part, ie when redirector
finds he cant "take the appropriate
action".

**Comment by andrewbird** [comment]
I agree it's poor, but I don't want the shim guessing what items (cds, cds length, lol) might be needed to implement each function within the redirector and it's not as if the shim has them at hand like FDPP does as it has to derive them somehow. What I really want is it to call the redirector with the DOS stack, which is identical to how FDPP would ideally call it, but that may not be possible. An alternative is not to use any DOS stack requiring function in the redirector extension, but that throws away much of the advantage of doing it.
Maybe this is a whole lot of work for little gain.

**Comment by stsp** [comment]
This is likely the wrong end of the problem
to discuss. The 1:1 move to mfs.c is quite
useless. It is very likely that where the current
interface seeks for CDS, you'll need some
other, LFN-aware CDS, or maybe something
else that suits.
So IMHO the first thing to do is to define the
API that would be both convenient and easy
to implement in fdpp.
After this is done, the shim can be considered.
But, before such shim is written, current lfn.c
can still be used perfectly. So writing shim is
purely optional.

**Comment by andrewbird** [comment]
> It is very likely that where the current
interface seeks for CDS, you'll need some
other, LFN-aware CDS, or maybe something
else that suits.

Yes, a very good point!
