### ISSUE TITLE
Having trouble getting -E working

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#940]
I'm trying to run a file with dosemu -E, but when I run dosemu it just boots in to C:  and outputs `Bad command or filename`
```sh
$ ls
build  deps  dos.com  dos.d  examples  incremental

$ dosemu -T -E dos.com
```

![image](https://user-images.githubusercontent.com/179677/67524972-b1899300-f6a9-11e9-941b-71701c9978e3.png)

Any idea what's going on ?

**Comment by andrewbird** [comment]
If you do `dosemu -T -E dir` do you see the directory listing you expect?

**Comment by stuaxo** [comment]
I was expecting to see my current directory, but instead it's dosemus drive C:

![image](https://user-images.githubusercontent.com/179677/67527632-607c9d80-f6af-11e9-990d-97c0a924e38b.png)

Here's the output of lredir2:

![image](https://user-images.githubusercontent.com/179677/67527711-93269600-f6af-11e9-9ba7-9dd501939615.png)

**Comment by andrewbird** [comment]
So the dos file you want to execute is on linux filesystem? In that case don't you want `dosemu -T -K $(pwd)/dos.com`?

**Comment by stuaxo** [comment]
Thanks, that worked .. but what is `-K`, I can't see it listed in `--help` ?

Is there something I can pass that will get it to exit afterwards ?

My program just outputs "hello world" is there some way it can output into the terminal, and that output still be in the terminal ?

I tried the `-t` slang but on exit the screen is cleared.

OT:   I'm testing a program that only outputs to stdout, I'd like to run the program in the terminal and quit - I can

**Comment by andrewbird** [comment]
Here's what `man dosemu.bin` says for `-K`
~~~
       -K unix_path
              Specify  unix  path for the program running with -E.  You can omit -E and specify the full unix path with -K,
              but passing command-line arguments via -K is not recommended and may be removed in the future. The  following
              may nevertheless work:
              dosemu -K "/home/joeuser/dosemu/freedos/bin/xcopy.exe my_file my_dir"
~~~

Not using `-T` will allow dosemu to exit after the command is run.

If it's a non-interactive program you can use `dosemu -td -K $(pwd)/dos.com` that will allow the output to remain on the terminal, or you can redirect it to a file instead.

**Comment by stsp** [comment]
`./` instead of `pwd` can also be used in `-K`.
Patches for updating `--help` are much appreciated. :)

**Comment by stuaxo** [comment]
@stsp would a patch to make `-K` exit by default, be welcome ?

This would make it consistent with `-E`.

**Comment by stsp** [comment]
They should behave equally.
If you find any inconsistency (which I
very much doubt as this functionality
is regularly tested) then yes.

**Comment by stuaxo** [comment]
Error was on my side.
