### ISSUE TITLE
Ingame graphics in Duke Nukem 2 are messed up with vm86 jit

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#942]
**Describe the bug**
![image](https://user-images.githubusercontent.com/877112/67624785-a19eba00-f835-11e9-97a9-ebc52324e836.png)

**To Reproduce**
Go ingame with DN2.

**Attach the binaries or provide an URL**
https://www.dosgamesarchive.com/download/duke-nukem-ii/

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/3775182/boot.log)

This used to work fine, so should be bisected.

**Comment by stsp** [comment]
Can't reproduce with my copy of duke2.
The colours are fine.

**Comment by stsp** [comment]
[duke2.tar.gz](https://github.com/stsp/dosemu2/files/3775303/duke2.tar.gz)
My copy.
Does it work for you?

**Comment by jschwartzenberg** [comment]
Same behavior with your copy over here.

**Comment by jschwartzenberg** [comment]
Enabling KVM fixes the issue here.

**Comment by stsp** [comment]
This seems to be fixed.
Could you please check?

**Comment by jschwartzenberg** [comment]
Yep, I can confirm it's fixed! The digital sound effects in the game are still broken though.

**Comment by stsp** [comment]
Don't remember such ticket.

**Comment by jschwartzenberg** [comment]
Created!
