### ISSUE TITLE
freedos: Cannot find a free DOS drive to use for LREDIR

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#944]
**Describe the bug**
With freedos, `dosemu -K xxx` prints this:
`ERROR: Cannot find a free DOS drive to use for LREDIR`

**To Reproduce**
dosemu -K ./some_file.exe

It seems like `is_valid_drive()` uses fn 0x29 to check
the drive existence, but freedos seems to always return
AX=0x2900 unless you are out of lastdrive.
With LASTDRIVE reduced, it would print
`ERROR: Could not change to H:` with H (or any other
letter) being the LASTDRIVE letter.

Looking into RBIL I can't find any notes about how
it should behave with free drives. And the difference
between fdpp and freedos in that func surprises me.
Andrew, have you patched something in fdpp for this
to work, or what's going on?

**Comment by andrewbird** [comment]
okay will have a look.

**Comment by andrewbird** [comment]
And `dosemu -K /home/ajb/chrset.exe` works for me also on FreeDOS 1.20

~~~
C:\>system -s DOSEMU_VERSION
C:\>system -e
About to Execute : chrset.exe
About to Execute : chrset.exe
 
    0 1 2 3 4 5 6 7 8 9 A B C D E F
  +---------------------------------+
0 |       0 @ P ` p Ç É á ░ └ ╨ α ≡ |
1 |     ! 1 A Q a q ü æ í ▒ ┴ ╤ ß ± |
2 |     " 2 B R b r é Æ ó ▓ ┬ ╥ Γ ≥ |
3 |     # 3 C S c s â ô ú │ ├ ╙ π ≤ |
4 |     $ 4 D T d t ä ö ñ ┤ ─ ╘ Σ ⌠ |
5 |     % 5 E U e u à ò Ñ ╡ ┼ ╒ σ ⌡ |
6 |     & 6 F V f v å û ª ╢ ╞ ╓ µ ÷ |
7 |     ' 7 G W g w ç ù º ╖ ╟ ╫ τ ≈ |
8 |     ( 8 H X h x ê ÿ ¿ ╕ ╚ ╪ Φ ° |
9 |     ) 9 I Y i y ë Ö ⌐ ╣ ╔ ┘ Θ ∙ |
A |     * : J Z j z è Ü ¬ ║ ╩ ┌ Ω · |
B |     + ; K [ k { ï ¢ ½ ╗ ╦ █ δ √ |
C |     , < L \ l | î £ ¼ ╝ ╠ ▄ ∞ ⁿ |
D |     - = M ] m } ì ¥ ¡ ╜ ═ ▌ φ ² |
E |     . > N ^ n ~ Ä ₧ « ╛ ╬ ▐ ε ■ |
F |     / ? O _ o ⌂ Å ƒ » ┐ ╧ ▀ ∩   |
  +---------------------------------+
G:\>
~~~


So which version of FreeDOS is broken for you?

**Comment by stsp** [comment]
Also put `fdconfig.sys` to `drive_c`.

**Comment by andrewbird** [comment]
With your kernel.sys (FreeDOS 1.00 I checked the sha1sum) I get failure too!
~~~
C:\>system -e
ERROR: Cannot find a free DOS drive to use for LREDIR
C:\>lredir -n /bin
Cannot redirect (maybe no drives available).
~~~

**Comment by stsp** [comment]
But this also have something to do with
dosemu, because booting system-wide
freedos seems to succeed with the very
same kernel. :(

**Comment by andrewbird** [comment]
You can see the thought process on choosing int21/29h here #883, and that RBIL suggests it to determine if a drive is valid http://www.ctyme.com/intr/rb-2570.htm. So it just looks like a freedos 1.0 bug to me, and it's fixed in FreeDOS 1.10.

**Comment by stsp** [comment]
But how to explain the system-wide boot then?

**Comment by stsp** [comment]
All you need to do, is to put dosemu-freedos-xxx into
dosemu source tree and do "make install".
Then you can remove `~/.dosemu` and the system-wide
boot should happen.
What I removed was the _install_ from system-wide
to local dir. There is still a minimal support for a system-wide
boot.

Let me know if you can confirm that system-wide
freedos (which is 1.0) allows -K to work.

**Comment by stsp** [comment]
Of course you also need to remove fdpp
from the system-wide path, or it will be preferred.

**Comment by stsp** [comment]
Simplified test:
`dosemu -K ./`
Then with local freedos you end up on drive C
and on system-wide - on drive H (allocated by lredir).

**Comment by stsp** [comment]
I can't download the newer kernel, the links here:
http://www.fdos.org/kernel/
are all broken.
Could you please upload yours?

**Comment by andrewbird** [comment]
I don't want to pollute my machine with `make install` so I've removed fdpp, dosemu and comcom32 and building a new debian package without those dependancies. I'll need to drop in the system freedos somewhere afterwards.

> Then with local freedos you end up on drive C
and on system-wide - on drive H (allocated by lredir).

That almost seems to opposite to what I'd expect, but in any case they should be the same.

[FR-DOS-1.20.tar.gz](https://github.com/stsp/dosemu2/files/3784858/FR-DOS-1.20.tar.gz)

**Comment by andrewbird** [comment]
With FreeDOS 1.20, `dosemu -K ./` and systemwide install I end up on F: (is lredired)
With FreeDOS 1.00, `dosemu -K ./` and systemwide install I end up on C:

So is this wrong if the FreeDOS 1.00 can't determine a free drive to lredir?

**Comment by stsp** [comment]
Aargh!
Sorry for fooling you around.
When I was removing the local freedos,
fdpp took over as I didn't remove also that. :(
So yes, a freedos-1.0 bug.

> So is this wrong if the FreeDOS 1.00 can't determine a free drive to lredir?

Which means that we do no longer support
dosemu-freedos-bin at all.

**Comment by andrewbird** [comment]
I ran strings on its kernel.sys and see no significantly long string to look for at boot. Maybe we have to settle for a warning if any FreeDOS and -K used? Since we don't package FreeDOS 1.00 any more can't we just document the requirement for FreeDOS >= 1.10?

> `make uninstall` is also supported.

Yes but I have a long time distrust of letting developer's makefiles loose on a system with root privs, it's the sort of thing that would have got me fired when I was working :)

**Comment by stsp** [comment]
> I ran strings on its kernel.sys and see no significantly long string to look for at boot.

Its UPXed. :(

> for a warning if any FreeDOS and -K used?

Oh well, better than nothing.

> document the requirement for FreeDOS >= 1.10?

The documented requirement is fdpp, others are all
at user's own risk. But the problem is that some people
still boot dosemu-freedos-bin.

> Yes but I have a long time distrust of letting developer's makefiles loose on a system with root privs

Maybe you can mess around prefix to avoid the root privs.

> sort of thing that would have got me fired when I was working :)

Hope that wasn't a makefile of dosemu? :)

**Comment by andrewbird** [comment]
> Hope that wasn't a makefile of dosemu? :)

Nope, and to be honest I never had an install go bad as I didn't ever do it. You can never know unless you read every script fully if there's anything malicious or just poorly coded in there. 

> Maybe you can mess around prefix to avoid the root privs.

Yes a tactic is to try the install as an unprivileged user with an install prefix knowing it will fail, and see where it wants to install. Create the top level directory as root, chown it to the unprivileged user, and repeat the install attempt. Works okay with installations that are located in a single place, but not with ones that want to spread their stuff all over the filesystem.

**Comment by stsp** [comment]
No, the better tactic is to use `--prefix=` during
configure to point it to the local place within home.

**Comment by andrewbird** [comment]
Sure thing, if you have the source. With commercial stuff you have to find other ways.

**Comment by stsp** [comment]
> Sure thing, if you have the source. With commercial stuff you have to find other ways.

If you still have `make install` but no sources
(isn't that a weird combination?), maybe `DESTDIR`
can be helpful?

Anyway, I think `sudo rm -rf /` in a Makefile is not a
very common practice, but sometimes it happens:
`https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123`

**Comment by stsp** [comment]
In either case, with dosemu2 you should be
able to set up the prefix for your needs, and
then do `make install` w/o root.
If that doesn't work as expected, please let me know.

**Comment by andrewbird** [comment]
BTW have you ever managed to svn checkout freedos from sourceforge? Its history goes back to 2000 and it would be nice to filter the kernel part of the tree into git for easy reference. I don't seem to be able to git-svn clone it, or use the github import tool, I get XML errors.

> If that doesn't work as expected, please let me know.

I doubt I'll ever do a make (un)install, as I far prefer packaged installs since at least I know they'll be no silent overwriting of any existing system files - old habits die hard :smile:

**Comment by stsp** [comment]
Yes, may be good to try merging a histories for fdpp.

> overwriting of any existing system files

But its not possible if you use weird prefix and no root.

**Comment by PerditionC** [comment]
> I can't download the newer kernel, the links here:
> http://www.fdos.org/kernel/
> are all broken.
> Could you please upload yours?

Thanks for the heads up.  I don't recall what I had been doing that broke them, but I will get the links fixed this weekend.

**Comment by stsp** [comment]
> 2000 and it would be nice to filter the kernel part of the tree into git for easy reference.

Done now, enjoy.
This is probably not the right thing to do,
as it would now seem as if fdpp is a continuation
of freedos, whereas it just re-uses its sources
in a copy/paste form. But if it helps in the
development, then lets have it that way.

> fixed this weekend.

Good, I thought this is a dead stuff. :)

**Comment by andrewbird** [comment]
> Done now, enjoy

Cool, so commit https://github.com/stsp/fdpp/commit/062ebeb6a667ead39938c6972c65eaeeef9fed16 looks like the change that fixed `is_valid_drive()` for FreeDOS 1.10.

Thanks.

**Comment by stsp** [comment]
Wow, 12 years ago!

**Comment by stsp** [comment]
I propose in that very lredir error msg to check
for freedos boot, and in that case throw an error
and terminate.

**Comment by andrewbird** [comment]
Sounds good.

**Comment by stsp** [comment]
Or even terminate in any case, as not
handling -K is fatal.
Btw, github doesn't see that prolonged history,
neither in commits nor in contributors list.
So it still doesn't look like a freedos continuation,
at least not in a guthub ui. :)
