### ISSUE TITLE
Prince of Persia 2 causes crash

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#945]
**Describe the bug**
There is a crash, dosemu is terminated, `Terminated with signal 4`.

**To Reproduce**
Get in-game and play a bit.

**Attach the binaries or provide an URL**
http://www.abandonia.com/en/games/51/Prince+of+Persia+2+-+The+Shadow+%2526+The+Flame.html

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/3775198/boot.log)

Same game as stsp/dosemu2#290. This issue is new, needs a bisect.

**Comment by stsp** [comment]
You are right, this had nothing to do with fdpp.
Please check if other mysteries do remain.

**Comment by jschwartzenberg** [comment]
With CPUEMU it runs fine for me now. I managed to complete 5 levels without problems.

**Comment by stsp** [comment]
Thanks for confirming.
Quite nasty regression.
