### ISSUE TITLE
freedos: DOS device list corrupted

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#946]
**Describe the bug**
Booting old freedos causes crash with that msg.

**To Reproduce**
Run the attached kernel.sys that worked in the past:
[kernel.sys.gz](https://github.com/stsp/dosemu2/files/3800998/kernel.sys.gz)

**Comment by stsp** [comment]
Bisect: 595bdc9b6
Andrew?

**Comment by andrewbird** [comment]
Just for interest, where did this kernel come from because it's not the standard FreeDOS 1.20 kernel.sys as that has different sha1sum and no crash?

**Comment by stsp** [comment]
This came from some thread here where
I fixed some lba partition crash, and uploaded
the bc3-built kernel.
It worked perfectly when you tested it back then.
But if that would be proved to be a bug in this
particular build - no problems, I am just a bit
sceptical as I see the regression.

**Comment by andrewbird** [comment]
I'm also seeing this with FreeDOS compiled from current git with gcc. Since that patch 595bdc9 uses int2f/12 I wonder if it's a result of a bad return value from int2f/1203 caused by the same issue as you fixed in https://github.com/stsp/fdpp/commit/97dc1ec ?

**Comment by stsp** [comment]
Very unlikely because the kernel I tried,
was not compiled with gcc, but with bc3.

**Comment by andrewbird** [comment]
It seems that loading `emufs.sys` is the trigger for this. I see a crash on both your Borland kernel and the current FreeDOS git.

**Comment by stsp** [comment]
Of course it is.
Otherwise there is no redirector.

**Comment by andrewbird** [comment]
This is the last thing in the log.
~~~
MFS: emufs operation: 0x0000                                                    
ERROR: general protection at 0xb035c6f0: 0                                      
Real-mode state dump:                                                           
EIP: 6c6f:00010000 ESP: 9dc9:000021f4  VFLAGS(b): 00011 00110000 00000111       
EAX: 00003528 EBX: 00000000 ECX: 000013ce EDX: 0000f6a4 VFLAGS(h): 00033007     
ESI: 0000f6a4 EDI: 0000e09a EBP: 000021fa DS: f000 ES: f000 FS: 0000 GS: 0000   
FLAGS: CF PF IF RF VM  IOPL: 3                                                  
STACK: a4 f6 9a e0 fa 21 00 f0 00 f0 -> a8 00 da 02 02 32 24 22 f7 00           
OPS  : 00 00 00 00 00 00 00 00 00 00 -> 00 00 00 00 00 00 00 00 00 00           
        0000                6c6f:0000 add  [bx+si],al                           
00| 00d8:11be->001f3e   01| 00d8:1189->001f09   02| f000:f104->0ff104           
03| 00d8:1189->001f09   04| 00f1:0400->001310   05| d811:89f0->0e0b00           
06| 00d8:11c6->001f46   07| 1189:f000->020890   08| f106:00d8->0f1138           
09| f000:e987->0fe987   0a| 0600:d811->013811   0b| 07f0:00f1->007ff1           
0c| f000:f10e->0ff10e   0d| f000:f106->0ff106   0e| f000:f107->0ff107           
0f| f000:f111->0ff111   10| 00f1:07f0->001700   11| d811:c6f0->0e4800           
12| f000:f114->0ff114   13| 11c6:f000->020c60   14| f109:00d8->0f1168           
15| f000:f117->0ff117   16| 0900:d811->016811   17| b3f0:00f1->0b3ff1           
18| f000:f11a->0ff11a   19| f000:f109->0ff109   1a| f000:feb3->0ffeb3           
1b| 0070:01fa->0008fa   1c| 00fe:b3f0->00c3d0   1d| 00e9:87f0->009680           
1e| 0070:0119->000819   1f| e987:f000->0f8870   20| f51e:f000->1041e0           
21| 6c6f:f6a4->07bd94   22| 1ef0:00e9->01efe9   23| 0df0:00f5->00dff5           
24| 00d8:1270->001ff0   25| f000:f51e->0ff51e   26| f000:f10d->0ff10d           
27| 00d8:11b6->001f36   28| 00f1:0df0->001d00   29| 00f1:0ef0->001e00           
2a| 00d8:1189->001f09   2b| f10e:f000->1000e0   2c| f10f:f000->1000f0           
2d| 00d8:1189->001f09   2e| 0ff0:00f1->00fff1   2f| 10f0:00f1->010ff1           
30| d811:d6ea->0e57fa   31| f000:f10f->0ff10f   32| f000:f110->0ff110           
33| 00d8:1189->001f09   34| 00f1:10f0->002000   35| 00f1:11f0->002100           
leavedos(vm86_GP_fault:378|0) called - shutting down                            
leavedos thread started                                                         
leavedos thread ended                                                           
closing debugger pipes                                                          
GEN: fd=27 removed from select SIGIO                                            
coopthreads stopped                                                             
~~~

On a previous run I stepped through the `dos_fs_dev()` with gdb and as it returned from INIT operation, dosemu crashed.

**Comment by andrewbird** [comment]
This is the dosdebug leading up to the crash. Quite what's going wrong with getting the int 28 vecter I can't see
~~~
02da:009e 55               push bp
dosdebug> 
dosdebug> 
system state: emulated,stopped
AX=0028  BX=0000  CX=13ce  DX=f6a4  SI=f6a4  DI=e09a  SP=21fa  BP=2224
DS=f000  ES=f000  FS=0000  GS=0000  FL=000b3302
CS:IP=02da:009f       SS:SP=9dc9:21fa

02da:009f 89E5             mov  bp,sp
dosdebug> 
dosdebug> 
system state: emulated,stopped
AX=0028  BX=0000  CX=13ce  DX=f6a4  SI=f6a4  DI=e09a  SP=21fa  BP=21fa
DS=f000  ES=f000  FS=0000  GS=0000  FL=000b3302
CS:IP=02da:00a1       SS:SP=9dc9:21fa

02da:00a1 B435             mov  ah,35
dosdebug> 
dosdebug> 
system state: emulated,stopped
AX=3528  BX=0000  CX=13ce  DX=f6a4  SI=f6a4  DI=e09a  SP=21fa  BP=21fa
DS=f000  ES=f000  FS=0000  GS=0000  FL=000b3302
CS:IP=02da:00a3       SS:SP=9dc9:21fa

02da:00a3 8A4604           mov  al,[bp+04]
dosdebug> 
dosdebug> 
system state: emulated,stopped
AX=3528  BX=0000  CX=13ce  DX=f6a4  SI=f6a4  DI=e09a  SP=21fa  BP=21fa
DS=f000  ES=f000  FS=0000  GS=0000  FL=000b3302
CS:IP=02da:00a6       SS:SP=9dc9:21fa

02da:00a6 CD21             int  21
dosdebug> 
dosdebug> 
General Protection Fault, system state: emulated,stopped
AX=3528  BX=0000  CX=13ce  DX=f6a4  SI=f6a4  DI=e09a  SP=21f4  BP=21fa
DS=f000  ES=f000  FS=0000  GS=0000  FL=00033207
CS:IP=6c6f:fffe       SS:SP=9dc9:21f4

6c6f:fffe 0000             add  [bx+si],al
~~~

**Comment by stsp** [comment]
So its a dosdebug problem?

**Comment by andrewbird** [comment]
No I don't think so as the returned to address was similar in both the dosemu log without dosdebug and the trace in dosdebug. In the meantime tkchia fixed a problem with int21/35 in his current PR for FreeDOS. This problem is no longer reproducible on FreeDOS with his PR, so I'll switch to back to the Borland compiled kernel.

**Comment by stsp** [comment]
But earlier you said dosdebug is
leading to a crash.
So are you going to recompile the new kernel
with bc3?

**Comment by andrewbird** [comment]
> But earlier you said dosdebug is
leading to a crash.

But I meant when using dosdebug I can see the steps that lead up to the crash.

> So are you going to recompile the new kernel
with bc3?

I'm thinking about it. It would be good thing for FreeDOS travis if I could automate it for their build, but getting a BC3 installation from somewhere reliable on the web might be difficult.
On the other hand I may just dosdebug/trace your kernel and see if the symptoms are the same.

**Comment by andrewbird** [comment]
So I just traced your BC3 kernel.sys with a little test program I wrote. The interrupt 2f/1203 isn't returning anything in DS, when it should have the Data segment.


### Just before the call to int2f/1203
~~~
2481:0102 B80312           mov  ax,1203                                         
dosdebug>                                                                       
dosdebug>                                                                       
system state: emulated,stopped                                                  
AX=1203  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000          
DS=2481  ES=2481  FS=0000  GS=0000  FL=000b3346                                 
CS:IP=2481:0105       SS:SP=2481:fffe                                           
                                                                                
2481:0105 CD2F             int  2F                                              
dosdebug>                                                                       
dosdebug>
~~~

### Notice the DS should be 00d9
~~~                               
system state: emulated,stopped                                                  
AX=1203  BX=00ff  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000          
DS=2481  ES=2481  FS=0000  GS=0000  FL=000b3346                                 
CS:IP=2481:0108       SS:SP=2481:fffe                                           
                                                                                
2481:0108 B44C             mov  ah,4C
~~~
### This is DOS's real data segment
~~~                                           
dosdebug> d 00d9:0000                                                           
dosdebug>                                                                       
                                                                                
00d9:0000 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00  ................     
00d9:0010 00 00 00 00 00 00 00 00 00 00 03 00 01 00 FF FF  ..............       
00d9:0020 FF FF 00 00 B0 02 B2 1B D9 00 CC 00 D9 00 06 06  ..0.2.Y.L.Y...       
00d9:0030 70 00 52 05 70 00 00 02 6D 00 D9 00 00 00 78 05  p.R.p...m.Y...x.     
00d9:0040 00 00 00 00 00 00 07 1A 52 05 70 00 04 80 76 14  ........R.p...v.     
00d9:0050 7B 14 4E 55 4C 20 20 20 20 20 00 00 00 00 00 00  {.NUL     ......     
00d9:0060 00 00 00 00 00 14 00 01 00 03 03 00 00 B4 12 BF  .............4.?     
00d9:0070 02 00 00 00 00 00 00 00 00 00 B0 0A D9 00 00 00  ..........0.Y...     
~~~

**Comment by stsp** [comment]
Using non-free compiler on travies
is likely a bad idea.
Ok, so if you are confident this is
fixed, then please post back when
the patches are applied, and Ill try
to rebuild it (if they still support bc3,
which may be not the case after gcc
porting).
It may also be good to move lol/sda
to umb also on fdpp.

**Comment by andrewbird** [comment]
> Using non-free compiler on travies
is likely a bad idea.

Yep I think so too.

I'm confident it's fixed for GCC, Borland C is less certain but the symptoms were the same.

>  (if they still support bc3,
which may be not the case after gcc
porting).

Yes another concern, I figure they'll either have to drop some compiler support or just accept they'll get broken from time to time. I looked at adding Watcom build to their travis, but it's a whopping 120MB, and that would be downloaded on every build. It's a shame there's no local data space to store stuff like that on Travis. Anyway they have an automated build with GCC and I do think that just having GCC available for ia16 in PPA must be a really good thing for FreeDOS devs.

**Comment by andrewbird** [comment]
> Ok, so if you are confident this is
fixed, then please post back when
the patches are applied, and Ill try
to rebuild it (if they still support bc3,

The PR just got merged into FreeDOS Git, so it'd be interesting if you could see if it still builds on BC3 and/or still has the problem, thanks!

**Comment by stsp** [comment]
Maybe next week-end.
You can try that too. :)

**Comment by stsp** [comment]
OK, you are perfectly correct!
This problem have disappeared.
New build attached.
But some other problem have appeared,
namely, it now says
`Error in the DJ mechanism!`
which, I think, have something to do
with the cdrom redirector.
[kernel.sys.gz](https://github.com/stsp/dosemu2/files/4106363/kernel.sys.gz)
