### ISSUE TITLE
elite frontier buggy with vm86sim

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#948]
Firing with the laser produces the infinite
laser ray. And also ubsan complains a lot.
Works perfectly with jit.

**Comment by stsp** [comment]
Fixed by 79eed1fff1.
Crazy!
Bart, was that intentional? :)

**Comment by bartoldeman** [comment]
No, I just noticed the bitops still faulting with Win 3.x after I changed S_DI and S_DI_IMM, then realized they were broken.
