### ISSUE TITLE
Tandy/PCjr 3-voice sound

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#952]
Is this something that can be supported?

**Comment by stsp** [comment]
Very unlikely.
This doesn't work on PCs (port C0h is used
by DMA on PC), so it will need a switch to XT.
I think dosbox is a better answer for that.
Of course if someone submits the patch, I
won't be too opposed.

**Comment by stsp** [comment]
So lets wait for PR.

**Comment by jharrison03** [comment]
Have you seen AGIMIDI?  

[agimidi.zip](https://github.com/stsp/dosemu2/files/3921787/agimidi.zip)

**Comment by stsp** [comment]
What does this have to do with tandy 3-voice?
