### ISSUE TITLE
2nd Reality no graphics display

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#963]
**Describe the bug**
Second Reality demo runs but produces no graphics output.

The following is observed in the console:

```
ERROR: SGDT not implemented
ERROR: SIDT not implemented
ERROR: SGDT not implemented
ERROR: SIDT not implemented
ERROR: SGDT not implemented
```

**To Reproduce**
Start the demo and observe the display.  The sound plays but no graphics are visible.

**Attach the binaries or provide an URL**
[2nd_real.zip](https://github.com/stsp/dosemu2/files/3921568/2nd_real.zip)

**Attach the log**
[boot.log.zip](https://github.com/stsp/dosemu2/files/3921584/boot.log.zip)
[dosemurc.zip](https://github.com/stsp/dosemu2/files/3921586/dosemurc.zip)

**Comment by stsp** [comment]
Only regressions are considered at that time.
Did it work on dosemu-1.4 or pre8?

**Comment by jharrison03** [comment]
> Only regressions are considered at that time.
> Did it work on dosemu-1.4 or pre8?

No, it doesn't.

**Comment by stsp** [comment]
No, this is wrong.
Just don't use simx86, set the demo to "mono"
and wait for a couple of minutes. The display
is there.

**Comment by stsp** [comment]
In fact, with simx86 it works similar.
So it is slow not because of CPU, but
probably because of bad timer emulation.
In any case, the only problem here is
that its very slow.

**Comment by stsp** [comment]
But you need to set it to mono.
