### ISSUE TITLE
Dosemu crashing with NDN

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#969]
**Describe the bug**
I was hoping to have a poke around bug #360 again, but a few seconds after starting NDN, Dosemu crashes with this on the launching terminal
~~~
ERROR: Not allowed for detached thread 260, dpmi_control
~~~
Seen with MS-DOS 6.22, PC-DOS 7.10, FR-DOS 1.20, FDPP git (may be others but these are the ones I saw it with)

**To Reproduce**
Steps to reproduce the behaviour:
1/ Extract binary `ndn_2_31_5309_bin_d32.exe`
2/ cd ndn
3/ ndn
4/ wait a few secs, crash

**Attach the binaries or provide an URL**
ndn_2_31_5309_bin_d32.exe inside t1.zip below

**Attach the log**
test.log inside t1.zip below

[t1.zip](https://github.com/stsp/dosemu2/files/3979050/t1.zip)

**Comment by stsp** [comment]
And guess what caused this. :(

**Comment by stsp** [comment]
Please use the fix from #972 to play with ndn.
