### ISSUE TITLE
Dosdebug mcbs command and FDPP

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#970]
With FDPP I see strangeness in the display of second DOS chunk

~~~
dosdebug> mcbs
dosdebug> 

ADDR(LOW) PARAS  OWNER
029f:0000 0x04b3 [DOS]
  => ADDR      PARAS TYPE USAGE
     02a0:0000 0x000c [F] Files
     02ad:0000 0x000a [D] Driver (EMUFS)
     02b8:0000 0x02a8 [B] Buffers
     0561:0000 0x00cf [F] Files
     0631:0000 0x008f [L] CDS Array
     06c1:0000 0x0080 [S] Stacks
     0742:0000 0x0010 [B] Buffers
0753:0000 0x00aa [DOS]
  => ADDR      PARAS TYPE USAGE
     ffffffff:0000 0x0000 [     da0e:0000 0x9f00 [0] Unknown Type
07fe:0000 0x0007 [FREE]
0806:0000 0x0410 [COMMAND]
0c17:0000 0x00e6 [02055]
0cfe:0000 0x0010 [02055]
0d0f:0000 0x000f [03360]
0d1f:0000 0x92e0 [MFT] (END)
~~~

Here's Qemm's MFT which shows 'DOS Code'. 
![2019-12-18-mft](https://user-images.githubusercontent.com/220835/71109418-0b479e80-21bd-11ea-87ea-fbc47e8fc6d6.png)

Do you know how detect 'DOS Code' properly so that we may avoid dosdebug interpreting it as Data?

**Comment by andrewbird** [comment]
Is it as simple as looking at the `SC` instead of `SD`?
~~~
0753:0000 4D 08 00 AA 00 00 00 00 53 43 20 44 4F 53 00 00  M..*....SC DOS..
~~~
~~~
029f:0000 4D 08 00 B3 04 00 00 00 53 44 00 00 00 00 00 00  M..3....SD......
~~~

**Comment by andrewbird** [comment]
So looking at the change you made to fdpp because of https://github.com/stsp/fdpp/issues/114 displaying LINK incorrectly with `ivec`, that still occurs with FreeDOS obviously. What exactly is LINK, and which MCB(sub) type is it valid in?

**Comment by ecm-pushbx** [comment]
> Is it as simple as looking at the `SC` instead of `SD`?

SC means either DOSCODE segment or excluded UMA area. SD means DOS data with subsegments. Generally, owner = 8 and first letter = S means that at most two letters of the name are used. Owner = 8 and a first letter other than S has the name same as a self-owned MCB. For example, "RPL" is the name used for the RPL's memory, with an owner equal to 8.

**Comment by stsp** [comment]
> What exactly is LINK

It is an "excluded UMA area" as @ecm-pushbx calls it.
I wanted them to be distinguishable with doscode, so
i looked how PC-DOS does this, and found that the
name contained more chars than just "SC" in the
case of the code.
So the "valid" way of detecting DOS code seems
to be that the first 2 letters are "SC" but strcmp()
does not match. :) At least this is how it always
worked with PC-DOS, so I just did the same.
