### ISSUE TITLE
mouse wrongly positioned in NDN

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#973]
**Describe the bug**
Mouse in NDN doesn't follow the host pointer.

**To Reproduce**
Apply fix for #972 then run ndn.

**Comment by j2969719** [comment]
maybe something happened on my end, but it seems that the same problem still exists when in vc/ dn/ndn I switch ega lines or other video modes

**Comment by stsp** [comment]
In the case please open a new ticket
with a full reproducer. I don't see the
mode selection in vc.

**Comment by j2969719** [comment]
alt+f9 or f9>commands>ega lines
