### ISSUE TITLE
Settlers 2 secondary mouse

### ISSUE THREAD

**Issue by stefand** [stsp/dosemu2#974]
I'm creating this issue to document my attempts to get the secondary mouse working in Settlers 2 (Siedler 2) and the possible bugs I have encountered on the way.

TL&DR version: With the help of the attached script you can convert evdev input to the format of a serial mouse and have dosemu2 read com1 from a fifo. The game should pick it up. [evdev2ser.txt](https://github.com/stsp/dosemu2/files/3992352/evdev2ser.txt). Rename the .txt away...
1) Attach mouse
2) Look up the xinput id of the mouse with "xinput"
2) xinput disable <secondary mouse id>
3) mkfifo /tmp/serfifo
4) sudo /opt/_windows_rw/dos/siedler2/evdev2ser /dev/input/eventXX /tmp/serfifo
5) set $_com1 = "/tmp/serfifo" in dosemu.conf
6) Start the game. Make sure in the options screen that the primary mouse uses PS2 and secondary mouse COM1.
7) Start a 2 player game :-)

More details:
In the past I've done this with gpm, see https://sourceforge.net/p/dosemu/bugs/414/ . The gpm command line is something along the lines of "gpm -m/dev/input/mouseXX -timps2 -D -Rmsc", then dosemu reads com1 from /dev/gpmdata. This still works, but has horrible mouse latency when moving. There is no latency when you only click without moving the mouse (although queued up movement will delay clicks too).

While trying to debug the latency I tried $_com1 = "mouse", but keep the normal mouse settings unchanged. This gives me a 'shadow' secondary mouse that follows the X mouse input - and interestingly has lots of movement latency as well.

My thinking was that modern mice have a way higher sample rate than old serial mice used to have. I tried to set usbhid.mousepoll=50 to get ~20hz polling. That subjectively improved the situation a bit, but I am not entirely sure.

During my research I ran across https://raspberrypi.stackexchange.com/questions/81465/usb-to-serial-rs232-mouse-converter , which is where the attached script originates from. It works better than gpm, but still has latency that makes the game unplayable. I modified it to report only every 4th move event, but report right away when there's a click. This gives me a nicely working secondary pointer with my mice. YMMV with your devices.

Presumably it would be better to decouple event reading and serial writing in the script and have a separate thread / timer that writes the accumulated movement every 25(?) ms. That would make it work better if mouse polling increases in the future. I am not a tcl expert, so if I ever do this thing I'd probably rewrite the script in something else.

Another interesting observation is that if the mouse is moved between dosemu start and the point where the game starts reading COM1, mouse movement is queued up somewhere and the mouse starts replaying that queued up movement in the first few game seconds. So there is still some unwanted buffering.

For the sake of clarity: The primary mouse works perfectly out of the box with dosemu2's mouse support. No settings changes needed, no latency.

So here are the possible actionable bugs / feature requests:
1) $_comX="mouse" has latency / buffering issues with modern mice.
2) That buffering may be in the generic serial code
3) Consider making $_comX="mouse" more generic, e.g. by supporting input from a particular /dev/input/mouseX node or multi-pointer X.

**Comment by jschwartzenberg** [comment]
I would say multi-pointer X would be the most user friendly variant. I guess that it would have to be supported by SDL2 as well though?

**Comment by stsp** [comment]
Hi Stefan.
I am on mobile right now, so will give
only a vague reply.
dosemu2 is not dosemu1. :) We
already have the mouse event
converters, see sermouse.c and
commouse.c. Sadly, I wrote them
5 years ago, so I need to see the
code before I can tell you how exactly
you should use them (forgot everything),
but surely you can quickly figure that
out too.

Buffering may require just some
flushing of tty line I suppose?

So, your interest in 2 mouse support
is very welcome, but before that, we
both need to (re-)understand how
dosemu2 handles that already.

**Comment by stefand** [comment]
I read through sermouse.c (I missed commouse.c somehow), and I think that's the code that $_comX="mouse" activates. If I understand it right - and I'll happily wait for corrections from you - is that there are a few Linux-side mouse "input" modules like SDL, GPM and reading from /dev/psaux and DOS-side "output" protocols, among them the code that handles int 33 and sermouse.c. So yeah, the components to handle this without external converters are there, what's missing is a way to configure two mouse paths - e.g. one that goes SDL->int33 and one that goes fd(/dev/input/mouse1)->sermouse.

What I am not quite understanding yet is how $_comX="mouse" and $_mouse_dev="comX" (suggested by comments in dosemu.conf) are supposed to interact. My guess is that the motivation of com=mouse is to feed the SDL mouse input into a game that talks to mouse HW directly without going through int 33. Is the idea of mouse_dev=comX to use dosemu2's internal int 33 support with direct HW access e.g. to /dev/ttyS0 without going through x11/gpm and without loading a dos mouse driver like mouse.com?

I tried to use com1=mouse && mouse_internal=off together with the CuteMouse driver to see if it also shows the same latency behavior I saw in Settlers 2. However, dosemu2 crashes when loading ctmouse when mouse_internal=off. I am using fdpp and comcom32, maybe fdpp has some bugs when dosemu does not provide an int 33 handler? Or maybe I am horribly misunderstanding something :-) .

Are you aware of any other games that use more than one mouse? I don't think I'll have much time to spend on this, the idea was to play S2 with my brother over the holidays, not dive into a multi-week multi-pointer X side quest. If two mice are a more common use case I might be motivated to do more though :-) .

**Comment by stefand** [comment]
Ah yes, I also have a computer with an old school COM port (on the mainboard, not USB to serial), but I don't have an old-school serial mouse any more.

**Comment by jschwartzenberg** [comment]
I have a serial mouse + a USB RS232 converter. I can at least confirm that this allows you to use a serial mouse directly with DOSEMU2. I used a serial mouse with a scroll wheel to record this video to see how the scrolling mouse driver for Windows 3.1 works: https://schwart6.home.xs4all.nl/win31-scrollwheel.ogv

So if you get hold of a serial mouse, it should work fine.

**Comment by stsp** [comment]
Yes, real serial mouse could work
because then there is no comX=mouse
and therefore no confusion about
the mouse source. But we need to
get comX=mouse working.

I havent yet looked, but I will soon.
Please attach a crash log in a mean
time, making sure it contains stack
trace with debug info.

**Comment by stsp** [comment]
The crash should now be fixed.
It doesn't look like ctmouse work, but
you can experiment with S2 a bit.

**Comment by stsp** [comment]
> Is the idea of mouse_dev=comX to use dosemu2's internal int 33 support with direct HW access e.g. to
> /dev/ttyS0 without going through x11/gpm and without loading a dos mouse driver like mouse.com?

Yes, exactly.
And using that with $_comX="mouse" means
that it then goes not from real serial mouse, but
from the emulated one, that can also be fed by
SDL. Quite a long round-trip that was supposed
only for debugging.

**Comment by stsp** [comment]
> Are you aware of any other games that use more than one mouse? I don't think I'll have much time to
> spend on this, the idea was to play S2 with my brother over the holidays, not dive into a multi-week
> multi-pointer X side quest.

I don't think its common at all, and therefore
what you propose (alternate path from /dev/xxx)
is perfectly fine with me.

**Comment by stsp** [comment]
I think the simplest trick would be for
$_comX="mouse" to derive the value of
$_mouse_dev and use that as an input.
$_mouse_dev is not for that - it is purely
for internal driver, but using it just as a
default value when nothing else is specified,
sounds like a nice simplification.
Later we can implement the overrides like
`$_comX="mouse dev /dev/input/mice"`.
The trick is that $_mouse_dev is almost
never really used as the mouse events go
from X/SDL/gpm, not from dev. So such
abuse looks not too evil to me.

**Comment by stsp** [comment]
I pushed the completely untested patch to
branch "m2" that should add the second mouse
support. Could you please test?

**Comment by stsp** [comment]
Event routing should now be implemented.

**Comment by stsp** [comment]
I made a successful testing with MS mouse.com.
It can't be tested as a secondary mouse because
it won't load if internal mouse is enabled. But at
least sermouse.c converter works fine.
Still no luck with ctmouse. It detects the mouse and
loads, but mousetst doesn't see events.

@mcericdos do you have any hints how to debug
the ctmouse incompatibility? In the dosemu log
I can see that it reads the data from serial port...

**Comment by stsp** [comment]
ctmouse doesn't even hook int33!
And yet it says:
```
CuteMouse v2.1 beta4 [FreeDOS]
Installed at COM1 (03F8h/IRQ4) in Logitech mode 
```

int33 still points to `F001:0B5E`.
I suppose ctmouse is somehow buggy.

**Comment by stsp** [comment]
> int33 still points to F001:0B5E.

Which is fine as long as there is an UMB.
Hmm...

**Comment by stsp** [comment]
OK, it appears ctmouse treats "M3" as Logitech
even though 'M' means (I think) Microsoft.
If I use "M0" then ctmouse detects mouse as Microsoft.
I wonder if it is a ctmouse bug, at least I tried
many different drivers and they all recognized
"M3" as Microsoft.

**Comment by stsp** [comment]
@mcericdos do you have any idea why "M3"
means Logitech to ctmouse, and if it is valid or not?

**Comment by stsp** [comment]
ctmouse is very buggy even if M3 is logitech.
For example mousetst does not track the movement
events when ctmouse driver is used, but perfectly
tracks them with MS mouse.com. Also in NDN the
cursor is invisible until you do a few clicks.
I wouldn't recommend the use of ctmouse with
dosemu2, but at least it is now supported.

**Comment by stefand** [comment]
Thanks for all the work! I unfortunately I forgot my Linux HD at home, so I won't be able to test it before I am back from my Christmas travels. I'll test it and report the results on Friday.

**Comment by stsp** [comment]
I filled multiple bugs for ctmouse: https://github.com/FDOS/mouse/issues
I think I should just revert its support. In its
current form it is not worth a try. It is also
incompatible with my win31 mouse driver.

**Comment by stsp** [comment]
I removed the ctmouse support again.
No matter whether it is right or wrong about
"M3", it is too buggy to be used with dosemu2.

**Comment by stefand** [comment]
I tested your new code, it correctly pipes the mouse I configured in $_mouse_dev to com1 and Settlers 2 understands it. However, the input latency problem I had with gpm and my script before I accumulated 4 move events into one is still there.

The mouse I have used for testing is this device:
Bus 001 Device 003: ID 046d:c077 Logitech, Inc. M105 Optical Mouse

I'll try to hack a similar throttling mechanism into sermouse...

**Comment by stsp** [comment]
So do 2 mices work simultaneously?
Do you mean latency or pre-buffering
problem? If it is latency, try `speed 0`
before starting the game.

**Comment by stefand** [comment]
Yes, both mice function simultaneously - the data routing from the X mouse to PS2(player 1) and /dev/input/mouse2 to COM1(player 2) works.

speed 0 does not help. The "latency" looks to me like serial or mouse input buffering. I guess a modern USB mouse produces more move events per second than an old serial mouse, and settlers 2 consumes every single byte of serial input or every single interrupt, but only does it at the 1200 baud rate a serial mouse would have.

The attached patch is my attempt to hack around the problem, but unfortunately it doesn't quite work the way I want to. It cuts the slow, smooth mouse movement into slow, jumpy movement and the movement still accumulates the delay. A similar concept in the evdev2ser script from post 1 achieved what I wanted.

[mousethrottle.txt](https://github.com/stsp/dosemu2/files/4005131/mousethrottle.txt)

**Comment by stefand** [comment]
I have attached a video to illustrate the input latency. I have intentionally reverted your sermouse routing change. Now the PS2 mouse (left side) and COM1 mouse (right side) read from the X cursor. The PS2 mouse is working as intended - movement from mouse to cursor is instant.

The right mouse (COM1 read by the game directly, not going through any mouse driver) mirrors the same movement, but lags behind. The lag accumulates with movement and goes down when the mouse is not moved. If I only click everything works fine (0:22), but if the mouse is moved clicks arrive delayed too (0:30).

[s2.ogg.gz](https://github.com/stsp/dosemu2/files/4005152/s2.ogg.gz)

**Comment by stsp** [comment]
I'll look at the video at the evening,
mobile now. Please do a few tests:
- see if plain cat of mouse dev in
linux terminal does not produce any
lag (visually)
- see if mousetst from ctmouse
package has a lag or not. For this
you need to activate both sermouse
and commouse.

This will lead us to the isolation of
the slowdown point. Different hacks
on input, like the ones you suggest,
should probably be attempted only
if we inentify S2 as a source of the
problem.

**Comment by stsp** [comment]
Ouch! I just realized that you will have
a problem activating both sermouse
and commouse, and specify the input
dev at the same time! I think there was
some hack that allowed things like
$_mouse_dev="/dev/mouse,com1"
but I am not sure if it still works...

**Comment by stefand** [comment]
I can quickly answer question 1 - no lag when reading /dev/input/mouse2 in a linux terminal.

I'll play around with mousetst and mouse.com. I originally dug out ctmouse with similar motivation - I wanted to run settlers 2 with an old school dos mouse driver on the primary mouse. I ended up with ctmouse because that was the first legally downloadable google hit for "dos mouse driver".

**Comment by stsp** [comment]
You dont need mouse.com: commouse.c
is the same thing. You just need to
stuff 2 values into mouse_dev. I am
quite sure I added the hack for that,
but order of values may matter, so
try swapping them.

**Comment by stefand** [comment]
I don't think I managed to do exactly what you wanted (afaik; read /dev/input/mouseXX into com1, use the builtin mouse on COM1). If $_mouse_internal=on, mousetst picks up the X11 mouse. If it is off, mousetst doesn't read anything (kinda expected).

Protocol.com included in ctmouse gave me some clues though in the following config:
mouse_internal=on
mouse_dev=/dev/input/mouseXX
com1=mouse

In this case mousetst reads the X11 mouse, and running protocol.com dumps binary numbers on the terminal when I move the secondary mouse. It does not seem to have a delay like in settlers 2 - there is some delay when I stop moving (maybe 0.25 seconds), but I attribute that to GUI slowness rather than input queuing.

My theory is that the slowness has something to do how S2 reads the COM port rather than dosemu accidentally queuing up data. No proof though, so take it with a grain of salt.

**Comment by stefand** [comment]
Ah ya, "type com1:" says "Unable to open file - com1:".

**Comment by stefand** [comment]
Ok, more ways I tried to get the builtin mouse driver to read com1. All had mouse_internal=on:

$_mouse_dev = "com1,/dev/input/mouse2"
$_mouse_dev = "/dev/input/mouse2,com1"
_com1=mouse

Both have the secondary mouse on com1 (according to protocol.com), but the mouse driver reads the SDL or xterm mouse. I removed the SDL, xterm and X11 mouse register calls. Now com1 still has the right data, but the builtin mouse driver does not report anything to mousetst.

$_mouse_dev = "/dev/input/mouse2"
com1 = ""
COM1 is dead, as expected, still no response from mousetst.

$_mouse_dev = "com1"
_com1=<pipe written to by my evdev2ser>

This again gives output via protocol.com, but no mouse data from the builtin driver. This might be due to my script not handling RTS signalling, breaking the detection mechanism. At least mouse.com and ctmouse complain that they can't detect a mouse.

**Comment by stsp** [comment]
OK, let me apply some hack (above hack above
hack...) so that $_mouse_dev="x,y" will disable
X/SDL. :)

**Comment by stsp** [comment]
OK, I had to update that 5 years old code,
and in fact, most of all I was saying about ctmouse,
was wrong. The bugs were mine. :)
It still doesn't agree to work with "M3" and has
problems in NDN, but is quite stable otherwise.

commouse should work, please proceed with your testing.

**Comment by stefand** [comment]
Progress!

$_mouse_internal = (on)
$_mouse_dev = "/dev/input/mouse2,com1"
$_com1 = "mouse"

Now reads the secondary mouse into mousetst. There is no delay. In this configuration the main mouse pointer in settlers 2 is now also controlled by /dev/input/mouse2 instead of the X11 mouse. And neither mousetst nor settlers 2 have any delay in this mode (reading the secondary mouse via the mouse driver. Settlers 2 says "Mouse 1 via Driver (PS2)"

However, when I configure things for two player mode I still have the delay when S2 reads com1 directly.

I also tried the following configuration:
$_mouse_internal = (off) #!!!
$_mouse_dev = "/dev/input/mouse2"
$_com1 = "mouse"
run s2 - it complains no driver is loaded, as it should
Load ctmouse
Run s2 - now I have a nicely working main mouse pointer in S2, controlled by the secondary mouse. S2 says "Mouse 1 via Driver (COM1)"

S2 also has a mode where it bypasses the driver entirely (cmdline parameter M1COM1). Interestingly for this mode a driver still needs to be installed, otherwise the game refuses to start. In this mode I have S2's main pointer controlled by my secondary mouse, with delay.

Another tibit: If commouse is active and I read the COM port directly (e.g. via s2 M1COM1 or ctmouse' protocol.com) commouse stops stops working - it will no longer report any mouse data until dosemu is restarted.

But I guess the mouse delay has something to do with how Settlers 2 reads the COM port. Going via the mouse driver (builtin, ctmouse or mouse.com) appears to hide the issue, but that's only an option for the game's first player mouse pointer.

**Comment by stsp** [comment]
> Load ctmouse

How? Have you hacked sermouse.c for it?

> Interestingly for this mode a driver still needs to be installed, otherwise the game refuses to start.

Maybe you can do M2COM1 and use the driver
`$_mouse_internal = (on)` for first mouse?

> protocol.com) commouse stops stops working - it will no longer report any mouse data
> until dosemu is restarted.

They lower DTR and RTS.
If you have some tool like setserial (but for DOS),
you can try to recover that.

In theory, we can route different mices to int33
and PS2, as S2 seems to have both drivers.

**Comment by stefand** [comment]
> > Load ctmouse
> 
> How? Have you hacked sermouse.c for it?
It just worked. I was surprised myself. It did report a Logitech mouse on COM1 when started as you mentioned, but apparently that didn't stop it from understanding your serial data.

> Maybe you can do M2COM1 and use the driver
> `$_mouse_internal = (on)` for first mouse?
That is kinda the default configuration. Although there's no option M2COM1.

> In theory, we can route different mices to int33
> and PS2, as S2 seems to have both drivers.
Afaics S2 never reads PS2 directly, it will only do that via the mouse driver. It can only read serial mice via hardware.

**Comment by stsp** [comment]
> mentioned, but apparently that didn't stop it from understanding your serial data.

But this is really strange, as for me it doesn't
work that way. Does it work in S2 or in mousetst for you?

> If the driver reads PS2, S2 will try

But it is very difficult to find out what does the
driver read. Maybe not even possible. What API
does it use for that?

> Afaics S2 never reads PS2 directly, it will only do that via the mouse driver.

But you are probably mistaken, as I don't know
of any API to find out what driver reads. So I suppose
when it says PS2, it reads PS2, not driver reads PS2.
How have you concluded otherwise, and is that info
reliable?

**Comment by stefand** [comment]
I don't know how S2 figures out what the driver reads. It somehow magically knows where ctmouse and the builtin driver read from. I doubt that it snoops on the COM port though.

I tried the following setup:
$_mouse_internal = (off)
$_mouse_dev = "/dev/input/mouse2"
$_com1 = "mouse"
$_com2 = "mouse"

load ctmouse with ctmouse /S1. Now s2 says on startup:
Mouse driver: Version  7.05.
Mouse type: Serial.
Mouse port: Mouse on COM1 detected.

Unload ctmouse (ctmouse /U), load it with /S2:
Mouse driver: Version  7.05.
Mouse type: Serial.
Mouse port: Mouse on COM2 detected.

And with the builtin driver, standard settings:
Mouse driver: Version  7.05.
Mouse type: PS2.
Mouse port: PS2 mouse detected.

(Is there a way to emulate PS2 hardware and run it with ctmouse or no driver at all?)

ctmouse apparently only works with S2. mousetst.exe reports some movement, but only once.

The other thing I am pretty sure about is that direct reading from COM1 or COM2 is the only way to feed a second mouse into S2. I would be very surprised if there's a way to make the second player mouse go through the driver.

**Comment by stsp** [comment]
Let me guess that it checks which COM
port has 1200bps, and if none - checks PS2.
Or maybe it checks PS2 first.
The problem is that `$_mouse_internal = (off)`
also disables PS2, so checking that precisely
is difficult.

> (Is there a way to emulate PS2 hardware and run it with ctmouse or no driver at all?)

Not without a few more hacks.
But this is what I was proposing to do.

> I would be very surprised if there's a way to make the second player mouse go through the driver.

Even checking that out would require some
work. But I am more positive in its success
than you are. :)
The driver is there, the one should just decouple
it from the int33 mouse driver and try things separately.

**Comment by stefand** [comment]
With commit ae76b4d8a my mousethrottle.txt hack starts to work. It is not as smooth as the primary mouse, and if I jerk it around violently there is some buffering remaining, but certainly makes the secondary mouse playable. I see that I uploaded a bad file earlier though - the if check added is obviously broken. I am adding a new one here:

[mousethrottle.txt](https://github.com/stsp/dosemu2/files/4006152/mousethrottle.txt)

One more factoid (still not proof) that mouse #2 will only work via direct reading of COM ports are the strings in the game:

(ONGAME.GER)
Maus I über Treiber (PS2 mode).
Maus I über Treiber (COM1).
Maus I über Treiber (COM2).
Maus I besitzt kein Treiber oder unbekannten Typ.
Maus I seriell über COM1.
Maus II direkt über COM1.
Maus II direkt über COM2.

(S2.EXE)
TRY COM%d FOR SECONDARY MOUSE, BECAUSE OF PRIMARY PS/2 MOUSE!

Yeah, sorry, the game is a german-english mess. The "über Treiber" part can be roughly translated to "via driver", and "direkt über COM1" as "direct via com1". Note that there's no Mouse II that mentions the driver.

**Comment by stefand** [comment]
The smoothness of my mousethrottle.txt hack are comparable to the evdev2ser script. It helps the overall gameplay a lot to reduce the X11 screen resolution to 1024x768 instead of having dosemu upscale the window to 3840x2160. But that's a topic for a different bug :-) .

**Comment by stsp** [comment]
For upscale you need $_sdl_hwrend.
Filtering will also work.
Good that you have found a work
around and can at least play S2.
But this is not something I'd like to
apply (at least I'd say it shoud flush
on a button presses so that they
happen on a right coord, should
have a flush timeout if no more
events come, etc).
I'll try to find some time to debug
S2 and maybe to find out why this
all happens.

Auxillary questions.
Have you tried dosbox for the same
task?
Have you tried S2Anniversary under
wine?
I find S1 nicer than S2. :)

**Comment by stefand** [comment]
Yeah, the point of the hack is to illustrate a potential path to a fix, I never intended to upstream it. Besides the points you mention, it will break with future mice if the 1:4 move event ratio needs changing.

> Auxillary questions.
> Have you tried dosbox for the same
> task?

Sorta. I tested it with my converter script. Dosbox attempts to program the HW ttySx, which fails on a pipe. I hacked out the hardware specific parts, but S2 apparently tried to set various modes (7 data bits, 8 data bits, RTS low, RTS high), presumably in an attempt to detect what weird mouse is connected here. I guess it is a miracle that this script works with dosemu2.

Besides the secondary mouse, dosbox is too slow to run the game when playing bigger maps. I blame it on the CPU emulator. The easy way to see the difference is to load a game in its advanced state with big road networks, enter the "WINTER" cheat code (just type, without quotes), then press alt-6 to set the game to 6x speed and scroll the map. Dosbox will update about once a second on modern HW, Dosemu1/2 still scroll fluently. My old 600 MHZ AMD Duron was somewhere between the two - certainly slower than dosemu on new HW.

The speed difference matters in real games on maxed out map sizes. But the wisdom of playing something that huge is questionable, it'll take days to get to that point :-) .

> Have you tried S2Anniversary under
> wine?

Yes, it works pretty well. It is not the same game though :-) . In particular, the fancy graphics make me feel blind.

There's also s25rttr, a GPL rewrite of the game engine used with the original game assets. The nice bits are network support and some settings to fix some balancing problems (In the original game, whoever has gold first wins, period). It lacks a working AI though and has its share of bugs too.

> I find S1 nicer than S2. :)

Tbh I never tried S1.

**Comment by stefand** [comment]
Ah yes, I'd vote to reopen this issue until the serial mouse latency is fixed

**Comment by stsp** [comment]
You can always open a new,
more specific ticket. Binding too
many fixes to one ticket will trouble
the NEWS writing.
I think dosbox also has things
similar to sermouse&commouse
so why did you need a script?
No support for 2 mices?

You should at least give a brief
look to S1. :) The things that always
annoied me in S2 were that they
removed that cool music (but you
can still get it back by replacing
the midi files) and simplified the
knight fights. In S1 the knight fights
had lots of different animations,
like ducking, jumping over the
opponent's sword etc. In S2 the
fights are dull (but the economic
is a bit more advanced).

**Comment by stefand** [comment]
Ok, I'll file a new one :-)

My dosbox investigation re 2 mice went as far as a google search. The only "here is how you do it" tutorial (http://jh-isch.de/s2/tipps/t_dosbox.php) talks about attaching a serial mouse to a real serial port and using directserial to make dosbox talk to it. Due to the performance issues I mentioned dosbox was never going to be what I wanted anyway.

The S2 history edition release supposedly supports two mice by talking to the Windows HID layer. It'll be fun to make that work in Wine...

**Comment by stsp** [comment]
I made it so that you can now recover
commouse with `emumouse r`.

As for S2 - I am not able to see the second
mouse. In settings it says there is, but just
one cursor.
Could you please attach the `-D9+ms` log
after reproducing the COM mouse lags?

**Comment by stefand** [comment]
To see the second pointer you have to start a "free game" (no idea what the exact english label is. It is "Freies Spiel" in german) and set Player #2 to Human. (botton on the right side)

**Comment by stsp** [comment]
Should now be fixed, enjoy.

**Comment by stefand** [comment]
Works nicely now, thanks! For the sake of completeness I tested this with gpm, works nicely too. This might come in handy for people who have a weird protocol second mouse or want to do some other teaks with it.

To satisfy my curiosity: Did you investigate how the game finds out what mouse the driver uses and how it accesses the PS2 mouse?

**Comment by stsp** [comment]
I tried disabling int33 and didn't see it
using int15 for PS2. so I guess you were
right that it can't do that.

As for any detection - I don't think it does.
For example, no matter whether I configure
COM1 or not, it says primary mouse PS2
and secondary mouse on COM1 (even on
disabled one!).
I am not reading its boot messages, I am
just looking up that info in options. Maybe
in boot messages it is more accurate?

**Comment by stefand** [comment]
Nah, the boot messages say the same thing. And yes, mouse 2 by default follows mouse 1.

mouse 1 -> mouse 2
PS2 -> COM1
COM1 -> COM2
COM2 -> COM1

The only way to change that is M2COM2, which will put it on COM2 if mouse 1 is PS2.

**Comment by stsp** [comment]
So the "detection" logic is very simple. :)
It doesn't even check the PS2 mouse via int11
(tried to disabled it - still says PS2).
Also its detection of serial mouse breaks
real serial mouse. For example if I enable
sermouse+commouse and run s2, then
mouse stops and I need to do `emumouse r`
to recover.

**Comment by stsp** [comment]
While with commouse S2 steals the
COM port from it (and nothing works),
with ctmouse it does not. So indeed
somehow it can distinguish ctmouse
and commouse...

**Comment by stsp** [comment]
OK, I am silly.
There is indeed the detection API!
Should now work properly.

**Comment by stsp** [comment]
It appears there will be The Settlers 2020 -
a remake of S1. I doubt they return
the S1-alike knight fights though, so
perhaps not worth a try, but who knows.

**Comment by stsp** [comment]
And according to the videos, they
actually will have something like S1
style knight fights. Hope they will
also have the S1-style music. :)
