### ISSUE TITLE
keyboard in MS-DOS 7.1 and 8.0 do not seem to work

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#975]
**Describe the bug**
7.1 briefly shows the windows logo, then black screen.
8.0 shows garbage.

**To Reproduce**
Just try to boot.

**Attach the binaries or provide an URL**
http://www.manmrk.net/tutorials/bootdisk/index.htm

Andrew, any idea if that works, and if so - how?

**Comment by andrewbird** [comment]
I haven't tested recently but I believe you have to add logo=off or suchlike to msdos.sys.

**Comment by stsp** [comment]
Indeed, MS-DOS7 is cured by
```
[Options]
BootGUI=0
Logo=0
```
You need to disable both.
Disabling only Logo brings up the boot menu
but keyboard doesn't work. Not sure if it is a bug.

DOS8 is not cured.

**Comment by stuaxo** [comment]
Adding MODE CO80 at the end of autoexec.bat along with a suitable replacement logo is good on these DOSes.

**Comment by stsp** [comment]
Have you tried that with dos8?
I don't think it goes to autoexec.
I think our loader loads it wrongly.
Strange that no one tried that before.

**Comment by andrewbird** [comment]
Just looking through my test binaries I have no MS-DOS 8.0, so I'd be surprised if I have tested it or added support to the loader. From memory I think there were so many hacked up versions around I wasn't sure what I'd be testing or adding. Did you try booting it off a bootable floppy image?

**Comment by stsp** [comment]
Mm, dos8 image is indeed unbootable.
Thanks.
Most of everything is clear.
I still do wonder why the keyboard in boot menu
of dos7 doesn't work.

**Comment by stsp** [comment]
But it would be good to find the proper DOS8
image somewhere.

**Comment by stsp** [comment]
https://www.allbootdisks.com/download/me.html
Its here.
But still the same keyboard problem.

**Comment by stsp** [comment]
Yep, also extracted image boots fine.
So www.manmrk.net/tutorials/bootdisk simply provides
bad image.

**Comment by stuaxo** [comment]
I was trying to work out what an offical image of DOS 8.x would contain and where to get it.
This page has a lot of info about DOS 8.x http://www.multiboot.ru/msdos8.htm along with patches.

Some interesting info is that diskcopy.dll in Windows XP onwards [contains a disk image of ms-dos 8.0 (4.90.3000)](https://www.betaarchive.com/forum/viewtopic.php?f=6&p=129169), slightly modified from the version that comes with ME.  This would should count as an official version.

This is used by the utility in Windows that can make a boot disk.

**Comment by stsp** [comment]
You can try to boot it. ;)

**Comment by stuaxo** [comment]
OK, I'll see if I can find one of those versions of Windows and make the disk with it, as I don't trust random versions on the net to not have been altered.

**Comment by stuaxo** [comment]
Steps to get the disk image - find your copy of diskcopy.dll, then use `wrestool` to extract the image:

```
$ wrestool diskcopy.dll --type='BINFILE' -x -R -o msdos8.img
```

Mounting the image, or using mtools shows the expected files:

```
$ mdir -i msdos8.img
16:10:17 
 Volume in drive : has no label
 Volume Serial Number is 2A87-6CE1
Directory for ::/

COMMAND  COM     93040 2005-04-18  17:54 
DISPLAY  SYS     17175 2005-04-18  17:54 
EGA      CPI     58870 2005-04-18  17:54 
EGA2     CPI     58870 2005-04-18  17:54 
EGA3     CPI     58753 2005-04-18  17:54 
KEYB     COM     21607 2005-04-18   3:04 
KEYBOARD SYS     34566 2005-04-18  17:54 
KEYBRD2  SYS     31942 2005-04-18  17:54 
KEYBRD3  SYS     31633 2005-04-18  17:54 
KEYBRD4  SYS     13014 2005-04-18  17:54 
MODE     COM     29239 2005-04-18  17:54 
       11 files             448 709 bytes
                            889 344 bytes free
```

I got stuck then, as I couldn't work out how to get dosemu to use the disk image.

I tried creating a `~/.dosemurc` and with 
```
$_vbootfloppy = "/home/stu/projects/mine/scratch/extract-dos-from-diskcopy/msdos8.img"```

but dosemu isn't happy, including with `-A`

```$ dosemu -A
ERROR: Drive A: not defined, can't boot!
```

**Comment by stsp** [comment]
Use `$_floppy_a` and `$_bootdrive="a"`

**Comment by stuaxo** [comment]
That boots and seems to work (only tried `dir` so far)

![image](https://user-images.githubusercontent.com/179677/71590233-990d7d00-2b1f-11ea-8fcf-5bcc207c9b41.png)

I'll come back to this later + make sure everything is up to date dosemu2 wise and try some other features.

Definitely interested to poke around the deleted files on this disk + see the README.txt that talkes about how the image was made.

**Comment by stsp** [comment]
What didnt work is a boot menu.
Something you don't have here.

**Comment by stuaxo** [comment]
I can confirm the bug.

DOS is still running as normal, it's just that nothing is displayed.

If you type `MODE CO80` then the screen is restored.

I've always wondered how the logo works (since text underneath is restored when you press ESC IIRC).

I guess the text goes to the usual address for text mode, and that doesn't interfere with the graphics on screen - DOS can redirect those, but does it go to any lengths to redirect stop apps from using BIOS functions to output text too ?

**Comment by stuaxo** [comment]
On the DOS 8 image (WindowsME.img from Allbootdisks), the boot menu works, but some device drivers can stop boot from proceding:

"QUICK": runs as normal.

"NOCD":  Gets stuck loading ramdrive.sys:

```
devicehigh=ramdrive.sys /E 2048
```

"CD"
This tries various device drivers in turn, only one of them causes dosemu to stop booting though, along with ramdrive:

```
device=aspi2dos.sys
devicehigh=ramdrive.sys /E 2048
```

"HELP"
This option is the same as "CD", but is calls HELP.BAT, one of the files in EBD.CAB, which the disk would normally extracted to the ramdrive.

**Comment by stsp** [comment]
May be good to support ramdrive
eventually, but this is a low prio
problem and likely not a regression.

**Comment by stuaxo** [comment]
That makes sense.

It seems to be the `/E` option (use extended memory) that is killing ramdrive.

I tried running the ramdrive in conventional memory:
```
devicehigh=ramdrive.sys 360
```

The driver does make a ramdrive and some of the tools are extracted there, a bit too small for all of them though :)

**Comment by stsp** [comment]
ramdrive can have another ticket.
