### ISSUE TITLE
GWBASIC 3.23 Crashes

### ISSUE THREAD

**Issue by Tubatstuff** [stsp/dosemu2#983]
Using  dosemu2 (2.0~pre8-5863-dc3a772+202001061417~ubuntu18.04.1), GWBASIC 3.23 now corrupts the screen and hangs.   Worked fine two weeks ago.

**Comment by stsp** [comment]
Please provide binaries or URLs,
instructions to reproduce the problem,
screen-shots and any other needed
info.

**Comment by Tubatstuff** [comment]
Just run GWBASIC from a command prompt.   (Binary attached).  FWIW, runs fine under original DOSEMU as well.  Program originally distributed with MSDOS 3.0.


[gwbasic.zip](https://github.com/stsp/dosemu2/files/4031705/gwbasic.zip)

**Comment by stsp** [comment]
Thanks, should now be fixed.

**Comment by Tubatstuff** [comment]
It appears to be working again, thanks!
