### ISSUE TITLE
Configure TAP bridge in dosemu.conf

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#987]
When using `$_vnet = "tap"`, I have to run `sudo brctl addif br0 tap0` in another terminal to get connectivity. It would be nice if I could configure a bridge in `dosemu.conf` that the newly created tap device would be automatically added to when starting dosemu.

Note that I already have`virbr0`, `lxcbr0` and `docker0` bridges devices configured automatically by respectively libvirt, lxc and docker that provide a bridge to a network with DHCP, DNS, IP masqueraded NAT, etc. VMware and VirtualBox also introduce their own bridge devices. DOSEMU might as well ship a config which by default sets up a `dosemubr0` bridge :)
I should investigate how those other bridge devices are set up.

**Comment by stsp** [comment]
I'd prefer slirp.

**Comment by jschwartzenberg** [comment]
Me too, but it won't handle all usecases. QEMU supports both as well. Being able to automatically put the tap device in a bridge would be helpful for the usecases that slirp won't support.

**Comment by stsp** [comment]
You don't need to do any command.
Create a persistent tap device owned
by the user.

**Comment by jschwartzenberg** [comment]
But that requires initial manual setup for each dosemu user. It's neater to have dosemu allocate tap devices and add them to a bridge by itself.

**Comment by stsp** [comment]
You can use IP forwarding.
Then you don't need any bridge.

**Comment by jschwartzenberg** [comment]
I don't see how it makes things easier. Then the IP configuration and forwarding configuration needs be to done manually as well instead of running a DHCP server on the bridge interface.

**Comment by stsp** [comment]
> But that requires initial manual setup for each dosemu user.

To avoid this, you can create the "tap" group.

**Comment by jschwartzenberg** [comment]
I don't think so. Each tap device is assigned to a particular user. Two instances cannot share one tap device.

**Comment by stuaxo** [comment]
+1 having dosemu able to set this up, with docker, virtualbox etc I know they use bridge networking but I dont need to know much about the details.

(No preference slirp vs bridge but it sounds like tap is almost all there already?)

**Comment by stsp** [comment]
> I don't think so. Each tap device is assigned to a particular user.

Yes, seems no group-level control. :(

**Comment by stsp** [comment]
In fact, the one can just set up tap
devices with NetworkManager:
https://mail.gnome.org/archives/networkmanager-list/2016-January/msg00049.html
It seems, this does not require root.
Bridges are supported too:
https://www.cyberciti.biz/faq/how-to-add-network-bridge-with-nmcli-networkmanager-on-linux/

Just why it normally requires root but
with NM you can do that from user, is
what I don't know but maybe someone
else does.
This means dosemu could do that too,
either by executing nmcli or sending
the dbus messages to NM. But IMHO
a much simpler solution is to allow to
assign the tap interfaces to a group
rather than to a particular user. This
should be a trivial change to the kernel
and tunctl, and no change at all to dosemu.

**Comment by stsp** [comment]
TUNSETGROUP ioctl is alredy there!
Looking...

**Comment by andrewbird** [comment]
> Just why it normally requires root but
with NM you can do that from user, is
what I don't know but maybe someone
else does.

NM daemon runs as root, user mode clients communicate with it over DBUS.

**Comment by stsp** [comment]
> NM daemon runs as root, user mode clients communicate with it over DBUS.

Obviously. :)
Please explain why it is still secure.

> I don't think so. Each tap device is assigned to a particular user.

OK, this is wrong.
man page documents `-g` switch, but it
is not visible in `SYNOPSIS`, so we both
didn't know about it.
So the fix here is just to patch up the man page.

**Comment by andrewbird** [comment]
From what I remember DBUS is not exposed to the networks and there's a policy in place for what DBUS services a local user can access, see https://linux.die.net/man/1/dbus-daemon-1

**Comment by stsp** [comment]
> From what I remember DBUS is not exposed to the networks

Same with ifconfig/brctl, but they require root.

> and there's a policy in place for what DBUS services a local user can access

Obviously he can access the NM service,
not requiring root for that, and yet it is safe...

Anyway, the group control to tap does exist,
which is the whole point of this discussion.

**Comment by jschwartzenberg** [comment]
Assigning tap devices to a group doesn't solve the problem. If you set up one tap device for one group, then only one user can run only one instance with networking. The second instance with the same configuration will show `ERROR: PKT: Cannot open tap0: Device or resource busy`.

With dynamically allocated tap devices, they can all be added to the same bridge. If that's configurable, then any number of instances can be started and they'll all be using this bridge. The only other option I can come up with is some lines inside `autoexec.bat` which resolve the tap device name that was allocated and perform a DBUS call (through `unix`) to add this device to a bridge.

**Comment by stsp** [comment]
> If you set up one tap device for one group,

No need to set one! Set 10.

> With dynamically allocated tap devices, they can all be added to the same bridge.

With pre-allocated - same thing.
The only thing I can offer is to specify
the range of devices, so that dosemu
tries to find the first free one.

**Comment by jschwartzenberg** [comment]
Why this silly limit of 10 or any number? I really see no advantage over allowing a range of preconfigured tap devices over just setting one up after allocating it.

**Comment by stsp** [comment]
There is no any limit.
You configure N devices and assign
them all to groups "tap". You add them
all to your bridge. You tell dosemu2 to
please iterate from tap0 to tapM where
`M<=N`.

**Comment by jschwartzenberg** [comment]
Then your non-root users can run a maximum of N dosemu instances with networking. That's a limit.

**Comment by stsp** [comment]
At least this is a working solution.
Try to find some way for NM to
automatically up every new tap device
and add them to your bridge. I think
this is possible, let us know about your
findings.

**Comment by stsp** [comment]
udev can do that easily btw.
No need for NM even!
There is no problem to solve.

**Comment by jschwartzenberg** [comment]
But I only want dosemu TAP devices in that bridge. Not every new tap device. I will do some investigation and see what's possible through DBUS though.

**Comment by stsp** [comment]
> But I only want dosemu TAP devices in that bridge.

Again no problems!
```
$_tapdev = "dosemu_tap%d"
ifconfig -a
dosemu_tap0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether f6:d7:03:76:ff:bb  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Where is the problem?

**Comment by stsp** [comment]
And here's the patch that does exactly that.

**Comment by stuaxo** [comment]
Do all the places in the docs that mention tap0 need updating to be dosemu_tap0 too ?

`https://github.com/stsp/dosemu2/search?q=tap0&unscoped_q=tap0`

**Comment by stuaxo** [comment]
@jschwartzenberg I had a bit of a play with creating a bridge via nmcli last night, but got a bit lost near the end - I wasn't sure what IPs I should be assigning to what, and if I should be bridging the network to my wifi to make things work.

Do you have info for manually setting up dosemu with bridging (that requires root) ?
I'm happy to try and convert this to nmcli + nonroot, which may be handy to reference if you are going to look at an implementation that speaks DBUS instead.

**Comment by stsp** [comment]
Yes, done.

**Comment by stsp** [comment]
@stuaxo there is a full-featured example in docs,
with explanations:
```
    brctl addbr br0
    ifconfig eth0 0.0.0.0 promisc up
    brctl addif br0 eth0
    ifconfig br0 192.168.1.10 netmask 255.255.255.0 up
    tunctl -u 500
    ifconfig tap0 0.0.0.0 promisc up
    brctl addif br0 tap0
```
(not copying the explanations here).
What more info do you need?

> look at an implementation that speaks DBUS instead.

The solution is in a trivial udev script, not in dbus.
It can match newly created `dosemu_tapN` devs by
a pattern match, and apply any actions you want on it.

**Comment by stuaxo** [comment]
A udev script is definitely convenient..  I'm still fuzzy on br0 + tap0 .. do I create a tap1 for the next dosemu, and then connect it to the existing bridge, or do I need br1 too ?

**Comment by stsp** [comment]
You can have single bridge if you
want multiple dosemus to communicate.

**Comment by jschwartzenberg** [comment]
I still don't really get how this would work. I understand now device names will be allocated with the `%d` bit filled in? So I can specify `dosemu_tap%d` and put the udev script in place which would put them all in a bridge and also run with another config containing `dosemunobr_tap%d` and those won't be treated the same way?


> @jschwartzenberg I had a bit of a play with creating a bridge via nmcli last night, but got a bit lost near the end - I wasn't sure what IPs I should be assigning to what, and if I should be bridging the network to my wifi to make things work.

With wired ethernet you can put both your ethernet interface and the dosemu tap interface in the same bridge. Your bridge device would be assigned an IP address (or use DHCP) and your dosemu instance would be on the same ethernet network and get an IP address the same way.

With wifi that usually won't work. You can create a bridge with an IP address configured and multiple DOSEMUs tap devices in it. You can run dnsmasq on the bridge interface and you can use IP forwarding with NAT+IP masquerading to allow dosemu instances to connect to hosts over wifi. Bridges preconfigured that way are set up by default by docker, libvirt and lxc (and could be used with dosemu too).

You should always assign IP addresses to the bridge interfaces, not to any of the devices you put in an bridge.

**Comment by stuaxo** [comment]
The wifi setup sounds a bit complex, but I already have the bridge setup by libvirt, so this might be an avenue to test first.

I'll try adding a tap interface to it for dosemu, if that works, I can see try and replicate it in a bridge created for dosemu.

poking the bridge + interfaces from libvirt, shows some of the info about the setup you mentioned:
```
$ brctl show virbr0
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.525400948077	yes		virbr0-nic

$ nmcli device show virbr0
GENERAL.DEVICE:                         virbr0
GENERAL.TYPE:                           bridge
GENERAL.HWADDR:                         52:54:00:94:80:77
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     virbr0
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/1
IP4.ADDRESS[1]:                         192.168.122.1/24
IP4.GATEWAY:                            --
IP4.ROUTE[1]:                           dst = 192.168.122.0/24, nh = 0.0.0.0, mt = 0
IP4.ROUTE[2]:                           dst = 169.254.0.0/16, nh = 0.0.0.0, mt = 1000
IP6.GATEWAY:                            --

$ nmcli device show virbr0-nic 
GENERAL.DEVICE:                         virbr0-nic
GENERAL.TYPE:                           tun
GENERAL.HWADDR:                         52:54:00:94:80:77
GENERAL.MTU:                            1500
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
```

**Comment by jschwartzenberg** [comment]
Yep, that should work. Just add the tap device that dosemu creates/uses to virbr0. Then DHCP inside dosemu will give you an address in 192.168.122.0/24 and the NAT+IP masquerading should work as well.

**Comment by andrewbird** [comment]
When I was messing with ne2000, I added my tap device to the virbr0 bridge made by libvirt. It worked quite well allowing mbrutmans mtcp dhcp to grab an address from it. Just be aware that on my system libvirts dhcp server only gave out leases of one hour, and that's below what mtcp clients consider valid, so you may have to tweak the dhcp conf a little.

**Comment by stsp** [comment]
> containing dosemunobr_tap%d and those won't be treated the same way?

Depends on the matching pattern you use
in udev script.

**Comment by jschwartzenberg** [comment]
Great that should indeed provide fully flexibility then!

**Comment by stsp** [comment]
Not quite, because this requires root (dosemu -s).
So I would still suggest to pre-allocate 10
tap devices and assign them to a group.

**Comment by stuaxo** [comment]
Creating tap devices from `nmcli` seems fairly straightforward, but I didn't get everything working enough yet to know it works for sure.

I'm definitely curious about what docker does, I couldn't see a docker bridge network when I ran it, but I could `apt-get`, and `ping 8.8.8.8` from it.   I guess I need to check it further.

DOSEMU logs seemed to imply packets were being sent, but I guess I hadn't configured my bridge properly as mtcp `DHCP.exe` was never happy enough to write a config file.

**Comment by jschwartzenberg** [comment]
I'm not sure what's going on. I still see `tap0` being created instead of `dosemu_tap0`.

**Comment by stuaxo** [comment]
I assumed I had to use tap0 as I hadn't updated dosemu yet.

Had another go after creating the bridge network with virt-manager, this time when I run DHCP it writes settings but all the apps then complain the lease time is less than 3600 seconds.  So next step is debugging that.

**Comment by jschwartzenberg** [comment]
You probably need to change the dnsmasq configuration that libvirt uses so that it gives out a longer lease time.

**Comment by stsp** [comment]
> I'm not sure what's going on. I still see tap0 being created instead of dosemu_tap0.

Maybe you have `$_tapdev` uncommented.

**Comment by jschwartzenberg** [comment]
No, it's commented out.

**Comment by stsp** [comment]
Is that a dynamic tap that didn't exist
before, and is created only with `dosemu -s`?

**Comment by jschwartzenberg** [comment]
Yes, it's created when I start `dosemu -s` and it disappears when quitting that session.

**Comment by stsp** [comment]
Please add the -D9+cnP log.

**Comment by jschwartzenberg** [comment]
The problem is still there, here's the log:
[boot.log](https://github.com/stsp/dosemu2/files/4302577/boot.log)

**Comment by stsp** [comment]
OK, for automatic allocations
(dosemu_tapX) you need to uncomment and set
`$_tapdev = ""`

**Comment by stsp** [comment]
And use `dosemu -s`.

**Comment by jschwartzenberg** [comment]
So was the default changed? In an old config file I have:
```
# Network device for packet driver in "tap" mode.
# Default: "" (dynamic TAP allocation)

# $_tapdev = ""
```

Wouldn't it make sense to have the dynamic allocation as default again?

**Comment by stsp** [comment]
No, it requires root.
