### ISSUE TITLE
Settlers 2 crashes when showing credits

### ISSUE THREAD

**Issue by stefand** [stsp/dosemu2#989]
Settlers 2 crashes when clicking the "credits" button in the main menu. It leaves behind garbage on the screen. If you redirect its output to a logfile you can see it complains about a file:

```
CRITICAL ERROR: FILE::RESET: D:\S2\gfx\pics2\credit00.lbm!
OUTER MAIN LOOP ERROR: FILE: D:\S2\gfx\pics2\credit00.lbm - ERROR 5 - Access denied!!

```
The file is on the CD, which is mounted via lredir -C. Reading the file with "type D:\S2\gfx\pics2\credit00.lbm" works OK. (EDIT: I originally wrote "imgmount -C", too much dosbox influence...)

I suspect the game is trying to open this file with write access and expecting it to succeed. If I copy the CD data to a writeable place and give myself write access to all files the credits play.

**To Reproduce**
1) Make sure settlers 2 has its CD. My usual way to test it is to run "siedler2.exe", which plays the intro. If the intro works the CD should be there. (I don't know how the english binary is named. It's not "s2.exe")
2) Start the main game
3) Click the credits button right above the quit button

**Attach the log**
I made a -D9+CD log; If you need any other channels let me know.
[boot.log.gz](https://github.com/stsp/dosemu2/files/4079318/boot.log.gz)

**Comment by stsp** [comment]
If it is trying to open the file in rw
mode, why is this a bug to disallow?

**Comment by jschwartzenberg** [comment]
Maybe it would be good to try different variations of cdrom support to analyze in which circumstances the problem occurs. There is also a `cdrom.sys` which can work with devices from cdemu.

**Comment by stefand** [comment]
The bug is that the game crashes. If the rw thing is the actual fault, a symptom, or the problem is in the error handling I don't know yet.

@jschwartzenberg good point. I tested shsucdx and the game loads the credits fine from the CD.

**Comment by stefand** [comment]
Actually, I used whatever builtin cdrom.sys dosemu has (devicehigh=dosemu\cdrom.sys) and then loaded SHCDX33E.COM /D:MSCD0001 . That was enough to work around this bug.

**Comment by jschwartzenberg** [comment]
Maybe those cdrom drivers allow opening a file in read+write mode and they only error out when there's an actual write attempt.

**Comment by stsp** [comment]
I have no idea what imgmount is.
Can you reproduce that with loop mount
and then `lredir -C`?

**Comment by stefand** [comment]
Er, that was a typo when comparing things to dosbox. I mean lredir -C, i.e. to get the game to recognise the CD as CD.

**Comment by stsp** [comment]
Please provide the link to CD image.
Just making the regular version a CD
drive doesn't reproduce the problem.

**Comment by stsp** [comment]
With proper setup.ini it works well:
`SOURCE_PATH=I:\S2\`
and in dosemu:
`lredir2 -nC <mountpoint>`

**Comment by andrewbird** [comment]
In #695 I said
>>  Should mapping a cdrom e.g. lredir -nC2 /tmp automatically set the readonly option? I'm unfamiliar with Dosemu and cdroms, with my patch currently a drive mapped as above is writable.

In response you said this:
> No, -R is read-only.
cdrom should be R/W. but write should
return an error.
We have a bug `this one` where this is not the
case if the underlying FS is R/O. For cdrom
we need to ignore R/O.
Would you like to take a look into that mess?

As I said in the other ticket I'm unfamiliar with CDROM usage on Dosemu, and my experience on DOS is limited to the oem device driver + MSCDEX pairing.
  a) I can't remember under DOS what that combination gave me could I list the filesystem as a drive, or was it just audio and block level access?
   b) So skimming the Dosemu source cdrom.s / mscdex.c seems to give DOS audio and block level access to /dev/cdrom. Furthermore lredir.c / mfs.c seems to provide a host mounted filesystem of /dev/cdrom, say /media/cdrom, to the DOS drive letter. Is that correct?

**Comment by stsp** [comment]
I think mscdex is a kind of redirector, so
it provides the FS access + sector-based API.
So of course you get another drive.

> Is that correct?

I think so, even though in DOS, mscdex itself
installs the redirector. As we already have the
redirector, our mscdex is quite small.

As for this particular bug - its only about adding
a cdrom check in open(). I think I'd rather do it
myself, as its trivial and @stefand already sent
me a cd image for testing. So its better to not
trouble you with that.

**Comment by andrewbird** [comment]
Sure, that's fine. I was thinking on a little further about the image support.

**Comment by stsp** [comment]
That would be exceptionally cool!

**Comment by andrewbird** [comment]
Actually I see the ticket #876 does describe a lot of what I've been asking about today. I also wonder if there's any FS code in `shsucdx` that might be of use for it. Anyway I'll move the image discussion to the aforementioned ticket, as this ticket's for your read only issue.

**Comment by stsp** [comment]
I applied the untested patch, could you please
see if it helps?

**Comment by stefand** [comment]
I'll have a look next time I boot to Linux

**Comment by stefand** [comment]
Yep, works as expected!

Just in case you ever get a bug about the intro not working - it only works if you start siedler2.exe. If you run s2.exe and click the "intro" button the game will just exit. On top of that siedler2.exe expects the cdrom in drive D:\

**Comment by stsp** [comment]
Have you got the intro working
under dosemu2 with cdrom on drive D?

**Comment by stefand** [comment]
Yes.

What I do is set up a pile of placeholder drives in dosemu.conf and then lredir -f them to something else (lredir -fC in case of drive D:). That way dosemu's many drives go somewhere higher.

Some time I'll file a bug about lredir -d not deleting a drive mapping thoroughly enough to be able to reuse the letter with mscdex/shsucdx/shsucdhd, but other than playing with image mounting via shsucdhd lredir -C works fine for my purposes.

**Comment by stsp** [comment]
Mm, configuring the placeholders
sounds like an interesting idea.

**Comment by andrewbird** [comment]
> Some time I'll file a bug about lredir -d not deleting a drive mapping thoroughly enough ...

The thing is that lredir -d on one of the magic dosemu drives only reveals the underlying FAT drive. To do any more would be removing a block device from DOS. There's a utility called drvswap over at bttr-software.de that should allow you to rename that block device out of the way.

**Comment by andrewbird** [comment]
Since making my last comment I've been reading the docs on that utility!  It suggests that it modifies the DPBs to achieve the rename, so that may not be effective if you want to exchange a block device drive letter with a CDROM or network device.

> Mm, configuring the placeholders
sounds like an interesting idea.

I wondered if a simple device driver skeleton could ask DOS to allocate a number of units with the minimum of driver memory overhead that a corresponding utility could then recognise those drives and allow deletion of its DPB in CDS, but not sure that would help as I think you allocate the Dosemu2 drives before processing config.sys.

**Comment by stsp** [comment]
> any more would be removing a block device from DOS.

This is not needed.
Only `lredir -n` does not pick up such drives.
You can redirect on them explicitly, w/o any problem.

> allow deletion of its DPB in CDS, but not sure that would help as I think you allocate
< the Dosemu2 drives before processing config.sys.

Right.
But we can simply ask fdpp to reserve some letters.
https://github.com/stsp/fdpp/issues/124

**Comment by stefand** [comment]
This bug is back as of current devel. I didn't yet run a regression test, but it was already broken before 1a4c7d882507be667b870b4462de2d5734cedc8c (#1490)

**Comment by stefand** [comment]
[s2fix.txt](https://github.com/dosemu2/dosemu2/files/6604032/s2fix.txt)

This hack fixes the re-incarnation of this bug. Git blame points towards 3222e9a745ba9bbae4268a426e8156b708fb973f, but the bug was already back before this commit.

**Comment by stsp** [comment]
I think this should now be fixed.
Please check.

Andrew, is there a test to open
a file with R/O attr as read/write?
Should this fail?

**Comment by stefand** [comment]
Yap, works again! Thx!

**Comment by andrewbird** [comment]
> Andrew, is there a test to open
a file with R/O attr as read/write?

I don't believe so, but you may have asked me before for one. I seem to remember pondering what the semantics should be, and vaguely recall thinking that I'd have to test this out on a FAT image of a floppy. Is this a DOS specific 'feature' because if I do this on Linux I get.
~~~
$ ls -l rofile
-r--r--r-- 1 ajb sphere 0 Jun  7 10:04 rofile
~~~

~~~
>>> import os
>>> fd = os.open("rofile", os.O_RDWR)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: 'rofile'
~~~

**Comment by stsp** [comment]
I believe the same is true also
for DOS, but it would be better
to have a test.
Another test may be to have the
R/O mount but no R/O attribute,
in which case the RW open
_should_ success.

**Comment by andrewbird** [comment]
So I just tried your suggestion, but on Linux.
~~~
$ mkfs -t ext3 /tmp/image
mke2fs 1.45.5 (07-Jan-2020)
Discarding device blocks: done                            
Creating filesystem with 2560 4k blocks and 2560 inodes

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (1024 blocks): done
Writing superblocks and filesystem accounting information: done

# mount /tmp/image /a
# touch /a/file
# chmod 666 /a/file
# umount /a
# mount -o ro /tmp/image /a
# ls -l /a
total 16
-rw-rw-rw- 1 root root     0 Jun  7 10:38 file
drwx------ 2 root root 16384 Jun  7 10:37 lost+found
~~~

~~~
>>> fd = os.open("/a/file", os.O_RDWR)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 30] Read-only file system: '/a/file'
~~~

So presumably on DOS the `open(O_RDWR)` would succeed, but any `write()` would fail?

**Comment by stsp** [comment]
Seems so.
At least this is what this bug
is all about. That RW open on
an R/O media keeps breaking
due to lack of the test.

**Comment by andrewbird** [comment]
I'll try to create a test this evening.

**Comment by stsp** [comment]
Another thing to test is whether the
0-sized read can be used for the
check of FD validity and EOF.
