### ISSUE TITLE
Tetris Classic timing issues

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#99]
WIth current GIT devel, Tetris Classic has timing issues making the game extremely easy to play.
It works correct with GIT master. A bisect gives:
5ee681aa114f003132bba3b6710bbb2f1e7fb014 is the first bad commit
commit 5ee681aa114f003132bba3b6710bbb2f1e7fb014
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Oct 24 17:41:16 2015 +0300

    pic: remove pic_iret() and all the surrounding stuff (half of pic.c code)
    
    DPMI now uses a different protection technique.
    The hope is, all those hacks are not needed any more.
    Some hacks, like pic_watch(), are left, but greatly simplified.
    
    This needs lots of testing!

:040000 040000 e9687fd5c514358f91fe3a43583ab48cb6190e9e f02ffe8a55eaf3d5b37367cace476385569554b4 M      src

More info about the game:
http://www.abandonia.com/en/games/914/Tetris+Classic.html

**Comment by stsp** [comment]
This is a bug in the game.
You can fix it with the simple binary patch:

TETRISC.EXE
0000EDC3: FB 90

But fixing it on dosemu side is exceptionally difficult,
unless to revert the patch...

**Comment by stsp** [comment]
I added the horrible (but 1-liner) work-around.
I don't know how much will it break, but restoring
the huge old hack is what I don't want to do either.
I'd like to try the small game-specific hacks instead,
but this may lead to the complete mayhem. We'll see...
I actually think we should not compete with dosbox
where dosbox is a clear winner. We should instead
concentrate on what dosbox is not for.

**Comment by jschwartzenberg** [comment]
Yep, makes sense. If the hacks become too much, maybe EMUfailure could be updated with your bug fix for this game and maybe there will be similar more of such cases.
Currently DOSEMU's OPL3 emulation is much better oob than DOSBox's btw.

**Comment by stsp** [comment]
> maybe EMUfailure could be updated with your bug fix for this game

My fear is that because of this "fix" the
EMUfailure should now be updated for many
other things too, that previously worked fine. It is
very scare and I don't know what will it break.
Multiplied to the same breaking effect of removing
the original hack, I am very scared.

> Currently DOSEMU's OPL3 emulation is much better oob than DOSBox's btw.

DOSBox has 2 OPL3 emulators.
I tested both and took the best, then applied just
a couple of patches of my own. This is still a
dosbox-stolen code, which was in turn stolen
from adlibemu project and patched. You can
activate that OPL in dosbox by some config option.

**Comment by stsp** [comment]
https://github.com/stsp/dosemu2/blob/devel/src/base/dev/sb16/opl.c

See the fresh dosbox copyrights.

**Comment by stsp** [comment]
https://github.com/stsp/dosemu2/blob/devel/src/base/dev/sb16/dbadlib.c

**Comment by jschwartzenberg** [comment]
Yep, but somehow ootb, the one in DOSBox sounds really bad with a lot of strange bleebs through the sounds. In DOSEMU I experience zero problems. Maybe the version you took from DOSBox is newer than what's in their latest release (which is also quite old already).

It'd be nice if DOSEMU could copy/learn from DOSBox's VGA emulation as well, it doesn't have the jerky scrolling issues that DOSEMU's has with Apogee games.

Are you aware of any programs specifically which would likely be affected by this fix that you did above now?

**Comment by stsp** [comment]
> Yep, but somehow ootb, the one in DOSBox sounds really bad

See above: in dosbox you can select either via config.

> It'd be nice if DOSEMU could copy/learn from DOSBox's VGA
> emulation as well, it doesn't have the jerky scrolling issues that
> DOSEMU's has with Apogee games.

dosemu's vga emulation is horribly written, but porting
the one from dosbox is not on the radar. At one point I
looked into qemu's code, but this would be quite hard
to port too. You can open the bug reports.
OTOH I am pretty sure dosemu2 has world's best sb16
implementation. :)

> Are you aware of any programs specifically which would
> likely be affected by this fix that you did above now?

Likely some multitaskers.
In any case, yesterday I soften the problem with yet another
hack. Hope it will not pop up.

**Comment by jschwartzenberg** [comment]
This issue is back with the latest Git, 201f1779045196011392492cb55c9b130098c46b.

**Comment by stsp** [comment]
Not confirming.
Tried both patched and unpatched versions
https://github.com/dosemu2/dosemu2/issues/99#issuecomment-155948289
and they are fine.
Made sure that commenting out
pic.c:446 have the desired effect
of getting the problem back for
the unpatched version.
So no.

**Comment by jschwartzenberg** [comment]
Thanks for checking! I did run into an odd performance issue earlier, but I cannot reproduce it now. Maybe you are right in the sense that dosemu is less suitable than dosbox for timing sensitive games. I might do some more testing.
