### ISSUE TITLE
PKZIP/PKUNZIP creashes DOSEMU2

### ISSUE THREAD

**Issue by Tubatstuff** [stsp/dosemu2#990]
Sounds like a DPMI issue again, but running PKZIP or PKUNZIP causes DOSEMU2 to exit without messages.   Using the -) switch disables 32-bit mode and both work normally.

**Comment by jharrison03** [comment]
I run these two programs regularly from batch events all day and don't see this problem.  DOSemu is using KVM.

What version of PKZIP is this?

[pkz250r.zip](https://github.com/stsp/dosemu2/files/4103369/pkz250r.zip)

**Comment by stsp** [comment]
Please attach the -D9+M log.
Please try `$_cpu_vm_dpmi="kvm"`.

**Comment by Tubatstuff** [comment]
I'm using a registered copy of 2.04c (12-28-92).

I'll get back to on the kvm-dpmi thing.

**Comment by jharrison03** [comment]
That's a very old Pkzip.  Try the 2.50.

**Comment by Tubatstuff** [comment]
Upgrading pkzip isn't an option; this is a registered corporate version (includes our signature in archives).  It's been running on Windows and DOS platforms since 1992.

Stas,  kvm is apparently installed and dosemu2 is using it according to the log.  Here's the boot log.
[boot_23jan20_1100.zip](https://github.com/stsp/dosemu2/files/4104960/boot_23jan20_1100.zip)
[pkz204c.zip](https://github.com/stsp/dosemu2/files/4104969/pkz204c.zip)

**Comment by stsp** [comment]
This is not a -D9+M log, the dosemu2 seems not
from git, and things like
`ERROR: emufs is too old, ver 3 need 4, but trying to continue`
suggest your installation is horribly messed up.

**Comment by jschwartzenberg** [comment]
It seems to hang here but not crash:
![image](https://user-images.githubusercontent.com/877112/73121264-b4ca3e80-3f78-11ea-84a5-7c4979a651ad.png)

**Comment by stsp** [comment]
Is this a regression?
