### ISSUE TITLE
MS-DOS EDIT from Windows 95 DOS Error 6

### ISSUE THREAD

**Issue by jharrison03** [stsp/dosemu2#991]
**Describe the bug**
Running MS-DOS EDIT.EXE version 0.9.019 from the Windows 95 DOS complains of an "Error 6" on startup when accessing EDIT.INI and EDIT.HLP.  The editor functions normally after these two error dialogs.

**To Reproduce**
Start EDIT.EXE 0.9.019.  Two error dialogs are observed, reporting "Error 6" when accessing EDIT.INI and EDIT.HLP., then the editor appears to function normally.  These errors occur if EDIT.EXE is executed from its home directory or from another location with EDIT.EXE in the DOS path.

**Attach the binaries or provide an URL**
[edit.zip](https://github.com/stsp/dosemu2/files/4103404/edit.zip)

**Attach the log**
[boot.log.zip](https://github.com/stsp/dosemu2/files/4103413/boot.log.zip)

**Comment by jharrison03** [comment]
FYI - This version of EDIT work normally before I synced a few days back.

**Comment by stsp** [comment]
I can't reproduce that.
Unpacked to `c:\edit` and started `edit.exe`.
Editor appears and no errors.

**Comment by andrewbird** [comment]
Same here, couldn't reproduce with supplied edit.zip and MS-DOS 6.22. I tried both with the files found in the current directory and by moving them into a directory on the path.

**Comment by andrewbird** [comment]
I think the boot.log is partial (due to log rotation), could you recreate it with debug options `-D+dRW`, please? Also which exact version of DOS are you using?

**Comment by jharrison03** [comment]
> I think the boot.log is partial (due to log rotation), could you recreate it with debug options `-D+dRW`, please? Also which exact version of DOS are you using?

[boot.log.zip](https://github.com/stsp/dosemu2/files/4109613/boot.log.zip)

**Comment by andrewbird** [comment]
Did you execute EDIT.EXE while capturing this log, I don't see any access for EDIT.EXE, EDIT.INI, or EDIT.HLP?

**Comment by jharrison03** [comment]
Yes.  I booted up, started EDIT.EXE, observed the two errors then quit the editor and shutdown DOSemu.

**Comment by jharrison03** [comment]
OK, I think it's not showing up through normal filesystem access because it's executing off a Netware drive.

Here's a log running EDIT.EXE from a local drive with no Netware loaded.

**Comment by andrewbird** [comment]
Okay I see findfirst/nexts for edit.??? and then open for edit.exe, but nothing that relates specifically to edit.ini or edit.hlp. Did you see the error when starting edit whilst running it from Dosemu's MFS drive?

**Comment by jharrison03** [comment]
Yes.  I get the error running EDIT.EXE from C:\UTILS (local drive).  No Netware client was loaded.

![editerr](https://user-images.githubusercontent.com/44394516/73091345-40c06580-3ea8-11ea-80da-2009dbbc9030.jpeg)

**Comment by andrewbird** [comment]
Could you add `#` to the debug flags please? i.e. `-D+dRW#`

**Comment by jharrison03** [comment]
> Could you add `#` to the debug flags please? i.e. `-D+dRW#`

[boot.log.zip](https://github.com/stsp/dosemu2/files/4109985/boot.log.zip)

**Comment by andrewbird** [comment]
Can you post your dosemu.conf, please? Do you have LFN disabled?

**Comment by andrewbird** [comment]
I've reproduced it now after turning off LFN support.

**Comment by andrewbird** [comment]
I'm seeing this sequence with LFN off
~~~
int 0x21, ax=0x1900                                                             
RET INT0xe6 eax=0x00001900 ebx=0x0000678c ss=0x1e0b esp=0x0000661a              
           ecx=0x00000000 edx=0x00000003 ds=0x1e0b  cs=0xf000 ip=0xf6ce         
           esi=0x000016be edi=0x0000af00 es=0x1e0b flg=0x00030046               
iret INT0x21 eax=0x00001902 ebx=0x0000678c ss=0x1e0b esp=0x00006628             
           ecx=0x00000000 edx=0x00000003 ds=0x1e0b  cs=0x1044 ip=0x2037         
           esi=0x000016be edi=0x0000af00 es=0x1e0b flg=0x000b0246               
int 0x21, ax=0x7147                                                             
RET INT0xe6 eax=0x00007147 ebx=0x0000678c ss=0x1e0b esp=0x0000661a              
           ecx=0x00000000 edx=0x00000003 ds=0x1e0b  cs=0xf000 ip=0xf6ce         
           esi=0x000016c1 edi=0x0000af00 es=0x1e0b flg=0x00030046               
iret INT0x21 eax=0x00007100 ebx=0x0000678c ss=0x1e0b esp=0x00006628             
           ecx=0x00000000 edx=0x00000003 ds=0x1e0b  cs=0x1044 ip=0x2056         
           esi=0x000016c1 edi=0x0000af00 es=0x1e0b flg=0x000b0246               
int 0x21, ax=0x7143                                                             
RET INT0xe6 eax=0x00007143 ebx=0x00006500 ss=0x1e0b esp=0x00006528              
           ecx=0x00000000 edx=0x0000653e ds=0x1e0b  cs=0xf000 ip=0xf6ce         
           esi=0x00000000 edi=0x000015ae es=0x1e0b flg=0x00030046               
iret INT0x21 eax=0x00007100 ebx=0x00006500 ss=0x1e0b esp=0x00006536             
           ecx=0x00000000 edx=0x0000653e ds=0x1e0b  cs=0x1044 ip=0x219e         
           esi=0x00000000 edi=0x000015ae es=0x1e0b flg=0x000b0246               
int 0x21, ax=0x716c                                                             
RET INT0xe6 eax=0x0000716c ebx=0x00000040 ss=0x1e0b esp=0x0000650c              
           ecx=0x00000000 edx=0x00000001 ds=0x1e0b  cs=0xf000 ip=0xf6ce         
           esi=0x0000653e edi=0x000015ae es=0x1e0b flg=0x00030046               
iret INT0x21 eax=0x00007100 ebx=0x00000040 ss=0x1e0b esp=0x0000651a             
           ecx=0x00000000 edx=0x00000001 ds=0x1e0b  cs=0x1044 ip=0x20ad         
           esi=0x0000653e edi=0x000015ae es=0x1e0b flg=0x000b0246               
int 0x21, ax=0x3f28                                                             
RET INT0xe6 eax=0x00003f28 ebx=0x00007100 ss=0x1e0b esp=0x00006506              
           ecx=0x000000c0 edx=0x000040d0 ds=0x1e0b  cs=0xf000 ip=0xf6ce         
           esi=0x000000c0 edi=0x00006642 es=0x1e0b flg=0x00030046               
iret INT0x21 eax=0x00000006 ebx=0x00007100 ss=0x1e0b esp=0x00006514             
           ecx=0x000000c0 edx=0x000040d0 ds=0x1e0b  cs=0x1044 ip=0x2179         
           esi=0x000000c0 edi=0x00006642 es=0x1e0b flg=0x000b0247               
~~~

So it seems that int21 / 716c return AX=7100 to indicate no lfn support but doesn't set the carry flag (not sure if it should), then the read is attempted with BX handle 0x7100 (presumably AX from previous call). Seems odd that EDIT should continue to use LFN calls when it's been told that LFN is unsupported. Also I wonder why this has changed recently?

**Comment by andrewbird** [comment]
During bisect (not complete yet!) on a good commit I can see in the log that after an `int 21/71a0` no further int 21/71xx calls are made i.e. the above sequence is all done with SFN calls, so presumably something changed in its return value or flags.

**Comment by jharrison03** [comment]
Yes.  LFN is off.  

[dosemurc.zip](https://github.com/stsp/dosemu2/files/4112923/dosemurc.zip)

**Comment by andrewbird** [comment]
$ git bisect good
30ac30357713faa65747a0f616d716780623dc76 is the first bad commit

**Comment by andrewbird** [comment]
Testing on Win95 which has its own LFN skeleton (booted as DOS with FAT filesystem) shows that CARRY flag should be set along with AX=7100 to indicate lack of LFN support.
~~~
int 0x21, ax=0x71a0                                                             
RET INT0xe6 eax=0x000071a0 ebx=0x00000000 ss=0x9055 esp=0x0000ddec              
           ecx=0x00000000 edx=0x0000e2df ds=0x9055  cs=0xf000 ip=0xf6ce         
           esi=0x0000e2df edi=0x0000d195 es=0x9055 flg=0x00034046               
iret INT0x21 eax=0x00007100 ebx=0x00000000 ss=0x9055 esp=0x0000ddfa             
           ecx=0x00000000 edx=0x0000e2df ds=0x9055  cs=0x9055 ip=0x454a         
           esi=0x0000e2df edi=0x0000d195 es=0x9055 flg=0x000b4247               
~~~

So it looks to me that the CARRY flag set below is being lost when Dosemu provides the LFN service.
https://github.com/stsp/dosemu2/blob/94f09985e399f77ab9f842afcbb71a3357c4c87b/src/base/core/int.c#L1749-L1769

**Comment by stsp** [comment]
Maybe the caller sets it and we lose
it somewhere?

**Comment by stsp** [comment]
IIRC you should set CF on error, but not
on "unsupported"?

**Comment by andrewbird** [comment]
> IIRC you should set CF on error, but not
on "unsupported"?

I wasn't sure about that, but from my experiments it seems
- Win95 in real DOS mode returns AX=7100 + CF set for FAT drive with int21 / 71a0
- Win95's edit.exe continues to use the AX value as file handle when int21 / 7160 returns AX=7100 without CF set.

**Comment by stsp** [comment]
But can you confirm that CF is actually set
rather than preserved? Otherwise I don't quite
understand where the regression came from.
Did we use to set it before that patch?

**Comment by andrewbird** [comment]
So I've now added a 'CLC' just before the interrupt in my test and can confirm that Win95 in real DOS mode sets CF with AX=7100, when it doesn't support LFN.
```asm
dosdebug> t
system state: emulated,stopped
AX=71a0  BX=0000  CX=0020  DX=01e6  SI=0000  DI=01c2  SP=fffe  BP=0000
DS=15e1  ES=15e1  FS=0000  GS=0000  FL=000b7306
CS:IP=15e1:0118       SS:SP=15e1:fffe

15e1:0118 F8               clc

dosdebug> t
system state: emulated,stopped
AX=71a0  BX=0000  CX=0020  DX=01e6  SI=0000  DI=01c2  SP=fffe  BP=0000
DS=15e1  ES=15e1  FS=0000  GS=0000  FL=000b7306
CS:IP=15e1:0119       SS:SP=15e1:fffe

15e1:0119 CD21             int  21

dosdebug> t
INT 0x21, system state: emulated,stopped
AX=71a0  BX=0000  CX=0020  DX=01e6  SI=0000  DI=01c2  SP=fffe  BP=0000
DS=15e1  ES=15e1  FS=0000  GS=0000  FL=000b7306
CS:IP=15e1:0119       SS:SP=15e1:fffe

15e1:0119 CD21             int  21

dosdebug> t
system state: emulated,stopped
AX=7100  BX=0000  CX=0020  DX=01e6  SI=0000  DI=01c2  SP=fffe  BP=0000
DS=15e1  ES=15e1  FS=0000  GS=0000  FL=000b7347
CS:IP=15e1:011b       SS:SP=15e1:fffe

15e1:011b 7236             jc   0153 ($+36)
```

**Comment by andrewbird** [comment]
Here's the test program and source, if you want to try it out: [t1.zip](https://github.com/stsp/dosemu2/files/4115172/t1.zip).

Run it as `lfnsuppt` and it tries to get the LFN volume info from the current drive.
Will print one of four results:
~~~
  1/ Operation Success(filesystem type) # CF not set and filesystem type has been returned
  2/ Carry Not Set But No Filesystem Type
  3/ Carry Set                          # but AX not 0x7100
  4/ Not Supported(AX=0x7100)           # with CF set  
~~~

**Comment by stsp** [comment]
OK but where did the regression came from?
Did we also used to set CF but stopped?

**Comment by andrewbird** [comment]
I think the logic in Dosemu's LFN regarding CF is the same now as before the breakage, but it seems to me that we are losing flags somewhere. Git bisect indicates it was 30ac303 that broke things. I don't really understand exactly what's going on in that patch, but I guess the flags returned to the caller are not those generated from executing the interrupt, but this effect only seems to occur in the case that the DOS itself does not service the int21/71a0 but it falls through to Dosemu2.

**Comment by stsp** [comment]
Thanks, tracking the problem to CF was helpful.
Should now be fixed.

**Comment by andrewbird** [comment]
So that seems mostly good as it fixes the original problem, but it seems there are cases where I see
"Carry Not Set But No Filesystem Type", this may be a logic problem in LFN code that your proper flag handling has uncovered. I'll try to get an understandable test case together.

**Comment by andrewbird** [comment]
So in this test case with MS-DOS 6.22 on MFS and Dosemu's LFN support on I don't see Dosemu's LFN called.
~~~
int_rvc 0x21 setup                                                              
int 0x21, ax=0x71a0                                                             
RET INT0xe6 eax=0x000071a0 ebx=0x00000000 ss=0x1039 esp=0x0000fff0              
           ecx=0x00000020 edx=0x000001e5 ds=0x1039  cs=0xf000 ip=0xf6ce         
           esi=0x00000100 edi=0x000001c1 es=0x1039 flg=0x00030047               
iret INT0x21 eax=0x00007100 ebx=0x00000000 ss=0x1039 esp=0x0000fffe             
           ecx=0x00000020 edx=0x000001e5 ds=0x1039  cs=0x1039 ip=0x011a         
           esi=0x00000100 edi=0x000001c1 es=0x1039 flg=0x000b0282               
~~~

if I place an `stc` in the call before int21/71a0 it works as expected.

~~~
int_rvc 0x21 setup                                                              
int 0x21, ax=0x71a0                                                             
RET INT0xe6 eax=0x000071a0 ebx=0x00000000 ss=0x1039 esp=0x0000fff0              
           ecx=0x00000020 edx=0x000001e6 ds=0x1039  cs=0xf000 ip=0xf6ce         
           esi=0x00000100 edi=0x000001c2 es=0x1039 flg=0x00030047               
int_rvc 0x21, doing second revect call                                          
int_rvc 0x21 call for ax=0x7100 71a0                                            
LFN: doing LFN!, AX=71a0 DL=e6                                                  
LFN: build_posix_path: D:\                                                      
truename(D:\)                                                                   
MFS: is_msdos_device                                                            
SUBSTing from: D:\                                                              
Absolute logical path: "D:\"                                                    
MFS: dos_fs: build_ufs_path for DOS path 'D:\'                                  
MFS: dos_gen: ufs '/clients/common/dosemu2.git/test-imagedir/dXXXXs/d/', path '\', l=51
MFS: dos_gen: path_to_ufs '/clients/common/dosemu2.git/test-imagedir/dXXXXs/d//'
MFS: dos_fs: build_ufs_path result is '/clients/common/dosemu2.git/test-imagedir/dXXXXs/d/'
RET INT0xe6 eax=0x00000000 ebx=0x00004002 ss=0x1039 esp=0x0000ffe6              
           ecx=0x000000ff edx=0x00000104 ds=0x1039  cs=0xf000 ip=0xf72c         
           esi=0x00000100 edi=0x000001c2 es=0x1039 flg=0x000b0246               
iret INT0x21 eax=0x00000000 ebx=0x00004002 ss=0x1039 esp=0x0000fffe             
           ecx=0x000000ff edx=0x00000104 ds=0x1039  cs=0x1039 ip=0x011b         
           esi=0x00000100 edi=0x000001c2 es=0x1039 flg=0x000b0246               
~~~

It could be that my LFN tests are wrong if I should always place an `stc` before calling an int21/71xx if CF doesn't get set if the handler is missing. What do you think?

**Comment by stsp** [comment]
Ah, thanks, I think the patch was wrong!
Re-pushed. :(

**Comment by andrewbird** [comment]
Thanks, that fixed the failing Travis test and the OP's issue too. Locally I'm writing some more test cases and I still wonder about whether I need to `stc` before the int21/71xx in case nothing is there to handle it?

**Comment by stsp** [comment]
RBIL says you need that indeed, for compatibility
with pre-7 DOSes.
Of course we can handle it the 7-way (in fdpp).

**Comment by andrewbird** [comment]
Thanks for that, I looked in lots of places but never fully searched rbil.
