### ISSUE TITLE
Emulation of int 0x15, ax=0xe820 not correct.

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/dosemu2#995]
**Describe the bug**
The emulation of the interrupt is buggy. If register ECX contains a value > 20 when the interrupt is called, the function returns garbage after the first, successful call.

**To Reproduce**
The tool MEMSTAT.EXE, contained in the JemmEx/Jemm386 package demonstrates the error. It displays garbage and finally terminates with an exception 00.

**Attach the binaries or provide an URL**
https://github.com/Baron-von-Riedesel/Jemm/blob/master/bin/JEMM579B.zip

**Attach the log**
No log, but a patch for file int.c:

```C
	} else if (REG(eax) == 0xe820 && REG(edx) == 0x534d4150) {
	    REG(eax) = REG(edx);
	    if (REG(ebx) < system_memory_map_size) {
	//	REG(ecx) = max(REG(ecx), 20);
		REG(ecx) = min(REG(ecx), 20);
		if (REG(ebx) + REG(ecx) >= system_memory_map_size)
		    REG(ecx) = system_memory_map_size - REG(ebx);
		MEMCPY_2DOS(SEGOFF2LINEAR(_ES, _DI),
			    (char *) system_memory_map + REG(ebx),
			    REG(ecx));
	//	REG(ebx) += REG(ecx);
		REG(ebx) += 20;
	    } else
		REG(ecx) = 0;
	    if (REG(ebx) >= system_memory_map_size)
```

**Comment by Baron-von-Riedesel** [comment]
Apparently I'm not very familiar with github's "code" insertion. Sorry!

**Comment by andrewbird** [comment]
To avoid the line wrapping and indentation collapse, enclose the code block between triple backticks, if you add 'C' suffix to the first set it will syntax highlight too.

~~~
```C
code block
```
~~~

**Comment by stsp** [comment]
What value of ecx does it set,
and why doesn't it want the next
call be started from that value?

**Comment by Baron-von-Riedesel** [comment]
> What value of ecx does it set,

the tools sets ECX to 24

> and why doesn't it want the next
> call be started from that value?

because the ACPI docs state that one call is to return ONE row of the table:

_The address map is
returned through successive invocations of this interface; each returning information on a **single**
range of physical addresses._

**Comment by stsp** [comment]
Fair enough, RBIL says the same thing:
```
        a maximum of 20 bytes will be transferred at one time, even if ECX is
          higher; some BIOSes (e.g. Award Modular BIOS v4.50PG) ignore the
          value of ECX on entry, and always copy 20 bytes
```

**Comment by stsp** [comment]
Should now be fixed, please check.
